import { HSKList } from "@src/tools/types";

const lesson: HSKList = {
  list: "1-2",
  content: [
    {
      simplified: "我",
      traditional: "我",
      pinyin: "wǒ",
      english: "I, me",
      english_alternate_choices: ["We, us", "He, him", "You", "She, her"],
    },
    {
      simplified: "我们",
      traditional: "我們",
      pinyin: "wǒmen",
      english: "We, us",
      english_alternate_choices: ["She, her", "You", "I, me", "He, him"],
    },
    {
      simplified: "你",
      traditional: "你",
      pinyin: "nǐ",
      english: "You",
      english_alternate_choices: ["I, me", "He, him", "She, her", "We, us"],
    },
    {
      simplified: "你们",
      traditional: "你們",
      pinyin: "nǐmen",
      english: "You (pl.)",
      english_alternate_choices: ["I, me", "He, him", "She, her", "We, us"],
    },
    {
      simplified: "他",
      traditional: "他",
      pinyin: "tā",
      english: "He, him",
      english_alternate_choices: ["I, me", "You", "She, her", "We, us"],
    },
    {
      simplified: "她",
      traditional: "她",
      pinyin: "tā",
      english: "She, her",
      english_alternate_choices: ["I, me", "You", "He, him", "We, us"],
    },
    {
      simplified: "他们",
      traditional: "他們",
      pinyin: "tāmen",
      english: "They (male+female)",
      english_alternate_choices: ["I, me", "She, her", "He, him", "We, us"],
    },
    {
      simplified: "她们",
      traditional: "她們",
      pinyin: "tāmen",
      english: "They (females)",
      english_alternate_choices: ["I, me", "She, her", "He, him", "We, us"],
    },
    {
      simplified: "这",
      traditional: "這",
      pinyin: "zhè",
      english: "Here, this",
      english_alternate_choices: [""],
    },
    {
      simplified: "那",
      traditional: "那",
      pinyin: "nà",
      english: "There, that",
      english_alternate_choices: [""],
    },
    {
      simplified: "哪",
      traditional: "哪",
      pinyin: "nǎ",
      english: "Where",
      english_alternate_choices: [""],
    },
    {
      simplified: "谁",
      traditional: "誰",
      pinyin: "shéi",
      english: "Who",
      english_alternate_choices: [""],
    },
    {
      simplified: "什么",
      traditional: "什麼",
      pinyin: "shénme",
      english: "What, why",
      english_alternate_choices: [""],
    },
    {
      simplified: "多少",
      traditional: "多少",
      pinyin: "duōshǎo",
      english: "How many, how much",
      english_alternate_choices: [""],
    },
    {
      simplified: "几",
      traditional: "幾",
      pinyin: "jǐ",
      english: "A few, how many",
      english_alternate_choices: [""],
    },
    {
      simplified: "怎么",
      traditional: "怎麼",
      pinyin: "zěnme",
      english: "How",
      english_alternate_choices: [""],
    },
    {
      simplified: "怎么样",
      traditional: "怎麼樣",
      pinyin: "zěnmeyàng",
      english: "How about",
      english_alternate_choices: [""],
    },
    {
      simplified: "它",
      traditional: "它",
      pinyin: "tā",
      english: "It",
      english_alternate_choices: [""],
    },
    {
      simplified: "大家",
      traditional: "大家",
      pinyin: "dàjiā",
      english: "Everyone",
      english_alternate_choices: [""],
    },
    {
      simplified: "每",
      traditional: "每",
      pinyin: "měi",
      english: "Every",
      english_alternate_choices: [""],
    },
    {
      simplified: "为什么",
      traditional: "為什麼",
      pinyin: "wèishénme",
      english: "Why",
      english_alternate_choices: [""],
    },
    {
      simplified: "一",
      traditional: "一",
      pinyin: "yī",
      english: "One",
      english_alternate_choices: [""],
    },
    {
      simplified: "二",
      traditional: "二",
      pinyin: "èr",
      english: "Two",
      english_alternate_choices: [""],
    },
    {
      simplified: "三",
      traditional: "三",
      pinyin: "sān",
      english: "Three",
      english_alternate_choices: [""],
    },
    {
      simplified: "四",
      traditional: "四",
      pinyin: "sì",
      english: "Four",
      english_alternate_choices: [""],
    },
    {
      simplified: "五",
      traditional: "五",
      pinyin: "wǔ",
      english: "Five",
      english_alternate_choices: [""],
    },
    {
      simplified: "六",
      traditional: "六",
      pinyin: "liù",
      english: "Six",
      english_alternate_choices: [""],
    },
    {
      simplified: "七",
      traditional: "七",
      pinyin: "qī",
      english: "Seven",
      english_alternate_choices: [""],
    },
    {
      simplified: "八",
      traditional: "八",
      pinyin: "bā",
      english: "Eight",
      english_alternate_choices: [""],
    },
    {
      simplified: "九",
      traditional: "九",
      pinyin: "jiǔ",
      english: "Nine",
      english_alternate_choices: [""],
    },
    {
      simplified: "十",
      traditional: "十",
      pinyin: "shí",
      english: "Ten",
      english_alternate_choices: [""],
    },
    {
      simplified: "零",
      traditional: "零",
      pinyin: "líng",
      english: "Zero",
      english_alternate_choices: [""],
    },
    {
      simplified: "两",
      traditional: "兩",
      pinyin: "liǎng",
      english: "Two (alt.)",
      english_alternate_choices: [""],
    },
    {
      simplified: "百",
      traditional: "百",
      pinyin: "bǎi",
      english: "Hundred",
      english_alternate_choices: [""],
    },
    {
      simplified: "千",
      traditional: "千",
      pinyin: "qiān",
      english: "Thousand",
      english_alternate_choices: [""],
    },
    {
      simplified: "第一",
      traditional: "第一",
      pinyin: "dìyī",
      english: "First",
      english_alternate_choices: [""],
    },
    {
      simplified: "个",
      traditional: "個",
      pinyin: "gè",
      english: "One, a, an",
      english_alternate_choices: [""],
    },
    {
      simplified: "岁",
      traditional: "歲",
      pinyin: "suì",
      english: "Year",
      english_alternate_choices: [""],
    },
    {
      simplified: "本",
      traditional: "本",
      pinyin: "běn",
      english: "Volume",
      english_alternate_choices: [""],
    },
    {
      simplified: "些",
      traditional: "些",
      pinyin: "xiē",
      english: "Some",
      english_alternate_choices: [""],
    },
    {
      simplified: "块",
      traditional: "塊",
      pinyin: "kuài",
      english: "Piece, block, bit",
      english_alternate_choices: [""],
    },
    {
      simplified: "次",
      traditional: "次",
      pinyin: "cì",
      english: "Number",
      english_alternate_choices: [""],
    },
    {
      simplified: "公斤",
      traditional: "公斤",
      pinyin: "gōngjīn",
      english: "Kilogram",
      english_alternate_choices: [""],
    },
    {
      simplified: "元",
      traditional: "元",
      pinyin: "yuán",
      english: "Yuan",
      english_alternate_choices: [""],
    },
    {
      simplified: "件",
      traditional: "事",
      pinyin: "jiàn",
      english: "Piece, thing, fact, matter",
      english_alternate_choices: [""],
    },
    {
      simplified: "张",
      traditional: "張",
      pinyin: "zhāng",
      english: "Sheet",
      english_alternate_choices: [""],
    },
    {
      simplified: "不",
      traditional: "不",
      pinyin: "bù",
      english: "No, do not",
      english_alternate_choices: [""],
    },
    {
      simplified: "没",
      traditional: "沒",
      pinyin: "méi",
      english: "No, not",
      english_alternate_choices: [""],
    },
    {
      simplified: "很",
      traditional: "很",
      pinyin: "hěn",
      english: "Quite, very",
      english_alternate_choices: [""],
    },
    {
      simplified: "太",
      traditional: "太",
      pinyin: "tài",
      english: "Too",
      english_alternate_choices: [""],
    },
    {
      simplified: "都",
      traditional: "都",
      pinyin: "dōu",
      english: "All",
      english_alternate_choices: [""],
    },
    {
      simplified: "别",
      traditional: "別",
      pinyin: "bié",
      english: "Other",
      english_alternate_choices: [""],
    },
    {
      simplified: "非常",
      traditional: "非常",
      pinyin: "fēicháng",
      english: "Very",
      english_alternate_choices: [""],
    },
    {
      simplified: "也",
      traditional: "也",
      pinyin: "yě",
      english: "Likewise",
      english_alternate_choices: [""],
    },
    {
      simplified: "还",
      traditional: "還",
      pinyin: "hái",
      english: "Still",
      english_alternate_choices: [""],
    },
    {
      simplified: "最",
      traditional: "最",
      pinyin: "zuì",
      english: "Most",
      english_alternate_choices: [""],
    },
    {
      simplified: "真",
      traditional: "真",
      pinyin: "zhēn",
      english: "Real",
      english_alternate_choices: [""],
    },
    {
      simplified: "正在",
      traditional: "正在",
      pinyin: "zhèngzài",
      english: "Be being",
      english_alternate_choices: [""],
    },
    {
      simplified: "已经",
      traditional: "已經",
      pinyin: "yǐjīng",
      english: "Already",
      english_alternate_choices: [""],
    },
    {
      simplified: "一起",
      traditional: "一起",
      pinyin: "yìqǐ",
      english: "Together",
      english_alternate_choices: [""],
    },
    {
      simplified: "再",
      traditional: "再",
      pinyin: "zài",
      english: "Again",
      english_alternate_choices: [""],
    },
    {
      simplified: "就",
      traditional: "就",
      pinyin: "jiǜ",
      english: "At once",
      english_alternate_choices: [""],
    },
    {
      simplified: "您",
      traditional: "您",
      pinyin: "nín",
      english: "You",
      english_alternate_choices: [""],
    },
    {
      simplified: "和",
      traditional: "和",
      pinyin: "hé",
      english: "And",
      english_alternate_choices: [""],
    },
    {
      simplified: "因为",
      traditional: "因為",
      pinyin: "yīnwèi",
      english: "Because",
      english_alternate_choices: [""],
    },
    {
      simplified: "所以",
      traditional: "所以",
      pinyin: "suǒyǐ",
      english: "So",
      english_alternate_choices: [""],
    },
    {
      simplified: "但是",
      traditional: "但是",
      pinyin: "dànshì",
      english: "But",
      english_alternate_choices: [""],
    },
    {
      simplified: "在",
      traditional: "在",
      pinyin: "zài",
      english: "In, at",
      english_alternate_choices: [""],
    },
    {
      simplified: "从",
      traditional: "從",
      pinyin: "cóng",
      english: "From",
      english_alternate_choices: [""],
    },
    {
      simplified: "对",
      traditional: "對",
      pinyin: "duì",
      english: "Right",
      english_alternate_choices: [""],
    },
    {
      simplified: "此",
      traditional: "此",
      pinyin: "cǐ",
      english: "This",
      english_alternate_choices: [""],
    },
    {
      simplified: "向",
      traditional: "向",
      pinyin: "xiàng",
      english: "Towards",
      english_alternate_choices: [""],
    },
    {
      simplified: "离",
      traditional: "離",
      pinyin: "lí",
      english: "Leave",
      english_alternate_choices: [""],
    },
    {
      simplified: "喂",
      traditional: "餵",
      pinyin: "wèi",
      english: "Hello",
      english_alternate_choices: [""],
    },
    {
      simplified: "家",
      traditional: "家",
      pinyin: "jiā",
      english: "Home",
      english_alternate_choices: [""],
    },
    {
      simplified: "学校",
      traditional: "學校",
      pinyin: "xuéxiào",
      english: "School",
      english_alternate_choices: [""],
    },
    {
      simplified: "饭馆",
      traditional: "飯館",
      pinyin: "fàndiàn",
      english: "Restaunt",
      english_alternate_choices: [""],
    },
    {
      simplified: "商店",
      traditional: "商店",
      pinyin: "shāngdiàn",
      english: "Store",
      english_alternate_choices: [""],
    },
    {
      simplified: "医院",
      traditional: "醫院",
      pinyin: "yīyuàn",
      english: "Hospital",
      english_alternate_choices: [""],
    },
    {
      simplified: "火车站",
      traditional: "火車站",
      pinyin: "huǒchēzhàn",
      english: "Train station",
      english_alternate_choices: [""],
    },
    {
      simplified: "中国",
      traditional: "中國",
      pinyin: "Zhōngguó",
      english: "China",
      english_alternate_choices: [""],
    },
    {
      simplified: "机场",
      traditional: "機場",
      pinyin: "jīchǎng",
      english: "Airport",
      english_alternate_choices: [""],
    },
    {
      simplified: "教室",
      traditional: "教室",
      pinyin: "jiàoshì",
      english: "Classroom",
      english_alternate_choices: [""],
    },
    {
      simplified: "房间",
      traditional: "房間",
      pinyin: "fángjiān",
      english: "Room",
      english_alternate_choices: [""],
    },
    {
      simplified: "路",
      traditional: "路",
      pinyin: "lù",
      english: "Road",
      english_alternate_choices: [""],
    },
    {
      simplified: "北京",
      traditional: "北京",
      pinyin: "Běijīng",
      english: "Beijing",
      english_alternate_choices: [""],
    },
    {
      simplified: "上",
      traditional: "上",
      pinyin: "shàng",
      english: "Up",
      english_alternate_choices: [""],
    },
    {
      simplified: "下",
      traditional: "下",
      pinyin: "xià",
      english: "Below",
      english_alternate_choices: [""],
    },
    {
      simplified: "前面",
      traditional: "前面",
      pinyin: "qiánmiàn",
      english: "Front",
      english_alternate_choices: [""],
    },
    {
      simplified: "后面",
      traditional: "後面",
      pinyin: "hòumiàn",
      english: "Behind",
      english_alternate_choices: [""],
    },
    {
      simplified: "左边",
      traditional: "左邊",
      pinyin: "zuǒbiān",
      english: "Left",
      english_alternate_choices: [""],
    },
    {
      simplified: "右边",
      traditional: "右邊",
      pinyin: "yòubiān",
      english: "Right",
      english_alternate_choices: [""],
    },
    {
      simplified: "外",
      traditional: "外",
      pinyin: "wài",
      english: "Out",
      english_alternate_choices: [""],
    },
    {
      simplified: "旁边",
      traditional: "旁邊",
      pinyin: "pángbiān",
      english: "Side",
      english_alternate_choices: [""],
    },
    {
      simplified: "里",
      traditional: "裡",
      pinyin: "lǐ",
      english: "Inside",
      english_alternate_choices: [""],
    },
    {
      simplified: "今天",
      traditional: "今天",
      pinyin: "jīntiān",
      english: "Today",
      english_alternate_choices: [""],
    },
    {
      simplified: "明天",
      traditional: "明天",
      pinyin: "míngtiān",
      english: "Tomorrow",
      english_alternate_choices: [""],
    },
    {
      simplified: "昨天",
      traditional: "昨天",
      pinyin: "zuótiān",
      english: "Yesterday",
      english_alternate_choices: [""],
    },
    {
      simplified: "上午",
      traditional: "上午",
      pinyin: "shàngwǔ",
      english: "Morning",
      english_alternate_choices: [""],
    },
    {
      simplified: "中午",
      traditional: "中午",
      pinyin: "zhōngwǔ",
      english: "Noon",
      english_alternate_choices: [""],
    },
    {
      simplified: "下午",
      traditional: "下午",
      pinyin: "xiàwǔ",
      english: "Afternoon",
      english_alternate_choices: [""],
    },
    {
      simplified: "年",
      traditional: "年",
      pinyin: "nián",
      english: "Year",
      english_alternate_choices: [""],
    },
    {
      simplified: "月",
      traditional: "月",
      pinyin: "yuè",
      english: "Month",
      english_alternate_choices: [""],
    },
    {
      simplified: "日",
      traditional: "日",
      pinyin: "rì",
      english: "Day",
      english_alternate_choices: [""],
    },
    {
      simplified: "星期",
      traditional: "星期",
      pinyin: "xīngqī",
      english: "Week",
      english_alternate_choices: [""],
    },
    {
      simplified: "点",
      traditional: "點",
      pinyin: "diǎn",
      english: "Dot, spot",
      english_alternate_choices: [""],
    },
    {
      simplified: "分钟",
      traditional: "分鐘",
      pinyin: "fēnzhōng",
      english: "Minute",
      english_alternate_choices: [""],
    },
    {
      simplified: "现在",
      traditional: "現在",
      pinyin: "xiànzài",
      english: "Now",
      english_alternate_choices: [""],
    },
    {
      simplified: "时候",
      traditional: "時候",
      pinyin: "shíhou",
      english: "Time, moment",
      english_alternate_choices: [""],
    },
    {
      simplified: "早上",
      traditional: "早上",
      pinyin: "zǎoshàng",
      english: "Morning, morrow",
      english_alternate_choices: [""],
    },
    {
      simplified: "晚上",
      traditional: "晚上",
      pinyin: "wǎnshàng",
      english: "Night",
      english_alternate_choices: [""],
    },
    {
      simplified: "小时",
      traditional: "小時",
      pinyin: "xiǎoshí",
      english: "Hour",
      english_alternate_choices: [""],
    },
    {
      simplified: "时间",
      traditional: "時間",
      pinyin: "shíjiān",
      english: "Time, period",
      english_alternate_choices: [""],
    },
    {
      simplified: "去年",
      traditional: "去年",
      pinyin: "qùnián",
      english: "Last year",
      english_alternate_choices: [""],
    },
    {
      simplified: "号",
      traditional: "號",
      pinyin: "hào",
      english: "Number",
      english_alternate_choices: [""],
    },
    {
      simplified: "生日",
      traditional: "生日",
      pinyin: "shēngrì",
      english: "Birthday",
      english_alternate_choices: [""],
    },
    {
      simplified: "爸爸",
      traditional: "爸爸",
      pinyin: "bàba",
      english: "Father",
      english_alternate_choices: [""],
    },
    {
      simplified: "妈妈",
      traditional: "媽媽",
      pinyin: "māma",
      english: "Mother",
      english_alternate_choices: [""],
    },
    {
      simplified: "儿子",
      traditional: "兒子",
      pinyin: "érzi",
      english: "Son",
      english_alternate_choices: [""],
    },
    {
      simplified: "女儿",
      traditional: "女兒",
      pinyin: "nǚ'ér",
      english: "Daughter",
      english_alternate_choices: [""],
    },
    {
      simplified: "老师",
      traditional: "老師",
      pinyin: "lǎoshī",
      english: "Teacher",
      english_alternate_choices: [""],
    },
    {
      simplified: "学生",
      traditional: "學生",
      pinyin: "xuéshēng",
      english: "Student",
      english_alternate_choices: [""],
    },
    {
      simplified: "同学",
      traditional: "同學",
      pinyin: "tóngxué",
      english: "Shoolmate",
      english_alternate_choices: [""],
    },
    {
      simplified: "朋友",
      traditional: "朋友",
      pinyin: "péngyǒu",
      english: "Friend",
      english_alternate_choices: [""],
    },
    {
      simplified: "医生",
      traditional: "醫生",
      pinyin: "yīshēng",
      english: "Doctor",
      english_alternate_choices: [""],
    },
    {
      simplified: "先生",
      traditional: "先生",
      pinyin: "xiānsheng",
      english: "Sir",
      english_alternate_choices: [""],
    },
    {
      simplified: "小姐",
      traditional: "小姐",
      pinyin: "xiǎojiě",
      english: "Miss",
      english_alternate_choices: [""],
    },
    {
      simplified: "哥哥",
      traditional: "哥哥",
      pinyin: "gēge",
      english: "Older brother",
      english_alternate_choices: [""],
    },
    {
      simplified: "姐姐",
      traditional: "姐姐",
      pinyin: "jiějie",
      english: "Older sister",
      english_alternate_choices: [""],
    },
    {
      simplified: "弟弟",
      traditional: "弟弟",
      pinyin: "dìdi",
      english: "Younger brother",
      english_alternate_choices: [""],
    },
    {
      simplified: "妹妹",
      traditional: "妹妹",
      pinyin: "mèimei",
      english: "Younger sister",
      english_alternate_choices: [""],
    },
    {
      simplified: "丈夫",
      traditional: "丈夫",
      pinyin: "zhàngfu",
      english: "Husband",
      english_alternate_choices: [""],
    },
    {
      simplified: "妻子",
      traditional: "妻子",
      pinyin: "qīzi",
      english: "Wife",
      english_alternate_choices: [""],
    },
    {
      simplified: "孩子",
      traditional: "孩子",
      pinyin: "háizi",
      english: "Child",
      english_alternate_choices: [""],
    },
    {
      simplified: "男人",
      traditional: "男人",
      pinyin: "nánrén",
      english: "Man",
      english_alternate_choices: [""],
    },
    {
      simplified: "女人",
      traditional: "女人",
      pinyin: "nǚrén",
      english: "Woman",
      english_alternate_choices: [""],
    },
    {
      simplified: "服务员",
      traditional: "服務員",
      pinyin: "fúwùyuán",
      english: "Waiter",
      english_alternate_choices: [""],
    },
    {
      simplified: "衣服",
      traditional: "衣服",
      pinyin: "yīfu",
      english: "Cloth",
      english_alternate_choices: [""],
    },
    {
      simplified: "水",
      traditional: "水",
      pinyin: "shuǐ",
      english: "Water",
      english_alternate_choices: [""],
    },
    {
      simplified: "菜",
      traditional: "菜",
      pinyin: "cài",
      english: "Dish",
      english_alternate_choices: [""],
    },
    {
      simplified: "米饭",
      traditional: "米飯",
      pinyin: "mǐfàn",
      english: "Rice",
      english_alternate_choices: [""],
    },
    {
      simplified: "水果",
      traditional: "水果",
      pinyin: "shuǐguǒ",
      english: "Fruit",
      english_alternate_choices: [""],
    },
    {
      simplified: "苹果",
      traditional: "蘋果",
      pinyin: "píngguǒ",
      english: "Apple",
      english_alternate_choices: [""],
    },
    {
      simplified: "茶",
      traditional: "茶",
      pinyin: "chá",
      english: "Tea",
      english_alternate_choices: [""],
    },
    {
      simplified: "杯子",
      traditional: "杯子",
      pinyin: "bēizi",
      english: "Cup",
      english_alternate_choices: [""],
    },
    {
      simplified: "钱",
      traditional: "錢",
      pinyin: "qián",
      english: "Money",
      english_alternate_choices: [""],
    },
    {
      simplified: "飞机",
      traditional: "飛機",
      pinyin: "fēijī",
      english: "Airplane",
      english_alternate_choices: [""],
    },
    {
      simplified: "出租车",
      traditional: "出租車",
      pinyin: "chūzūchē",
      english: "Taxi",
      english_alternate_choices: [""],
    },
    {
      simplified: "电视",
      traditional: "電視",
      pinyin: "diànshì",
      english: "Television",
      english_alternate_choices: [""],
    },
    {
      simplified: "电脑",
      traditional: "電腦",
      pinyin: "diànnǎo",
      english: "Computer",
      english_alternate_choices: [""],
    },
    {
      simplified: "电影",
      traditional: "電影",
      pinyin: "diànyǐng",
      english: "Movie",
      english_alternate_choices: [""],
    },
    {
      simplified: "天气",
      traditional: "天氣",
      pinyin: "tiānqì",
      english: "Weather",
      english_alternate_choices: [""],
    },
    {
      simplified: "猫",
      traditional: "貓",
      pinyin: "māo",
      english: "Cat",
      english_alternate_choices: [""],
    },
    {
      simplified: "狗",
      traditional: "狗",
      pinyin: "gǒu",
      english: "Dog",
      english_alternate_choices: [""],
    },
    {
      simplified: "东西",
      traditional: "東西",
      pinyin: "dōngxi",
      english: "Thing",
      english_alternate_choices: [""],
    },
    {
      simplified: "鱼",
      traditional: "魚",
      pinyin: "yú",
      english: "Fish",
      english_alternate_choices: [""],
    },
    {
      simplified: "羊肉",
      traditional: "羊肉",
      pinyin: "yángròu",
      english: "Mutton",
      english_alternate_choices: [""],
    },
    {
      simplified: "牛奶",
      traditional: "牛奶",
      pinyin: "niúnǎi",
      english: "Milk",
      english_alternate_choices: [""],
    },
    {
      simplified: "鸡蛋",
      traditional: "雞蛋",
      pinyin: "jīdàn",
      english: "Egg",
      english_alternate_choices: [""],
    },
    {
      simplified: "西瓜",
      traditional: "西瓜",
      pinyin: "xīguā",
      english: "Watermelon",
      english_alternate_choices: [""],
    },
    {
      simplified: "咖啡",
      traditional: "咖啡",
      pinyin: "kāfēi",
      english: "Coffee",
      english_alternate_choices: [""],
    },
    {
      simplified: "自行车",
      traditional: "自行車",
      pinyin: "zìxíngchē",
      english: "Bike",
      english_alternate_choices: [""],
    },
    {
      simplified: "船",
      traditional: "船",
      pinyin: "chuán",
      english: "Boat",
      english_alternate_choices: [""],
    },
    {
      simplified: "雪",
      traditional: "雪",
      pinyin: "xuě",
      english: "Snow",
      english_alternate_choices: [""],
    },
    {
      simplified: "药",
      traditional: "藥",
      pinyin: "yào",
      english: "Medicine",
      english_alternate_choices: [""],
    },
    {
      simplified: "手机",
      traditional: "手機",
      pinyin: "shǒujī",
      english: "Cellphone",
      english_alternate_choices: [""],
    },
    {
      simplified: "手表",
      traditional: "手錶",
      pinyin: "shǒubiǎo",
      english: "Watch",
      english_alternate_choices: [""],
    },
    {
      simplified: "眼睛",
      traditional: "眼睛",
      pinyin: "yǎnjīng",
      english: "Eye",
      english_alternate_choices: [""],
    },
    {
      simplified: "身体",
      traditional: "身體",
      pinyin: "shēntǐ",
      english: "Body",
      english_alternate_choices: [""],
    },
    {
      simplified: "公共汽车",
      traditional: "公共汽車",
      pinyin: "gōnggòngqìchē",
      english: "Bus",
      english_alternate_choices: [""],
    },
    {
      simplified: "报纸",
      traditional: "報紙",
      pinyin: "bàozhǐ",
      english: "Newspaper",
      english_alternate_choices: [""],
    },
    {
      simplified: "人",
      traditional: "人",
      pinyin: "rén",
      english: "Person",
      english_alternate_choices: [""],
    },
    {
      simplified: "名字",
      traditional: "名字",
      pinyin: "míngzì",
      english: "Name",
      english_alternate_choices: [""],
    },
    {
      simplified: "书",
      traditional: "書",
      pinyin: "shū",
      english: "Book",
      english_alternate_choices: [""],
    },
    {
      simplified: "汉语",
      traditional: "漢語",
      pinyin: "hànyǔ",
      english: "Chinese",
      english_alternate_choices: [""],
    },
    {
      simplified: "字",
      traditional: "字",
      pinyin: "zì",
      english: "Character",
      english_alternate_choices: [""],
    },
    {
      simplified: "桌子",
      traditional: "桌子",
      pinyin: "zhuōzi",
      english: "Desk",
      english_alternate_choices: [""],
    },
    {
      simplified: "椅子",
      traditional: "椅子",
      pinyin: "yǐzi",
      english: "Chair",
      english_alternate_choices: [""],
    },
    {
      simplified: "门",
      traditional: "門",
      pinyin: "mén",
      english: "Door",
      english_alternate_choices: [""],
    },
    {
      simplified: "题",
      traditional: "題",
      pinyin: "tí",
      english: "Topic",
      english_alternate_choices: [""],
    },
    {
      simplified: "课",
      traditional: "課",
      pinyin: "kè",
      english: "Lesson",
      english_alternate_choices: [""],
    },
    {
      simplified: "姓",
      traditional: "姓",
      pinyin: "xìng",
      english: "Surname",
      english_alternate_choices: [""],
    },
    {
      simplified: "问题",
      traditional: "問題",
      pinyin: "wèntí",
      english: "Question",
      english_alternate_choices: [""],
    },
    {
      simplified: "事情",
      traditional: "事情",
      pinyin: "shìqing",
      english: "Matter",
      english_alternate_choices: [""],
    },
    {
      simplified: "考试",
      traditional: "考試",
      pinyin: "kǎoshì",
      english: "Exam",
      english_alternate_choices: [""],
    },
    {
      simplified: "票",
      traditional: "票",
      pinyin: "piào",
      english: "Ticket",
      english_alternate_choices: [""],
    },
    {
      simplified: "意思",
      traditional: "意思",
      pinyin: "yìsi",
      english: "Meaning",
      english_alternate_choices: [""],
    },
    {
      simplified: "颜色",
      traditional: "顏色",
      pinyin: "yánsè",
      english: "Color",
      english_alternate_choices: [""],
    },
    {
      simplified: "谢谢",
      traditional: "謝謝",
      pinyin: "xièxie",
      english: "Thank",
      english_alternate_choices: [""],
    },
    {
      simplified: "不客气",
      traditional: "不客氣",
      pinyin: "búkèqì",
      english: "You are welcome",
      english_alternate_choices: [""],
    },
    {
      simplified: "再见",
      traditional: "再見",
      pinyin: "zàijiàn",
      english: "Good-bye",
      english_alternate_choices: [""],
    },
    {
      simplified: "请",
      traditional: "請",
      pinyin: "qǐng",
      english: "Please",
      english_alternate_choices: [""],
    },
    {
      simplified: "对不起",
      traditional: "對不起",
      pinyin: "duìbùqǐ",
      english: "Sorry",
      english_alternate_choices: [""],
    },
    {
      simplified: "没关系",
      traditional: "沒關係",
      pinyin: "méiguānxi",
      english: "It doesn't matter",
      english_alternate_choices: [""],
    },
    {
      simplified: "欢迎",
      traditional: "歡迎",
      pinyin: "huānyíng",
      english: "Welcome",
      english_alternate_choices: [""],
    },
    {
      simplified: "是",
      traditional: "是",
      pinyin: "shì",
      english: "Am, is, are",
      english_alternate_choices: [""],
    },
    {
      simplified: "有",
      traditional: "有",
      pinyin: "yǒu",
      english: "Have",
      english_alternate_choices: [""],
    },
    {
      simplified: "看",
      traditional: "看",
      pinyin: "kàn",
      english: "Look",
      english_alternate_choices: [""],
    },
    {
      simplified: "听",
      traditional: "聽",
      pinyin: "tīng",
      english: "Listen",
      english_alternate_choices: [""],
    },
    {
      simplified: "说话",
      traditional: "說話",
      pinyin: "shuōhuà",
      english: "Speak",
      english_alternate_choices: [""],
    },
    {
      simplified: "读",
      traditional: "讀",
      pinyin: "dú",
      english: "Read",
      english_alternate_choices: [""],
    },
    {
      simplified: "写",
      traditional: "寫",
      pinyin: "xiě",
      english: "Write",
      english_alternate_choices: [""],
    },
    {
      simplified: "看见",
      traditional: "看見",
      pinyin: "kànjiàn",
      english: "See",
      english_alternate_choices: [""],
    },
    {
      simplified: "叫",
      traditional: "叫",
      pinyin: "jiào",
      english: "Call",
      english_alternate_choices: [""],
    },
    {
      simplified: "来",
      traditional: "來",
      pinyin: "lái",
      english: "Come",
      english_alternate_choices: [""],
    },
    {
      simplified: "回",
      traditional: "時",
      pinyin: "huí",
      english: "Return",
      english_alternate_choices: [""],
    },
    {
      simplified: "去",
      traditional: "去",
      pinyin: "qù",
      english: "Go",
      english_alternate_choices: [""],
    },
    {
      simplified: "吃",
      traditional: "吃",
      pinyin: "chī",
      english: "Eat",
      english_alternate_choices: [""],
    },
    {
      simplified: "喝",
      traditional: "喝",
      pinyin: "hē",
      english: "Drink",
      english_alternate_choices: [""],
    },
    {
      simplified: "睡觉",
      traditional: "睡覺",
      pinyin: "shuìjiào",
      english: "Sleep",
      english_alternate_choices: [""],
    },
    {
      simplified: "认识",
      traditional: "認識",
      pinyin: "rènshi",
      english: "Know",
      english_alternate_choices: [""],
    },
    {
      simplified: "打电话",
      traditional: "打電話",
      pinyin: "dǎdiànhuà",
      english: "Call up",
      english_alternate_choices: [""],
    },
    {
      simplified: "做",
      traditional: "做",
      pinyin: "zuò",
      english: "Do",
      english_alternate_choices: [""],
    },
    {
      simplified: "高兴",
      traditional: "高興",
      pinyin: "gāoxìng",
      english: "Happy",
      english_alternate_choices: [""],
    },
    {
      simplified: "买",
      traditional: "買",
      pinyin: "mǎi",
      english: "Buy",
      english_alternate_choices: [""],
    },
    {
      simplified: "开",
      traditional: "開",
      pinyin: "kāi",
      english: "Open",
      english_alternate_choices: [""],
    },
    {
      simplified: "坐",
      traditional: "坐",
      pinyin: "zuò",
      english: "Sit",
      english_alternate_choices: [""],
    },
    {
      simplified: "住",
      traditional: "住",
      pinyin: "zhù",
      english: "Live",
      english_alternate_choices: [""],
    },
    {
      simplified: "学习",
      traditional: "學習",
      pinyin: "xuéxí",
      english: "Study",
      english_alternate_choices: [""],
    },
    {
      simplified: "工作",
      traditional: "工作",
      pinyin: "gōngzuò",
      english: "Work",
      english_alternate_choices: [""],
    },
    {
      simplified: "下雨",
      traditional: "下雨",
      pinyin: "xiàyǔ",
      english: "Rain",
      english_alternate_choices: [""],
    },
    {
      simplified: "问",
      traditional: "問",
      pinyin: "wèn",
      english: "Ask",
      english_alternate_choices: [""],
    },
    {
      simplified: "走",
      traditional: "走",
      pinyin: "zǒu",
      english: "Walk",
      english_alternate_choices: [""],
    },
    {
      simplified: "进",
      traditional: "進",
      pinyin: "jìn",
      english: "Enter",
      english_alternate_choices: [""],
    },
    {
      simplified: "出",
      traditional: "出",
      pinyin: "chū",
      english: "Come",
      english_alternate_choices: [""],
    },
    {
      simplified: "跑步",
      traditional: "跑步",
      pinyin: "pǎobù",
      english: "Run",
      english_alternate_choices: [""],
    },
    {
      simplified: "到",
      traditional: "到",
      pinyin: "dào",
      english: "Arrive",
      english_alternate_choices: [""],
    },
    {
      simplified: "穿",
      traditional: "穿",
      pinyin: "chuān",
      english: "Wear",
      english_alternate_choices: [""],
    },
    {
      simplified: "洗",
      traditional: "洗",
      pinyin: "xǐ",
      english: "Wash",
      english_alternate_choices: [""],
    },
    {
      simplified: "给",
      traditional: "給",
      pinyin: "gěi",
      english: "Give",
      english_alternate_choices: [""],
    },
    {
      simplified: "找",
      traditional: "找",
      pinyin: "zhǎo",
      english: "Find",
      english_alternate_choices: [""],
    },
    {
      simplified: "懂",
      traditional: "懂",
      pinyin: "dǒng",
      english: "Understand",
      english_alternate_choices: [""],
    },
    {
      simplified: "笑",
      traditional: "笑",
      pinyin: "xiào",
      english: "Smile",
      english_alternate_choices: [""],
    },
    {
      simplified: "回答",
      traditional: "回答",
      pinyin: "huídá",
      english: "Answer",
      english_alternate_choices: [""],
    },
    {
      simplified: "告诉",
      traditional: "告訴",
      pinyin: "gàosù",
      english: "Tell",
      english_alternate_choices: [""],
    },
    {
      simplified: "准备",
      traditional: "準備",
      pinyin: "zhǔnbèi",
      english: "Prepare",
      english_alternate_choices: [""],
    },
    {
      simplified: "开始",
      traditional: "開始",
      pinyin: "kāishǐ",
      english: "Begin",
      english_alternate_choices: [""],
    },
    {
      simplified: "介绍",
      traditional: "介紹",
      pinyin: "jièshào",
      english: "Introduce",
      english_alternate_choices: [""],
    },
    {
      simplified: "帮助",
      traditional: "幫助",
      pinyin: "bāngzhù",
      english: "Help",
      english_alternate_choices: [""],
    },
    {
      simplified: "玩",
      traditional: "玩",
      pinyin: "wán",
      english: "Play",
      english_alternate_choices: [""],
    },
    {
      simplified: "送",
      traditional: "送",
      pinyin: "sòng",
      english: "Present",
      english_alternate_choices: [""],
    },
    {
      simplified: "等",
      traditional: "等",
      pinyin: "děng",
      english: "Wait",
      english_alternate_choices: [""],
    },
    {
      simplified: "让",
      traditional: "讓",
      pinyin: "ràng",
      english: "Let",
      english_alternate_choices: [""],
    },
    {
      simplified: "起床",
      traditional: "起床",
      pinyin: "qǐchuáng",
      english: "Get up",
      english_alternate_choices: [""],
    },
    {
      simplified: "唱歌",
      traditional: "唱歌",
      pinyin: "chànggē",
      english: "Sing",
      english_alternate_choices: [""],
    },
    {
      simplified: "跳舞",
      traditional: "跳舞",
      pinyin: "tiàowǔ",
      english: "Dance",
      english_alternate_choices: [""],
    },
    {
      simplified: "旅游",
      traditional: "旅遊",
      pinyin: "lǚyóu",
      english: "Travel",
      english_alternate_choices: [""],
    },
    {
      simplified: "上班",
      traditional: "上班",
      pinyin: "shàngbān",
      english: "Be on duty",
      english_alternate_choices: [""],
    },
    {
      simplified: "生病",
      traditional: "生病",
      pinyin: "shēngbìng",
      english: "Fall ill",
      english_alternate_choices: [""],
    },
    {
      simplified: "休息",
      traditional: "休息",
      pinyin: "xiūxi",
      english: "Rest",
      english_alternate_choices: [""],
    },
    {
      simplified: "运动",
      traditional: "運動",
      pinyin: "yùndòng",
      english: "Exercise",
      english_alternate_choices: [""],
    },
    {
      simplified: "游泳",
      traditional: "游泳",
      pinyin: "yóuyǒng",
      english: "Swim",
      english_alternate_choices: [""],
    },
    {
      simplified: "踢足球",
      traditional: "踢足球",
      pinyin: "tīzúqiú",
      english: "Play footbal",
      english_alternate_choices: [""],
    },
    {
      simplified: "打篮球",
      traditional: "打籃球",
      pinyin: "dǎlánqiú",
      english: "Play basketball",
      english_alternate_choices: [""],
    },
    {
      simplified: "完",
      traditional: "完",
      pinyin: "wán",
      english: "Finish",
      english_alternate_choices: [""],
    },
    {
      simplified: "爱",
      traditional: "愛",
      pinyin: "ài",
      english: "Love",
      english_alternate_choices: [""],
    },
    {
      simplified: "喜欢",
      traditional: "喜歡",
      pinyin: "xǐhuān",
      english: "Love, like",
      english_alternate_choices: [""],
    },
    {
      simplified: "想",
      traditional: "想",
      pinyin: "xiǎng",
      english: "Want",
      english_alternate_choices: [""],
    },
    {
      simplified: "觉得",
      traditional: "覺得",
      pinyin: "juédé",
      english: "Think",
      english_alternate_choices: [""],
    },
    {
      simplified: "知道",
      traditional: "知道",
      pinyin: "zhīdao",
      english: "Know",
      english_alternate_choices: [""],
    },
    {
      simplified: "希望",
      traditional: "希望",
      pinyin: "xīwàng",
      english: "Hope",
      english_alternate_choices: [""],
    },
    {
      simplified: "能",
      traditional: "能",
      pinyin: "néng",
      english: "Can, be able to",
      english_alternate_choices: [""],
    },
    {
      simplified: "可以",
      traditional: "可以",
      pinyin: "kěyǐ",
      english: "Can",
      english_alternate_choices: [""],
    },
    {
      simplified: "要",
      traditional: "要",
      pinyin: "yào",
      english: "Ask for",
      english_alternate_choices: [""],
    },
    {
      simplified: "可能",
      traditional: "可能",
      pinyin: "kěnéng",
      english: "May",
      english_alternate_choices: [""],
    },
    {
      simplified: "好",
      traditional: "好",
      pinyin: "hǎo",
      english: "Good",
      english_alternate_choices: [""],
    },
    {
      simplified: "大",
      traditional: "大",
      pinyin: "dà",
      english: "Big",
      english_alternate_choices: [""],
    },
    {
      simplified: "小",
      traditional: "小",
      pinyin: "xiǎo",
      english: "Small",
      english_alternate_choices: [""],
    },
    {
      simplified: "多",
      traditional: "多",
      pinyin: "duō",
      english: "Many, much",
      english_alternate_choices: [""],
    },
    {
      simplified: "少",
      traditional: "少",
      pinyin: "shǎo",
      english: "Few, little",
      english_alternate_choices: [""],
    },
    {
      simplified: "冷",
      traditional: "冷",
      pinyin: "lěng",
      english: "Cold",
      english_alternate_choices: [""],
    },
    {
      simplified: "热",
      traditional: "熱",
      pinyin: "rè",
      english: "Hot",
      english_alternate_choices: [""],
    },
    {
      simplified: "漂亮",
      traditional: "漂亮",
      pinyin: "piàoliang",
      english: "Beautiful",
      english_alternate_choices: [""],
    },
    {
      simplified: "高",
      traditional: "高",
      pinyin: "gāo",
      english: "Tall",
      english_alternate_choices: [""],
    },
    {
      simplified: "红",
      traditional: "紅",
      pinyin: "hóng",
      english: "Red",
      english_alternate_choices: [""],
    },
    {
      simplified: "白",
      traditional: "白",
      pinyin: "bái",
      english: "White",
      english_alternate_choices: [""],
    },
    {
      simplified: "黑",
      traditional: "黑",
      pinyin: "hēi",
      english: "Black",
      english_alternate_choices: [""],
    },
    {
      simplified: "忙",
      traditional: "忙",
      pinyin: "máng",
      english: "Busy",
      english_alternate_choices: [""],
    },
    {
      simplified: "快",
      traditional: "快",
      pinyin: "kuài",
      english: "Fast",
      english_alternate_choices: [""],
    },
    {
      simplified: "慢",
      traditional: "慢",
      pinyin: "màn",
      english: "Slow",
      english_alternate_choices: [""],
    },
    {
      simplified: "远",
      traditional: "遠",
      pinyin: "yuǎn",
      english: "Far",
      english_alternate_choices: [""],
    },
    {
      simplified: "近",
      traditional: "近",
      pinyin: "jìn",
      english: "Close",
      english_alternate_choices: [""],
    },
    {
      simplified: "好吃",
      traditional: "好吃",
      pinyin: "hǎochī",
      english: "Delicioous",
      english_alternate_choices: [""],
    },
    {
      simplified: "累",
      traditional: "累",
      pinyin: "lèi",
      english: "Tired",
      english_alternate_choices: [""],
    },
    {
      simplified: "长",
      traditional: "長",
      pinyin: "cháng",
      english: "Long",
      english_alternate_choices: [""],
    },
    {
      simplified: "新",
      traditional: "新",
      pinyin: "xīn",
      english: "New",
      english_alternate_choices: [""],
    },
    {
      simplified: "贵",
      traditional: "貴",
      pinyin: "guì",
      english: "Expensive",
      english_alternate_choices: [""],
    },
    {
      simplified: "便宜",
      traditional: "便宜",
      pinyin: "piányi",
      english: "Cheap",
      english_alternate_choices: [""],
    },
    {
      simplified: "晴",
      traditional: "晴",
      pinyin: "qíng",
      english: "Fine",
      english_alternate_choices: [""],
    },
    {
      simplified: "阴",
      traditional: "陰",
      pinyin: "yīn",
      english: "Cloudy",
      english_alternate_choices: [""],
    },
    {
      simplified: "错",
      traditional: "錯",
      pinyin: "cuò",
      english: "Wrong",
      english_alternate_choices: [""],
    },
    {
      simplified: "快乐",
      traditional: "快樂",
      pinyin: "kuàilè",
      english: "Happy",
      english_alternate_choices: [""],
    },
    {
      simplified: "会",
      traditional: "會",
      pinyin: "huì",
      english: "Can",
      english_alternate_choices: [""],
    },

    {
      simplified: "打鸡血",
      traditional: "打雞血",
      pinyin: "dǎ jī xuè",
      english: "Become excited",
      english_alternate_choices: [""],
    },
    {
      simplified: "萌萌哒",
      traditional: "萌萌噠",
      pinyin: "méng méng dá",
      english: "Cute or adorable",
      english_alternate_choices: [""],
    },
    {
      simplified: "老板",
      traditional: "老闆",
      pinyin: "lǎobǎn",
      english: "Boss",
      english_alternate_choices: [""],
    },
    {
      simplified: "辣眼睛",
      traditional: "辣眼睛",
      pinyin: "là yǎnjīng",
      english: "Spicy eyes (an eyesore)",
      english_alternate_choices: [""],
    },
    {
      simplified: "方了",
      traditional: "方了",
      pinyin: "fāngle",
      english: "To panic",
      english_alternate_choices: [""],
    },
    {
      simplified: "接地气",
      traditional: "接地氣",
      pinyin: "Jiēdì qì",
      english: "Down to Earth",
      english_alternate_choices: [""],
    },
    {
      simplified: "一脸懵逼",
      traditional: "一臉懵逼",
      pinyin: "yī liǎn měng bī",
      english: "To feel completely lost",
      english_alternate_choices: [""],
    },
  ],
};

export default lesson;
