import { HSKList } from "@src/tools/types";

const lesson: HSKList = {
  list: "1-2",
  content: [
    {
      simplified: "我",
      traditional: "我",
      pinyin: "wǒ",
      english: "I, me",
      english_alternate_choices: [""],
    },
    {
      simplified: "我们",
      traditional: "我們",
      pinyin: "wǒmen",
      english: "we, us (pl.)",
      english_alternate_choices: [""],
    },
    {
      simplified: "你",
      traditional: "你",
      pinyin: "nǐ",
      english: "you",
      english_alternate_choices: [""],
    },
    {
      simplified: "你们",
      traditional: "你們",
      pinyin: "nǐmen",
      english: "you (pl.)",
      english_alternate_choices: [""],
    },
    {
      simplified: "他",
      traditional: "他",
      pinyin: "tā",
      english: "he, him",
      english_alternate_choices: [""],
    },
    {
      simplified: "她",
      traditional: "她",
      pinyin: "tā",
      english: "she, her",
      english_alternate_choices: [""],
    },
    {
      simplified: "他们",
      traditional: "他們",
      pinyin: "tāmen",
      english: "they (male+female / male，pl.)",
      english_alternate_choices: [""],
    },
    {
      simplified: "她们",
      traditional: "她們",
      pinyin: "tāmen",
      english: "they (females, pl.)",
      english_alternate_choices: [""],
    },
    {
      simplified: "这",
      traditional: "這",
      pinyin: "zhè",
      english: "here, this",
      english_alternate_choices: [""],
    },
    {
      simplified: "那",
      traditional: "那",
      pinyin: "nà",
      english: "there, that",
      english_alternate_choices: [""],
    },
    {
      simplified: "哪",
      traditional: "哪",
      pinyin: "nǎ",
      english: "where",
      english_alternate_choices: [""],
    },
    {
      simplified: "谁",
      traditional: "誰",
      pinyin: "shéi",
      english: "who",
      english_alternate_choices: [""],
    },
    {
      simplified: "什么",
      traditional: "什麼",
      pinyin: "shénme",
      english: "what, why",
      english_alternate_choices: [""],
    },
    {
      simplified: "多少",
      traditional: "多少",
      pinyin: "duōshǎo",
      english: "how many, how much",
      english_alternate_choices: [""],
    },
    {
      simplified: "几",
      traditional: "幾",
      pinyin: "jǐ",
      english: "a few, how many",
      english_alternate_choices: [""],
    },
    {
      simplified: "怎么",
      traditional: "怎麼",
      pinyin: "zěnme",
      english: "how",
      english_alternate_choices: [""],
    },
    {
      simplified: "怎么样",
      traditional: "怎麼樣",
      pinyin: "zěnmeyàng",
      english: "how about",
      english_alternate_choices: [""],
    },
    {
      simplified: "您",
      traditional: "您",
      pinyin: "nín",
      english: "you",
      english_alternate_choices: [""],
    },
    {
      simplified: "它",
      traditional: "它",
      pinyin: "tā",
      english: "it",
      english_alternate_choices: [""],
    },
    {
      simplified: "大家",
      traditional: "大家",
      pinyin: "dàjiā",
      english: "everyone",
      english_alternate_choices: [""],
    },
    {
      simplified: "每",
      traditional: "每",
      pinyin: "měi",
      english: "every",
      english_alternate_choices: [""],
    },
    {
      simplified: "为什么",
      traditional: "為什麼",
      pinyin: "wèishénme",
      english: "why",
      english_alternate_choices: [""],
    },
    {
      simplified: "一",
      traditional: "一",
      pinyin: "yī",
      english: "one",
      english_alternate_choices: [""],
    },
    {
      simplified: "二",
      traditional: "二",
      pinyin: "èr",
      english: "two",
      english_alternate_choices: [""],
    },
    {
      simplified: "三",
      traditional: "三",
      pinyin: "sān",
      english: "three",
      english_alternate_choices: [""],
    },
    {
      simplified: "四",
      traditional: "四",
      pinyin: "sì",
      english: "four",
      english_alternate_choices: [""],
    },
    {
      simplified: "五",
      traditional: "五",
      pinyin: "wǔ",
      english: "five",
      english_alternate_choices: [""],
    },
    {
      simplified: "六",
      traditional: "六",
      pinyin: "liù",
      english: "six",
      english_alternate_choices: [""],
    },
    {
      simplified: "七",
      traditional: "七",
      pinyin: "qī",
      english: "seven",
      english_alternate_choices: [""],
    },
    {
      simplified: "八",
      traditional: "八",
      pinyin: "bā",
      english: "eight",
      english_alternate_choices: [""],
    },
    {
      simplified: "九",
      traditional: "九",
      pinyin: "jiǔ",
      english: "nine",
      english_alternate_choices: [""],
    },
    {
      simplified: "十",
      traditional: "十",
      pinyin: "shí",
      english: "ten",
      english_alternate_choices: [""],
    },
    {
      simplified: "零",
      traditional: "零",
      pinyin: "líng",
      english: "zero",
      english_alternate_choices: [""],
    },
    {
      simplified: "两",
      traditional: "兩",
      pinyin: "liǎng",
      english: "two (alt.)",
      english_alternate_choices: [""],
    },
    {
      simplified: "百",
      traditional: "百",
      pinyin: "bǎi",
      english: "hundred",
      english_alternate_choices: [""],
    },
    {
      simplified: "千",
      traditional: "千",
      pinyin: "qiān",
      english: "thousand",
      english_alternate_choices: [""],
    },
    {
      simplified: "第一",
      traditional: "第一",
      pinyin: "dìyī",
      english: "first",
      english_alternate_choices: [""],
    },
    {
      simplified: "个",
      traditional: "個",
      pinyin: "gè",
      english: "one, a, an",
      english_alternate_choices: [""],
    },
    {
      simplified: "岁",
      traditional: "歲",
      pinyin: "suì",
      english: "year",
      english_alternate_choices: [""],
    },
    {
      simplified: "本",
      traditional: "本",
      pinyin: "běn",
      english: "volume",
      english_alternate_choices: [""],
    },
    {
      simplified: "些",
      traditional: "些",
      pinyin: "xiē",
      english: "some",
      english_alternate_choices: [""],
    },
    {
      simplified: "块",
      traditional: "塊",
      pinyin: "kuài",
      english: "piece",
      english_alternate_choices: [""],
    },
    {
      simplified: "次",
      traditional: "次",
      pinyin: "cì",
      english: "number",
      english_alternate_choices: [""],
    },
    {
      simplified: "公斤",
      traditional: "公斤",
      pinyin: "gōngjīn",
      english: "kilogram",
      english_alternate_choices: [""],
    },
    {
      simplified: "元",
      traditional: "元",
      pinyin: "yuán",
      english: "yuan",
      english_alternate_choices: [""],
    },
    {
      simplified: "件",
      traditional: "事",
      pinyin: "jiàn",
      english: "piece",
      english_alternate_choices: [""],
    },
    {
      simplified: "张",
      traditional: "張",
      pinyin: "zhāng",
      english: "sheet",
      english_alternate_choices: [""],
    },
    {
      simplified: "不",
      traditional: "不",
      pinyin: "bù",
      english: "no",
      english_alternate_choices: [""],
    },
    {
      simplified: "没",
      traditional: "沒",
      pinyin: "méi",
      english: "no",
      english_alternate_choices: [""],
    },
    {
      simplified: "很",
      traditional: "很",
      pinyin: "hěn",
      english: "quite, very",
      english_alternate_choices: [""],
    },
    {
      simplified: "太",
      traditional: "太",
      pinyin: "tài",
      english: "too",
      english_alternate_choices: [""],
    },
    {
      simplified: "都",
      traditional: "都",
      pinyin: "dōu",
      english: "all",
      english_alternate_choices: [""],
    },
    {
      simplified: "别",
      traditional: "別",
      pinyin: "bié",
      english: "other",
      english_alternate_choices: [""],
    },
    {
      simplified: "非常",
      traditional: "非常",
      pinyin: "fēicháng",
      english: "very",
      english_alternate_choices: [""],
    },
    {
      simplified: "也",
      traditional: "也",
      pinyin: "yě",
      english: "likewise",
      english_alternate_choices: [""],
    },
    {
      simplified: "还",
      traditional: "還",
      pinyin: "hái",
      english: "still",
      english_alternate_choices: [""],
    },
    {
      simplified: "最",
      traditional: "最",
      pinyin: "zuì",
      english: "most",
      english_alternate_choices: [""],
    },
    {
      simplified: "真",
      traditional: "真",
      pinyin: "zhēn",
      english: "real",
      english_alternate_choices: [""],
    },
    {
      simplified: "正在",
      traditional: "正在",
      pinyin: "zhèngzài",
      english: "be being",
      english_alternate_choices: [""],
    },
    {
      simplified: "已经",
      traditional: "已經",
      pinyin: "yǐjīng",
      english: "already",
      english_alternate_choices: [""],
    },
    {
      simplified: "一起",
      traditional: "一起",
      pinyin: "yìqǐ",
      english: "together",
      english_alternate_choices: [""],
    },
    {
      simplified: "再",
      traditional: "再",
      pinyin: "zài",
      english: "again",
      english_alternate_choices: [""],
    },
    {
      simplified: "就",
      traditional: "就",
      pinyin: "jiǜ",
      english: "at once",
      english_alternate_choices: [""],
    },
    {
      simplified: "和",
      traditional: "和",
      pinyin: "hé",
      english: "and",
      english_alternate_choices: [""],
    },
    {
      simplified: "因为",
      traditional: "因為",
      pinyin: "yīnwèi",
      english: "because",
      english_alternate_choices: [""],
    },
    {
      simplified: "所以",
      traditional: "所以",
      pinyin: "suǒyǐ",
      english: "so",
      english_alternate_choices: [""],
    },
    {
      simplified: "但是",
      traditional: "但是",
      pinyin: "dànshì",
      english: "but",
      english_alternate_choices: [""],
    },
    {
      simplified: "在",
      traditional: "在",
      pinyin: "zài",
      english: "in, at",
      english_alternate_choices: [""],
    },
    {
      simplified: "从",
      traditional: "從",
      pinyin: "cóng",
      english: "from",
      english_alternate_choices: [""],
    },
    {
      simplified: "对",
      traditional: "對",
      pinyin: "duì",
      english: "right",
      english_alternate_choices: [""],
    },
    {
      simplified: "此",
      traditional: "此",
      pinyin: "cǐ",
      english: "this",
      english_alternate_choices: [""],
    },
    {
      simplified: "向",
      traditional: "向",
      pinyin: "xiàng",
      english: "towards",
      english_alternate_choices: [""],
    },
    {
      simplified: "离",
      traditional: "離",
      pinyin: "lí",
      english: "leave",
      english_alternate_choices: [""],
    },
    {
      simplified: "喂",
      traditional: "餵",
      pinyin: "wèi",
      english: "hello",
      english_alternate_choices: [""],
    },
    {
      simplified: "家",
      traditional: "家",
      pinyin: "jiā",
      english: "home",
      english_alternate_choices: [""],
    },
    {
      simplified: "学校",
      traditional: "學校",
      pinyin: "xuéxiào",
      english: "school",
      english_alternate_choices: [""],
    },
    {
      simplified: "饭馆",
      traditional: "飯館",
      pinyin: "fàndiàn",
      english: "restaunt",
      english_alternate_choices: [""],
    },
    {
      simplified: "商店",
      traditional: "商店",
      pinyin: "shāngdiàn",
      english: "store",
      english_alternate_choices: [""],
    },
    {
      simplified: "医院",
      traditional: "醫院",
      pinyin: "yīyuàn",
      english: "hospital",
      english_alternate_choices: [""],
    },
    {
      simplified: "火车站",
      traditional: "火車站",
      pinyin: "huǒchēzhàn",
      english: "train station",
      english_alternate_choices: [""],
    },
    {
      simplified: "中国",
      traditional: "中國",
      pinyin: "Zhōngguó",
      english: "China",
      english_alternate_choices: [""],
    },
    {
      simplified: "机场",
      traditional: "機場",
      pinyin: "jīchǎng",
      english: "airport",
      english_alternate_choices: [""],
    },
    {
      simplified: "教室",
      traditional: "教室",
      pinyin: "jiàoshì",
      english: "classroom",
      english_alternate_choices: [""],
    },
    {
      simplified: "房间",
      traditional: "房間",
      pinyin: "fángjiān",
      english: "room",
      english_alternate_choices: [""],
    },
    {
      simplified: "路",
      traditional: "路",
      pinyin: "lù",
      english: "road",
      english_alternate_choices: [""],
    },
    {
      simplified: "北京",
      traditional: "北京",
      pinyin: "Běijīng",
      english: "Beijing",
      english_alternate_choices: [""],
    },
    {
      simplified: "上",
      traditional: "上",
      pinyin: "shàng",
      english: "up",
      english_alternate_choices: [""],
    },
    {
      simplified: "下",
      traditional: "下",
      pinyin: "xià",
      english: "below",
      english_alternate_choices: [""],
    },
    {
      simplified: "前面",
      traditional: "前面",
      pinyin: "qiánmiàn",
      english: "front",
      english_alternate_choices: [""],
    },
    {
      simplified: "后面",
      traditional: "後面",
      pinyin: "hòumiàn",
      english: "behind",
      english_alternate_choices: [""],
    },
    {
      simplified: "左边",
      traditional: "左邊",
      pinyin: "zuǒbiān",
      english: "left",
      english_alternate_choices: [""],
    },
    {
      simplified: "右边",
      traditional: "右邊",
      pinyin: "yòubiān",
      english: "right",
      english_alternate_choices: [""],
    },
    {
      simplified: "外",
      traditional: "外",
      pinyin: "wài",
      english: "out",
      english_alternate_choices: [""],
    },
    {
      simplified: "旁边",
      traditional: "旁邊",
      pinyin: "pángbiān",
      english: "side",
      english_alternate_choices: [""],
    },
    {
      simplified: "里",
      traditional: "裡",
      pinyin: "lǐ",
      english: "inside",
      english_alternate_choices: [""],
    },
    {
      simplified: "今天",
      traditional: "今天",
      pinyin: "jīntiān",
      english: "today",
      english_alternate_choices: [""],
    },
    {
      simplified: "明天",
      traditional: "明天",
      pinyin: "míngtiān",
      english: "tomorrow",
      english_alternate_choices: [""],
    },
    {
      simplified: "昨天",
      traditional: "昨天",
      pinyin: "zuótiān",
      english: "yesterday",
      english_alternate_choices: [""],
    },
    {
      simplified: "上午",
      traditional: "上午",
      pinyin: "shàngwǔ",
      english: "morning",
      english_alternate_choices: [""],
    },
    {
      simplified: "中午",
      traditional: "中午",
      pinyin: "zhōngwǔ",
      english: "noon",
      english_alternate_choices: [""],
    },
    {
      simplified: "下午",
      traditional: "下午",
      pinyin: "xiàwǔ",
      english: "afternoon",
      english_alternate_choices: [""],
    },
    {
      simplified: "年",
      traditional: "年",
      pinyin: "nián",
      english: "year",
      english_alternate_choices: [""],
    },
    {
      simplified: "月",
      traditional: "月",
      pinyin: "yuè",
      english: "month",
      english_alternate_choices: [""],
    },
    {
      simplified: "日",
      traditional: "日",
      pinyin: "rì",
      english: "day",
      english_alternate_choices: [""],
    },
    {
      simplified: "星期",
      traditional: "星期",
      pinyin: "xīngqī",
      english: "week",
      english_alternate_choices: [""],
    },
    {
      simplified: "点",
      traditional: "點",
      pinyin: "diǎn",
      english: "dot, spot",
      english_alternate_choices: [""],
    },
    {
      simplified: "分钟",
      traditional: "分鐘",
      pinyin: "fēnzhōng",
      english: "minute",
      english_alternate_choices: [""],
    },
    {
      simplified: "现在",
      traditional: "現在",
      pinyin: "xiànzài",
      english: "now",
      english_alternate_choices: [""],
    },
    {
      simplified: "时候",
      traditional: "時候",
      pinyin: "shíhou",
      english: "time",
      english_alternate_choices: [""],
    },
    {
      simplified: "早上",
      traditional: "早上",
      pinyin: "zǎoshàng",
      english: "morning",
      english_alternate_choices: [""],
    },
    {
      simplified: "晚上",
      traditional: "晚上",
      pinyin: "wǎnshàng",
      english: "night",
      english_alternate_choices: [""],
    },
    {
      simplified: "小时",
      traditional: "小時",
      pinyin: "xiǎoshí",
      english: "hour",
      english_alternate_choices: [""],
    },
    {
      simplified: "时间",
      traditional: "時間",
      pinyin: "shíjiān",
      english: "time",
      english_alternate_choices: [""],
    },
    {
      simplified: "去年",
      traditional: "去年",
      pinyin: "qùnián",
      english: "last year",
      english_alternate_choices: [""],
    },
    {
      simplified: "号",
      traditional: "號",
      pinyin: "hào",
      english: "number",
      english_alternate_choices: [""],
    },
    {
      simplified: "生日",
      traditional: "生日",
      pinyin: "shēngrì",
      english: "birthday",
      english_alternate_choices: [""],
    },
    {
      simplified: "爸爸",
      traditional: "爸爸",
      pinyin: "bàba",
      english: "father",
      english_alternate_choices: [""],
    },
    {
      simplified: "妈妈",
      traditional: "媽媽",
      pinyin: "māma",
      english: "mother",
      english_alternate_choices: [""],
    },
    {
      simplified: "儿子",
      traditional: "兒子",
      pinyin: "érzi",
      english: "son",
      english_alternate_choices: [""],
    },
    {
      simplified: "女儿",
      traditional: "女兒",
      pinyin: "nǚ'ér",
      english: "daughter",
      english_alternate_choices: [""],
    },
    {
      simplified: "老师",
      traditional: "老師",
      pinyin: "lǎoshī",
      english: "teacher",
      english_alternate_choices: [""],
    },
    {
      simplified: "学生",
      traditional: "學生",
      pinyin: "xuéshēng",
      english: "student",
      english_alternate_choices: [""],
    },
    {
      simplified: "同学",
      traditional: "同學",
      pinyin: "tóngxué",
      english: "shoolmate",
      english_alternate_choices: [""],
    },
    {
      simplified: "朋友",
      traditional: "朋友",
      pinyin: "péngyǒu",
      english: "friend",
      english_alternate_choices: [""],
    },
    {
      simplified: "医生",
      traditional: "醫生",
      pinyin: "yīshēng",
      english: "doctor",
      english_alternate_choices: [""],
    },
    {
      simplified: "先生",
      traditional: "先生",
      pinyin: "xiānsheng",
      english: "sir",
      english_alternate_choices: [""],
    },
    {
      simplified: "小姐",
      traditional: "小姐",
      pinyin: "xiǎojiě",
      english: "Miss",
      english_alternate_choices: [""],
    },
    {
      simplified: "哥哥",
      traditional: "哥哥",
      pinyin: "gēge",
      english: "older brother",
      english_alternate_choices: [""],
    },
    {
      simplified: "姐姐",
      traditional: "姐姐",
      pinyin: "jiějie",
      english: "older sister",
      english_alternate_choices: [""],
    },
    {
      simplified: "弟弟",
      traditional: "弟弟",
      pinyin: "dìdi",
      english: "younger brother",
      english_alternate_choices: [""],
    },
    {
      simplified: "妹妹",
      traditional: "妹妹",
      pinyin: "mèimei",
      english: "younger sister",
      english_alternate_choices: [""],
    },
    {
      simplified: "丈夫",
      traditional: "丈夫",
      pinyin: "zhàngfu",
      english: "husband",
      english_alternate_choices: [""],
    },
    {
      simplified: "妻子",
      traditional: "妻子",
      pinyin: "qīzi",
      english: "wife",
      english_alternate_choices: [""],
    },
    {
      simplified: "孩子",
      traditional: "孩子",
      pinyin: "háizi",
      english: "child",
      english_alternate_choices: [""],
    },
    {
      simplified: "男人",
      traditional: "男人",
      pinyin: "nánrén",
      english: "man",
      english_alternate_choices: [""],
    },
    {
      simplified: "女人",
      traditional: "女人",
      pinyin: "nǚrén",
      english: "woman",
      english_alternate_choices: [""],
    },
    {
      simplified: "服务员",
      traditional: "服務員",
      pinyin: "fúwùyuán",
      english: "waiter",
      english_alternate_choices: [""],
    },
    {
      simplified: "衣服",
      traditional: "衣服",
      pinyin: "yīfu",
      english: "cloth",
      english_alternate_choices: [""],
    },
    {
      simplified: "水",
      traditional: "水",
      pinyin: "shuǐ",
      english: "water",
      english_alternate_choices: [""],
    },
    {
      simplified: "菜",
      traditional: "菜",
      pinyin: "cài",
      english: "dish",
      english_alternate_choices: [""],
    },
    {
      simplified: "米饭",
      traditional: "米飯",
      pinyin: "mǐfàn",
      english: "rice",
      english_alternate_choices: [""],
    },
    {
      simplified: "水果",
      traditional: "水果",
      pinyin: "shuǐguǒ",
      english: "fruit",
      english_alternate_choices: [""],
    },
    {
      simplified: "苹果",
      traditional: "蘋果",
      pinyin: "píngguǒ",
      english: "apple",
      english_alternate_choices: [""],
    },
    {
      simplified: "茶",
      traditional: "茶",
      pinyin: "chá",
      english: "tea",
      english_alternate_choices: [""],
    },
    {
      simplified: "杯子",
      traditional: "杯子",
      pinyin: "bēizi",
      english: "cup",
      english_alternate_choices: [""],
    },
    {
      simplified: "钱",
      traditional: "錢",
      pinyin: "qián",
      english: "money",
      english_alternate_choices: [""],
    },
    {
      simplified: "飞机",
      traditional: "飛機",
      pinyin: "fēijī",
      english: "airplane",
      english_alternate_choices: [""],
    },
    {
      simplified: "出租车",
      traditional: "出租車",
      pinyin: "chūzūchē",
      english: "taxi",
      english_alternate_choices: [""],
    },
    {
      simplified: "电视",
      traditional: "電視",
      pinyin: "diànshì",
      english: "television",
      english_alternate_choices: [""],
    },
    {
      simplified: "电脑",
      traditional: "電腦",
      pinyin: "diànnǎo",
      english: "computer",
      english_alternate_choices: [""],
    },
    {
      simplified: "电影",
      traditional: "電影",
      pinyin: "diànyǐng",
      english: "movie",
      english_alternate_choices: [""],
    },
    {
      simplified: "天气",
      traditional: "天氣",
      pinyin: "tiānqì",
      english: "weather",
      english_alternate_choices: [""],
    },
    {
      simplified: "猫",
      traditional: "貓",
      pinyin: "māo",
      english: "cat",
      english_alternate_choices: [""],
    },
    {
      simplified: "狗",
      traditional: "狗",
      pinyin: "gǒu",
      english: "dog",
      english_alternate_choices: [""],
    },
    {
      simplified: "东西",
      traditional: "東西",
      pinyin: "dōngxi",
      english: "thing",
      english_alternate_choices: [""],
    },
    {
      simplified: "鱼",
      traditional: "魚",
      pinyin: "yú",
      english: "fish",
      english_alternate_choices: [""],
    },
    {
      simplified: "羊肉",
      traditional: "羊肉",
      pinyin: "yángròu",
      english: "mutton",
      english_alternate_choices: [""],
    },
    {
      simplified: "牛奶",
      traditional: "牛奶",
      pinyin: "niúnǎi",
      english: "milk",
      english_alternate_choices: [""],
    },
    {
      simplified: "鸡蛋",
      traditional: "雞蛋",
      pinyin: "jīdàn",
      english: "egg",
      english_alternate_choices: [""],
    },
    {
      simplified: "西瓜",
      traditional: "西瓜",
      pinyin: "xīguā",
      english: "watermelon",
      english_alternate_choices: [""],
    },
    {
      simplified: "咖啡",
      traditional: "咖啡",
      pinyin: "kāfēi",
      english: "coffee",
      english_alternate_choices: [""],
    },
    {
      simplified: "自行车",
      traditional: "自行車",
      pinyin: "zìxíngchē",
      english: "bike",
      english_alternate_choices: [""],
    },
    {
      simplified: "船",
      traditional: "船",
      pinyin: "chuán",
      english: "boat",
      english_alternate_choices: [""],
    },
    {
      simplified: "雪",
      traditional: "雪",
      pinyin: "xuě",
      english: "snow",
      english_alternate_choices: [""],
    },
    {
      simplified: "药",
      traditional: "藥",
      pinyin: "yào",
      english: "medicine",
      english_alternate_choices: [""],
    },
    {
      simplified: "手机",
      traditional: "手機",
      pinyin: "shǒujī",
      english: "cellphone",
      english_alternate_choices: [""],
    },
    {
      simplified: "手表",
      traditional: "手錶",
      pinyin: "shǒubiǎo",
      english: "watch",
      english_alternate_choices: [""],
    },
    {
      simplified: "眼睛",
      traditional: "眼睛",
      pinyin: "yǎnjīng",
      english: "eye",
      english_alternate_choices: [""],
    },
    {
      simplified: "身体",
      traditional: "身體",
      pinyin: "shēntǐ",
      english: "body",
      english_alternate_choices: [""],
    },
    {
      simplified: "公共汽车",
      traditional: "公共汽車",
      pinyin: "gōnggòngqìchē",
      english: "bus",
      english_alternate_choices: [""],
    },
    {
      simplified: "报纸",
      traditional: "報紙",
      pinyin: "bàozhǐ",
      english: "newspaper",
      english_alternate_choices: [""],
    },
    {
      simplified: "人",
      traditional: "人",
      pinyin: "rén",
      english: "person",
      english_alternate_choices: [""],
    },
    {
      simplified: "名字",
      traditional: "名字",
      pinyin: "míngzì",
      english: "name",
      english_alternate_choices: [""],
    },
    {
      simplified: "书",
      traditional: "書",
      pinyin: "shū",
      english: "book",
      english_alternate_choices: [""],
    },
    {
      simplified: "汉语",
      traditional: "漢語",
      pinyin: "hànyǔ",
      english: "Chinese",
      english_alternate_choices: [""],
    },
    {
      simplified: "字",
      traditional: "字",
      pinyin: "zì",
      english: "character",
      english_alternate_choices: [""],
    },
    {
      simplified: "桌子",
      traditional: "桌子",
      pinyin: "zhuōzi",
      english: "desk",
      english_alternate_choices: [""],
    },
    {
      simplified: "椅子",
      traditional: "椅子",
      pinyin: "yǐzi",
      english: "chair",
      english_alternate_choices: [""],
    },
    {
      simplified: "门",
      traditional: "門",
      pinyin: "mén",
      english: "door",
      english_alternate_choices: [""],
    },
    {
      simplified: "题",
      traditional: "題",
      pinyin: "tí",
      english: "topic",
      english_alternate_choices: [""],
    },
    {
      simplified: "课",
      traditional: "課",
      pinyin: "kè",
      english: "lesson",
      english_alternate_choices: [""],
    },
    {
      simplified: "姓",
      traditional: "姓",
      pinyin: "xìng",
      english: "surname",
      english_alternate_choices: [""],
    },
    {
      simplified: "问题",
      traditional: "問題",
      pinyin: "wèntí",
      english: "question",
      english_alternate_choices: [""],
    },
    {
      simplified: "事情",
      traditional: "事情",
      pinyin: "shìqing",
      english: "matter",
      english_alternate_choices: [""],
    },
    {
      simplified: "考试",
      traditional: "考試",
      pinyin: "kǎoshì",
      english: "exam",
      english_alternate_choices: [""],
    },
    {
      simplified: "票",
      traditional: "票",
      pinyin: "piào",
      english: "ticket",
      english_alternate_choices: [""],
    },
    {
      simplified: "意思",
      traditional: "意思",
      pinyin: "yìsi",
      english: "meaning",
      english_alternate_choices: [""],
    },
    {
      simplified: "颜色",
      traditional: "顏色",
      pinyin: "yánsè",
      english: "color",
      english_alternate_choices: [""],
    },
    {
      simplified: "谢谢",
      traditional: "謝謝",
      pinyin: "xièxie",
      english: "thank",
      english_alternate_choices: [""],
    },
    {
      simplified: "不客气",
      traditional: "不客氣",
      pinyin: "búkèqì",
      english: "you are welcome",
      english_alternate_choices: [""],
    },
    {
      simplified: "再见",
      traditional: "再見",
      pinyin: "zàijiàn",
      english: "good-bye",
      english_alternate_choices: [""],
    },
    {
      simplified: "请",
      traditional: "請",
      pinyin: "qǐng",
      english: "please",
      english_alternate_choices: [""],
    },
    {
      simplified: "对不起",
      traditional: "對不起",
      pinyin: "duìbùqǐ",
      english: "sorry",
      english_alternate_choices: [""],
    },
    {
      simplified: "没关系",
      traditional: "沒關係",
      pinyin: "méiguānxi",
      english: "It doesn't matter",
      english_alternate_choices: [""],
    },
    {
      simplified: "欢迎",
      traditional: "歡迎",
      pinyin: "huānyíng",
      english: "welcome",
      english_alternate_choices: [""],
    },
    {
      simplified: "是",
      traditional: "是",
      pinyin: "shì",
      english: "am, is, are",
      english_alternate_choices: [""],
    },
    {
      simplified: "有",
      traditional: "有",
      pinyin: "yǒu",
      english: "have",
      english_alternate_choices: [""],
    },
    {
      simplified: "看",
      traditional: "看",
      pinyin: "kàn",
      english: "look",
      english_alternate_choices: [""],
    },
    {
      simplified: "听",
      traditional: "聽",
      pinyin: "tīng",
      english: "listen",
      english_alternate_choices: [""],
    },
    {
      simplified: "说话",
      traditional: "說話",
      pinyin: "shuōhuà",
      english: "speak",
      english_alternate_choices: [""],
    },
    {
      simplified: "读",
      traditional: "讀",
      pinyin: "dú",
      english: "read",
      english_alternate_choices: [""],
    },
    {
      simplified: "写",
      traditional: "寫",
      pinyin: "xiě",
      english: "write",
      english_alternate_choices: [""],
    },
    {
      simplified: "看见",
      traditional: "看見",
      pinyin: "kànjiàn",
      english: "see",
      english_alternate_choices: [""],
    },
    {
      simplified: "叫",
      traditional: "叫",
      pinyin: "jiào",
      english: "call",
      english_alternate_choices: [""],
    },
    {
      simplified: "来",
      traditional: "來",
      pinyin: "lái",
      english: "come",
      english_alternate_choices: [""],
    },
    {
      simplified: "回",
      traditional: "時",
      pinyin: "huí",
      english: "return",
      english_alternate_choices: [""],
    },
    {
      simplified: "去",
      traditional: "去",
      pinyin: "qù",
      english: "go",
      english_alternate_choices: [""],
    },
    {
      simplified: "吃",
      traditional: "吃",
      pinyin: "chī",
      english: "eat",
      english_alternate_choices: [""],
    },
    {
      simplified: "喝",
      traditional: "喝",
      pinyin: "hē",
      english: "drink",
      english_alternate_choices: [""],
    },
    {
      simplified: "睡觉",
      traditional: "睡覺",
      pinyin: "shuìjiào",
      english: "sleep",
      english_alternate_choices: [""],
    },
    {
      simplified: "打电话",
      traditional: "打電話",
      pinyin: "dǎdiànhuà",
      english: "call up",
      english_alternate_choices: [""],
    },
    {
      simplified: "做",
      traditional: "做",
      pinyin: "zuò",
      english: "do",
      english_alternate_choices: [""],
    },
    {
      simplified: "买",
      traditional: "買",
      pinyin: "mǎi",
      english: "buy",
      english_alternate_choices: [""],
    },
    {
      simplified: "开",
      traditional: "開",
      pinyin: "kāi",
      english: "open",
      english_alternate_choices: [""],
    },
    {
      simplified: "坐",
      traditional: "坐",
      pinyin: "zuò",
      english: "sit",
      english_alternate_choices: [""],
    },
    {
      simplified: "住",
      traditional: "住",
      pinyin: "zhù",
      english: "live",
      english_alternate_choices: [""],
    },
    {
      simplified: "学习",
      traditional: "學習",
      pinyin: "xuéxí",
      english: "study",
      english_alternate_choices: [""],
    },
    {
      simplified: "工作",
      traditional: "工作",
      pinyin: "gōngzuò",
      english: "work",
      english_alternate_choices: [""],
    },
    {
      simplified: "下雨",
      traditional: "下雨",
      pinyin: "xiàyǔ",
      english: "rain",
      english_alternate_choices: [""],
    },
    {
      simplified: "问",
      traditional: "問",
      pinyin: "wèn",
      english: "ask",
      english_alternate_choices: [""],
    },
    {
      simplified: "走",
      traditional: "走",
      pinyin: "zǒu",
      english: "walk",
      english_alternate_choices: [""],
    },
    {
      simplified: "进",
      traditional: "進",
      pinyin: "jìn",
      english: "enter",
      english_alternate_choices: [""],
    },
    {
      simplified: "出",
      traditional: "出",
      pinyin: "chū",
      english: "come",
      english_alternate_choices: [""],
    },
    {
      simplified: "跑步",
      traditional: "跑步",
      pinyin: "pǎobù",
      english: "run",
      english_alternate_choices: [""],
    },
    {
      simplified: "到",
      traditional: "到",
      pinyin: "dào",
      english: "arrive",
      english_alternate_choices: [""],
    },
    {
      simplified: "穿",
      traditional: "穿",
      pinyin: "chuān",
      english: "wear",
      english_alternate_choices: [""],
    },
    {
      simplified: "洗",
      traditional: "洗",
      pinyin: "xǐ",
      english: "wash",
      english_alternate_choices: [""],
    },
    {
      simplified: "给",
      traditional: "給",
      pinyin: "gěi",
      english: "give",
      english_alternate_choices: [""],
    },
    {
      simplified: "找",
      traditional: "找",
      pinyin: "zhǎo",
      english: "find",
      english_alternate_choices: [""],
    },
    {
      simplified: "懂",
      traditional: "懂",
      pinyin: "dǒng",
      english: "understand",
      english_alternate_choices: [""],
    },
    {
      simplified: "笑",
      traditional: "洛爾",
      pinyin: "xiào",
      english: "smile",
      english_alternate_choices: [""],
    },
    {
      simplified: "回答",
      traditional: "回答",
      pinyin: "huídá",
      english: "answer",
      english_alternate_choices: [""],
    },
    {
      simplified: "告诉",
      traditional: "告訴",
      pinyin: "gàosù",
      english: "tell",
      english_alternate_choices: [""],
    },
    {
      simplified: "准备",
      traditional: "準備",
      pinyin: "zhǔnbèi",
      english: "prepare",
      english_alternate_choices: [""],
    },
    {
      simplified: "开始",
      traditional: "開始",
      pinyin: "kāishǐ",
      english: "begin",
      english_alternate_choices: [""],
    },
    {
      simplified: "介绍",
      traditional: "介紹",
      pinyin: "jièshào",
      english: "introduce",
      english_alternate_choices: [""],
    },
    {
      simplified: "帮助",
      traditional: "幫助",
      pinyin: "bāngzhù",
      english: "help",
      english_alternate_choices: [""],
    },
    {
      simplified: "玩",
      traditional: "玩",
      pinyin: "wán",
      english: "play",
      english_alternate_choices: [""],
    },
    {
      simplified: "送",
      traditional: "送",
      pinyin: "sòng",
      english: "present",
      english_alternate_choices: [""],
    },
    {
      simplified: "等",
      traditional: "等",
      pinyin: "děng",
      english: "wait",
      english_alternate_choices: [""],
    },
    {
      simplified: "让",
      traditional: "讓",
      pinyin: "ràng",
      english: "let",
      english_alternate_choices: [""],
    },
    {
      simplified: "起床",
      traditional: "起床",
      pinyin: "qǐchuáng",
      english: "get up",
      english_alternate_choices: [""],
    },
    {
      simplified: "唱歌",
      traditional: "唱歌",
      pinyin: "chànggē",
      english: "sing",
      english_alternate_choices: [""],
    },
    {
      simplified: "跳舞",
      traditional: "跳舞",
      pinyin: "tiàowǔ",
      english: "dance",
      english_alternate_choices: [""],
    },
    {
      simplified: "旅游",
      traditional: "旅遊",
      pinyin: "lǚyóu",
      english: "travel",
      english_alternate_choices: [""],
    },
    {
      simplified: "上班",
      traditional: "上班",
      pinyin: "shàngbān",
      english: "be on duty",
      english_alternate_choices: [""],
    },
    {
      simplified: "生病",
      traditional: "生病",
      pinyin: "shēngbìng",
      english: "fall ill",
      english_alternate_choices: [""],
    },
    {
      simplified: "休息",
      traditional: "休息",
      pinyin: "xiūxi",
      english: "rest",
      english_alternate_choices: [""],
    },
    {
      simplified: "运动",
      traditional: "運動",
      pinyin: "yùndòng",
      english: "exercise",
      english_alternate_choices: [""],
    },
    {
      simplified: "游泳",
      traditional: "游泳",
      pinyin: "yóuyǒng",
      english: "swim",
      english_alternate_choices: [""],
    },
    {
      simplified: "踢足球",
      traditional: "踢足球",
      pinyin: "tīzúqiú",
      english: "play footbal",
      english_alternate_choices: [""],
    },
    {
      simplified: "打篮球",
      traditional: "打籃球",
      pinyin: "dǎlánqiú",
      english: "play basketball",
      english_alternate_choices: [""],
    },
    {
      simplified: "完",
      traditional: "完",
      pinyin: "wán",
      english: "finish",
      english_alternate_choices: [""],
    },
    {
      simplified: "爱",
      traditional: "愛",
      pinyin: "ài",
      english: "love",
      english_alternate_choices: [""],
    },
    {
      simplified: "喜欢",
      traditional: "喜歡",
      pinyin: "xǐhuān",
      english: "love, like",
      english_alternate_choices: [""],
    },
    {
      simplified: "想",
      traditional: "想",
      pinyin: "xiǎng",
      english: "want",
      english_alternate_choices: [""],
    },
    {
      simplified: "认识",
      traditional: "認識",
      pinyin: "rènshi",
      english: "know",
      english_alternate_choices: [""],
    },
    {
      simplified: "觉得",
      traditional: "覺得",
      pinyin: "juédé",
      english: "think",
      english_alternate_choices: [""],
    },
    {
      simplified: "知道",
      traditional: "知道",
      pinyin: "zhīdao",
      english: "know",
      english_alternate_choices: [""],
    },
    {
      simplified: "希望",
      traditional: "希望",
      pinyin: "xīwàng",
      english: "hope",
      english_alternate_choices: [""],
    },
    {
      simplified: "会",
      traditional: "會",
      pinyin: "huì",
      english: "can",
      english_alternate_choices: [""],
    },
    {
      simplified: "能",
      traditional: "能",
      pinyin: "néng",
      english: "can, be able to",
      english_alternate_choices: [""],
    },
    {
      simplified: "可以",
      traditional: "可以",
      pinyin: "kěyǐ",
      english: "can",
      english_alternate_choices: [""],
    },
    {
      simplified: "要",
      traditional: "要",
      pinyin: "yào",
      english: "ask for",
      english_alternate_choices: [""],
    },
    {
      simplified: "可能",
      traditional: "可能",
      pinyin: "kěnéng",
      english: "may",
      english_alternate_choices: [""],
    },
    {
      simplified: "好",
      traditional: "好",
      pinyin: "hǎo",
      english: "good",
      english_alternate_choices: [""],
    },
    {
      simplified: "大",
      traditional: "大",
      pinyin: "dà",
      english: "big",
      english_alternate_choices: [""],
    },
    {
      simplified: "小",
      traditional: "小",
      pinyin: "xiǎo",
      english: "small",
      english_alternate_choices: [""],
    },
    {
      simplified: "多",
      traditional: "多",
      pinyin: "duō",
      english: "many, much",
      english_alternate_choices: [""],
    },
    {
      simplified: "少",
      traditional: "少",
      pinyin: "shǎo",
      english: "few, little",
      english_alternate_choices: [""],
    },
    {
      simplified: "冷",
      traditional: "冷",
      pinyin: "lěng",
      english: "cold",
      english_alternate_choices: [""],
    },
    {
      simplified: "热",
      traditional: "熱",
      pinyin: "rè",
      english: "hot",
      english_alternate_choices: [""],
    },
    {
      simplified: "高兴",
      traditional: "高興",
      pinyin: "gāoxìng",
      english: "happy",
      english_alternate_choices: [""],
    },
    {
      simplified: "漂亮",
      traditional: "漂亮",
      pinyin: "piàoliang",
      english: "beautiful",
      english_alternate_choices: [""],
    },
    {
      simplified: "高",
      traditional: "高",
      pinyin: "gāo",
      english: "tall",
      english_alternate_choices: [""],
    },
    {
      simplified: "红",
      traditional: "紅",
      pinyin: "hóng",
      english: "red",
      english_alternate_choices: [""],
    },
    {
      simplified: "白",
      traditional: "白",
      pinyin: "bái",
      english: "white",
      english_alternate_choices: [""],
    },
    {
      simplified: "黑",
      traditional: "黑",
      pinyin: "hēi",
      english: "black",
      english_alternate_choices: [""],
    },
    {
      simplified: "忙",
      traditional: "忙",
      pinyin: "máng",
      english: "busy",
      english_alternate_choices: [""],
    },
    {
      simplified: "快",
      traditional: "快",
      pinyin: "kuài",
      english: "fast",
      english_alternate_choices: [""],
    },
    {
      simplified: "慢",
      traditional: "慢",
      pinyin: "màn",
      english: "slow",
      english_alternate_choices: [""],
    },
    {
      simplified: "远",
      traditional: "遠",
      pinyin: "yuǎn",
      english: "far",
      english_alternate_choices: [""],
    },
    {
      simplified: "近",
      traditional: "近",
      pinyin: "jìn",
      english: "close",
      english_alternate_choices: [""],
    },
    {
      simplified: "好吃",
      traditional: "好吃",
      pinyin: "hǎochī",
      english: "delicioous",
      english_alternate_choices: [""],
    },
    {
      simplified: "累",
      traditional: "累",
      pinyin: "lèi",
      english: "tired",
      english_alternate_choices: [""],
    },
    {
      simplified: "长",
      traditional: "長",
      pinyin: "cháng",
      english: "long",
      english_alternate_choices: [""],
    },
    {
      simplified: "新",
      traditional: "新",
      pinyin: "xīn",
      english: "new",
      english_alternate_choices: [""],
    },
    {
      simplified: "贵",
      traditional: "貴",
      pinyin: "guì",
      english: "expensive",
      english_alternate_choices: [""],
    },
    {
      simplified: "便宜",
      traditional: "便宜",
      pinyin: "piányi",
      english: "cheap",
      english_alternate_choices: [""],
    },
    {
      simplified: "晴",
      traditional: "晴",
      pinyin: "qíng",
      english: "fine",
      english_alternate_choices: [""],
    },
    {
      simplified: "阴",
      traditional: "陰",
      pinyin: "yīn",
      english: "cloudy",
      english_alternate_choices: [""],
    },
    {
      simplified: "错",
      traditional: "錯",
      pinyin: "cuò",
      english: "wrong",
      english_alternate_choices: [""],
    },
    {
      simplified: "快乐",
      traditional: "快樂",
      pinyin: "kuàilè",
      english: "happy",
      english_alternate_choices: [""],
    },
  ],
};

export default lesson;
