import { HSKList } from "@src/tools/types";

const lesson: HSKList = {
  list: "7",
  locked: false,
  title: "General Vocabulary",
  content: [
    {
      simplified: "讚",
      traditional: "赞",
      pinyin: "zàn",
      english: "Awesome",
    },
    {
      simplified: "外带",
      traditional: "外帶",
      pinyin: "wàidài",
      english: "Takeaway",
    },
    {
      simplified: "这里",
      traditional: "這裡",
      pinyin: "zhèlǐ",
      english: "Here",
    },
    {
      simplified: "跟",
      traditional: "跟",
      pinyin: "gēn",
      english: "With",
    },
    {
      simplified: "大学",
      traditional: "大學",
      pinyin: "dàxué",
      english: "University",
    },
    {
      simplified: "如果",
      traditional: "如果",
      pinyin: "rúguǒ",
      english: "If",
    },
    {
      simplified: "尝试",
      traditional: "嘗試",
      pinyin: "chángshì",
      english: "Try",
    },
    {
      simplified: "豬肉",
      traditional: "豬肉",
      pinyin: "zhūròu",
      english: "Pork",
    },
    {
      simplified: "牛肉",
      traditional: "牛肉",
      pinyin: "niúròu",
      english: "Beef",
    },
    {
      simplified: "雞",
      traditional: "雞",
      pinyin: "Jī",
      english: "Chicken",
    },
    {
      simplified: "肉",
      traditional: "肉",
      pinyin: "ròu",
      english: "Meat",
    },
    {
      simplified: "哪里是",
      traditional: "哪裡是",
      pinyin: "nǎlǐ shì",
      english: "Where is that?",
    },
    {
      simplified: "几点了",
      traditional: "幾點了",
      pinyin: "jǐ diǎnle",
      english: "What time?",
    },
    {
      simplified: "田纳西",
      traditional: "田納西",
      pinyin: "tiánnàxī",
      english: "Tennessee",
    },
    {
      simplified: "怎么了",
      traditional: "怎麼了",
      pinyin: "zěnmeliǎo",
      english: "What happened?",
    },
    {
      simplified: "走路",
      traditional: "走路",
      pinyin: "zǒulù",
      english: "Walk",
    },
    {
      simplified: "蜜柚红茶",
      traditional: "蜜柚紅茶",
      pinyin: "mì yòu hóngchá",
      english: "Honey grapefruit tea",
    },
    {
      simplified: "卤味",
      traditional: "滷味",
      pinyin: "lǔwèi",
      english: "Fried vegetables bowl",
    },
    {
      simplified: "最近",
      traditional: "最近",
      pinyin: "zuì jìn",
      english: "Recently",
    },
    {
      simplified: "还不错",
      traditional: "還不錯",
      pinyin: "Hái bùcuò",
      english: "Not bad",
    },
    {
      simplified: "还可以",
      traditional: "還可以",
      pinyin: "Hái kěyǐ",
      english: "Still alright",
    },
    {
      simplified: "很差",
      traditional: "很差",
      pinyin: "Hěn chà",
      english: "Very poor",
    },
    {
      simplified: "关心",
      traditional: "關心",
      pinyin: "guān xīn",
      english: "Care for",
    },
    {
      simplified: "来",
      traditional: "來",
      pinyin: "lái",
      english: "Come",
    },
    {
      simplified: "不好意思",
      traditional: "不好意思",
      pinyin: "bù hǎo yì si",
      english: "Sorry",
    },
    {
      simplified: "我要到",
      traditional: "我要到",
      pinyin: "wǒ yào dào",
      english: "I want to",
    },
    {
      simplified: "稍等",
      traditional: "稍等",
      pinyin: "shāo děng",
      english: "Wait a minute",
    },
    {
      simplified: "司机",
      traditional: "司機",
      pinyin: "sī jī",
      english: "Driver",
    },
    {
      simplified: "直走",
      traditional: "直走",
      pinyin: "zhí zǒu",
      english: "Go straight",
    },
    {
      simplified: "左转",
      traditional: "左轉",
      pinyin: "zuǒ zhuǎn",
      english: "Turn left",
    },
    {
      simplified: "右转",
      traditional: "右轉",
      pinyin: "yòu zhuǎn",
      english: "Turn right",
    },
    {
      simplified: "十字路口",
      traditional: "十字路口",
      pinyin: "shí zì lù kǒu",
      english: "Crossroads",
    },
    {
      simplified: "下班",
      traditional: "下班",
      pinyin: "xià bān",
      english: "Off work",
    },
    {
      simplified: "重要",
      traditional: "重要",
      pinyin: "zhòng yào",
      english: "Important",
    },
    {
      simplified: "宵夜",
      traditional: "宵夜",
      pinyin: "xiāo yè",
      english: "Supper",
    },
    {
      simplified: "附近",
      traditional: "附近",
      pinyin: "fù jìn",
      english: "Nearby",
    },
    {
      simplified: "抵达",
      traditional: "抵達",
      pinyin: "dǐ dá",
      english: "Arrival",
    },
    {
      simplified: "服务生",
      traditional: "服務生",
      pinyin: "fú wù shēng",
      english: "Waiter",
    },
    {
      simplified: "这边",
      traditional: "這邊",
      pinyin: "zhè biān",
      english: "Over here",
    },
    {
      simplified: "那边",
      traditional: "那邊",
      pinyin: "nà bian",
      english: "There",
    },
    {
      simplified: "单点",
      traditional: "單點",
      pinyin: "dān diǎn",
      english: "À la carte",
    },
    {
      simplified: "套餐",
      traditional: "套餐",
      pinyin: "tào cān",
      english: "Package",
    },
    {
      simplified: "开胃菜",
      traditional: "開胃菜",
      pinyin: "kāi wèi cài",
      english: "Appetizer",
    },
    {
      simplified: "汤",
      traditional: "湯",
      pinyin: "tāng",
      english: "Soup",
    },
    {
      simplified: "沙拉",
      traditional: "沙拉",
      pinyin: "shā lā",
      english: "Salad",
    },
    {
      simplified: "饮料",
      traditional: "飲料",
      pinyin: "yǐn liào",
      english: "Drink",
    },
    {
      simplified: "甜点",
      traditional: "甜點",
      pinyin: "tián diǎn",
      english: "Dessert",
    },
    {
      simplified: "人气",
      traditional: "人氣",
      pinyin: "rén qì",
      english: "Popularity",
    },
    {
      simplified: "主厨",
      traditional: "主廚",
      pinyin: "zhǔ chú",
      english: "Chef",
    },
    {
      simplified: "推荐",
      traditional: "推薦",
      pinyin: "tuī jiàn",
      english: "Recommend",
    },
    {
      simplified: "讨论",
      traditional: "討論",
      pinyin: "tǎo lùn",
      english: "Discuss",
    },
    {
      simplified: "过来",
      traditional: "過來",
      pinyin: "guò lái",
      english: "Come",
    },
    {
      simplified: "过",
      traditional: "過",
      pinyin: "guò",
      english: "Over",
    },
    {
      simplified: "下班后",
      traditional: "下班後",
      pinyin: "xià bān hòu",
      english: "After work",
    },
    {
      simplified: "走吧",
      traditional: "走吧",
      pinyin: "zǒu ba",
      english: "Let's go",
    },
    {
      simplified: "两位",
      traditional: "兩位",
      pinyin: "liǎng wèi",
      english: "Two people",
    },
    {
      simplified: "这边请",
      traditional: "這邊請",
      pinyin: "zhè biān qǐng",
      english: "This way please",
    },
    {
      simplified: "好的",
      traditional: "好的",
      pinyin: "hǎo de",
      english: "Ok",
    },
    {
      simplified: "你们有几位呢",
      traditional: "你們有幾位呢",
      pinyin: "nǐmen yǒu jǐ wèi ne",
      english: "How many of you",
    },
    {
      simplified: "总共",
      traditional: "總共",
      pinyin: "zǒnggòng",
      english: "Total",
    },
    {
      simplified: "钱",
      traditional: "錢",
      pinyin: "qián",
      english: "Money",
    },
    {
      simplified: "一千",
      traditional: "一千",
      pinyin: "yīqiān",
      english: "One thousand",
    },
    {
      simplified: "一万",
      traditional: "一萬",
      pinyin: "yī wàn",
      english: "Ten thousand",
    },
    {
      simplified: "十万",
      traditional: "十萬",
      pinyin: "shí wàn",
      english: "One hundred thousand",
    },
    {
      simplified: "一百万",
      traditional: "一百萬",
      pinyin: "yībǎi wàn",
      english: "One million",
    },
    {
      simplified: "一亿",
      traditional: "一億",
      pinyin: "yī yì",
      english: "100 million",
    },
    {
      simplified: "加",
      traditional: "加",
      pinyin: "jiā",
      english: "Plus",
    },
    {
      simplified: "减",
      traditional: "減",
      pinyin: "jiǎn",
      english: "Minus",
    },
    {
      simplified: "乘",
      traditional: "乘",
      pinyin: "chéng",
      english: "Multiply",
    },
    {
      simplified: "除",
      traditional: "除",
      pinyin: "chú",
      english: "Divide",
    },
    {
      simplified: "等于",
      traditional: "等於",
      pinyin: "děngyú",
      english: "Equal",
    },
    {
      simplified: "时间",
      traditional: "時間",
      pinyin: "shíjiān",
      english: "Time",
    },
    {
      simplified: "凌晨",
      traditional: "凌晨",
      pinyin: "língchén",
      english: "Early morning",
    },
    {
      simplified: "早上",
      traditional: "早上",
      pinyin: "zǎoshang",
      english: "Morning",
    },
    {
      simplified: "晚上",
      traditional: "晚上",
      pinyin: "wǎnshàng",
      english: "At night",
    },
    {
      simplified: "之前",
      traditional: "之前",
      pinyin: "zhīqián",
      english: "Prior to",
    },
    {
      simplified: "之后",
      traditional: "之後",
      pinyin: "zhīhòu",
      english: "After that",
    },
    {
      simplified: "前天",
      traditional: "前天",
      pinyin: "qián tiān",
      english: "The day before yesterday",
    },
    {
      simplified: "去年",
      traditional: "去年",
      pinyin: "qùnián",
      english: "Last year",
    },
    {
      simplified: "今年",
      traditional: "今年",
      pinyin: "jīnnián",
      english: "This year",
    },
    {
      simplified: "明年",
      traditional: "明年",
      pinyin: "míngnián",
      english: "Next year",
    },
    {
      simplified: "后年",
      traditional: "後年",
      pinyin: "hòu nián",
      english: "The following year",
    },
    {
      simplified: "兴趣",
      traditional: "興趣",
      pinyin: "xìng qù",
      english: "Habit",
    },
    {
      simplified: "打篮球",
      traditional: "打籃球",
      pinyin: "dǎ lánqiú",
      english: "Play basketball",
    },
    {
      simplified: "打鼓",
      traditional: "打鼓",
      pinyin: "dǎ gǔ",
      english: "Drumming",
    },
    {
      simplified: "爬山",
      traditional: "爬山",
      pinyin: "pá shān",
      english: "Mountain climbing",
    },
    {
      simplified: "游泳",
      traditional: "游泳",
      pinyin: "yóu yǒng",
      english: "Swimming",
    },
    {
      simplified: "打电动游戏",
      traditional: "打電動遊戲",
      pinyin: "dǎ diàndòng yóuxì",
      english: "Play video games",
    },
    {
      simplified: "看电影",
      traditional: "看電影",
      pinyin: "kàn diànyǐng",
      english: "Watch movie",
    },
    {
      simplified: "可乐",
      traditional: "可樂",
      pinyin: "kě lè",
      english: "Cola",
    },
    {
      simplified: "爆米花",
      traditional: "爆米花",
      pinyin: "bào mǐ huā",
      english: "Popcorn",
    },
    {
      simplified: "热狗",
      traditional: "熱狗",
      pinyin: "rè gǒu",
      english: "Hot dog",
    },
    {
      simplified: "健身",
      traditional: "健身",
      pinyin: "jiàn shēn",
      english: "Fitness",
    },
    {
      simplified: "看书",
      traditional: "看書",
      pinyin: "kàn shū",
      english: "Read a book",
    },
    {
      simplified: "小说",
      traditional: "小說",
      pinyin: "xiǎo shuō",
      english: "Fiction/novel",
    },
    {
      simplified: "漫画",
      traditional: "漫畫",
      pinyin: "màn huà",
      english: "Comic",
    },
    {
      simplified: "杂志",
      traditional: "雜誌",
      pinyin: "zá zhì",
      english: "Magazine",
    },
    {
      simplified: "职业",
      traditional: "職業",
      pinyin: "zhí yè",
      english: "Occupation",
    },
    {
      simplified: "擂茶",
      traditional: "擂茶",
      pinyin: "léi cha",
      english: "Tea",
    },
  ],
};

export default lesson;
