import { HSKList } from "@src/tools/types";

const lesson: HSKList = {
  list: "8",
  locked: false,
  title: "Dictation",
  content: [
    {
      simplified: "陈",
      traditional: "陳",
      pinyin: "chén",
      english: "Chen",
    },
    {
      simplified: "月",
      traditional: "月",
      pinyin: "yuè",
      english: "Month",
    },
    {
      simplified: "美",
      traditional: "美",
      pinyin: "měi",
      english: "Nice",
    },
    {
      simplified: "李",
      traditional: "李",
      pinyin: "lǐ",
      english: "Lee",
    },
    {
      simplified: "明",
      traditional: "明",
      pinyin: "míng",
      english: "Bright",
    },
    {
      simplified: "华",
      traditional: "華",
      pinyin: "huá",
      english: "China",
    },
    {
      simplified: "王",
      traditional: "王",
      pinyin: "wáng",
      english: "King",
    },
    {
      simplified: "开",
      traditional: "開",
      pinyin: "kāi",
      english: "Open",
    },
    {
      simplified: "文",
      traditional: "文",
      pinyin: "wén",
      english: "Text",
    },
    {
      simplified: "你",
      traditional: "你",
      pinyin: "nǐ",
      english: "You",
    },
    {
      simplified: "来",
      traditional: "來",
      pinyin: "lái",
      english: "Come",
    },
    {
      simplified: "是",
      traditional: "是",
      pinyin: "shì",
      english: "Yes",
    },
    {
      simplified: "小",
      traditional: "小",
      pinyin: "xiǎo",
      english: "Small",
    },
    {
      simplified: "姐",
      traditional: "姐",
      pinyin: "jiě",
      english: "Sister",
    },
    {
      simplified: "吗",
      traditional: "嗎",
      pinyin: "mǎ",
      english: "?",
    },
    {
      simplified: "接",
      traditional: "接",
      pinyin: "jiē",
      english: "Pick up",
    },
    {
      simplified: "我",
      traditional: "我",
      pinyin: "wǒ",
      english: "I",
    },
    {
      simplified: "们",
      traditional: "們",
      pinyin: "men",
      english: "We",
    },
    {
      simplified: "这",
      traditional: "這",
      pinyin: "zhè",
      english: "This",
    },
    {
      simplified: "先",
      traditional: "先",
      pinyin: "xiān",
      english: "First",
    },
    {
      simplified: "生",
      traditional: "生",
      pinyin: "shēng",
      english: "Raw",
    },
    {
      simplified: "好",
      traditional: "好",
      pinyin: "hǎo",
      english: "It is good",
    },
    {
      simplified: "姓",
      traditional: "姓",
      pinyin: "xìng",
      english: "Surname",
    },
    {
      simplified: "叫",
      traditional: "叫",
      pinyin: "jiào",
      english: "Call",
    },
    {
      simplified: "台",
      traditional: "臺",
      pinyin: "tái",
      english: "Station",
    },
    {
      simplified: "湾",
      traditional: "灣",
      pinyin: "wān",
      english: "Bay",
    },
    {
      simplified: "欢",
      traditional: "歡",
      pinyin: "huān",
      english: "Huan",
    },
    {
      simplified: "迎",
      traditional: "迎",
      pinyin: "yíng",
      english: "Welcome",
    },
    {
      simplified: "请",
      traditional: "請",
      pinyin: "qǐng",
      english: "Please",
    },
    {
      simplified: "问",
      traditional: "問",
      pinyin: "wèn",
      english: "Ask",
    },
    {
      simplified: "的",
      traditional: "的",
      pinyin: "de",
      english: "Of",
    },
    {
      simplified: "谢",
      traditional: "謝",
      pinyin: "xiè",
      english: "Thank",
    },
    {
      simplified: "不",
      traditional: "不",
      pinyin: "bù",
      english: "Do not",
    },
    {
      simplified: "客",
      traditional: "客",
      pinyin: "kè",
      english: "Customer",
    },
    {
      simplified: "气",
      traditional: "氣",
      pinyin: "qì",
      english: "Gas",
    },
    {
      simplified: "喝",
      traditional: "喝",
      pinyin: "hē",
      english: "Drink",
    },
    {
      simplified: "茶",
      traditional: "茶",
      pinyin: "chá",
      english: "Tea",
    },
  ],
};

export default lesson;
