import { HSKList } from "@src/tools/types";

const lesson: HSKList = {
  list: "8",
  locked: false,
  title: "MTC Book 1 Lesson 1",
  content: [
    {
      simplified: "你",
      traditional: "你",
      pinyin: "nǐ",
      english: "You",
    },
    {
      simplified: "来",
      traditional: "來",
      pinyin: "lái",
      english: "Come",
    },
    {
      simplified: "小姐",
      traditional: "小姐",
      pinyin: "xiǎo jie",
      english: "Miss",
    },
    {
      simplified: "吗",
      traditional: "嗎",
      pinyin: "mǎ",
      english: "?",
    },
    {
      simplified: "接",
      traditional: "接",
      pinyin: "jiē",
      english: "Pick up",
    },
    {
      simplified: "我",
      traditional: "我",
      pinyin: "wǒ",
      english: "I",
    },
    {
      simplified: "我们",
      traditional: "我們",
      pinyin: "wǒ men",
      english: "We",
    },
    {
      simplified: "先生",
      traditional: "先生",
      pinyin: "xiān sheng",
      english: "Mr",
    },
    {
      simplified: "好",
      traditional: "好",
      pinyin: "hǎo",
      english: "It is good",
    },
    {
      simplified: "姓",
      traditional: "姓",
      pinyin: "xìng",
      english: "Surname",
    },
    {
      simplified: "叫",
      traditional: "叫",
      pinyin: "jiào",
      english: "Call",
    },
    {
      simplified: "你们",
      traditional: "你們",
      pinyin: "nǐ men",
      english: "You guys",
    },
    {
      simplified: "台湾",
      traditional: "台灣",
      pinyin: "tái wān",
      english: "Taiwan",
    },
    {
      simplified: "欢迎",
      traditional: "歡迎",
      pinyin: "huān yíng",
      english: "Welcome",
    },
    {
      simplified: "请问",
      traditional: "請問",
      pinyin: "qǐng wèn",
      english: "Excuse me",
    },
    {
      simplified: "是的",
      traditional: "是的",
      pinyin: "shì de",
      english: "Yes",
    },
    {
      simplified: "谢谢",
      traditional: "謝謝",
      pinyin: "xiè xie",
      english: "Thank you",
    },
    {
      simplified: "不客气",
      traditional: "不客氣",
      pinyin: "bù kè qi",
      english: "You&#39;re welcome",
    },
    {
      simplified: "你好",
      traditional: "你好",
      pinyin: "nǐ hǎo",
      english: "Hello there",
    },
    {
      simplified: "请",
      traditional: "請",
      pinyin: "qǐng",
      english: "Please",
    },
    {
      simplified: "喝",
      traditional: "喝",
      pinyin: "hē",
      english: "Drink",
    },
    {
      simplified: "茶",
      traditional: "茶",
      pinyin: "chá",
      english: "Tea",
    },
    {
      simplified: "很",
      traditional: "很",
      pinyin: "hěn",
      english: "Very",
    },
    {
      simplified: "好喝",
      traditional: "好喝",
      pinyin: "hǎo hē",
      english: "Delicious",
    },
    {
      simplified: "什么",
      traditional: "什麼",
      pinyin: "shén me",
      english: "What",
    },
    {
      simplified: "人",
      traditional: "人",
      pinyin: "rén",
      english: "People",
    },
    {
      simplified: "喜欢",
      traditional: "喜歡",
      pinyin: "xǐ huan",
      english: "Like",
    },
    {
      simplified: "呢",
      traditional: "呢",
      pinyin: "ne",
      english: "What",
    },
    {
      simplified: "他",
      traditional: "他",
      pinyin: "tā",
      english: "He",
    },
    {
      simplified: "不",
      traditional: "不",
      pinyin: "bù",
      english: "Do not",
    },
    {
      simplified: "哪",
      traditional: "哪",
      pinyin: "nǎ",
      english: "Where",
    },
    {
      simplified: "要",
      traditional: "要",
      pinyin: "yāo",
      english: "To",
    },
    {
      simplified: "咖啡",
      traditional: "咖啡",
      pinyin: "kā fēi",
      english: "Coffee",
    },
    {
      simplified: "乌龙茶",
      traditional: "烏龍茶",
      pinyin: "wū lóng chá",
      english: "Oolong tea",
    },
    {
      simplified: "日本",
      traditional: "日本",
      pinyin: "rì běn",
      english: "Japan",
    },
    {
      simplified: "美国",
      traditional: "美國",
      pinyin: "měi guó",
      english: "United states",
    },
    {
      simplified: "对不起",
      traditional: "對不起",
      pinyin: "duì bu qǐ",
      english: "Sorry",
    },
    {
      simplified: "哪国",
      traditional: "哪國",
      pinyin: "nǎ",
      english: "Which country",
    },
  ],
};

export default lesson;
