import { HSKList } from "@src/tools/types";

const lesson: HSKList = {
  list: "9",
  locked: false,
  title: "Greetings and Restaurant",
  content: [
    {
      simplified: "最近",
      english: "Recently",
      traditional: "最近",
      pinyin: "zuì jìn",
    },
    {
      simplified: "还不错",
      english: "Not bad",
      traditional: "還不錯",
      pinyin: "Hái bùcuò",
    },
    {
      simplified: "还可以",
      english: "Still alright",
      traditional: "還可以",
      pinyin: "Hái kěyǐ",
    },
    {
      simplified: "很差",
      english: "Very poor",
      traditional: "很差",
      pinyin: "Hěn chà",
    },
    {
      simplified: "关心",
      english: "Care for",
      traditional: "關心",
      pinyin: "guān xīn",
    },
    {
      simplified: "来",
      english: "Come",
      traditional: "來",
      pinyin: "lái",
    },
    {
      simplified: "不好意思",
      english: "Sorry",
      traditional: "不好意思",
      pinyin: "bù hǎo yì si",
    },
    {
      simplified: "我要到",
      english: "I want to",
      traditional: "我要到",
      pinyin: "wǒ yào dào",
    },
    {
      simplified: "稍等",
      english: "Wait a minute",
      traditional: "稍等",
      pinyin: "shāo děng",
    },
    {
      simplified: "司机",
      english: "Driver",
      traditional: "司機",
      pinyin: "sī jī",
    },
    {
      simplified: "直走",
      english: "Go straight",
      traditional: "直走",
      pinyin: "zhí zǒu",
    },
    {
      simplified: "左转",
      english: "Turn left",
      traditional: "左轉",
      pinyin: "zuǒ zhuǎn",
    },
    {
      simplified: "右转",
      english: "Turn right",
      traditional: "右轉",
      pinyin: "yòu zhuǎn",
    },
    {
      simplified: "十字路口",
      english: "Crossroads",
      traditional: "十字路口",
      pinyin: "shí zì lù kǒu",
    },
    {
      simplified: "下班",
      english: "Off work",
      traditional: "下班",
      pinyin: "xià bān",
    },
    {
      simplified: "重要",
      english: "Important",
      traditional: "重要",
      pinyin: "zhòng yào",
    },
    {
      simplified: "宵夜",
      english: "Supper",
      traditional: "宵夜",
      pinyin: "xiāo yè",
    },
    {
      simplified: "附近",
      english: "Nearby",
      traditional: "附近",
      pinyin: "fù jìn",
    },
    {
      simplified: "抵达",
      english: "Arrival",
      traditional: "抵達",
      pinyin: "dǐ dá",
    },
    {
      simplified: "服务生",
      english: "Waiter",
      traditional: "服務生",
      pinyin: "fú wù shēng",
    },
    {
      simplified: "这边",
      english: "Over here",
      traditional: "這邊",
      pinyin: "zhè biān",
    },
    {
      simplified: "那边",
      english: "There",
      traditional: "那邊",
      pinyin: "nà bian",
    },
    {
      simplified: "单点",
      english: "À la carte",
      traditional: "單點",
      pinyin: "dān diǎn",
    },
    {
      simplified: "套餐",
      english: "Package",
      traditional: "套餐",
      pinyin: "tào cān",
    },
    {
      simplified: "开胃菜",
      english: "Appetizer",
      traditional: "開胃菜",
      pinyin: "kāi wèi cài",
    },
    {
      simplified: "汤",
      english: "Soup",
      traditional: "湯",
      pinyin: "tāng",
    },
    {
      simplified: "沙拉",
      english: "Salad",
      traditional: "沙拉",
      pinyin: "shā lā",
    },
    {
      simplified: "饮料",
      english: "Drink",
      traditional: "飲料",
      pinyin: "yǐn liào",
    },
    {
      simplified: "甜点",
      english: "Dessert",
      traditional: "甜點",
      pinyin: "tián diǎn",
    },
    {
      simplified: "人气",
      english: "Popularity",
      traditional: "人氣",
      pinyin: "rén qì",
    },
    {
      simplified: "主厨",
      english: "Chef",
      traditional: "主廚",
      pinyin: "zhǔ chú",
    },
    {
      simplified: "推荐",
      english: "Recommend",
      traditional: "推薦",
      pinyin: "tuī jiàn",
    },
    {
      simplified: "讨论",
      english: "Discuss",
      traditional: "討論",
      pinyin: "tǎo lùn",
    },
    {
      simplified: "过来",
      english: "Come",
      traditional: "過來",
      pinyin: "guò lái",
    },
    {
      simplified: "过",
      english: "Over",
      traditional: "過",
      pinyin: "guò",
    },
    {
      simplified: "下班后",
      english: "After work",
      traditional: "下班後",
      pinyin: "xià bān hòu",
    },
    {
      simplified: "走吧",
      english: "Let's go",
      traditional: "走吧",
      pinyin: "zǒu ba",
    },
    {
      simplified: "两位",
      english: "Two people",
      traditional: "兩位",
      pinyin: "liǎng wèi",
    },
    {
      simplified: "这边请",
      english: "This way please",
      traditional: "這邊請",
      pinyin: "zhè biān qǐng",
    },
    {
      simplified: "好的",
      english: "Ok",
      traditional: "好的",
      pinyin: "hǎo de",
    },
    {
      simplified: "你们有几位呢",
      english: "How many of you",
      traditional: "你們有幾位呢",
      pinyin: "nǐmen yǒu jǐ wèi ne",
    },
  ],
};

export default lesson;
