import { HSKList } from "@src/tools/types";

const lesson: HSKList = {
  list: "9",
  locked: false,
  title: "Book 1 Lesson 2",
  content: [
    {
      simplified: "的",
      traditional: "的",
      pinyin: "de",
      english: "Of",
    },
    {
      simplified: "家人",
      traditional: "家人",
      pinyin: "jiā rén",
      english: "Family",
    },
    {
      simplified: "家",
      traditional: "家",
      pinyin: "jiā",
      english: "Family",
    },
    {
      simplified: "漂亮",
      traditional: "漂亮",
      pinyin: "piào liang",
      english: "Pretty",
    },
    {
      simplified: "房子",
      traditional: "房子",
      pinyin: "fáng zi",
      english: "House",
    },
    {
      simplified: "坐",
      traditional: "坐",
      pinyin: "zuò",
      english: "Sit",
    },
    {
      simplified: "有",
      traditional: "有",
      pinyin: "yǒu",
      english: "Have",
    },
    {
      simplified: "多",
      traditional: "多",
      pinyin: "duō",
      english: "Many",
    },
    {
      simplified: "照片",
      traditional: "照片",
      pinyin: "zhào piàn",
      english: "Photo",
    },
    {
      simplified: "都",
      traditional: "都",
      pinyin: "dū",
      english: "All",
    },
    {
      simplified: "照相",
      traditional: "照相",
      pinyin: "zhào xiàng",
      english: "Take pictures",
    },
    {
      simplified: "张",
      traditional: "張",
      pinyin: "zhāng",
      english: "Zhang",
    },
    {
      simplified: "好看",
      traditional: "好看",
      pinyin: "hǎo kàn",
      english: "Good looking",
    },
    {
      simplified: "谁",
      traditional: "誰",
      pinyin: "shéi",
      english: "Who",
    },
    {
      simplified: "姐姐",
      traditional: "姐姐",
      pinyin: "jiě jie",
      english: "Sister",
    },
    {
      simplified: "妹妹",
      traditional: "妹妹",
      pinyin: "mèi mei",
      english: "Younger sister",
    },
    {
      simplified: "爸爸",
      traditional: "爸爸",
      pinyin: "bà ba",
      english: "Father",
    },
    {
      simplified: "妈妈",
      traditional: "媽媽",
      pinyin: "mā ma",
      english: "Mom",
    },
    {
      simplified: "请进",
      traditional: "請進",
      pinyin: "qǐng jìn",
      english: "Come in",
    },
    {
      simplified: "伯母",
      traditional: "伯母",
      pinyin: "bó mǔ",
      english: "Aunt",
    },
    {
      simplified: "您",
      traditional: "您",
      pinyin: "nín",
      english: "You",
    },
    {
      simplified: "名字",
      traditional: "名字",
      pinyin: "míng zi",
      english: "First name",
    },
    {
      simplified: "书",
      traditional: "書",
      pinyin: "shū",
      english: "Book",
    },
    {
      simplified: "哥哥",
      traditional: "哥哥",
      pinyin: "gē ge",
      english: "Brother",
    },
    {
      simplified: "老师",
      traditional: "老師",
      pinyin: "lǎo shī",
      english: "Teacher",
    },
    {
      simplified: "看书",
      traditional: "看書",
      pinyin: "kàn shū",
      english: "Read a book",
    },
    {
      simplified: "几",
      traditional: "幾",
      pinyin: "jī",
      english: "A few",
    },
    {
      simplified: "个",
      traditional: "個",
      pinyin: "gè",
      english: "Each",
    },
    {
      simplified: "没",
      traditional: "沒",
      pinyin: "méi",
      english: "No",
    },
    {
      simplified: "兄弟",
      traditional: "兄弟",
      pinyin: "xiōng dì",
      english: "Brothers",
    },
    {
      simplified: "姐妹",
      traditional: "姐妹",
      pinyin: "jiě mèi",
      english: "Sisters",
    },
    {
      simplified: "五",
      traditional: "五",
      pinyin: "wǔ",
      english: "Five",
    },
    {
      simplified: "两",
      traditional: "兩",
      pinyin: "liǎng",
      english: "Two",
    },
  ],
  dictation: [
    {
      simplified: "张",
      traditional: "張",
      pinyin: "zhāng",
      english: "Zhang",
    },
    {
      simplified: "怡",
      traditional: "怡",
      pinyin: "yí",
      english: "Yi",
    },
    {
      simplified: "君",
      traditional: "君",
      pinyin: "jūn",
      english: "Jun",
    },
    {
      simplified: "马",
      traditional: "馬",
      pinyin: "mǎ",
      english: "Horse",
    },
    {
      simplified: "安",
      traditional: "安",
      pinyin: "ān",
      english: "An",
    },
    {
      simplified: "同",
      traditional: "同",
      pinyin: "tòng",
      english: "With",
    },
    {
      simplified: "家",
      traditional: "家",
      pinyin: "jiā",
      english: "Family",
    },
    {
      simplified: "票",
      traditional: "票",
      pinyin: "piào",
      english: "Ticket",
    },
    {
      simplified: "亮",
      traditional: "亮",
      pinyin: "liàng",
      english: "Bright",
    },
    {
      simplified: "房",
      traditional: "房",
      pinyin: "fáng",
      english: "Room",
    },
    {
      simplified: "子",
      traditional: "子",
      pinyin: "zǐ",
      english: "Child",
    },
    {
      simplified: "坐",
      traditional: "坐",
      pinyin: "zuò",
      english: "Sit",
    },
    {
      simplified: "有",
      traditional: "有",
      pinyin: "yǒu",
      english: "Have",
    },
    {
      simplified: "多",
      traditional: "多",
      pinyin: "duō",
      english: "Many",
    },
    {
      simplified: "照",
      traditional: "照",
      pinyin: "zhào",
      english: "According to",
    },
    {
      simplified: "片",
      traditional: "片",
      pinyin: "piān",
      english: "Sheet",
    },
    {
      simplified: "都",
      traditional: "都",
      pinyin: "dū",
      english: "All",
    },
    {
      simplified: "相",
      traditional: "相",
      pinyin: "xiāng",
      english: "Phase",
    },
    {
      simplified: "看",
      traditional: "看",
      pinyin: "kān",
      english: "Look",
    },
    {
      simplified: "谁",
      traditional: "誰",
      pinyin: "shéi",
      english: "Who",
    },
    {
      simplified: "妹",
      traditional: "妹",
      pinyin: "mèi",
      english: "Sister",
    },
    {
      simplified: "爸",
      traditional: "爸",
      pinyin: "bà",
      english: "Dad",
    },
    {
      simplified: "妈",
      traditional: "媽",
      pinyin: "mā",
      english: "Mom",
    },
    {
      simplified: "进",
      traditional: "進",
      pinyin: "jìn",
      english: "Enter",
    },
    {
      simplified: "田",
      traditional: "田",
      pinyin: "tián",
      english: "Field",
    },
    {
      simplified: "中",
      traditional: "中",
      pinyin: "zhōng",
      english: "In",
    },
    {
      simplified: "诚",
      traditional: "誠",
      pinyin: "chéng",
      english: "Honest",
    },
    {
      simplified: "一",
      traditional: "一",
      pinyin: "yī",
      english: "One",
    },
    {
      simplified: "伯",
      traditional: "伯",
      pinyin: "bà",
      english: "Bo",
    },
    {
      simplified: "母",
      traditional: "母",
      pinyin: "mǔ",
      english: "Mother",
    },
    {
      simplified: "您",
      traditional: "您",
      pinyin: "nín",
      english: "You",
    },
    {
      simplified: "名",
      traditional: "名",
      pinyin: "míng",
      english: "Name",
    },
    {
      simplified: "字",
      traditional: "字",
      pinyin: "zì",
      english: "Word",
    },
    {
      simplified: "书",
      traditional: "書",
      pinyin: "shū",
      english: "Book",
    },
    {
      simplified: "哥",
      traditional: "哥",
      pinyin: "gē",
      english: "Brother",
    },
    {
      simplified: "老",
      traditional: "老",
      pinyin: "lǎo",
      english: "Old",
    },
    {
      simplified: "师",
      traditional: "師",
      pinyin: "shī",
      english: "Division",
    },
    {
      simplified: "几",
      traditional: "幾",
      pinyin: "jī",
      english: "A few",
    },
    {
      simplified: "个",
      traditional: "個",
      pinyin: "gè",
      english: "Each",
    },
    {
      simplified: "没",
      traditional: "沒",
      pinyin: "méi",
      english: "No",
    },
    {
      simplified: "兄",
      traditional: "兄",
      pinyin: "xiōng",
      english: "Brother",
    },
    {
      simplified: "弟",
      traditional: "弟",
      pinyin: "dì",
      english: "Younger brother",
    },
    {
      simplified: "五",
      traditional: "五",
      pinyin: "wǔ",
      english: "Fives",
    },
    {
      simplified: "两",
      traditional: "兩",
      pinyin: "liǎng",
      english: "Two",
    },
  ],
};

export default lesson;
