import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "qaAR6U7k8Q",
  type: "Contemporary Chinese",
  list: "9",
  locked: false,
  title: "Lesson 7",
  content: [
    {
      simplified: "点",
      traditional: "點",
      pinyin: "diǎn",
      english: "O'clock",
    },
    {
      simplified: "唱歌",
      traditional: "唱歌",
      pinyin: "chàng gē",
      english: "Sing",
    },
    {
      simplified: "分",
      traditional: "分",
      pinyin: "fēn",
      english: "Minute",
    },
    {
      simplified: "见面",
      traditional: "見面",
      pinyin: "jiàn miàn",
      english: "Meet",
    },
    {
      simplified: "从",
      traditional: "從",
      pinyin: "cóng",
      english: "From",
    },
    {
      simplified: "中午",
      traditional: "中午",
      pinyin: "zhōngwǔ",
      english: "Noon",
    },
    {
      simplified: "得",
      traditional: "得",
      pinyin: "dé",
      english: "Get",
    },
    {
      simplified: "银行",
      traditional: "銀行",
      pinyin: "yín háng",
      english: "Bank",
    },
    {
      simplified: "时候",
      traditional: "時候",
      pinyin: "shíhòu",
      english: "Time",
    },
    {
      simplified: "后天",
      traditional: "後天",
      pinyin: "hòutiān",
      english: "Day after tomorrow",
    },
    {
      simplified: "大安",
      traditional: "大安",
      pinyin: "dà'ān",
      english: "Daan",
    },
    {
      simplified: "下次",
      traditional: "下次",
      pinyin: "xià cì",
      english: "Next time",
    },
    {
      simplified: "没问题",
      traditional: "沒問題",
      pinyin: "méi wèntí",
      english: "No problem",
    },
    {
      simplified: "对了",
      traditional: "對了",
      pinyin: "duìle",
      english: "Correct",
    },
    {
      simplified: "有空",
      traditional: "有空",
      pinyin: "yǒu kòng",
      english: "Free",
    },
    {
      simplified: "再见",
      traditional: "再見",
      pinyin: "zàijiàn",
      english: "Goodbye",
    },
    {
      simplified: "午餐",
      traditional: "午餐",
      pinyin: "wǔcān",
      english: "Lunch",
    },
    {
      simplified: "刚",
      traditional: "剛",
      pinyin: "gāng",
      english: "Just",
    },
    {
      simplified: "下课",
      traditional: "下課",
      pinyin: "xiàkè",
      english: "After class",
    },
    {
      simplified: "下午",
      traditional: "下午",
      pinyin: "xiàwǔ",
      english: "In the afternoon",
    },
    {
      simplified: "半",
      traditional: "半",
      pinyin: "bàn",
      english: "Half",
    },
    {
      simplified: "比赛",
      traditional: "比賽",
      pinyin: "bǐsài",
      english: "Game",
    },
    {
      simplified: "结束",
      traditional: "結束",
      pinyin: "jiéshù",
      english: "End",
    },
    {
      simplified: "最近",
      traditional: "最近",
      pinyin: "zuì jìn",
      english: "Recent",
    },
    {
      simplified: "忙",
      traditional: "忙",
      pinyin: "máng",
      english: "Busy",
    },
    {
      simplified: "每",
      traditional: "每",
      pinyin: "měi",
      english: "Each",
    },
    {
      simplified: "天",
      traditional: "天",
      pinyin: "tiān",
      english: "Day",
    },
    {
      simplified: "书法",
      traditional: "書法",
      pinyin: "shū fǎ",
      english: "Calligraphy",
    },
    {
      simplified: "课",
      traditional: "課",
      pinyin: "kè",
      english: "Class",
    },
    {
      simplified: "开始",
      traditional: "開始",
      pinyin: "kāi shǐ",
      english: "Start",
    },
    {
      simplified: "字",
      traditional: "字",
      pinyin: "zì",
      english: "Word",
    },
    {
      simplified: "写",
      traditional: "寫",
      pinyin: "xiě",
      english: "Write",
    },
    {
      simplified: "可以",
      traditional: "可以",
      pinyin: "kě yǐ",
      english: "Can",
    },
    {
      simplified: "问",
      traditional: "問",
      pinyin: "wèn",
      english: "Ask",
    },
    {
      simplified: "等一下",
      traditional: "等一下",
      pinyin: "děng yī xià",
      english: "Wait",
    },
    {
      simplified: "有事",
      traditional: "有事",
      pinyin: "yǒu shì",
      english: "Something",
    },
    {
      simplified: "有意思",
      traditional: "有意思",
      pinyin: "yǒu yì si",
      english: "Interesting",
    },
  ],
};

export default lesson;
