import { HSKList } from "@src/tools/types";

const lesson: HSKList = {
  list: "11",
  locked: false,
  title: "MTC Book 1 Lesson 3",
  content: [
    {
      simplified: "周末",
      traditional: "週末",
      pinyin: "zhōu mò",
      english: "Weekend",
    },
    {
      simplified: "听",
      traditional: "聽",
      pinyin: "tīng",
      english: "Listen",
    },
    {
      simplified: "音乐",
      traditional: "音樂",
      pinyin: "yīn yuè",
      english: "Music",
    },
    {
      simplified: "运动",
      traditional: "運動",
      pinyin: "yùn dòng",
      english: "Motion",
    },
    {
      simplified: "打",
      traditional: "打",
      pinyin: "dá",
      english: "Hit",
    },
    {
      simplified: "网球",
      traditional: "網球",
      pinyin: "wǎng qiú",
      english: "Tennis",
    },
    {
      simplified: "棒球",
      traditional: "棒球",
      pinyin: "bàng qiú",
      english: "Baseball",
    },
    {
      simplified: "和",
      traditional: "和",
      pinyin: "hé",
      english: "With",
    },
    {
      simplified: "游泳",
      traditional: "游泳",
      pinyin: "yóu yǒng",
      english: "Swim",
    },
    {
      simplified: "常",
      traditional: "常",
      pinyin: "cháng",
      english: "Often",
    },
    {
      simplified: "篮球",
      traditional: "籃球",
      pinyin: "lán qiú",
      english: "Basketball",
    },
    {
      simplified: "也",
      traditional: "也",
      pinyin: "yě",
      english: "And also",
    },
    {
      simplified: "踢",
      traditional: "踢",
      pinyin: "tī",
      english: "Kick",
    },
    {
      simplified: "足球",
      traditional: "足球",
      pinyin: "zú qiú",
      english: "Football",
    },
    {
      simplified: "觉得",
      traditional: "覺得",
      pinyin: "jué de",
      english: "Feel",
    },
    {
      simplified: "好玩",
      traditional: "好玩",
      pinyin: "hǎo wán",
      english: "Fun",
    },
    {
      simplified: "明天",
      traditional: "明天",
      pinyin: "míng tiān",
      english: "Tomorrow",
    },
    {
      simplified: "早上",
      traditional: "早上",
      pinyin: "zǎo shang",
      english: "Morning",
    },
    {
      simplified: "去",
      traditional: "去",
      pinyin: "qù",
      english: "Go with",
    },
    {
      simplified: "怎么样",
      traditional: "怎麼樣",
      pinyin: "zěn me yàng",
      english: "How about it",
    },
    {
      simplified: "啊",
      traditional: "啊",
      pinyin: "ā",
      english: "What",
    },
    {
      simplified: "做什么",
      traditional: "做什麼",
      pinyin: "zuò shén me",
      english: "Doing what",
    },
    {
      simplified: "好啊",
      traditional: "好啊",
      pinyin: "hǎo",
      english: "Alright",
    },
    {
      simplified: "今天",
      traditional: "今天",
      pinyin: "jīn tiān",
      english: "Nowadays",
    },
    {
      simplified: "晚上",
      traditional: "晚上",
      pinyin: "wǎn shang",
      english: "At night",
    },
    {
      simplified: "看",
      traditional: "看",
      pinyin: "kān",
      english: "Look",
    },
    {
      simplified: "电影",
      traditional: "電影",
      pinyin: "diàn yǐng",
      english: "The film",
    },
    {
      simplified: "妳",
      traditional: "妳",
      pinyin: "nǎi",
      english: "You",
    },
    {
      simplified: "想",
      traditional: "想",
      pinyin: "xiǎng",
      english: "Miss you",
    },
    {
      simplified: "还是",
      traditional: "還是",
      pinyin: "hái shi",
      english: "Still is",
    },
    {
      simplified: "吧",
      traditional: "吧",
      pinyin: "bā",
      english: "Right",
    },
    {
      simplified: "可以",
      traditional: "可以",
      pinyin: "kě yǐ",
      english: "Can",
    },
    {
      simplified: "学",
      traditional: "學",
      pinyin: "xué",
      english: "Learn",
    },
    {
      simplified: "中文",
      traditional: "中文",
      pinyin: "zhōng wén",
      english: "Chinese",
    },
    {
      simplified: "一起",
      traditional: "一起",
      pinyin: "yī qǐ",
      english: "Together",
    },
    {
      simplified: "吃",
      traditional: "吃",
      pinyin: "chī",
      english: "Eat",
    },
    {
      simplified: "晚饭",
      traditional: "晚飯",
      pinyin: "wǎn fàn",
      english: "Dinner",
    },
    {
      simplified: "菜",
      traditional: "菜",
      pinyin: "cài",
      english: "Dish",
    },
    {
      simplified: "越南",
      traditional: "越南",
      pinyin: "yuè nán",
      english: "Vietnam",
    },
    {
      simplified: "周末",
      traditional: "週末",
      pinyin: "zhōu mò",
      english: "Weekend",
    },
    {
      simplified: "听",
      traditional: "聽",
      pinyin: "tīng",
      english: "Listen",
    },
    {
      simplified: "音乐",
      traditional: "音樂",
      pinyin: "yīn yuè",
      english: "Music",
    },
    {
      simplified: "运动",
      traditional: "運動",
      pinyin: "yùn dòng",
      english: "Motion",
    },
    {
      simplified: "打",
      traditional: "打",
      pinyin: "dá",
      english: "Hit",
    },
    {
      simplified: "网球",
      traditional: "網球",
      pinyin: "wǎng qiú",
      english: "Tennis",
    },
    {
      simplified: "棒球",
      traditional: "棒球",
      pinyin: "bàng qiú",
      english: "Baseball",
    },
    {
      simplified: "和",
      traditional: "和",
      pinyin: "hé",
      english: "With",
    },
    {
      simplified: "游泳",
      traditional: "游泳",
      pinyin: "yóu yǒng",
      english: "Swim",
    },
    {
      simplified: "常",
      traditional: "常",
      pinyin: "cháng",
      english: "Often",
    },
    {
      simplified: "篮球",
      traditional: "籃球",
      pinyin: "lán qiú",
      english: "Basketball",
    },
    {
      simplified: "也",
      traditional: "也",
      pinyin: "yě",
      english: "And also",
    },
    {
      simplified: "踢",
      traditional: "踢",
      pinyin: "tī",
      english: "Kick",
    },
    {
      simplified: "足球",
      traditional: "足球",
      pinyin: "zú qiú",
      english: "Football",
    },
    {
      simplified: "觉得",
      traditional: "覺得",
      pinyin: "jué de",
      english: "Feel",
    },
    {
      simplified: "好玩",
      traditional: "好玩",
      pinyin: "hǎo wán",
      english: "Fun",
    },
    {
      simplified: "明天",
      traditional: "明天",
      pinyin: "míng tiān",
      english: "Tomorrow",
    },
    {
      simplified: "早上",
      traditional: "早上",
      pinyin: "zǎo shang",
      english: "Morning",
    },
    {
      simplified: "去",
      traditional: "去",
      pinyin: "qù",
      english: "Go with",
    },
    {
      simplified: "怎么样",
      traditional: "怎麼樣",
      pinyin: "zěn me yàng",
      english: "How about it",
    },
    {
      simplified: "啊",
      traditional: "啊",
      pinyin: "ā",
      english: "What",
    },
    {
      simplified: "做什么",
      traditional: "做什麼",
      pinyin: "zuò shén me",
      english: "Doing what",
    },
    {
      simplified: "好啊",
      traditional: "好啊",
      pinyin: "hǎo",
      english: "Alright",
    },
    {
      simplified: "今天",
      traditional: "今天",
      pinyin: "jīn tiān",
      english: "Nowadays",
    },
    {
      simplified: "晚上",
      traditional: "晚上",
      pinyin: "wǎn shang",
      english: "At night",
    },
    {
      simplified: "看",
      traditional: "看",
      pinyin: "kān",
      english: "Look",
    },
    {
      simplified: "电影",
      traditional: "電影",
      pinyin: "diàn yǐng",
      english: "The film",
    },
    {
      simplified: "妳",
      traditional: "妳",
      pinyin: "nǎi",
      english: "You",
    },
    {
      simplified: "想",
      traditional: "想",
      pinyin: "xiǎng",
      english: "Miss you",
    },
    {
      simplified: "还是",
      traditional: "還是",
      pinyin: "hái shi",
      english: "Still is",
    },
    {
      simplified: "吧",
      traditional: "吧",
      pinyin: "bā",
      english: "Right",
    },
    {
      simplified: "可以",
      traditional: "可以",
      pinyin: "kě yǐ",
      english: "Can",
    },
    {
      simplified: "学",
      traditional: "學",
      pinyin: "xué",
      english: "Learn",
    },
    {
      simplified: "中文",
      traditional: "中文",
      pinyin: "zhōng wén",
      english: "Chinese",
    },
    {
      simplified: "一起",
      traditional: "一起",
      pinyin: "yī qǐ",
      english: "Together",
    },
    {
      simplified: "吃",
      traditional: "吃",
      pinyin: "chī",
      english: "Eat",
    },
    {
      simplified: "晚饭",
      traditional: "晚飯",
      pinyin: "wǎn fàn",
      english: "Dinner",
    },
    {
      simplified: "菜",
      traditional: "菜",
      pinyin: "cài",
      english: "Dish",
    },
    {
      simplified: "越南",
      traditional: "越南",
      pinyin: "yuè nán",
      english: "Vietnam",
    },
  ],
};

export default lesson;
