import { HSKList } from "@src/tools/types";

const lesson: HSKList = {
  list: "11",
  locked: false,
  title: "MTC Book 1 Lesson 4",
  content: [
    {
      simplified: "一共",
      traditional: "一共",
      pinyin: "yī gòng",
      english: "In total",
    },
    {
      simplified: "多少",
      traditional: "多少",
      pinyin: "duō shǎo",
      english: "How many",
    },
    {
      simplified: "",
      traditional: "錢",
      pinyin: "qián",
      english: "",
    },
    {
      simplified: "老板",
      traditional: "老闆",
      pinyin: "lǎo bǎn",
      english: "",
    },
    {
      simplified: "",
      traditional: "買",
      pinyin: "mǎi",
      english: "",
    },
    {
      simplified: "",
      traditional: "杯",
      pinyin: "bēi",
      english: "",
    },
    {
      simplified: "",
      traditional: "熱",
      pinyin: "rè",
      english: "",
    },
    {
      simplified: "",
      traditional: "包子",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "要",
      pinyin: "yāo",
      english: "",
    },
    {
      simplified: "大",
      traditional: "大",
      pinyin: "",
      english: "Big",
    },
    {
      simplified: "中",
      traditional: "中",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "小",
      pinyin: "xiǎo",
      english: "Small",
    },
    {
      simplified: "",
      traditional: "棒",
      pinyin: "bàng",
      english: "",
    },
    {
      simplified: "微波",
      traditional: "微波",
      pinyin: "wēi bō",
      english: "",
    },
    {
      simplified: "百",
      traditional: "百",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "塊",
      pinyin: "kuài",
      english: "",
    },
    {
      simplified: "",
      traditional: "好的",
      pinyin: "hǎo",
      english: "Ok",
    },
    {
      simplified: "",
      traditional: "外帶",
      pinyin: "wài dài",
      english: "",
    },
    {
      simplified: "",
      traditional: "內用",
      pinyin: "nèi yòng",
      english: "",
    },
    {
      simplified: "",
      traditional: "支",
      pinyin: "",
      english: "Support",
    },
    {
      simplified: "新",
      traditional: "新",
      pinyin: "xīn",
      english: "New",
    },
    {
      simplified: "",
      traditional: "手機",
      pinyin: "shǒu jī",
      english: "",
    },
    {
      simplified: "太",
      traditional: "太",
      pinyin: "tài",
      english: "Too",
    },
    {
      simplified: "",
      traditional: "舊",
      pinyin: "jiù",
      english: "Old",
    },
    {
      simplified: "",
      traditional: "了",
      pinyin: "liǎo",
      english: "",
    },
    {
      simplified: "种",
      traditional: "種",
      pinyin: "zhǒng",
      english: "",
    },
    {
      simplified: "",
      traditional: "能",
      pinyin: "néng",
      english: "Can",
    },
    {
      simplified: "上网",
      traditional: "上網",
      pinyin: "shàng wǎng",
      english: "",
    },
    {
      simplified: "",
      traditional: "那",
      pinyin: "nā",
      english: "That",
    },
    {
      simplified: "贵",
      traditional: "貴",
      pinyin: "guì",
      english: "Expensive",
    },
    {
      simplified: "",
      traditional: "賣",
      pinyin: "mài",
      english: "Sell",
    },
    {
      simplified: "便宜",
      traditional: "便宜",
      pinyin: "biàn yí",
      english: "Cheap",
    },
    {
      simplified: "万",
      traditional: "萬",
      pinyin: "wàn",
      english: "Million",
    },
    {
      simplified: "千",
      traditional: "千",
      pinyin: "qiān",
      english: "Thousand",
    },
  ],
  dictation: [
    {
      simplified: "共",
      traditional: "共",
      pinyin: "gòng",
      english: "Total",
    },
    {
      simplified: "少",
      traditional: "少",
      pinyin: "shǎo",
      english: "Less",
    },
    {
      simplified: "钱",
      traditional: "錢",
      pinyin: "qián",
      english: "Money",
    },
    {
      simplified: "板",
      traditional: "闆",
      pinyin: "bǎn",
      english: "Board",
    },
    {
      simplified: "买",
      traditional: "買",
      pinyin: "mǎi",
      english: "Buy",
    },
    {
      simplified: "被",
      traditional: "被",
      pinyin: "bèi",
      english: "Be",
    },
    {
      simplified: "热",
      traditional: "熱",
      pinyin: "rè",
      english: "Heat",
    },
    {
      simplified: "包",
      traditional: "包",
      pinyin: "bāo",
      english: "Package",
    },
    {
      simplified: "大",
      traditional: "大",
      pinyin: "dà",
      english: "Big",
    },
    {
      simplified: "帮",
      traditional: "幫",
      pinyin: "bāng",
      english: "Help",
    },
    {
      simplified: "微",
      traditional: "微",
      pinyin: "wēi",
      english: "Micro-",
    },
    {
      simplified: "波",
      traditional: "波",
      pinyin: "bō",
      english: "Wave",
    },
    {
      simplified: "百",
      traditional: "百",
      pinyin: "bǎi",
      english: "Hundred",
    },
    {
      simplified: "块",
      traditional: "塊",
      pinyin: "kuài",
      english: "Piece",
    },
    {
      simplified: "外",
      traditional: "外",
      pinyin: "wài",
      english: "Outer",
    },
    {
      simplified: "带",
      traditional: "帶",
      pinyin: "dài",
      english: "Band",
    },
    {
      simplified: "内",
      traditional: "內",
      pinyin: "nèi",
      english: "Inside",
    },
    {
      simplified: "用",
      traditional: "用",
      pinyin: "yòng",
      english: "Use",
    },
    {
      simplified: "支",
      traditional: "支",
      pinyin: "zhī",
      english: "Support",
    },
    {
      simplified: "新",
      traditional: "新",
      pinyin: "xīn",
      english: "New",
    },
    {
      simplified: "手",
      traditional: "手",
      pinyin: "shǒu",
      english: "Hand",
    },
    {
      simplified: "几",
      traditional: "幾",
      pinyin: "jī",
      english: "A few",
    },
    {
      simplified: "太",
      traditional: "太",
      pinyin: "tài",
      english: "Too",
    },
    {
      simplified: "旧",
      traditional: "舊",
      pinyin: "jiù",
      english: "Old",
    },
    {
      simplified: "了",
      traditional: "了",
      pinyin: "liǎo",
      english: "Off",
    },
    {
      simplified: "种",
      traditional: "種",
      pinyin: "zhǒng",
      english: "Species",
    },
    {
      simplified: "能",
      traditional: "能",
      pinyin: "néng",
      english: "Can",
    },
    {
      simplified: "那",
      traditional: "那",
      pinyin: "nā",
      english: "That",
    },
    {
      simplified: "贵",
      traditional: "貴",
      pinyin: "guì",
      english: "Expensive",
    },
    {
      simplified: "卖",
      traditional: "賣",
      pinyin: "mài",
      english: "Sell",
    },
    {
      simplified: "便",
      traditional: "便",
      pinyin: "biàn",
      english: "Then",
    },
    {
      simplified: "宜",
      traditional: "宜",
      pinyin: "yí",
      english: "Should",
    },
    {
      simplified: "万",
      traditional: "萬",
      pinyin: "wàn",
      english: "Million",
    },
    {
      simplified: "千",
      traditional: "千",
      pinyin: "qiān",
      english: "Thousand",
    },
    {
      simplified: "为",
      traditional: "為",
      pinyin: "wéi",
      english: "For",
    },
  ],
};

export default lesson;
