import { HSKList } from "@src/tools/types";
const lesson: HSKList = {
  list: "11",
  locked: false,
  title: "MTC Book 1 Lesson 3",
  content: [
    {
      simplified: "",
      traditional: "週末",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "聽",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "音樂",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "運動",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "打",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "網球",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "棒球",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "和",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "游泳",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "常",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "籃球",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "也",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "踢",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "足球",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "覺得",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "好玩",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "明天",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "早上",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "去",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "怎麼樣",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "啊",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "做什麼",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "好啊",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "今天",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "晚上",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "看",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "電影",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "妳",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "想",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "還是",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "吧",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "可以",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "學",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "中文",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "一起",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "吃",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "晚飯",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "菜",
      pinyin: "",
      english: "",
    },
    {
      simplified: "",
      traditional: "越南",
      pinyin: "",
      english: "",
    },
  ],
};

export default lesson;
