import { HSKList } from "@src/tools/types";

const lesson: HSKList = {
  list: "12",
  locked: false,
  title: "MTC Book 1 Lesson 5",
  content: [
    {
      simplified: "",
      traditional: "牛肉",
      pinyin: "niú ròu",
      english: "Beef",
    },
    {
      simplified: "面",
      traditional: "麵",
      pinyin: "miàn",
      english: "",
    },
    {
      simplified: "",
      traditional: "真",
      pinyin: "zhēn",
      english: "",
    },
    {
      simplified: "",
      traditional: "好吃",
      pinyin: "hǎo chī",
      english: "",
    },
    {
      simplified: "",
      traditional: "說",
      pinyin: "shuì",
      english: "Say",
    },
    {
      simplified: "少",
      traditional: "少",
      pinyin: "shǎo",
      english: "",
    },
    {
      simplified: "",
      traditional: "有名",
      pinyin: "yǒu míng",
      english: "",
    },
    {
      simplified: "",
      traditional: "小吃",
      pinyin: "xiǎo chī",
      english: "",
    },
    {
      simplified: "",
      traditional: "最",
      pinyin: "zuì",
      english: "",
    },
    {
      simplified: "汤",
      traditional: "湯",
      pinyin: "tāng",
      english: "",
    },
    {
      simplified: "",
      traditional: "這麼",
      pinyin: "zhè me",
      english: "",
    },
    {
      simplified: "",
      traditional: "知道",
      pinyin: "zhī dào",
      english: "",
    },
    {
      simplified: "",
      traditional: "家",
      pinyin: "jiā",
      english: "Family",
    },
    {
      simplified: "",
      traditional: "店",
      pinyin: "diàn",
      english: "",
    },
    {
      simplified: "一定",
      traditional: "一定",
      pinyin: "yī dìng",
      english: "",
    },
    {
      simplified: "",
      traditional: "點",
      pinyin: "diǎn",
      english: "",
    },
    {
      simplified: "",
      traditional: "碗",
      pinyin: "wǎn",
      english: "",
    },
    {
      simplified: "是啊",
      traditional: "是啊",
      pinyin: "shì ",
      english: "",
    },
    {
      simplified: "",
      traditional: "小籠包",
      pinyin: "xiǎo lóng bāo",
      english: "",
    },
    {
      simplified: "臭豆腐",
      traditional: "臭豆腐",
      pinyin: "chòu dòu fu",
      english: "",
    },
    {
      simplified: "",
      traditional: "太好了",
      pinyin: "tài hǎo le",
      english: "",
    },
    {
      simplified: "昨天",
      traditional: "昨天",
      pinyin: "zuó tiān",
      english: "",
    },
    {
      simplified: "",
      traditional: "餐廳",
      pinyin: "cān tīng",
      english: "",
    },
    {
      simplified: "",
      traditional: "可是",
      pinyin: "kě shì",
      english: "",
    },
    {
      simplified: "",
      traditional: "辣",
      pinyin: "là",
      english: "",
    },
    {
      simplified: "怕",
      traditional: "怕",
      pinyin: "pà",
      english: "Afraid",
    },
    {
      simplified: "所以",
      traditional: "所以",
      pinyin: "suǒ yǐ",
      english: "And so",
    },
    {
      simplified: "",
      traditional: "自己",
      pinyin: "zì jǐ",
      english: "",
    },
    {
      simplified: "",
      traditional: "做飯",
      pinyin: "zuò fàn",
      english: "Cook",
    },
    {
      simplified: "",
      traditional: "得",
      pinyin: "dé",
      english: "",
    },
    {
      simplified: "会",
      traditional: "會",
      pinyin: "huì",
      english: "",
    },
    {
      simplified: "甜点",
      traditional: "甜點",
      pinyin: "tián diǎn",
      english: "Dessert",
    },
    {
      simplified: "不错",
      traditional: "不錯",
      pinyin: "bù cuò",
      english: "Not bad",
    },
    {
      simplified: "",
      traditional: "可以",
      pinyin: "kě yǐ",
      english: "Can",
    },
    {
      simplified: "教",
      traditional: "教",
      pinyin: "jiào",
      english: "Teach",
    },
    {
      simplified: "到",
      traditional: "到",
      pinyin: "dào",
      english: "To",
    },
    {
      simplified: "有一点",
      traditional: "有一點",
      pinyin: "yǒu yī diǎn",
      english: "A little",
    },
    {
      simplified: "不好",
      traditional: "不好",
      pinyin: "bù hǎo",
      english: "Not good",
    },
  ],
  dictation: [
    {
      simplified: "牛",
      traditional: "牛",
      pinyin: "niú",
      english: "Cattle",
    },
    {
      simplified: "肉",
      traditional: "肉",
      pinyin: "ròu",
      english: "Meat",
    },
    {
      simplified: "面",
      traditional: "麵",
      pinyin: "miàn",
      english: "Surface",
    },
    {
      simplified: "真",
      traditional: "真",
      pinyin: "zhēn",
      english: "True",
    },
    {
      simplified: "说",
      traditional: "說",
      pinyin: "shuì",
      english: "Say",
    },
    {
      simplified: "最",
      traditional: "最",
      pinyin: "zuì",
      english: "Most",
    },
    {
      simplified: "汤",
      traditional: "湯",
      pinyin: "tāng",
      english: "Soup",
    },
    {
      simplified: "知",
      traditional: "知",
      pinyin: "zhī",
      english: "Know",
    },
    {
      simplified: "道",
      traditional: "道",
      pinyin: "dào",
      english: "Tao",
    },
    {
      simplified: "店",
      traditional: "店",
      pinyin: "diàn",
      english: "Shop",
    },
    {
      simplified: "定",
      traditional: "定",
      pinyin: "dìng",
      english: "Set",
    },
    {
      simplified: "点",
      traditional: "點",
      pinyin: "diǎn",
      english: "Point",
    },
    {
      simplified: "碗",
      traditional: "碗",
      pinyin: "wǎn",
      english: "Bowl",
    },
    {
      simplified: "龙",
      traditional: "龍",
      pinyin: "lóng",
      english: "Long",
    },
    {
      simplified: "臭",
      traditional: "臭",
      pinyin: "chòu",
      english: "Smelly",
    },
    {
      simplified: "豆",
      traditional: "豆",
      pinyin: "dòu",
      english: "Beans",
    },
    {
      simplified: "腐",
      traditional: "腐",
      pinyin: "fǔ",
      english: "Rot",
    },
    {
      simplified: "昨",
      traditional: "昨",
      pinyin: "zuó",
      english: "Yesterday",
    },
    {
      simplified: "餐",
      traditional: "餐",
      pinyin: "cān",
      english: "Meal",
    },
    {
      simplified: "听",
      traditional: "聽",
      pinyin: "tīng",
      english: "Listen",
    },
    {
      simplified: "辣",
      traditional: "辣",
      pinyin: "là",
      english: "Hot",
    },
    {
      simplified: "怕",
      traditional: "怕",
      pinyin: "pà",
      english: "Afraid",
    },
    {
      simplified: "所",
      traditional: "所",
      pinyin: "suǒ",
      english: "Place",
    },
    {
      simplified: "自",
      traditional: "自",
      pinyin: "zì",
      english: "From",
    },
    {
      simplified: "己",
      traditional: "己",
      pinyin: "jǐ",
      english: "Already",
    },
    {
      simplified: "会",
      traditional: "會",
      pinyin: "huì",
      english: "Meeting",
    },
    {
      simplified: "甜",
      traditional: "甜",
      pinyin: "tián",
      english: "Sweet",
    },
    {
      simplified: "错",
      traditional: "錯",
      pinyin: "cuò",
      english: "Wrong",
    },
    {
      simplified: "教",
      traditional: "教",
      pinyin: "jiào",
      english: "Teach",
    },
    {
      simplified: "到",
      traditional: "到",
      pinyin: "dào",
      english: "To",
    },
  ],
};

export default lesson;
