import { HSKList } from "@src/tools/types";

const lesson: HSKList = {
  list: "12",
  locked: false,
  title: "Far East Lessons 1-6",
  content: [
    {
      simplified: "付",
      traditional: "付",
      pinyin: "fù",
      english: "Pay",
    },
    {
      simplified: "打折",
      traditional: "打折",
      pinyin: "dǎzhé",
      english: "Discount",
    },
    {
      simplified: "刷卡",
      traditional: "刷卡",
      pinyin: "shuākǎ",
      english: "Swipe",
    },
    {
      simplified: "信用卡",
      traditional: "信用卡",
      pinyin: "xìnyòngkǎ",
      english: "Credit card",
    },
    {
      simplified: "收",
      traditional: "收",
      pinyin: "shōu",
      english: "Receive",
    },
    {
      simplified: "那么",
      traditional: "那麼",
      pinyin: "nàme",
      english: "Then",
    },
    {
      simplified: "现金",
      traditional: "現金",
      pinyin: "xiànjīn",
      english: "Cash",
    },
    {
      simplified: "这票",
      traditional: "這票",
      pinyin: "zhè piào",
      english: "Check",
    },
    {
      simplified: "旧",
      traditional: "舊",
      pinyin: "jiù",
      english: "Old",
    },
    {
      simplified: "换",
      traditional: "換",
      pinyin: "To exchange",
      english: "huàn",
    },
    {
      simplified: "美金",
      traditional: "美金",
      pinyin: "US Dollar",
      english: "měijīn",
    },
    {
      simplified: "台币",
      traditional: "台幣",
      pinyin: "Taiwan Dollar",
      english: "táibì",
    },
    {
      simplified: "填表",
      traditional: "填表",
      pinyin: "Fill out the form",
      english: "tián biǎo",
    },
    {
      simplified: "旅行支票",
      traditional: "旅行支票",
      pinyin: "Traveler's check",
      english: "lǚxíng zhīpiào",
    },
    {
      simplified: "約",
      traditional: "约",
      pinyin: "yuē",
      english: "Schedule appointment",
    },
    {
      simplified: "喂",
      traditional: "喂",
      pinyin: "wèi",
      english: "Hello",
    },
    {
      simplified: "打错了",
      traditional: "打錯了",
      pinyin: "dǎ cuòle",
      english: "Wrong number",
    },
    {
      simplified: "洗手间",
      traditional: "洗手間",
      pinyin: "xǐshǒujiān",
      english: "Restroom",
    },
    {
      simplified: "楼上",
      traditional: "樓上",
      pinyin: "lóu shàng",
      english: "Upstairs",
    },
    {
      simplified: "楼下",
      traditional: "樓下",
      pinyin: "lóu xià",
      english: "Downstairs",
    },
    {
      simplified: "公用电话",
      traditional: "公用電話",
      pinyin: "gōngyòng diànhuà",
      english: "Public telephone",
    },
    {
      simplified: "对面",
      traditional: "對面",
      pinyin: "duìmiàn",
      english: "Opposite",
    },
    {
      simplified: "百货公司",
      traditional: "百貨公司",
      pinyin: "bǎihuò gōngsī",
      english: "Department store",
    },
    {
      simplified: "皮鞋",
      traditional: "皮鞋",
      pinyin: "píxié",
      english: "Leather shoes",
    },
    {
      simplified: "爽",
      traditional: "爽",
      pinyin: "shuǎng",
      english: "Cool",
    },
    {
      simplified: "双",
      traditional: "雙",
      pinyin: "shuāng",
      english: "Double",
    },
    {
      simplified: "应该",
      traditional: "應該",
      pinyin: "yīnggāi",
      english: "Should",
    },
    {
      simplified: "路口",
      traditional: "路口",
      pinyin: "lùkǒu",
      english: "Intersection",
    },
    {
      simplified: "找",
      traditional: "找",
      pinyin: "zhǎo",
      english: "Find",
    },
    {
      simplified: "房子",
      traditional: "房子",
      pinyin: "fángzi",
      english: "House",
    },
    {
      simplified: "公寓",
      traditional: "公寓",
      pinyin: "gōngyù",
      english: "Apartment",
    },
    {
      simplified: "万",
      traditional: "萬",
      pinyin: "wàn",
      english: "Million",
    },
    {
      simplified: "日新百货公司",
      traditional: "日新百貨公司",
      pinyin: "rìxīn bǎihuò gōngsī",
      english: "Rixin Department Store",
    },
    {
      simplified: "怎么",
      traditional: "怎麼",
      pinyin: "zěnme",
      english: "How",
    },
    {
      simplified: "走",
      traditional: "走",
      pinyin: "zǒu",
      english: "Walk",
    },
    {
      simplified: "开车",
      traditional: "開車",
      pinyin: "kāichē",
      english: "Drive",
    },
    {
      simplified: "从",
      traditional: "從",
      pinyin: "cóng",
      english: "From",
    },
    {
      simplified: "东三街",
      traditional: "東三街",
      pinyin: "dōngsān jiē",
      english: "Dongsan Street",
    },
    {
      simplified: "往",
      traditional: "往",
      pinyin: "wǎng",
      english: "Toward",
    },
    {
      simplified: "南",
      traditional: "南",
      pinyin: "nán",
      english: "South",
    },
    {
      simplified: "北",
      traditional: "北",
      pinyin: "běi",
      english: "North",
    },
    {
      simplified: "西",
      traditional: "西",
      pinyin: "xī",
      english: "West",
    },
    {
      simplified: "东",
      traditional: "東",
      pinyin: "dōng",
      english: "East",
    },
    {
      simplified: "过",
      traditional: "過",
      pinyin: "guò",
      english: "Pass",
    },
    {
      simplified: "红绿灯",
      traditional: "紅綠燈",
      pinyin: "hónglǜdēng",
      english: "Traffic light",
    },
    {
      simplified: "火车站",
      traditional: "火車站",
      pinyin: "huǒchē zhàn",
      english: "Train station",
    },
    {
      simplified: "转",
      traditional: "轉",
      pinyin: "zhuǎn",
      english: "Turn",
    },
    {
      simplified: "分",
      traditional: "分",
      pinyin: "fēn",
      english: "Minute",
    },
    {
      simplified: "钟",
      traditional: "鐘",
      pinyin: "zhōng",
      english: "Clock",
    },
    {
      simplified: "小时",
      traditional: "小時",
      pinyin: "xiǎoshí",
      english: "Hour",
    },
  ],
};

export default lesson;
