import { HSKList } from "@src/tools/types";

const lesson: HSKList = {
  list: "13",
  locked: false,
  title: "Book 1 Lesson 6",
  content: [
    {
      simplified: "他们",
      traditional: "他們",
      pinyin: "tā men",
      english: "They",
    },
    {
      simplified: "学校",
      traditional: "學校",
      pinyin: "xuéxiào",
      english: "School",
    },
    {
      simplified: "在",
      traditional: "在",
      pinyin: "zài",
      english: "In",
    },
    {
      simplified: "山上",
      traditional: "山上",
      pinyin: "shān shàng",
      english: "On the mountain",
    },
    {
      simplified: "哪里",
      traditional: "哪裡",
      pinyin: "nǎlǐ",
      english: "Where",
    },
    {
      simplified: "远",
      traditional: "遠",
      pinyin: "yuǎn",
      english: "Far",
    },
    {
      simplified: "那里",
      traditional: "那裡",
      pinyin: "nà li",
      english: "There",
    },
    {
      simplified: "风景",
      traditional: "風景",
      pinyin: "fēngjǐng",
      english: "Landscape",
    },
    {
      simplified: "美",
      traditional: "美",
      pinyin: "měi",
      english: "Nice",
    },
    {
      simplified: "前面",
      traditional: "前面",
      pinyin: "qián miàn",
      english: "Front",
    },
    {
      simplified: "海",
      traditional: "海",
      pinyin: "hǎi",
      english: "Sea",
    },
    {
      simplified: "后面",
      traditional: "後面",
      pinyin: "hòu miàn",
      english: "Behind",
    },
    {
      simplified: "山",
      traditional: "山",
      pinyin: "shān",
      english: "Mountain",
    },
    {
      simplified: "真的",
      traditional: "真的",
      pinyin: "zhēn de",
      english: "Really",
    },
    {
      simplified: "地方",
      traditional: "地方",
      pinyin: "dìfāng",
      english: "Local",
    },
    {
      simplified: "现在",
      traditional: "現在",
      pinyin: "xiànzài",
      english: "Just now",
    },
    {
      simplified: "附近",
      traditional: "附近",
      pinyin: "fù jìn",
      english: "Nearby",
    },
    {
      simplified: "楼下",
      traditional: "樓下",
      pinyin: "lóu xià",
      english: "Downstairs",
    },
    {
      simplified: "找",
      traditional: "找",
      pinyin: "zhǎo",
      english: "Find",
    },
    {
      simplified: "朋友",
      traditional: "朋友",
      pinyin: "péngyǒu",
      english: "Friend",
    },
    {
      simplified: "上课",
      traditional: "上課",
      pinyin: "shàngkè",
      english: "Class",
    },
    {
      simplified: "花莲",
      traditional: "花蓮",
      pinyin: "huā lián",
      english: "Hualien",
    },
    {
      simplified: "听说",
      traditional: "聽說",
      pinyin: "tīng shuō",
      english: "It is said that",
    },
    {
      simplified: "近",
      traditional: "近",
      pinyin: "jìn",
      english: "Near",
    },
    {
      simplified: "方便",
      traditional: "方便",
      pinyin: "fāngbiàn",
      english: "Convenience",
    },
    {
      simplified: "这里",
      traditional: "這裡",
      pinyin: "zhèlǐ",
      english: "Here",
    },
    {
      simplified: "学生",
      traditional: "學生",
      pinyin: "xué sheng",
      english: "Student",
    },
    {
      simplified: "东西",
      traditional: "東西",
      pinyin: "dōngxī",
      english: "Thing",
    },
    {
      simplified: "外面",
      traditional: "外面",
      pinyin: "wàimiàn",
      english: "Outside",
    },
    {
      simplified: "里面",
      traditional: "裡面",
      pinyin: "lǐmiàn",
      english: "Inside",
    },
    {
      simplified: "商店",
      traditional: "商店",
      pinyin: "shāngdiàn",
      english: "Store",
    },
    {
      simplified: "吃饭",
      traditional: "吃飯",
      pinyin: "chīfàn",
      english: "Eat",
    },
    {
      simplified: "宿舍",
      traditional: "宿舍",
      pinyin: "sù shè",
      english: "Dorm room",
    },
    {
      simplified: "楼",
      traditional: "樓",
      pinyin: "lóu",
      english: "Floor",
    },
    {
      simplified: "栋",
      traditional: "棟",
      pinyin: "dòng",
      english: "Dong",
    },
    {
      simplified: "大楼",
      traditional: "大樓",
      pinyin: "dàlóu",
      english: "Building",
    },
    {
      simplified: "图书馆",
      traditional: "圖書館",
      pinyin: "tú shū guǎn",
      english: "Library",
    },
    {
      simplified: "旁边",
      traditional: "旁邊",
      pinyin: "páng biān",
      english: "Next to",
    },
    {
      simplified: "教师",
      traditional: "教師",
      pinyin: "jiàoshī",
      english: "Teacher",
    },
    {
      simplified: "游泳池",
      traditional: "游泳池",
      pinyin: "yóu yǒng chí",
      english: "Swimming pool",
    },
  ],
  dictation: [
    {
      simplified: "校",
      traditional: "校",
      pinyin: "jiào",
      english: "School",
    },
    {
      simplified: "在",
      traditional: "在",
      pinyin: "zài",
      english: "In",
    },
    {
      simplified: "山",
      traditional: "山",
      pinyin: "shān",
      english: "Mountain",
    },
    {
      simplified: "里",
      traditional: "裡",
      pinyin: "lǐ",
      english: "In",
    },
    {
      simplified: "远",
      traditional: "遠",
      pinyin: "yuǎn",
      english: "Far",
    },
    {
      simplified: "风",
      traditional: "風",
      pinyin: "fēng",
      english: "Wind",
    },
    {
      simplified: "景",
      traditional: "景",
      pinyin: "jǐng",
      english: "View",
    },
    {
      simplified: "前",
      traditional: "前",
      pinyin: "qián",
      english: "Before",
    },
    {
      simplified: "面",
      traditional: "面",
      pinyin: "miàn",
      english: "Surface",
    },
    {
      simplified: "海",
      traditional: "海",
      pinyin: "hǎi",
      english: "Sea",
    },
    {
      simplified: "后",
      traditional: "後",
      pinyin: "hòu",
      english: "Rear",
    },
    {
      simplified: "地",
      traditional: "地",
      pinyin: "de",
      english: "Ground",
    },
    {
      simplified: "方",
      traditional: "方",
      pinyin: "fāng",
      english: "Square",
    },
    {
      simplified: "现",
      traditional: "現",
      pinyin: "xiàn",
      english: "Now",
    },
    {
      simplified: "附",
      traditional: "附",
      pinyin: "fù",
      english: "Attached",
    },
    {
      simplified: "近",
      traditional: "近",
      pinyin: "jìn",
      english: "Near",
    },
    {
      simplified: "楼",
      traditional: "樓",
      pinyin: "lóu",
      english: "Floor",
    },
    {
      simplified: "下",
      traditional: "下",
      pinyin: "xià",
      english: "Under",
    },
    {
      simplified: "找",
      traditional: "找",
      pinyin: "zhǎo",
      english: "Find",
    },
    {
      simplified: "朋",
      traditional: "朋",
      pinyin: "péng",
      english: "Friends",
    },
    {
      simplified: "友",
      traditional: "友",
      pinyin: "yǒu",
      english: "Friend",
    },
    {
      simplified: "课",
      traditional: "課",
      pinyin: "kè",
      english: "Class",
    },
    {
      simplified: "花",
      traditional: "花",
      pinyin: "huā",
      english: "Flower",
    },
    {
      simplified: "莲",
      traditional: "蓮",
      pinyin: "lián",
      english: "Lotus",
    },
    {
      simplified: "便",
      traditional: "便",
      pinyin: "biàn",
      english: "Poop",
    },
    {
      simplified: "栋",
      traditional: "棟",
      pinyin: "dòng",
      english: "Dong",
    },
    {
      simplified: "西",
      traditional: "西",
      pinyin: "xī",
      english: "Oo",
    },
    {
      simplified: "商",
      traditional: "商",
      pinyin: "shāng",
      english: "Quotient",
    },
    {
      simplified: "宿",
      traditional: "宿",
      pinyin: "sù",
      english: "Place",
    },
    {
      simplified: "舍",
      traditional: "舍",
      pinyin: "shě",
      english: "Shed",
    },
    {
      simplified: "栋",
      traditional: "棟",
      pinyin: "dòng",
      english: "Dong",
    },
    {
      simplified: "图",
      traditional: "圖",
      pinyin: "tú",
      english: "Fig",
    },
    {
      simplified: "馆",
      traditional: "館",
      pinyin: "guǎn",
      english: "Pavilion",
    },
    {
      simplified: "旁",
      traditional: "旁",
      pinyin: "páng",
      english: "Beside",
    },
    {
      simplified: "边",
      traditional: "邊",
      pinyin: "biān",
      english: "Side",
    },
    {
      simplified: "教",
      traditional: "教",
      pinyin: "jiào",
      english: "Teach",
    },
    {
      simplified: "室",
      traditional: "室",
      pinyin: "shì",
      english: "Room",
    },
    {
      simplified: "池",
      traditional: "池",
      pinyin: "chí",
      english: "Pool",
    },
  ],
};

export default lesson;
