import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "flkSIJf75S",
  type: "Far East",
  list: "14",
  locked: false,
  title: "Far East Lessons 7-8",
  content: [
    {
      simplified: "远",
      traditional: "遠",
      pinyin: "Yuǎn",
      english: "Far",
    },
    {
      simplified: "近",
      traditional: "近",
      pinyin: "Jìn",
      english: "Near",
    },
    {
      simplified: "这样",
      traditional: "這樣",
      pinyin: "Zhèyàng",
      english: "Such",
    },
    {
      simplified: "住",
      traditional: "住",
      pinyin: "Zhù",
      english: "Live",
    },
    {
      simplified: "搬",
      traditional: "搬",
      pinyin: "Bān",
      english: "Move",
    },
    {
      simplified: "只",
      traditional: "只",
      pinyin: "Zhǐ",
      english: "Only",
    },
    {
      simplified: "办",
      traditional: "辦",
      pinyin: "Bàn",
      english: "To handle, manage",
    },
    {
      simplified: "房客",
      traditional: "房客",
      pinyin: "Fángkè",
      english: "Tenant",
    },
    {
      simplified: "拿回去",
      traditional: "拿回去",
      pinyin: "Náhuíqù",
      english: "Take it back",
    },
    {
      simplified: "每",
      traditional: "每",
      pinyin: "Měi",
      english: "Each, every",
    },
    {
      simplified: "下雨",
      traditional: "下雨",
      pinyin: "Xià yǔ",
      english: "Rain",
    },
    {
      simplified: "办法",
      traditional: "辦法",
      pinyin: "Bànfǎ",
      english: "Method, way",
    },
    {
      simplified: "帮",
      traditional: "幫",
      pinyin: "Bāng",
      english: "Help",
    },
    {
      simplified: "麻烦",
      traditional: "麻煩",
      pinyin: "Máfan",
      english: "To be troublesome",
    },
    {
      simplified: "地方",
      traditional: "地方",
      pinyin: "dìfāng",
      english: "Place",
    },
    {
      simplified: "些",
      traditional: "些",
      pinyin: "xiē",
      english: "Some, several",
    },
    {
      simplified: "问题",
      traditional: "問題",
      pinyin: "wèntí",
      english: "Problem, question",
    },
    {
      simplified: "跟",
      traditional: "跟",
      pinyin: "gēn",
      english: "With",
    },
    {
      simplified: "交朋友",
      traditional: "交朋友",
      pinyin: "jiāo péngyǒu",
      english: "To Make friends",
    },
    {
      simplified: "怕",
      traditional: "怕",
      pinyin: "pà",
      english: "To fear",
    },
    {
      simplified: "吵",
      traditional: "吵",
      pinyin: "chǎo",
      english: "to be noisy, to annoy",
    },
    {
      simplified: "睡觉",
      traditional: "睡覺",
      pinyin: "shuìjiào",
      english: "Go to sleep",
    },
    {
      simplified: "洗衣机",
      traditional: "洗衣機",
      pinyin: "xǐyījī",
      english: "Washing machine",
    },
    {
      simplified: "对方付费",
      traditional: "對方付費",
      pinyin: "duìfāng fùfèi",
      english: "Collect",
    },
    {
      simplified: "对方",
      traditional: "對方",
      pinyin: "duìfāng",
      english: "Other party",
    },
    {
      simplified: "长途",
      traditional: "長途",
      pinyin: "chángtú",
      english: "Long distance",
    },
    {
      simplified: "嗯",
      traditional: "嗯",
      pinyin: "ń",
      english: "Affirmation particle",
    },
    {
      simplified: "李红",
      traditional: "李紅",
      pinyin: "Lǐ Hóng",
      english: "Li Hong Chinese name",
    },
    {
      simplified: "赵奇",
      traditional: "趙奇",
      pinyin: "Zhào Qí",
      english: "Zhao Qi Chinese name",
    },
    {
      simplified: "奇怪",
      traditional: "奇怪",
      pinyin: "qíguài",
      english: "Strange",
    },
    {
      simplified: "好几",
      traditional: "好幾",
      pinyin: "hǎojǐ",
      english: "Many, several",
    },
    {
      simplified: "次",
      traditional: "次",
      pinyin: "cì",
      english: "A time, occasion",
    },
    {
      simplified: "捷",
      traditional: "捷",
      pinyin: "jié",
      english: "To answer the phone",
    },
    {
      simplified: "办公室",
      traditional: "辦公室",
      pinyin: "bàngōngshì",
      english: "Office",
    },
    {
      simplified: "希望",
      traditional: "希望",
      pinyin: "xīwàng",
      english: "Hope",
    },
    {
      simplified: "大千公司",
      traditional: "大千公司",
      pinyin: "Dàqiān Gōngsī",
      english: "Daqian Company",
    },
    {
      simplified: "转",
      traditional: "轉",
      pinyin: "zhuǎn",
      english: "To pass on, to transfer",
    },
    {
      simplified: "稍等",
      traditional: "稍等",
      pinyin: "shāo děng",
      english: "Wait a moment",
    },
    {
      simplified: "听",
      traditional: "聽",
      pinyin: "tīng",
      english: "Listen",
    },
    {
      simplified: "进来",
      traditional: "進來",
      pinyin: "jìnlái",
      english: "Come in",
    },
    {
      simplified: "留话",
      traditional: "留話",
      pinyin: "liú huà",
      english: "Leave a message",
    },
    {
      simplified: "留",
      traditional: "留",
      pinyin: "liú",
      english: "To leave, to keep",
    },
    {
      simplified: "下班",
      traditional: "下班",
      pinyin: "xiàbān",
      english: "Off work",
    },
    {
      simplified: "上班",
      traditional: "上班",
      pinyin: "shàngbān",
      english: "Go to work",
    },
    {
      simplified: "以前",
      traditional: "以前",
      pinyin: "yǐqián",
      english: "Before",
    },
    {
      simplified: "以后",
      traditional: "以後",
      pinyin: "yǐhòu",
      english: "After",
    },
    {
      simplified: "回电",
      traditional: "回電",
      pinyin: "huí diàn",
      english: "Call back",
    },
    {
      simplified: "自己",
      traditional: "自己",
      pinyin: "zìjǐ",
      english: "Oneself",
    },
    {
      simplified: "试",
      traditional: "試",
      pinyin: "shì",
      english: "to try",
    },
    {
      simplified: "话",
      traditional: "話",
      pinyin: "huà",
      english: "Word",
    },
  ],
};

export default lesson;
