import { HSKList } from "@src/tools/types";

const lesson: HSKList = {
  list: "15",
  locked: false,
  title: "MTC Book 1 Lesson 8",
  content: [
    {
      simplified: "坐",
      traditional: "坐",
      pinyin: "zuò",
      english: "Sit",
    },
    {
      simplified: "火车",
      traditional: "火車",
      pinyin: "huǒchē",
      english: "Train",
    },
    {
      simplified: "跟",
      traditional: "跟",
      pinyin: "gēn",
      english: "With",
    },
    {
      simplified: "玩",
      traditional: "玩",
      pinyin: "wán",
      english: "Play",
    },
    {
      simplified: "怎么",
      traditional: "怎麼",
      pinyin: "zěn me",
      english: "How",
    },
    {
      simplified: "慢",
      traditional: "慢",
      pinyin: "màn",
      english: "Slow",
    },
    {
      simplified: "钟头",
      traditional: "鐘頭",
      pinyin: "zhōngtóu",
      english: "Hour",
    },
    {
      simplified: "比较",
      traditional: "比較",
      pinyin: "bǐjiào",
      english: "Compare",
    },
    {
      simplified: "快",
      traditional: "快",
      pinyin: "kuài",
      english: "Fast",
    },
    {
      simplified: "车票",
      traditional: "車票",
      pinyin: "chēpiào",
      english: "Ticket",
    },
    {
      simplified: "非常",
      traditional: "非常",
      pinyin: "fēi cháng",
      english: "Very much",
    },
    {
      simplified: "但是",
      traditional: "但是",
      pinyin: "dànshì",
      english: "But",
    },
    {
      simplified: "又",
      traditional: "又",
      pinyin: "yòu",
      english: "Also",
    },
    {
      simplified: "舒服",
      traditional: "舒服",
      pinyin: "shūfú",
      english: "Comfortable",
    },
    {
      simplified: "站",
      traditional: "站",
      pinyin: "zhàn",
      english: "Station",
    },
    {
      simplified: "或是",
      traditional: "或是",
      pinyin: "huò shì",
      english: "Or",
    },
    {
      simplified: "台南",
      traditional: "臺南",
      pinyin: "táinán",
      english: "Tainan",
    },
    {
      simplified: "高铁",
      traditional: "高鐵",
      pinyin: "gāotiě",
      english: "High speed rail",
    },
    {
      simplified: "网路上",
      traditional: "網路上",
      pinyin: "wǎng lùshàng",
      english: "Online",
    },
    {
      simplified: "便利商店",
      traditional: "便利商店",
      pinyin: "biànlì shāngdiàn",
      english: "Convenience store",
    },
    {
      simplified: "同学",
      traditional: "同學",
      pinyin: "tóngxué",
      english: "Classmate",
    },
    {
      simplified: "参观",
      traditional: "參觀",
      pinyin: "cānguān",
      english: "Visit",
    },
    {
      simplified: "古代",
      traditional: "古代",
      pinyin: "gǔdài",
      english: "Ancient",
    },
    {
      simplified: "骑",
      traditional: "騎",
      pinyin: "qí",
      english: "Ride",
    },
    {
      simplified: "机车",
      traditional: "機車",
      pinyin: "jī chē",
      english: "Locomotive",
    },
    {
      simplified: "载",
      traditional: "載",
      pinyin: "zài",
      english: "Set",
    },
    {
      simplified: "捷运",
      traditional: "捷運",
      pinyin: "jié yùn",
      english: "Mrt",
    },
    {
      simplified: "比",
      traditional: "比",
      pinyin: "bǐ",
      english: "Ratio",
    },
    {
      simplified: "中国",
      traditional: "中國",
      pinyin: "zhōngguó",
      english: "China",
    },
    {
      simplified: "公共汽车",
      traditional: "公共汽車",
      pinyin: "gōnggòng qìchē",
      english: "Bus",
    },
    {
      simplified: "不行",
      traditional: "不行",
      pinyin: "bùxíng",
      english: "No way",
    },
    {
      simplified: "计程车",
      traditional: "計程車",
      pinyin: "jìchéngchē",
      english: "Taxi",
    },
    {
      simplified: "差不多",
      traditional: "差不多",
      pinyin: "chàbùduō",
      english: "Almost",
    },
  ],
  dictation: [
    {
      simplified: "火",
      traditional: "火",
      pinyin: "huǒ",
      english: "Fire",
    },
    {
      simplified: "车",
      traditional: "車",
      pinyin: "chē",
      english: "Car",
    },
    {
      simplified: "跟",
      traditional: "跟",
      pinyin: "gēn",
      english: "With",
    },
    {
      simplified: "慢",
      traditional: "慢",
      pinyin: "màn",
      english: "Slow",
    },
    {
      simplified: "种",
      traditional: "種",
      pinyin: "zhǒng",
      english: "Species",
    },
    {
      simplified: "头",
      traditional: "頭",
      pinyin: "tóu",
      english: "Head",
    },
    {
      simplified: "较",
      traditional: "較",
      pinyin: "jiào",
      english: "Compare",
    },
    {
      simplified: "快",
      traditional: "快",
      pinyin: "kuài",
      english: "Fast",
    },
    {
      simplified: "票",
      traditional: "票",
      pinyin: "piào",
      english: "Ticket",
    },
    {
      simplified: "非",
      traditional: "非",
      pinyin: "fēi",
      english: "Non-",
    },
    {
      simplified: "但",
      traditional: "但",
      pinyin: "dàn",
      english: "But",
    },
    {
      simplified: "又",
      traditional: "又",
      pinyin: "yòu",
      english: "Also",
    },
    {
      simplified: "舒",
      traditional: "舒",
      pinyin: "shū",
      english: "Shu",
    },
    {
      simplified: "服",
      traditional: "服",
      pinyin: "fú",
      english: "Clothes",
    },
    {
      simplified: "站",
      traditional: "站",
      pinyin: "zhàn",
      english: "Station",
    },
    {
      simplified: "或",
      traditional: "或",
      pinyin: "huò",
      english: "Or",
    },
    {
      simplified: "高",
      traditional: "高",
      pinyin: "gāo",
      english: "High",
    },
    {
      simplified: "铁",
      traditional: "鐵",
      pinyin: "tiě",
      english: "Iron",
    },
    {
      simplified: "路",
      traditional: "路",
      pinyin: "lù",
      english: "Road",
    },
    {
      simplified: "利",
      traditional: "利",
      pinyin: "lì",
      english: "Benefit",
    },
    {
      simplified: "参",
      traditional: "參",
      pinyin: "sān",
      english: "Ginseng",
    },
    {
      simplified: "观",
      traditional: "觀",
      pinyin: "guàn",
      english: "View",
    },
    {
      simplified: "古",
      traditional: "古",
      pinyin: "gǔ",
      english: "Ancient",
    },
    {
      simplified: "代",
      traditional: "代",
      pinyin: "dài",
      english: "Generation",
    },
    {
      simplified: "骑",
      traditional: "騎",
      pinyin: "jì",
      english: "Ride",
    },
    {
      simplified: "载",
      traditional: "載",
      pinyin: "zǎi",
      english: "Set",
    },
    {
      simplified: "捷",
      traditional: "捷",
      pinyin: "jié",
      english: "Jie",
    },
    {
      simplified: "故",
      traditional: "故",
      pinyin: "gù",
      english: "Therefore",
    },
    {
      simplified: "宫",
      traditional: "宮",
      pinyin: "gōng",
      english: "Palace",
    },
    {
      simplified: "博",
      traditional: "博",
      pinyin: "bó",
      english: "Bo",
    },
    {
      simplified: "物",
      traditional: "物",
      pinyin: "wù",
      english: "Thing",
    },
    {
      simplified: "院",
      traditional: "院",
      pinyin: "yuàn",
      english: "Hospital",
    },
    {
      simplified: "公",
      traditional: "公",
      pinyin: "gōng",
      english: "Public",
    },
    {
      simplified: "汽",
      traditional: "汽",
      pinyin: "qì",
      english: "Vapor",
    },
    {
      simplified: "行",
      traditional: "行",
      pinyin: "háng",
      english: "Row",
    },
  ],
};

export default lesson;
