import { HSKList } from "@src/tools/types";

const lesson: HSKList = {
  list: "16",
  locked: false,
  title: "Book 1 Lesson 9",
  content: [
    {
      simplified: "星期",
      traditional: "星期",
      pinyin: "xīng qī",
      english: "Week",
    },
    {
      simplified: "回国",
      traditional: "回國",
      pinyin: "huí guó",
      english: "Return home",
    },
    {
      simplified: "打算",
      traditional: "打算",
      pinyin: "dǎ suàn",
      english: "Intend",
    },
    {
      simplified: "电视",
      traditional: "電視",
      pinyin: "diàn shì",
      english: "Tv",
    },
    {
      simplified: "影片",
      traditional: "影片",
      pinyin: "yǐng piàn",
      english: "Film",
    },
    {
      simplified: "旅行",
      traditional: "旅行",
      pinyin: "lǚ xíng",
      english: "Travel",
    },
    {
      simplified: "功课",
      traditional: "功課",
      pinyin: "gōng kè",
      english: "Homework",
    },
    {
      simplified: "出去",
      traditional: "出去",
      pinyin: "chū qù",
      english: "Go out",
    },
    {
      simplified: "大概",
      traditional: "大概",
      pinyin: "dà gài",
      english: "Probably",
    },
    {
      simplified: "放假",
      traditional: "放假",
      pinyin: "fàng jià",
      english: "Holiday",
    },
    {
      simplified: "下个星期",
      traditional: "下個星期",
      pinyin: "xià gè xīng qī",
      english: "Next week",
    },
    {
      simplified: "有时候",
      traditional: "有時候",
      pinyin: "yǒu shí hou",
      english: "Sometimes",
    },
    {
      simplified: "多久",
      traditional: "多久",
      pinyin: "duō jiǔ",
      english: "How long",
    },
    {
      simplified: "台东",
      traditional: "臺東",
      pinyin: "tái dōng",
      english: "Taitung",
    },
    {
      simplified: "女",
      traditional: "女",
      pinyin: "nǚ",
      english: "Female",
    },
    {
      simplified: "月",
      traditional: "月",
      pinyin: "yuè",
      english: "Month",
    },
    {
      simplified: "号",
      traditional: "號",
      pinyin: "háo",
      english: "Number",
    },
    {
      simplified: "带",
      traditional: "帶",
      pinyin: "dài",
      english: "Band",
    },
    {
      simplified: "她",
      traditional: "她",
      pinyin: "tā",
      english: "She was",
    },
    {
      simplified: "还",
      traditional: "還",
      pinyin: "huán",
      english: "Also",
    },
    {
      simplified: "建议",
      traditional: "建議",
      pinyin: "jiàn yì",
      english: "Suggest",
    },
    {
      simplified: "夜市",
      traditional: "夜市",
      pinyin: "yè shì",
      english: "Night market",
    },
    {
      simplified: "应该",
      traditional: "應該",
      pinyin: "yīng gāi",
      english: "Should",
    },
    {
      simplified: "逛",
      traditional: "逛",
      pinyin: "guàng",
      english: "Visit",
    },
    {
      simplified: "特别",
      traditional: "特別",
      pinyin: "tè bié",
      english: "Particular",
    },
    {
      simplified: "茶馆",
      traditional: "茶館",
      pinyin: "chá guǎn",
      english: "Teahouse",
    },
    {
      simplified: "决定",
      traditional: "決定",
      pinyin: "jué dìng",
      english: "Decide",
    },
    {
      simplified: "要是",
      traditional: "要是",
      pinyin: "yào shi",
      english: "If",
    },
    {
      simplified: "就",
      traditional: "就",
      pinyin: "jiù",
      english: "On",
    },
    {
      simplified: "猫空",
      traditional: "貓空",
      pinyin: "māo ",
      english: "Cat empty",
    },
  ],
  dictation: [
    {
      simplified: "计",
      traditional: "計",
      pinyin: "jì",
      english: "Meter",
    },
    {
      simplified: "程",
      traditional: "程",
      pinyin: "chéng",
      english: "Cheng",
    },
    {
      simplified: "差",
      traditional: "差",
      pinyin: "chā",
      english: "Difference",
    },
    {
      simplified: "星",
      traditional: "星",
      pinyin: "xīng",
      english: "Star",
    },
    {
      simplified: "期",
      traditional: "期",
      pinyin: "qī",
      english: "Period",
    },
    {
      simplified: "回",
      traditional: "回",
      pinyin: "huí",
      english: "Return",
    },
    {
      simplified: "算",
      traditional: "算",
      pinyin: "suàn",
      english: "Count",
    },
    {
      simplified: "视",
      traditional: "視",
      pinyin: "shì",
      english: "As",
    },
    {
      simplified: "旅",
      traditional: "旅",
      pinyin: "lǚ",
      english: "Trip",
    },
    {
      simplified: "功",
      traditional: "功",
      pinyin: "gōng",
      english: "Merit",
    },
    {
      simplified: "出",
      traditional: "出",
      pinyin: "chū",
      english: "Out",
    },
    {
      simplified: "概",
      traditional: "概",
      pinyin: "gài",
      english: "General",
    },
    {
      simplified: "放",
      traditional: "放",
      pinyin: "fàng",
      english: "Put",
    },
    {
      simplified: "假",
      traditional: "假",
      pinyin: "jiǎ",
      english: "False",
    },
    {
      simplified: "久",
      traditional: "久",
      pinyin: "jiǔ",
      english: "Long",
    },
    {
      simplified: "女",
      traditional: "女",
      pinyin: "nǚ",
      english: "Female",
    },
    {
      simplified: "号",
      traditional: "號",
      pinyin: "háo",
      english: "Number",
    },
    {
      simplified: "她",
      traditional: "她",
      pinyin: "tā",
      english: "She was",
    },
    {
      simplified: "建",
      traditional: "建",
      pinyin: "jiàn",
      english: "Build",
    },
    {
      simplified: "议",
      traditional: "議",
      pinyin: "yì",
      english: "Discuss",
    },
    {
      simplified: "夜",
      traditional: "夜",
      pinyin: "yè",
      english: "Night",
    },
    {
      simplified: "市",
      traditional: "市",
      pinyin: "shì",
      english: "City",
    },
    {
      simplified: "应",
      traditional: "應",
      pinyin: "yìng",
      english: "Should",
    },
    {
      simplified: "该",
      traditional: "該",
      pinyin: "gāi",
      english: "The",
    },
    {
      simplified: "逛",
      traditional: "逛",
      pinyin: "guàng",
      english: "Visit",
    },
    {
      simplified: "特",
      traditional: "特",
      pinyin: "tè",
      english: "Special",
    },
    {
      simplified: "别",
      traditional: "別",
      pinyin: "bié",
      english: "Do not",
    },
    {
      simplified: "决",
      traditional: "決",
      pinyin: "jué",
      english: "Decide",
    },
    {
      simplified: "就",
      traditional: "就",
      pinyin: "jiù",
      english: "On",
    },
    {
      simplified: "猫",
      traditional: "貓",
      pinyin: "māo",
      english: "Cat",
    },
  ],
};

export default lesson;
