import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "871Uf87816T",
  type: "Contemporary Chinese",
  list: "16",
  locked: false,
  title: "Lesson 10",
  content: [
    {
      traditional: "租",
      simplified: "租",
      pinyin: "zū",
      english: "Rent",
    },
    {
      traditional: "房東",
      simplified: "房东",
      pinyin: "fáng dōng",
      english: "Landlord",
    },
    {
      traditional: "客廳",
      simplified: "客厅",
      pinyin: "kè tīng",
      english: "Living room",
    },
    {
      traditional: "廚房",
      simplified: "厨房",
      pinyin: "chú fáng",
      english: "Kitchen",
    },
    {
      traditional: "左邊",
      simplified: "左边",
      pinyin: "zuǒ biān",
      english: "Left",
    },
    {
      traditional: "右邊",
      simplified: "右边",
      pinyin: "yòu biān",
      english: "Right",
    },
    {
      traditional: "浴室",
      simplified: "浴室",
      pinyin: "yù shì",
      english: "Bathroom",
    },
    {
      traditional: "超市",
      simplified: "超市",
      pinyin: "chāo shì",
      english: "Supermarket",
    },
    {
      traditional: "走路",
      simplified: "走路",
      pinyin: "zǒu lù",
      english: "Walk",
    },
    {
      traditional: "分鐘",
      simplified: "分钟",
      pinyin: "fēn zhōng",
      english: "Minute",
    },
    {
      traditional: "就",
      simplified: "就",
      pinyin: "jiù",
      english: "On",
    },
    {
      traditional: "到",
      simplified: "到",
      pinyin: "dào",
      english: "To",
    },
    {
      traditional: "間",
      simplified: "间",
      pinyin: "jiān",
      english: "Between",
    },
    {
      traditional: "空",
      simplified: "空",
      pinyin: "kōng",
      english: "Air",
    },
    {
      traditional: "房間",
      simplified: "房间",
      pinyin: "fáng jiān",
      english: "Room",
    },
    {
      traditional: "套房",
      simplified: "套房",
      pinyin: "tào fáng",
      english: "Suite",
    },
    {
      traditional: "回去",
      simplified: "回去",
      pinyin: "huí qù",
      english: "Go back",
    },
    {
      traditional: "想",
      simplified: "想",
      pinyin: "xiǎng",
      english: "Miss you",
    },
    {
      traditional: "再",
      simplified: "再",
      pinyin: "zài",
      english: "Again",
    },
    {
      traditional: "電話",
      simplified: "电话",
      pinyin: "diàn huà",
      english: "Phone",
    },
    {
      traditional: "給",
      simplified: "给",
      pinyin: "gěi",
      english: "Give",
    },
    {
      traditional: "林",
      simplified: "林",
      pinyin: "lín",
      english: "Common Chinese Surname",
    },
    {
      traditional: "打電話",
      simplified: "打电话",
      pinyin: "dǎ diàn huà",
      english: "Make a call",
    },
    {
      traditional: "喂",
      simplified: "喂",
      pinyin: "wèi",
      english: "Hey",
    },
    {
      traditional: "房租",
      simplified: "房租",
      pinyin: "fáng zū",
      english: "Rent",
    },
    {
      traditional: "已經",
      simplified: "已经",
      pinyin: "yǐ jīng",
      english: "Already",
    },
    {
      traditional: "習慣",
      simplified: "习惯",
      pinyin: "xí guàn",
      english: "Habit",
    },
    {
      traditional: "問題",
      simplified: "问题",
      pinyin: "wèn tí",
      english: "Problem",
    },
    {
      traditional: "熱水器",
      simplified: "热水器",
      pinyin: "rè shuǐ qì",
      english: "Water heater",
    },
    {
      traditional: "好像",
      simplified: "好像",
      pinyin: "hǎo xiàng",
      english: "Like",
    },
    {
      traditional: "會",
      simplified: "会",
      pinyin: "huì",
      english: "Meeting",
    },
    {
      traditional: "等",
      simplified: "等",
      pinyin: "děng",
      english: "Wait",
    },
    {
      traditional: "那",
      simplified: "那",
      pinyin: "nà",
      english: "That",
    },
    {
      traditional: "裝",
      simplified: "装",
      pinyin: "zhuāng",
      english: "Attire",
    },
    {
      traditional: "不過",
      simplified: "不过",
      pinyin: "bù guò",
      english: "But",
    },
    {
      traditional: "付",
      simplified: "付",
      pinyin: "fù",
      english: "Pay",
    },
    {
      traditional: "收到",
      simplified: "收到",
      pinyin: "shōu dào",
      english: "Roger that",
    },
    {
      traditional: "不好意思",
      simplified: "不好意思",
      pinyin: "bù hǎo yì sī",
      english: "Sorry",
    },
    {
      traditional: "有線電視",
      simplified: "有线电视",
      pinyin: "yǒu xiàn diàn shì",
      english: "Cable tv",
    },
  ],
};

export default lesson;
