import { HSKList } from "@src/tools/types";

const lesson: HSKList = {
  list: "17",
  locked: false,
  title: "MTC Book 1 Lesson 10",
  content: [
    {
      simplified: "水果",
      traditional: "水果",
      pinyin: "shuǐ guǒ",
      english: "Fruit",
    },
    {
      simplified: "黄色",
      traditional: "黃色",
      pinyin: "huáng sè",
      english: "Yellow",
    },
    {
      simplified: "芒果",
      traditional: "芒果",
      pinyin: "máng guǒ",
      english: "Mango",
    },
    {
      simplified: "给",
      traditional: "給",
      pinyin: "gěi",
      english: "Give",
    },
    {
      simplified: "块",
      traditional: "塊",
      pinyin: "kuài",
      english: "Piece",
    },
    {
      simplified: "香",
      traditional: "香",
      pinyin: "xiāng",
      english: "Fragrant",
    },
    {
      simplified: "甜",
      traditional: "甜",
      pinyin: "tián",
      english: "Sweet",
    },
    {
      simplified: "红色",
      traditional: "紅色",
      pinyin: "hóng sè",
      english: "Red",
    },
    {
      simplified: "西瓜",
      traditional: "西瓜",
      pinyin: "xī guā",
      english: "Watermelon",
    },
    {
      simplified: "吧",
      traditional: "吧",
      pinyin: "bā",
      english: "Right",
    },
    {
      simplified: "对",
      traditional: "對",
      pinyin: "duì",
      english: "Correct",
    },
    {
      simplified: "以前",
      traditional: "以前",
      pinyin: "yǐ qián",
      english: "Before",
    },
    {
      simplified: "机会",
      traditional: "機會",
      pinyin: "jī huì",
      english: "Opportunity",
    },
    {
      simplified: "请",
      traditional: "請",
      pinyin: "qǐng",
      english: "Please",
    },
    {
      simplified: "吃吃看",
      traditional: "吃吃看",
      pinyin: "chī chī ",
      english: "Try it",
    },
    {
      simplified: "拍",
      traditional: "拍",
      pinyin: "pāi",
      english: "Beat",
    },
    {
      simplified: "笑",
      traditional: "笑",
      pinyin: "xiào",
      english: "Laugh",
    },
    {
      simplified: "开心",
      traditional: "開心",
      pinyin: "kāi xīn",
      english: "Happy",
    },
    {
      simplified: "穿",
      traditional: "穿",
      pinyin: "chuān",
      english: "Wear",
    },
    {
      simplified: "衣服",
      traditional: "衣服",
      pinyin: "yī fu",
      english: "Clothes",
    },
    {
      simplified: "旅馆",
      traditional: "旅館",
      pinyin: "lǚ guǎn",
      english: "Hostel",
    },
    {
      simplified: "太太",
      traditional: "太太",
      pinyin: "tài tai",
      english: "Mrs",
    },
    {
      simplified: "男",
      traditional: "男",
      pinyin: "nán",
      english: "Male",
    },
    {
      simplified: "矮",
      traditional: "矮",
      pinyin: "ǎi",
      english: "Short",
    },
    {
      simplified: "高",
      traditional: "高",
      pinyin: "gāo",
      english: "High",
    },
    {
      simplified: "弟弟",
      traditional: "弟弟",
      pinyin: "dì di",
      english: "Little brother",
    },
    {
      simplified: "干净",
      traditional: "乾淨",
      pinyin: "gān jìng",
      english: "Clean",
    },
    {
      simplified: "窗户",
      traditional: "窗戶",
      pinyin: "chuāng hu",
      english: "Window",
    },
    {
      simplified: "往",
      traditional: "往",
      pinyin: "wǎng",
      english: "To",
    },
    {
      simplified: "蓝色",
      traditional: "藍色",
      pinyin: "lán sè",
      english: "Blue",
    },
    {
      simplified: "因为",
      traditional: "因為",
      pinyin: "yīn wèi",
      english: "Because",
    },
    {
      simplified: "住",
      traditional: "住",
      pinyin: "zhù",
      english: "Live",
    },
    {
      simplified: "上个月",
      traditional: "上個月",
      pinyin: "shàng gè yuè",
      english: "Last month",
    },
    {
      simplified: "这些",
      traditional: "這些",
      pinyin: "zhè xiē",
      english: "These ones",
    },
  ],
  dictation: [
    {
      simplified: "水",
      traditional: "水",
      pinyin: "shuǐ",
      english: "Water",
    },
    {
      simplified: "果",
      traditional: "果",
      pinyin: "guǒ",
      english: "Fruit",
    },
    {
      simplified: "黄",
      traditional: "黃",
      pinyin: "huáng",
      english: "Yellow",
    },
    {
      simplified: "色",
      traditional: "色",
      pinyin: "sè",
      english: "Color",
    },
    {
      simplified: "芒",
      traditional: "芒",
      pinyin: "máng",
      english: "Mango",
    },
    {
      simplified: "给",
      traditional: "給",
      pinyin: "gěi",
      english: "Give",
    },
    {
      simplified: "香",
      traditional: "香",
      pinyin: "xiāng",
      english: "Fragrant",
    },
    {
      simplified: "红",
      traditional: "紅",
      pinyin: "hóng",
      english: "Red",
    },
    {
      simplified: "瓜",
      traditional: "瓜",
      pinyin: "guā",
      english: "Melon",
    },
    {
      simplified: "拍",
      traditional: "拍",
      pinyin: "pāi",
      english: "Beat",
    },
    {
      simplified: "笑",
      traditional: "笑",
      pinyin: "xiào",
      english: "Laugh",
    },
    {
      simplified: "心",
      traditional: "心",
      pinyin: "xīn",
      english: "Heart",
    },
    {
      simplified: "穿",
      traditional: "穿",
      pinyin: "chuān",
      english: "Wear",
    },
    {
      simplified: "衣",
      traditional: "衣",
      pinyin: "yī",
      english: "Clothes",
    },
    {
      simplified: "男",
      traditional: "男",
      pinyin: "nán",
      english: "Male",
    },
    {
      simplified: "矮",
      traditional: "矮",
      pinyin: "ǎi",
      english: "Short",
    },
    {
      simplified: "干",
      traditional: "乾",
      pinyin: "qián",
      english: "Dry",
    },
    {
      simplified: "净",
      traditional: "淨",
      pinyin: "jìng",
      english: "Net",
    },
    {
      simplified: "窗",
      traditional: "窗",
      pinyin: "chuāng",
      english: "Window",
    },
    {
      simplified: "户",
      traditional: "戶",
      pinyin: "hù",
      english: "Household",
    },
    {
      simplified: "往",
      traditional: "往",
      pinyin: "wǎng",
      english: "To",
    },
    {
      simplified: "蓝",
      traditional: "藍",
      pinyin: "lán",
      english: "Blue",
    },
    {
      simplified: "因",
      traditional: "因",
      pinyin: "yīn",
      english: "Because",
    },
    {
      simplified: "住",
      traditional: "住",
      pinyin: "zhù",
      english: "Live",
    },
    {
      simplified: "些",
      traditional: "些",
      pinyin: "xiē",
      english: "Some",
    },
  ],
};

export default lesson;
