import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "fKauWQ78166",
  type: "Contemporary Chinese",
  list: "17",
  locked: false,
  title: "Lesson 11",
  content: [
    {
      traditional: "計畫",
      simplified: "计画",
      pinyin: "jì huà",
      english: "Plan",
    },
    {
      traditional: "年",
      simplified: "年",
      pinyin: "nián",
      english: "Year",
    },
    {
      traditional: "久",
      simplified: "久",
      pinyin: "jiǔ",
      english: "Long",
    },
    {
      traditional: "時間",
      simplified: "时间",
      pinyin: "shí jiān",
      english: "Time",
    },
    {
      traditional: "先",
      simplified: "先",
      pinyin: "xiān",
      english: "First",
    },
    {
      traditional: "念",
      simplified: "念",
      pinyin: "niàn",
      english: "Read",
    },
    {
      traditional: "大學",
      simplified: "大学",
      pinyin: "dà xué",
      english: "The university",
    },
    {
      traditional: "需要",
      simplified: "需要",
      pinyin: "xū yào",
      english: "Need",
    },
    {
      traditional: "花",
      simplified: "花",
      pinyin: "huā",
      english: "Flower",
    },
    {
      traditional: "獎學金",
      simplified: "奖学金",
      pinyin: "jiǎng xué jīn",
      english: "Scholarship",
    },
    {
      traditional: "成績",
      simplified: "成绩",
      pinyin: "chéng jī",
      english: "Grades",
    },
    {
      traditional: "公司",
      simplified: "公司",
      pinyin: "gōng sī",
      english: "The company",
    },
    {
      traditional: "替",
      simplified: "替",
      pinyin: "tì",
      english: "For",
    },
    {
      traditional: "希望",
      simplified: "希望",
      pinyin: "xī wàng",
      english: "Hope",
    },
    {
      traditional: "以後",
      simplified: "以后",
      pinyin: "yǐ hòu",
      english: "After",
    },
    {
      traditional: "到",
      simplified: "到",
      pinyin: "dào",
      english: "To",
    },
    {
      traditional: "上班",
      simplified: "上班",
      pinyin: "shàng bān",
      english: "Go to work",
    },
    {
      traditional: "念書",
      simplified: "念书",
      pinyin: "niàn shū",
      english: "Study",
    },
    {
      traditional: "累",
      simplified: "累",
      pinyin: "lèi",
      english: "Tired",
    },
    {
      traditional: "語言中心",
      simplified: "语言中心",
      pinyin: "yǔ yán zhōng xīn",
      english: "Language center",
    },
    {
      traditional: "加油",
      simplified: "加油",
      pinyin: "jiā yóu",
      english: "Come on",
    },
    {
      traditional: "工作",
      simplified: "工作",
      pinyin: "gōng zuò",
      english: "Jobs",
    },
    {
      traditional: "去年",
      simplified: "去年",
      pinyin: "qù nián",
      english: "Last year",
    },
    {
      traditional: "做",
      simplified: "做",
      pinyin: "zuò",
      english: "Do",
    },
    {
      traditional: "生意",
      simplified: "生意",
      pinyin: "shēng yì",
      english: "Business",
    },
    {
      traditional: "以後",
      simplified: "以后",
      pinyin: "yǐ hòu",
      english: "After",
    },
    {
      traditional: "找",
      simplified: "找",
      pinyin: "zhǎo",
      english: "Find",
    },
    {
      traditional: "這樣",
      simplified: "这样",
      pinyin: "zhè yàng",
      english: "Such",
    },
    {
      traditional: "國家",
      simplified: "国家",
      pinyin: "guó jiā",
      english: "Country",
    },
    {
      traditional: "試",
      simplified: "试",
      pinyin: "shì",
      english: "Test",
    },
    {
      traditional: "難",
      simplified: "难",
      pinyin: "nán",
      english: "Difficult",
    },
    {
      traditional: "那麼",
      simplified: "那么",
      pinyin: "nà me",
      english: "Then",
    },
    {
      traditional: "再",
      simplified: "再",
      pinyin: "zài",
      english: "Again",
    },
    {
      traditional: "試試看",
      simplified: "试试看",
      pinyin: "shì shì kàn",
      english: "Try it",
    },
  ],
};

export default lesson;
