import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "alsoqpe0s9",
  type: "Contemporary Chinese",
  locked: false,
  title: "Book 2 Lesson 6",
  content: [
    {
      traditional: "李東健",
      simplified: "李东健",
      pinyin: "lǐ dōng jiàn",
      english: "Li dongjian",
    },
    {
      traditional: "搬",
      simplified: "搬",
      pinyin: "bān",
      english: "Move",
    },
    {
      traditional: "河邊",
      simplified: "河边",
      pinyin: "hé biān",
      english: "Riverside",
    },
    {
      traditional: "公園",
      simplified: "公园",
      pinyin: "gōng yuán",
      english: "Park",
    },
    {
      traditional: "腳踏車",
      simplified: "脚踏车",
      pinyin: "jiǎo tà chē",
      english: "Bicycle",
    },
    {
      traditional: "正在",
      simplified: "正在",
      pinyin: "zhèng zài",
      english: "Being",
    },
    {
      traditional: "網站",
      simplified: "网站",
      pinyin: "wǎng zhàn",
      english: "Website",
    },
    {
      traditional: "資料",
      simplified: "资料",
      pinyin: "zī liào",
      english: "Data",
    },
    {
      traditional: "搬家",
      simplified: "搬家",
      pinyin: "bān jiā",
      english: "Move",
    },
    {
      traditional: "近",
      simplified: "近",
      pinyin: "jìn",
      english: "Near",
    },
    {
      traditional: "合約",
      simplified: "合约",
      pinyin: "hé yuē",
      english: "Contract",
    },
    {
      traditional: "到期",
      simplified: "到期",
      pinyin: "dào qī",
      english: "Maturity",
    },
    {
      traditional: "還好",
      simplified: "还好",
      pinyin: "hái hǎo",
      english: "Okay",
    },
    {
      traditional: "光線",
      simplified: "光线",
      pinyin: "guāng xiàn",
      english: "Light",
    },
    {
      traditional: "重要",
      simplified: "重要",
      pinyin: "zhòng yào",
      english: "Important",
    },
    {
      traditional: "如果",
      simplified: "如果",
      pinyin: "rú guǒ",
      english: "In case",
    },
    {
      traditional: "別的",
      simplified: "别的",
      pinyin: "bié dē",
      english: "Other",
    },
    {
      traditional: "合適",
      simplified: "合适",
      pinyin: "hé shì",
      english: "Suitable",
    },
    {
      traditional: "少",
      simplified: "少",
      pinyin: "shǎo",
      english: "Less",
    },
    {
      traditional: "可惜",
      simplified: "可惜",
      pinyin: "kě xī",
      english: "Unfortunately",
    },
    {
      traditional: "放",
      simplified: "放",
      pinyin: "fàng",
      english: "Put",
    },
    {
      traditional: "兩邊",
      simplified: "两边",
      pinyin: "liǎng biān",
      english: "Both sides",
    },
    {
      traditional: "願意",
      simplified: "愿意",
      pinyin: "yuàn yì",
      english: "Willing",
    },
    {
      traditional: "開",
      simplified: "开",
      pinyin: "kāi",
      english: "Open",
    },
    {
      traditional: "存",
      simplified: "存",
      pinyin: "cún",
      english: "Save",
    },
    {
      traditional: "隨身碟",
      simplified: "随身碟",
      pinyin: "suí shēn dié",
      english: "Flash drive",
    },
    {
      traditional: "什麼樣",
      simplified: "什么样",
      pinyin: "shén me yàng",
      english: "What kind",
    },
    {
      traditional: "慢慢來",
      simplified: "慢慢来",
      pinyin: "màn màn lái",
      english: "Take it easy",
    },
    {
      traditional: "不急",
      simplified: "不急",
      pinyin: "bù jí",
      english: "Not urgent",
    },
    {
      traditional: "相當",
      simplified: "相当",
      pinyin: "xiāng dāng",
      english: "Quite",
    },
    {
      traditional: "自行車",
      simplified: "自行车",
      pinyin: "zì xíng chē",
      english: "Bicycle",
    },
    {
      traditional: "床",
      simplified: "床",
      pinyin: "chuáng",
      english: "Bed",
    },
    {
      traditional: "桌子",
      simplified: "桌子",
      pinyin: "zhuō zi",
      english: "Table",
    },
    {
      traditional: "椅子",
      simplified: "椅子",
      pinyin: "yǐ zi",
      english: "Chair",
    },
    {
      traditional: "家具",
      simplified: "家具",
      pinyin: "jiā jù",
      english: "Furniture",
    },
    {
      traditional: "而且",
      simplified: "而且",
      pinyin: "ér qiě",
      english: "And",
    },
    {
      traditional: "吵",
      simplified: "吵",
      pinyin: "chǎo",
      english: "Noisy",
    },
    {
      traditional: "生活費",
      simplified: "生活费",
      pinyin: "shēng huó fèi",
      english: "Living expenses",
    },
    {
      traditional: "低",
      simplified: "低",
      pinyin: "dī",
      english: "Low",
    },
    {
      traditional: "留",
      simplified: "留",
      pinyin: "liú",
      english: "Stay",
    },
    {
      traditional: "長",
      simplified: "长",
      pinyin: "zhǎng",
      english: "Long",
    },
    {
      traditional: "討論",
      simplified: "讨论",
      pinyin: "tǎo lùn",
      english: "Discuss",
    },
    {
      traditional: "社團",
      simplified: "社团",
      pinyin: "shè tuán",
      english: "Societies",
    },
    {
      traditional: "活動",
      simplified: "活动",
      pinyin: "huó dòng",
      english: "Activity",
    },
    {
      traditional: "失望",
      simplified: "失望",
      pinyin: "shī wàng",
      english: "Disappointed",
    },
    {
      traditional: "放心",
      simplified: "放心",
      pinyin: "fàng xīn",
      english: "Rest assured",
    },
    {
      traditional: "用",
      simplified: "用",
      pinyin: "yòng",
      english: "Use",
    },
    {
      traditional: "首爾",
      simplified: "首尔",
      pinyin: "shǒu ěr",
      english: "Seoul",
    },
  ],
};

export default lesson;
