import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "a8fsu8a723",
  type: "Contemporary Chinese",
  locked: false,
  title: "Book 2 Lesson 3",
  content: [
    {
      traditional: "進步",
      simplified: "进步",
      pinyin: "jìn bù",
      english: "Progress",
    },
    {
      traditional: "早",
      simplified: "早",
      pinyin: "zǎo",
      english: "Early",
    },
    {
      traditional: "考試",
      simplified: "考试",
      pinyin: "kǎo shì",
      english: "Examination",
    },
    {
      traditional: "準備",
      simplified: "准备",
      pinyin: "zhǔn bèi",
      english: "Ready",
    },
    {
      traditional: "考",
      simplified: "考",
      pinyin: "kǎo",
      english: "Test",
    },
    {
      traditional: "停歇",
      simplified: "停歇",
      pinyin: "tíng xiē",
      english: "Stop",
    },
    {
      traditional: "容易",
      simplified: "容易",
      pinyin: "róng yì",
      english: "Easy",
    },
    {
      traditional: "小學",
      simplified: "小学",
      pinyin: "xiǎo xué",
      english: "Primary school",
    },
    {
      traditional: "漢字",
      simplified: "汉字",
      pinyin: "hàn zì",
      english: "Chinese character",
    },
    {
      traditional: "過",
      simplified: "过",
      pinyin: "guò",
      english: "Pass",
    },
    {
      traditional: "才",
      simplified: "才",
      pinyin: "cái",
      english: "Only",
    },
    {
      traditional: "說話",
      simplified: "说话",
      pinyin: "shuō huà",
      english: "Speak",
    },
    {
      traditional: "不夠",
      simplified: "不够",
      pinyin: "bù gòu",
      english: "Not enough",
    },
    {
      traditional: "流利",
      simplified: "流利",
      pinyin: "liú lì",
      english: "Fluent",
    },
    {
      traditional: "雖然",
      simplified: "虽然",
      pinyin: "suī rán",
      english: "Although",
    },
    {
      traditional: "環境",
      simplified: "环境",
      pinyin: "huán jìng",
      english: "Surroundings",
    },
    {
      traditional: "同意",
      simplified: "同意",
      pinyin: "tóng yì",
      english: "Agree",
    },
    {
      traditional: "報紙",
      simplified: "报纸",
      pinyin: "bào zhǐ",
      english: "Newspaper",
    },
    {
      traditional: "麵包",
      simplified: "面包",
      pinyin: "miàn bāo",
      english: "Bread",
    },
    {
      traditional: "演講",
      simplified: "演讲",
      pinyin: "yǎn jiǎng",
      english: "Speech",
    },
    {
      traditional: "噢",
      simplified: "噢",
      pinyin: "ō",
      english: "Oh",
    },
    {
      traditional: "活動中心",
      simplified: "活动中心",
      pinyin: "huó dòng zhōng xīn",
      english: "Activity center",
    },
    {
      traditional: "想起來",
      simplified: "想起来",
      pinyin: "xiǎng qǐ lái",
      english: "Think of it",
    },
    {
      traditional: "選",
      simplified: "选",
      pinyin: "xuǎn",
      english: "Selected",
    },
    {
      traditional: "作業",
      simplified: "作业",
      pinyin: "zuò yè",
      english: "Operation",
    },
    {
      traditional: "練習",
      simplified: "练习",
      pinyin: "liàn xí",
      english: "Exercise",
    },
    {
      traditional: "半夜",
      simplified: "半夜",
      pinyin: "bàn yè",
      english: "Midnight",
    },
    {
      traditional: "高興",
      simplified: "高兴",
      pinyin: "gāo xìng",
      english: "Happy",
    },
    {
      traditional: "平常",
      simplified: "平常",
      pinyin: "píng cháng",
      english: "Usually",
    },
    {
      traditional: "爬山",
      simplified: "爬山",
      pinyin: "pá shān",
      english: "Mountain climbing",
    },
    {
      traditional: "認識",
      simplified: "认识",
      pinyin: "rèn shí",
      english: "Understanding",
    },
    {
      traditional: "聊天",
      simplified: "聊天",
      pinyin: "liáo tiān",
      english: "To chat with",
    },
    {
      traditional: "文化",
      simplified: "文化",
      pinyin: "wén huà",
      english: "Culture",
    },
    {
      traditional: "廣告",
      simplified: "广告",
      pinyin: "guǎng gào",
      english: "Advertising",
    },
    {
      traditional: "位",
      simplified: "位",
      pinyin: "wèi",
      english: "Bit",
    },
    {
      traditional: "了解",
      simplified: "了解",
      pinyin: "liǎo jiě",
      english: "To understanding",
    },
    {
      traditional: "生活",
      simplified: "生活",
      pinyin: "shēng huó",
      english: "Life",
    },
    {
      traditional: "陽明山",
      simplified: "阳明山",
      pinyin: "yáng míng shān",
      english: "Yangmingshan",
    },
    {
      traditional: "外國人",
      simplified: "外国人",
      pinyin: "wài guó rén",
      english: "Foreigner",
    },
    {
      traditional: "一些",
      simplified: "一些",
      pinyin: "yī xiē",
      english: "Some",
    },
  ],
};

export default lesson;
