import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "qaAfkslqiu",
  type: "Contemporary Chinese",
  locked: false,
  title: "Book 2 Lesson 1",
  content: [
    {
      traditional: "走",
      simplified: "走",
      pinyin: "zǒu",
      english: "Go",
    },
    {
      traditional: "路人",
      simplified: "路人",
      pinyin: "lù rén",
      english: "Passersby",
    },
    {
      traditional: "幫忙",
      simplified: "帮忙",
      pinyin: "bāng máng",
      english: "Help",
    },
    {
      traditional: "迷路",
      simplified: "迷路",
      pinyin: "mí lù",
      english: "Get lost",
    },
    {
      traditional: "下",
      simplified: "下",
      pinyin: "xià",
      english: "Under",
    },
    {
      traditional: "路口",
      simplified: "路口",
      pinyin: "lù kǒu",
      english: "Intersection",
    },
    {
      traditional: "段",
      simplified: "段",
      pinyin: "duàn",
      english: "Segment",
    },
    {
      traditional: "過",
      simplified: "过",
      pinyin: "guò",
      english: "Pass",
    },
    {
      traditional: "第",
      simplified: "第",
      pinyin: "dì",
      english: "First",
    },
    {
      traditional: "紅綠燈",
      simplified: "红绿灯",
      pinyin: "hóng lǜ dēng",
      english: "Traffic light",
    },
    {
      traditional: "告訴",
      simplified: "告诉",
      pinyin: "gào sù",
      english: "Tell",
    },
    {
      traditional: "提款機",
      simplified: "提款机",
      pinyin: "tí kuǎn jī",
      english: "Atm",
    },
    {
      traditional: "超商",
      simplified: "超商",
      pinyin: "chāo shāng",
      english: "Super business",
    },
    {
      traditional: "應該",
      simplified: "应该",
      pinyin: "yīng gāi",
      english: "Should",
    },
    {
      traditional: "郵局",
      simplified: "邮局",
      pinyin: "yóu jú",
      english: "Post office",
    },
    {
      traditional: "提",
      simplified: "提",
      pinyin: "tí",
      english: "Mention",
    },
    {
      traditional: "那邊",
      simplified: "那边",
      pinyin: "nà biān",
      english: "There",
    },
    {
      traditional: "和平東路",
      simplified: "和平东路",
      pinyin: "hé píng dōng lù",
      english: "Heping east road",
    },
    {
      traditional: "往前",
      simplified: "往前",
      pinyin: "wǎng qián",
      english: "Forward",
    },
    {
      traditional: "右轉",
      simplified: "右转",
      pinyin: "yòu zhuǎn",
      english: "Turn right",
    },
    {
      traditional: "聽起來",
      simplified: "听起来",
      pinyin: "tīng qǐ lái",
      english: "Sound",
    },
    {
      traditional: "看見",
      simplified: "看见",
      pinyin: "kàn jiàn",
      english: "See",
    },
    {
      traditional: "下載",
      simplified: "下载",
      pinyin: "xià zài",
      english: "Download",
    },
    {
      traditional: "地圖",
      simplified: "地图",
      pinyin: "dì tú",
      english: "Map",
    },
    {
      traditional: "好用",
      simplified: "好用",
      pinyin: "hǎo yòng",
      english: "Easy to use",
    },
    {
      traditional: "著",
      simplified: "着",
      pinyin: "zhe",
      english: "With",
    },
    {
      traditional: "日用品",
      simplified: "日用品",
      pinyin: "rì yòng pǐn",
      english: "Daily necessities",
    },
    {
      traditional: "經過",
      simplified: "经过",
      pinyin: "jīng guò",
      english: "After",
    },
    {
      traditional: "巷子",
      simplified: "巷子",
      pinyin: "xiàng zi",
      english: "Alley",
    },
    {
      traditional: "餓",
      simplified: "饿",
      pinyin: "è",
      english: "Hungry",
    },
    {
      traditional: "一邊",
      simplified: "一边",
      pinyin: "yī biān",
      english: "One side",
    },
    {
      traditional: "發現",
      simplified: "发现",
      pinyin: "fā xiàn",
      english: "Find",
    },
    {
      traditional: "離",
      simplified: "离",
      pinyin: "lí",
      english: "From",
    },
    {
      traditional: "背包",
      simplified: "背包",
      pinyin: "bēi bāo",
      english: "Backpack",
    },
    {
      traditional: "正好",
      simplified: "正好",
      pinyin: "zhèng hǎo",
      english: "Just right",
    },
    {
      traditional: "最後",
      simplified: "最后",
      pinyin: "zuì hòu",
      english: "At last",
    },
    {
      traditional: "枝",
      simplified: "枝",
      pinyin: "zhī",
      english: "Branch",
    },
    {
      traditional: "筆",
      simplified: "笔",
      pinyin: "bǐ",
      english: "Pen",
    },
    {
      traditional: "本",
      simplified: "本",
      pinyin: "běn",
      english: "This",
    },
    {
      traditional: "本子",
      simplified: "本子",
      pinyin: "běn zi",
      english: "Book",
    },
    {
      traditional: "左轉",
      simplified: "左转",
      pinyin: "zuǒ zhuǎn",
      english: "Turn left",
    },
    {
      traditional: "師大路上",
      simplified: "师大路上",
      pinyin: "shī dà lù shàng",
      english: "Shida road",
    },
    {
      traditional: "麵店",
      simplified: "面店",
      pinyin: "miàn diàn",
      english: "Noodle shop",
    },
  ],
};

export default lesson;
