import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "qaAR6U7k8Q",
  type: "Contemporary Chinese",
  locked: false,
  title: "Book 1 Lessons 7-15",
  content: [
    {
      simplified: "点",
      traditional: "點",
      pinyin: "diǎn",
      english: "O'clock",
    },
    {
      simplified: "唱歌",
      traditional: "唱歌",
      pinyin: "chàng gē",
      english: "Sing",
    },
    {
      simplified: "分",
      traditional: "分",
      pinyin: "fēn",
      english: "Minute",
    },
    {
      simplified: "见面",
      traditional: "見面",
      pinyin: "jiàn miàn",
      english: "Meet",
    },
    {
      simplified: "从",
      traditional: "從",
      pinyin: "cóng",
      english: "From",
    },
    {
      simplified: "中午",
      traditional: "中午",
      pinyin: "zhōngwǔ",
      english: "Noon",
    },
    {
      simplified: "得",
      traditional: "得",
      pinyin: "dé",
      english: "Get",
    },
    {
      simplified: "银行",
      traditional: "銀行",
      pinyin: "yín háng",
      english: "Bank",
    },
    {
      simplified: "时候",
      traditional: "時候",
      pinyin: "shíhòu",
      english: "Time",
    },
    {
      simplified: "后天",
      traditional: "後天",
      pinyin: "hòutiān",
      english: "Day after tomorrow",
    },
    {
      simplified: "大安",
      traditional: "大安",
      pinyin: "dà'ān",
      english: "Daan",
    },
    {
      simplified: "下次",
      traditional: "下次",
      pinyin: "xià cì",
      english: "Next time",
    },
    {
      simplified: "没问题",
      traditional: "沒問題",
      pinyin: "méi wèntí",
      english: "No problem",
    },
    {
      simplified: "对了",
      traditional: "對了",
      pinyin: "duìle",
      english: "Correct",
    },
    {
      simplified: "有空",
      traditional: "有空",
      pinyin: "yǒu kòng",
      english: "Free",
    },
    {
      simplified: "再见",
      traditional: "再見",
      pinyin: "zàijiàn",
      english: "Goodbye",
    },
    {
      simplified: "午餐",
      traditional: "午餐",
      pinyin: "wǔcān",
      english: "Lunch",
    },
    {
      simplified: "刚",
      traditional: "剛",
      pinyin: "gāng",
      english: "Just",
    },
    {
      simplified: "下课",
      traditional: "下課",
      pinyin: "xiàkè",
      english: "After class",
    },
    {
      simplified: "下午",
      traditional: "下午",
      pinyin: "xiàwǔ",
      english: "In the afternoon",
    },
    {
      simplified: "半",
      traditional: "半",
      pinyin: "bàn",
      english: "Half",
    },
    {
      simplified: "比赛",
      traditional: "比賽",
      pinyin: "bǐsài",
      english: "Game",
    },
    {
      simplified: "结束",
      traditional: "結束",
      pinyin: "jiéshù",
      english: "End",
    },
    {
      simplified: "最近",
      traditional: "最近",
      pinyin: "zuì jìn",
      english: "Recent",
    },
    {
      simplified: "忙",
      traditional: "忙",
      pinyin: "máng",
      english: "Busy",
    },
    {
      simplified: "每",
      traditional: "每",
      pinyin: "měi",
      english: "Each",
    },
    {
      simplified: "天",
      traditional: "天",
      pinyin: "tiān",
      english: "Day",
    },
    {
      simplified: "书法",
      traditional: "書法",
      pinyin: "shū fǎ",
      english: "Calligraphy",
    },
    {
      simplified: "课",
      traditional: "課",
      pinyin: "kè",
      english: "Class",
    },
    {
      simplified: "开始",
      traditional: "開始",
      pinyin: "kāi shǐ",
      english: "Start",
    },
    {
      simplified: "字",
      traditional: "字",
      pinyin: "zì",
      english: "Word",
    },
    {
      simplified: "写",
      traditional: "寫",
      pinyin: "xiě",
      english: "Write",
    },
    {
      simplified: "可以",
      traditional: "可以",
      pinyin: "kě yǐ",
      english: "Can",
    },
    {
      simplified: "问",
      traditional: "問",
      pinyin: "wèn",
      english: "Ask",
    },
    {
      simplified: "等一下",
      traditional: "等一下",
      pinyin: "děng yī xià",
      english: "Wait",
    },
    {
      simplified: "有事",
      traditional: "有事",
      pinyin: "yǒu shì",
      english: "Something",
    },
    {
      simplified: "有意思",
      traditional: "有意思",
      pinyin: "yǒu yì si",
      english: "Interesting",
    },
    {
      simplified: "坐",
      traditional: "坐",
      pinyin: "zuò",
      english: "Sit",
    },
    {
      simplified: "火车",
      traditional: "火車",
      pinyin: "huǒchē",
      english: "Train",
    },
    {
      simplified: "跟",
      traditional: "跟",
      pinyin: "gēn",
      english: "With",
    },
    {
      simplified: "玩",
      traditional: "玩",
      pinyin: "wán",
      english: "Play",
    },
    {
      simplified: "怎么",
      traditional: "怎麼",
      pinyin: "zěn me",
      english: "How",
    },
    {
      simplified: "慢",
      traditional: "慢",
      pinyin: "màn",
      english: "Slow",
    },
    {
      simplified: "钟头",
      traditional: "鐘頭",
      pinyin: "zhōngtóu",
      english: "Hour",
    },
    {
      simplified: "比较",
      traditional: "比較",
      pinyin: "bǐjiào",
      english: "Compare",
    },
    {
      simplified: "快",
      traditional: "快",
      pinyin: "kuài",
      english: "Fast",
    },
    {
      simplified: "车票",
      traditional: "車票",
      pinyin: "chēpiào",
      english: "Ticket",
    },
    {
      simplified: "非常",
      traditional: "非常",
      pinyin: "fēi cháng",
      english: "Very much",
    },
    {
      simplified: "但是",
      traditional: "但是",
      pinyin: "dànshì",
      english: "But",
    },
    {
      simplified: "又",
      traditional: "又",
      pinyin: "yòu",
      english: "Also",
    },
    {
      simplified: "舒服",
      traditional: "舒服",
      pinyin: "shūfú",
      english: "Comfortable",
    },
    {
      simplified: "站",
      traditional: "站",
      pinyin: "zhàn",
      english: "Station",
    },
    {
      simplified: "或是",
      traditional: "或是",
      pinyin: "huò shì",
      english: "Or",
    },
    {
      simplified: "台南",
      traditional: "臺南",
      pinyin: "táinán",
      english: "Tainan",
    },
    {
      simplified: "高铁",
      traditional: "高鐵",
      pinyin: "gāotiě",
      english: "High speed rail",
    },
    {
      simplified: "网路上",
      traditional: "網路上",
      pinyin: "wǎng lùshàng",
      english: "Online",
    },
    {
      simplified: "便利商店",
      traditional: "便利商店",
      pinyin: "biànlì shāngdiàn",
      english: "Convenience store",
    },
    {
      simplified: "同学",
      traditional: "同學",
      pinyin: "tóngxué",
      english: "Classmate",
    },
    {
      simplified: "参观",
      traditional: "參觀",
      pinyin: "cānguān",
      english: "Visit",
    },
    {
      simplified: "古代",
      traditional: "古代",
      pinyin: "gǔdài",
      english: "Ancient",
    },
    {
      simplified: "骑",
      traditional: "騎",
      pinyin: "qí",
      english: "Ride",
    },
    {
      simplified: "机车",
      traditional: "機車",
      pinyin: "jī chē",
      english: "Locomotive",
    },
    {
      simplified: "载",
      traditional: "載",
      pinyin: "zài",
      english: "To give a ride, pick up",
    },
    {
      simplified: "捷运",
      traditional: "捷運",
      pinyin: "jié yùn",
      english: "Mrt",
    },
    {
      simplified: "比",
      traditional: "比",
      pinyin: "bǐ",
      english: "Ratio",
    },
    {
      simplified: "中国",
      traditional: "中國",
      pinyin: "zhōngguó",
      english: "China",
    },
    {
      simplified: "公共汽车",
      traditional: "公共汽車",
      pinyin: "gōnggòng qìchē",
      english: "Bus",
    },
    {
      simplified: "不行",
      traditional: "不行",
      pinyin: "bùxíng",
      english: "No way",
    },
    {
      simplified: "计程车",
      traditional: "計程車",
      pinyin: "jìchéngchē",
      english: "Taxi",
    },
    {
      simplified: "差不多",
      traditional: "差不多",
      pinyin: "chàbùduō",
      english: "Almost",
    },
    {
      simplified: "星期",
      traditional: "星期",
      pinyin: "xīng qī",
      english: "Week",
    },
    {
      simplified: "回国",
      traditional: "回國",
      pinyin: "huí guó",
      english: "Return home",
    },
    {
      simplified: "打算",
      traditional: "打算",
      pinyin: "dǎ suàn",
      english: "Plan, intend",
    },
    {
      simplified: "电视",
      traditional: "電視",
      pinyin: "diàn shì",
      english: "Tv",
    },
    {
      simplified: "影片",
      traditional: "影片",
      pinyin: "yǐng piàn",
      english: "Film",
    },
    {
      simplified: "旅行",
      traditional: "旅行",
      pinyin: "lǚ xíng",
      english: "Travel",
    },
    {
      simplified: "功课",
      traditional: "功課",
      pinyin: "gōng kè",
      english: "Homework",
    },
    {
      simplified: "出去",
      traditional: "出去",
      pinyin: "chū qù",
      english: "Go out",
    },
    {
      simplified: "大概",
      traditional: "大概",
      pinyin: "dà gài",
      english: "Probably",
    },
    {
      simplified: "放假",
      traditional: "放假",
      pinyin: "fàng jià",
      english: "Holiday",
    },
    {
      simplified: "下个星期",
      traditional: "下個星期",
      pinyin: "xià gè xīng qī",
      english: "Next week",
    },
    {
      simplified: "有时候",
      traditional: "有時候",
      pinyin: "yǒu shí hou",
      english: "Sometimes",
    },
    {
      simplified: "多久",
      traditional: "多久",
      pinyin: "duō jiǔ",
      english: "How long",
    },
    {
      simplified: "台东",
      traditional: "臺東",
      pinyin: "tái dōng",
      english: "Taitung",
    },
    {
      simplified: "女",
      traditional: "女",
      pinyin: "nǚ",
      english: "Female",
    },
    {
      simplified: "月",
      traditional: "月",
      pinyin: "yuè",
      english: "Month",
    },
    {
      simplified: "号",
      traditional: "號",
      pinyin: "háo",
      english: "Number",
    },
    {
      simplified: "带",
      traditional: "帶",
      pinyin: "dài",
      english: "Band",
    },
    {
      simplified: "她",
      traditional: "她",
      pinyin: "tā",
      english: "She",
    },
    {
      simplified: "还",
      traditional: "還",
      pinyin: "hái",
      english: "Also",
    },
    {
      simplified: "建议",
      traditional: "建議",
      pinyin: "jiàn yì",
      english: "Suggest",
    },
    {
      simplified: "夜市",
      traditional: "夜市",
      pinyin: "yè shì",
      english: "Night market",
    },
    {
      simplified: "应该",
      traditional: "應該",
      pinyin: "yīng gāi",
      english: "Should",
    },
    {
      simplified: "逛",
      traditional: "逛",
      pinyin: "guàng",
      english: "Wander around",
    },
    {
      simplified: "特别",
      traditional: "特別",
      pinyin: "tè bié",
      english: "Special",
    },
    {
      simplified: "茶馆",
      traditional: "茶館",
      pinyin: "chá guǎn",
      english: "Teahouse",
    },
    {
      simplified: "决定",
      traditional: "決定",
      pinyin: "jué dìng",
      english: "Decide",
    },
    {
      simplified: "要是",
      traditional: "要是",
      pinyin: "yào shi",
      english: "If",
    },
    {
      simplified: "就",
      traditional: "就",
      pinyin: "jiù",
      english: "Then",
    },
    {
      simplified: "水果",
      traditional: "水果",
      pinyin: "shuǐguǒ",
      english: "Fruit",
    },
    {
      simplified: "黄色",
      traditional: "黃色",
      pinyin: "huángsè",
      english: "Yellow",
    },
    {
      simplified: "芒果",
      traditional: "芒果",
      pinyin: "mángguǒ",
      english: "Mango",
    },
    {
      simplified: "给",
      traditional: "給",
      pinyin: "gěi",
      english: "To give",
    },
    {
      simplified: "块",
      traditional: "塊",
      pinyin: "kuài",
      english: "Piece of food",
    },
    {
      simplified: "想",
      traditional: "想",
      pinyin: "xiǎng",
      english: "Fragrant",
    },
    {
      simplified: "甜",
      traditional: "甜",
      pinyin: "tián",
      english: "Sweet (taste)",
    },
    {
      simplified: "红色",
      traditional: "紅色",
      pinyin: "hóngsè",
      english: "Red",
    },
    {
      simplified: "西瓜",
      traditional: "西瓜",
      pinyin: "xīguā",
      english: "Watermelon",
    },
    {
      simplified: "吧",
      traditional: "吧",
      pinyin: "ba",
      english: "Sentence finale particle (guessing)",
    },
    {
      simplified: "对",
      traditional: "對",
      pinyin: "duì",
      english: "Correct, right",
    },
    {
      simplified: "以前",
      traditional: "以前",
      pinyin: "yǐqián",
      english: "Before",
    },
    {
      simplified: "机会",
      traditional: "機會",
      pinyin: "jīhuì",
      english: "Opportunity",
    },
    {
      simplified: "请",
      traditional: "請",
      pinyin: "qǐng",
      english: "To treat someone",
    },
    {
      simplified: "香蕉",
      traditional: "香蕉",
      pinyin: "xiāngjiāo",
      english: "Banana",
    },
    {
      simplified: "菠萝",
      traditional: "菠蘿",
      pinyin: "bōluó",
      english: "Pineapple",
    },
    {
      simplified: "草莓",
      traditional: "草莓",
      pinyin: "cǎoméi",
      english: "Strawberry",
    },
    {
      simplified: "蓝莓",
      traditional: "藍莓",
      pinyin: "lánméi",
      english: "Blueberry",
    },
    {
      simplified: "葡萄",
      traditional: "葡萄",
      pinyin: "pútáo",
      english: "Grape",
    },
    {
      simplified: "拍",
      traditional: "拍",
      pinyin: "pāi",
      english: "To take a picture",
    },
    {
      simplified: "笑",
      traditional: "笑",
      pinyin: "xiào",
      english: "Laugh, smile",
    },
    {
      simplified: "开心",
      traditional: "開心",
      pinyin: "kāixīn",
      english: "Happy",
    },
    {
      simplified: "穿",
      traditional: "穿",
      pinyin: "chuān",
      english: "Wear",
    },
    {
      simplified: "衣服",
      traditional: "衣服",
      pinyin: "yīfú",
      english: "Clothes",
    },
    {
      simplified: "旅馆",
      traditional: "旅館",
      pinyin: "lǚguǎn",
      english: "Hotel",
    },
    {
      simplified: "太太",
      traditional: "太太",
      pinyin: "tàitài",
      english: "Wife",
    },
    {
      simplified: "男",
      traditional: "男",
      pinyin: "nán",
      english: "Boy, male",
    },
    {
      simplified: "矮",
      traditional: "矮",
      pinyin: "ǎi",
      english: "Short",
    },
    {
      simplified: "高",
      traditional: "高",
      pinyin: "gāo",
      english: "Tall",
    },
    {
      simplified: "弟弟",
      traditional: "弟弟",
      pinyin: "dìdì",
      english: "Younger brother",
    },
    {
      simplified: "干净",
      traditional: "乾淨",
      pinyin: "gānjìng",
      english: "Clean",
    },
    {
      simplified: "窗户",
      traditional: "窗戶",
      pinyin: "chuānghù",
      english: "Window",
    },
    {
      simplified: "往",
      traditional: "往",
      pinyin: "wǎng",
      english: "To, toward",
    },
    {
      simplified: "蓝色",
      traditional: "藍色",
      pinyin: "lánsè",
      english: "Blue",
    },
    {
      simplified: "因为",
      traditional: "因為",
      pinyin: "yīnwèi",
      english: "Because",
    },
    {
      simplified: "住",
      traditional: "住",
      pinyin: "zhù",
      english: "To stay",
    },
    {
      simplified: "上个月",
      traditional: "上個月",
      pinyin: "shàng gè yuè",
      english: "Last month",
    },
    {
      simplified: "这些",
      traditional: "這些",
      pinyin: "zhèxiē",
      english: "These",
    },
    {
      traditional: "租",
      simplified: "租",
      pinyin: "zū",
      english: "Rent",
    },
    {
      traditional: "房東",
      simplified: "房东",
      pinyin: "fáng dōng",
      english: "Landlord",
    },
    {
      traditional: "客廳",
      simplified: "客厅",
      pinyin: "kè tīng",
      english: "Living room",
    },
    {
      traditional: "廚房",
      simplified: "厨房",
      pinyin: "chú fáng",
      english: "Kitchen",
    },
    {
      traditional: "左邊",
      simplified: "左边",
      pinyin: "zuǒ biān",
      english: "Left",
    },
    {
      traditional: "右邊",
      simplified: "右边",
      pinyin: "yòu biān",
      english: "Right",
    },
    {
      traditional: "浴室",
      simplified: "浴室",
      pinyin: "yù shì",
      english: "Bathroom",
    },
    {
      traditional: "超市",
      simplified: "超市",
      pinyin: "chāo shì",
      english: "Supermarket",
    },
    {
      traditional: "走路",
      simplified: "走路",
      pinyin: "zǒu lù",
      english: "Walk",
    },
    {
      traditional: "分鐘",
      simplified: "分钟",
      pinyin: "fēn zhōng",
      english: "Minute",
    },
    {
      traditional: "就",
      simplified: "就",
      pinyin: "jiù",
      english: "On",
    },
    {
      traditional: "到",
      simplified: "到",
      pinyin: "dào",
      english: "To",
    },
    {
      traditional: "間",
      simplified: "间",
      pinyin: "jiān",
      english: "Between",
    },
    {
      traditional: "空",
      simplified: "空",
      pinyin: "kōng",
      english: "Air",
    },
    {
      traditional: "房間",
      simplified: "房间",
      pinyin: "fáng jiān",
      english: "Room",
    },
    {
      traditional: "套房",
      simplified: "套房",
      pinyin: "tào fáng",
      english: "Suite",
    },
    {
      traditional: "回去",
      simplified: "回去",
      pinyin: "huí qù",
      english: "Go back",
    },
    {
      traditional: "想",
      simplified: "想",
      pinyin: "xiǎng",
      english: "Miss you",
    },
    {
      traditional: "再",
      simplified: "再",
      pinyin: "zài",
      english: "Again",
    },
    {
      traditional: "電話",
      simplified: "电话",
      pinyin: "diàn huà",
      english: "Phone",
    },
    {
      traditional: "給",
      simplified: "给",
      pinyin: "gěi",
      english: "Give",
    },
    {
      traditional: "林",
      simplified: "林",
      pinyin: "lín",
      english: "Common Chinese Surname",
    },
    {
      traditional: "打電話",
      simplified: "打电话",
      pinyin: "dǎ diàn huà",
      english: "Make a call",
    },
    {
      traditional: "喂",
      simplified: "喂",
      pinyin: "wèi",
      english: "Hey",
    },
    {
      traditional: "房租",
      simplified: "房租",
      pinyin: "fáng zū",
      english: "Rent",
    },
    {
      traditional: "已經",
      simplified: "已经",
      pinyin: "yǐ jīng",
      english: "Already",
    },
    {
      traditional: "習慣",
      simplified: "习惯",
      pinyin: "xí guàn",
      english: "Habit",
    },
    {
      traditional: "問題",
      simplified: "问题",
      pinyin: "wèn tí",
      english: "Problem",
    },
    {
      traditional: "熱水器",
      simplified: "热水器",
      pinyin: "rè shuǐ qì",
      english: "Water heater",
    },
    {
      traditional: "好像",
      simplified: "好像",
      pinyin: "hǎo xiàng",
      english: "Like",
    },
    {
      traditional: "會",
      simplified: "会",
      pinyin: "huì",
      english: "Meeting",
    },
    {
      traditional: "等",
      simplified: "等",
      pinyin: "děng",
      english: "Wait",
    },
    {
      traditional: "那",
      simplified: "那",
      pinyin: "nà",
      english: "That",
    },
    {
      traditional: "裝",
      simplified: "装",
      pinyin: "zhuāng",
      english: "Attire",
    },
    {
      traditional: "不過",
      simplified: "不过",
      pinyin: "bù guò",
      english: "But",
    },
    {
      traditional: "付",
      simplified: "付",
      pinyin: "fù",
      english: "Pay",
    },
    {
      traditional: "收到",
      simplified: "收到",
      pinyin: "shōu dào",
      english: "Roger that",
    },
    {
      traditional: "不好意思",
      simplified: "不好意思",
      pinyin: "bù hǎo yì sī",
      english: "Sorry",
    },
    {
      traditional: "有線電視",
      simplified: "有线电视",
      pinyin: "yǒu xiàn diàn shì",
      english: "Cable tv",
    },
    {
      traditional: "計畫",
      simplified: "计画",
      pinyin: "jì huà",
      english: "Plan",
    },
    {
      traditional: "年",
      simplified: "年",
      pinyin: "nián",
      english: "Year",
    },
    {
      traditional: "久",
      simplified: "久",
      pinyin: "jiǔ",
      english: "Long",
    },
    {
      traditional: "時間",
      simplified: "时间",
      pinyin: "shí jiān",
      english: "Time",
    },
    {
      traditional: "先",
      simplified: "先",
      pinyin: "xiān",
      english: "First",
    },
    {
      traditional: "念",
      simplified: "念",
      pinyin: "niàn",
      english: "Read",
    },
    {
      traditional: "大學",
      simplified: "大学",
      pinyin: "dà xué",
      english: "The university",
    },
    {
      traditional: "需要",
      simplified: "需要",
      pinyin: "xū yào",
      english: "Need",
    },
    {
      traditional: "花",
      simplified: "花",
      pinyin: "huā",
      english: "Flower",
    },
    {
      traditional: "獎學金",
      simplified: "奖学金",
      pinyin: "jiǎng xué jīn",
      english: "Scholarship",
    },
    {
      traditional: "成績",
      simplified: "成绩",
      pinyin: "chéng jī",
      english: "Grades",
    },
    {
      traditional: "公司",
      simplified: "公司",
      pinyin: "gōng sī",
      english: "The company",
    },
    {
      traditional: "替",
      simplified: "替",
      pinyin: "tì",
      english: "For",
    },
    {
      traditional: "希望",
      simplified: "希望",
      pinyin: "xī wàng",
      english: "Hope",
    },
    {
      traditional: "以後",
      simplified: "以后",
      pinyin: "yǐ hòu",
      english: "After",
    },
    {
      traditional: "到",
      simplified: "到",
      pinyin: "dào",
      english: "To",
    },
    {
      traditional: "上班",
      simplified: "上班",
      pinyin: "shàng bān",
      english: "Go to work",
    },
    {
      traditional: "念書",
      simplified: "念书",
      pinyin: "niàn shū",
      english: "Study",
    },
    {
      traditional: "累",
      simplified: "累",
      pinyin: "lèi",
      english: "Tired",
    },
    {
      traditional: "語言中心",
      simplified: "语言中心",
      pinyin: "yǔ yán zhōng xīn",
      english: "Language center",
    },
    {
      traditional: "加油",
      simplified: "加油",
      pinyin: "jiā yóu",
      english: "Come on",
    },
    {
      traditional: "工作",
      simplified: "工作",
      pinyin: "gōng zuò",
      english: "Jobs",
    },
    {
      traditional: "去年",
      simplified: "去年",
      pinyin: "qù nián",
      english: "Last year",
    },
    {
      traditional: "做",
      simplified: "做",
      pinyin: "zuò",
      english: "Do",
    },
    {
      traditional: "生意",
      simplified: "生意",
      pinyin: "shēng yì",
      english: "Business",
    },
    {
      traditional: "以後",
      simplified: "以后",
      pinyin: "yǐ hòu",
      english: "After",
    },
    {
      traditional: "找",
      simplified: "找",
      pinyin: "zhǎo",
      english: "Find",
    },
    {
      traditional: "這樣",
      simplified: "这样",
      pinyin: "zhè yàng",
      english: "Such",
    },
    {
      traditional: "國家",
      simplified: "国家",
      pinyin: "guó jiā",
      english: "Country",
    },
    {
      traditional: "試",
      simplified: "试",
      pinyin: "shì",
      english: "Test",
    },
    {
      traditional: "難",
      simplified: "难",
      pinyin: "nán",
      english: "Difficult",
    },
    {
      traditional: "那麼",
      simplified: "那么",
      pinyin: "nà me",
      english: "Then",
    },
    {
      traditional: "再",
      simplified: "再",
      pinyin: "zài",
      english: "Again",
    },
    {
      traditional: "試試看",
      simplified: "试试看",
      pinyin: "shì shì kàn",
      english: "Try it",
    },
    {
      traditional: "生日",
      simplified: "生日",
      pinyin: "shēng rì",
      english: "Birthday",
    },
    {
      traditional: "快樂",
      simplified: "快乐",
      pinyin: "kuài lè",
      english: "Happy",
    },
    {
      traditional: "回來",
      simplified: "回来",
      pinyin: "huí lái",
      english: "Come back",
    },
    {
      traditional: "啊",
      simplified: "啊",
      pinyin: "a",
      english: "What",
    },
    {
      traditional: "怎麼",
      simplified: "怎么",
      pinyin: "zěn me",
      english: "How",
    },
    {
      traditional: "忘了",
      simplified: "忘了",
      pinyin: "wàng le",
      english: "Forget",
    },
    {
      traditional: "記得",
      simplified: "记得",
      pinyin: "jì dé",
      english: "Remember",
    },
    {
      traditional: "當然",
      simplified: "当然",
      pinyin: "dāng rán",
      english: "Of course",
    },
    {
      traditional: "語言",
      simplified: "语言",
      pinyin: "yǔ yán",
      english: "Language",
    },
    {
      traditional: "交換",
      simplified: "交换",
      pinyin: "jiāo huàn",
      english: "Exchange",
    },
    {
      traditional: "那麼",
      simplified: "那么",
      pinyin: "nà me",
      english: "Then",
    },
    {
      traditional: "熱心",
      simplified: "热心",
      pinyin: "rè xīn",
      english: "Enthusiastic",
    },
    {
      traditional: "西班牙文",
      simplified: "西班牙文",
      pinyin: "xī bān yá wén",
      english: "Spanish",
    },
    {
      traditional: "一樣",
      simplified: "一样",
      pinyin: "yī yàng",
      english: "Same",
    },
    {
      traditional: "過",
      simplified: "过",
      pinyin: "guò",
      english: "Pass",
    },
    {
      traditional: "左右",
      simplified: "左右",
      pinyin: "zuǒ yòu",
      english: "About",
    },
    {
      traditional: "門口",
      simplified: "门口",
      pinyin: "mén kǒu",
      english: "Doorway",
    },
    {
      traditional: "西班牙",
      simplified: "西班牙",
      pinyin: "xī bān yá",
      english: "Spain",
    },
    {
      traditional: "生日快樂",
      simplified: "生日快乐",
      pinyin: "shēng rì kuài lè",
      english: "Happy birthday",
    },
    {
      traditional: "我就是",
      simplified: "我就是",
      pinyin: "wǒ jiù shì",
      english: "I am",
    },
    {
      traditional: "好久不見",
      simplified: "好久不见",
      pinyin: "hǎo jiǔ bù jiàn",
      english: "Long time no see",
    },
    {
      traditional: "不必客氣",
      simplified: "不必客气",
      pinyin: "bù bì kè qì",
      english: "It's my pleasure",
    },
    {
      traditional: "太客氣",
      simplified: "太客气",
      pinyin: "tài kè qì",
      english: "That's very kind of you",
    },
    {
      traditional: "禮物",
      simplified: "礼物",
      pinyin: "lǐ wù",
      english: "Gift",
    },
    {
      traditional: "今年",
      simplified: "今年",
      pinyin: "jīn nián",
      english: "This year",
    },
    {
      traditional: "訂",
      simplified: "订",
      pinyin: "dìng",
      english: "Order",
    },
    {
      traditional: "了",
      simplified: "了",
      pinyin: "le",
      english: "Up",
    },
    {
      traditional: "豬腳",
      simplified: "猪脚",
      pinyin: "zhū jiǎo",
      english: "Pig's feet",
    },
    {
      traditional: "麵線",
      simplified: "面线",
      pinyin: "miàn xiàn",
      english: "Noodles",
    },
    {
      traditional: "蛋",
      simplified: "蛋",
      pinyin: "dàn",
      english: "Egg",
    },
    {
      traditional: "一點",
      simplified: "一点",
      pinyin: "yī diǎn",
      english: "A little",
    },
    {
      traditional: "傳統",
      simplified: "传统",
      pinyin: "chuán tǒng",
      english: "Traditional",
    },
    {
      traditional: "年輕",
      simplified: "年轻",
      pinyin: "nián qīng",
      english: "Young",
    },
    {
      traditional: "蛋糕",
      simplified: "蛋糕",
      pinyin: "dàn gāo",
      english: "Cake",
    },
    {
      traditional: "對",
      simplified: "对",
      pinyin: "duì",
      english: "Correct",
    },
    {
      traditional: "祝",
      simplified: "祝",
      pinyin: "zhù",
      english: "Wish",
    },
    {
      traditional: "哪裡，哪裡",
      simplified: "哪里，哪里",
      pinyin: "nǎ lǐ nǎ lǐ",
      english: "My pleasure",
    },
    {
      traditional: "大部分",
      simplified: "大部分",
      pinyin: "dà bù fèn",
      english: "Most",
    },
    {
      traditional: "萬事如意",
      simplified: "万事如意",
      pinyin: "wàn shì rú yì",
      english: "Everything goes well",
    },
    {
      traditional: "心想事成",
      simplified: "心想事成",
      pinyin: "xīn xiǎng shì chéng",
      english: "All wishes come true",
    },
    {
      traditional: "天氣",
      simplified: "天气",
      pinyin: "tiān qì",
      english: "The weather",
    },
    {
      traditional: "冷",
      simplified: "冷",
      pinyin: "lěng",
      english: "Cold",
    },
    {
      traditional: "風",
      simplified: "风",
      pinyin: "fēng",
      english: "Wind",
    },
    {
      traditional: "滑雪",
      simplified: "滑雪",
      pinyin: "huá xuě",
      english: "Ski",
    },
    {
      traditional: "春天",
      simplified: "春天",
      pinyin: "chūn tiān",
      english: "Spring",
    },
    {
      traditional: "想",
      simplified: "想",
      pinyin: "xiǎng",
      english: "Miss you",
    },
    {
      traditional: "新年",
      simplified: "新年",
      pinyin: "xīn nián",
      english: "New year",
    },
    {
      traditional: "快",
      simplified: "快",
      pinyin: "kuài",
      english: "Fast",
    },
    {
      traditional: "父母",
      simplified: "父母",
      pinyin: "fù mǔ",
      english: "Parents",
    },
    {
      traditional: "冬天",
      simplified: "冬天",
      pinyin: "dōng tiān",
      english: "Winter",
    },
    {
      traditional: "明年",
      simplified: "明年",
      pinyin: "míng nián",
      english: "Next year",
    },
    {
      traditional: "秋天",
      simplified: "秋天",
      pinyin: "qiū tiān",
      english: "Fall",
    },
    {
      traditional: "紅葉",
      simplified: "红叶",
      pinyin: "hóng yè",
      english: "Red leaves",
    },
    {
      traditional: "只",
      simplified: "只",
      pinyin: "zhǐ",
      english: "Only",
    },
    {
      traditional: "玉山",
      simplified: "玉山",
      pinyin: "yù shān",
      english: "Yushan",
    },
    {
      traditional: "紐約",
      simplified: "纽约",
      pinyin: "niǔ yuē",
      english: "New york",
    },
    {
      traditional: "下雪",
      simplified: "下雪",
      pinyin: "xià xuě",
      english: "Snowing",
    },
    {
      traditional: "十二月底",
      simplified: "十二月底",
      pinyin: "shí èr yuè dǐ",
      english: "End of december",
    },
    {
      traditional: "雨",
      simplified: "雨",
      pinyin: "yǔ",
      english: "Rain",
    },
    {
      traditional: "傘",
      simplified: "伞",
      pinyin: "sǎn",
      english: "Umbrella",
    },
    {
      traditional: "颱風",
      simplified: "台风",
      pinyin: "tái fēng",
      english: "Typhoon",
    },
    {
      traditional: "要",
      simplified: "要",
      pinyin: "yào",
      english: "Want",
    },
    {
      traditional: "夏天",
      simplified: "夏天",
      pinyin: "xià tiān",
      english: "Summer",
    },
    {
      traditional: "濕",
      simplified: "湿",
      pinyin: "shī",
      english: "Wet",
    },
    {
      traditional: "討厭",
      simplified: "讨厌",
      pinyin: "tǎo yàn",
      english: "Hate",
    },
    {
      traditional: "新聞",
      simplified: "新闻",
      pinyin: "xīn wén",
      english: "News",
    },
    {
      traditional: "更",
      simplified: "更",
      pinyin: "gèng",
      english: "More",
    },
    {
      traditional: "大家",
      simplified: "大家",
      pinyin: "dà jiā",
      english: "Everyone",
    },
    {
      traditional: "小心",
      simplified: "小心",
      pinyin: "xiǎo xīn",
      english: "Be careful",
    },
    {
      traditional: "可怕",
      simplified: "可怕",
      pinyin: "kě pà",
      english: "Terrible",
    },
    {
      traditional: "停",
      simplified: "停",
      pinyin: "tíng",
      english: "Stop",
    },
    {
      traditional: "下雨",
      simplified: "下雨",
      pinyin: "xià yǔ",
      english: "Rain",
    },
    {
      traditional: "這次",
      simplified: "这次",
      pinyin: "zhè cì",
      english: "This time",
    },
    {
      traditional: "上次",
      simplified: "上次",
      pinyin: "shàng cì",
      english: "Last time",
    },
    {
      traditional: "慢走",
      simplified: "慢走",
      pinyin: "màn zǒu",
      english: "Walk slowly",
    },
    {
      traditional: "醫生",
      simplified: "医生",
      pinyin: "yī shēng",
      english: "Doctors",
    },
    {
      traditional: "一直",
      simplified: "一直",
      pinyin: "yī zhí",
      english: "Always",
    },
    {
      traditional: "流",
      simplified: "流",
      pinyin: "liú",
      english: "Flow",
    },
    {
      traditional: "鼻水",
      simplified: "鼻水",
      pinyin: "bí shuǐ",
      english: "Nose water",
    },
    {
      traditional: "頭",
      simplified: "头",
      pinyin: "tóu",
      english: "Head",
    },
    {
      traditional: "痛",
      simplified: "痛",
      pinyin: "tòng",
      english: "Pain",
    },
    {
      traditional: "胃口",
      simplified: "胃口",
      pinyin: "wèi kǒu",
      english: "Appetite",
    },
    {
      traditional: "差",
      simplified: "差",
      pinyin: "chà",
      english: "Difference",
    },
    {
      traditional: "喉嚨",
      simplified: "喉咙",
      pinyin: "hóu lóng",
      english: "Throat",
    },
    {
      traditional: "發炎",
      simplified: "发炎",
      pinyin: "fā yán",
      english: "Fever",
    },
    {
      traditional: "生病",
      simplified: "生病",
      pinyin: "shēng bìng",
      english: "Sick",
    },
    {
      traditional: "發燒",
      simplified: "发烧",
      pinyin: "fā shāo",
      english: "Fever",
    },
    {
      traditional: "感冒",
      simplified: "感冒",
      pinyin: "gǎn mào",
      english: "Cold",
    },
    {
      traditional: "藥",
      simplified: "药",
      pinyin: "yào",
      english: "Medicine",
    },
    {
      traditional: "藥局",
      simplified: "药局",
      pinyin: "yào jú",
      english: "Pharmacy",
    },
    {
      traditional: "拿",
      simplified: "拿",
      pinyin: "ná",
      english: "Take",
    },
    {
      traditional: "把",
      simplified: "把",
      pinyin: "bǎ",
      english: "Put",
    },
    {
      traditional: "水",
      simplified: "水",
      pinyin: "shuǐ",
      english: "Water",
    },
    {
      traditional: "休息",
      simplified: "休息",
      pinyin: "xiū xī",
      english: "Rest",
    },
    {
      traditional: "睡覺",
      simplified: "睡觉",
      pinyin: "shuì jué",
      english: "Go to bed",
    },
    {
      traditional: "早一點",
      simplified: "早一点",
      pinyin: "zǎo yī diǎn",
      english: "Earlier",
    },
    {
      traditional: "臉色",
      simplified: "脸色",
      pinyin: "liǎn sè",
      english: "Face",
    },
    {
      traditional: "難看",
      simplified: "难看",
      pinyin: "nán kàn",
      english: "Ugly",
    },
    {
      traditional: "肚子",
      simplified: "肚子",
      pinyin: "dǔ zi",
      english: "Belly",
    },
    {
      traditional: "吐",
      simplified: "吐",
      pinyin: "tǔ",
      english: "Threw up",
    },
    {
      traditional: "幾",
      simplified: "几",
      pinyin: "jǐ",
      english: "A few",
    },
    {
      traditional: "次",
      simplified: "次",
      pinyin: "cì",
      english: "Times",
    },
    {
      traditional: "陪",
      simplified: "陪",
      pinyin: "péi",
      english: "Accompany",
    },
    {
      traditional: "看病",
      simplified: "看病",
      pinyin: "kàn bìng",
      english: "See a doctor",
    },
    {
      traditional: "健康",
      simplified: "健康",
      pinyin: "jiàn kāng",
      english: "Health",
    },
    {
      traditional: "保險",
      simplified: "保险",
      pinyin: "bǎo xiǎn",
      english: "Insurance",
    },
    {
      traditional: "跟",
      simplified: "跟",
      pinyin: "gēn",
      english: "With",
    },
    {
      traditional: "油",
      simplified: "油",
      pinyin: "yóu",
      english: "Oil",
    },
    {
      traditional: "冰",
      simplified: "冰",
      pinyin: "bīng",
      english: "Ice",
    },
    {
      traditional: "別",
      simplified: "别",
      pinyin: "bié",
      english: "Do not",
    },
    {
      traditional: "關心",
      simplified: "关心",
      pinyin: "guān xīn",
      english: "Concern",
    },
    {
      traditional: "包",
      simplified: "包",
      pinyin: "bāo",
      english: "Package",
    },
    {
      traditional: "睡",
      simplified: "睡",
      pinyin: "shuì",
      english: "Sleep",
    },
    {
      traditional: "小時",
      simplified: "小时",
      pinyin: "xiǎo shí",
      english: "Hour",
    },
    {
      traditional: "怎麼了",
      simplified: "怎么了",
      pinyin: "zěn me le",
      english: "What's happenin",
    },
    {
      traditional: "不用了",
      simplified: "不用了",
      pinyin: "bù yòng le",
      english: "No need",
    },
    {
      traditional: "健康中心",
      simplified: "健康中心",
      pinyin: "jiàn kāng zhōng xīn",
      english: "Health center",
    },
    {
      traditional: "回家",
      simplified: "回家",
      pinyin: "huí jiā",
      english: "Come back home",
    },
    {
      traditional: "最好",
      simplified: "最好",
      pinyin: "zuì hǎo",
      english: "The best",
    },
  ],
};

export default lesson;
