import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "1zsol3qmsx",
  type: "Contemporary Chinese",
  locked: false,
  title: "Book 2 Lesson 5",
  content: [
    {
      traditional: "喜酒",
      simplified: "喜酒",
      pinyin: "xǐ jiǔ",
      english: "Wedding wine",
    },
    {
      traditional: "恭喜",
      simplified: "恭喜",
      pinyin: "gōng xǐ",
      english: "Congratulations",
    },
    {
      traditional: "新娘",
      simplified: "新娘",
      pinyin: "xīn niáng",
      english: "Bride",
    },
    {
      traditional: "參加",
      simplified: "参加",
      pinyin: "cān jiā",
      english: "Participate",
    },
    {
      traditional: "婚禮",
      simplified: "婚礼",
      pinyin: "hūn lǐ",
      english: "Wedding",
    },
    {
      traditional: "西裝",
      simplified: "西装",
      pinyin: "xī zhuāng",
      english: "Suit",
    },
    {
      traditional: "正式",
      simplified: "正式",
      pinyin: "zhèng shì",
      english: "Formal",
    },
    {
      traditional: "客人",
      simplified: "客人",
      pinyin: "kè rén",
      english: "The guests",
    },
    {
      traditional: "手",
      simplified: "手",
      pinyin: "shǒu",
      english: "Hand",
    },
    {
      traditional: "照相機",
      simplified: "照相机",
      pinyin: "zhào xiàng jī",
      english: "Camera",
    },
    {
      traditional: "新郎",
      simplified: "新郎",
      pinyin: "xīn láng",
      english: "Bridegroom",
    },
    {
      traditional: "站",
      simplified: "站",
      pinyin: "zhàn",
      english: "Station",
    },
    {
      traditional: "白",
      simplified: "白",
      pinyin: "bái",
      english: "White",
    },
    {
      traditional: "帥",
      simplified: "帅",
      pinyin: "shuài",
      english: "Handsome",
    },
    {
      traditional: "禮服",
      simplified: "礼服",
      pinyin: "lǐ fú",
      english: "Dress",
    },
    {
      traditional: "座位",
      simplified: "座位",
      pinyin: "zuò wèi",
      english: "Seat",
    },
    {
      traditional: "看起來",
      simplified: "看起来",
      pinyin: "kàn qǐ lái",
      english: "It looks like",
    },
    {
      traditional: "結婚",
      simplified: "结婚",
      pinyin: "jié hūn",
      english: "Marry",
    },
    {
      traditional: "日子",
      simplified: "日子",
      pinyin: "rì zi",
      english: "Day",
    },
    {
      traditional: "親戚",
      simplified: "亲戚",
      pinyin: "qīn qī",
      english: "Relative",
    },
    {
      traditional: "熱鬧",
      simplified: "热闹",
      pinyin: "rè nào",
      english: "Lively",
    },
    {
      traditional: "慶祝",
      simplified: "庆祝",
      pinyin: "qìng zhù",
      english: "Celebrate",
    },
    {
      traditional: "件",
      simplified: "件",
      pinyin: "jiàn",
      english: "Pieces",
    },
    {
      traditional: "喜事",
      simplified: "喜事",
      pinyin: "xǐ shì",
      english: "Happy event",
    },
    {
      traditional: "請客",
      simplified: "请客",
      pinyin: "qǐng kè",
      english: "Dinner",
    },
    {
      traditional: "紅包",
      simplified: "红包",
      pinyin: "hóng bāo",
      english: "Red envelope",
    },
    {
      traditional: "送",
      simplified: "送",
      pinyin: "sòng",
      english: "Give away",
    },
    {
      traditional: "新人",
      simplified: "新人",
      pinyin: "xīn rén",
      english: "Newcomer",
    },
    {
      traditional: "喜宴",
      simplified: "喜宴",
      pinyin: "xǐ yàn",
      english: "Wedding banquet",
    },
    {
      traditional: "敬酒",
      simplified: "敬酒",
      pinyin: "jìng jiǔ",
      english: "Toast",
    },
    {
      traditional: "大人",
      simplified: "大人",
      pinyin: "dà rén",
      english: "Grown ups",
    },
    {
      traditional: "小孩",
      simplified: "小孩",
      pinyin: "xiǎo hái",
      english: "Child",
    },
    {
      traditional: "不得了",
      simplified: "不得了",
      pinyin: "bù dé le",
      english: "Terrible",
    },
    {
      traditional: "另外",
      simplified: "另外",
      pinyin: "lìng wài",
      english: "In addition",
    },
    {
      traditional: "糖",
      simplified: "糖",
      pinyin: "táng",
      english: "Sugar",
    },
    {
      traditional: "離開",
      simplified: "离开",
      pinyin: "lí kāi",
      english: "Go away",
    },
    {
      traditional: "句",
      simplified: "句",
      pinyin: "jù",
      english: "Sentence",
    },
    {
      traditional: "祝福",
      simplified: "祝福",
      pinyin: "zhù fú",
      english: "Blessing",
    },
    {
      traditional: "話",
      simplified: "话",
      pinyin: "huà",
      english: "Words",
    },
    {
      traditional: "一會兒",
      simplified: "一会儿",
      pinyin: "yī huì ér",
      english: "A while",
    },
    {
      traditional: "有說有笑",
      simplified: "有说有笑",
      pinyin: "yǒu shuō yǒu xiào",
      english: "Talking and laughing",
    },
    {
      traditional: "有吃有喝",
      simplified: "有吃有喝",
      pinyin: "yǒu chī yǒu hē",
      english: "Eat and drink",
    },
    {
      traditional: "百年好合",
      simplified: "百年好合",
      pinyin: "bǎi nián hǎo hé",
      english: "A hundred years of good cooperation",
    },
    {
      traditional: "早生貴子",
      simplified: "早生贵子",
      pinyin: "zǎo shēng guì zi",
      english: "Early birth of takako",
    },
  ],
};

export default lesson;
