import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "aslkieu7sn",
  type: "Contemporary Chinese",
  locked: false,
  title: "Book 2 Lesson 4",
  content: [
    {
      traditional: "高美玲",
      simplified: "高美玲",
      pinyin: "gāo měi líng",
      english: "Gao meiling",
    },
    {
      traditional: "打工",
      simplified: "打工",
      pinyin: "dǎ gōng",
      english: "Part-time job",
    },
    {
      traditional: "主任",
      simplified: "主任",
      pinyin: "zhǔ rèn",
      english: "Director",
    },
    {
      traditional: "介紹",
      simplified: "介绍",
      pinyin: "jiè shào",
      english: "Introduction",
    },
    {
      traditional: "歲",
      simplified: "岁",
      pinyin: "suì",
      english: "Year old",
    },
    {
      traditional: "語言學",
      simplified: "语言学",
      pinyin: "yǔ yán xué",
      english: "Linguistics",
    },
    {
      traditional: "經驗",
      simplified: "经验",
      pinyin: "jīng yàn",
      english: "Experience",
    },
    {
      traditional: "談",
      simplified: "谈",
      pinyin: "tán",
      english: "Talk",
    },
    {
      traditional: "當",
      simplified: "当",
      pinyin: "dāng",
      english: "When",
    },
    {
      traditional: "助教",
      simplified: "助教",
      pinyin: "zhù jiào",
      english: "Teaching assistant",
    },
    {
      traditional: "上午",
      simplified: "上午",
      pinyin: "shàng wǔ",
      english: "Morning",
    },
    {
      traditional: "除了",
      simplified: "除了",
      pinyin: "chú le",
      english: "Apart from",
    },
    {
      traditional: "年級",
      simplified: "年级",
      pinyin: "nián jí",
      english: "Grade",
    },
    {
      traditional: "暑假",
      simplified: "暑假",
      pinyin: "shǔ jià",
      english: "Summer vacation",
    },
    {
      traditional: "請教",
      simplified: "请教",
      pinyin: "qǐng jiào",
      english: "Consult",
    },
    {
      traditional: "貴",
      simplified: "贵",
      pinyin: "guì",
      english: "Expensive",
    },
    {
      traditional: "薪水",
      simplified: "薪水",
      pinyin: "xīn shuǐ",
      english: "Salary",
    },
    {
      traditional: "算",
      simplified: "算",
      pinyin: "suàn",
      english: "Calculate",
    },
    {
      traditional: "按照",
      simplified: "按照",
      pinyin: "àn zhào",
      english: "According to",
    },
    {
      traditional: "教授",
      simplified: "教授",
      pinyin: "jiào shòu",
      english: "Professor",
    },
    {
      traditional: "鐘點費",
      simplified: "钟点费",
      pinyin: "zhōng diǎn fèi",
      english: "Hourly fee",
    },
    {
      traditional: "份",
      simplified: "份",
      pinyin: "fèn",
      english: "Share",
    },
    {
      traditional: "法文",
      simplified: "法文",
      pinyin: "fǎ wén",
      english: "French",
    },
    {
      traditional: "亞洲",
      simplified: "亚洲",
      pinyin: "yà zhōu",
      english: "Asia",
    },
    {
      traditional: "西班牙語",
      simplified: "西班牙语",
      pinyin: "xī bān yá yǔ",
      english: "Spanish",
    },
    {
      traditional: "英文",
      simplified: "英文",
      pinyin: "yīng wén",
      english: "English",
    },
    {
      traditional: "三年級",
      simplified: "三年级",
      pinyin: "sān nián jí",
      english: "Third grade",
    },
    {
      traditional: "法律",
      simplified: "法律",
      pinyin: "fǎ lǜ",
      english: "Legal",
    },
    {
      traditional: "夠",
      simplified: "够",
      pinyin: "gòu",
      english: "Enough",
    },
    {
      traditional: "履歷表",
      simplified: "履历表",
      pinyin: "lǚ lì biǎo",
      english: "Resume",
    },
    {
      traditional: "面談",
      simplified: "面谈",
      pinyin: "miàn tán",
      english: "Interview",
    },
    {
      traditional: "華僑",
      simplified: "华侨",
      pinyin: "huá qiáo",
      english: "Overseas chinese",
    },
    {
      traditional: "辦公室",
      simplified: "办公室",
      pinyin: "bàn gōng shì",
      english: "Office",
    },
    {
      traditional: "談話",
      simplified: "谈话",
      pinyin: "tán huà",
      english: "Conversation",
    },
    {
      traditional: "情形",
      simplified: "情形",
      pinyin: "qíng xíng",
      english: "Situation",
    },
    {
      traditional: "適合",
      simplified: "适合",
      pinyin: "shì hé",
      english: "Suitable for",
    },
    {
      traditional: "說明",
      simplified: "说明",
      pinyin: "shuō míng",
      english: "Description",
    },
    {
      traditional: "然後",
      simplified: "然后",
      pinyin: "rán hòu",
      english: "Then",
    },
    {
      traditional: "月底",
      simplified: "月底",
      pinyin: "yuè dǐ",
      english: "End of month",
    },
    {
      traditional: "發",
      simplified: "发",
      pinyin: "fā",
      english: "Hair",
    },
    {
      traditional: "馬上",
      simplified: "马上",
      pinyin: "mǎ shàng",
      english: "Immediately",
    },
    {
      traditional: "答應",
      simplified: "答应",
      pinyin: "dá yīng",
      english: "Promise",
    },
    {
      traditional: "順利",
      simplified: "顺利",
      pinyin: "shùn lì",
      english: "Smoothly",
    },
    {
      traditional: "黃",
      simplified: "黄",
      pinyin: "huáng",
      english: "Yellow",
    },
    {
      traditional: "沒想到",
      simplified: "没想到",
      pinyin: "méi xiǎng dào",
      english: "Did not expect",
    },
  ],
};

export default lesson;
