import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "a8s7suaytQ",
  type: "Contemporary Chinese",
  locked: false,
  title: "Book 2 Lesson 2",
  content: [
    {
      traditional: "還是",
      simplified: "还是",
      pinyin: "hái shì",
      english: "Still is",
    },
    {
      traditional: "早",
      simplified: "早",
      pinyin: "zǎo",
      english: "Early",
    },
    {
      traditional: "約",
      simplified: "约",
      pinyin: "yuē",
      english: "Approximately",
    },
    {
      traditional: "對面",
      simplified: "对面",
      pinyin: "duì miàn",
      english: "Opposite",
    },
    {
      traditional: "直接",
      simplified: "直接",
      pinyin: "zhí jiē",
      english: "Direct",
    },
    {
      traditional: "不必",
      simplified: "不必",
      pinyin: "bù bì",
      english: "Don't have to",
    },
    {
      traditional: "換",
      simplified: "换",
      pinyin: "huàn",
      english: "Change",
    },
    {
      traditional: "車站",
      simplified: "车站",
      pinyin: "chē zhàn",
      english: "Station",
    },
    {
      traditional: "麻煩",
      simplified: "麻烦",
      pinyin: "má fán",
      english: "Trouble",
    },
    {
      traditional: "趕快",
      simplified: "赶快",
      pinyin: "gǎn kuài",
      english: "Hurry up",
    },
    {
      traditional: "班次",
      simplified: "班次",
      pinyin: "bān cì",
      english: "Shift",
    },
    {
      traditional: "禮拜",
      simplified: "礼拜",
      pinyin: "lǐ bài",
      english: "Worship",
    },
    {
      traditional: "見",
      simplified: "见",
      pinyin: "jiàn",
      english: "See",
    },
    {
      traditional: "電腦展",
      simplified: "电脑展",
      pinyin: "diàn nǎo zhǎn",
      english: "Computer show",
    },
    {
      traditional: "世貿展覽館",
      simplified: "世贸展览馆",
      pinyin: "shì mào zhǎn lǎn guǎn",
      english: "World trade exhibition hall",
    },
    {
      traditional: "二號線",
      simplified: "二号线",
      pinyin: "èr hào xiàn",
      english: "Line 2",
    },
    {
      traditional: "別急",
      simplified: "别急",
      pinyin: "bié jí",
      english: "Don't worry",
    },
    {
      traditional: "飛機",
      simplified: "飞机",
      pinyin: "fēi jī",
      english: "Aircraft",
    },
    {
      traditional: "轉機",
      simplified: "转机",
      pinyin: "zhuǎn jī",
      english: "Turnaround",
    },
    {
      traditional: "機場",
      simplified: "机场",
      pinyin: "jī chǎng",
      english: "Airport",
    },
    {
      traditional: "巴士",
      simplified: "巴士",
      pinyin: "bā shì",
      english: "Bus",
    },
    {
      traditional: "市區",
      simplified: "市区",
      pinyin: "shì qū",
      english: "Urban area",
    },
    {
      traditional: "下",
      simplified: "下",
      pinyin: "xià",
      english: "Under",
    },
    {
      traditional: "交通",
      simplified: "交通",
      pinyin: "jiāo tōng",
      english: "Traffic",
    },
    {
      traditional: "便利",
      simplified: "便利",
      pinyin: "biàn lì",
      english: "Convenient",
    },
    {
      traditional: "到處",
      simplified: "到处",
      pinyin: "dào chù",
      english: "Everywhere",
    },
    {
      traditional: "路線",
      simplified: "路线",
      pinyin: "lù xiàn",
      english: "Route",
    },
    {
      traditional: "複雜",
      simplified: "复杂",
      pinyin: "fù zá",
      english: "Complex",
    },
    {
      traditional: "輕鬆",
      simplified: "轻松",
      pinyin: "qīng sōng",
      english: "Easy",
    },
    {
      traditional: "東部",
      simplified: "东部",
      pinyin: "dōng bù",
      english: "East",
    },
    {
      traditional: "海邊",
      simplified: "海边",
      pinyin: "hǎi biān",
      english: "Seaside",
    },
    {
      traditional: "島",
      simplified: "岛",
      pinyin: "dǎo",
      english: "Island",
    },
    {
      traditional: "搭",
      simplified: "搭",
      pinyin: "dā",
      english: "Take",
    },
    {
      traditional: "船",
      simplified: "船",
      pinyin: "chuán",
      english: "Ferry",
    },
    {
      traditional: "地",
      simplified: "地",
      pinyin: "dì",
      english: "Ground",
    },
    {
      traditional: "法國",
      simplified: "法国",
      pinyin: "fǎ guó",
      english: "France",
    },
    {
      traditional: "歐洲",
      simplified: "欧洲",
      pinyin: "ōu zhōu",
      english: "Europe",
    },
    {
      traditional: "悠遊卡",
      simplified: "悠游卡",
      pinyin: "yōu yóu kǎ",
      english: "Leisure card",
    },
    {
      traditional: "綠島",
      simplified: "绿岛",
      pinyin: "lǜ dǎo",
      english: "Green island",
    },
    {
      traditional: "東南邊",
      simplified: "东南边",
      pinyin: "dōng nán biān",
      english: "Southeast",
    },
  ],
};

export default lesson;
