import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "xyB2jhUO3",
  type: "Contemporary Chinese",
  list: "11",
  locked: false,
  title: "Lesson 9",
  content: [
    {
      simplified: "星期",
      traditional: "星期",
      pinyin: "xīng qī",
      english: "Week",
    },
    {
      simplified: "回国",
      traditional: "回國",
      pinyin: "huí guó",
      english: "Return home",
    },
    {
      simplified: "打算",
      traditional: "打算",
      pinyin: "dǎ suàn",
      english: "Plan, intend",
    },
    {
      simplified: "电视",
      traditional: "電視",
      pinyin: "diàn shì",
      english: "Tv",
    },
    {
      simplified: "影片",
      traditional: "影片",
      pinyin: "yǐng piàn",
      english: "Film",
    },
    {
      simplified: "旅行",
      traditional: "旅行",
      pinyin: "lǚ xíng",
      english: "Travel",
    },
    {
      simplified: "功课",
      traditional: "功課",
      pinyin: "gōng kè",
      english: "Homework",
    },
    {
      simplified: "出去",
      traditional: "出去",
      pinyin: "chū qù",
      english: "Go out",
    },
    {
      simplified: "大概",
      traditional: "大概",
      pinyin: "dà gài",
      english: "Probably",
    },
    {
      simplified: "放假",
      traditional: "放假",
      pinyin: "fàng jià",
      english: "Holiday",
    },
    {
      simplified: "下个星期",
      traditional: "下個星期",
      pinyin: "xià gè xīng qī",
      english: "Next week",
    },
    {
      simplified: "有时候",
      traditional: "有時候",
      pinyin: "yǒu shí hou",
      english: "Sometimes",
    },
    {
      simplified: "多久",
      traditional: "多久",
      pinyin: "duō jiǔ",
      english: "How long",
    },
    {
      simplified: "台东",
      traditional: "臺東",
      pinyin: "tái dōng",
      english: "Taitung",
    },
    {
      simplified: "女",
      traditional: "女",
      pinyin: "nǚ",
      english: "Female",
    },
    {
      simplified: "月",
      traditional: "月",
      pinyin: "yuè",
      english: "Month",
    },
    {
      simplified: "号",
      traditional: "號",
      pinyin: "háo",
      english: "Number",
    },
    {
      simplified: "带",
      traditional: "帶",
      pinyin: "dài",
      english: "Band",
    },
    {
      simplified: "她",
      traditional: "她",
      pinyin: "tā",
      english: "She",
    },
    {
      simplified: "还",
      traditional: "還",
      pinyin: "hái",
      english: "Also",
    },
    {
      simplified: "建议",
      traditional: "建議",
      pinyin: "jiàn yì",
      english: "Suggest",
    },
    {
      simplified: "夜市",
      traditional: "夜市",
      pinyin: "yè shì",
      english: "Night market",
    },
    {
      simplified: "应该",
      traditional: "應該",
      pinyin: "yīng gāi",
      english: "Should",
    },
    {
      simplified: "逛",
      traditional: "逛",
      pinyin: "guàng",
      english: "Wander around",
    },
    {
      simplified: "特别",
      traditional: "特別",
      pinyin: "tè bié",
      english: "Special",
    },
    {
      simplified: "茶馆",
      traditional: "茶館",
      pinyin: "chá guǎn",
      english: "Teahouse",
    },
    {
      simplified: "决定",
      traditional: "決定",
      pinyin: "jué dìng",
      english: "Decide",
    },
    {
      simplified: "要是",
      traditional: "要是",
      pinyin: "yào shi",
      english: "If",
    },
    {
      simplified: "就",
      traditional: "就",
      pinyin: "jiù",
      english: "Then",
    },
  ],
};

export default lesson;
