import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "fKauffjus6",
  type: "Contemporary Chinese",
  locked: false,
  title: "Lesson 14",
  content: [
    {
      traditional: "天氣",
      simplified: "天气",
      pinyin: "tiān qì",
      english: "The weather",
    },
    {
      traditional: "冷",
      simplified: "冷",
      pinyin: "lěng",
      english: "Cold",
    },
    {
      traditional: "風",
      simplified: "风",
      pinyin: "fēng",
      english: "Wind",
    },
    {
      traditional: "滑雪",
      simplified: "滑雪",
      pinyin: "huá xuě",
      english: "Ski",
    },
    {
      traditional: "春天",
      simplified: "春天",
      pinyin: "chūn tiān",
      english: "Spring",
    },
    {
      traditional: "想",
      simplified: "想",
      pinyin: "xiǎng",
      english: "Miss you",
    },
    {
      traditional: "新年",
      simplified: "新年",
      pinyin: "xīn nián",
      english: "New year",
    },
    {
      traditional: "快",
      simplified: "快",
      pinyin: "kuài",
      english: "Fast",
    },
    {
      traditional: "父母",
      simplified: "父母",
      pinyin: "fù mǔ",
      english: "Parents",
    },
    {
      traditional: "冬天",
      simplified: "冬天",
      pinyin: "dōng tiān",
      english: "Winter",
    },
    {
      traditional: "明年",
      simplified: "明年",
      pinyin: "míng nián",
      english: "Next year",
    },
    {
      traditional: "秋天",
      simplified: "秋天",
      pinyin: "qiū tiān",
      english: "Fall",
    },
    {
      traditional: "紅葉",
      simplified: "红叶",
      pinyin: "hóng yè",
      english: "Red leaves",
    },
    {
      traditional: "只",
      simplified: "只",
      pinyin: "zhǐ",
      english: "Only",
    },
    {
      traditional: "玉山",
      simplified: "玉山",
      pinyin: "yù shān",
      english: "Yushan",
    },
    {
      traditional: "紐約",
      simplified: "纽约",
      pinyin: "niǔ yuē",
      english: "New york",
    },
    {
      traditional: "下雪",
      simplified: "下雪",
      pinyin: "xià xuě",
      english: "Snowing",
    },
    {
      traditional: "十二月底",
      simplified: "十二月底",
      pinyin: "shí èr yuè dǐ",
      english: "End of december",
    },
    {
      traditional: "雨",
      simplified: "雨",
      pinyin: "yǔ",
      english: "Rain",
    },
    {
      traditional: "傘",
      simplified: "伞",
      pinyin: "sǎn",
      english: "Umbrella",
    },
    {
      traditional: "颱風",
      simplified: "台风",
      pinyin: "tái fēng",
      english: "Typhoon",
    },
    {
      traditional: "要",
      simplified: "要",
      pinyin: "yào",
      english: "Want",
    },
    {
      traditional: "夏天",
      simplified: "夏天",
      pinyin: "xià tiān",
      english: "Summer",
    },
    {
      traditional: "濕",
      simplified: "湿",
      pinyin: "shī",
      english: "Wet",
    },
    {
      traditional: "討厭",
      simplified: "讨厌",
      pinyin: "tǎo yàn",
      english: "Hate",
    },
    {
      traditional: "新聞",
      simplified: "新闻",
      pinyin: "xīn wén",
      english: "News",
    },
    {
      traditional: "更",
      simplified: "更",
      pinyin: "gèng",
      english: "More",
    },
    {
      traditional: "大家",
      simplified: "大家",
      pinyin: "dà jiā",
      english: "Everyone",
    },
    {
      traditional: "小心",
      simplified: "小心",
      pinyin: "xiǎo xīn",
      english: "Be careful",
    },
    {
      traditional: "可怕",
      simplified: "可怕",
      pinyin: "kě pà",
      english: "Terrible",
    },
    {
      traditional: "停",
      simplified: "停",
      pinyin: "tíng",
      english: "Stop",
    },
    {
      traditional: "下雨",
      simplified: "下雨",
      pinyin: "xià yǔ",
      english: "Rain",
    },
    {
      traditional: "這次",
      simplified: "这次",
      pinyin: "zhè cì",
      english: "This time",
    },
    {
      traditional: "上次",
      simplified: "上次",
      pinyin: "shàng cì",
      english: "Last time",
    },
    {
      traditional: "慢走",
      simplified: "慢走",
      pinyin: "màn zǒu",
      english: "Walk slowly",
    },
  ],
};

export default lesson;
