import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "CbbMYmOGz",
  type: "Contemporary Chinese",
  list: "8",
  locked: false,
  title: "Book 1 Vocabulary",
  content: [
    {
      simplified: "你",
      traditional: "你",
      pinyin: "nǐ",
      english: "You",
    },
    {
      simplified: "来",
      traditional: "來",
      pinyin: "lái",
      english: "Come",
    },
    {
      simplified: "小姐",
      traditional: "小姐",
      pinyin: "xiǎo jie",
      english: "Miss",
    },
    {
      simplified: "吗",
      traditional: "嗎",
      pinyin: "mǎ",
      english: "?",
    },
    {
      simplified: "接",
      traditional: "接",
      pinyin: "jiē",
      english: "Pick up",
    },
    {
      simplified: "我",
      traditional: "我",
      pinyin: "wǒ",
      english: "I",
    },
    {
      simplified: "我们",
      traditional: "我們",
      pinyin: "wǒ men",
      english: "We",
    },
    {
      simplified: "先生",
      traditional: "先生",
      pinyin: "xiān sheng",
      english: "Mr",
    },
    {
      simplified: "好",
      traditional: "好",
      pinyin: "hǎo",
      english: "It is good",
    },
    {
      simplified: "姓",
      traditional: "姓",
      pinyin: "xìng",
      english: "Surname",
    },
    {
      simplified: "叫",
      traditional: "叫",
      pinyin: "jiào",
      english: "Call",
    },
    {
      simplified: "你们",
      traditional: "你們",
      pinyin: "nǐ men",
      english: "You guys",
    },
    {
      simplified: "台湾",
      traditional: "台灣",
      pinyin: "tái wān",
      english: "Taiwan",
    },
    {
      simplified: "欢迎",
      traditional: "歡迎",
      pinyin: "huān yíng",
      english: "Welcome",
    },
    {
      simplified: "请问",
      traditional: "請問",
      pinyin: "qǐng wèn",
      english: "Excuse me",
    },
    {
      simplified: "是的",
      traditional: "是的",
      pinyin: "shì de",
      english: "Yes",
    },
    {
      simplified: "谢谢",
      traditional: "謝謝",
      pinyin: "xiè xie",
      english: "Thank you",
    },
    {
      simplified: "不客气",
      traditional: "不客氣",
      pinyin: "bù kè qi",
      english: "You're welcome",
    },
    {
      simplified: "你好",
      traditional: "你好",
      pinyin: "nǐ hǎo",
      english: "Hello there",
    },
    {
      simplified: "请",
      traditional: "請",
      pinyin: "qǐng",
      english: "Please",
    },
    {
      simplified: "喝",
      traditional: "喝",
      pinyin: "hē",
      english: "Drink",
    },
    {
      simplified: "茶",
      traditional: "茶",
      pinyin: "chá",
      english: "Tea",
    },
    {
      simplified: "很",
      traditional: "很",
      pinyin: "hěn",
      english: "Very",
    },
    {
      simplified: "好喝",
      traditional: "好喝",
      pinyin: "hǎo hē",
      english: "Delicious",
    },
    {
      simplified: "什么",
      traditional: "什麼",
      pinyin: "shén me",
      english: "What",
    },
    {
      simplified: "人",
      traditional: "人",
      pinyin: "rén",
      english: "People",
    },
    {
      simplified: "喜欢",
      traditional: "喜歡",
      pinyin: "xǐ huan",
      english: "Like",
    },
    {
      simplified: "呢",
      traditional: "呢",
      pinyin: "ne",
      english: "What",
    },
    {
      simplified: "他",
      traditional: "他",
      pinyin: "tā",
      english: "He",
    },
    {
      simplified: "不",
      traditional: "不",
      pinyin: "bù",
      english: "Do not",
    },
    {
      simplified: "哪",
      traditional: "哪",
      pinyin: "nǎ",
      english: "Where",
    },
    {
      simplified: "要",
      traditional: "要",
      pinyin: "yāo",
      english: "Want",
    },
    {
      simplified: "咖啡",
      traditional: "咖啡",
      pinyin: "kā fēi",
      english: "Coffee",
    },
    {
      simplified: "乌龙茶",
      traditional: "烏龍茶",
      pinyin: "wū lóng chá",
      english: "Oolong tea",
    },
    {
      simplified: "日本",
      traditional: "日本",
      pinyin: "rì běn",
      english: "Japan",
    },
    {
      simplified: "美国",
      traditional: "美國",
      pinyin: "měi guó",
      english: "United states",
    },
    {
      simplified: "对不起",
      traditional: "對不起",
      pinyin: "duì bu qǐ",
      english: "Sorry",
    },
    {
      simplified: "哪国",
      traditional: "哪國",
      pinyin: "nǎ",
      english: "Which country",
    },
    {
      simplified: "的",
      traditional: "的",
      pinyin: "de",
      english: "Of",
    },
    {
      simplified: "家人",
      traditional: "家人",
      pinyin: "jiā rén",
      english: "Family",
    },
    {
      simplified: "家",
      traditional: "家",
      pinyin: "jiā",
      english: "Family",
    },
    {
      simplified: "漂亮",
      traditional: "漂亮",
      pinyin: "piào liang",
      english: "Pretty",
    },
    {
      simplified: "房子",
      traditional: "房子",
      pinyin: "fáng zi",
      english: "House",
    },
    {
      simplified: "坐",
      traditional: "坐",
      pinyin: "zuò",
      english: "Sit",
    },
    {
      simplified: "有",
      traditional: "有",
      pinyin: "yǒu",
      english: "Have",
    },
    {
      simplified: "多",
      traditional: "多",
      pinyin: "duō",
      english: "Many",
    },
    {
      simplified: "照片",
      traditional: "照片",
      pinyin: "zhào piàn",
      english: "Photo",
    },
    {
      simplified: "都",
      traditional: "都",
      pinyin: "dū",
      english: "All",
    },
    {
      simplified: "照相",
      traditional: "照相",
      pinyin: "zhào xiàng",
      english: "Take pictures",
    },
    {
      simplified: "张",
      traditional: "張",
      pinyin: "zhāng",
      english: "Zhang",
    },
    {
      simplified: "好看",
      traditional: "好看",
      pinyin: "hǎo kàn",
      english: "Good looking",
    },
    {
      simplified: "谁",
      traditional: "誰",
      pinyin: "shéi",
      english: "Who",
    },
    {
      simplified: "姐姐",
      traditional: "姐姐",
      pinyin: "jiě jie",
      english: "Sister",
    },
    {
      simplified: "妹妹",
      traditional: "妹妹",
      pinyin: "mèi mei",
      english: "Younger sister",
    },
    {
      simplified: "爸爸",
      traditional: "爸爸",
      pinyin: "bà ba",
      english: "Father",
    },
    {
      simplified: "妈妈",
      traditional: "媽媽",
      pinyin: "mā ma",
      english: "Mom",
    },
    {
      simplified: "请进",
      traditional: "請進",
      pinyin: "qǐng jìn",
      english: "Come in",
    },
    {
      simplified: "伯母",
      traditional: "伯母",
      pinyin: "bó mǔ",
      english: "Aunt",
    },
    {
      simplified: "您",
      traditional: "您",
      pinyin: "nín",
      english: "You",
    },
    {
      simplified: "名字",
      traditional: "名字",
      pinyin: "míng zi",
      english: "First name",
    },
    {
      simplified: "书",
      traditional: "書",
      pinyin: "shū",
      english: "Book",
    },
    {
      simplified: "哥哥",
      traditional: "哥哥",
      pinyin: "gē ge",
      english: "Brother",
    },
    {
      simplified: "老师",
      traditional: "老師",
      pinyin: "lǎo shī",
      english: "Teacher",
    },
    {
      simplified: "看书",
      traditional: "看書",
      pinyin: "kàn shū",
      english: "Read a book",
    },
    {
      simplified: "几",
      traditional: "幾",
      pinyin: "jī",
      english: "A few",
    },
    {
      simplified: "个",
      traditional: "個",
      pinyin: "gè",
      english: "Each",
    },
    {
      simplified: "没",
      traditional: "沒",
      pinyin: "méi",
      english: "No",
    },
    {
      simplified: "兄弟",
      traditional: "兄弟",
      pinyin: "xiōng dì",
      english: "Brothers",
    },
    {
      simplified: "姐妹",
      traditional: "姐妹",
      pinyin: "jiě mèi",
      english: "Sisters",
    },
    {
      simplified: "五",
      traditional: "五",
      pinyin: "wǔ",
      english: "Five",
    },
    {
      simplified: "两",
      traditional: "兩",
      pinyin: "liǎng",
      english: "Two",
    },
    {
      simplified: "周末",
      traditional: "週末",
      pinyin: "zhōu mò",
      english: "Weekend",
    },
    {
      simplified: "听",
      traditional: "聽",
      pinyin: "tīng",
      english: "Listen",
    },
    {
      simplified: "音乐",
      traditional: "音樂",
      pinyin: "yīn yuè",
      english: "Music",
    },
    {
      simplified: "运动",
      traditional: "運動",
      pinyin: "yùn dòng",
      english: "Motion",
    },
    {
      simplified: "打",
      traditional: "打",
      pinyin: "dá",
      english: "Hit",
    },
    {
      simplified: "和",
      traditional: "和",
      pinyin: "hé",
      english: "With",
    },
    {
      simplified: "常",
      traditional: "常",
      pinyin: "cháng",
      english: "Often",
    },
    {
      simplified: "也",
      traditional: "也",
      pinyin: "yě",
      english: "And also",
    },
    {
      simplified: "踢",
      traditional: "踢",
      pinyin: "tī",
      english: "Kick",
    },
    {
      simplified: "觉得",
      traditional: "覺得",
      pinyin: "jué de",
      english: "Feel",
    },
    {
      simplified: "好玩",
      traditional: "好玩",
      pinyin: "hǎo wán",
      english: "Fun",
    },
    {
      simplified: "明天",
      traditional: "明天",
      pinyin: "míng tiān",
      english: "Tomorrow",
    },
    {
      simplified: "早上",
      traditional: "早上",
      pinyin: "zǎo shang",
      english: "Morning",
    },
    {
      simplified: "去",
      traditional: "去",
      pinyin: "qù",
      english: "Go with",
    },
    {
      simplified: "怎么样",
      traditional: "怎麼樣",
      pinyin: "zěn me yàng",
      english: "How about it",
    },
    {
      simplified: "啊",
      traditional: "啊",
      pinyin: "ā",
      english: "What",
    },
    {
      simplified: "做什么",
      traditional: "做什麼",
      pinyin: "zuò shén me",
      english: "Doing what",
    },
    {
      simplified: "好啊",
      traditional: "好啊",
      pinyin: "hǎo",
      english: "Alright",
    },
    {
      simplified: "今天",
      traditional: "今天",
      pinyin: "jīn tiān",
      english: "Nowadays",
    },
    {
      simplified: "晚上",
      traditional: "晚上",
      pinyin: "wǎn shang",
      english: "At night",
    },
    {
      simplified: "看",
      traditional: "看",
      pinyin: "kān",
      english: "Look",
    },
    {
      simplified: "电影",
      traditional: "電影",
      pinyin: "diàn yǐng",
      english: "The film",
    },
    {
      simplified: "妳",
      traditional: "妳",
      pinyin: "nǎi",
      english: "You (female)",
    },
    {
      simplified: "想",
      traditional: "想",
      pinyin: "xiǎng",
      english: "Miss you",
    },
    {
      simplified: "还是",
      traditional: "還是",
      pinyin: "hái shi",
      english: "Still is",
    },
    {
      simplified: "吧",
      traditional: "吧",
      pinyin: "bā",
      english: "Right",
    },
    {
      simplified: "可以",
      traditional: "可以",
      pinyin: "kě yǐ",
      english: "Can",
    },
    {
      simplified: "学",
      traditional: "學",
      pinyin: "xué",
      english: "Learn",
    },
    {
      simplified: "中文",
      traditional: "中文",
      pinyin: "zhōng wén",
      english: "Chinese",
    },
    {
      simplified: "一起",
      traditional: "一起",
      pinyin: "yī qǐ",
      english: "Together",
    },
    {
      simplified: "吃",
      traditional: "吃",
      pinyin: "chī",
      english: "Eat",
    },
    {
      simplified: "晚饭",
      traditional: "晚飯",
      pinyin: "wǎn fàn",
      english: "Dinner",
    },
    {
      simplified: "菜",
      traditional: "菜",
      pinyin: "cài",
      english: "Dish",
    },
    {
      simplified: "越南",
      traditional: "越南",
      pinyin: "yuè nán",
      english: "Vietnam",
    },
    {
      simplified: "网球",
      traditional: "網球",
      pinyin: "wǎng qiú",
      english: "Tennis",
    },
    {
      simplified: "棒球",
      traditional: "棒球",
      pinyin: "lánqiú",
      english: "Baseball",
    },
    {
      simplified: "篮球",
      traditional: "籃球",
      pinyin: "",
      english: "Basketball",
    },
    {
      simplified: "乒乓球",
      traditional: "乒乓球",
      pinyin: "pīng pāng qiú",
      english: "Pingpong",
    },
    {
      simplified: "排球",
      traditional: "排球",
      pinyin: "páiqiú",
      english: "Volleyball",
    },
    {
      simplified: "高尔夫球",
      traditional: "高爾夫球",
      pinyin: "gāo'ěrfū qiú",
      english: "Golf",
    },
    {
      simplified: "冰球",
      traditional: "冰球",
      pinyin: "bīng qiú",
      english: "Puck",
    },
    {
      simplified: "橄榄球",
      traditional: "橄欖球",
      pinyin: "gǎn lǎn qiú",
      english: "Football",
    },
    {
      simplified: "踢足球",
      traditional: "踢足球",
      pinyin: "tī zúqiú",
      english: "Play football",
    },
    {
      simplified: "游泳",
      traditional: "游泳",
      pinyin: "yóuyǒng",
      english: "Swim",
    },
    {
      simplified: "冲浪",
      traditional: "衝浪",
      pinyin: "chōnglàng",
      english: "Surf",
    },
    {
      simplified: "慢跑",
      traditional: "慢跑",
      pinyin: "màn pǎo",
      english: "Jogging",
    },
    {
      simplified: "做瑜伽",
      traditional: "做瑜伽",
      pinyin: "zuò yújiā",
      english: "Do yoga",
    },
    {
      simplified: "爬山",
      traditional: "爬山",
      pinyin: "páshān",
      english: "Mountain climbing",
    },
    {
      simplified: "骑马",
      traditional: "騎馬",
      pinyin: "qímǎ",
      english: "Horse riding",
    },
    {
      simplified: "骑脚踏车",
      traditional: "騎腳踏車",
      pinyin: "qí jiǎotàchē",
      english: "Cycling",
    },
    {
      simplified: "滑雪",
      traditional: "滑雪",
      pinyin: "huáxuě",
      english: "Ski",
    },
    {
      simplified: "溜滑板",
      traditional: "溜滑板",
      pinyin: "liū huábǎn",
      english: "Skateboarding",
    },
    {
      simplified: "溜冰",
      traditional: "溜冰",
      pinyin: "liūbīng",
      english: "Ice skating",
    },
    {
      simplified: "跳舞",
      traditional: "跳舞",
      pinyin: "tiàowǔ",
      english: "Dancing",
    },
    {
      simplified: "一共",
      traditional: "一共",
      pinyin: "yī gòng",
      english: "In total",
    },
    {
      simplified: "多少",
      traditional: "多少",
      pinyin: "duō shǎo",
      english: "How many",
    },
    {
      simplified: "钱",
      traditional: "錢",
      pinyin: "qián",
      english: "Money",
    },
    {
      simplified: "老板",
      traditional: "老闆",
      pinyin: "lǎo bǎn",
      english: "Boss",
    },
    {
      simplified: "买",
      traditional: "買",
      pinyin: "mǎi",
      english: "Buy",
    },
    {
      simplified: "杯",
      traditional: "杯",
      pinyin: "bēi",
      english: "Cup",
    },
    {
      simplified: "热",
      traditional: "熱",
      pinyin: "rè",
      english: "Hot",
    },
    {
      simplified: "包子",
      traditional: "包子",
      pinyin: "bāozi",
      english: "Steamed bun",
    },
    {
      simplified: "要",
      traditional: "要",
      pinyin: "yāo",
      english: "Want",
    },
    {
      simplified: "大",
      traditional: "大",
      pinyin: "dà",
      english: "Big",
    },
    {
      simplified: "中",
      traditional: "中",
      pinyin: "zhōng",
      english: "Center",
    },
    {
      simplified: "小",
      traditional: "小",
      pinyin: "xiǎo",
      english: "Small",
    },
    {
      simplified: "棒",
      traditional: "棒",
      pinyin: "bàng",
      english: "Stick",
    },
    {
      simplified: "微波",
      traditional: "微波",
      pinyin: "wēi bō",
      english: "Microwave",
    },
    {
      simplified: "百",
      traditional: "百",
      pinyin: "bǎi",
      english: "Hundred",
    },
    {
      simplified: "块",
      traditional: "塊",
      pinyin: "kuài",
      english: "Piece",
    },
    {
      simplified: "好的",
      traditional: "好的",
      pinyin: "hǎo",
      english: "Ok",
    },
    {
      simplified: "外带",
      traditional: "外帶",
      pinyin: "wài dài",
      english: "Takeaway",
    },
    {
      simplified: "内用",
      traditional: "內用",
      pinyin: "nèi yòng",
      english: "For here",
    },
    {
      simplified: "支",
      traditional: "支",
      pinyin: "zhī",
      english: "Support",
    },
    {
      simplified: "新",
      traditional: "新",
      pinyin: "xīn",
      english: "New",
    },
    {
      simplified: "手机",
      traditional: "手機",
      pinyin: "shǒu jī",
      english: "Cellphone",
    },
    {
      simplified: "太",
      traditional: "太",
      pinyin: "tài",
      english: "Too",
    },
    {
      simplified: "舊",
      traditional: "舊",
      pinyin: "jiù",
      english: "Old",
    },
    {
      simplified: "了",
      traditional: "了",
      pinyin: "liǎo",
      english: "Sentence final particle",
    },
    {
      simplified: "种",
      traditional: "種",
      pinyin: "zhǒng",
      english: "Kind/type",
    },
    {
      simplified: "能",
      traditional: "能",
      pinyin: "néng",
      english: "Can",
    },
    {
      simplified: "上网",
      traditional: "上網",
      pinyin: "shàng wǎng",
      english: "Surf wifi",
    },
    {
      simplified: "那",
      traditional: "那",
      pinyin: "nā",
      english: "That",
    },
    {
      simplified: "贵",
      traditional: "貴",
      pinyin: "guì",
      english: "Expensive",
    },
    {
      simplified: "卖",
      traditional: "賣",
      pinyin: "mài",
      english: "Sell",
    },
    {
      simplified: "便宜",
      traditional: "便宜",
      pinyin: "biàn yí",
      english: "Cheap",
    },
    {
      simplified: "万",
      traditional: "萬",
      pinyin: "wàn",
      english: "Million",
    },
    {
      simplified: "千",
      traditional: "千",
      pinyin: "qiān",
      english: "Thousand",
    },
    {
      simplified: "牛肉",
      traditional: "牛肉",
      pinyin: "niú ròu",
      english: "Beef",
    },
    {
      simplified: "面",
      traditional: "麵",
      pinyin: "miàn",
      english: "Noodle",
    },
    {
      simplified: "真",
      traditional: "真",
      pinyin: "zhēn",
      english: "True",
    },
    {
      simplified: "好吃",
      traditional: "好吃",
      pinyin: "hǎo chī",
      english: "Delicious",
    },
    {
      simplified: "说",
      traditional: "說",
      pinyin: "shuì",
      english: "Say",
    },
    {
      simplified: "少",
      traditional: "少",
      pinyin: "shǎo",
      english: "A few",
    },
    {
      simplified: "有名",
      traditional: "有名",
      pinyin: "yǒu míng",
      english: "Famous",
    },
    {
      simplified: "小吃",
      traditional: "小吃",
      pinyin: "xiǎo chī",
      english: "Snacks",
    },
    {
      simplified: "最",
      traditional: "最",
      pinyin: "zuì",
      english: "Most",
    },
    {
      simplified: "汤",
      traditional: "湯",
      pinyin: "tāng",
      english: "Soup",
    },
    {
      simplified: "这么",
      traditional: "這麼",
      pinyin: "zhè me",
      english: "So",
    },
    {
      simplified: "知道",
      traditional: "知道",
      pinyin: "zhī dào",
      english: "To know",
    },
    {
      simplified: "家",
      traditional: "家",
      pinyin: "jiā",
      english: "Family",
    },
    {
      simplified: "店",
      traditional: "店",
      pinyin: "diàn",
      english: "Shop/store",
    },
    {
      simplified: "一定",
      traditional: "一定",
      pinyin: "yī dìng",
      english: "Definitely",
    },
    {
      simplified: "点",
      traditional: "點",
      pinyin: "diǎn",
      english: "To order (meals)",
    },
    {
      simplified: "碗",
      traditional: "碗",
      pinyin: "wǎn",
      english: "A bowl of",
    },
    {
      simplified: "是啊",
      traditional: "是啊",
      pinyin: "shì ",
      english: "That's right",
    },
    {
      simplified: "小笼包",
      traditional: "小籠包",
      pinyin: "xiǎo lóng bāo",
      english: "Small bun",
    },
    {
      simplified: "臭豆腐",
      traditional: "臭豆腐",
      pinyin: "chòu dòu fu",
      english: "Stinky tofu",
    },
    {
      simplified: "太好了",
      traditional: "太好了",
      pinyin: "tài hǎo le",
      english: "Excellent",
    },
    {
      simplified: "昨天",
      traditional: "昨天",
      pinyin: "zuó tiān",
      english: "Yesterday",
    },
    {
      simplified: "餐厅",
      traditional: "餐廳",
      pinyin: "cān tīng",
      english: "Restaurant",
    },
    {
      simplified: "可是",
      traditional: "可是",
      pinyin: "kě shì",
      english: "But, however",
    },
    {
      simplified: "辣",
      traditional: "辣",
      pinyin: "là",
      english: "Spicy",
    },
    {
      simplified: "怕",
      traditional: "怕",
      pinyin: "pà",
      english: "Afraid",
    },
    {
      simplified: "所以",
      traditional: "所以",
      pinyin: "suǒ yǐ",
      english: "And so",
    },
    {
      simplified: "自己",
      traditional: "自己",
      pinyin: "zì jǐ",
      english: "Self",
    },
    {
      simplified: "做饭",
      traditional: "做飯",
      pinyin: "zuò fàn",
      english: "Cook",
    },
    {
      simplified: "得",
      traditional: "得",
      pinyin: "dé",
      english: "Complement marker",
    },
    {
      simplified: "会",
      traditional: "會",
      pinyin: "huì",
      english: "To be able to, can",
    },
    {
      simplified: "甜点",
      traditional: "甜點",
      pinyin: "tián diǎn",
      english: "Dessert",
    },
    {
      simplified: "不错",
      traditional: "不錯",
      pinyin: "bù cuò",
      english: "Not bad",
    },
    {
      simplified: "",
      traditional: "可以",
      pinyin: "kě yǐ",
      english: "Can",
    },
    {
      simplified: "教",
      traditional: "教",
      pinyin: "jiào",
      english: "Teach",
    },
    {
      simplified: "到",
      traditional: "到",
      pinyin: "dào",
      english: "To",
    },
    {
      simplified: "有一点",
      traditional: "有一點",
      pinyin: "yǒu yī diǎn",
      english: "A little",
    },
    {
      simplified: "不好",
      traditional: "不好",
      pinyin: "bù hǎo",
      english: "Not good",
    },
    {
      simplified: "他们",
      traditional: "他們",
      pinyin: "tā men",
      english: "They",
    },
    {
      simplified: "学校",
      traditional: "學校",
      pinyin: "xuéxiào",
      english: "School",
    },
    {
      simplified: "在",
      traditional: "在",
      pinyin: "zài",
      english: "In",
    },
    {
      simplified: "山上",
      traditional: "山上",
      pinyin: "shān shàng",
      english: "On the mountain",
    },
    {
      simplified: "哪里",
      traditional: "哪裡",
      pinyin: "nǎlǐ",
      english: "Where",
    },
    {
      simplified: "远",
      traditional: "遠",
      pinyin: "yuǎn",
      english: "Far",
    },
    {
      simplified: "那里",
      traditional: "那裡",
      pinyin: "nà li",
      english: "There",
    },
    {
      simplified: "风景",
      traditional: "風景",
      pinyin: "fēngjǐng",
      english: "Landscape",
    },
    {
      simplified: "美",
      traditional: "美",
      pinyin: "měi",
      english: "Nice",
    },
    {
      simplified: "前面",
      traditional: "前面",
      pinyin: "qián miàn",
      english: "Front",
    },
    {
      simplified: "海",
      traditional: "海",
      pinyin: "hǎi",
      english: "Sea",
    },
    {
      simplified: "后面",
      traditional: "後面",
      pinyin: "hòu miàn",
      english: "Behind",
    },
    {
      simplified: "山",
      traditional: "山",
      pinyin: "shān",
      english: "Mountain",
    },
    {
      simplified: "真的",
      traditional: "真的",
      pinyin: "zhēn de",
      english: "Really",
    },
    {
      simplified: "地方",
      traditional: "地方",
      pinyin: "dìfāng",
      english: "Local",
    },
    {
      simplified: "现在",
      traditional: "現在",
      pinyin: "xiànzài",
      english: "Just now",
    },
    {
      simplified: "附近",
      traditional: "附近",
      pinyin: "fù jìn",
      english: "Nearby",
    },
    {
      simplified: "楼下",
      traditional: "樓下",
      pinyin: "lóu xià",
      english: "Downstairs",
    },
    {
      simplified: "找",
      traditional: "找",
      pinyin: "zhǎo",
      english: "Find",
    },
    {
      simplified: "朋友",
      traditional: "朋友",
      pinyin: "péngyǒu",
      english: "Friend",
    },
    {
      simplified: "上课",
      traditional: "上課",
      pinyin: "shàngkè",
      english: "Class",
    },
    {
      simplified: "花莲",
      traditional: "花蓮",
      pinyin: "huā lián",
      english: "Hualien",
    },
    {
      simplified: "听说",
      traditional: "聽說",
      pinyin: "tīng shuō",
      english: "It is said that",
    },
    {
      simplified: "近",
      traditional: "近",
      pinyin: "jìn",
      english: "Near",
    },
    {
      simplified: "方便",
      traditional: "方便",
      pinyin: "fāngbiàn",
      english: "Convenience",
    },
    {
      simplified: "这里",
      traditional: "這裡",
      pinyin: "zhèlǐ",
      english: "Here",
    },
    {
      simplified: "学生",
      traditional: "學生",
      pinyin: "xué sheng",
      english: "Student",
    },
    {
      simplified: "东西",
      traditional: "東西",
      pinyin: "dōngxī",
      english: "Thing",
    },
    {
      simplified: "外面",
      traditional: "外面",
      pinyin: "wàimiàn",
      english: "Outside",
    },
    {
      simplified: "里面",
      traditional: "裡面",
      pinyin: "lǐmiàn",
      english: "Inside",
    },
    {
      simplified: "商店",
      traditional: "商店",
      pinyin: "shāngdiàn",
      english: "Store",
    },
    {
      simplified: "吃饭",
      traditional: "吃飯",
      pinyin: "chīfàn",
      english: "Eat",
    },
    {
      simplified: "宿舍",
      traditional: "宿舍",
      pinyin: "sù shè",
      english: "Dorm room",
    },
    {
      simplified: "楼",
      traditional: "樓",
      pinyin: "lóu",
      english: "Floor",
    },
    {
      simplified: "栋",
      traditional: "棟",
      pinyin: "dòng",
      english: "Dong",
    },
    {
      simplified: "大楼",
      traditional: "大樓",
      pinyin: "dàlóu",
      english: "Building",
    },
    {
      simplified: "图书馆",
      traditional: "圖書館",
      pinyin: "tú shū guǎn",
      english: "Library",
    },
    {
      simplified: "旁边",
      traditional: "旁邊",
      pinyin: "páng biān",
      english: "Next to",
    },
    {
      simplified: "教师",
      traditional: "教師",
      pinyin: "jiàoshī",
      english: "Teacher",
    },
    {
      simplified: "游泳池",
      traditional: "游泳池",
      pinyin: "yóu yǒng chí",
      english: "Swimming pool",
    },
    {
      simplified: "水果",
      traditional: "水果",
      pinyin: "shuǐ guǒ",
      english: "Fruit",
    },
    {
      simplified: "黄色",
      traditional: "黃色",
      pinyin: "huáng sè",
      english: "Yellow",
    },
    {
      simplified: "芒果",
      traditional: "芒果",
      pinyin: "máng guǒ",
      english: "Mango",
    },
    {
      simplified: "给",
      traditional: "給",
      pinyin: "gěi",
      english: "Give",
    },
    {
      simplified: "块",
      traditional: "塊",
      pinyin: "kuài",
      english: "Piece",
    },
    {
      simplified: "香",
      traditional: "香",
      pinyin: "xiāng",
      english: "Fragrant",
    },
    {
      simplified: "甜",
      traditional: "甜",
      pinyin: "tián",
      english: "Sweet",
    },
    {
      simplified: "红色",
      traditional: "紅色",
      pinyin: "hóng sè",
      english: "Red",
    },
    {
      simplified: "西瓜",
      traditional: "西瓜",
      pinyin: "xī guā",
      english: "Watermelon",
    },
    {
      simplified: "吧",
      traditional: "吧",
      pinyin: "bā",
      english: "Right",
    },
    {
      simplified: "对",
      traditional: "對",
      pinyin: "duì",
      english: "Correct",
    },
    {
      simplified: "以前",
      traditional: "以前",
      pinyin: "yǐ qián",
      english: "Before",
    },
    {
      simplified: "机会",
      traditional: "機會",
      pinyin: "jī huì",
      english: "Opportunity",
    },
    {
      simplified: "请",
      traditional: "請",
      pinyin: "qǐng",
      english: "Please",
    },
    {
      simplified: "吃吃看",
      traditional: "吃吃看",
      pinyin: "chī chī ",
      english: "Try it",
    },
    {
      simplified: "拍",
      traditional: "拍",
      pinyin: "pāi",
      english: "Beat",
    },
    {
      simplified: "笑",
      traditional: "笑",
      pinyin: "xiào",
      english: "Laugh",
    },
    {
      simplified: "开心",
      traditional: "開心",
      pinyin: "kāi xīn",
      english: "Happy",
    },
    {
      simplified: "穿",
      traditional: "穿",
      pinyin: "chuān",
      english: "Wear",
    },
    {
      simplified: "衣服",
      traditional: "衣服",
      pinyin: "yī fu",
      english: "Clothes",
    },
    {
      simplified: "旅馆",
      traditional: "旅館",
      pinyin: "lǚ guǎn",
      english: "Hostel",
    },
    {
      simplified: "太太",
      traditional: "太太",
      pinyin: "tài tai",
      english: "Mrs",
    },
    {
      simplified: "男",
      traditional: "男",
      pinyin: "nán",
      english: "Male",
    },
    {
      simplified: "矮",
      traditional: "矮",
      pinyin: "ǎi",
      english: "Short",
    },
    {
      simplified: "高",
      traditional: "高",
      pinyin: "gāo",
      english: "High",
    },
    {
      simplified: "弟弟",
      traditional: "弟弟",
      pinyin: "dì di",
      english: "Little brother",
    },
    {
      simplified: "干净",
      traditional: "乾淨",
      pinyin: "gān jìng",
      english: "Clean",
    },
    {
      simplified: "窗户",
      traditional: "窗戶",
      pinyin: "chuāng hu",
      english: "Window",
    },
    {
      simplified: "往",
      traditional: "往",
      pinyin: "wǎng",
      english: "To",
    },
    {
      simplified: "蓝色",
      traditional: "藍色",
      pinyin: "lán sè",
      english: "Blue",
    },
    {
      simplified: "因为",
      traditional: "因為",
      pinyin: "yīn wèi",
      english: "Because",
    },
    {
      simplified: "住",
      traditional: "住",
      pinyin: "zhù",
      english: "Live",
    },
    {
      simplified: "上个月",
      traditional: "上個月",
      pinyin: "shàng gè yuè",
      english: "Last month",
    },
    {
      simplified: "这些",
      traditional: "這些",
      pinyin: "zhè xiē",
      english: "These ones",
    },
  ],
  dictation: [
    {
      simplified: "月",
      traditional: "月",
      pinyin: "yuè",
      english: "Month",
    },
    {
      simplified: "美",
      traditional: "美",
      pinyin: "měi",
      english: "Nice",
    },
    {
      simplified: "明",
      traditional: "明",
      pinyin: "míng",
      english: "Bright",
    },
    {
      simplified: "华",
      traditional: "華",
      pinyin: "huá",
      english: "China",
    },
    {
      simplified: "王",
      traditional: "王",
      pinyin: "wáng",
      english: "King",
    },
    {
      simplified: "开",
      traditional: "開",
      pinyin: "kāi",
      english: "Open",
    },
    {
      simplified: "文",
      traditional: "文",
      pinyin: "wén",
      english: "Text",
    },
    {
      simplified: "你",
      traditional: "你",
      pinyin: "nǐ",
      english: "You",
    },
    {
      simplified: "来",
      traditional: "來",
      pinyin: "lái",
      english: "Come",
    },
    {
      simplified: "是",
      traditional: "是",
      pinyin: "shì",
      english: "Yes",
    },
    {
      simplified: "小",
      traditional: "小",
      pinyin: "xiǎo",
      english: "Small",
    },
    {
      simplified: "姐",
      traditional: "姐",
      pinyin: "jiě",
      english: "Sister",
    },
    {
      simplified: "吗",
      traditional: "嗎",
      pinyin: "mǎ",
      english: "?",
    },
    {
      simplified: "接",
      traditional: "接",
      pinyin: "jiē",
      english: "Pick up",
    },
    {
      simplified: "我",
      traditional: "我",
      pinyin: "wǒ",
      english: "I",
    },
    {
      simplified: "们",
      traditional: "們",
      pinyin: "men",
      english: "We",
    },
    {
      simplified: "这",
      traditional: "這",
      pinyin: "zhè",
      english: "This",
    },
    {
      simplified: "先",
      traditional: "先",
      pinyin: "xiān",
      english: "First",
    },
    {
      simplified: "生",
      traditional: "生",
      pinyin: "shēng",
      english: "Raw",
    },
    {
      simplified: "好",
      traditional: "好",
      pinyin: "hǎo",
      english: "It is good",
    },
    {
      simplified: "姓",
      traditional: "姓",
      pinyin: "xìng",
      english: "Surname",
    },
    {
      simplified: "叫",
      traditional: "叫",
      pinyin: "jiào",
      english: "Call",
    },
    {
      simplified: "台",
      traditional: "臺",
      pinyin: "tái",
      english: "Station",
    },
    {
      simplified: "湾",
      traditional: "灣",
      pinyin: "wān",
      english: "Bay",
    },
    {
      simplified: "欢",
      traditional: "歡",
      pinyin: "huān",
      english: "Huan",
    },
    {
      simplified: "迎",
      traditional: "迎",
      pinyin: "yíng",
      english: "Welcome",
    },
    {
      simplified: "请",
      traditional: "請",
      pinyin: "qǐng",
      english: "Please",
    },
    {
      simplified: "问",
      traditional: "問",
      pinyin: "wèn",
      english: "Ask",
    },
    {
      simplified: "的",
      traditional: "的",
      pinyin: "de",
      english: "Of",
    },
    {
      simplified: "谢",
      traditional: "謝",
      pinyin: "xiè",
      english: "Thank",
    },
    {
      simplified: "不",
      traditional: "不",
      pinyin: "bù",
      english: "Do not",
    },
    {
      simplified: "客",
      traditional: "客",
      pinyin: "kè",
      english: "Customer",
    },
    {
      simplified: "气",
      traditional: "氣",
      pinyin: "qì",
      english: "Gas",
    },
    {
      simplified: "喝",
      traditional: "喝",
      pinyin: "hē",
      english: "Drink",
    },
    {
      simplified: "茶",
      traditional: "茶",
      pinyin: "chá",
      english: "Tea",
    },
    {
      simplified: "谢",
      traditional: "謝",
      pinyin: "xiè",
      english: "Thank",
    },
    {
      simplified: "不",
      traditional: "不",
      pinyin: "bù",
      english: "Do not",
    },
    {
      simplified: "客",
      traditional: "客",
      pinyin: "kè",
      english: "Customer",
    },
    {
      simplified: "气",
      traditional: "氣",
      pinyin: "qì",
      english: "Gas",
    },
    {
      simplified: "喝",
      traditional: "喝",
      pinyin: "hē",
      english: "Drink",
    },
    {
      simplified: "茶",
      traditional: "茶",
      pinyin: "chá",
      english: "Tea",
    },
    {
      simplified: "很",
      traditional: "很",
      pinyin: "hěn",
      english: "Very",
    },
    {
      simplified: "什",
      traditional: "什",
      pinyin: "shén",
      english: "What",
    },
    {
      simplified: "么",
      traditional: "麼",
      pinyin: "me",
      english: "What",
    },
    {
      simplified: "人",
      traditional: "人",
      pinyin: "rén",
      english: "People",
    },
    {
      simplified: "喜",
      traditional: "喜",
      pinyin: "xǐ",
      english: "Like",
    },
    {
      simplified: "呢",
      traditional: "呢",
      pinyin: "ne",
      english: "What",
    },
    {
      simplified: "他",
      traditional: "他",
      pinyin: "tā",
      english: "He",
    },
    {
      simplified: "哪",
      traditional: "哪",
      pinyin: "nǎ",
      english: "Where",
    },
    {
      simplified: "要",
      traditional: "要",
      pinyin: "yāo",
      english: "To",
    },
    {
      simplified: "咖",
      traditional: "咖",
      pinyin: "kā",
      english: "Coffee",
    },
    {
      simplified: "啡",
      traditional: "啡",
      pinyin: "fēi",
      english: "Coffee",
    },
    {
      simplified: "乌",
      traditional: "烏",
      pinyin: "wū",
      english: "Black",
    },
    {
      simplified: "龙",
      traditional: "龍",
      pinyin: "lóng",
      english: "Long",
    },
    {
      simplified: "日",
      traditional: "日",
      pinyin: "rì",
      english: "Day",
    },
    {
      simplified: "本",
      traditional: "本",
      pinyin: "běn",
      english: "This",
    },
    {
      simplified: "国",
      traditional: "國",
      pinyin: "guó",
      english: "Country",
    },
    {
      simplified: "对",
      traditional: "對",
      pinyin: "duì",
      english: "Correct",
    },
    {
      simplified: "起",
      traditional: "起",
      pinyin: "qǐ",
      english: "From",
    },
    {
      simplified: "的",
      traditional: "的",
      pinyin: "de",
      english: "Of",
    },
    {
      simplified: "家人",
      traditional: "家人",
      pinyin: "jiā rén",
      english: "Family",
    },
    {
      simplified: "家",
      traditional: "家",
      pinyin: "jiā",
      english: "Family",
    },
    {
      simplified: "漂亮",
      traditional: "漂亮",
      pinyin: "piào liang",
      english: "Pretty",
    },
    {
      simplified: "房子",
      traditional: "房子",
      pinyin: "fáng zi",
      english: "House",
    },
    {
      simplified: "坐",
      traditional: "坐",
      pinyin: "zuò",
      english: "Sit",
    },
    {
      simplified: "有",
      traditional: "有",
      pinyin: "yǒu",
      english: "Have",
    },
    {
      simplified: "多",
      traditional: "多",
      pinyin: "duō",
      english: "Many",
    },
    {
      simplified: "照片",
      traditional: "照片",
      pinyin: "zhào piàn",
      english: "Photo",
    },
    {
      simplified: "都",
      traditional: "都",
      pinyin: "dū",
      english: "All",
    },
    {
      simplified: "照相",
      traditional: "照相",
      pinyin: "zhào xiàng",
      english: "Take pictures",
    },
    {
      simplified: "张",
      traditional: "張",
      pinyin: "zhāng",
      english: "Zhang",
    },
    {
      simplified: "好看",
      traditional: "好看",
      pinyin: "hǎo kàn",
      english: "Good looking",
    },
    {
      simplified: "谁",
      traditional: "誰",
      pinyin: "shéi",
      english: "Who",
    },
    {
      simplified: "姐姐",
      traditional: "姐姐",
      pinyin: "jiě jie",
      english: "Sister",
    },
    {
      simplified: "妹妹",
      traditional: "妹妹",
      pinyin: "mèi mei",
      english: "Younger sister",
    },
    {
      simplified: "爸爸",
      traditional: "爸爸",
      pinyin: "bà ba",
      english: "Father",
    },
    {
      simplified: "妈妈",
      traditional: "媽媽",
      pinyin: "mā ma",
      english: "Mom",
    },
    {
      simplified: "请进",
      traditional: "請進",
      pinyin: "qǐng jìn",
      english: "Come in",
    },
    {
      simplified: "伯母",
      traditional: "伯母",
      pinyin: "bó mǔ",
      english: "Aunt",
    },
    {
      simplified: "您",
      traditional: "您",
      pinyin: "nín",
      english: "You",
    },
    {
      simplified: "名字",
      traditional: "名字",
      pinyin: "míng zi",
      english: "First name",
    },
    {
      simplified: "书",
      traditional: "書",
      pinyin: "shū",
      english: "Book",
    },
    {
      simplified: "哥哥",
      traditional: "哥哥",
      pinyin: "gē ge",
      english: "Brother",
    },
    {
      simplified: "老师",
      traditional: "老師",
      pinyin: "lǎo shī",
      english: "Teacher",
    },
    {
      simplified: "看书",
      traditional: "看書",
      pinyin: "kàn shū",
      english: "Read a book",
    },
    {
      simplified: "几",
      traditional: "幾",
      pinyin: "jī",
      english: "A few",
    },
    {
      simplified: "个",
      traditional: "個",
      pinyin: "gè",
      english: "Each",
    },
    {
      simplified: "没",
      traditional: "沒",
      pinyin: "méi",
      english: "No",
    },
    {
      simplified: "兄弟",
      traditional: "兄弟",
      pinyin: "xiōng dì",
      english: "Brothers",
    },
    {
      simplified: "姐妹",
      traditional: "姐妹",
      pinyin: "jiě mèi",
      english: "Sisters",
    },
    {
      simplified: "五",
      traditional: "五",
      pinyin: "wǔ",
      english: "Five",
    },
    {
      simplified: "两",
      traditional: "兩",
      pinyin: "liǎng",
      english: "Two",
    },
  ],
};

export default lesson;
