import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "fKaufksuw0",
  type: "Contemporary Chinese",
  locked: false,
  title: "Lesson 13",
  content: [
    {
      traditional: "生日",
      simplified: "生日",
      pinyin: "shēng rì",
      english: "Birthday",
    },
    {
      traditional: "快樂",
      simplified: "快乐",
      pinyin: "kuài lè",
      english: "Happy",
    },
    {
      traditional: "回來",
      simplified: "回来",
      pinyin: "huí lái",
      english: "Come back",
    },
    {
      traditional: "啊",
      simplified: "啊",
      pinyin: "a",
      english: "What",
    },
    {
      traditional: "怎麼",
      simplified: "怎么",
      pinyin: "zěn me",
      english: "How",
    },
    {
      traditional: "忘了",
      simplified: "忘了",
      pinyin: "wàng le",
      english: "Forget",
    },
    {
      traditional: "記得",
      simplified: "记得",
      pinyin: "jì dé",
      english: "Remember",
    },
    {
      traditional: "當然",
      simplified: "当然",
      pinyin: "dāng rán",
      english: "Of course",
    },
    {
      traditional: "語言",
      simplified: "语言",
      pinyin: "yǔ yán",
      english: "Language",
    },
    {
      traditional: "交換",
      simplified: "交换",
      pinyin: "jiāo huàn",
      english: "Exchange",
    },
    {
      traditional: "那麼",
      simplified: "那么",
      pinyin: "nà me",
      english: "Then",
    },
    {
      traditional: "熱心",
      simplified: "热心",
      pinyin: "rè xīn",
      english: "Enthusiastic",
    },
    {
      traditional: "西班牙文",
      simplified: "西班牙文",
      pinyin: "xī bān yá wén",
      english: "Spanish",
    },
    {
      traditional: "一樣",
      simplified: "一样",
      pinyin: "yī yàng",
      english: "Same",
    },
    {
      traditional: "過",
      simplified: "过",
      pinyin: "guò",
      english: "Pass",
    },
    {
      traditional: "左右",
      simplified: "左右",
      pinyin: "zuǒ yòu",
      english: "About",
    },
    {
      traditional: "門口",
      simplified: "门口",
      pinyin: "mén kǒu",
      english: "Doorway",
    },
    {
      traditional: "西班牙",
      simplified: "西班牙",
      pinyin: "xī bān yá",
      english: "Spain",
    },
    {
      traditional: "生日快樂",
      simplified: "生日快乐",
      pinyin: "shēng rì kuài lè",
      english: "Happy birthday",
    },
    {
      traditional: "我就是",
      simplified: "我就是",
      pinyin: "wǒ jiù shì",
      english: "I am",
    },
    {
      traditional: "好久不見",
      simplified: "好久不见",
      pinyin: "hǎo jiǔ bù jiàn",
      english: "Long time no see",
    },
    {
      traditional: "不必客氣",
      simplified: "不必客气",
      pinyin: "bù bì kè qì",
      english: "It's my pleasure",
    },
    {
      traditional: "太客氣",
      simplified: "太客气",
      pinyin: "tài kè qì",
      english: "That's very kind of you",
    },
    {
      traditional: "禮物",
      simplified: "礼物",
      pinyin: "lǐ wù",
      english: "Gift",
    },
    {
      traditional: "今年",
      simplified: "今年",
      pinyin: "jīn nián",
      english: "This year",
    },
    {
      traditional: "訂",
      simplified: "订",
      pinyin: "dìng",
      english: "Order",
    },
    {
      traditional: "了",
      simplified: "了",
      pinyin: "le",
      english: "Up",
    },
    {
      traditional: "豬腳",
      simplified: "猪脚",
      pinyin: "zhū jiǎo",
      english: "Pig's feet",
    },
    {
      traditional: "麵線",
      simplified: "面线",
      pinyin: "miàn xiàn",
      english: "Noodles",
    },
    {
      traditional: "蛋",
      simplified: "蛋",
      pinyin: "dàn",
      english: "Egg",
    },
    {
      traditional: "一點",
      simplified: "一点",
      pinyin: "yī diǎn",
      english: "A little",
    },
    {
      traditional: "傳統",
      simplified: "传统",
      pinyin: "chuán tǒng",
      english: "Traditional",
    },
    {
      traditional: "年輕",
      simplified: "年轻",
      pinyin: "nián qīng",
      english: "Young",
    },
    {
      traditional: "蛋糕",
      simplified: "蛋糕",
      pinyin: "dàn gāo",
      english: "Cake",
    },
    {
      traditional: "對",
      simplified: "对",
      pinyin: "duì",
      english: "Correct",
    },
    {
      traditional: "祝",
      simplified: "祝",
      pinyin: "zhù",
      english: "Wish",
    },
    {
      traditional: "哪裡，哪裡",
      simplified: "哪里，哪里",
      pinyin: "nǎ lǐ nǎ lǐ",
      english: "My pleasure",
    },
    {
      traditional: "大部分",
      simplified: "大部分",
      pinyin: "dà bù fèn",
      english: "Most",
    },
    {
      traditional: "萬事如意",
      simplified: "万事如意",
      pinyin: "wàn shì rú yì",
      english: "Everything goes well",
    },
    {
      traditional: "心想事成",
      simplified: "心想事成",
      pinyin: "xīn xiǎng shì chéng",
      english: "All wishes come true",
    },
  ],
};

export default lesson;
