import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "fKauffnaql",
  type: "Contemporary Chinese",
  locked: false,
  title: "Lesson 15",
  content: [
    {
      traditional: "醫生",
      simplified: "医生",
      pinyin: "yī shēng",
      english: "Doctors",
    },
    {
      traditional: "一直",
      simplified: "一直",
      pinyin: "yī zhí",
      english: "Always",
    },
    {
      traditional: "流",
      simplified: "流",
      pinyin: "liú",
      english: "Flow",
    },
    {
      traditional: "鼻水",
      simplified: "鼻水",
      pinyin: "bí shuǐ",
      english: "Nose water",
    },
    {
      traditional: "頭",
      simplified: "头",
      pinyin: "tóu",
      english: "Head",
    },
    {
      traditional: "痛",
      simplified: "痛",
      pinyin: "tòng",
      english: "Pain",
    },
    {
      traditional: "胃口",
      simplified: "胃口",
      pinyin: "wèi kǒu",
      english: "Appetite",
    },
    {
      traditional: "差",
      simplified: "差",
      pinyin: "chà",
      english: "Difference",
    },
    {
      traditional: "喉嚨",
      simplified: "喉咙",
      pinyin: "hóu lóng",
      english: "Throat",
    },
    {
      traditional: "發炎",
      simplified: "发炎",
      pinyin: "fā yán",
      english: "Fever",
    },
    {
      traditional: "生病",
      simplified: "生病",
      pinyin: "shēng bìng",
      english: "Sick",
    },
    {
      traditional: "發燒",
      simplified: "发烧",
      pinyin: "fā shāo",
      english: "Fever",
    },
    {
      traditional: "感冒",
      simplified: "感冒",
      pinyin: "gǎn mào",
      english: "Cold",
    },
    {
      traditional: "藥",
      simplified: "药",
      pinyin: "yào",
      english: "Medicine",
    },
    {
      traditional: "藥局",
      simplified: "药局",
      pinyin: "yào jú",
      english: "Pharmacy",
    },
    {
      traditional: "拿",
      simplified: "拿",
      pinyin: "ná",
      english: "Take",
    },
    {
      traditional: "把",
      simplified: "把",
      pinyin: "bǎ",
      english: "Put",
    },
    {
      traditional: "水",
      simplified: "水",
      pinyin: "shuǐ",
      english: "Water",
    },
    {
      traditional: "休息",
      simplified: "休息",
      pinyin: "xiū xī",
      english: "Rest",
    },
    {
      traditional: "睡覺",
      simplified: "睡觉",
      pinyin: "shuì jué",
      english: "Go to bed",
    },
    {
      traditional: "早一點",
      simplified: "早一点",
      pinyin: "zǎo yī diǎn",
      english: "Earlier",
    },
    {
      traditional: "臉色",
      simplified: "脸色",
      pinyin: "liǎn sè",
      english: "Face",
    },
    {
      traditional: "難看",
      simplified: "难看",
      pinyin: "nán kàn",
      english: "Ugly",
    },
    {
      traditional: "肚子",
      simplified: "肚子",
      pinyin: "dǔ zi",
      english: "Belly",
    },
    {
      traditional: "吐",
      simplified: "吐",
      pinyin: "tǔ",
      english: "Threw up",
    },
    {
      traditional: "幾",
      simplified: "几",
      pinyin: "jǐ",
      english: "A few",
    },
    {
      traditional: "次",
      simplified: "次",
      pinyin: "cì",
      english: "Times",
    },
    {
      traditional: "陪",
      simplified: "陪",
      pinyin: "péi",
      english: "Accompany",
    },
    {
      traditional: "看病",
      simplified: "看病",
      pinyin: "kàn bìng",
      english: "See a doctor",
    },
    {
      traditional: "健康",
      simplified: "健康",
      pinyin: "jiàn kāng",
      english: "Health",
    },
    {
      traditional: "保險",
      simplified: "保险",
      pinyin: "bǎo xiǎn",
      english: "Insurance",
    },
    {
      traditional: "跟",
      simplified: "跟",
      pinyin: "gēn",
      english: "With",
    },
    {
      traditional: "油",
      simplified: "油",
      pinyin: "yóu",
      english: "Oil",
    },
    {
      traditional: "冰",
      simplified: "冰",
      pinyin: "bīng",
      english: "Ice",
    },
    {
      traditional: "別",
      simplified: "别",
      pinyin: "bié",
      english: "Do not",
    },
    {
      traditional: "關心",
      simplified: "关心",
      pinyin: "guān xīn",
      english: "Concern",
    },
    {
      traditional: "包",
      simplified: "包",
      pinyin: "bāo",
      english: "Package",
    },
    {
      traditional: "睡",
      simplified: "睡",
      pinyin: "shuì",
      english: "Sleep",
    },
    {
      traditional: "小時",
      simplified: "小时",
      pinyin: "xiǎo shí",
      english: "Hour",
    },
    {
      traditional: "怎麼了",
      simplified: "怎么了",
      pinyin: "zěn me le",
      english: "What's happenin",
    },
    {
      traditional: "不用了",
      simplified: "不用了",
      pinyin: "bù yòng le",
      english: "No need",
    },
    {
      traditional: "健康中心",
      simplified: "健康中心",
      pinyin: "jiàn kāng zhōng xīn",
      english: "Health center",
    },
    {
      traditional: "回家",
      simplified: "回家",
      pinyin: "huí jiā",
      english: "Come back home",
    },
    {
      traditional: "最好",
      simplified: "最好",
      pinyin: "zuì hǎo",
      english: "The best",
    },
  ],
};

export default lesson;
