import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "fuS2jhj7T",
  type: "Contemporary Chinese",
  list: "13",
  locked: false,
  title: "Lesson 10",
  content: [
    {
      simplified: "水果",
      traditional: "水果",
      pinyin: "shuǐguǒ",
      english: "Fruit",
    },
    {
      simplified: "黄色",
      traditional: "黃色",
      pinyin: "huángsè",
      english: "Yellow",
    },
    {
      simplified: "芒果",
      traditional: "芒果",
      pinyin: "mángguǒ",
      english: "Mango",
    },
    {
      simplified: "给",
      traditional: "給",
      pinyin: "gěi",
      english: "To give",
    },
    {
      simplified: "块",
      traditional: "塊",
      pinyin: "kuài",
      english: "Piece of food",
    },
    {
      simplified: "想",
      traditional: "想",
      pinyin: "xiǎng",
      english: "Fragrant",
    },
    {
      simplified: "甜",
      traditional: "甜",
      pinyin: "tián",
      english: "Sweet (taste)",
    },
    {
      simplified: "红色",
      traditional: "紅色",
      pinyin: "hóngsè",
      english: "Red",
    },
    {
      simplified: "西瓜",
      traditional: "西瓜",
      pinyin: "xīguā",
      english: "Watermelon",
    },
    {
      simplified: "吧",
      traditional: "吧",
      pinyin: "ba",
      english: "Sentence finale particle (guessing)",
    },
    {
      simplified: "对",
      traditional: "對",
      pinyin: "duì",
      english: "Correct, right",
    },
    {
      simplified: "以前",
      traditional: "以前",
      pinyin: "yǐqián",
      english: "Before",
    },
    {
      simplified: "机会",
      traditional: "機會",
      pinyin: "jīhuì",
      english: "Opportunity",
    },
    {
      simplified: "请",
      traditional: "請",
      pinyin: "qǐng",
      english: "To treat someone",
    },
    {
      simplified: "香蕉",
      traditional: "香蕉",
      pinyin: "xiāngjiāo",
      english: "Banana",
    },
    {
      simplified: "菠萝",
      traditional: "菠蘿",
      pinyin: "bōluó",
      english: "Pineapple",
    },
    {
      simplified: "草莓",
      traditional: "草莓",
      pinyin: "cǎoméi",
      english: "Strawberry",
    },
    {
      simplified: "蓝莓",
      traditional: "藍莓",
      pinyin: "lánméi",
      english: "Blueberry",
    },
    {
      simplified: "葡萄",
      traditional: "葡萄",
      pinyin: "pútáo",
      english: "Grape",
    },
    {
      simplified: "拍",
      traditional: "拍",
      pinyin: "pāi",
      english: "To take a picture",
    },
    {
      simplified: "笑",
      traditional: "笑",
      pinyin: "xiào",
      english: "Laugh, smile",
    },
    {
      simplified: "开心",
      traditional: "開心",
      pinyin: "kāixīn",
      english: "Happy",
    },
    {
      simplified: "穿",
      traditional: "穿",
      pinyin: "chuān",
      english: "Wear",
    },
    {
      simplified: "衣服",
      traditional: "衣服",
      pinyin: "yīfú",
      english: "Clothes",
    },
    {
      simplified: "旅馆",
      traditional: "旅館",
      pinyin: "lǚguǎn",
      english: "Hotel",
    },
    {
      simplified: "太太",
      traditional: "太太",
      pinyin: "tàitài",
      english: "Wife",
    },
    {
      simplified: "男",
      traditional: "男",
      pinyin: "nán",
      english: "Boy, male",
    },
    {
      simplified: "矮",
      traditional: "矮",
      pinyin: "ǎi",
      english: "Short",
    },
    {
      simplified: "高",
      traditional: "高",
      pinyin: "gāo",
      english: "Tall",
    },
    {
      simplified: "弟弟",
      traditional: "弟弟",
      pinyin: "dìdì",
      english: "Younger brother",
    },
    {
      simplified: "干净",
      traditional: "乾淨",
      pinyin: "gānjìng",
      english: "Clean",
    },
    {
      simplified: "窗户",
      traditional: "窗戶",
      pinyin: "chuānghù",
      english: "Window",
    },
    {
      simplified: "往",
      traditional: "往",
      pinyin: "wǎng",
      english: "To, toward",
    },
    {
      simplified: "蓝色",
      traditional: "藍色",
      pinyin: "lánsè",
      english: "Blue",
    },
    {
      simplified: "因为",
      traditional: "因為",
      pinyin: "yīnwèi",
      english: "Because",
    },
    {
      simplified: "住",
      traditional: "住",
      pinyin: "zhù",
      english: "To stay",
    },
    {
      simplified: "上个月",
      traditional: "上個月",
      pinyin: "shàng gè yuè",
      english: "Last month",
    },
    {
      simplified: "这些",
      traditional: "這些",
      pinyin: "zhèxiē",
      english: "These",
    },
  ],
};

export default lesson;
