import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "fKauWfjsuQ",
  type: "Far East",
  locked: false,
  title: "Lesson 9",
  content: [
    {
      traditional: "王家明",
      simplified: "王家明",
      pinyin: "wáng jiā míng",
      english: "Wang jiaming",
    },
    {
      traditional: "貴姓",
      simplified: "贵姓",
      pinyin: "guì xìng",
      english: "Your last name",
    },
    {
      traditional: "林金水",
      simplified: "林金水",
      pinyin: "lín jīn shuǐ",
      english: "Lin jinshui",
    },
    {
      traditional: "台灣大學",
      simplified: "台湾大学",
      pinyin: "tái wān dà xué",
      english: "Taiwan university",
    },
    {
      traditional: "念書",
      simplified: "念书",
      pinyin: "niàn shū",
      english: "Study",
    },
    {
      traditional: "家",
      simplified: "家",
      pinyin: "jiā",
      english: "Home",
    },
    {
      traditional: "爸媽",
      simplified: "爸妈",
      pinyin: "bà mā",
      english: "Parents",
    },
    {
      traditional: "上海",
      simplified: "上海",
      pinyin: "shàng hǎi",
      english: "Shanghai",
    },
    {
      traditional: "多",
      simplified: "多",
      pinyin: "duō",
      english: "Many",
    },
    {
      traditional: "久",
      simplified: "久",
      pinyin: "jiǔ",
      english: "Long",
    },
    {
      traditional: "歲",
      simplified: "岁",
      pinyin: "suì",
      english: "Year old",
    },
    {
      traditional: "英文",
      simplified: "英文",
      pinyin: "yīng wén",
      english: "English",
    },
    {
      traditional: "一定",
      simplified: "一定",
      pinyin: "yí dìng",
      english: "For sure",
    },
    {
      traditional: "會",
      simplified: "会",
      pinyin: "huì",
      english: "Meeting",
    },
    {
      traditional: "教",
      simplified: "教",
      pinyin: "jiào",
      english: "Teach",
    },
    {
      traditional: "台北",
      simplified: "台北",
      pinyin: "tái běi",
      english: "Taipei",
    },
    {
      traditional: "台南",
      simplified: "台南",
      pinyin: "tái nán",
      english: "Tainan",
    },
    {
      traditional: "還",
      simplified: "还",
      pinyin: "hái",
      english: "Also",
    },
    {
      traditional: "哥哥",
      simplified: "哥哥",
      pinyin: "gē ge",
      english: "Brother",
    },
    {
      traditional: "姊姊",
      simplified: "姊姊",
      pinyin: "zǐ zǐ",
      english: "Sister",
    },
    {
      traditional: "妹妹",
      simplified: "妹妹",
      pinyin: "mèi mei",
      english: "Younger sister",
    },
    {
      traditional: "弟弟",
      simplified: "弟弟",
      pinyin: "dì di",
      english: "Younger brother",
    },
    {
      traditional: "有的",
      simplified: "有的",
      pinyin: "yǒu dē",
      english: "Some",
    },
    {
      traditional: "在",
      simplified: "在",
      pinyin: "zài",
      english: "In",
    },
    {
      traditional: "做事",
      simplified: "做事",
      pinyin: "zuò shì",
      english: "Work",
    },
    {
      traditional: "女孩子",
      simplified: "女孩子",
      pinyin: "nǚ hái zi",
      english: "Girl",
    },
    {
      traditional: "孩子",
      simplified: "孩子",
      pinyin: "hái zi",
      english: "Child",
    },
    {
      traditional: "男孩子",
      simplified: "男孩子",
      pinyin: "nán hái zi",
      english: "Boy",
    },
    {
      traditional: "上課",
      simplified: "上课",
      pinyin: "shàng kè",
      english: "Go to class",
    },
    {
      traditional: "大概",
      simplified: "大概",
      pinyin: "dà gài",
      english: "Probably",
    },
    {
      traditional: "認識",
      simplified: "认识",
      pinyin: "rèn shí",
      english: "Understanding",
    },
    {
      traditional: "大有",
      simplified: "大有",
      pinyin: "dà yǒu",
      english: "Great",
    },
    {
      traditional: "介紹",
      simplified: "介绍",
      pinyin: "jiè shào",
      english: "Introduction",
    },
    {
      traditional: "王明",
      simplified: "王明",
      pinyin: "wáng míng",
      english: "Wang ming",
    },
    {
      traditional: "謝新雨",
      simplified: "谢新雨",
      pinyin: "xiè xīn yǔ",
      english: "Xie xinyu",
    },
    {
      traditional: "喝",
      simplified: "喝",
      pinyin: "hē",
      english: "Drink",
    },
    {
      traditional: "可樂",
      simplified: "可乐",
      pinyin: "kě lè",
      english: "Coke",
    },
    {
      traditional: "啤酒",
      simplified: "啤酒",
      pinyin: "pí jiǔ",
      english: "Beer",
    },
    {
      traditional: "酒",
      simplified: "酒",
      pinyin: "jiǔ",
      english: "Liqueur",
    },
    {
      traditional: "電腦",
      simplified: "电脑",
      pinyin: "diàn nǎo",
      english: "Computer",
    },
    {
      traditional: "工程師",
      simplified: "工程师",
      pinyin: "gōng chéng shī",
      english: "Engineer",
    },
    {
      traditional: "名片",
      simplified: "名片",
      pinyin: "míng piàn",
      english: "Business card",
    },
    {
      traditional: "難",
      simplified: "难",
      pinyin: "nán",
      english: "Difficult",
    },
    {
      traditional: "容易",
      simplified: "容易",
      pinyin: "róng yì",
      english: "Easy",
    },
    {
      traditional: "懂",
      simplified: "懂",
      pinyin: "dǒng",
      english: "Understand",
    },
    {
      traditional: "工作",
      simplified: "工作",
      pinyin: "gōng zuò",
      english: "Jobs",
    },
    {
      traditional: "貿易公司",
      simplified: "贸易公司",
      pinyin: "mào yì gōng sī",
      english: "Trading company",
    },
    {
      traditional: "常常",
      simplified: "常常",
      pinyin: "cháng cháng",
      english: "Often",
    },
    {
      traditional: "電影",
      simplified: "电影",
      pinyin: "diàn yǐng",
      english: "The film",
    },
    {
      traditional: "逛街",
      simplified: "逛街",
      pinyin: "guàng jiē",
      english: "Go shopping",
    },
    {
      traditional: "愛",
      simplified: "爱",
      pinyin: "ài",
      english: "Love",
    },
    {
      traditional: "爬山",
      simplified: "爬山",
      pinyin: "pá shān",
      english: "Mountain climbing",
    },
    {
      traditional: "打球",
      simplified: "打球",
      pinyin: "dǎ qiú",
      english: "Play ball",
    },
    {
      traditional: "打",
      simplified: "打",
      pinyin: "dǎ",
      english: "Hit",
    },
    {
      traditional: "球",
      simplified: "球",
      pinyin: "qiú",
      english: "Ball",
    },
  ],
};

export default lesson;
