import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "hjbUpJC1UF",
  type: "Far East",
  locked: false,
  title: "Far East Lessons 1-8",
  content: [
    {
      simplified: "付",
      traditional: "付",
      pinyin: "fù",
      english: "Pay",
    },
    {
      simplified: "打折",
      traditional: "打折",
      pinyin: "dǎzhé",
      english: "Discount",
    },
    {
      simplified: "刷卡",
      traditional: "刷卡",
      pinyin: "shuākǎ",
      english: "Swipe",
    },
    {
      simplified: "信用卡",
      traditional: "信用卡",
      pinyin: "xìnyòngkǎ",
      english: "Credit card",
    },
    {
      simplified: "收",
      traditional: "收",
      pinyin: "shōu",
      english: "Receive",
    },
    {
      simplified: "那么",
      traditional: "那麼",
      pinyin: "nàme",
      english: "Then",
    },
    {
      simplified: "现金",
      traditional: "現金",
      pinyin: "xiànjīn",
      english: "Cash",
    },
    {
      simplified: "这票",
      traditional: "這票",
      pinyin: "zhè piào",
      english: "Check",
    },
    {
      simplified: "旧",
      traditional: "舊",
      pinyin: "jiù",
      english: "Old",
    },
    {
      simplified: "换",
      traditional: "換",
      pinyin: "huàn",
      english: "To exchange",
    },
    {
      simplified: "美金",
      traditional: "美金",
      pinyin: "měijīn",
      english: "US Dollar",
    },
    {
      simplified: "台币",
      traditional: "台幣",
      pinyin: "táibì",
      english: "Taiwan Dollar",
    },
    {
      simplified: "填表",
      traditional: "填表",
      pinyin: "tián biǎo",
      english: "Fill out the form",
    },
    {
      simplified: "旅行支票",
      traditional: "旅行支票",
      pinyin: "lǚxíng zhīpiào",
      english: "Traveler's check",
    },
    {
      simplified: "約",
      traditional: "约",
      pinyin: "yuē",
      english: "Schedule appointment",
    },
    {
      simplified: "喂",
      traditional: "喂",
      pinyin: "wèi",
      english: "Hello",
    },
    {
      simplified: "打错了",
      traditional: "打錯了",
      pinyin: "dǎ cuòle",
      english: "Wrong number",
    },
    {
      simplified: "洗手间",
      traditional: "洗手間",
      pinyin: "xǐshǒujiān",
      english: "Restroom",
    },
    {
      simplified: "楼上",
      traditional: "樓上",
      pinyin: "lóu shàng",
      english: "Upstairs",
    },
    {
      simplified: "楼下",
      traditional: "樓下",
      pinyin: "lóu xià",
      english: "Downstairs",
    },
    {
      simplified: "公用电话",
      traditional: "公用電話",
      pinyin: "gōngyòng diànhuà",
      english: "Public telephone",
    },
    {
      simplified: "对面",
      traditional: "對面",
      pinyin: "duìmiàn",
      english: "Opposite",
    },
    {
      simplified: "百货公司",
      traditional: "百貨公司",
      pinyin: "bǎihuò gōngsī",
      english: "Department store",
    },
    {
      simplified: "皮鞋",
      traditional: "皮鞋",
      pinyin: "píxié",
      english: "Leather shoes",
    },
    {
      simplified: "爽",
      traditional: "爽",
      pinyin: "shuǎng",
      english: "Cool",
    },
    {
      simplified: "双",
      traditional: "雙",
      pinyin: "shuāng",
      english: "Double",
    },
    {
      simplified: "应该",
      traditional: "應該",
      pinyin: "yīnggāi",
      english: "Should",
    },
    {
      simplified: "路口",
      traditional: "路口",
      pinyin: "lùkǒu",
      english: "Intersection",
    },
    {
      simplified: "找",
      traditional: "找",
      pinyin: "zhǎo",
      english: "Find",
    },
    {
      simplified: "房子",
      traditional: "房子",
      pinyin: "fángzi",
      english: "House",
    },
    {
      simplified: "公寓",
      traditional: "公寓",
      pinyin: "gōngyù",
      english: "Apartment",
    },
    {
      simplified: "万",
      traditional: "萬",
      pinyin: "wàn",
      english: "Million",
    },
    {
      simplified: "日新百货公司",
      traditional: "日新百貨公司",
      pinyin: "rìxīn bǎihuò gōngsī",
      english: "Rixin Department Store",
    },
    {
      simplified: "怎么",
      traditional: "怎麼",
      pinyin: "zěnme",
      english: "How",
    },
    {
      simplified: "走",
      traditional: "走",
      pinyin: "zǒu",
      english: "Walk",
    },
    {
      simplified: "开车",
      traditional: "開車",
      pinyin: "kāichē",
      english: "Drive",
    },
    {
      simplified: "从",
      traditional: "從",
      pinyin: "cóng",
      english: "From",
    },
    {
      simplified: "东三街",
      traditional: "東三街",
      pinyin: "dōngsān jiē",
      english: "Dongsan Street",
    },
    {
      simplified: "往",
      traditional: "往",
      pinyin: "wǎng",
      english: "Toward",
    },
    {
      simplified: "南",
      traditional: "南",
      pinyin: "nán",
      english: "South",
    },
    {
      simplified: "北",
      traditional: "北",
      pinyin: "běi",
      english: "North",
    },
    {
      simplified: "西",
      traditional: "西",
      pinyin: "xī",
      english: "West",
    },
    {
      simplified: "东",
      traditional: "東",
      pinyin: "dōng",
      english: "East",
    },
    {
      simplified: "过",
      traditional: "過",
      pinyin: "guò",
      english: "Pass",
    },
    {
      simplified: "红绿灯",
      traditional: "紅綠燈",
      pinyin: "hónglǜdēng",
      english: "Traffic light",
    },
    {
      simplified: "火车站",
      traditional: "火車站",
      pinyin: "huǒchē zhàn",
      english: "Train station",
    },
    {
      simplified: "转",
      traditional: "轉",
      pinyin: "zhuǎn",
      english: "Turn",
    },
    {
      simplified: "分",
      traditional: "分",
      pinyin: "fēn",
      english: "Minute",
    },
    {
      simplified: "钟",
      traditional: "鐘",
      pinyin: "zhōng",
      english: "Clock",
    },
    {
      simplified: "小时",
      traditional: "小時",
      pinyin: "xiǎoshí",
      english: "Hour",
    },
    {
      simplified: "王",
      traditional: "王",
      pinyin: "Wáng",
      english: "Chinese family name",
    },
    {
      simplified: "房间",
      traditional: "房間",
      pinyin: "fángjiān",
      english: "Room",
    },
    {
      simplified: "出租",
      traditional: "出租",
      pinyin: "chūzū",
      english: "To rent",
    },
    {
      simplified: "房东",
      traditional: "房東",
      pinyin: "fángdōng",
      english: "Landlord",
    },
    {
      simplified: "学生",
      traditional: "學生",
      pinyin: "xuéshēng",
      english: "Student",
    },
    {
      simplified: "房租",
      traditional: "房租",
      pinyin: "fángzū",
      english: "Rent",
    },
    {
      simplified: "月",
      traditional: "月",
      pinyin: "yuè",
      english: "Month",
    },
    {
      simplified: "水电费",
      traditional: "水電費",
      pinyin: "shuǐdiànfèi",
      english: "Utility fee",
    },
    {
      simplified: "水费",
      traditional: "水費",
      pinyin: "shuǐfèi",
      english: "Water bill",
    },
    {
      simplified: "电费",
      traditional: "電費",
      pinyin: "diànfèi",
      english: "Electricity bill",
    },
    {
      simplified: "算",
      traditional: "算",
      pinyin: "suàn",
      english: "To count",
    },
    {
      simplified: "押金",
      traditional: "押金",
      pinyin: "yājīn",
      english: "Deposit",
    },
    {
      simplified: "家具",
      traditional: "家具",
      pinyin: "jiājù",
      english: "Furniture",
    },
    {
      simplified: "床",
      traditional: "床",
      pinyin: "chuáng",
      english: "Bed",
    },
    {
      simplified: "还",
      traditional: "還",
      pinyin: "hái",
      english: "In addition",
    },
    {
      simplified: "衣柜",
      traditional: "衣櫃",
      pinyin: "yīguì",
      english: "Closet, wardrobe",
    },
    {
      simplified: "放",
      traditional: "放",
      pinyin: "fàng",
      english: "To put",
    },
    {
      simplified: "衣服",
      traditional: "衣服",
      pinyin: "yīfú",
      english: "Clothes, dress",
    },
    {
      simplified: "跟",
      traditional: "跟",
      pinyin: "gēn",
      english: "With",
    },
    {
      simplified: "电视",
      traditional: "電視",
      pinyin: "diànshì",
      english: "TV set",
    },
    {
      simplified: "客厅",
      traditional: "客廳",
      pinyin: "kètīng",
      english: "Living room",
    },
    {
      simplified: "厨房",
      traditional: "廚房",
      pinyin: "chúfáng",
      english: "Kitchen",
    },
    {
      simplified: "洗澡间",
      traditional: "洗澡間",
      pinyin: "xǐzǎo jiān",
      english: "Bathroom",
    },
    {
      simplified: "洗澡",
      traditional: "洗澡",
      pinyin: "xǐzǎo",
      english: "To take a shower or bath",
    },
    {
      simplified: "秋天",
      traditional: "秋天",
      pinyin: "Qiūtiān",
      english: "Fall",
    },
    {
      simplified: "学期",
      traditional: "學期",
      pinyin: "xuéqí",
      english: "Semester",
    },
    {
      simplified: "考试",
      traditional: "考試",
      pinyin: "kǎoshì",
      english: "Examination",
    },
    {
      simplified: "结果",
      traditional: "結果",
      pinyin: "jiéguǒ",
      english: "Result",
    },
    {
      simplified: "办法",
      traditional: "辦法",
      pinyin: "bànfǎ",
      english: "Method",
    },
    {
      simplified: "搬家",
      traditional: "搬家",
      pinyin: "bānjiā",
      english: "Move",
    },
    {
      simplified: "决定",
      traditional: "決定",
      pinyin: "juédìng",
      english: "Decide",
    },
    {
      simplified: "容易",
      traditional: "容易",
      pinyin: "róngyì",
      english: "Easy",
    },
    {
      simplified: "别的",
      traditional: "別的",
      pinyin: "bié de",
      english: "Other",
    },
    {
      simplified: "远",
      traditional: "遠",
      pinyin: "Yuǎn",
      english: "Far",
    },
    {
      simplified: "近",
      traditional: "近",
      pinyin: "Jìn",
      english: "Near",
    },
    {
      simplified: "这样",
      traditional: "這樣",
      pinyin: "Zhèyàng",
      english: "Such",
    },
    {
      simplified: "住",
      traditional: "住",
      pinyin: "Zhù",
      english: "Live",
    },
    {
      simplified: "搬",
      traditional: "搬",
      pinyin: "Bān",
      english: "Move",
    },
    {
      simplified: "只",
      traditional: "只",
      pinyin: "Zhǐ",
      english: "Only",
    },
    {
      simplified: "办",
      traditional: "辦",
      pinyin: "Bàn",
      english: "To handle, manage",
    },
    {
      simplified: "房客",
      traditional: "房客",
      pinyin: "Fángkè",
      english: "Tenant",
    },
    {
      simplified: "拿回去",
      traditional: "拿回去",
      pinyin: "Náhuíqù",
      english: "Take it back",
    },
    {
      simplified: "每",
      traditional: "每",
      pinyin: "Měi",
      english: "Each, every",
    },
    {
      simplified: "下雨",
      traditional: "下雨",
      pinyin: "Xià yǔ",
      english: "Rain",
    },
    {
      simplified: "办法",
      traditional: "辦法",
      pinyin: "Bànfǎ",
      english: "Method, way",
    },
    {
      simplified: "帮",
      traditional: "幫",
      pinyin: "Bāng",
      english: "Help",
    },
    {
      simplified: "麻烦",
      traditional: "麻煩",
      pinyin: "Máfan",
      english: "To be troublesome",
    },
    {
      simplified: "地方",
      traditional: "地方",
      pinyin: "dìfāng",
      english: "Place",
    },
    {
      simplified: "些",
      traditional: "些",
      pinyin: "xiē",
      english: "Some, several",
    },
    {
      simplified: "问题",
      traditional: "問題",
      pinyin: "wèntí",
      english: "Problem, question",
    },
    {
      simplified: "跟",
      traditional: "跟",
      pinyin: "gēn",
      english: "With",
    },
    {
      simplified: "交朋友",
      traditional: "交朋友",
      pinyin: "jiāo péngyǒu",
      english: "To Make friends",
    },
    {
      simplified: "怕",
      traditional: "怕",
      pinyin: "pà",
      english: "To fear",
    },
    {
      simplified: "吵",
      traditional: "吵",
      pinyin: "chǎo",
      english: "to be noisy, to annoy",
    },
    {
      simplified: "睡觉",
      traditional: "睡覺",
      pinyin: "shuìjiào",
      english: "Go to sleep",
    },
    {
      simplified: "洗衣机",
      traditional: "洗衣機",
      pinyin: "xǐyījī",
      english: "Washing machine",
    },
    {
      simplified: "对方付费",
      traditional: "對方付費",
      pinyin: "duìfāng fùfèi",
      english: "Collect",
    },
    {
      simplified: "对方",
      traditional: "對方",
      pinyin: "duìfāng",
      english: "Other party",
    },
    {
      simplified: "长途",
      traditional: "長途",
      pinyin: "chángtú",
      english: "Long distance",
    },
    {
      simplified: "嗯",
      traditional: "嗯",
      pinyin: "ń",
      english: "Affirmation particle",
    },
    {
      simplified: "李红",
      traditional: "李紅",
      pinyin: "Lǐ Hóng",
      english: "Li Hong Chinese name",
    },
    {
      simplified: "赵奇",
      traditional: "趙奇",
      pinyin: "Zhào Qí",
      english: "Zhao Qi Chinese name",
    },
    {
      simplified: "奇怪",
      traditional: "奇怪",
      pinyin: "qíguài",
      english: "Strange",
    },
    {
      simplified: "好几",
      traditional: "好幾",
      pinyin: "hǎojǐ",
      english: "Many, several",
    },
    {
      simplified: "次",
      traditional: "次",
      pinyin: "cì",
      english: "A time, occasion",
    },
    {
      simplified: "捷",
      traditional: "捷",
      pinyin: "jié",
      english: "To answer the phone",
    },
    {
      simplified: "办公室",
      traditional: "辦公室",
      pinyin: "bàngōngshì",
      english: "Office",
    },
    {
      simplified: "希望",
      traditional: "希望",
      pinyin: "xīwàng",
      english: "Hope",
    },
    {
      simplified: "大千公司",
      traditional: "大千公司",
      pinyin: "Dàqiān Gōngsī",
      english: "Daqian Company",
    },
    {
      simplified: "转",
      traditional: "轉",
      pinyin: "zhuǎn",
      english: "To pass on, to transfer",
    },
    {
      simplified: "稍等",
      traditional: "稍等",
      pinyin: "shāo děng",
      english: "Wait a moment",
    },
    {
      simplified: "听",
      traditional: "聽",
      pinyin: "tīng",
      english: "Listen",
    },
    {
      simplified: "进来",
      traditional: "進來",
      pinyin: "jìnlái",
      english: "Come in",
    },
    {
      simplified: "留话",
      traditional: "留話",
      pinyin: "liú huà",
      english: "Leave a message",
    },
    {
      simplified: "留",
      traditional: "留",
      pinyin: "liú",
      english: "To leave, to keep",
    },
    {
      simplified: "下班",
      traditional: "下班",
      pinyin: "xiàbān",
      english: "Off work",
    },
    {
      simplified: "上班",
      traditional: "上班",
      pinyin: "shàngbān",
      english: "Go to work",
    },
    {
      simplified: "以前",
      traditional: "以前",
      pinyin: "yǐqián",
      english: "Before",
    },
    {
      simplified: "以后",
      traditional: "以後",
      pinyin: "yǐhòu",
      english: "After",
    },
    {
      simplified: "回电",
      traditional: "回電",
      pinyin: "huí diàn",
      english: "Call back",
    },
    {
      simplified: "自己",
      traditional: "自己",
      pinyin: "zìjǐ",
      english: "Oneself",
    },
    {
      simplified: "试",
      traditional: "試",
      pinyin: "shì",
      english: "to try",
    },
    {
      simplified: "话",
      traditional: "話",
      pinyin: "huà",
      english: "Word",
    },
  ],
};

export default lesson;
