import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "asklqpos84",
  type: "Far East",
  locked: false,
  title: "Far East Lesson 10",
  content: [
    {
      traditional: "寄",
      simplified: "寄",
      pinyin: "jì",
      english: "Send",
    },
    {
      traditional: "信",
      simplified: "信",
      pinyin: "xìn",
      english: "Letter",
    },
    {
      traditional: "航空信",
      simplified: "航空信",
      pinyin: "háng kōng xìn",
      english: "Airmail",
    },
    {
      traditional: "貼",
      simplified: "贴",
      pinyin: "tiē",
      english: "Paste",
    },
    {
      traditional: "超重郵票",
      simplified: "超重邮票",
      pinyin: "chāo zhòng yóu piào",
      english: "Overweight stamp",
    },
    {
      traditional: "重",
      simplified: "重",
      pinyin: "zhòng",
      english: "Weight",
    },
    {
      traditional: "輕",
      simplified: "轻",
      pinyin: "qīng",
      english: "Light",
    },
    {
      traditional: "的話",
      simplified: "的话",
      pinyin: "dē huà",
      english: "If",
    },
    {
      traditional: "公克",
      simplified: "公克",
      pinyin: "gōng kè",
      english: "Gram",
    },
    {
      traditional: "加",
      simplified: "加",
      pinyin: "jiā",
      english: "Plus",
    },
    {
      traditional: "快",
      simplified: "快",
      pinyin: "kuài",
      english: "Fast",
    },
    {
      traditional: "就",
      simplified: "就",
      pinyin: "jiù",
      english: "On",
    },
    {
      traditional: "慢",
      simplified: "慢",
      pinyin: "màn",
      english: "Slow",
    },
    {
      traditional: "才",
      simplified: "才",
      pinyin: "cái",
      english: "Only",
    },
    {
      traditional: "封",
      simplified: "封",
      pinyin: "fēng",
      english: "Seal",
    },
    {
      traditional: "忘了",
      simplified: "忘了",
      pinyin: "wàng le",
      english: "Forget",
    },
    {
      traditional: "寫",
      simplified: "写",
      pinyin: "xiě",
      english: "Write",
    },
    {
      traditional: "地址",
      simplified: "地址",
      pinyin: "dì zhǐ",
      english: "Address",
    },
    {
      traditional: "名字",
      simplified: "名字",
      pinyin: "míng zì",
      english: "First name",
    },
    {
      traditional: "告訴",
      simplified: "告诉",
      pinyin: "gào sù",
      english: "Tell",
    },
    {
      traditional: "明信片",
      simplified: "明信片",
      pinyin: "míng xìn piàn",
      english: "Postcard",
    },
    {
      traditional: "掛號信",
      simplified: "挂号信",
      pinyin: "guà hào xìn",
      english: "Registered letter",
    },
    {
      traditional: "信封",
      simplified: "信封",
      pinyin: "xìn fēng",
      english: "Envelope",
    },
    {
      traditional: "領",
      simplified: "领",
      pinyin: "lǐng",
      english: "Collar",
    },
    {
      traditional: "包裹",
      simplified: "包裹",
      pinyin: "bāo guǒ",
      english: "Package",
    },
    {
      traditional: "窗口",
      simplified: "窗口",
      pinyin: "chuāng kǒu",
      english: "Window",
    },
    {
      traditional: "窗子",
      simplified: "窗子",
      pinyin: "chuāng zi",
      english: "Window",
    },
    {
      traditional: "門口",
      simplified: "门口",
      pinyin: "mén kǒu",
      english: "Doorway",
    },
    {
      traditional: "通知單",
      simplified: "通知单",
      pinyin: "tōng zhī dān",
      english: "Notice",
    },
    {
      traditional: "通知",
      simplified: "通知",
      pinyin: "tōng zhī",
      english: "Notice",
    },
    {
      traditional: "單字",
      simplified: "单字",
      pinyin: "dān zì",
      english: "Single word",
    },
    {
      traditional: "身分證",
      simplified: "身分证",
      pinyin: "shēn fèn zhèng",
      english: "Identity card",
    },
    {
      traditional: "圖章",
      simplified: "图章",
      pinyin: "tú zhāng",
      english: "Stamp",
    },
    {
      traditional: "帶",
      simplified: "带",
      pinyin: "dài",
      english: "Band",
    },
    {
      traditional: "簽名",
      simplified: "签名",
      pinyin: "qiān míng",
      english: "Signature",
    },
    {
      traditional: "旅行社",
      simplified: "旅行社",
      pinyin: "lǚ xíng shè",
      english: "Travel agency",
    },
    {
      traditional: "影本",
      simplified: "影本",
      pinyin: "yǐng běn",
      english: "Copy",
    },
    {
      traditional: "送",
      simplified: "送",
      pinyin: "sòng",
      english: "Give away",
    },
    {
      traditional: "傳真",
      simplified: "传真",
      pinyin: "chuán zhēn",
      english: "Fax",
    },
    {
      traditional: "傳真機",
      simplified: "传真机",
      pinyin: "chuán zhēn jī",
      english: "Fax machine",
    },
    {
      traditional: "哎呀",
      simplified: "哎呀",
      pinyin: "āi yā",
      english: "Damn",
    },
    {
      traditional: "壞了",
      simplified: "坏了",
      pinyin: "huài le",
      english: "Broken",
    },
    {
      traditional: "壞",
      simplified: "坏",
      pinyin: "huài",
      english: "Bad",
    },
    {
      traditional: "沒關係",
      simplified: "没关系",
      pinyin: "méi guān xì",
      english: "It's ok",
    },
    {
      traditional: "關係",
      simplified: "关系",
      pinyin: "guān xì",
      english: "Relationship",
    },
    {
      traditional: "郵局",
      simplified: "邮局",
      pinyin: "yóu jú",
      english: "Post office",
    },
    {
      traditional: "費用",
      simplified: "费用",
      pinyin: "fèi yòng",
      english: "Cost",
    },
    {
      traditional: "市區",
      simplified: "市区",
      pinyin: "shì qū",
      english: "Urban area",
    },
    {
      traditional: "別的",
      simplified: "别的",
      pinyin: "bié dē",
      english: "Other",
    },
    {
      traditional: "台中",
      simplified: "台中",
      pinyin: "tái zhōng",
      english: "Taichung",
    },
  ],
};

export default lesson;
