import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "aisLEqpSre",
  type: "General Vocabulary",
  locked: false,
  title: "Restaurant Menus",
  content: [
    {
      traditional: "花生醬",
      simplified: "花生酱",
      pinyin: "huā shēng jiàng",
      english: "Peanut butter",
    },
    {
      traditional: "雞腿",
      simplified: "鸡腿",
      pinyin: "jī tuǐ",
      english: "Chicken leg",
    },
    {
      traditional: "堡",
      simplified: "堡",
      pinyin: "bǎo",
      english: '"Burger"',
    },
    {
      traditional: "吐司",
      simplified: "吐司",
      pinyin: "tǔ sī",
      english: "Toast",
    },
    {
      traditional: "蛋",
      simplified: "蛋",
      pinyin: "dàn",
      english: "Egg",
    },
    {
      traditional: "原味",
      simplified: "原味",
      pinyin: "yuán wèi",
      english: "Original flavor",
    },
    {
      traditional: "辣味",
      simplified: "辣味",
      pinyin: "là wèi",
      english: "Spicy",
    },
    {
      traditional: "美生菜",
      simplified: "美生菜",
      pinyin: "měi shēng cài",
      english: "Lettuce",
    },
    {
      traditional: "絲",
      simplified: "丝",
      pinyin: "sī",
      english: "Shreds",
    },
    {
      traditional: "洋蔥",
      simplified: "洋葱",
      pinyin: "yáng cōng",
      english: "Onion",
    },
    {
      traditional: "番茄",
      simplified: "番茄",
      pinyin: "fān qié",
      english: "Tomato",
    },
    {
      traditional: "片",
      simplified: "片",
      pinyin: "piàn",
      english: "Sheet (slices)",
    },
    {
      traditional: "鐵板",
      simplified: "铁板",
      pinyin: "tiě bǎn",
      english: "Iron plate",
    },
    {
      traditional: "蘑菇",
      simplified: "蘑菇",
      pinyin: "mó gū",
      english: "Mushroom",
    },
    {
      traditional: "黑胡椒",
      simplified: "黑胡椒",
      pinyin: "hēi hú jiāo",
      english: "Black pepper",
    },
    {
      traditional: "燒",
      simplified: "烧",
      pinyin: "shāo",
      english: "Burn",
    },
    {
      traditional: "里肌肉",
      simplified: "里肌肉",
      pinyin: "lǐ jī ròu",
      english: "Inner muscles (pork loin)",
    },
    {
      traditional: "奶油",
      simplified: "奶油",
      pinyin: "nǎi yóu",
      english: "Cream",
    },
    {
      traditional: "白醬",
      simplified: "白酱",
      pinyin: "bái jiàng",
      english: "White sauce",
    },
    {
      traditional: "肉醬",
      simplified: "肉酱",
      pinyin: "ròu jiàng",
      english: "Meat sauce",
    },
    {
      traditional: "宮保雞丁",
      simplified: "宫保鸡丁",
      pinyin: "gōng bǎo jī dīng",
      english: "Kung pao chicken",
    },
    {
      traditional: "義大利",
      simplified: "义大利",
      pinyin: "yì dà lì",
      english: "Italy",
    },
    {
      traditional: "咖哩",
      simplified: "咖喱",
      pinyin: "kā li",
      english: "Curry",
    },
    {
      traditional: "九層塔",
      simplified: "九层塔",
      pinyin: "jiǔ céng tǎ",
      english: "Basil",
    },
    {
      traditional: "塔",
      simplified: "塔",
      pinyin: "tǎ",
      english: "Tower (basil)",
    },
    {
      traditional: "蘿蔔糕",
      simplified: "萝卜糕",
      pinyin: "luó bó gāo",
      english: "Fried radish cake",
    },
    {
      traditional: "起司",
      simplified: "起司",
      pinyin: "qǐ sī",
      english: "Cheese",
    },
    {
      traditional: "玉米",
      simplified: "玉米",
      pinyin: "yù mǐ",
      english: "Corn",
    },
    {
      traditional: "肉鬆",
      simplified: "肉松",
      pinyin: "ròu sōng",
      english: "Pork floss",
    },
    {
      traditional: "火腿",
      simplified: "火腿",
      pinyin: "huǒ tuǐ",
      english: "Ham",
    },
    {
      traditional: "蔥",
      simplified: "葱",
      pinyin: "cōng",
      english: "Scallion/green onion",
    },
    {
      traditional: "薯餅",
      simplified: "薯饼",
      pinyin: "shǔ bǐng",
      english: "Potato cake (hash brown)",
    },
    {
      traditional: "脆",
      simplified: "脆",
      pinyin: "cuì",
      english: "Crispy/Crunchy",
    },
    {
      traditional: "藷",
      simplified: "薯",
      pinyin: "shǔ",
      english: "Yam",
    },
    {
      traditional: "甜不辣",
      simplified: "甜不辣",
      pinyin: "tián bù là",
      english: "Sweet or not spicy (tempura)",
    },
    {
      traditional: "豬排",
      simplified: "猪排",
      pinyin: "zhū pái",
      english: "Pork chops",
    },
    {
      traditional: "大腸",
      simplified: "大肠",
      pinyin: "dà cháng",
      english: "The large intestine",
    },
    {
      traditional: "醋",
      simplified: "醋",
      pinyin: "cù",
      english: "Vinegar",
    },
    {
      traditional: "蒜",
      simplified: "蒜",
      pinyin: "suàn",
      english: "Garlic",
    },
    {
      traditional: "香菜",
      simplified: "香菜",
      pinyin: "xiāng cài",
      english: "Parsley",
    },
    {
      traditional: "土司",
      simplified: "土司",
      pinyin: "tǔ sī",
      english: "Toast",
    },
    {
      traditional: "草莓",
      simplified: "草莓",
      pinyin: "cǎo méi",
      english: "Strawberry",
    },
    {
      traditional: "巧克力",
      simplified: "巧克力",
      pinyin: "qiǎo kè lì",
      english: "Chocolate",
    },
    {
      traditional: "炸雞",
      simplified: "炸鸡",
      pinyin: "zhà jī",
      english: "Fried chicken",
    },
    {
      traditional: "切",
      simplified: "切",
      pinyin: "qiè",
      english: "Cut",
    },
    {
      traditional: "總匯三明治",
      simplified: "总汇三明治",
      pinyin: "zǒng huì sān míng zhì",
      english: "General sandwich",
    },
    {
      traditional: "美乃滋",
      simplified: "美乃滋",
      pinyin: "měi nǎi zī",
      english: "Mayonnaise",
    },
    {
      traditional: "番茄醬",
      simplified: "番茄酱",
      pinyin: "fān qié jiàng",
      english: "Ketchup",
    },
    {
      traditional: "黃芥末醬",
      simplified: "黄芥末酱",
      pinyin: "huáng jiè mò jiàng",
      english: "Yellow mustard sauce",
    },
    {
      traditional: "美生菜",
      simplified: "美生菜",
      pinyin: "měi shēng cài",
      english: "Lettuce",
    },
    {
      traditional: "高麗菜絲",
      simplified: "高丽菜丝",
      pinyin: "gāo lì cài sī",
      english: "Cabbage",
    },
    {
      traditional: "洋蔥",
      simplified: "洋葱",
      pinyin: "yáng cōng",
      english: "Onion",
    },
    {
      traditional: "番茄片",
      simplified: "番茄片",
      pinyin: "fān qié piàn",
      english: "Tomato slices",
    },
    {
      traditional: "肉鬆",
      simplified: "肉松",
      pinyin: "ròu sōng",
      english: "Pork floss",
    },
    {
      traditional: "火腿",
      simplified: "火腿",
      pinyin: "huǒ tuǐ",
      english: "Ham",
    },
    {
      traditional: "咔啦雞腿總匯三明治",
      simplified: "咔啦鸡腿总汇三明治",
      pinyin: "kā la jī tuǐ zǒng huì sān míng zhì",
      english: "Kala chicken drumsticks sandwich",
    },
    {
      traditional: "招牌鮪魚",
      simplified: "招牌鲔鱼",
      pinyin: "zhāo pái wěi yú",
      english: "Signature tuna",
    },
    {
      traditional: "香雞總匯三明治",
      simplified: "香鸡总汇三明治",
      pinyin: "xiāng jī zǒng huì sān míng zhì",
      english: "Fragrant chicken sandwich",
    },
    {
      traditional: "養生蔬食總匯三明治(地瓜/芋泥/蔓越莓)",
      simplified: "养生蔬食总汇三明治(地瓜/芋泥/蔓越莓)",
      pinyin:
        "yǎng shēng shū shí zǒng huì sān míng zhì dì guā yù ní màn yuè méi",
      english: "Healthy veggie sandwich (sweet potatoes/taro puree/cranberry)",
    },
    {
      traditional: "花生培根乳酪",
      simplified: "花生培根乳酪",
      pinyin: "huā shēng péi gēn rǔ lào",
      english: "Peanut bacon cheese",
    },
    {
      traditional: "燒肉里肌乳酪",
      simplified: "烧肉里肌乳酪",
      pinyin: "shāo ròu lǐ jī rǔ lào",
      english: "Roasted meat with yogurt",
    },
    {
      traditional: "火雞嫩蛋乳酪",
      simplified: "火鸡嫩蛋乳酪",
      pinyin: "huǒ jī nèn dàn rǔ lào",
      english: "Turkey soft egg cheese",
    },
    {
      traditional: "吐司/厚片",
      simplified: "吐司/厚片",
      pinyin: "tǔ sī hòu piàn",
      english: "Toast/thick slices",
    },
    {
      traditional: "奶油",
      simplified: "奶油",
      pinyin: "nǎi yóu",
      english: "Cream",
    },
    {
      traditional: "草莓",
      simplified: "草莓",
      pinyin: "cǎo méi",
      english: "Strawberry",
    },
    {
      traditional: "巧克力",
      simplified: "巧克力",
      pinyin: "qiǎo kè lì",
      english: "Chocolate",
    },
    {
      traditional: "奶酥",
      simplified: "奶酥",
      pinyin: "nǎi sū",
      english: "Soufflé",
    },
    {
      traditional: "芋頭",
      simplified: "芋头",
      pinyin: "yù tóu",
      english: "Taro",
    },
    {
      traditional: "顆粒花生",
      simplified: "颗粒花生",
      pinyin: "kē lì huā shēng",
      english: "Granulated peanuts",
    },
    {
      traditional: "奶酥蔓越莓",
      simplified: "奶酥蔓越莓",
      pinyin: "nǎi sū màn yuè méi",
      english: "Soufflé cranberry",
    },
    {
      traditional: "蛋餅/蔥油餅",
      simplified: "蛋饼/葱油饼",
      pinyin: "dàn bǐng cōng yóu bǐng",
      english: "Quiche/scallion pancake",
    },
    {
      traditional: "豬排",
      simplified: "猪排",
      pinyin: "zhū pái",
      english: "Pork chops",
    },
    {
      traditional: "地瓜",
      simplified: "地瓜",
      pinyin: "dì guā",
      english: "Sweet potato",
    },
    {
      traditional: "培根",
      simplified: "培根",
      pinyin: "péi gēn",
      english: "Bacon",
    },
    {
      traditional: "薯餅",
      simplified: "薯饼",
      pinyin: "shǔ bǐng",
      english: "Potato cake",
    },
    {
      traditional: "德國香腸起司",
      simplified: "德国香肠起司",
      pinyin: "dé guó xiāng cháng qǐ sī",
      english: "German sausage cheese",
    },
    {
      traditional: "熱狗",
      simplified: "热狗",
      pinyin: "rè gǒu",
      english: "Hot dog",
    },
    {
      traditional: "蔬菜",
      simplified: "蔬菜",
      pinyin: "shū cài",
      english: "Vegetables",
    },
    {
      traditional: "起司",
      simplified: "起司",
      pinyin: "qǐ sī",
      english: "Cheese",
    },
    {
      traditional: "玉米",
      simplified: "玉米",
      pinyin: "yù mǐ",
      english: "Corn",
    },
    {
      traditional: "肉鬆",
      simplified: "肉松",
      pinyin: "ròu sōng",
      english: "Pork floss",
    },
    {
      traditional: "火腿",
      simplified: "火腿",
      pinyin: "huǒ tuǐ",
      english: "Ham",
    },
    {
      traditional: "香蔥",
      simplified: "香葱",
      pinyin: "xiāng cōng",
      english: "Chives",
    },
    {
      traditional: "原味",
      simplified: "原味",
      pinyin: "yuán wèi",
      english: "Original",
    },
    {
      traditional: "特濃鮮奶茶",
      simplified: "特浓鲜奶茶",
      pinyin: "tè nóng xiān nǎi chá",
      english: "Extra concentrated fresh milk tea",
    },
    {
      traditional: "招牌紅茶",
      simplified: "招牌红茶",
      pinyin: "zhāo pái hóng chá",
      english: "Signature black tea",
    },
    {
      traditional: "豆漿紅腸",
      simplified: "豆浆红肠",
      pinyin: "dòu jiāng hóng cháng",
      english: "Soy milk red sausage",
    },
    {
      traditional: "招牌奶茶",
      simplified: "招牌奶茶",
      pinyin: "zhāo pái nǎi chá",
      english: "Signature milk tea",
    },
    {
      traditional: "鮮奶茶",
      simplified: "鲜奶茶",
      pinyin: "xiān nǎi chá",
      english: "Fresh milk tea",
    },
    {
      traditional: "特濃鮮奶茶",
      simplified: "特浓鲜奶茶",
      pinyin: "tè nóng xiān nǎi chá",
      english: "Extra concentrated fresh milk tea",
    },
    {
      traditional: "晨霧青茶",
      simplified: "晨雾青茶",
      pinyin: "chén wù qīng chá",
      english: "Morning mist green tea",
    },
    {
      traditional: "蜂蜜 紅/青茶",
      simplified: "蜂蜜 红/青茶",
      pinyin: "fēng mì hóng qīng chá",
      english: "Honey red/green tea",
    },
    {
      traditional: "檸檬 紅/青茶",
      simplified: "柠檬 红/青茶",
      pinyin: "níng méng hóng qīng chá",
      english: "Lemon red/green tea",
    },
    {
      traditional: "金桔檸檬",
      simplified: "金桔柠檬",
      pinyin: "jīn jú níng méng",
      english: "Kumquat lemon",
    },
    {
      traditional: "鴛鴦奶茶",
      simplified: "鸳鸯奶茶",
      pinyin: "yuān yāng nǎi chá",
      english: "Mandarin duck milk tea",
    },
    {
      traditional: "養樂多青茶",
      simplified: "养乐多青茶",
      pinyin: "yǎng lè duō qīng chá",
      english: "Yakult green tea",
    },
    {
      traditional: "黑糖撞奶",
      simplified: "黑糖撞奶",
      pinyin: "hēi táng zhuàng nǎi",
      english: "Brown sugar hit milk",
    },
    {
      traditional: "橙又青(季節品)",
      simplified: "橙又青(季节品)",
      pinyin: "chéng yòu qīng jì jié pǐn",
      english: "Orange and green (seasonal product)",
    },
    {
      traditional: "葡萄柚青茶(季節品)",
      simplified: "葡萄柚青茶(季节品)",
      pinyin: "pú táo yòu qīng chá jì jié pǐn",
      english: "Grapefruit green tea (seasonal)",
    },
    {
      traditional: "美式咖啡",
      simplified: "美式咖啡",
      pinyin: "měi shì kā fēi",
      english: "American coffee",
    },
    {
      traditional: "特調咖啡",
      simplified: "特调咖啡",
      pinyin: "tè diào kā fēi",
      english: "Special coffee",
    },
    {
      traditional: "拿鐵咖啡",
      simplified: "拿铁咖啡",
      pinyin: "ná tiě kā fēi",
      english: "Latte",
    },
    {
      traditional: "香蕉牛奶",
      simplified: "香蕉牛奶",
      pinyin: "xiāng jiāo niú nǎi",
      english: "Banana milk",
    },
    {
      traditional: "地瓜豆漿",
      simplified: "地瓜豆浆",
      pinyin: "dì guā dòu jiāng",
      english: "Sweet potato soy milk",
    },
    {
      traditional: "柳橙原汁",
      simplified: "柳橙原汁",
      pinyin: "liǔ chéng yuán zhī",
      english: "Orange juice",
    },
    {
      traditional: "酪梨牛奶",
      simplified: "酪梨牛奶",
      pinyin: "lào lí niú nǎi",
      english: "Avocado milk",
    },
    {
      traditional: "酪梨牛奶布丁",
      simplified: "酪梨牛奶布丁",
      pinyin: "lào lí niú nǎi bù dīng",
      english: "Avocado milk pudding",
    },
    {
      traditional: "原味豆漿/無糖豆漿/薏仁漿",
      simplified: "原味豆浆/无糖豆浆/薏仁浆",
      pinyin: "yuán wèi dòu jiāng wú táng dòu jiāng yì rén jiāng",
      english: "Original soy milk/sugar-free soy milk/coix seed milk",
    },
    {
      traditional: "杏仁漿",
      simplified: "杏仁浆",
      pinyin: "xìng rén jiāng",
      english: "Almond milk",
    },
    {
      traditional: "總匯",
      simplified: "总汇",
      pinyin: "zǒng huì",
      english: "Confluence",
    },
    {
      traditional: "三明治",
      simplified: "三明治",
      pinyin: "sān míng zhì",
      english: "Sandwich",
    },
    {
      traditional: "美乃滋",
      simplified: "美乃滋",
      pinyin: "měi nǎi zī",
      english: "Mayonnaise",
    },
    {
      traditional: "番茄醬",
      simplified: "番茄酱",
      pinyin: "fān qié jiàng",
      english: "Ketchup",
    },
    {
      traditional: "黃芥末醬",
      simplified: "黄芥末酱",
      pinyin: "huáng jiè mò jiàng",
      english: "Yellow mustard sauce",
    },
    {
      traditional: "芥末",
      simplified: "芥末",
      pinyin: "jiè mò",
      english: "Mustard",
    },
    {
      traditional: "招牌",
      simplified: "招牌",
      pinyin: "zhāo pái",
      english: "Sign",
    },
    {
      traditional: "鮪魚",
      simplified: "鲔鱼",
      pinyin: "wěi yú",
      english: "Tuna",
    },
    {
      traditional: "養生",
      simplified: "养生",
      pinyin: "yǎng shēng",
      english: "Keep in good health",
    },
    {
      traditional: "蔬食",
      simplified: "蔬食",
      pinyin: "shū shí",
      english: "Vegetable food",
    },
    {
      traditional: "地瓜",
      simplified: "地瓜",
      pinyin: "dì guā",
      english: "Sweet potato",
    },
    {
      traditional: "芋泥",
      simplified: "芋泥",
      pinyin: "yù ní",
      english: "Mashed taro",
    },
    {
      traditional: "蔓越莓",
      simplified: "蔓越莓",
      pinyin: "màn yuè méi",
      english: "Cranberry",
    },
    {
      traditional: "培根",
      simplified: "培根",
      pinyin: "péi gēn",
      english: "Bacon",
    },
    {
      traditional: "乳酪",
      simplified: "乳酪",
      pinyin: "rǔ lào",
      english: "Cheese",
    },
    {
      traditional: "火雞",
      simplified: "火鸡",
      pinyin: "huǒ jī",
      english: "Turkey",
    },
    {
      traditional: "嫩",
      simplified: "嫩",
      pinyin: "nèn",
      english: "Tender",
    },
    {
      traditional: "厚片",
      simplified: "厚片",
      pinyin: "hòu piàn",
      english: "Thick slices",
    },
    {
      traditional: "奶油",
      simplified: "奶油",
      pinyin: "nǎi yóu",
      english: "Cream",
    },
    {
      traditional: "奶酥",
      simplified: "奶酥",
      pinyin: "nǎi sū",
      english: "Soufflé",
    },
    {
      traditional: "芋頭",
      simplified: "芋头",
      pinyin: "yù tóu",
      english: "Taro",
    },
    {
      traditional: "顆粒",
      simplified: "颗粒",
      pinyin: "kē lì",
      english: "Granule",
    },
    {
      traditional: "蔥油餅",
      simplified: "葱油饼",
      pinyin: "cōng yóu bǐng",
      english: "Scallion pancakes",
    },
    {
      traditional: "豬排",
      simplified: "猪排",
      pinyin: "zhū pái",
      english: "Pork chops",
    },
    {
      traditional: "薯餅",
      simplified: "薯饼",
      pinyin: "shǔ bǐng",
      english: "Potato cake",
    },
    {
      traditional: "德國",
      simplified: "德国",
      pinyin: "dé guó",
      english: "Germany",
    },
    {
      traditional: "香腸",
      simplified: "香肠",
      pinyin: "xiāng cháng",
      english: "Sausage",
    },
    {
      traditional: "起司",
      simplified: "起司",
      pinyin: "qǐ sī",
      english: "Cheese",
    },
    {
      traditional: "熱狗",
      simplified: "热狗",
      pinyin: "rè gǒu",
      english: "Hot dog",
    },
    {
      traditional: "玉米",
      simplified: "玉米",
      pinyin: "yù mǐ",
      english: "Corn",
    },
    {
      traditional: "飲品",
      simplified: "饮品",
      pinyin: "yǐn pǐn",
      english: "Drink",
    },
    {
      traditional: "特",
      simplified: "特",
      pinyin: "tè",
      english: "Special",
    },
    {
      traditional: "濃",
      simplified: "浓",
      pinyin: "nóng",
      english: "Concentrated",
    },
    {
      traditional: "奶茶",
      simplified: "奶茶",
      pinyin: "nǎi chá",
      english: "Milk tea",
    },
    {
      traditional: "豆漿",
      simplified: "豆浆",
      pinyin: "dòu jiāng",
      english: "Soy milk",
    },
    {
      traditional: "青茶",
      simplified: "青茶",
      pinyin: "qīng chá",
      english: "Green tea",
    },
    {
      traditional: "蜂蜜",
      simplified: "蜂蜜",
      pinyin: "fēng mì",
      english: "Honey",
    },
    {
      traditional: "檸檬",
      simplified: "柠檬",
      pinyin: "níng méng",
      english: "Lemon",
    },
    {
      traditional: "金桔",
      simplified: "金桔",
      pinyin: "jīn jú",
      english: "Kumquat",
    },
    {
      traditional: "鴛鴦奶茶",
      simplified: "鸳鸯奶茶",
      pinyin: "yuān yāng nǎi chá",
      english: "Mandarin duck milk tea",
    },
    {
      traditional: "養樂多",
      simplified: "养乐多",
      pinyin: "yǎng lè duō",
      english: "Yakult",
    },
    {
      traditional: "黑糖",
      simplified: "黑糖",
      pinyin: "hēi táng",
      english: "Brown sugar",
    },
    {
      traditional: "撞奶=奶茶",
      simplified: "撞奶=奶茶",
      pinyin: "zhuàng nǎi nǎi chá",
      english: "Bumping milk = milk tea",
    },
    {
      traditional: "橙",
      simplified: "橙",
      pinyin: "chéng",
      english: "Orange",
    },
    {
      traditional: "季節",
      simplified: "季节",
      pinyin: "jì jié",
      english: "Season",
    },
    {
      traditional: "品",
      simplified: "品",
      pinyin: "pǐn",
      english: "Product",
    },
    {
      traditional: "葡萄柚",
      simplified: "葡萄柚",
      pinyin: "pú táo yòu",
      english: "Grapefruit",
    },
    {
      traditional: "特調",
      simplified: "特调",
      pinyin: "tè diào",
      english: "Special blend/House blend",
    },
    {
      traditional: "拿鐵咖啡",
      simplified: "拿铁咖啡",
      pinyin: "ná tiě kā fēi",
      english: "Latte",
    },
    {
      traditional: "香蕉",
      simplified: "香蕉",
      pinyin: "xiāng jiāo",
      english: "Banana",
    },
    {
      traditional: "柳橙",
      simplified: "柳橙",
      pinyin: "liǔ chéng",
      english: "Oranges",
    },
    {
      traditional: "原汁",
      simplified: "原汁",
      pinyin: "yuán zhī",
      english: "Raw juice",
    },
    {
      traditional: "酪梨",
      simplified: "酪梨",
      pinyin: "lào lí",
      english: "Avocado",
    },
    {
      traditional: "布丁",
      simplified: "布丁",
      pinyin: "bù dīng",
      english: "Pudding",
    },
    {
      traditional: "無糖",
      simplified: "无糖",
      pinyin: "wú táng",
      english: "Sugar free",
    },
    {
      traditional: "杏仁",
      simplified: "杏仁",
      pinyin: "xìng rén",
      english: "Almond",
    },
  ],
};

export default lesson;
