import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "aisLEqpSre",
  type: "General Vocabulary",
  locked: false,
  title: "Restaurant Menus",
  content: [
    {
      traditional: "花生醬",
      simplified: "花生酱",
      pinyin: "huā shēng jiàng",
      english: "Peanut butter",
    },
    {
      traditional: "雞腿",
      simplified: "鸡腿",
      pinyin: "jī tuǐ",
      english: "Chicken leg",
    },
    {
      traditional: "堡",
      simplified: "堡",
      pinyin: "bǎo",
      english: '"Burger"',
    },
    {
      traditional: "吐司",
      simplified: "吐司",
      pinyin: "tǔ sī",
      english: "Toast",
    },
    {
      traditional: "蛋",
      simplified: "蛋",
      pinyin: "dàn",
      english: "Egg",
    },
    {
      traditional: "原味",
      simplified: "原味",
      pinyin: "yuán wèi",
      english: "Original flavor",
    },
    {
      traditional: "辣味",
      simplified: "辣味",
      pinyin: "là wèi",
      english: "Spicy",
    },
    {
      traditional: "美生菜",
      simplified: "美生菜",
      pinyin: "měi shēng cài",
      english: "Lettuce",
    },
    {
      traditional: "絲",
      simplified: "丝",
      pinyin: "sī",
      english: "Shreds",
    },
    {
      traditional: "洋蔥",
      simplified: "洋葱",
      pinyin: "yáng cōng",
      english: "Onion",
    },
    {
      traditional: "番茄",
      simplified: "番茄",
      pinyin: "fān qié",
      english: "Tomato",
    },
    {
      traditional: "片",
      simplified: "片",
      pinyin: "piàn",
      english: "Sheet (slices)",
    },
    {
      traditional: "鐵板",
      simplified: "铁板",
      pinyin: "tiě bǎn",
      english: "Iron plate",
    },
    {
      traditional: "蘑菇",
      simplified: "蘑菇",
      pinyin: "mó gū",
      english: "Mushroom",
    },
    {
      traditional: "黑胡椒",
      simplified: "黑胡椒",
      pinyin: "hēi hú jiāo",
      english: "Black pepper",
    },
    {
      traditional: "燒",
      simplified: "烧",
      pinyin: "shāo",
      english: "Burn",
    },
    {
      traditional: "里肌肉",
      simplified: "里肌肉",
      pinyin: "lǐ jī ròu",
      english: "Inner muscles (pork loin)",
    },
    {
      traditional: "奶油",
      simplified: "奶油",
      pinyin: "nǎi yóu",
      english: "Cream",
    },
    {
      traditional: "白醬",
      simplified: "白酱",
      pinyin: "bái jiàng",
      english: "White sauce",
    },
    {
      traditional: "肉醬",
      simplified: "肉酱",
      pinyin: "ròu jiàng",
      english: "Meat sauce",
    },
    {
      traditional: "宮保雞丁",
      simplified: "宫保鸡丁",
      pinyin: "gōng bǎo jī dīng",
      english: "Kung pao chicken",
    },
    {
      traditional: "義大利",
      simplified: "义大利",
      pinyin: "yì dà lì",
      english: "Italy",
    },
    {
      traditional: "咖哩",
      simplified: "咖喱",
      pinyin: "kā li",
      english: "Curry",
    },
    {
      traditional: "九層塔",
      simplified: "九层塔",
      pinyin: "jiǔ céng tǎ",
      english: "Basil",
    },
    {
      traditional: "塔",
      simplified: "塔",
      pinyin: "tǎ",
      english: "Tower (basil)",
    },
    {
      traditional: "蘿蔔糕",
      simplified: "萝卜糕",
      pinyin: "luó bó gāo",
      english: "Fried radish cake",
    },
    {
      traditional: "起司",
      simplified: "起司",
      pinyin: "qǐ sī",
      english: "Cheese",
    },
    {
      traditional: "玉米",
      simplified: "玉米",
      pinyin: "yù mǐ",
      english: "Corn",
    },
    {
      traditional: "肉鬆",
      simplified: "肉松",
      pinyin: "ròu sōng",
      english: "Pork floss",
    },
    {
      traditional: "火腿",
      simplified: "火腿",
      pinyin: "huǒ tuǐ",
      english: "Ham",
    },
    {
      traditional: "蔥",
      simplified: "葱",
      pinyin: "cōng",
      english: "Scallion/green onion",
    },
    {
      traditional: "薯餅",
      simplified: "薯饼",
      pinyin: "shǔ bǐng",
      english: "Potato cake (hash brown)",
    },
    {
      traditional: "脆",
      simplified: "脆",
      pinyin: "cuì",
      english: "Crispy/Crunchy",
    },
    {
      traditional: "藷",
      simplified: "薯",
      pinyin: "shǔ",
      english: "Yam",
    },
    {
      traditional: "甜不辣",
      simplified: "甜不辣",
      pinyin: "tián bù là",
      english: "Sweet or not spicy (tempura)",
    },
    {
      traditional: "豬排",
      simplified: "猪排",
      pinyin: "zhū pái",
      english: "Pork chops",
    },
    {
      traditional: "大腸",
      simplified: "大肠",
      pinyin: "dà cháng",
      english: "The large intestine",
    },
    {
      traditional: "醋",
      simplified: "醋",
      pinyin: "cù",
      english: "Vinegar",
    },
    {
      traditional: "蒜",
      simplified: "蒜",
      pinyin: "suàn",
      english: "Garlic",
    },
    {
      traditional: "香菜",
      simplified: "香菜",
      pinyin: "xiāng cài",
      english: "Parsley",
    },
    {
      traditional: "土司",
      simplified: "土司",
      pinyin: "tǔ sī",
      english: "Toast",
    },
    {
      traditional: "草莓",
      simplified: "草莓",
      pinyin: "cǎo méi",
      english: "Strawberry",
    },
    {
      traditional: "巧克力",
      simplified: "巧克力",
      pinyin: "qiǎo kè lì",
      english: "Chocolate",
    },
    {
      traditional: "炸雞",
      simplified: "炸鸡",
      pinyin: "zhà jī",
      english: "Fried chicken",
    },
    {
      traditional: "切",
      simplified: "切",
      pinyin: "qiè",
      english: "Cut",
    },
  ],
};

export default lesson;
