import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "f87s63hJFK",
  type: "Grammar",
  locked: false,
  title: "Lessons 6-15 Grammar",
  content: [
    {
      traditional: "我們學校在臺北。",
      simplified: "我们学校在台北。",
      pinyin: "wǒ men xué xiào zài tái běi",
      english: "Our school is in taipei.",
    },
    {
      traditional: "我在宿舍裡面。",
      simplified: "我在宿舍里面。",
      pinyin: "wǒ zài sù shè lǐ miàn",
      english: "I am in the dormitory.",
    },
    {
      traditional: "那家店在你家附近嗎？",
      simplified: "那家店在你家附近吗？",
      pinyin: "nà jiā diàn zài nǐ jiā fù jìn ma",
      english: "Is that store near your home?",
    },
    {
      traditional: "咖啡店在宿舍的旁邊，不在裡面。",
      simplified: "咖啡店在宿舍的旁边，不在里面。",
      pinyin: "kā fēi diàn zài sù shè dē páng biān bù zài lǐ miàn",
      english: "The coffee shop is next to the dormitory, not inside.",
    },
    {
      traditional: "游泳池在圖書館的後面，不在前面。",
      simplified: "游泳池在图书馆的后面，不在前面。",
      pinyin: "yóu yǒng chí zài tú shū guǎn dē hòu miàn bù zài qián miàn",
      english: "The swimming pool is behind the library, not in front.",
    },
    {
      traditional: "他和朋友在圖書館後面的咖啡店。",
      simplified: "他和朋友在图书馆后面的咖啡店。",
      pinyin: "tā hé péng yǒu zài tú shū guǎn hòu miàn dí kā fēi diàn",
      english: "He and his friends are in the coffee shop behind the library.",
    },
    {
      traditional: "那棟大樓的前面有很多人。",
      simplified: "那栋大楼的前面有很多人。",
      pinyin: "nà dòng dà lóu dē qián miàn yǒu hěn duō rén",
      english: "There are many people in front of that building.",
    },
    {
      traditional: "我家附近有圖書館。",
      simplified: "我家附近有图书馆。",
      pinyin: "wǒ jiā fù jìn yǒu tú shū guǎn",
      english: "There is a library near my home.",
    },
    {
      traditional: "山上有兩家很有名的咖啡店。",
      simplified: "山上有两家很有名的咖啡店。",
      pinyin: "shān shàng yǒu liǎng jiā hěn yǒu míng dē kā fēi diàn",
      english: "There are two famous coffee shops on the mountain.",
    },
    {
      traditional: "樓下有一家商店。",
      simplified: "楼下有一家商店。",
      pinyin: "lóu xià yǒu yī jiā shāng diàn",
      english: "There is a shop downstairs.",
    },
    {
      traditional: "他家附近沒有學生。",
      simplified: "他家附近没有学生。",
      pinyin: "tā jiā fù jìn méi yǒu xué shēng",
      english: "There are no students near his home.",
    },
    {
      traditional: "那棟大樓的後面沒有餐廳。",
      simplified: "那栋大楼的后面没有餐厅。",
      pinyin: "nà dòng dà lóu dē hòu miàn méi yǒu cān tīng",
      english: "There is no restaurant behind that building.",
    },
    {
      traditional: "你家附近有海嗎？",
      simplified: "你家附近有海吗？",
      pinyin: "nǐ jiā fù jìn yǒu hǎi ma",
      english: "Is there a sea near your home?",
    },
    {
      traditional: "學校的後面有沒有好吃的牛肉麵店？",
      simplified: "学校的后面有没有好吃的牛肉面店？",
      pinyin: "xué xiào dē hòu miàn yǒu méi yǒu hǎo chī dē niú ròu miàn diàn",
      english: "Is there a delicious beef noodle shop behind the school?",
    },
    {
      traditional: "他們學校很漂亮，我想去看一看。",
      simplified: "他们学校很漂亮，我想去看一看。",
      pinyin: "tā men xué xiào hěn piào liàng wǒ xiǎng qù kàn yī kàn",
      english: "Their school is very beautiful, i want to take a look.",
    },
    {
      traditional: "我想學中文，請教教我。",
      simplified: "我想学中文，请教教我。",
      pinyin: "wǒ xiǎng xué zhōng wén qǐng jiào jiào wǒ",
      english: "I want to learn chinese, please teach me.",
    },
    {
      traditional: "我們今天晚上去哪裡吃飯？我想一想。",
      simplified: "我们今天晚上去哪里吃饭？我想一想。",
      pinyin: "wǒ men jīn tiān wǎn shǎng qù nǎ lǐ chī fàn wǒ xiǎng yī xiǎng",
      english: "Where shall we go for dinner tonight? i think about it.",
    },
    {
      traditional:
        "你週末做什麼？在家看看書，喝喝咖啡，上上網，也去學校打打籃球。",
      simplified:
        "你周末做什么？在家看看书，喝喝咖啡，上上网，也去学校打打篮球。",
      pinyin:
        "nǐ zhōu mò zuò shén me zài jiā kàn kàn shū hē hē kā fēi shàng shàng wǎng yě qù xué xiào dǎ dǎ lán qiú",
      english:
        "What do you do during weekend? read books at home, drink coffee, go online, and play basketball at school.",
    },
    {
      traditional: "請幫幫我，好不好？",
      simplified: "请帮帮我，好不好？",
      pinyin: "qǐng bāng bāng wǒ hǎo bù hǎo",
      english: "Please help me, okay?",
    },
    {
      traditional: "請你教教我，可以嗎？",
      simplified: "请你教教我，可以吗？",
      pinyin: "qǐng nǐ jiào jiào wǒ kě yǐ ma",
      english: "Would you please teach me?",
    },
    {
      traditional: "現在外面很熱，你要不要在家看看書？",
      simplified: "现在外面很热，你要不要在家看看书？",
      pinyin: "xiàn zài wài miàn hěn rè nǐ yào bú yào zài jiā kàn kàn shū",
      english:
        "It's very hot outside now, would you like to read a book at home?",
    },
    {
      traditional: "我不會做甜點，你可不可以教教我？",
      simplified: "我不会做甜点，你可不可以教教我？",
      pinyin: "wǒ bù huì zuò tián diǎn nǐ kě bù kě yǐ jiào jiào wǒ",
      english: "I don't know how to make desserts, can you teach me?",
    },
    {
      traditional: "明華覺得那支手機很貴。我覺得不是很貴。",
      simplified: "明华觉得那支手机很贵。我觉得不是很贵。",
      pinyin: "míng huá jué dé nà zhī shǒu jī hěn guì wǒ jué dé bú shì hěn guì",
      english:
        "Minghua thinks that phone is very expensive. i don't think it is very expensive.",
    },
    {
      traditional: "他不是點大碗的牛肉麵。他點小碗的。",
      simplified: "他不是点大碗的牛肉面。他点小碗的。",
      pinyin: "tā bú shì diǎn dà wǎn dē niú ròu miàn tā diǎn xiǎo wǎn dē",
      english:
        "He is not ordering a big bowl of beef noodles. he ordered a small bowl.",
    },
    {
      traditional: "餐廳不是在學校裡面。餐廳在學校外面。",
      simplified: "餐厅不是在学校里面。餐厅在学校外面。",
      pinyin:
        "cān tīng bú shì zài xué xiào lǐ miàn cān tīng zài xué xiào wài miàn",
      english:
        "The restaurant is not in the school. the restaurant is outside the school.",
    },
    {
      traditional: "他們不是在樓下喝咖啡。他們在樓下買書。",
      simplified: "他们不是在楼下喝咖啡。他们在楼下买书。",
      pinyin: "tā men bú shì zài lóu xià hē kā fēi tā men zài lóu xià mǎi shū",
      english:
        "They are not drinking coffee downstairs. they buy books downstairs.",
    },
    {
      traditional: "我不是不賴，我週末來。",
      simplified: "我不是不赖，我周末来。",
      pinyin: "wǒ bú shì bù lài wǒ zhōu mò lái",
      english: "I'm not bad, i'll come this weekend.",
    },
    {
      traditional: "我不是不喜歡吃牛肉麵，可是這家的牛肉麵太辣了。",
      simplified: "我不是不喜欢吃牛肉面，可是这家的牛肉面太辣了。",
      pinyin:
        "wǒ bú shì bù xǐ huān chī niú ròu miàn kě shì zhè jiā dē niú ròu miàn tài là le",
      english:
        "It's not that i don't like beef noodles, but the beef noodles in this restaurant are too spicy.",
    },
    {
      traditional: "我爸爸在家做飯。",
      simplified: "我爸爸在家做饭。",
      pinyin: "wǒ bà bà zài jiā zuò fàn",
      english: "My dad cooks at home.",
    },
    {
      traditional: "他和他朋友到七樓的教室上網。",
      simplified: "他和他朋友到七楼的教室上网。",
      pinyin: "tā hé tā péng yǒu dào qī lóu dē jiào shì shàng wǎng",
      english:
        "He and his friends went online in the classroom on the seventh floor.",
    },
    {
      traditional: "我們老師唱到學校附近的咖啡店喝咖啡。",
      simplified: "我们老师唱到学校附近的咖啡店喝咖啡。",
      pinyin:
        "wǒ men lǎo shī chàng dào xué xiào fù jìn dē kā fēi diàn hē kā fēi",
      english:
        "Our teacher sang to drink coffee at a coffee shop near the school.",
    },
    {
      traditional: "我們很喜歡在這家餐廳吃就肉麵。",
      simplified: "我们很喜欢在这家餐厅吃就肉面。",
      pinyin: "wǒ men hěn xǐ huān zài zhè jiā cān tīng chī jiù ròu miàn",
      english: "We like meat noodles at this restaurant.",
    },
    {
      traditional: "他們今天不在家吃完飯。",
      simplified: "他们今天不在家吃完饭。",
      pinyin: "tā men jīn tiān bù zài jiā chī wán fàn",
      english: "They are not at home to finish their dinner today.",
    },
    {
      traditional: "他現在不在宿舍看書。",
      simplified: "他现在不在宿舍看书。",
      pinyin: "tā xiàn zài bù zài sù shè kàn shū",
      english: "He is not reading in the dormitory now.",
    },
    {
      traditional: "很多學生不在學校裡面的咖啡店買咖啡。",
      simplified: "很多学生不在学校里面的咖啡店买咖啡。",
      pinyin:
        "hěn duō xué shēng bù zài xué xiào lǐ miàn dí kā fēi diàn mǎi kā fēi",
      english:
        "Many students do not buy coffee in the coffee shop inside the school.",
    },
    {
      traditional: "你們在那裡打籃球。",
      simplified: "你们在那里打篮球。",
      pinyin: "nǐ men zài nà lǐ dǎ lán qiú",
      english: "You play basketball there.",
    },
    {
      traditional: "你沒咩到這家商店買甜點嗎？",
      simplified: "你没咩到这家商店买甜点吗？",
      pinyin: "nǐ méi miē dào zhè jiā shāng diàn mǎi tián diǎn ma",
      english: "Didn't you go to this shop to buy desserts?",
    },
    {
      traditional: "他和他朋友下午在教室寫書法。",
      simplified: "他和他朋友下午在教室写书法。",
      pinyin: "tā hé tā péng yǒu xià wǔ zài jiào shì xiě shū fǎ",
      english:
        "He and his friend write calligraphy in the classroom in the afternoon.",
    },
    {
      traditional: "我昨天晚上到我家附近的咖啡點喝咖啡",
      simplified: "我昨天晚上到我家附近的咖啡点喝咖啡",
      pinyin:
        "wǒ zuó tiān wǎn shàng dào wǒ jiā fù jìn dē kā fēi diǎn hē kā fēi",
      english: "I went to a coffee shop near my house last night for coffee",
    },
    {
      traditional: "我們這個週末圖書館看書。",
      simplified: "我们这个周末图书馆看书。",
      pinyin: "wǒ men zhè gè zhōu mò tú shū guǎn kàn shū",
      english: "We read in the library this weekend.",
    },
    {
      traditional: "你們明天早上十一點到我家來吃牛肉麵。",
      simplified: "你们明天早上十一点到我家来吃牛肉面。",
      pinyin:
        "nǐ men míng tiān zǎo shàng shí yī diǎn dào wǒ jiā lái chī niú ròu miàn",
      english:
        "You come to my house for beef noodles at 11 o'clock tomorrow morning.",
    },
    {
      traditional: "我晚上不在家吃飯。",
      simplified: "我晚上不在家吃饭。",
      pinyin: "wǒ wǎn shàng bù zài jiā chī fàn",
      english: "I don't eat at home at night.",
    },
    {
      traditional: "他和他哥哥最近都不來學校上課。",
      simplified: "他和他哥哥最近都不来学校上课。",
      pinyin: "tā hé tā gē ge zuì jìn dōu bù lái xué xiào shàng kè",
      english: "He and his brother have not come to school recently.",
    },
    {
      traditional: "他們這個週末不去山上看風景。",
      simplified: "他们这个周末不去山上看风景。",
      pinyin: "tā men zhè gè zhōu mò bù qù shān shàng kàn fēng jǐng",
      english:
        "They won't go to the mountains to see the scenery this weekend.",
    },
    {
      traditional: "你下午要不要來學校打籃球？",
      simplified: "你下午要不要来学校打篮球？",
      pinyin: "nǐ xià wǔ yào bú yào lái xué xiào dǎ lán qiú",
      english:
        "Would you like to come to school to play basketball this afternoon?",
    },
    {
      traditional: "你們現在在我家附近的商店買手機嗎？",
      simplified: "你们现在在我家附近的商店买手机吗？",
      pinyin: "nǐ men xiàn zài zài wǒ jiā fù jìn dē shāng diàn mǎi shǒu jī ma",
      english: "Do you buy mobile phones in a store near my house now?",
    },
    {
      traditional: "你朋友晚上幾點去KTV唱歌？",
      simplified: "你朋友晚上几点去KTV唱歌？",
      pinyin: "nǐ péng yǒu wǎn shàng jǐ diǎn qù chàng gē",
      english: "What time does your friend go to ktv to sing at night?",
    },
    {
      traditional: "他們什麼時候到花蓮看籃球比賽？",
      simplified: "他们什么时候到花莲看篮球比赛？",
      pinyin: "tā men shén me shí hòu dào huā lián kàn lán qiú bǐ sài",
      english: "When will they go to hualien to watch a basketball game?",
    },
    {
      traditional: "你和你妹妹明天早上要去哪裡看電影？",
      simplified: "你和你妹妹明天早上要去哪里看电影？",
      pinyin: "nǐ hé nǐ mèi mei míng tiān zǎo shàng yào qù nǎ lǐ kàn diàn yǐng",
      english:
        "Where are you and your sister going to watch a movie tomorrow morning?",
    },
    {
      traditional: "我從早上十點二十分到下午一點十分有中文課。",
      simplified: "我从早上十点二十分到下午一点十分有中文课。",
      pinyin:
        "wǒ cóng zǎo shàng shí diǎn èr shí fēn dào xià wǔ yī diǎn shí fēn yǒu zhōng wén kè",
      english:
        "I have chinese lessons from 10:20 in the morning to 1:10 in the afternoon.",
    },
    {
      traditional: "我今天從早上到晚上。",
      simplified: "我今天从早上到晚上。",
      pinyin: "wǒ jīn tiān cóng zǎo shàng dào wǎn shàng",
      english: "I am from morning to night today.",
    },
    {
      traditional: "從我家到那個游泳池有一點遠。",
      simplified: "从我家到那个游泳池有一点远。",
      pinyin: "cóng wǒ jiā dào nà gè yóu yǒng chí yǒu yī diǎn yuǎn",
      english: "It's a little far from my house to the swimming pool.",
    },
    {
      traditional: "我從我朋友嫁到這個地方來。",
      simplified: "我从我朋友嫁到这个地方来。",
      pinyin: "wǒ cóng wǒ péng yǒu jià dào zhè gè dì fāng lái",
      english: "I came to this place from the marriage of my friend.",
    },
    {
      traditional: "他從圖書館到那家餐廳去吃飯。",
      simplified: "他从图书馆到那家餐厅去吃饭。",
      pinyin: "tā cóng tú shū guǎn dào nà jiā cān tīng qù chī fàn",
      english: "He went from the library to the restaurant to eat.",
    },
    {
      traditional: "我們的書法課不是從九點到十一點。",
      simplified: "我们的书法课不是从九点到十一点。",
      pinyin: "wǒ men dē shū fǎ kè bú shì cóng jiǔ diǎn dào shí yī diǎn",
      english: "Our calligraphy class is not from nine to eleven.",
    },
    {
      traditional: "陳先生的媽媽昨天不是從早上到晚上都很忙。",
      simplified: "陈先生的妈妈昨天不是从早上到晚上都很忙。",
      pinyin:
        "chén xiān shēng dē mā mā zuó tiān bú shì cóng zǎo shàng dào wǎn shàng dōu hěn máng",
      english:
        "Mr. chen's mother was not busy from morning to night yesterday.",
    },
    {
      traditional:
        "我身時候可以去你家？我今天從早上到晚上都沒有空，可是明天可以。",
      simplified:
        "我身时候可以去你家？我今天从早上到晚上都没有空，可是明天可以。",
      pinyin:
        "wǒ shēn shí hòu kě yǐ qù nǐ jiā wǒ jīn tiān cóng zǎo shàng dào wǎn shàng dōu méi yǒu kòng kě shì míng tiān kě yǐ",
      english:
        "Can i go to your house when i am? i have no time from morning to night today, but tomorrow will be fine.",
    },
    {
      traditional: "從這棟大樓到那家KTV不遠。",
      simplified: "从这栋大楼到那家KTV不远。",
      pinyin: "cóng zhè dòng dà lóu dào nà jiā bù yuǎn",
      english: "It’s not far from this building to that ktv.",
    },
    {
      traditional: "我不想從學校到哪裡去，想從我家去。",
      simplified: "我不想从学校到哪里去，想从我家去。",
      pinyin: "wǒ bù xiǎng cóng xué xiào dào nǎ lǐ qù xiǎng cóng wǒ jiā qù",
      english:
        "I don't want to go anywhere from school, i want to go from my home.",
    },
    {
      traditional: "你們老師後天從早上到下午都有空嗎？",
      simplified: "你们老师后天从早上到下午都有空吗？",
      pinyin:
        "nǐ men lǎo shī hòu tiān cóng zǎo shàng dào xià wǔ dōu yǒu kòng ma",
      english:
        "Is your teacher free from morning to afternoon the day after tomorrow?",
    },
    {
      traditional: "請問從圖書館到你們宿舍遠不遠？",
      simplified: "请问从图书馆到你们宿舍远不远？",
      pinyin: "qǐng wèn cóng tú shū guǎn dào nǐ men sù shè yuǎn bù yuǎn",
      english: "Is it far from the library to your dormitory?",
    },
    {
      traditional: "他們想從宿舍還是圖書館到教室去上課？",
      simplified: "他们想从宿舍还是图书馆到教室去上课？",
      pinyin:
        "tā men xiǎng cóng sù shè hái shì tú shū guǎn dào jiào shì qù shàng kè",
      english:
        "Do they want to go to class from the dormitory or the library to the classroom?",
    },
    {
      traditional: "林老師在上課。",
      simplified: "林老师在上课。",
      pinyin: "lín lǎo shī zài shàng kè",
      english: "Teacher lin is in class.",
    },
    {
      traditional: "你看！陳先生在唱歌。",
      simplified: "你看！陈先生在唱歌。",
      pinyin: "nǐ kàn chén xiān shēng zài chàng gē",
      english: "Look! mr. chen is singing.",
    },
    {
      traditional: "昨天下午五點我在做飯。",
      simplified: "昨天下午五点我在做饭。",
      pinyin: "zuó tiān xià wǔ wǔ diǎn wǒ zài zuò fàn",
      english: "I was cooking at five yesterday afternoon.",
    },
    {
      traditional: "他不是在看書。他在看籃球比賽。",
      simplified: "他不是在看书。他在看篮球比赛。",
      pinyin: "tā bú shì zài kàn shū tā zài kàn lán qiú bǐ sài",
      english: "He is not reading. he is watching a basketball game.",
    },
    {
      traditional: "我不是在照相。我的手機不能照相。",
      simplified: "我不是在照相。我的手机不能照相。",
      pinyin: "wǒ bú shì zài zhào xiàng wǒ dē shǒu jī bù néng zhào xiàng",
      english: "I'm not taking pictures. my phone cannot take pictures.",
    },
    {
      traditional: "你們在喝什麼？",
      simplified: "你们在喝什么？",
      pinyin: "nǐ men zài hē shén me",
      english: "What are you drinking?",
    },
    {
      traditional: "他們老師在上課嗎？",
      simplified: "他们老师在上课吗？",
      pinyin: "tā men lǎo shī zài shàng kè ma",
      english: "Is their teacher in class?",
    },
    {
      traditional: "他們在打籃球嗎？",
      simplified: "他们在打篮球吗？",
      pinyin: "tā men zài dǎ lán qiú ma",
      english: "Are they playing basketball?",
    },
    {
      traditional: "他妹妹天都有空。",
      simplified: "他妹妹天都有空。",
      pinyin: "tā mèi mei tiān dū yǒu kòng",
      english: "His sister is free every day.",
    },
    {
      traditional: "他朋友每個週末都去學校附近的游泳池游泳。",
      simplified: "他朋友每个周末都去学校附近的游泳池游泳。",
      pinyin:
        "tā péng yǒu měi gè zhōu mò dōu qù xué xiào fù jìn dē yóu yǒng chí yóu yǒng",
      english:
        "His friend goes to the swimming pool near the school to swim every weekend.",
    },
    {
      traditional: "每一棟大樓都可以上網。",
      simplified: "每一栋大楼都可以上网。",
      pinyin: "měi yī dòng dà lóu dōu kě yǐ shàng wǎng",
      english: "Every building has internet access.",
    },
    {
      traditional: "他家人，每個人都會做甜點。",
      simplified: "他家人，每个人都会做甜点。",
      pinyin: "tā jiā rén měi gè rén dōu huì zuò tián diǎn",
      english: "Everyone in his family makes desserts.",
    },
    {
      traditional: "他每天都不忙。",
      simplified: "他每天都不忙。",
      pinyin: "tā měi tiān dū bù máng",
      english: "He is not busy every day.",
    },
    {
      traditional: "我媽媽每個週末都沒空。",
      simplified: "我妈妈每个周末都没空。",
      pinyin: "wǒ mā mā měi gè zhōu mò dōu méi kōng",
      english: "My mother is not free every weekend.",
    },
    {
      traditional: "這家商店，每支手機都不便宜。",
      simplified: "这家商店，每支手机都不便宜。",
      pinyin: "zhè jiā shāng diàn měi zhī shǒu jī dōu bù pián yí",
      english: "In this shop, every cell phone is not cheap.",
    },
    {
      traditional: "他朋友不是每天都去看電影。",
      simplified: "他朋友不是每天都去看电影。",
      pinyin: "tā péng yǒu bú shì měi tiān dū qù kàn diàn yǐng",
      english: "His friend doesn't go to the movies every day.",
    },
    {
      traditional: "我們不是每天都有書法課。",
      simplified: "我们不是每天都有书法课。",
      pinyin: "wǒ men bú shì měi tiān dū yǒu shū fǎ kè",
      english: "We don’t have calligraphy lessons every day.",
    },
    {
      traditional: "他的兄弟姊妹不是每個人都喜歡打球。",
      simplified: "他的兄弟姊妹不是每个人都喜欢打球。",
      pinyin: "tā dē xiōng dì zǐ mèi bú shì měi gè rén dōu xǐ huān dǎ qiú",
      english: "Not everyone of his siblings likes to play ball.",
    },
    {
      traditional: "他每個週末都去哪裡運動？",
      simplified: "他每个周末都去哪里运动？",
      pinyin: "tā měi gè zhōu mò dōu qù nǎ lǐ yùn dòng",
      english: "Where does he go to exercise every weekend?",
    },
    {
      traditional: "你爸爸每天都在家吃晚飯嗎？",
      simplified: "你爸爸每天都在家吃晚饭吗？",
      pinyin: "nǐ bà bà měi tiān dū zài jiā chī wǎn fàn ma",
      english: "Does your father eat dinner at home every day?",
    },
    {
      traditional: "他的照片，每張都很好看嗎？",
      simplified: "他的照片，每张都很好看吗？",
      pinyin: "tā dē zhào piān měi zhāng dōu hěn hǎo kàn ma",
      english: "Are each of his photos pretty good-looking?",
    },
    {
      traditional: "我媽媽說，你們可以來我家打籃球。",
      simplified: "我妈妈说，你们可以来我家打篮球。",
      pinyin: "wǒ mā mā shuō nǐ men kě yǐ lái wǒ jiā dǎ lán qiú",
      english: "My mother said, you can come to my house to play basketball.",
    },
    {
      traditional: "爸爸說，我可以買這支手機。",
      simplified: "爸爸说，我可以买这支手机。",
      pinyin: "bà bà shuō wǒ kě yǐ mǎi zhè zhī shǒu jī",
      english: "Dad said, i can buy this phone.",
    },
    {
      traditional: "我叫安同，你可以教我小同。",
      simplified: "我叫安同，你可以教我小同。",
      pinyin: "wǒ jiào ān tóng nǐ kě yǐ jiào wǒ xiǎo tóng",
      english: "My name is antong, you can teach me xiaotong.",
    },
    {
      traditional: "媽媽說，我不可以買這支手機。",
      simplified: "妈妈说，我不可以买这支手机。",
      pinyin: "mā mā shuō wǒ bù kě yǐ mǎi zhè zhī shǒu jī",
      english: "Mom said, i can’t buy this phone.",
    },
    {
      traditional: "你不可以在圖書館裡面吃東西。",
      simplified: "你不可以在图书馆里面吃东西。",
      pinyin: "nǐ bù kě yǐ zài tú shū guǎn lǐ miàn chī dōng xī",
      english: "You cannot eat in the library.",
    },
    {
      traditional: "先生，對不起，你不可以在這裡照相。",
      simplified: "先生，对不起，你不可以在这里照相。",
      pinyin: "xiān shēng duì bù qǐ nǐ bù kě yǐ zài zhè lǐ zhào xiàng",
      english: "Sorry, sir, you can’t take pictures here.",
    },
    {
      traditional: "我可以不可以去看你們的籃球比賽？沒問題！",
      simplified: "我可以不可以去看你们的篮球比赛？没问题！",
      pinyin: "wǒ kě yǐ bù kě yǐ qù kàn nǐ men dē lán qiú bǐ sài méi wèn tí",
      english: "Can i go to your basketball game? no problem!",
    },
    {
      traditional: "我想吃你的包子，可以嗎？可以啊。",
      simplified: "我想吃你的包子，可以吗？可以啊。",
      pinyin: "wǒ xiǎng chī nǐ dē bāo zi kě yǐ ma kě yǐ a",
      english: "I want to eat your buns, can i? sure.",
    },
    {
      traditional: "這是你的書嗎？我可以看看嗎？對不起，那不是我的書。",
      simplified: "这是你的书吗？我可以看看吗？对不起，那不是我的书。",
      pinyin:
        "zhè shì nǐ dē shū ma wǒ kě yǐ kàn kàn ma duì bù qǐ nà bú shì wǒ dē shū",
      english:
        "Is this your book? may i take a look at it? sorry, that is not my book.",
    },
    {
      traditional: "你可不可以明天來？",
      simplified: "你可不可以明天来？",
      pinyin: "nǐ kě bù kě yǐ míng tiān lái",
      english: "Can you come tomorrow?",
    },
    {
      traditional: "我可以不可以買一支新手機？",
      simplified: "我可以不可以买一支新手机？",
      pinyin: "wǒ kě yǐ bù kě yǐ mǎi yī zhī xīn shǒu jī",
      english: "Can i buy a new phone?",
    },
    {
      traditional: "媽媽，我可不可以買這支手機？可以。",
      simplified: "妈妈，我可不可以买这支手机？可以。",
      pinyin: "mā mā wǒ kě bù kě yǐ mǎi zhè zhī shǒu jī kě yǐ",
      english: "Mom, can i buy this phone? can.",
    },
    {
      traditional: "我今天不跟同學去上書法課。",
      simplified: "我今天不跟同学去上书法课。",
      pinyin: "wǒ jīn tiān bù gēn tóng xué qù shàng shū fǎ kè",
      english: "I won’t go to calligraphy class with my classmates today",
    },
    {
      traditional: "他不跟我一起去KTV唱歌。",
      simplified: "他不跟我一起去KTV唱歌。",
      pinyin: "tā bù gēn wǒ yì qǐ qù chàng gē",
      english: "He doesn't go to ktv to sing with me",
    },
    {
      traditional: "妹妹不跟我去吃越南菜。",
      simplified: "妹妹不跟我去吃越南菜。",
      pinyin: "mèi mei bù gēn wǒ qù chī yuè nán cài",
      english: "My sister won't go to eat vietnamese food with me",
    },
    {
      traditional: "你要跟他去日本嗎？",
      simplified: "你要跟他去日本吗？",
      pinyin: "nǐ yào gēn tā qù rì běn ma",
      english: "Do you want to go to japan with him?",
    },
    {
      traditional: "你常跟誰去看電影？",
      simplified: "你常跟谁去看电影？",
      pinyin: "nǐ cháng gēn shuí qù kàn diàn yǐng",
      english: "Who do you go to the movies with?",
    },
    {
      traditional: "你想跟我去打網球嗎？",
      simplified: "你想跟我去打网球吗？",
      pinyin: "nǐ xiǎng gēn wǒ qù dǎ wǎng qiú ma",
      english: "Do you want to play tennis with me?",
    },
    {
      traditional: "你跟不跟我去圖書館看書？",
      simplified: "你跟不跟我去图书馆看书？",
      pinyin: "nǐ gēn bù gēn wǒ qù tú shū guǎn kàn shū",
      english: "Will you go to the library to read with me?",
    },
    {
      traditional: "你們怎麼去？",
      simplified: "你们怎么去？",
      pinyin: "nǐ men zěn me qù",
      english: "How are you going?",
    },
    {
      traditional: "這個才怎麼做？",
      simplified: "这个才怎么做？",
      pinyin: "zhè gè cái zěn me zuò",
      english: "How to do this?",
    },
    {
      traditional: "這個歌怎麼唱？",
      simplified: "这个歌怎么唱？",
      pinyin: "zhè gè gē zěn me chàng",
      english: "How to sing this song?",
    },
    {
      traditional: "這支新手機怎麼上網？",
      simplified: "这支新手机怎么上网？",
      pinyin: "zhè zhī xīn shǒu jī zěn me shàng wǎng",
      english: "How does this new phone go online?",
    },
    {
      traditional: "今天比較熱。",
      simplified: "今天比较热。",
      pinyin: "jīn tiān bǐ jiào rè",
      english: "It's hotter today",
    },
    {
      traditional: "越南餐廳很遠。坐捷運比較快。",
      simplified: "越南餐厅很远。坐捷运比较快。",
      pinyin: "yuè nán cān tīng hěn yuǎn zuò jié yùn bǐ jiào kuài",
      english: "The vietnamese restaurant is far away. the mrt is faster.",
    },
    {
      traditional: "我們家，姐姐比較會做飯。",
      simplified: "我们家，姐姐比较会做饭。",
      pinyin: "wǒ men jiā jiě jie bǐ jiào huì zuò fàn",
      english: "My sister is better at cooking.",
    },
    {
      traditional: "昨天比較不熱。",
      simplified: "昨天比较不热。",
      pinyin: "zuó tiān bǐ jiào bù rè",
      english: "It was not hot yesterday",
    },
    {
      traditional: "他比較不喜歡游泳。",
      simplified: "他比较不喜欢游泳。",
      pinyin: "tā bǐ jiào bù xǐ huān yóu yǒng",
      english: "He doesn't like swimming",
    },
    {
      traditional: "我最近比較沒有空。",
      simplified: "我最近比较没有空。",
      pinyin: "wǒ zuì jìn bǐ jiào méi yǒu kòng",
      english: "I'm relatively unavailable lately",
    },
    {
      traditional: "咖啡和茶，你比較喜歡喝咖啡嗎？",
      simplified: "咖啡和茶，你比较喜欢喝咖啡吗？",
      pinyin: "kā fēi hé chá nǐ bǐ jiào xǐ huān hē kā fēi ma",
      english: "Coffee and tea, do you prefer coffee?",
    },
    {
      traditional: "你和哥哥，你比較會打棒球嗎？",
      simplified: "你和哥哥，你比较会打棒球吗？",
      pinyin: "nǐ hé gē ge nǐ bǐ jiào huì dǎ bàng qiú ma",
      english: "Are you better at baseball with your brother?",
    },
    {
      traditional: "他比較想去看美國電影還是日本電影？",
      simplified: "他比较想去看美国电影还是日本电影？",
      pinyin:
        "tā bǐ jiào xiǎng qù kàn měi guó diàn yǐng hái shì rì běn diàn yǐng",
      english: "Does he prefer to watch american movies or japanese movies?",
    },
    {
      traditional: "這家餐廳的菜，又便宜又好吃，所以我們常來吃。",
      simplified: "这家餐厅的菜，又便宜又好吃，所以我们常来吃。",
      pinyin:
        "zhè jiā cān tīng dē cài yòu pián yí yòu hǎo chī suǒ yǐ wǒ men cháng lái chī",
      english:
        "The food in this restaurant is cheap and delicious, so we often come to eat it.",
    },
    {
      traditional: "坐高鐵又快又舒服，可是有一點貴。",
      simplified: "坐高铁又快又舒服，可是有一点贵。",
      pinyin: "zuò gāo tiě yòu kuài yòu shū fú kě shì yǒu yī diǎn guì",
      english:
        "The high-speed train is fast and comfortable, but a bit expensive.",
    },
    {
      traditional: "我有想和擦好有想喝咖啡，但是這裡沒有便利商店。",
      simplified: "我有想和擦好有想喝咖啡，但是这里没有便利商店。",
      pinyin:
        "wǒ yǒu xiǎng hé cā hǎo yǒu xiǎng hē kā fēi dàn shì zhè lǐ méi yǒu biàn lì shāng diàn",
      english:
        "I want to clean it and drink coffee, but there is no convenience store here.",
    },
    {
      traditional: "老闆今天做的臭豆腐又不愁又不辣。 我覺得不好吃。",
      simplified: "老板今天做的臭豆腐又不愁又不辣。我觉得不好吃。",
      pinyin:
        "lǎo bǎn jīn tiān zuò dē chòu dòu fǔ yòu bù chóu yòu bù là wǒ jué dé bù hǎo chī",
      english:
        "The stinky tofu made by the boss today is not worrying and not spicy. i don't think it tastes good.",
    },
    {
      traditional: "我的舊手機又不能照相又不能上網。我想買新的。",
      simplified: "我的旧手机又不能照相又不能上网。我想买新的。",
      pinyin:
        "wǒ dē jiù shǒu jī yòu bù néng zhào xiàng yòu bù néng shàng wǎng wǒ xiǎng mǎi xīn dē",
      english:
        "My old mobile phone can't take pictures or surf the internet. i want to buy a new one.",
    },
    {
      traditional: "山上的風景比這裡漂亮。",
      simplified: "山上的风景比这里漂亮。",
      pinyin: "shān shàng dē fēng jǐng bǐ zhè lǐ piào liàng",
      english: "The scenery on the mountain is more beautiful than here",
    },
    {
      traditional: "我們學校比他們學校元。",
      simplified: "我们学校比他们学校元。",
      pinyin: "wǒ men xué xiào bǐ tā men xué xiào yuán",
      english: "Our school is more yuan than theirs",
    },
    {
      traditional: "坐捷運比坐火車快。",
      simplified: "坐捷运比坐火车快。",
      pinyin: "zuò jié yùn bǐ zuò huǒ chē kuài",
      english: "Mrt is faster than train",
    },
    {
      traditional: "在家上網不比在學校快。",
      simplified: "在家上网不比在学校快。",
      pinyin: "zài jiā shàng wǎng bù bǐ zài xué xiào kuài",
      english: "Internet at home is not faster than at school",
    },
    {
      traditional: "我的車不比他的車貴。",
      simplified: "我的车不比他的车贵。",
      pinyin: "wǒ dē chē bù bǐ tā dē chē guì",
      english: "My car is not more expensive than his",
    },
    {
      traditional: "坐公車不是比做計程車快。",
      simplified: "坐公车不是比做计程车快。",
      pinyin: "zuò gōng chē bú shì bǐ zuò jì chéng chē kuài",
      english: "Taking a bus is not faster than taking a taxi",
    },
    {
      traditional: "他們學校比你們學校元嗎？",
      simplified: "他们学校比你们学校元吗？",
      pinyin: "tā men xué xiào bǐ nǐ men xué xiào yuán ma",
      english: "Is their school better than yours?",
    },
    {
      traditional: "這種手機比那種貴嗎？",
      simplified: "这种手机比那种贵吗？",
      pinyin: "zhè zhǒng shǒu jī bǐ nà zhǒng guì ma",
      english: "Is this kind of mobile phone more expensive than that?",
    },
    {
      traditional: "我去花蓮玩一個星期。",
      simplified: "我去花莲玩一个星期。",
      pinyin: "wǒ qù huā lián wán yī gè xīng qī",
      english: "I went to hualien for a week.",
    },
    {
      traditional: "這個電影很有意思，可是要看三個鐘頭。",
      simplified: "这个电影很有意思，可是要看三个钟头。",
      pinyin: "zhè gè diàn yǐng hěn yǒu yì sī kě shì yào kàn sān gè zhōng tóu",
      english:
        "This movie is very interesting, but it takes three hours to watch.",
    },
    {
      traditional: "中文，我想學一年半。",
      simplified: "中文，我想学一年半。",
      pinyin: "zhōng wén wǒ xiǎng xué yī nián bàn",
      english: "I want to learn chinese for a year and a half.",
    },
    {
      traditional: "我去日本旅行一個多星期。",
      simplified: "我去日本旅行一个多星期。",
      pinyin: "wǒ qù rì běn lǚ xíng yī gè duō xīng qī",
      english: "I traveled to japan for more than a week.",
    },
    {
      traditional: "這麼多甜點，我們要吃一個星期。",
      simplified: "这么多甜点，我们要吃一个星期。",
      pinyin: "zhè me duō tián diǎn wǒ men yào chī yī gè xīng qī",
      english: "We will eat so many desserts for a week.",
    },
    {
      traditional: "我想坐高鐵去台南玩兩天。",
      simplified: "我想坐高铁去台南玩两天。",
      pinyin: "wǒ xiǎng zuò gāo tiě qù tái nán wán liǎng tiān",
      english: "I want to take the high-speed rail to tainan for two days.",
    },
    {
      traditional: "中文課，我們學校要上四年。",
      simplified: "中文课，我们学校要上四年。",
      pinyin: "zhōng wén kè wǒ men xué xiào yào shàng sì nián",
      english: "Chinese class, our school will take four years.",
    },
    {
      traditional: "他打算腳中文教一年。",
      simplified: "他打算脚中文教一年。",
      pinyin: "tā dǎ suàn jiǎo zhōng wén jiào yī nián",
      english: "He plans to teach chinese for one year.",
    },
    {
      traditional: "我每個星期學書法學兩天。",
      simplified: "我每个星期学书法学两天。",
      pinyin: "wǒ měi gè xīng qī xué shū fǎ xué liǎng tiān",
      english: "I study calligraphy two days a week.",
    },
    {
      traditional: "今年我想在台灣學中文學九個月。",
      simplified: "今年我想在台湾学中文学九个月。",
      pinyin: "jīn nián wǒ xiǎng zài tái wān xué zhōng wén xué jiǔ gè yuè",
      english:
        "This year i want to study chinese literature in taiwan for nine months.",
    },
    {
      traditional: "他太忙了，所以他倆天不能來上課。",
      simplified: "他太忙了，所以他俩天不能来上课。",
      pinyin: "tā tài máng le suǒ yǐ tā liǎ tiān bù néng lái shàng kè",
      english: "He is too busy, so they can't come to class for two days.",
    },
    {
      traditional: "這裡沒有網路，所以我兩個星期不能上網。",
      simplified: "这里没有网路，所以我两个星期不能上网。",
      pinyin:
        "zhè lǐ méi yǒu wǎng lù suǒ yǐ wǒ liǎng gè xīng qī bù néng shàng wǎng",
      english:
        "There is no internet here, so i cannot access the internet for two weeks.",
    },
    {
      traditional: "他要回美國，所以一個月不能上課。",
      simplified: "他要回美国，所以一个月不能上课。",
      pinyin: "tā yào huí měi guó suǒ yǐ yī gè yuè bù néng shàng kè",
      english:
        "He is going back to the united states, so he can't attend classes for a month.",
    },
    {
      traditional: "我每星期上五天的課。",
      simplified: "我每星期上五天的课。",
      pinyin: "wǒ měi xīng qī shàng wǔ tiān dē kè",
      english: "I have classes five days a week.",
    },
    {
      traditional: "學校下個月放三天的假。",
      simplified: "学校下个月放三天的假。",
      pinyin: "xué xiào xià gè yuè fàng sān tiān dē jiǎ",
      english: "The school will take three days off next month.",
    },
    {
      traditional: "我們打算明天去KTV長三個鐘頭的歌。",
      simplified: "我们打算明天去KTV长三个钟头的歌。",
      pinyin: "wǒ men dǎ suàn míng tiān qù zhǎng sān gè zhōng tóu dē gē",
      english: "We plan to go to ktv tomorrow for a three-hour song.",
    },
    {
      traditional: "你決定在台灣學多久的中文？",
      simplified: "你决定在台湾学多久的中文？",
      pinyin: "nǐ jué dìng zài tái wān xué duō jiǔ dē zhōng wén",
      english: "How long did you decide to study chinese in taiwan?",
    },
    {
      traditional: "在山上看風景的時候，我覺得很舒服。",
      simplified: "在山上看风景的时候，我觉得很舒服。",
      pinyin: "zài shān shàng kàn fēng jǐng dē shí hòu wǒ jué de hěn shū fú",
      english:
        "When looking at the scenery on the mountain, i feel very comfortable.",
    },
    {
      traditional: "放假的時候，我喜歡去逛夜市。",
      simplified: "放假的时候，我喜欢去逛夜市。",
      pinyin: "fàng jià dē shí hòu wǒ xǐ huān qù guàng yè shì",
      english: "During holidays, i like to go to the night market.",
    },
    {
      traditional: "你有空的時候，請到我家來玩。",
      simplified: "你有空的时候，请到我家来玩。",
      pinyin: "nǐ yǒu kòng dē shí hòu qǐng dào wǒ jiā lái wán",
      english: "When you are free, please come to my house to play.",
    },
    {
      traditional: "我有時候吃中國菜，有時候吃越南菜。",
      simplified: "我有时候吃中国菜，有时候吃越南菜。",
      pinyin: "wǒ yǒu shí hòu chī zhōng guó cài yǒu shí hòu chī yuè nán cài",
      english: "I sometimes eat chinese food and sometimes vietnamese food.",
    },
    {
      traditional: "在圖書館的時候，我有時候看書，有時候上網。",
      simplified: "在图书馆的时候，我有时候看书，有时候上网。",
      pinyin:
        "zài tú shū guǎn dē shí hòu wǒ yǒu shí hòu kàn shū yǒu shí hòu shàng wǎng",
      english:
        "When i was in the library, i sometimes read books and sometimes went online.",
    },
    {
      traditional: "放假的時候，我有時候在家寫功課，有時候出去玩。",
      simplified: "放假的时候，我有时候在家写功课，有时候出去玩。",
      pinyin:
        "fàng jià dē shí hòu wǒ yǒu shí hòu zài jiā xiě gōng kè yǒu shí hòu chū qù wán",
      english:
        "During holidays, i sometimes do homework at home and sometimes go out to play.",
    },
    {
      traditional: "要是我有錢，我就買大房子。",
      simplified: "要是我有钱，我就买大房子。",
      pinyin: "yào shì wǒ yǒu qián wǒ jiù mǎi dà fáng zi",
      english: "If i have money, i will buy a big house.",
    },
    {
      traditional: "我要是不會過，我就跟你們一起去玩。",
      simplified: "我要是不会过，我就跟你们一起去玩。",
      pinyin: "wǒ yào shì bù huì guò wǒ jiù gēn nǐ men yì qǐ qù wán",
      english: "If i don't know how to live, i will play with you.",
    },
    {
      traditional: "要是我有空，我就跟朋友一起去KYV唱歌。",
      simplified: "要是我有空，我就跟朋友一起去KYV唱歌。",
      pinyin: "yào shì wǒ yǒu kòng wǒ jiù gēn péng yǒu yì qǐ qù chàng gē",
      english: "If i have time, i will go to kyv to sing with my friends.",
    },
    {
      traditional: "你要是星期日有空，你就跟我去旅行吧！",
      simplified: "你要是星期日有空，你就跟我去旅行吧！",
      pinyin: "nǐ yào shì xīng qī rì yǒu kòng nǐ jiù gēn wǒ qù lǚ xíng ba",
      english: "If you are free on sunday, you can travel with me!",
    },
    {
      traditional: "要是下個月不忙，他就回國。",
      simplified: "要是下个月不忙，他就回国。",
      pinyin: "yào shì xià gè yuè bù máng tā jiù huí guó",
      english: "If he is not busy next month, he will return home.",
    },
    {
      traditional: "你要是沒空，我們就不要去逛夜市。",
      simplified: "你要是没空，我们就不要去逛夜市。",
      pinyin: "nǐ yào shì méi kōng wǒ men jiù bú yào qù guàng yè shì",
      english: "If you are not free, we should not go to the night market.",
    },
    {
      traditional: "這杯咖啡很香，你喝喝看。",
      simplified: "这杯咖啡很香，你喝喝看。",
      pinyin: "zhè bēi kā fēi hěn xiāng nǐ hē hē kàn",
      english: "This cup of coffee is very fragrant, you can drink it.",
    },
    {
      traditional: "聽說你唱歌唱的很好，我想聽聽看。",
      simplified: "听说你唱歌唱的很好，我想听听看。",
      pinyin: "tīng shuō nǐ chàng gē chàng dē hěn hǎo wǒ xiǎng tīng tīng kàn",
      english: "I heard that you can sing very well, i want to hear it.",
    },
    {
      traditional: "那家餐廳的菜很好吃，我想去吃吃看。",
      simplified: "那家餐厅的菜很好吃，我想去吃吃看。",
      pinyin: "nà jiā cān tīng dē cài hěn hǎo chī wǒ xiǎng qù chī chī kàn",
      english: "The food in that restaurant is delicious, i want to eat it.",
    },
    {
      traditional: "台灣的夜市很有名，這個週末我想去逛逛看。",
      simplified: "台湾的夜市很有名，这个周末我想去逛逛看。",
      pinyin:
        "tái wān dē yè shì hěn yǒu míng zhè gè zhōu mò wǒ xiǎng qù guàng guàng kàn",
      english:
        "Taiwan’s night markets are very famous. i want to go shopping this weekend.",
    },
    {
      traditional: "這碗牛肉湯想想的。",
      simplified: "这碗牛肉汤想想的。",
      pinyin: "zhè wǎn niú ròu tāng xiǎng xiǎng dē",
      english: "Think about this bowl of beef soup.",
    },
    {
      traditional: "熱熱的咖啡，真香。",
      simplified: "热热的咖啡，真香。",
      pinyin: "rè rè dē kā fēi zhēn xiāng",
      english: "Hot coffee, really fragrant.",
    },
    {
      traditional: "那個地方有很多高高的大樓。",
      simplified: "那个地方有很多高高的大楼。",
      pinyin: "nà gè dì fāng yǒu hěn duō gāo gāo dē dà lóu",
      english: "There are many tall buildings in that place.",
    },
    {
      traditional: "你說得水果是西瓜。",
      simplified: "你说得水果是西瓜。",
      pinyin: "nǐ shuō dé shuǐ guǒ shì xī guā",
      english: "You said the fruit is watermelon.",
    },
    {
      traditional: "他喝的茶是烏龍茶。",
      simplified: "他喝的茶是乌龙茶。",
      pinyin: "tā hē dē chá shì wū lóng chá",
      english: "The tea he drank was oolong tea.",
    },
    {
      traditional: "這些是我拍的照片。",
      simplified: "这些是我拍的照片。",
      pinyin: "zhè xiē shì wǒ pāi dē zhào piān",
      english: "These are the photos i took.",
    },
    {
      traditional: "穿黃衣服的這個人是老闆。",
      simplified: "穿黄衣服的这个人是老板。",
      pinyin: "chuān huáng yī fú dē zhè gè rén shì lǎo bǎn",
      english: "The man in yellow is the boss.",
    },
    {
      traditional: "現在去哪裡玩的人比較少。",
      simplified: "现在去哪里玩的人比较少。",
      pinyin: "xiàn zài qù nǎ lǐ wán dē rén bǐ jiào shǎo",
      english: "Few people go there to play now.",
    },
    {
      traditional: "買這種手機的人很多。",
      simplified: "买这种手机的人很多。",
      pinyin: "mǎi zhè zhǒng shǒu jī dē rén hěn duō",
      english: "Many people buy this kind of mobile phone.",
    },
    {
      traditional: "不能上網的手機很不方便。",
      simplified: "不能上网的手机很不方便。",
      pinyin: "bù néng shàng wǎng dē shǒu jī hěn bù fāng biàn",
      english: "Mobile phones without internet access are very inconvenient.",
    },
    {
      traditional: "不來上課的同學不能去看籃球比賽。",
      simplified: "不来上课的同学不能去看篮球比赛。",
      pinyin: "bù lái shàng kè dē tóng xué bù néng qù kàn lán qiú bǐ sài",
      english:
        "Students who do not come to class cannot go to the basketball game.",
    },
    {
      traditional: "咖啡貴了。",
      simplified: "咖啡贵了。",
      pinyin: "kā fēi guì le",
      english: "Coffee is expensive.",
    },
    {
      traditional: "我會打網球了。",
      simplified: "我会打网球了。",
      pinyin: "wǒ huì dǎ wǎng qiú le",
      english: "I can play tennis.",
    },
    {
      traditional: "現在有手機的人多了。",
      simplified: "现在有手机的人多了。",
      pinyin: "xiàn zài yǒu shǒu jī dē rén duō le",
      english: "There are more people with mobile phones now.",
    },
    {
      traditional: "我現在喜歡吃越南麵了。",
      simplified: "我现在喜欢吃越南面了。",
      pinyin: "wǒ xiàn zài xǐ huān chī yuè nán miàn le",
      english: "I like to eat vietnamese noodles now.",
    },
    {
      traditional: "我媽媽不喝咖啡了。",
      simplified: "我妈妈不喝咖啡了。",
      pinyin: "wǒ mā mā bù hē kā fēi le",
      english: "My mother stops drinking coffee.",
    },
    {
      traditional: "他不想買哪支咖啡了。",
      simplified: "他不想买哪支咖啡了。",
      pinyin: "tā bù xiǎng mǎi nǎ zhī kā fēi le",
      english: "He doesn't want to buy any coffee.",
    },
    {
      traditional: "他不想買那支手機了。",
      simplified: "他不想买那支手机了。",
      pinyin: "tā bù xiǎng mǎi nà zhī shǒu jī le",
      english: "He doesn't want to buy that phone anymore.",
    },
    {
      traditional: "我們不要去參觀故宮了。",
      simplified: "我们不要去参观故宫了。",
      pinyin: "wǒ men bú yào qù cān guān gù gōng le",
      english: "Let's not visit the forbidden city.",
    },
    {
      traditional: "你想吃午餐了嗎？",
      simplified: "你想吃午餐了吗？",
      pinyin: "nǐ xiǎng chī wǔ cān le ma",
      english: "Do you want to eat lunch?",
    },
    {
      traditional: "現在學中文的學生多了嗎？",
      simplified: "现在学中文的学生多了吗？",
      pinyin: "xiàn zài xué zhōng wén dē xué shēng duō le ma",
      english: "Are there many students studying chinese now?",
    },
    {
      traditional: "你們不去台東了嗎？",
      simplified: "你们不去台东了吗？",
      pinyin: "nǐ men bù qù tái dōng le ma",
      english: "Are you not going to taitung?",
    },
    {
      traditional: "因為現在去玩的人比較少，所以旅館不太貴。",
      simplified: "因为现在去玩的人比较少，所以旅馆不太贵。",
      pinyin:
        "yīn wèi xiàn zài qù wán dē rén bǐ jiào shǎo suǒ yǐ lǚ guǎn bù tài guì",
      english:
        "Because there are fewer people going to play now, the hotel is not too expensive.",
    },
    {
      traditional: "因為火車太慢了，所以我想坐高鐵。",
      simplified: "因为火车太慢了，所以我想坐高铁。",
      pinyin: "yīn wèi huǒ chē tài màn le suǒ yǐ wǒ xiǎng zuò gāo tiě",
      english:
        "Because the train is too slow, i want to take the high-speed train.",
    },
    {
      traditional: "因為我不會做飯，所以常去餐廳吃飯。",
      simplified: "因为我不会做饭，所以常去餐厅吃饭。",
      pinyin: "yīn wèi wǒ bù huì zuò fàn suǒ yǐ cháng qù cān tīng chī fàn",
      english:
        "Because i don't know how to cook, i often go to restaurants to eat.",
    },
    {
      traditional: "因為我不知道在那裡賣票，所以想請你幫我買。",
      simplified: "因为我不知道在那里卖票，所以想请你帮我买。",
      pinyin:
        "yīn wèi wǒ bù zhī dào zài nà lǐ mài piào suǒ yǐ xiǎng qǐng nǐ bāng wǒ mǎi",
      english:
        "Because i don't know where the tickets are sold, i would like to ask you to buy them for me.",
    },
    {
      traditional: "我來學中文。",
      simplified: "我来学中文。",
      pinyin: "wǒ lái xué zhōng wén",
      english: "I'm here to learn chinese.",
    },
    {
      traditional: "他來打籃球。",
      simplified: "他来打篮球。",
      pinyin: "tā lái dǎ lán qiú",
      english: "He came to play basketball.",
    },
    {
      traditional: "我和朋友來逛夜市。",
      simplified: "我和朋友来逛夜市。",
      pinyin: "wǒ hé péng yǒu lái guàng yè shì",
      english: "My friends and i came to visit the night market.",
    },
    {
      traditional: "我明天有時不來上課。",
      simplified: "我明天有时不来上课。",
      pinyin: "wǒ míng tiān yǒu shí bù lái shàng kè",
      english: "I sometimes won't come to class tomorrow.",
    },
    {
      traditional: "他不跟我來看電影。",
      simplified: "他不跟我来看电影。",
      pinyin: "tā bù gēn wǒ lái kàn diàn yǐng",
      english: "He doesn't watch movies with me.",
    },
    {
      traditional: "我很忙，不來幫你裝有線電視了。",
      simplified: "我很忙，不来帮你装有线电视了。",
      pinyin: "wǒ hěn máng bù lái bāng nǐ zhuāng yǒu xiàn diàn shì le",
      english: "I'm very busy, so i won't install the cable tv for you.",
    },
    {
      traditional: "他不來吃晚飯嗎？",
      simplified: "他不来吃晚饭吗？",
      pinyin: "tā bù lái chī wǎn fàn ma",
      english: "Isn't he coming for dinner?",
    },
    {
      traditional: "你們常來游泳嗎？",
      simplified: "你们常来游泳吗？",
      pinyin: "nǐ men cháng lái yóu yǒng ma",
      english: "Do you often come to swim?",
    },
    {
      traditional: "你要來參觀故宮博物院嗎？",
      simplified: "你要来参观故宫博物院吗？",
      pinyin: "nǐ yào lái cān guān gù gōng bó wù yuàn ma",
      english: "Are you coming to visit the palace museum?",
    },
    {
      traditional: "我星期四來上書法課。",
      simplified: "我星期四来上书法课。",
      pinyin: "wǒ xīng qī sì lái shàng shū fǎ kè",
      english: "I have a calligraphy class on thursday.",
    },
    {
      traditional: "我妹妹不想來吃牛肉麵。",
      simplified: "我妹妹不想来吃牛肉面。",
      pinyin: "wǒ mèi mei bù xiǎng lái chī niú ròu miàn",
      english: "My sister doesn't want to eat beef noodles.",
    },
    {
      traditional: "學校很近。走路十分鐘就到了。",
      simplified: "学校很近。走路十分钟就到了。",
      pinyin: "xué xiào hěn jìn zǒu lù shí fēn zhōng jiù dào le",
      english: "The school is very close. it's a ten-minute walk.",
    },
    {
      traditional: "那個地方不遠。很快就到了。",
      simplified: "那个地方不远。很快就到了。",
      pinyin: "nà gè dì fāng bù yuǎn hěn kuài jiù dào le",
      english: "That place is not far away. it will be here soon.",
    },
    {
      traditional: "他等一下就來。",
      simplified: "他等一下就来。",
      pinyin: "tā děng yī xià jiù lái",
      english: "He will come in a minute.",
    },
    {
      traditional: "有人住這裡。",
      simplified: "有人住这里。",
      pinyin: "yǒu rén zhù zhè lǐ",
      english: "Someone lives here.",
    },
    {
      traditional: "有兩個學生來找你。",
      simplified: "有两个学生来找你。",
      pinyin: "yǒu liǎng gè xué shēng lái zhǎo nǐ",
      english: "Two students are coming to you.",
    },
    {
      traditional: "早上有一個小姐打電話給你。",
      simplified: "早上有一个小姐打电话给你。",
      pinyin: "zǎo shàng yǒu yī gè xiǎo jiě dǎ diàn huà gěi nǐ",
      english: "A young lady called you this morning.",
    },
    {
      traditional: "昨天有一個先生來裝有線電視。",
      simplified: "昨天有一个先生来装有线电视。",
      pinyin: "zuó tiān yǒu yī gè xiān shēng lái zhuāng yǒu xiàn diàn shì",
      english: "Yesterday, a gentleman came to install the cable tv.",
    },
    {
      traditional: "有一個人在外面唱歌。",
      simplified: "有一个人在外面唱歌。",
      pinyin: "yǒu yī gè rén zài wài miàn chàng gē",
      english: "There was a man singing outside.",
    },
    {
      traditional: "這件沒有人住。",
      simplified: "这件没有人住。",
      pinyin: "zhè jiàn méi yǒu rén zhù",
      english: "No one lives in this one.",
    },
    {
      traditional: "沒有人要跟我去逛夜市。",
      simplified: "没有人要跟我去逛夜市。",
      pinyin: "méi yǒu rén yào gēn wǒ qù guàng yè shì",
      english: "No one wants to go to the night market with me.",
    },
    {
      traditional: "沒有學生要去故宮。",
      simplified: "没有学生要去故宫。",
      pinyin: "méi yǒu xué shēng yào qù gù gōng",
      english: "No students are going to the forbidden city.",
    },
    {
      traditional: "有人在裡面看書嗎？",
      simplified: "有人在里面看书吗？",
      pinyin: "yǒu rén zài lǐ miàn kàn shū ma",
      english: "Is anyone reading in there?",
    },
    {
      traditional: "有沒有人要跟我一起去花蓮玩？",
      simplified: "有没有人要跟我一起去花莲玩？",
      pinyin: "yǒu méi yǒu rén yào gēn wǒ yì qǐ qù huā lián wán",
      english: "Does anyone want to go to hualien with me?",
    },
    {
      traditional: "有沒有人不喜歡吃日本麵？",
      simplified: "有没有人不喜欢吃日本面？",
      pinyin: "yǒu méi yǒu rén bù xǐ huān chī rì běn miàn",
      english: "Does anyone dislike eating japanese noodles?",
    },
    {
      traditional: "地上有一支手機？是誰的？",
      simplified: "地上有一支手机？是谁的？",
      pinyin: "dì shàng yǒu yī zhī shǒu jī shì shuí dē",
      english: "Have a cell phone on the ground? whose?",
    },
    {
      traditional: "有一支手機在地上。地上？為什麼在地上？",
      simplified: "有一支手机在地上。地上？为什么在地上？",
      pinyin:
        "yǒu yī zhī shǒu jī zài dì shàng dì shàng wèi shén me zài dì shàng",
      english:
        "There is a cell phone on the ground. on the ground? why on the ground?",
    },
    {
      traditional: "他會做飯。",
      simplified: "他会做饭。",
      pinyin: "tā huì zuò fàn",
      english: "He can cook.",
    },
    {
      traditional: "我不會打籃球。",
      simplified: "我不会打篮球。",
      pinyin: "wǒ bù huì dǎ lán qiú",
      english: "I can't play basketball.",
    },
    {
      traditional: "我明天會去看看他。",
      simplified: "我明天会去看看他。",
      pinyin: "wǒ míng tiān huì qù kàn kàn tā",
      english: "I will visit him tomorrow.",
    },
    {
      traditional: "他明天不會去上書法課。",
      simplified: "他明天不会去上书法课。",
      pinyin: "tā míng tiān bù huì qù shàng shū fǎ kè",
      english: "He won't go to calligraphy class tomorrow.",
    },
    {
      traditional: "請問，外帶還是內用？",
      simplified: "请问，外带还是内用？",
      pinyin: "qǐng wèn wài dài hái shì nèi yòng",
      english: "Excuse me, take-out or internal use?",
    },
    {
      traditional: "今天晚上要一起吃晚飯嗎？",
      simplified: "今天晚上要一起吃晚饭吗？",
      pinyin: "jīn tiān wǎn shàng yào yì qǐ chī wǎn fàn ma",
      english: "Do you want to have dinner together tonight?",
    },
    {
      traditional: "聽說台灣有很多小吃。",
      simplified: "听说台湾有很多小吃。",
      pinyin: "tīng shuō tái wān yǒu hěn duō xiǎo chī",
      english: "I heard that there are many snacks in taiwan.",
    },
    {
      traditional: "昨天朋友給我一個芒果，我不想吃。",
      simplified: "昨天朋友给我一个芒果，我不想吃。",
      pinyin: "zuó tiān péng yǒu gěi wǒ yī gè máng guǒ wǒ bù xiǎng chī",
      english: "Yesterday my friend gave me a mango, i don’t want to eat it.",
    },
    {
      traditional: "弟弟打算先去旅行在找工作。",
      simplified: "弟弟打算先去旅行在找工作。",
      pinyin: "dì di dǎ suàn xiān qù lǚ xíng zài zhǎo gōng zuò",
      english:
        "The younger brother is going to travel first in search of a job.",
    },
    {
      traditional: "我想先吃完飯再給媽媽打電話。",
      simplified: "我想先吃完饭再给妈妈打电话。",
      pinyin: "wǒ xiǎng xiān chī wán fàn zài gěi mā mā dǎ diàn huà",
      english: "I want to finish my meal before calling my mother.",
    },
    {
      traditional: "他計畫在台灣先學語言在念大學。",
      simplified: "他计画在台湾先学语言在念大学。",
      pinyin: "tā jì huà zài tái wān xiān xué yǔ yán zài niàn dà xué",
      english:
        "He plans to learn languages in taiwan before going to university.",
    },
    {
      traditional: "我昨天晚上先寫功課，在看電視。",
      simplified: "我昨天晚上先写功课，在看电视。",
      pinyin: "wǒ zuó tiān wǎn shàng xiān xiě gōng kè zài kàn diàn shì",
      english: "I did my homework first last night and was watching tv.",
    },
    {
      traditional: "我明天先去圖書館看書，再去超市買東西。",
      simplified: "我明天先去图书馆看书，再去超市买东西。",
      pinyin:
        "wǒ míng tiān xiān qù tú shū guǎn kàn shū zài qù chāo shì mǎi dōng xī",
      english:
        "I will go to the library to read books tomorrow, and then go to the supermarket to buy things.",
    },
    {
      traditional: "他是昨天晚上到台灣的。",
      simplified: "他是昨天晚上到台湾的。",
      pinyin: "tā shì zuó tiān wǎn shàng dào tái wān dē",
      english: "He arrived in taiwan last night.",
    },
    {
      traditional: "他是在學校附近吃晚飯的。",
      simplified: "他是在学校附近吃晚饭的。",
      pinyin: "tā shì zài xué xiào fù jìn chī wǎn fàn dē",
      english: "He ate dinner near the school.",
    },
    {
      traditional: "我是坐捷運來學校的。",
      simplified: "我是坐捷运来学校的。",
      pinyin: "wǒ shì zuò jié yùn lái xué xiào dē",
      english: "I came to school by mrt.",
    },
    {
      traditional: "學費是公司替我付的。",
      simplified: "学费是公司替我付的。",
      pinyin: "xué fèi shì gōng sī tì wǒ fù dē",
      english: "The tuition fee is paid by the company for me.",
    },
    {
      traditional: "這支手機是在夜市買的。",
      simplified: "这支手机是在夜市买的。",
      pinyin: "zhè zhī shǒu jī shì zài yè shì mǎi dē",
      english: "This phone was bought at the night market.",
    },
    {
      traditional: "是我打電話給房東的。",
      simplified: "是我打电话给房东的。",
      pinyin: "shì wǒ dǎ diàn huà gěi fáng dōng dē",
      english: "I called the landlord.",
    },
    {
      traditional: "我是昨天晚上去看電影的。",
      simplified: "我是昨天晚上去看电影的。",
      pinyin: "wǒ shì zuó tiān wǎn shǎng qù kàn diàn yǐng dē",
      english: "I went to the movies last night.",
    },
    {
      traditional: "他是在那家便利商店買咖啡的。",
      simplified: "他是在那家便利商店买咖啡的。",
      pinyin: "tā shì zài nà jiā biàn lì shāng diàn mǎi kā fēi dē",
      english: "He bought coffee at that convenience store.",
    },
    {
      traditional: "我是坐公車來上課的。",
      simplified: "我是坐公车来上课的。",
      pinyin: "wǒ shì zuò gōng chē lái shàng kè dē",
      english: "I came to class by bus.",
    },
    {
      traditional: "他不是今天早上去美國的。",
      simplified: "他不是今天早上去美国的。",
      pinyin: "tā bú shì jīn tiān zǎo shǎng qù měi guó dē",
      english: "He didn't go to america this morning.",
    },
    {
      traditional: "不是我打電話給房東的。",
      simplified: "不是我打电话给房东的。",
      pinyin: "bú shì wǒ dǎ diàn huà gěi fáng dōng dē",
      english: "I didn’t call the landlord.",
    },
    {
      traditional: "我不是在圖書館看書的。",
      simplified: "我不是在图书馆看书的。",
      pinyin: "wǒ bú shì zài tú shū guǎn kàn shū dē",
      english: "I am not reading in the library.",
    },
    {
      traditional: "你是一個人來的嗎？",
      simplified: "你是一个人来的吗？",
      pinyin: "nǐ shì yī gè rén lái dē ma",
      english: "Are you here alone?",
    },
    {
      traditional: "他是坐高鐵去台南的嗎？",
      simplified: "他是坐高铁去台南的吗？",
      pinyin: "tā shì zuò gāo tiě qù tái nán dē ma",
      english: "Did he go to tainan by high-speed rail?",
    },
    {
      traditional: "你的房租是自己付的嗎？",
      simplified: "你的房租是自己付的吗？",
      pinyin: "nǐ dē fáng zū shì zì jǐ fù dē ma",
      english: "Do you pay the rent yourself?",
    },
    {
      traditional: "我跟朋友一起來的。",
      simplified: "我跟朋友一起来的。",
      pinyin: "wǒ gēn péng yǒu yì qǐ lái dē",
      english: "I came with a friend.",
    },
    {
      traditional: "我坐計程車來的。",
      simplified: "我坐计程车来的。",
      pinyin: "wǒ zuò jì chéng chē lái dē",
      english: "I came by taxi.",
    },
    {
      traditional: "是誰打電話給你的？",
      simplified: "是谁打电话给你的？",
      pinyin: "shì shuí dǎ diàn huà gěi nǐ dē",
      english: "Who called you?",
    },
    {
      traditional: "他是什麼時候來學校的？",
      simplified: "他是什么时候来学校的？",
      pinyin: "tā shì shén me shí hòu lái xué xiào dē",
      english: "When did he come to school?",
    },
    {
      traditional: "你是怎麼去的？",
      simplified: "你是怎么去的？",
      pinyin: "nǐ shì zěn me qù dē",
      english: "How did you go?",
    },
    {
      traditional: "你是在那裡吃飯的？",
      simplified: "你是在那里吃饭的？",
      pinyin: "nǐ shì zài nà lǐ chī fàn dē",
      english: "Where did you eat?",
    },
    {
      traditional: "我們以後都得上班。",
      simplified: "我们以后都得上班。",
      pinyin: "wǒ men yǐ hòu dōu dé shàng bān",
      english: "We all have to go to work in the future.",
    },
    {
      traditional: "他們以後還要再到台南去。",
      simplified: "他们以后还要再到台南去。",
      pinyin: "tā men yǐ hòu hái yào zài dào tái nán qù",
      english: "They will go to tainan again in the future.",
    },
    {
      traditional: "回國以後，我要找個有機會說中文的工作。",
      simplified: "回国以后，我要找个有机会说中文的工作。",
      pinyin:
        "huí guó yǐ hòu wǒ yào zhǎo gè yǒu jī huì shuō zhōng wén dē gōng zuò",
      english:
        "After returning to china, i will find a job where i have the opportunity to speak chinese.",
    },
    {
      traditional: "來台灣以後，我每星期上五天的中文課。",
      simplified: "来台湾以后，我每星期上五天的中文课。",
      pinyin: "lái tái wān yǐ hòu wǒ měi xīng qī shàng wǔ tiān dē zhōng wén kè",
      english:
        "After coming to taiwan, i have chinese classes five days a week.",
    },
    {
      traditional: "我下課以後，常在圖書館上網。",
      simplified: "我下课以后，常在图书馆上网。",
      pinyin: "wǒ xià kè yǐ hòu cháng zài tú shū guǎn shàng wǎng",
      english: "After class, i often go online in the library.",
    },
    {
      traditional: "日本菜好吃也好看。",
      simplified: "日本菜好吃也好看。",
      pinyin: "rì běn cài hǎo chī yě hǎo kàn",
      english: "Japanese food is delicious and beautiful.",
    },
    {
      traditional: "好工作很難找。",
      simplified: "好工作很难找。",
      pinyin: "hǎo gōng zuò hěn nán zhǎo",
      english: "A good job is hard to find.",
    },
    {
      traditional: "這個歌好聽也好唱。",
      simplified: "这个歌好听也好唱。",
      pinyin: "zhè gè gē hǎo tīng yě hǎo chàng",
      english: "This song is nice and easy to sing.",
    },
    {
      traditional: "我媽媽做的菜很好吃。",
      simplified: "我妈妈做的菜很好吃。",
      pinyin: "wǒ mā mā zuò dē cài hěn hǎo chī",
      english: "My mother's dishes are delicious.",
    },
    {
      traditional: "有人覺得中文很難學。",
      simplified: "有人觉得中文很难学。",
      pinyin: "yǒu rén jué dé zhòng wén hěn nán xué",
      english: "Some people find it difficult to learn chinese.",
    },
    {
      traditional: "便宜的咖啡不好喝。",
      simplified: "便宜的咖啡不好喝。",
      pinyin: "pián yí dē kā fēi bù hǎo hē",
      english: "Cheap coffee is not good.",
    },
    {
      traditional: "學校餐廳的菜不難吃。",
      simplified: "学校餐厅的菜不难吃。",
      pinyin: "xué xiào cān tīng dē cài bù nán chī",
      english: "The food in the school cafeteria is not unpalatable.",
    },
    {
      traditional: "這個歌，唱的太慢不好聽。",
      simplified: "这个歌，唱的太慢不好听。",
      pinyin: "zhè gè gē chàng dē tài màn bù hǎo tīng",
      english: "This song is too slow to be sung.",
    },
    {
      traditional: "這家店買的小籠包不好做。",
      simplified: "这家店买的小笼包不好做。",
      pinyin: "zhè jiā diàn mǎi dē xiǎo lóng bāo bù hǎo zuò",
      english: "The dumplings bought in this shop are not easy to make.",
    },
    {
      traditional: "老師常常說中文不難學。",
      simplified: "老师常常说中文不难学。",
      pinyin: "lǎo shī cháng cháng shuō zhōng wén bù nán xué",
      english: "Teachers often say that chinese is not difficult to learn.",
    },
    {
      traditional: "學校附近便宜的套房不好找。",
      simplified: "学校附近便宜的套房不好找。",
      pinyin: "xué xiào fù jìn pián yí dē tào fáng bù hǎo zhǎo",
      english: "Cheap suites near the school are hard to find.",
    },
    {
      traditional: "旅館老闆賣的水果好吃嗎？",
      simplified: "旅馆老板卖的水果好吃吗？",
      pinyin: "lǚ guǎn lǎo bǎn mài dē shuǐ guǒ hǎo chī ma",
      english: "Is the fruit sold by the hotel owner delicious?",
    },
    {
      traditional: "你覺得那個電影好不好看？",
      simplified: "你觉得那个电影好不好看？",
      pinyin: "nǐ jué dé nà gè diàn yǐng hǎo bù hǎo kàn",
      english: "Do you think that movie is good?",
    },
    {
      traditional: "點烏龍茶的那個先生唱歌唱餓得好聽嗎？",
      simplified: "点乌龙茶的那个先生唱歌唱饿得好听吗？",
      pinyin:
        "diǎn wū lóng chá dē nà gè xiān shēng chàng gē chàng è dé hǎo tīng ma",
      english:
        "Is the gentleman who ordered oolong tea singing and singing so hungry?",
    },
    {
      traditional: "說中文的工作在你的國家好找嗎？",
      simplified: "说中文的工作在你的国家好找吗？",
      pinyin: "shuō zhōng wén dē gōng zuò zài nǐ dē guó jiā hǎo zhǎo ma",
      english: "Is a chinese-speaking job easy to find in your country?",
    },
    {
      traditional: "又大又貴的房子好不好賣？",
      simplified: "又大又贵的房子好不好卖？",
      pinyin: "yòu dà yòu guì dē fáng zi hǎo bù hǎo mài",
      english: "Can a big and expensive house sell well?",
    },
    {
      traditional: "老師今天教的甜點難不難學？",
      simplified: "老师今天教的甜点难不难学？",
      pinyin: "lǎo shī jīn tiān jiào dē tián diǎn nán bù nán xué",
      english: "Is it difficult to learn the dessert the teacher taught today?",
    },
    {
      traditional: "我一下課，就回來。",
      simplified: "我一下课，就回来。",
      pinyin: "wǒ yī xià kè jiù huí lái",
      english: "I'll be back after class.",
    },
    {
      traditional: "他已回國，就找工作。",
      simplified: "他已回国，就找工作。",
      pinyin: "tā yǐ huí guó jiù zhǎo gōng zuò",
      english: "He has returned to china and is looking for a job.",
    },
    {
      traditional: "我妹妹一回去，就給媽媽打電話。",
      simplified: "我妹妹一回去，就给妈妈打电话。",
      pinyin: "wǒ mèi mei yī huí qù jiù gěi mā mā dǎ diàn huà",
      english: "As soon as my sister went back, she called her mother.",
    },
    {
      traditional: "我一下課，就去吃晚飯。",
      simplified: "我一下课，就去吃晚饭。",
      pinyin: "wǒ yī xià kè jiù qù chī wǎn fàn",
      english: "I will go to dinner after class.",
    },
    {
      traditional: "他打算等那裡一枚人，就去拍照。",
      simplified: "他打算等那里一枚人，就去拍照。",
      pinyin: "tā dǎ suàn děng nà lǐ yī méi rén jiù qù pāi zhào",
      english: "He planned to wait for someone there to take pictures.",
    },
    {
      traditional: "老闆今天早上一到公司，就不開心。",
      simplified: "老板今天早上一到公司，就不开心。",
      pinyin: "lǎo bǎn jīn tiān zǎo shàng yí dào gōng sī jiù bù kāi xīn",
      english:
        "The boss was unhappy when he arrived at the company this morning.",
    },
    {
      traditional: "他一下課，就去學校找你嗎？",
      simplified: "他一下课，就去学校找你吗？",
      pinyin: "tā yī xià kè jiù qù xué xiào zhǎo nǐ ma",
      english: "Does he go to school to look for you after class?",
    },
    {
      traditional: "我們今天是不是比賽一結束，就一起去KTV唱歌？",
      simplified: "我们今天是不是比赛一结束，就一起去KTV唱歌？",
      pinyin:
        "wǒ men jīn tiān shì bú shì bǐ sài yī jié shù jiù yì qǐ qù chàng gē",
      english:
        "Are we going to ktv to sing together as soon as the competition is over today?",
    },
    {
      traditional: "我買了三張車票。",
      simplified: "我买了三张车票。",
      pinyin: "wǒ mǎi le sān zhāng chē piào",
      english: "I bought three tickets.",
    },
    {
      traditional: "我要買三張車票。",
      simplified: "我要买三张车票。",
      pinyin: "wǒ yào mǎi sān zhāng chē piào",
      english: "I want to buy three tickets.",
    },
    {
      traditional: "我剛在便利商店喝了咖啡。",
      simplified: "我刚在便利商店喝了咖啡。",
      pinyin: "wǒ gāng zài biàn lì shāng diàn hē le kā fēi",
      english: "I just drank coffee at the convenience store.",
    },
    {
      traditional: "我昨天吃了很多東西。",
      simplified: "我昨天吃了很多东西。",
      pinyin: "wǒ zuó tiān chī le hěn duō dōng xī",
      english: "I ate a lot yesterday.",
    },
    {
      traditional: "今天早上我喝了一杯咖啡。",
      simplified: "今天早上我喝了一杯咖啡。",
      pinyin: "jīn tiān zǎo shàng wǒ hē le yī bēi kā fēi",
      english: "I had a cup of coffee this morning.",
    },
    {
      traditional: "她租了一個漂亮的房子。",
      simplified: "她租了一个漂亮的房子。",
      pinyin: "tā zū le yī gè piào liàng dē fáng zi",
      english: "She rented a beautiful house.",
    },
    {
      traditional: "我今天沒吃午餐。",
      simplified: "我今天没吃午餐。",
      pinyin: "wǒ jīn tiān méi chī wǔ cān",
      english: "I didn't eat lunch today.",
    },
    {
      traditional: "我我最近很忙，一星期都沒看電視。",
      simplified: "我我最近很忙，一星期都没看电视。",
      pinyin: "wǒ wǒ zuì jìn hěn máng yī xīng qī dōu méi kàn diàn shì",
      english: "I am very busy recently and haven't watched tv for a week.",
    },
    {
      traditional: "昨天跟朋友去過生日，所以我沒寫功課。",
      simplified: "昨天跟朋友去过生日，所以我没写功课。",
      pinyin: "zuó tiān gēn péng yǒu qù guò shēng rì suǒ yǐ wǒ méi xiě gōng kè",
      english:
        "Yesterday i went to my birthday with my friend, so i didn't write my homework.",
    },
    {
      traditional: "弟弟吃了午餐沒有？",
      simplified: "弟弟吃了午餐没有？",
      pinyin: "dì di chī le wǔ cān méi yǒu",
      english: "Did your brother eat lunch?",
    },
    {
      traditional: "下個月的學費，她付了沒有？",
      simplified: "下个月的学费，她付了没有？",
      pinyin: "xià gè yuè dē xué fèi tā fù le méi yǒu",
      english: "Has she paid the tuition for next month?",
    },
    {
      traditional: "今晚的籃球比賽開始了沒有？",
      simplified: "今晚的篮球比赛开始了没有？",
      pinyin: "jīn wǎn dē lán qiú bǐ sài kāi shǐ le méi yǒu",
      english: "Has the basketball game started tonight?",
    },
    {
      traditional: "我沒吃晚飯。",
      simplified: "我没吃晚饭。",
      pinyin: "wǒ méi chī wǎn fàn",
      english: "I didn't eat dinner.",
    },
    {
      traditional: "我們星期六不上課。",
      simplified: "我们星期六不上课。",
      pinyin: "wǒ men xīng qī liù bù shàng kè",
      english: "We do not have classes on saturday.",
    },
    {
      traditional: "學生常不吃早餐。",
      simplified: "学生常不吃早餐。",
      pinyin: "xué shēng cháng bù chī zǎo cān",
      english: "Students often skip breakfast.",
    },
    {
      traditional: "我不去圖書館。",
      simplified: "我不去图书馆。",
      pinyin: "wǒ bù qù tú shū guǎn",
      english: "I don't go to the library.",
    },
    {
      traditional: "他不找工作。",
      simplified: "他不找工作。",
      pinyin: "tā bù zhǎo gōng zuò",
      english: "He is not looking for work.",
    },
    {
      traditional: "昨天我沒打電話給他。",
      simplified: "昨天我没打电话给他。",
      pinyin: "zuó tiān wǒ méi dǎ diàn huà gěi tā",
      english: "I didn't call him yesterday.",
    },
    {
      traditional: "上個星期我沒跟同學去KTV。",
      simplified: "上个星期我没跟同学去KTV。",
      pinyin: "shàng gè xīng qī wǒ méi gēn tóng xué qù",
      english: "I didn't go to ktv with my classmates last week.",
    },
    {
      traditional: "今天我沒坐捷運來上課。我坐公車。",
      simplified: "今天我没坐捷运来上课。我坐公车。",
      pinyin: "jīn tiān wǒ méi zuò jié yùn lái shàng kè wǒ zuò gōng chē",
      english: "I didn't take the mrt to come to class today. i take the bus.",
    },
    {
      traditional: "今天不熱，我想出去逛逛。",
      simplified: "今天不热，我想出去逛逛。",
      pinyin: "jīn tiān bù rè wǒ xiǎng chū qù guàng guàng",
      english: "It's not hot today, i want to go out and stroll around.",
    },
    {
      traditional: "他說中文不難學，可是中國字不好寫。",
      simplified: "他说中文不难学，可是中国字不好写。",
      pinyin: "tā shuō zhōng wén bù nán xué kě shì zhōng guó zì bù hǎo xiě",
      english:
        "He said that chinese is not difficult to learn, but chinese characters are not easy to write.",
    },
    {
      traditional: "我不舒服，今天不想出去。",
      simplified: "我不舒服，今天不想出去。",
      pinyin: "wǒ bù shū fu jīn tiān bù xiǎng chū qù",
      english: "I'm sick and don't want to go out today.",
    },
    {
      traditional: "中文可還沒結束，所以我不能回國。",
      simplified: "中文可还没结束，所以我不能回国。",
      pinyin: "zhōng wén kě hái méi jié shù suǒ yǐ wǒ bù néng huí guó",
      english: "Chinese is not over yet, so i can't go back to my country.",
    },
    {
      traditional: "我沒忘。你先去學校，我等一下去找你。",
      simplified: "我没忘。你先去学校，我等一下去找你。",
      pinyin: "wǒ méi wàng nǐ xiān qù xué xiào wǒ děng yī xià qù zhǎo nǐ",
      english: "I did not forget. you go to school first, i'll find you later.",
    },
    {
      traditional: "我還沒決定要不要去旅行。",
      simplified: "我还没决定要不要去旅行。",
      pinyin: "wǒ hái méi jué dìng yào bú yào qù lǚ xíng",
      english: "I haven't decided whether to travel or not.",
    },
    {
      traditional: "誰都喜歡去旅行。",
      simplified: "谁都喜欢去旅行。",
      pinyin: "shuí dōu xǐ huān qù lǚ xíng",
      english: "Everyone likes to travel.",
    },
    {
      traditional: "哪裡都有好吃的東西。",
      simplified: "哪里都有好吃的东西。",
      pinyin: "nǎ lǐ dōu yǒu hǎo chī dē dōng xī",
      english: "There are delicious things everywhere.",
    },
    {
      traditional: "他什麼都想買。",
      simplified: "他什么都想买。",
      pinyin: "tā shén me dōu xiǎng mǎi",
      english: "He wants to buy everything.",
    },
    {
      traditional: "弟弟什麼時候都在上網。",
      simplified: "弟弟什么时候都在上网。",
      pinyin: "dì di shén me shí hòu dōu zài shàng wǎng",
      english: "The younger brother is online anytime.",
    },
    {
      traditional: "他們學校很方便，怎麼去都能到。",
      simplified: "他们学校很方便，怎么去都能到。",
      pinyin: "tā men xué xiào hěn fāng biàn zěn me qù dōu néng dào",
      english:
        "Their school is very convenient and they can be reached wherever they go.",
    },
    {
      traditional: "誰也不喜歡難看的東西。",
      simplified: "谁也不喜欢难看的东西。",
      pinyin: "shuí yě bù xǐ huān nán kàn dē dōng xī",
      english: "No one likes ugly things.",
    },
    {
      traditional: "昨天我哪裡都沒去，在家看電視。",
      simplified: "昨天我哪里都没去，在家看电视。",
      pinyin: "zuó tiān wǒ nǎ lǐ dōu méi qù zài jiā kàn diàn shì",
      english: "I didn't go anywhere yesterday, watching tv at home.",
    },
    {
      traditional: "我今天什麼也不想吃。",
      simplified: "我今天什么也不想吃。",
      pinyin: "wǒ jīn tiān shén me yě bù xiǎng chī",
      english: "I don't want to eat anything today.",
    },
    {
      traditional: "下個星期，我什麼時候都不在家，我要去旅行。",
      simplified: "下个星期，我什么时候都不在家，我要去旅行。",
      pinyin:
        "xià gè xīng qī wǒ shén me shí hòu dōu bù zài jiā wǒ yào qù lǚ xíng",
      english:
        "Next week, i will not be at home any time, i am going to travel.",
    },
    {
      traditional: "中國才很難做，我怎麼做都不好吃。",
      simplified: "中国才很难做，我怎么做都不好吃。",
      pinyin: "zhōng guó cái hěn nán zuò wǒ zěn me zuò dōu bù hǎo chī",
      english:
        "It's hard to make in china. no matter how i make it, it doesn't taste good.",
    },
    {
      traditional: "這家餐廳的東西什麼都好吃嗎？",
      simplified: "这家餐厅的东西什么都好吃吗？",
      pinyin: "zhè jiā cān tīng dē dōng xī shén me dōu hǎo chī ma",
      english: "Is everything in this restaurant delicious?",
    },
    {
      traditional: "你今天什麼時候都在公司嗎？",
      simplified: "你今天什么时候都在公司吗？",
      pinyin: "nǐ jīn tiān shén me shí hòu dōu zài gōng sī ma",
      english: "Are you at the company anytime today?",
    },
    {
      traditional: "我最近沒錢了，應該少買東西。",
      simplified: "我最近没钱了，应该少买东西。",
      pinyin: "wǒ zuì jìn méi qián le yīng gāi shǎo mǎi dōng xī",
      english: "I have run out of money recently, so i should buy less things.",
    },
    {
      traditional: "我中文不好，應該多看書，少看電視。",
      simplified: "我中文不好，应该多看书，少看电视。",
      pinyin: "wǒ zhōng wén bù hǎo yīng gāi duō kàn shū shǎo kàn diàn shì",
      english:
        "My chinese is not good, so i should read more and watch less tv.",
    },
    {
      traditional: "我們明天應該多穿衣服嗎？",
      simplified: "我们明天应该多穿衣服吗？",
      pinyin: "wǒ men míng tiān yīng gāi duō chuān yī fu ma",
      english: "Should we wear more clothes tomorrow?",
    },
    {
      traditional: "他喜歡台灣，想多學一點中文。",
      simplified: "他喜欢台湾，想多学一点中文。",
      pinyin: "tā xǐ huān tái wān xiǎng duō xué yī diǎn zhōng wén",
      english: "He likes taiwan and wants to learn more chinese.",
    },
    {
      traditional: "昨天我朋友來我家，我多做了一點菜。",
      simplified: "昨天我朋友来我家，我多做了一点菜。",
      pinyin: "zuó tiān wǒ péng yǒu lái wǒ jiā wǒ duō zuò le yī diǎn cài",
      english:
        "Yesterday my friend came to my house and i cooked a little more.",
    },
    {
      traditional: "他今天太累了，想少做一點功課。",
      simplified: "他今天太累了，想少做一点功课。",
      pinyin: "tā jīn tiān tài lèi le xiǎng shǎo zuò yī diǎn gōng kè",
      english: "He is too tired today and wants to do a little less homework.",
    },
    {
      traditional: "你是不是家等我？",
      simplified: "你是不是家等我？",
      pinyin: "nǐ shì bú shì jiā děng wǒ",
      english: "Are you waiting for me at home?",
    },
    {
      traditional: "那家餐廳是不是很有名？",
      simplified: "那家餐厅是不是很有名？",
      pinyin: "nà jiā cān tīng shì bú shì hěn yǒu míng",
      english: "Is that restaurant very famous?",
    },
    {
      traditional: "你是不是剛旅行回來？",
      simplified: "你是不是刚旅行回来？",
      pinyin: "nǐ shì bú shì gāng lǚ xíng huí lái",
      english: "Did you just come back from a trip?",
    },
    {
      traditional: "你銀行有錢嗎？",
      simplified: "你银行有钱吗？",
      pinyin: "nǐ yín xíng yǒu qián ma",
      english: "Is your bank rich?",
    },
    {
      traditional: "你銀行有沒有錢？",
      simplified: "你银行有没有钱？",
      pinyin: "nǐ yín xíng yǒu méi yǒu qián",
      english: "Do you have money in your bank?",
    },
    {
      traditional: "你銀行是不是有錢？",
      simplified: "你银行是不是有钱？",
      pinyin: "nǐ yín xíng shì bú shì yǒu qián",
      english: "Is your bank rich?",
    },
    {
      traditional: "你比他高。你是不是比他高？",
      simplified: "你比他高。你是不是比他高？",
      pinyin: "nǐ bǐ tā gāo nǐ shì bú shì bǐ tā gāo",
      english: "You are taller than him. are you taller than him?",
    },
    {
      traditional: "你最近太忙了。你是不是最近太忙了？",
      simplified: "你最近太忙了。你是不是最近太忙了？",
      pinyin: "nǐ zuì jìn tài máng le nǐ shì bú shì zuì jìn tài máng le",
      english: "You have been too busy lately. are you too busy lately?",
    },
    {
      traditional: "這支手機跟那隻手機一樣。",
      simplified: "这支手机跟那只手机一样。",
      pinyin: "zhè zhī shǒu jī gēn nà zhī shǒu jī yī yàng",
      english: "This phone is the same as that one.",
    },
    {
      traditional: "我的生日跟他的生日一樣，都是八月十七日。",
      simplified: "我的生日跟他的生日一样，都是八月十七日。",
      pinyin:
        "wǒ dē shēng rì gēn tā dē shēng rì yī yàng dōu shì bā yuè shí qī rì",
      english: "My birthday is the same as his birthday, both on august 17.",
    },
    {
      traditional: "他跟我一樣，都常有用。",
      simplified: "他跟我一样，都常有用。",
      pinyin: "tā gēn wǒ yī yàng dōu cháng yǒu yòng",
      english: "Like me, he is often useful.",
    },
    {
      traditional: "你點的菜跟我點的一樣。",
      simplified: "你点的菜跟我点的一样。",
      pinyin: "nǐ diǎn dē cài gēn wǒ diǎn dē yī yàng",
      english: "The food you ordered is the same as mine.",
    },
    {
      traditional: "我跟我妹妹一樣高。",
      simplified: "我跟我妹妹一样高。",
      pinyin: "wǒ gēn wǒ mèi mei yī yàng gāo",
      english: "I am as tall as my sister.",
    },
    {
      traditional: "姐姐租的房子跟我租的一樣貴。",
      simplified: "姐姐租的房子跟我租的一样贵。",
      pinyin: "jiě jie zū dē fáng zi gēn wǒ zū dē yī yàng guì",
      english: "The house my sister rents is as expensive as mine.",
    },
    {
      traditional: "我跟我朋友一樣喜歡看電視。",
      simplified: "我跟我朋友一样喜欢看电视。",
      pinyin: "wǒ gēn wǒ péng yǒu yī yàng xǐ huān kàn diàn shì",
      english: "I like watching tv as much as my friends.",
    },
    {
      traditional: "中國茶跟日本茶不一樣。",
      simplified: "中国茶跟日本茶不一样。",
      pinyin: "zhōng guó chá gēn rì běn chá bù yī yàng",
      english: "Chinese tea is not the same as japanese tea.",
    },
    {
      traditional: "我跟妹妹不一樣高。",
      simplified: "我跟妹妹不一样高。",
      pinyin: "wǒ gēn mèi mei bù yī yàng gāo",
      english: "I am not the same height as my sister.",
    },
    {
      traditional: "他不跟我一樣高，跟小王一樣高。",
      simplified: "他不跟我一样高，跟小王一样高。",
      pinyin: "tā bù gēn wǒ yī yàng gāo gēn xiǎo wáng yī yàng gāo",
      english: "He is not as tall as me, as tall as xiao wang.",
    },
    {
      traditional: "小籠包跟包子一樣不一樣？",
      simplified: "小笼包跟包子一样不一样？",
      pinyin: "xiǎo lóng bāo gēn bāo zi yī yàng bù yī yàng",
      english: "Xiaolongbao is different from steamed buns?",
    },
    {
      traditional: "小籠包跟包子是不是一樣？？",
      simplified: "小笼包跟包子是不是一样？ ？",
      pinyin: "xiǎo lóng bāo gēn bāo zi shì bú shì yī yàng",
      english: "Is xiaolongbao the same as steamed buns? ?",
    },
    {
      traditional: "幾年的生意是不是跟去年的一樣好？",
      simplified: "几年的生意是不是跟去年的一样好？",
      pinyin: "jǐ nián dē shēng yì shì bú shì gēn qù nián dē yī yàng hǎo",
      english:
        "Has the business in the past few years been as good as last year?",
    },
    {
      traditional: "說中文跟寫中文是不是一樣難？",
      simplified: "说中文跟写中文是不是一样难？",
      pinyin: "shuō zhōng wén gēn xiě zhōng wén shì bú shì yī yàng nán",
      english: "Is speaking chinese as difficult as writing chinese?",
    },
    {
      traditional: "媽媽的朋友在台北玩了三天。",
      simplified: "妈妈的朋友在台北玩了三天。",
      pinyin: "mā mā dē péng yǒu zài tái běi wán le sān tiān",
      english: "Mom's friend spent three days in taipei.",
    },
    {
      traditional: "老師在美國住了一年。",
      simplified: "老师在美国住了一年。",
      pinyin: "lǎo shī zài měi guó zhù le yī nián",
      english: "The teacher lived in the united states for a year.",
    },
    {
      traditional: "李小姐在語言中心工作了一個月。",
      simplified: "李小姐在语言中心工作了一个月。",
      pinyin: "lǐ xiǎo jiě zài yǔ yán zhōng xīn gōng zuò le yī gè yuè",
      english: "Ms. li worked in the language center for a month.",
    },
    {
      traditional: "她租房子租了半年。",
      simplified: "她租房子租了半年。",
      pinyin: "tā zū fáng zi zū le bàn nián",
      english: "She rented a house for six months.",
    },
    {
      traditional: "他住台北住了三年。",
      simplified: "他住台北住了三年。",
      pinyin: "tā zhù tái běi zhù le sān nián",
      english: "He lived in taipei for three years.",
    },
    {
      traditional: "房子他只租了半年。",
      simplified: "房子他只租了半年。",
      pinyin: "fáng zi tā zhǐ zū le bàn nián",
      english: "He only rented the house for half a year.",
    },
    {
      traditional: "台北他只住了三年。",
      simplified: "台北他只住了三年。",
      pinyin: "tái běi tā zhǐ zhù le sān nián",
      english: "He only lived in taipei for three years.",
    },
    {
      traditional: "那間房子你租了一年半嗎？",
      simplified: "那间房子你租了一年半吗？",
      pinyin: "nà jiān fáng zi nǐ zū le yī nián bàn ma",
      english: "Have you rented that house for a year and a half?",
    },
    {
      traditional: "你是不是在這裡等了一個鐘頭？",
      simplified: "你是不是在这里等了一个钟头？",
      pinyin: "nǐ shì bú shì zài zhè lǐ děng le yī gè zhōng tóu",
      english: "Did you wait here for an hour?",
    },
    {
      traditional: "陳老闆去年是不是在紐約住了半年？",
      simplified: "陈老板去年是不是在纽约住了半年？",
      pinyin: "chén lǎo bǎn qù nián shì bú shì zài niǔ yuē zhù le bàn nián",
      english: "Did boss chen live in new york for half a year last year?",
    },
    {
      traditional: "他已經在台灣玩了一年了。",
      simplified: "他已经在台湾玩了一年了。",
      pinyin: "tā yǐ jīng zài tái wān wán le yī nián le",
      english: "He has been playing in taiwan for a year.",
    },
    {
      traditional: "陳小姐在美國住了五年了。",
      simplified: "陈小姐在美国住了五年了。",
      pinyin: "chén xiǎo jiě zài měi guó zhù le wǔ nián le",
      english: "Miss chen has lived in the united states for five years.",
    },
    {
      traditional: "我工作了兩個月了。",
      simplified: "我工作了两个月了。",
      pinyin: "wǒ gōng zuò le liǎng gè yuè le",
      english: "I have been working for two months.",
    },
    {
      traditional: "這間房子，他亦盈租了半年了。",
      simplified: "这间房子，他亦盈租了半年了。",
      pinyin: "zhè jiān fáng zi tā yì yíng zū le bàn nián le",
      english: "He has rented this house for half a year.",
    },
    {
      traditional: "他們學中文學了三個星期了。",
      simplified: "他们学中文学了三个星期了。",
      pinyin: "tā men xué zhōng wén xué le sān gè xīng qī le",
      english: "They have been studying chinese literature for three weeks.",
    },
    {
      traditional: "快下雨了。",
      simplified: "快下雨了。",
      pinyin: "kuài xià yǔ le",
      english: "It's raining soon.",
    },
    {
      traditional: "電影要結束了。",
      simplified: "电影要结束了。",
      pinyin: "diàn yǐng yào jié shù le",
      english: "The movie is about to end.",
    },
    {
      traditional: "爸爸快要到家了。",
      simplified: "爸爸快要到家了。",
      pinyin: "bà bà kuài yào dào jiā le",
      english: "Dad is going home soon.",
    },
    {
      traditional: "你媽媽的生日快到了嗎？",
      simplified: "你妈妈的生日快到了吗？",
      pinyin: "nǐ mā mā dē shēng rì kuài dào le ma",
      english: "Is your mother's birthday coming soon?",
    },
    {
      traditional: "比賽要開始了嗎？",
      simplified: "比赛要开始了吗？",
      pinyin: "bǐ sài yào kāi shǐ le ma",
      english: "Is the game about to start?",
    },
    {
      traditional: "哥哥的女朋友快要會法國了嗎？",
      simplified: "哥哥的女朋友快要会法国了吗？",
      pinyin: "gē ge dē nǚ péng yǒu kuài yào huì fǎ guó le ma",
      english: "Is your brother's girlfriend going to meet france soon?",
    },
    {
      traditional: "她很高，他哥哥比他更高。",
      simplified: "她很高，他哥哥比他更高。",
      pinyin: "tā hěn gāo tā gē ge bǐ tā gèng gāo",
      english: "She is tall, and his brother is taller than him.",
    },
    {
      traditional: "今年比去年更冷。",
      simplified: "今年比去年更冷。",
      pinyin: "jīn nián bǐ qù nián gèng lěng",
      english: "This year is colder than last year.",
    },
    {
      traditional: "我覺得芒果比西瓜更好吃。",
      simplified: "我觉得芒果比西瓜更好吃。",
      pinyin: "wǒ jué dé máng guǒ bǐ xī guā gèng hǎo chī",
      english: "I think mango is better than watermelon.",
    },
    {
      traditional: "這次的颱風是不是比上次的更大？",
      simplified: "这次的台风是不是比上次的更大？",
      pinyin: "zhè cì dē tái fēng shì bú shì bǐ shàng cì dē gèng dà",
      english: "Is this typhoon bigger than the last one?",
    },
    {
      traditional: "在學校上網是不是比在家裡更快？",
      simplified: "在学校上网是不是比在家里更快？",
      pinyin: "zài xué xiào shàng wǎng shì bú shì bǐ zài jiā lǐ gèng kuài",
      english: "Is the internet faster at school than at home?",
    },
    {
      traditional: "哥哥沒有爸爸那麼高。",
      simplified: "哥哥没有爸爸那么高。",
      pinyin: "gē ge méi yǒu bà bà nà me gāo",
      english: "My brother is not as tall as my father.",
    },
    {
      traditional: "火車沒有高鐵那麼快。",
      simplified: "火车没有高铁那么快。",
      pinyin: "huǒ chē méi yǒu gāo tiě nà me kuài",
      english: "The train is not as fast as the high-speed rail.",
    },
    {
      traditional: "我的中文沒有老師的那麼好。",
      simplified: "我的中文没有老师的那么好。",
      pinyin: "wǒ dē zhōng wén méi yǒu lǎo shī dē nà me hǎo",
      english: "My chinese is not as good as the teacher's.",
    },
    {
      traditional: "臭豆腐沒有牛肉麵這麼好吃。",
      simplified: "臭豆腐没有牛肉面这么好吃。",
      pinyin: "chòu dòu fǔ méi yǒu niú ròu miàn zhè me hǎo chī",
      english: "Stinky tofu is not as delicious as beef noodles.",
    },
    {
      traditional: "甜點沒有小籠包那麼好做。",
      simplified: "甜点没有小笼包那么好做。",
      pinyin: "tián diǎn méi yǒu xiǎo lóng bāo nà me hǎo zuò",
      english: "Dessert is not as good as xiaolongbao.",
    },
    {
      traditional: "這次的颱風沒有上次的那麼可怕。",
      simplified: "这次的台风没有上次的那么可怕。",
      pinyin: "zhè cì dē tái fēng méi yǒu shàng cì dē nà me kě pà",
      english: "This typhoon was not as terrible as the last one.",
    },
    {
      traditional: "妹妹有沒有姐姐那麼漂亮？",
      simplified: "妹妹有没有姐姐那么漂亮？",
      pinyin: "mèi mei yǒu méi yǒu jiě jie nà me piào liàng",
      english: "Is the younger sister as pretty as the older sister?",
    },
    {
      traditional: "花蓮的房租有沒有台北的那麼貴？",
      simplified: "花莲的房租有没有台北的那么贵？",
      pinyin: "huā lián dē fáng zū yǒu méi yǒu tái běi dē nà me guì",
      english: "Is the rent in hualien as expensive as in taipei?",
    },
    {
      traditional: "日本的工作有沒有美國的那麼難找？",
      simplified: "日本的工作有没有美国的那么难找？",
      pinyin: "rì běn dē gōng zuò yǒu méi yǒu měi guó dē nà me nán zhǎo",
      english: "Is the job in japan as hard to find in the us?",
    },
    {
      traditional: "夏天的天氣有沒有春天的舒服？",
      simplified: "夏天的天气有没有春天的舒服？",
      pinyin: "xià tiān dē tiān qì yǒu méi yǒu chūn tiān dē shū fú",
      english: "Is the summer weather comfortable in spring?",
    },
    {
      traditional: "今天跟昨天一樣熱。",
      simplified: "今天跟昨天一样热。",
      pinyin: "jīn tiān gēn zuó tiān yī yàng rè",
      english: "Today is as hot as yesterday.",
    },
    {
      traditional: "今天沒有昨天那麼熱。",
      simplified: "今天没有昨天那么热。",
      pinyin: "jīn tiān méi yǒu zuó tiān nà me rè",
      english: "Today is not as hot as yesterday.",
    },
    {
      traditional: "今天比昨天熱。",
      simplified: "今天比昨天热。",
      pinyin: "jīn tiān bǐ zuó tiān rè",
      english: "Today is hotter than yesterday.",
    },
    {
      traditional: "我沒有多少錢。",
      simplified: "我没有多少钱。",
      pinyin: "wǒ méi yǒu duō shǎo qián",
      english: "I don't have much money.",
    },
    {
      traditional: "他沒有幾個朋友。",
      simplified: "他没有几个朋友。",
      pinyin: "tā méi yǒu jǐ gè péng yǒu",
      english: "He has few friends.",
    },
    {
      traditional: "你的感冒沒有什麼關係。",
      simplified: "你的感冒没有什么关系。",
      pinyin: "nǐ dē gǎn mào méi yǒu shén me guān xì",
      english: "Your cold has nothing to do with it.",
    },
    {
      traditional: "我沒去哪裡",
      simplified: "我没去哪里",
      pinyin: "wǒ méi qù nǎ lǐ",
      english: "I didn't go where",
    },
    {
      traditional: "他不打算買什麼。",
      simplified: "他不打算买什么。",
      pinyin: "tā bù dǎ suàn mǎi shén me",
      english: "He doesn't plan to buy anything.",
    },
    {
      traditional: "我昨天沒跟誰去看電影。",
      simplified: "我昨天没跟谁去看电影。",
      pinyin: "wǒ zuó tiān méi gēn shuí qù kàn diàn yǐng",
      english: "I didn't go to the movies with anyone yesterday.",
    },
    {
      traditional: "我把牛肉麵吃了。",
      simplified: "我把牛肉面吃了。",
      pinyin: "wǒ bǎ niú ròu miàn chī le",
      english: "I ate beef noodles.",
    },
    {
      traditional: "他把我的湯喝了。",
      simplified: "他把我的汤喝了。",
      pinyin: "tā bǎ wǒ dē tāng hē le",
      english: "He drank my soup.",
    },
    {
      traditional: "房東把房子賣了。",
      simplified: "房东把房子卖了。",
      pinyin: "fáng dōng bǎ fáng zi mài le",
      english: "The landlord sold the house.",
    },
    {
      traditional: "我沒把豬腳麵線吃了。",
      simplified: "我没把猪脚面线吃了。",
      pinyin: "wǒ méi bǎ zhū jiǎo miàn xiàn chī le",
      english: "I didn't eat the pork knuckle noodles.",
    },
    {
      traditional: "別把我的腰吃了。",
      simplified: "别把我的腰吃了。",
      pinyin: "bié bǎ wǒ dē yāo chī le",
      english: "Don't eat my waist.",
    },
    {
      traditional: "他沒把書買了。",
      simplified: "他没把书买了。",
      pinyin: "tā méi bǎ shū mǎi le",
      english: "He didn't buy the book.",
    },
    {
      traditional: "你把功課寫了沒有？",
      simplified: "你把功课写了没有？",
      pinyin: "nǐ bǎ gōng kè xiě le méi yǒu",
      english: "Have you written your homework yet?",
    },
    {
      traditional: "你是不是把機車買了？",
      simplified: "你是不是把机车买了？",
      pinyin: "nǐ shì bú shì bǎ jī chē mǎi le",
      english: "Did you buy the motorcycle?",
    },
    {
      traditional: "你是不是把他的早飯吃了？",
      simplified: "你是不是把他的早饭吃了？",
      pinyin: "nǐ shì bú shì bǎ tā dē zǎo fàn chī le",
      english: "Did you eat his breakfast?",
    },
    {
      traditional: "我想把手機買了。",
      simplified: "我想把手机买了。",
      pinyin: "wǒ xiǎng bǎ shǒu jī mǎi le",
      english: "I want to buy a mobile phone.",
    },
    {
      traditional: "我想把那隻手機買了。",
      simplified: "我想把那只手机买了。",
      pinyin: "wǒ xiǎng bǎ nà zhī shǒu jī mǎi le",
      english: "I want to buy that phone.",
    },
    {
      traditional: "我放了假就去旅行。",
      simplified: "我放了假就去旅行。",
      pinyin: "wǒ fàng le jiǎ jiù qù lǚ xíng",
      english: "I'm going to travel on vacation.",
    },
    {
      traditional: "他吃了藥就睡覺。",
      simplified: "他吃了药就睡觉。",
      pinyin: "tā chī le yào jiù shuì jué",
      english: "He went to bed after taking the medicine.",
    },
    {
      traditional: "爸爸會了假就喝了兩杯烏龍茶。",
      simplified: "爸爸会了假就喝了两杯乌龙茶。",
      pinyin: "bà bà huì le jiǎ jiù hē le liǎng bēi wū lóng chá",
      english: "Dad drank two cups of oolong tea after the holiday.",
    },
    {
      traditional: "他到了台北，就去台北101看看。",
      simplified: "他到了台北，就去台北101看看。",
      pinyin: "tā dào le tái běi jiù qù tái běi kàn kàn",
      english: "When he arrived in taipei, he went to visit taipei 101.",
    },
    {
      traditional: "妹妹喝了一碗熱湯，就不覺得冷了。",
      simplified: "妹妹喝了一碗热汤，就不觉得冷了。",
      pinyin: "mèi mei hē le yī wǎn rè tāng jiù bù jué dé lěng le",
      english:
        "My sister drank a bowl of hot soup and didn't feel cold anymore.",
    },
    {
      traditional: "姊姊吃了臭豆腐，肚子就不舒服。",
      simplified: "姊姊吃了臭豆腐，肚子就不舒服。",
      pinyin: "zǐ zǐ chī le chòu dòu fǔ dǔ zi jiù bù shū fu",
      english:
        "My sister ate stinky tofu and her stomach became uncomfortable.",
    },
    {
      traditional: "他們見了面，就去喝咖啡嗎？",
      simplified: "他们见了面，就去喝咖啡吗？",
      pinyin: "tā men jiàn le miàn jiù qù hē kā fēi ma",
      english: "When they meet, should they go for coffee?",
    },
    {
      traditional: "你弟弟是不是下了課，就去KTV唱歌？",
      simplified: "你弟弟是不是下了课，就去KTV唱歌？",
      pinyin: "nǐ dì di shì bú shì xià le kè jiù qù chàng gē",
      english: "Does your brother go to ktv to sing after class?",
    },
    {
      traditional: "她是不是紐約玩了兩個星期，就不想回來了？",
      simplified: "她是不是纽约玩了两个星期，就不想回来了？",
      pinyin:
        "tā shì bú shì niǔ yuē wán le liǎng gè xīng qī jiù bù xiǎng huí lái le",
      english:
        "Did she not want to come back after playing in new york for two weeks?",
    },
    {
      traditional: "他吃了藥以後，就去睡覺。",
      simplified: "他吃了药以后，就去睡觉。",
      pinyin: "tā chī le yào yǐ hòu jiù qù shuì jué",
      english: "After he took the medicine, he went to sleep.",
    },
    {
      traditional: "他喝了一點咖啡。",
      simplified: "他喝了一点咖啡。",
      pinyin: "tā hē le yī diǎn kā fēi",
      english: "He drank a little coffee.",
    },
    {
      traditional: "這一點錢太少了。",
      simplified: "这一点钱太少了。",
      pinyin: "zhè yī diǎn qián tài shǎo le",
      english: "This little money is too little.",
    },
    {
      traditional: "他要吃一點麵線。",
      simplified: "他要吃一点面线。",
      pinyin: "tā yào chī yī diǎn miàn xiàn",
      english: "He wants to eat some noodles.",
    },
    {
      traditional: "他在超市買了一點東西。",
      simplified: "他在超市买了一点东西。",
      pinyin: "tā zài chāo shì mǎi le yī diǎn dōng xī",
      english: "He bought something in the supermarket.",
    },
    {
      traditional: "我只喝了一點烏龍茶。",
      simplified: "我只喝了一点乌龙茶。",
      pinyin: "wǒ zhǐ hē le yī diǎn wū lóng chá",
      english: "I only drank a little oolong tea.",
    },
    {
      traditional: "昨天下了一點雨。",
      simplified: "昨天下了一点雨。",
      pinyin: "zuó tiān xià le yī diǎn yǔ",
      english: "It rained a little yesterday.",
    },
    {
      traditional: "他比我年輕一點。",
      simplified: "他比我年轻一点。",
      pinyin: "tā bǐ wǒ nián qīng yī diǎn",
      english: "He is a little younger than me.",
    },
    {
      traditional: "請你早一點來！",
      simplified: "请你早一点来！",
      pinyin: "qǐng nǐ zǎo yī diǎn lái",
      english: "Please come early!",
    },
    {
      traditional: "明天我會晚一點回家。",
      simplified: "明天我会晚一点回家。",
      pinyin: "míng tiān wǒ huì wǎn yī diǎn huí jiā",
      english: "Tomorrow i will go home later.",
    },
    {
      traditional: "牛肉麵有一點啦。",
      simplified: "牛肉面有一点啦。",
      pinyin: "niú ròu miàn yǒu yī diǎn la",
      english: "There is a bit of beef noodles.",
    },
    {
      traditional: "這裡，冬天有一點冷。",
      simplified: "这里，冬天有一点冷。",
      pinyin: "zhè lǐ dōng tiān yǒu yī diǎn lěng",
      english: "Here, it is a bit cold in winter.",
    },
    {
      traditional: "這支手機有一點貴。",
      simplified: "这支手机有一点贵。",
      pinyin: "zhè zhī shǒu jī yǒu yī diǎn guì",
      english: "This phone is a bit expensive.",
    },
    {
      traditional: "他有一點想睡。",
      simplified: "他有一点想睡。",
      pinyin: "tā yǒu yī diǎn xiǎng shuì",
      english: "He is a little sleepy.",
    },
    {
      traditional: "哥哥吃牛肉麵吃得比弟弟多。",
      simplified: "哥哥吃牛肉面吃得比弟弟多。",
      pinyin: "gē ge chī niú ròu miàn chī dé bǐ dì di duō",
      english:
        "The older brother eats beef noodles more than his younger brother.",
    },
    {
      traditional: "這種手機買得比那種好。",
      simplified: "这种手机买得比那种好。",
      pinyin: "zhè zhǒng shǒu jī mǎi dé bǐ nà zhǒng hǎo",
      english: "This kind of mobile phone is better than that.",
    },
    {
      traditional: "他比我做得快。",
      simplified: "他比我做得快。",
      pinyin: "tā bǐ wǒ zuò dé kuài",
      english: "He did it faster than me.",
    },
    {
      traditional: "我比他走得快。",
      simplified: "我比他走得快。",
      pinyin: "wǒ bǐ tā zǒu dé kuài",
      english: "I walk faster than him.",
    },
    {
      traditional: "弟弟比哥哥年的好。",
      simplified: "弟弟比哥哥年的好。",
      pinyin: "dì di bǐ gē ge nián dē hǎo",
      english: "The younger brother is younger than the older brother.",
    },
    {
      traditional: "他做飯做得比我快。",
      simplified: "他做饭做得比我快。",
      pinyin: "tā zuò fàn zuò dé bǐ wǒ kuài",
      english: "He cooks faster than me.",
    },
    {
      traditional: "我走路走得比他快。",
      simplified: "我走路走得比他快。",
      pinyin: "wǒ zǒu lù zǒu dé bǐ tā kuài",
      english: "I walk faster than him.",
    },
    {
      traditional: "弟弟唸書唸得比哥哥好。",
      simplified: "弟弟念书念得比哥哥好。",
      pinyin: "dì di niàn shū niàn dé bǐ gē ge hǎo",
      english: "My brother studies better than his brother.",
    },
    {
      traditional: "他做飯不比我做得快。",
      simplified: "他做饭不比我做得快。",
      pinyin: "tā zuò fàn bù bǐ wǒ zuò dé kuài",
      english: "He does not cook faster than i do.",
    },
    {
      traditional: "走路，我不比他走得快。",
      simplified: "走路，我不比他走得快。",
      pinyin: "zǒu lù wǒ bù bǐ tā zǒu dé kuài",
      english: "Walking, i can't walk faster than him.",
    },
    {
      traditional: "弟弟唸書唸得不比哥哥好。",
      simplified: "弟弟念书念得不比哥哥好。",
      pinyin: "dì di niàn shū niàn dé bù bǐ gē ge hǎo",
      english:
        "My younger brother does not study better than his older brother.",
    },
    {
      traditional: "你做飯做得比媽媽好嗎？",
      simplified: "你做饭做得比妈妈好吗？",
      pinyin: "nǐ zuò fàn zuò dé bǐ mā mā hǎo ma",
      english: "Do you cook better than your mother?",
    },
    {
      traditional: "他是不是走路走得比你快？",
      simplified: "他是不是走路走得比你快？",
      pinyin: "tā shì bú shì zǒu lù zǒu dé bǐ nǐ kuài",
      english: "Does he walk faster than you?",
    },
    {
      traditional: "弟弟打網球打得比哥哥好嗎？",
      simplified: "弟弟打网球打得比哥哥好吗？",
      pinyin: "dì di dǎ wǎng qiú dǎ dé bǐ gē ge hǎo ma",
      english: "Does my brother play tennis better than my brother?",
    },
    {
      traditional: "他的房間比我的大一點。",
      simplified: "他的房间比我的大一点。",
      pinyin: "tā dē fáng jiān bǐ wǒ dē dà yī diǎn",
      english: "His room is a bit bigger than mine.",
    },
    {
      traditional: "捷運站比公車站遠的多。",
      simplified: "捷运站比公车站远的多。",
      pinyin: "jié yùn zhàn bǐ gōng chē zhàn yuǎn dē duō",
      english: "The mrt station is farther away than the bus station.",
    },
    {
      traditional: "我覺得晚上比早上舒服多了。",
      simplified: "我觉得晚上比早上舒服多了。",
      pinyin: "wǒ jué dé wǎn shàng bǐ zǎo shàng shū fú duō le",
      english: "I feel more comfortable at night than in the morning.",
    },
    {
      traditional: "哥哥是不是比弟弟高一點？",
      simplified: "哥哥是不是比弟弟高一点？",
      pinyin: "gē ge shì bú shì bǐ dì di gāo yī diǎn",
      english: "Is the older brother a bit taller than the younger brother?",
    },
    {
      traditional: "房租可以便宜一點嗎？",
      simplified: "房租可以便宜一点吗？",
      pinyin: "fáng zū kě yǐ pián yí yī diǎn ma",
      english: "Can the rent be cheaper?",
    },
    {
      traditional: "春天去旅行是不是比夏天舒服得多？",
      simplified: "春天去旅行是不是比夏天舒服得多？",
      pinyin: "chūn tiān qù lǚ xíng shì bú shì bǐ xià tiān shū fú dé duō",
      english:
        "Is it much more comfortable to travel in spring than in summer?",
    },
    {
      traditional: "高鐵票比火車票貴多了嗎？",
      simplified: "高铁票比火车票贵多了吗？",
      pinyin: "gāo tiě piào bǐ huǒ chē piào guì duō le ma",
      english: "Are high-speed rail tickets more expensive than train tickets?",
    },
    {
      traditional: "他會了假以後，就開始工作。",
      simplified: "他会了假以后，就开始工作。",
      pinyin: "tā huì le jiǎ yǐ hòu jiù kāi shǐ gōng zuò",
      english: "After he had a vacation, he started to work.",
    },
    {
      traditional: "我昨天下了課就跟朋友去看電影。",
      simplified: "我昨天下了课就跟朋友去看电影。",
      pinyin: "wǒ zuó tiān xià le kè jiù gēn péng yǒu qù kàn diàn yǐng",
      english: "I went to the movies with my friends after class yesterday.",
    },
    {
      traditional: "我想見你一面。",
      simplified: "我想见你一面。",
      pinyin: "wǒ xiǎng jiàn nǐ yī miàn",
      english: "I want to see you.",
    },
    {
      traditional: "他找了你一張相。",
      simplified: "他找了你一张相。",
      pinyin: "tā zhǎo le nǐ yī zhāng xiāng",
      english: "He found you a picture.",
    },
    {
      traditional: "我們每天上八個鐘頭的班。",
      simplified: "我们每天上八个钟头的班。",
      pinyin: "wǒ men měi tiān shàng bā gè zhōng tóu dē bān",
      english: "We work for eight hours every day.",
    },
    {
      traditional: "你們新年的時候，放幾天的家？",
      simplified: "你们新年的时候，放几天的家？",
      pinyin: "nǐ men xīn nián dē shí hòu fàng jǐ tiān dē jiā",
      english: "How many days do you put in your home during the new year?",
    },
    {
      traditional: "他唱了三小時的歌，有一點累。",
      simplified: "他唱了三小时的歌，有一点累。",
      pinyin: "tā chàng le sān xiǎo shí dē gē yǒu yī diǎn lèi",
      english: "He sang a song for three hours and was a little tired.",
    },
  ],
};

export default lesson;
