import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "fkajusyq5",
  type: "Grammar",
  locked: false,
  title: "Lesson 14 Grammar",
  content: [
    {
      traditional: "媽媽的朋友在台北玩了三天。",
      simplified: "妈妈的朋友在台北玩了三天。",
      pinyin: "mā mā dē péng yǒu zài tái běi wán le sān tiān",
      english: "Mom's friend spent three days in taipei.",
    },
    {
      traditional: "老師在美國住了一年。",
      simplified: "老师在美国住了一年。",
      pinyin: "lǎo shī zài měi guó zhù le yī nián",
      english: "The teacher lived in the united states for a year.",
    },
    {
      traditional: "李小姐在語言中心工作了一個月。",
      simplified: "李小姐在语言中心工作了一个月。",
      pinyin: "lǐ xiǎo jiě zài yǔ yán zhōng xīn gōng zuò le yī gè yuè",
      english: "Ms. li worked in the language center for a month.",
    },
    {
      traditional: "她租房子租了半年。",
      simplified: "她租房子租了半年。",
      pinyin: "tā zū fáng zi zū le bàn nián",
      english: "She rented a house for six months.",
    },
    {
      traditional: "他住台北住了三年。",
      simplified: "他住台北住了三年。",
      pinyin: "tā zhù tái běi zhù le sān nián",
      english: "He lived in taipei for three years.",
    },
    {
      traditional: "房子他只租了半年。",
      simplified: "房子他只租了半年。",
      pinyin: "fáng zi tā zhǐ zū le bàn nián",
      english: "He only rented the house for half a year.",
    },
    {
      traditional: "台北他只住了三年。",
      simplified: "台北他只住了三年。",
      pinyin: "tái běi tā zhǐ zhù le sān nián",
      english: "He only lived in taipei for three years.",
    },
    {
      traditional: "那間房子你租了一年半嗎？",
      simplified: "那间房子你租了一年半吗？",
      pinyin: "nà jiān fáng zi nǐ zū le yī nián bàn ma",
      english: "Have you rented that house for a year and a half?",
    },
    {
      traditional: "你是不是在這裡等了一個鐘頭？",
      simplified: "你是不是在这里等了一个钟头？",
      pinyin: "nǐ shì bú shì zài zhè lǐ děng le yī gè zhōng tóu",
      english: "Did you wait here for an hour?",
    },
    {
      traditional: "陳老闆去年是不是在紐約住了半年？",
      simplified: "陈老板去年是不是在纽约住了半年？",
      pinyin: "chén lǎo bǎn qù nián shì bú shì zài niǔ yuē zhù le bàn nián",
      english: "Did boss chen live in new york for half a year last year?",
    },
    {
      traditional: "他已經在台灣玩了一年了。",
      simplified: "他已经在台湾玩了一年了。",
      pinyin: "tā yǐ jīng zài tái wān wán le yī nián le",
      english: "He has been playing in taiwan for a year.",
    },
    {
      traditional: "陳小姐在美國住了五年了。",
      simplified: "陈小姐在美国住了五年了。",
      pinyin: "chén xiǎo jiě zài měi guó zhù le wǔ nián le",
      english: "Miss chen has lived in the united states for five years.",
    },
    {
      traditional: "我工作了兩個月了。",
      simplified: "我工作了两个月了。",
      pinyin: "wǒ gōng zuò le liǎng gè yuè le",
      english: "I have been working for two months.",
    },
    {
      traditional: "這間房子，他亦盈租了半年了。",
      simplified: "这间房子，他亦盈租了半年了。",
      pinyin: "zhè jiān fáng zi tā yì yíng zū le bàn nián le",
      english: "He has rented this house for half a year.",
    },
    {
      traditional: "他們學中文學了三個星期了。",
      simplified: "他们学中文学了三个星期了。",
      pinyin: "tā men xué zhōng wén xué le sān gè xīng qī le",
      english: "They have been studying chinese literature for three weeks.",
    },
    {
      traditional: "快下雨了。",
      simplified: "快下雨了。",
      pinyin: "kuài xià yǔ le",
      english: "It's raining soon.",
    },
    {
      traditional: "電影要結束了。",
      simplified: "电影要结束了。",
      pinyin: "diàn yǐng yào jié shù le",
      english: "The movie is about to end.",
    },
    {
      traditional: "爸爸快要到家了。",
      simplified: "爸爸快要到家了。",
      pinyin: "bà bà kuài yào dào jiā le",
      english: "Dad is going home soon.",
    },
    {
      traditional: "你媽媽的生日快到了嗎？",
      simplified: "你妈妈的生日快到了吗？",
      pinyin: "nǐ mā mā dē shēng rì kuài dào le ma",
      english: "Is your mother's birthday coming soon?",
    },
    {
      traditional: "比賽要開始了嗎？",
      simplified: "比赛要开始了吗？",
      pinyin: "bǐ sài yào kāi shǐ le ma",
      english: "Is the game about to start?",
    },
    {
      traditional: "哥哥的女朋友快要會法國了嗎？",
      simplified: "哥哥的女朋友快要会法国了吗？",
      pinyin: "gē ge dē nǚ péng yǒu kuài yào huì fǎ guó le ma",
      english: "Is your brother's girlfriend going to meet france soon?",
    },
    {
      traditional: "她很高，他哥哥比他更高。",
      simplified: "她很高，他哥哥比他更高。",
      pinyin: "tā hěn gāo tā gē ge bǐ tā gèng gāo",
      english: "She is tall, and his brother is taller than him.",
    },
    {
      traditional: "今年比去年更冷。",
      simplified: "今年比去年更冷。",
      pinyin: "jīn nián bǐ qù nián gèng lěng",
      english: "This year is colder than last year.",
    },
    {
      traditional: "我覺得芒果比西瓜更好吃。",
      simplified: "我觉得芒果比西瓜更好吃。",
      pinyin: "wǒ jué dé máng guǒ bǐ xī guā gèng hǎo chī",
      english: "I think mango is better than watermelon.",
    },
    {
      traditional: "這次的颱風是不是比上次的更大？",
      simplified: "这次的台风是不是比上次的更大？",
      pinyin: "zhè cì dē tái fēng shì bú shì bǐ shàng cì dē gèng dà",
      english: "Is this typhoon bigger than the last one?",
    },
    {
      traditional: "在學校上網是不是比在家裡更快？",
      simplified: "在学校上网是不是比在家里更快？",
      pinyin: "zài xué xiào shàng wǎng shì bú shì bǐ zài jiā lǐ gèng kuài",
      english: "Is the internet faster at school than at home?",
    },
    {
      traditional: "哥哥沒有爸爸那麼高。",
      simplified: "哥哥没有爸爸那么高。",
      pinyin: "gē ge méi yǒu bà bà nà me gāo",
      english: "My brother is not as tall as my father.",
    },
    {
      traditional: "火車沒有高鐵那麼快。",
      simplified: "火车没有高铁那么快。",
      pinyin: "huǒ chē méi yǒu gāo tiě nà me kuài",
      english: "The train is not as fast as the high-speed rail.",
    },
    {
      traditional: "我的中文沒有老師的那麼好。",
      simplified: "我的中文没有老师的那么好。",
      pinyin: "wǒ dē zhōng wén méi yǒu lǎo shī dē nà me hǎo",
      english: "My chinese is not as good as the teacher's.",
    },
    {
      traditional: "臭豆腐沒有牛肉麵這麼好吃。",
      simplified: "臭豆腐没有牛肉面这么好吃。",
      pinyin: "chòu dòu fǔ méi yǒu niú ròu miàn zhè me hǎo chī",
      english: "Stinky tofu is not as delicious as beef noodles.",
    },
    {
      traditional: "甜點沒有小籠包那麼好做。",
      simplified: "甜点没有小笼包那么好做。",
      pinyin: "tián diǎn méi yǒu xiǎo lóng bāo nà me hǎo zuò",
      english: "Dessert is not as good as xiaolongbao.",
    },
    {
      traditional: "這次的颱風沒有上次的那麼可怕。",
      simplified: "这次的台风没有上次的那么可怕。",
      pinyin: "zhè cì dē tái fēng méi yǒu shàng cì dē nà me kě pà",
      english: "This typhoon was not as terrible as the last one.",
    },
    {
      traditional: "妹妹有沒有姐姐那麼漂亮？",
      simplified: "妹妹有没有姐姐那么漂亮？",
      pinyin: "mèi mei yǒu méi yǒu jiě jie nà me piào liàng",
      english: "Is the younger sister as pretty as the older sister?",
    },
    {
      traditional: "花蓮的房租有沒有台北的那麼貴？",
      simplified: "花莲的房租有没有台北的那么贵？",
      pinyin: "huā lián dē fáng zū yǒu méi yǒu tái běi dē nà me guì",
      english: "Is the rent in hualien as expensive as in taipei?",
    },
    {
      traditional: "日本的工作有沒有美國的那麼難找？",
      simplified: "日本的工作有没有美国的那么难找？",
      pinyin: "rì běn dē gōng zuò yǒu méi yǒu měi guó dē nà me nán zhǎo",
      english: "Is the job in japan as hard to find in the us?",
    },
    {
      traditional: "夏天的天氣有沒有春天的舒服？",
      simplified: "夏天的天气有没有春天的舒服？",
      pinyin: "xià tiān dē tiān qì yǒu méi yǒu chūn tiān dē shū fú",
      english: "Is the summer weather comfortable in spring?",
    },
    {
      traditional: "今天跟昨天一樣熱。",
      simplified: "今天跟昨天一样热。",
      pinyin: "jīn tiān gēn zuó tiān yī yàng rè",
      english: "Today is as hot as yesterday.",
    },
    {
      traditional: "今天沒有昨天那麼熱。",
      simplified: "今天没有昨天那么热。",
      pinyin: "jīn tiān méi yǒu zuó tiān nà me rè",
      english: "Today is not as hot as yesterday.",
    },
    {
      traditional: "今天比昨天熱。",
      simplified: "今天比昨天热。",
      pinyin: "jīn tiān bǐ zuó tiān rè",
      english: "Today is hotter than yesterday.",
    },
  ],
};

export default lesson;
