import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "f87s6f88us",
  type: "Grammar",
  locked: false,
  title: "Real Life Grammar",
  content: [
    {
      traditional: "我覺得還是星期六比較適合耶。",
      simplified: "我觉得还是星期六比较适合耶。",
      pinyin: "Wǒ juédé háishì xīngqíliù bǐjiào shìhé yé.",
      english: "I think Saturday is more suitable.",
    },
    {
      traditional: "你為什麼不要今晚寫功課 明天跟我們去唱歌？",
      simplified: "你为什么不要今晚写功课 明天跟我们去唱歌？",
      pinyin:
        "nǐ wèi shén me bú yào jīn wǎn xiě gōng kè míng tiān gēn wǒ men qù chàng gē",
      english:
        "Why don't you write your homework tonight and sing with us tomorrow?",
    },
    {
      traditional: "我到現在也還在學英文。",
      simplified: "我到现在也还在学英文。",
      pinyin: "wǒ dào xiàn zài yě hái zài xué yīng wén",
      english: "I am still learning english.",
    },
    {
      traditional: "學語言是一輩子的事。",
      simplified: "学语言是一辈子的事。",
      pinyin: "xué yǔ yán shì yī bèi zi dē shì",
      english: "Learning a language is a lifelong matter.",
    },
    {
      traditional: "相信我 你會變得很厲害。",
      simplified: "相信我 你会变得很厉害。",
      pinyin: "xiāng xìn wǒ nǐ huì biàn de hěn lì hài",
      english: "Believe me you will become great.",
    },
    {
      traditional: "重點是你能跟我聊得起來。",
      simplified: "重点是你能跟我聊得起来。",
      pinyin: "zhòng diǎn shì nǐ néng gēn wǒ liáo dé qǐ lái",
      english: "The point is that you can talk to me.",
    },
    {
      traditional: "我可以自在的跟你用中文傳訊息。",
      simplified: "我可以自在的跟你用中文传讯息。",
      pinyin: "wǒ kě yǐ zì zài dē gēn nǐ yòng zhōng wén chuán xùn xī",
      english: "I can send messages to you in chinese at ease.",
    },
    {
      traditional: "我真的覺得你進步很多耶。",
      simplified: "我真的觉得你进步很多耶。",
      pinyin: "wǒ zhēn dē jué dé nǐ jìn bù hěn duō yé",
      english: "I really think you have improved a lot.",
    },
    {
      traditional: "這什麼年代了。",
      simplified: "这什么年代了。",
      pinyin: "zhè shén me nián dài le",
      english: "What age is this?",
    },
    {
      traditional: "當個特別的學生很好啊。",
      simplified: "当个特别的学生很好啊。",
      pinyin: "dāng gè tè bié dē xué shēng hěn hǎo a",
      english: "It's great to be a special student.",
    },
    {
      traditional: "他們從沒有我這樣的學生。",
      simplified: "他们从没有我这样的学生。",
      pinyin: "tā men cóng méi yǒu wǒ zhè yàng dē xué shēng",
      english: "They have never had a student like me.",
    },
    {
      traditional: "我學法文都沒有你認真。",
      simplified: "我学法文都没有你认真。",
      pinyin: "wǒ xué fǎ wén dōu méi yǒu nǐ rèn zhēn",
      english: "I'm not as serious as you in studying french.",
    },
    {
      traditional: "希望你找到好學校 好老師。",
      simplified: "希望你找到好学校 好老师。",
      pinyin: "xī wàng nǐ zhǎo dào hǎo xué xiào hǎo lǎo shī",
      english: "Hope you find a good school and good teacher.",
    },
    {
      traditional: "有幾個問題我不知道。",
      simplified: "有几个问题我不知道。",
      pinyin: "yǒu jǐ gè wèn tí wǒ bù zhī dào",
      english: "There are a few questions i don't know.",
    },
    {
      traditional: "有找到更好的學校嗎？。",
      simplified: "有找到更好的学校吗？ 。",
      pinyin: "yǒu zhǎo dào gèng hǎo dē xué xiào ma",
      english: "Have you found a better school? .",
    },
    {
      traditional: "你今天考的怎麼樣。",
      simplified: "你今天考的怎么样。",
      pinyin: "nǐ jīn tiān kǎo dē zěn me yàng",
      english: "How did you take the exam today.",
    },
    {
      traditional: "我覺得還是星期六比較適合耶。",
      simplified: "我觉得还是星期六比较适合耶。",
      pinyin: "wǒ jué dé hái shì xīng qī liù bǐ jiào shì hé yé",
      english: "I think saturday is more suitable.",
    },
    {
      traditional: "不然FT沒辦法一起去。",
      simplified: "不然FT没办法一起去。",
      pinyin: "bù rán méi bàn fǎ yì qǐ qù",
      english: "Otherwise ft can't go together.",
    },
    {
      traditional: "翻譯和秘書 所以才這麼忙。",
      simplified: "翻译和秘书 所以才这么忙。",
      pinyin: "fān yì hé mì shū suǒ yǐ cái zhè me máng",
      english: "The translator and secretary are so busy.",
    },
    {
      traditional: "因為我做兩份工作。",
      simplified: "因为我做两份工作。",
      pinyin: "yīn wèi wǒ zuò liǎng fèn gōng zuò",
      english: "Because i do two jobs.",
    },
    {
      traditional: "我要先去睡覺了。",
      simplified: "我要先去睡觉了。",
      pinyin: "wǒ yào xiān qù shuì jué le",
      english: "I'm going to bed first.",
    },
    {
      traditional: "明天再約時間。",
      simplified: "明天再约时间。",
      pinyin: "míng tiān zài yuē shí jiān",
      english: "Make an appointment tomorrow.",
    },
    {
      traditional: "星期六讓你好好發洩一下。",
      simplified: "星期六让你好好发泄一下。",
      pinyin: "xīng qī liù ràng nǐ hǎo hǎo fā xiè yī xià",
      english: "Let you vent it on saturday.",
    },
    {
      traditional: "像密碼一樣 好可怕。",
      simplified: "像密码一样 好可怕。",
      pinyin: "xiàng mì mǎ yī yàng hǎo kě pà",
      english: "It's scary like a password.",
    },
    {
      traditional: "為什麼都沒有舉例。",
      simplified: "为什么都没有举例。",
      pinyin: "wèi shén me dōu méi yǒu jǔ lì",
      english: "Why are there no examples.",
    },
    {
      traditional: "天啊 我也看不懂。",
      simplified: "天啊 我也看不懂。",
      pinyin: "tiān a wǒ yě kàn bu dǒng",
      english: "Oh my god, i can't understand either.",
    },
    {
      traditional: "所以剩文法還沒複習？",
      simplified: "所以剩文法还没复习？",
      pinyin: "suǒ yǐ shèng wén fǎ hái méi fù xí",
      english: "So the remaining grammar hasn't been reviewed yet?",
    },
    {
      traditional: "演講要講多久？",
      simplified: "演讲要讲多久？",
      pinyin: "yǎn jiǎng yào jiǎng duō jiǔ",
      english: "How long will the speech last?",
    },
    {
      traditional: "那趕快複習啊！",
      simplified: "那赶快复习啊！",
      pinyin: "nà gǎn kuài fù xí a",
      english: "Then hurry up and review!",
    },
    {
      traditional: "跟老師說他們教太爛 所以你不會。",
      simplified: "跟老师说他们教太烂 所以你不会。",
      pinyin: "gēn lǎo shī shuō tā men jiào tài làn suǒ yǐ nǐ bù huì",
      english: "Tell the teacher that they teach too badly, so you won't.",
    },
    {
      traditional: "那就...兩眼開開 等著投胎。",
      simplified: "那就...两眼开开 等着投胎。",
      pinyin: "nà jiù liǎng yǎn kāi kāi děng zhe tóu tāi",
      english: "Then...with eyes open, waiting for reincarnation.",
    },
    {
      traditional: "然後順便教你寫功課。",
      simplified: "然后顺便教你写功课。",
      pinyin: "rán hòu shùn biàn jiào nǐ xiě gōng kè",
      english: "Then teach you how to write your homework by the way.",
    },
    {
      traditional: "你下星期是不是要去溪頭?",
      simplified: "你下星期是不是要去溪头?",
      pinyin: "nǐ xià xīng qī shì bú shì yào qù xī tóu",
      english: "Are you going to xitou next week?",
    },
    {
      traditional: "早一點開始，早一點結束啊。",
      simplified: "早一点开始，早一点结束啊。",
      pinyin: "zǎo yī diǎn kāi shǐ zǎo yī diǎn jié shù a",
      english: "Start earlier and end earlier.",
    },
    {
      traditional: "我覺得一般課程都會包含文法。",
      simplified: "我觉得一般课程都会包含文法。",
      pinyin: "wǒ jué dé yì bān kè chéng dōu huì bāo hán wén fǎ",
      english: "I think the general course will include grammar.",
    },
    {
      traditional: "那你要學商業/生活中文。",
      simplified: "那你要学商业/生活中文。",
      pinyin: "nà nǐ yào xué shāng yè shēng huó zhōng wén",
      english: "Then you have to learn business/life chinese.",
    },
    {
      traditional: "我可以跟你講聽起來對不對。",
      simplified: "我可以跟你讲听起来对不对。",
      pinyin: "wǒ kě yǐ gēn nǐ jiǎng tīng qǐ lái duì bù duì",
      english: "I can tell you if it sounds right.",
    },
    {
      traditional: "我也可以大約跟你解釋為什麼。",
      simplified: "我也可以大约跟你解释为什么。",
      pinyin: "wǒ yě kě yǐ dà yuē gēn nǐ jiě shì wèi shén me",
      english: "I can also explain to you about why.",
    },
    {
      traditional: "因為這跟中文很不一樣。",
      simplified: "因为这跟中文很不一样。",
      pinyin: "yīn wèi zhè gēn zhōng wén hěn bù yī yàng",
      english: "Because it is very different from chinese.",
    },
    {
      traditional: "我覺得記住很多詞彙，然後就會很厲害了。",
      simplified: "我觉得记住很多词汇，然后就会很厉害了。",
      pinyin: "wǒ jué dé jì zhù hěn duō cí huì rán hòu jiù huì hěn lì hài le",
      english:
        "I think remember a lot of vocabulary, and then it will be very good.",
    },
    {
      traditional: "他們從來沒有像我這樣的學生。",
      simplified: "他们从来没有像我这样的学生。",
      pinyin: "tā men cóng lái méi yǒu xiàng wǒ zhè yàng dē xué shēng",
      english: "They have never had a student like me.",
    },
    {
      traditional: "很無聊吧！",
      simplified: "很无聊吧！",
      pinyin: "hěn wú liáo ba",
      english: "Very boring!",
    },
    {
      traditional: "跟我學英文一樣。",
      simplified: "跟我学英文一样。",
      pinyin: "gēn wǒ xué yīng wén yī yàng",
      english: "Learn english like me.",
    },
    {
      traditional: "要用背的。",
      simplified: "要用背的。",
      pinyin: "yào yòng bèi dē",
      english: "Use the back.",
    },
    {
      traditional: "你的中文越來越進步了。",
      simplified: "你的中文越来越进步了。",
      pinyin: "nǐ dē zhōng wén yuè lái yuè jìn bù le",
      english: "Your chinese is getting better and better.",
    },
    {
      traditional: "星期六晚上天氣好我可以搭帳篷。",
      simplified: "星期六晚上天气好我可以搭帐篷。",
      pinyin: "xīng qī liù wǎn shàng tiān qì hǎo wǒ kě yǐ dā zhàng péng",
      english:
        "I can set up a tent on saturday night when the weather is good.",
    },
    {
      traditional: "我星期天下午有事。",
      simplified: "我星期天下午有事。",
      pinyin: "wǒ xīng qī tiān xià wǔ yǒu shì",
      english: "I have something on sunday afternoon.",
    },
    {
      traditional: "你是指星期天嗎？",
      simplified: "你是指星期天吗？",
      pinyin: "nǐ shì zhǐ xīng qī tiān ma",
      english: "Do you mean sunday?",
    },
  ],
};

export default lesson;
