import { ContentList } from "@src/tools/types";

const lesson: ContentList = {
  id: "fufay1652",
  type: "Grammar",
  locked: false,
  title: "Lesson 15 Grammar",
  content: [
    {
      traditional: "我沒有多少錢。",
      simplified: "我没有多少钱。",
      pinyin: "wǒ méi yǒu duō shǎo qián",
      english: "I don't have much money.",
    },
    {
      traditional: "他沒有幾個朋友。",
      simplified: "他没有几个朋友。",
      pinyin: "tā méi yǒu jǐ gè péng yǒu",
      english: "He has few friends.",
    },
    {
      traditional: "你的感冒沒有什麼關係。",
      simplified: "你的感冒没有什么关系。",
      pinyin: "nǐ dē gǎn mào méi yǒu shén me guān xì",
      english: "Your cold has nothing to do with it.",
    },
    {
      traditional: "我沒去哪裡",
      simplified: "我没去哪里",
      pinyin: "wǒ méi qù nǎ lǐ",
      english: "I didn't go where",
    },
    {
      traditional: "他不打算買什麼。",
      simplified: "他不打算买什么。",
      pinyin: "tā bù dǎ suàn mǎi shén me",
      english: "He doesn't plan to buy anything.",
    },
    {
      traditional: "我昨天沒跟誰去看電影。",
      simplified: "我昨天没跟谁去看电影。",
      pinyin: "wǒ zuó tiān méi gēn shuí qù kàn diàn yǐng",
      english: "I didn't go to the movies with anyone yesterday.",
    },
    {
      traditional: "我把牛肉麵吃了。",
      simplified: "我把牛肉面吃了。",
      pinyin: "wǒ bǎ niú ròu miàn chī le",
      english: "I ate beef noodles.",
    },
    {
      traditional: "他把我的湯喝了。",
      simplified: "他把我的汤喝了。",
      pinyin: "tā bǎ wǒ dē tāng hē le",
      english: "He drank my soup.",
    },
    {
      traditional: "房東把房子賣了。",
      simplified: "房东把房子卖了。",
      pinyin: "fáng dōng bǎ fáng zi mài le",
      english: "The landlord sold the house.",
    },
    {
      traditional: "我沒把豬腳麵線吃了。",
      simplified: "我没把猪脚面线吃了。",
      pinyin: "wǒ méi bǎ zhū jiǎo miàn xiàn chī le",
      english: "I didn't eat the pork knuckle noodles.",
    },
    {
      traditional: "別把我的腰吃了。",
      simplified: "别把我的腰吃了。",
      pinyin: "bié bǎ wǒ dē yāo chī le",
      english: "Don't eat my waist.",
    },
    {
      traditional: "他沒把書買了。",
      simplified: "他没把书买了。",
      pinyin: "tā méi bǎ shū mǎi le",
      english: "He didn't buy the book.",
    },
    {
      traditional: "你把功課寫了沒有？",
      simplified: "你把功课写了没有？",
      pinyin: "nǐ bǎ gōng kè xiě le méi yǒu",
      english: "Have you written your homework yet?",
    },
    {
      traditional: "你是不是把機車買了？",
      simplified: "你是不是把机车买了？",
      pinyin: "nǐ shì bú shì bǎ jī chē mǎi le",
      english: "Did you buy the motorcycle?",
    },
    {
      traditional: "你是不是把他的早飯吃了？",
      simplified: "你是不是把他的早饭吃了？",
      pinyin: "nǐ shì bú shì bǎ tā dē zǎo fàn chī le",
      english: "Did you eat his breakfast?",
    },
    {
      traditional: "我想把手機買了。",
      simplified: "我想把手机买了。",
      pinyin: "wǒ xiǎng bǎ shǒu jī mǎi le",
      english: "I want to buy a mobile phone.",
    },
    {
      traditional: "我想把那隻手機買了。",
      simplified: "我想把那只手机买了。",
      pinyin: "wǒ xiǎng bǎ nà zhī shǒu jī mǎi le",
      english: "I want to buy that phone.",
    },
    {
      traditional: "我放了假就去旅行。",
      simplified: "我放了假就去旅行。",
      pinyin: "wǒ fàng le jiǎ jiù qù lǚ xíng",
      english: "I'm going to travel on vacation.",
    },
    {
      traditional: "他吃了藥就睡覺。",
      simplified: "他吃了药就睡觉。",
      pinyin: "tā chī le yào jiù shuì jué",
      english: "He went to bed after taking the medicine.",
    },
    {
      traditional: "爸爸會了假就喝了兩杯烏龍茶。",
      simplified: "爸爸会了假就喝了两杯乌龙茶。",
      pinyin: "bà bà huì le jiǎ jiù hē le liǎng bēi wū lóng chá",
      english: "Dad drank two cups of oolong tea after the holiday.",
    },
    {
      traditional: "他到了台北，就去台北101看看。",
      simplified: "他到了台北，就去台北101看看。",
      pinyin: "tā dào le tái běi jiù qù tái běi kàn kàn",
      english: "When he arrived in taipei, he went to visit taipei 101.",
    },
    {
      traditional: "妹妹喝了一碗熱湯，就不覺得冷了。",
      simplified: "妹妹喝了一碗热汤，就不觉得冷了。",
      pinyin: "mèi mei hē le yī wǎn rè tāng jiù bù jué dé lěng le",
      english:
        "My sister drank a bowl of hot soup and didn't feel cold anymore.",
    },
    {
      traditional: "姊姊吃了臭豆腐，肚子就不舒服。",
      simplified: "姊姊吃了臭豆腐，肚子就不舒服。",
      pinyin: "zǐ zǐ chī le chòu dòu fǔ dǔ zi jiù bù shū fu",
      english:
        "My sister ate stinky tofu and her stomach became uncomfortable.",
    },
    {
      traditional: "他們見了面，就去喝咖啡嗎？",
      simplified: "他们见了面，就去喝咖啡吗？",
      pinyin: "tā men jiàn le miàn jiù qù hē kā fēi ma",
      english: "When they meet, should they go for coffee?",
    },
    {
      traditional: "你弟弟是不是下了課，就去KTV唱歌？",
      simplified: "你弟弟是不是下了课，就去KTV唱歌？",
      pinyin: "nǐ dì di shì bú shì xià le kè jiù qù chàng gē",
      english: "Does your brother go to ktv to sing after class?",
    },
    {
      traditional: "她是不是紐約玩了兩個星期，就不想回來了？",
      simplified: "她是不是纽约玩了两个星期，就不想回来了？",
      pinyin:
        "tā shì bú shì niǔ yuē wán le liǎng gè xīng qī jiù bù xiǎng huí lái le",
      english:
        "Did she not want to come back after playing in new york for two weeks?",
    },
    {
      traditional: "他吃了藥以後，就去睡覺。",
      simplified: "他吃了药以后，就去睡觉。",
      pinyin: "tā chī le yào yǐ hòu jiù qù shuì jué",
      english: "After he took the medicine, he went to sleep.",
    },
    {
      traditional: "他喝了一點咖啡。",
      simplified: "他喝了一点咖啡。",
      pinyin: "tā hē le yī diǎn kā fēi",
      english: "He drank a little coffee.",
    },
    {
      traditional: "這一點錢太少了。",
      simplified: "这一点钱太少了。",
      pinyin: "zhè yī diǎn qián tài shǎo le",
      english: "This little money is too little.",
    },
    {
      traditional: "他要吃一點麵線。",
      simplified: "他要吃一点面线。",
      pinyin: "tā yào chī yī diǎn miàn xiàn",
      english: "He wants to eat some noodles.",
    },
    {
      traditional: "他在超市買了一點東西。",
      simplified: "他在超市买了一点东西。",
      pinyin: "tā zài chāo shì mǎi le yī diǎn dōng xī",
      english: "He bought something in the supermarket.",
    },
    {
      traditional: "我只喝了一點烏龍茶。",
      simplified: "我只喝了一点乌龙茶。",
      pinyin: "wǒ zhǐ hē le yī diǎn wū lóng chá",
      english: "I only drank a little oolong tea.",
    },
    {
      traditional: "昨天下了一點雨。",
      simplified: "昨天下了一点雨。",
      pinyin: "zuó tiān xià le yī diǎn yǔ",
      english: "It rained a little yesterday.",
    },
    {
      traditional: "他比我年輕一點。",
      simplified: "他比我年轻一点。",
      pinyin: "tā bǐ wǒ nián qīng yī diǎn",
      english: "He is a little younger than me.",
    },
    {
      traditional: "請你早一點來！",
      simplified: "请你早一点来！",
      pinyin: "qǐng nǐ zǎo yī diǎn lái",
      english: "Please come early!",
    },
    {
      traditional: "明天我會晚一點回家。",
      simplified: "明天我会晚一点回家。",
      pinyin: "míng tiān wǒ huì wǎn yī diǎn huí jiā",
      english: "Tomorrow i will go home later.",
    },
    {
      traditional: "牛肉麵有一點啦。",
      simplified: "牛肉面有一点啦。",
      pinyin: "niú ròu miàn yǒu yī diǎn la",
      english: "There is a bit of beef noodles.",
    },
    {
      traditional: "這裡，冬天有一點冷。",
      simplified: "这里，冬天有一点冷。",
      pinyin: "zhè lǐ dōng tiān yǒu yī diǎn lěng",
      english: "Here, it is a bit cold in winter.",
    },
    {
      traditional: "這支手機有一點貴。",
      simplified: "这支手机有一点贵。",
      pinyin: "zhè zhī shǒu jī yǒu yī diǎn guì",
      english: "This phone is a bit expensive.",
    },
    {
      traditional: "他有一點想睡。",
      simplified: "他有一点想睡。",
      pinyin: "tā yǒu yī diǎn xiǎng shuì",
      english: "He is a little sleepy.",
    },
    {
      traditional: "哥哥吃牛肉麵吃得比弟弟多。",
      simplified: "哥哥吃牛肉面吃得比弟弟多。",
      pinyin: "gē ge chī niú ròu miàn chī dé bǐ dì di duō",
      english:
        "The older brother eats beef noodles more than his younger brother.",
    },
    {
      traditional: "這種手機買得比那種好。",
      simplified: "这种手机买得比那种好。",
      pinyin: "zhè zhǒng shǒu jī mǎi dé bǐ nà zhǒng hǎo",
      english: "This kind of mobile phone is better than that.",
    },
    {
      traditional: "他比我做得快。",
      simplified: "他比我做得快。",
      pinyin: "tā bǐ wǒ zuò dé kuài",
      english: "He did it faster than me.",
    },
    {
      traditional: "我比他走得快。",
      simplified: "我比他走得快。",
      pinyin: "wǒ bǐ tā zǒu dé kuài",
      english: "I walk faster than him.",
    },
    {
      traditional: "弟弟比哥哥年的好。",
      simplified: "弟弟比哥哥年的好。",
      pinyin: "dì di bǐ gē ge nián dē hǎo",
      english: "The younger brother is younger than the older brother.",
    },
    {
      traditional: "他做飯做得比我快。",
      simplified: "他做饭做得比我快。",
      pinyin: "tā zuò fàn zuò dé bǐ wǒ kuài",
      english: "He cooks faster than me.",
    },
    {
      traditional: "我走路走得比他快。",
      simplified: "我走路走得比他快。",
      pinyin: "wǒ zǒu lù zǒu dé bǐ tā kuài",
      english: "I walk faster than him.",
    },
    {
      traditional: "弟弟唸書唸得比哥哥好。",
      simplified: "弟弟念书念得比哥哥好。",
      pinyin: "dì di niàn shū niàn dé bǐ gē ge hǎo",
      english: "My brother studies better than his brother.",
    },
    {
      traditional: "他做飯不比我做得快。",
      simplified: "他做饭不比我做得快。",
      pinyin: "tā zuò fàn bù bǐ wǒ zuò dé kuài",
      english: "He does not cook faster than i do.",
    },
    {
      traditional: "走路，我不比他走得快。",
      simplified: "走路，我不比他走得快。",
      pinyin: "zǒu lù wǒ bù bǐ tā zǒu dé kuài",
      english: "Walking, i can't walk faster than him.",
    },
    {
      traditional: "弟弟唸書唸得不比哥哥好。",
      simplified: "弟弟念书念得不比哥哥好。",
      pinyin: "dì di niàn shū niàn dé bù bǐ gē ge hǎo",
      english:
        "My younger brother does not study better than his older brother.",
    },
    {
      traditional: "你做飯做得比媽媽好嗎？",
      simplified: "你做饭做得比妈妈好吗？",
      pinyin: "nǐ zuò fàn zuò dé bǐ mā mā hǎo ma",
      english: "Do you cook better than your mother?",
    },
    {
      traditional: "他是不是走路走得比你快？",
      simplified: "他是不是走路走得比你快？",
      pinyin: "tā shì bú shì zǒu lù zǒu dé bǐ nǐ kuài",
      english: "Does he walk faster than you?",
    },
    {
      traditional: "弟弟打網球打得比哥哥好嗎？",
      simplified: "弟弟打网球打得比哥哥好吗？",
      pinyin: "dì di dǎ wǎng qiú dǎ dé bǐ gē ge hǎo ma",
      english: "Does my brother play tennis better than my brother?",
    },
    {
      traditional: "他的房間比我的大一點。",
      simplified: "他的房间比我的大一点。",
      pinyin: "tā dē fáng jiān bǐ wǒ dē dà yī diǎn",
      english: "His room is a bit bigger than mine.",
    },
    {
      traditional: "捷運站比公車站遠的多。",
      simplified: "捷运站比公车站远的多。",
      pinyin: "jié yùn zhàn bǐ gōng chē zhàn yuǎn dē duō",
      english: "The mrt station is farther away than the bus station.",
    },
    {
      traditional: "我覺得晚上比早上舒服多了。",
      simplified: "我觉得晚上比早上舒服多了。",
      pinyin: "wǒ jué dé wǎn shàng bǐ zǎo shàng shū fú duō le",
      english: "I feel more comfortable at night than in the morning.",
    },
    {
      traditional: "哥哥是不是比弟弟高一點？",
      simplified: "哥哥是不是比弟弟高一点？",
      pinyin: "gē ge shì bú shì bǐ dì di gāo yī diǎn",
      english: "Is the older brother a bit taller than the younger brother?",
    },
    {
      traditional: "房租可以便宜一點嗎？",
      simplified: "房租可以便宜一点吗？",
      pinyin: "fáng zū kě yǐ pián yí yī diǎn ma",
      english: "Can the rent be cheaper?",
    },
    {
      traditional: "春天去旅行是不是比夏天舒服得多？",
      simplified: "春天去旅行是不是比夏天舒服得多？",
      pinyin: "chūn tiān qù lǚ xíng shì bú shì bǐ xià tiān shū fú dé duō",
      english:
        "Is it much more comfortable to travel in spring than in summer?",
    },
    {
      traditional: "高鐵票比火車票貴多了嗎？",
      simplified: "高铁票比火车票贵多了吗？",
      pinyin: "gāo tiě piào bǐ huǒ chē piào guì duō le ma",
      english: "Are high-speed rail tickets more expensive than train tickets?",
    },
    {
      traditional: "他會了假以後，就開始工作。",
      simplified: "他会了假以后，就开始工作。",
      pinyin: "tā huì le jiǎ yǐ hòu jiù kāi shǐ gōng zuò",
      english: "After he had a vacation, he started to work.",
    },
    {
      traditional: "我昨天下了課就跟朋友去看電影。",
      simplified: "我昨天下了课就跟朋友去看电影。",
      pinyin: "wǒ zuó tiān xià le kè jiù gēn péng yǒu qù kàn diàn yǐng",
      english: "I went to the movies with my friends after class yesterday.",
    },
    {
      traditional: "我想見你一面。",
      simplified: "我想见你一面。",
      pinyin: "wǒ xiǎng jiàn nǐ yī miàn",
      english: "I want to see you.",
    },
    {
      traditional: "他找了你一張相。",
      simplified: "他找了你一张相。",
      pinyin: "tā zhǎo le nǐ yī zhāng xiāng",
      english: "He found you a picture.",
    },
    {
      traditional: "我們每天上八個鐘頭的班。",
      simplified: "我们每天上八个钟头的班。",
      pinyin: "wǒ men měi tiān shàng bā gè zhōng tóu dē bān",
      english: "We work for eight hours every day.",
    },
    {
      traditional: "你們新年的時候，放幾天的家？",
      simplified: "你们新年的时候，放几天的家？",
      pinyin: "nǐ men xīn nián dē shí hòu fàng jǐ tiān dē jiā",
      english: "How many days do you put in your home during the new year?",
    },
    {
      traditional: "他唱了三小時的歌，有一點累。",
      simplified: "他唱了三小时的歌，有一点累。",
      pinyin: "tā chàng le sān xiǎo shí dē gē yǒu yī diǎn lèi",
      english: "He sang a song for three hours and was a little tired.",
    },
  ],
};

export default lesson;
