export default [
  "阿姨 āyí aunt",
  "啊 a ah",
  "矮 ǎi short",
  "爱 ài love",
  "爱好 àihào hobby",
  "安静 ānjìng Be quiet",
  "八 bā Eight",
  "把 bǎ hold",
  "爸爸 bàba Dad",
  "吧 ba",
  "白 bái white",
  "百 bǎi hundred",
  "班 bān class",
  "搬 bān move",
  "半 bàn half",
  "办法 bànfǎ Way",
  "办公室 bàngōngshì Office",
  "帮忙 bāngmáng Help",
  "帮助 bāngzhù Help",
  "包 bāo package",
  "饱 bǎo full",
  "报纸 bàozhǐ Newspaper",
  "杯子 bēizi glass",
  "北方 běifāng north",
  "北京 Běijīng Beijing",
  "被 bèi cover",
  "本 běn book",
  "鼻子 bízi nose",
  "比 bǐ than",
  "比较 bǐjiào compare",
  "比赛 bǐsài Match",
  "必须 bìxū Must",
  "变化 biànhuà change",
  "表示 biǎoshì Express",
  "表演 biǎoyǎn perform",
  "1   别 bié other",
  "别人 biéren Others",
  "宾馆 bīnguǎn hotel",
  "冰箱 bīngxiāng Refrigerator",
  "不客气 búkèqi You are welcome",
  "不 bù No",
  "才 cái just",
  "菜 cài food,dish",
  "菜单 càidān menu",
  "参加 cānjiā participate in",
  "草 cǎo grass",
  "层 céng layer",
  "茶 chá tea",
  "差 chà bad",
  "长 cháng long",
  "唱歌 chànggē Sing",
  "超市 chāoshì Supermarket",
  "衬衫 chènshān shirt",
  "成绩 chéngjì achievement",
  "城市 chéngshì City",
  "吃 chī eat",
  "迟到 chídào Late",
  "出 chū come out",
  "出现 chūxiàn Appear",
  "出租车 chūzūchē Taxi",
  "厨房 chúfáng Kitchen",
  "除了 chúle except, besides",
  "穿 chuān Wear",
  "船 chuán ship",
  "春 chūn spring",
  "词语 cíyǔ terms, words",
  "次 cì times",
  "聪明 cōngming clever",
  "从 cóng from",
  "错 cuò Wrong",
  "打电话 dǎdiànhuà call",
  "打篮球 dǎlánqiú Play basketball",
  "打扫 dǎsǎo Clean",
  "打算 dǎsuàn Plan",
  "大 dà big",
  "大家 dàjiā everybody",
  "带 dài belt",
  "担心 dānxīn Worry",
  "蛋糕 dàngāo Cake",
  "2",
  "但是 dànshì however",
  "当然 dāngrán Of course",
  "到 dào reach",
  "地 de",
  "的 de",
  "得 dé",
  "灯 dēng lamp",
  "等 děng etc.",
  "低 dī low",
  "弟弟 dìdi Younger brother",
  "地方 dìfang local",
  "地铁 dìtiě metro",
  "地图 dìtú Map",
  "第一 dìyī first",
  "点 diǎn spot",
  "电脑 diànnǎo Computer",
  "电视 diànshì television",
  "电梯 diàntī Elevator.",
  "电影 diànyǐng Film",
  "电子邮件 diànzǐyóujiàn E-mail",
  "东 dōng east",
  "东西 dōngxi thing",
  "冬 dōng winter",
  "懂 dǒng understand",
  "动物 dòngwù Animal",
  "都 dōu all",
  "读 dú read",
  "短 duǎn short",
  "段 duàn paragraph",
  "锻炼 duànliàn Physical exercise",
  "对 duì Yes",
  "对不起 duìbuqǐ I'm sorry.",
  "多 duō many",
  "多么 duōme such",
  "多少 duōshao how much",
  "饿 è hungry",
  "而且 érqiě And",
  "儿子 érzi Son",
  "耳朵 ěrduo Ears",
  "二 èr Two",
  "发烧 fāshāo Have a fever",
  "发现 fāxiàn find, discover",
  "饭馆 fànguǎn restaurant",
  "方便 fāngbiàn convenient",
  "3",
  "房间 fángjiān Room",
  "放 fàng discharge",
  "放心 fàngxīn Don't worry",
  "非常 fēicháng very",
  "飞机 fēijī aircraft",
  "分 fēn minute",
  "分钟 fēnzhōng Minute",
  "服务员 fúwùyuán Waiter",
  "附近 fùjìn nearby",
  "复习 fùxí Review",
  "干净 gānjìng clean",
  "敢 gǎn dare",
  "感冒 gǎnmào get a cold",
  "刚才 gāngcái just",
  "高 gāo high",
  "高兴 gāoxìng happy",
  "告诉 gàosu tell",
  "哥哥 gēge older brother",
  "个 gè individual",
  "给 gěi to",
  "跟 gēn with",
  "根据 gēnjù according to",
  "更 gèng more",
  "公共汽车 gōnggòngqìchē Bus",
  "公斤 gōngjīn Kg.",
  "公司 gōngsī company",
  "公园 gōngyuán Park",
  "工作 gōngzuò work",
  "狗 gǒu Dog",
  "故事 gùshi Story",
  "刮风 guāfēng Windy",
  "关 guān shut",
  "关系 guānxì relationship",
  "关心 guānxīn Care for",
  "关于 guānyú about",
  "贵 guì Expensive",
  "国家 guójiā Country",
  "果汁 guǒzhī fruit juice",
  "过去 guòqù Past times",
  "过 guo too",
  "还 hái still",
  "还是 háishì still",
  "孩子 háizi Children",
  "害怕 hàipà Fear",
  "4",
  "汉语 hànyǔ Chinese",
  "好 hǎo good",
  "好吃 hǎochī Yummy",
  "号 hào Number",
  "喝 hē drink",
  "和 hé and",
  "河 hé river",
  "黑 hēi black",
  "黑板 hēibǎn blackboard",
  "很 hěn very",
  "红 hóng red",
  "后面 hòumiàn behind",
  "护照 hùzhào passport",
  "花 (动) huā spend (verb)",
  "花园 huāyuán Garden",
  "画 huà painting",
  "坏 huài bad",
  "欢迎 huānyíng Welcome",
  "还 huán return",
  "环境 huánjìng Environment",
  "换 huàn change",
  "黄 huáng yellow",
  "回 huí return",
  "回答 huídá Answer",
  "会 huì can;be able to",
  "会议 huìyì Meeting",
  "火车站 huǒchēzhàn Train station",
  "或者 huòzhě perhaps",
  "机场 jīchǎng Airport",
  "鸡蛋 jīdàn Egg",
  "几乎 jīhū almost",
  "机会 jīhuì Opportunity",
  "极 jí extremely",
  "几 jǐ several",
  "记得 jìde remember",
  "季节 jìjié Season",
  "家 jiā home",
  "检查 jiǎnchá inspect",
  "简单 jiǎndān simple",
  "件 jiàn piece",
  "健康 jiànkāng Healthy",
  "见面 jiànmiàn meet",
  "讲 jiǎng speak",
  "教 jiāo teach",
  "5",
  "角 jiǎo horn",
  "脚 jiǎo foot",
  "叫 jiào call",
  "教室 jiàoshì Classroom",
  "接 jiē pick,get",
  "街道 jiēdào Street",
  "结婚 jiéhūn marry",
  "结束 jiéshù End",
  "节目 jiémù program",
  "节日 jiérì festival",
  "姐姐 jiějie sister",
  "解决 jiějué Solve",
  "借 jiè borrow",
  "介绍 jièshào introduce",
  "今天 jīntiān Today",
  "进 jìn enter",
  "近 jìn near",
  "经常 jīngcháng Often",
  "经过 jīngguò After, through",
  "经理 jīnglǐ manager",
  "九 jiǔ Nine",
  "久 jiǔ long",
  "旧 jiù old,used",
  "就 jiù",
  "举行 jǔxíng hold",
  "句子 jùzi sentence",
  "觉得 juéde Think",
  "决定 juédìng Decision",
  "咖啡 kāfēi Coffee",
  "开 kāi open",
  "开始 kāishǐ start",
  "看 kàn see",
  "看见 kànjiàn seeing",
  "考试 kǎoshì Examination",
  "渴 kě thirsty",
  "可爱 kě'ài Lovely",
  "可能 kěnéng Probably",
  "可以 kěyǐ Sure",
  "刻 kè moment",
  "课 kè course",
  "客人 kèrén Guest",
  "空调 kōngtiáo Air conditioner",
  "口 kǒu mouth",
  "哭 kū cry",
  "6",
  "裤子 kùzi trousers",
  "块 kuài block",
  "快 kuài fast",
  "快乐 kuàilè happy",
  "筷子 kuàizi chopsticks",
  "来 lái come",
  "蓝 lán blue",
  "老 lǎo old",
  "老师 lǎoshī Teacher",
  "了 le",
  "累 lèi tired",
  "冷 lěng cold",
  "离 lí leave",
  "离开 líkāi leave",
  "里 lǐ in",
  "礼物 lǐwù gift",
  "历史 lìshǐ History",
  "脸 liǎn face",
  "练习 liànxí Practice",
  "两 liǎng Two",
  "辆 liàng Car",
  "了解 liǎojiě understand",
  "邻居 línjū neighbor",
  "零 líng Zero",
  "六 liù Six",
  "楼 lóu floor",
  "路 lù road",
  "旅游 lǚyóu Tourism",
  "绿 lǜ green",
  "妈妈 māma Mom",
  "马 mǎ Horse",
  "马上 mǎshàng Right off",
  "吗 ma",
  "买 mǎi buy",
  "卖 mài sell",
  "满意 mǎnyì Satisfied",
  "慢 màn slow",
  "忙 máng busy",
  "猫 māo cat",
  "帽子 màozi Hat",
  "没 méi no",
  "没关系 méiguānxi No problem",
  "每 měi each",
  "妹妹 mèimei Younger sister",
  "7",
  "门 mén door",
  "米 mǐ rice",
  "米饭 mǐfàn Steamed Rice",
  "面包 miànbāo Bread",
  "面条 miàntiáo noodle",
  "明白 míngbai clear",
  "明天 míngtiān Tomorrow",
  "名字 míngzi Name",
  "拿 ná take",
  "哪 (哪儿) nǎ(nǎr) Which (where)",
  "那 (那儿) nà(nàr) That (there)",
  "奶奶 nǎinai grandma",
  "南 nán south",
  "男人 nánrén Man",
  "难 nán difficult",
  "难过 nánguò sad",
  "呢 ne",
  "能 néng can",
  "你 nǐ you",
  "年 nián year",
  "年级 niánjí grade",
  "年轻 niánqīng Young",
  "鸟 niǎo bird",
  "您 nín you",
  "牛奶 niúnǎi milk",
  "努力 nǔlì Strive",
  "女儿 nǚ'ér daughter",
  "女人 nǚrén woman",
  "爬山 páshān Mountain climbing",
  "盘子 pánzi plate",
  "旁边 pángbiān Side",
  "胖 pàng fat",
  "跑步 pǎobù Run",
  "朋友 péngyou Friend",
  "啤酒 píjiǔ Beer",
  "便宜 piányi Cheap",
  "票 piào ticket",
  "漂亮 piàoliang Well done!",
  "苹果 píngguǒ Apple",
  "葡萄 pútao Grape",
  "普通话 pǔtōnghuà Mandarin",
  "七 qī Seven",
  "妻子 qīzi Wife",
  "其实 qíshí actually",
  "8",
  "其他 qítā Other",
  "骑 qí ride",
  "奇怪 qíguài strange",
  "起床 qǐchuáng Get up",
  "千 qiān thousand",
  "铅笔 qiānbǐ pencil",
  "钱 qián money",
  "前面 qiánmiàn Front",
  "清楚 qīngchu clear",
  "晴 qíng Sunny",
  "请 qǐng please",
  "秋 qiū autumn",
  "去 qù go",
  "去年 qùnián Last year",
  "裙子 qúnzi skirt",
  "然后 ránhòu Then",
  "让 ràng Give Way",
  "热 rè hot",
  "热情 rèqíng Enthusiasm",
  "人 rén people, person",
  "认识 rènshi know",
  "认为 rènwéi think",
  "认真 rènzhēn earnest",
  "日 rì day",
  "容易 róngyì easily",
  "如果 rúguǒ If",
  "三 sān Three",
  "伞 sǎn umbrella",
  "商店 shāngdiàn Shop",
  "上 shàng upper",
  "上班 shàngbān go to work",
  "上网 shàngwǎng Surf the Internet",
  "上午 shàngwǔ morning",
  "少 shǎo less",
  "谁 shéi who",
  "身体 shēntǐ body",
  "什么 shénme What",
  "生病 shēngbìng Fall ill",
  "生气 shēngqì get angry",
  "生日 shēngrì Birthday",
  "声音 shēngyīn voice",
  "十 shí Ten",
  "时候 shíhou time",
  "时间 shíjiān time",
  "9",
  "使 shǐ make",
  "是 shì yes",
  "世界 shìjiè world",
  "事情 shìqing Thing",
  "手表 shǒubiǎo Wrist Watch",
  "手机 shǒujī Mobile phone",
  "瘦 shòu thin",
  "书 shū book",
  "舒服 shūfu comfortable",
  "叔叔 shūshu uncle",
  "树 shù tree",
  "数学 shùxué Mathematics",
  "刷牙 shuāyá Brush one's teeth",
  "双 shuāng double, pair",
  "水 shuǐ water",
  "水果 shuǐguǒ Fruits",
  "水平 shuǐpíng level",
  "睡觉 shuìjiào sleep",
  "说话 shuōhuà talk",
  "司机 sījī Driver",
  "四 sì Four",
  "送 sòng give",
  "虽然 suīrán although",
  "岁 suì year",
  "所以 suǒyǐ therefore",
  "他 tā he",
  "她 tā she",
  "它 tā it",
  "太 tài too",
  "太阳 tàiyáng sun",
  "糖 táng sugar",
  "特别 tèbié Especially",
  "疼 téng hurt",
  "踢足球 tīzúqiú Play football",
  "题 tí topic",
  "提高 tígāo increase",
  "体育 tǐyù Sports",
  "天气 tiānqì weather",
  "甜 tián sweet",
  "条 tiáo strip",
  "跳舞 tiàowǔ dance",
  "听 tīng hear",
  "同事 tóngshì Colleague",
  "同学 tóngxué Classmate",
  "10",
  "同意 tóngyì Agree",
  "头发 tóufa Hair",
  "突然 tūrán suddenly",
  "图书馆 túshūguǎn Library",
  "腿 tuǐ leg",
  "外 wài abroad, outside",
  "完 wán finish",
  "完成 wánchéng complete",
  "玩 wán play",
  "碗 wǎn bowl",
  "晚上 wǎnshang Night",
  "万 wàn ten thousand",
  "忘记 wàngjì forget",
  "喂 wèi feed",
  "为 wèi for",
  "为了 wèile in order to",
  "为什么 wèishénme Why",
  "位 wèi position",
  "文化 wénhuà Culture",
  "问 wèn ask",
  "问题 wèntí problem",
  "我 wǒ I",
  "我们 wǒmen We",
  "五 wǔ Five",
  "西 xī west",
  "西瓜 xīguā watermelon",
  "希望 xīwàng hope",
  "习惯 xíguàn Habit",
  "洗 xǐ wash",
  "洗手间 xǐshǒujiān Restroom",
  "洗澡 xǐzǎo Take a shower",
  "喜欢 xǐhuan like",
  "下 xià lower, down",
  "下午 xiàwǔ Afternoon",
  "下雨 xiàyǔ rain",
  "夏 xià summer",
  "先 xiān first",
  "先生 xiānsheng Sir",
  "现在 xiànzài Now",
  "香蕉 xiāngjiāo Banana",
  "相同 xiāngtóng identical",
  "相信 xiāngxìn believe",
  "想 xiǎng think",
  "向 xiàng towards",
  "11",
  "像 xiàng image",
  "小 xiǎo Small",
  "小姐 xiǎojiě Miss",
  "小时 xiǎoshí hour",
  "小心 xiǎoxīn watch out",
  "笑 xiào laugh, smile",
  "校长 xiàozhǎng Principal",
  "些 xiē some",
  "鞋 xié shoes",
  "写 xiě write",
  "谢谢 xièxie Thank you",
  "新 xīn new",
  "新闻 xīnwén news",
  "新鲜 xīnxiān fresh",
  "信 xìn letter",
  "星期 xīngqī week",
  "行李箱 xínglixiāng Trunk",
  "姓 xìng surname",
  "兴趣 xìngqù Interest",
  "熊猫 xióngmāo Panda",
  "休息 xiūxi Rest",
  "需要 xūyào Need",
  "选择 xuǎnzé Choice",
  "学生 xuésheng Student",
  "学习 xuéxí Study",
  "学校 xuéxiào School",
  "雪 xuě Snow",
  "颜色 yánsè colour",
  "眼镜 yǎnjìng glasses",
  "眼睛 yǎnjing Eye",
  "羊肉 yángròu mutton",
  "要求 yāoqiú Requirement",
  "药 yào drug",
  "要 yào want",
  "爷爷 yéye grandpa",
  "也 yě also",
  "一 yī One",
  "衣服 yīfu clothes",
  "医生 yīshēng Doctor",
  "医院 yīyuàn Hospital",
  "一定 yídìng Certain",
  "一共 yígòng Altogether",
  "一会儿 yíhuìr a while",
  "一样 yíyàng equally",
  "12",
  "以后 yǐhòu In the future",
  "以前 yǐqián before",
  "以为 yǐwéi Think",
  "已经 yǐjīng Already",
  "椅子 yǐzi Chair",
  "一般 yìbān commonly",
  "一边 yìbiān One side",
  "一起 yìqǐ together",
  "一直 yìzhí always",
  "意思 yìsi Meaning",
  "阴 yīn Yin",
  "因为 yīnwèi because",
  "音乐 yīnyuè Music",
  "银行 yínháng Bank",
  "应该 yīnggāi Should",
  "影响 yǐngxiǎng Influence",
  "用 yòng use",
  "游戏 yóuxì Game",
  "游泳 yóuyǒng Swimming",
  "有 yǒu have",
  "有名 yǒumíng Famous",
  "又 yòu again",
  "右边 yòubian Right",
  "鱼 yú fish",
  "遇到 yùdào encounter",
  "元 yuán element; yuan",
  "远 yuǎn far",
  "愿意 yuànyì Be willing",
  "月 yuè month",
  "月亮 yuèliang Moon",
  "越 yuè the more",
  "云 yún cloud",
  "运动 yùndòng excercise",
  "在 zài stay; in process of",
  "再 zài again",
  "再见 zàijiàn Bye",
  "早上 zǎoshang Morning",
  "怎么 zěnme How",
  "怎么样 zěnmeyàng How about",
  "站 zhàn station",
  "张 zhāng Zhang (surname)",
  "长 zhǎng grow",
  "丈夫 zhàngfu husband",
  "着急 zháojí Worry",
  "13",
  "找 zhǎo look for",
  "照顾 zhàogù look after",
  "照片 zhàopiàn Photo",
  "照相机 zhàoxiàngjī Camera",
  "这 (这儿) zhè(zhèr) this (here)",
  "着 zhe",
  "真 zhēn real, true",
  "正在 zhèngzài in process of",
  "知道 zhīdào know",
  "只 zhǐ only",
  "中国 zhōngguó China",
  "中间 zhōngjiān Middle",
  "中午 zhōngwǔ Noon",
  "终于 zhōngyú finally",
  "种 zhǒng species",
  "重要 zhòngyào important",
  "周末 zhōumò Weekend",
  "主要 zhǔyào main",
  "住 zhù live",
  "祝 zhù wish",
  "注意 zhùyì Be careful",
  "准备 zhǔnbèi prepare",
  "桌子 zhuōzi Table",
  "字 zì character",
  "字典 zìdiǎn Dictionaries",
  "自己 zìjǐ Own, self",
  "自行车 zìxíngchē Bicycle",
  "总是 zǒngshì always",
  "走 zǒu go，walk",
  "最 zuì most",
  "最近 zuìjìn lately",
  "昨天 zuótiān Yesterday",
  "左边 zuǒbian left",
  "坐 zuò sit",
  "做 zuò do",
  "作业 zuòyè task",
  "作用 zuòyòng Effect",
];
