export default [
  "阿姨 阿姨 āyí aunt",
  "啊 啊 a ah",
  "矮 矮 ǎi short",
  "爱好 愛好 àihào hobby",
  "安静 安靜 ānjìng Be quiet",
  "把 把 bǎ hold",
  "班 班 bān class",
  "搬 搬 bān move",
  "半 半 bàn half",
  "办法 辦法 bànfǎ Way",
  "办公室 辦公室 bàngōngshì Office",
  "帮忙 幫忙 bāngmáng Help",
  "包 包 bāo package",
  "饱 飽 bǎo full",
  "北方 北方 běifāng north",
  "被 被 bèi cover",
  "鼻子 鼻子 bízi nose",
  "比 比 bǐ than",
  "比较 比較 bǐjiào compare",
  "比赛 比賽 bǐsài Match",
  "必须 必須 bìxū Must",
  "变化 變化 biànhuà change",
  "表示 表示 biǎoshì Express",
  "表演 表演 biǎoyǎn perform",
  "别人 別人 biéren Others",
  "宾馆 賓館 bīnguǎn hotel",
  "冰箱 冰箱 bīngxiāng Refrigerator",
  "才 才 cái just",
  "菜单 菜單 càidān menu",
  "参加 參加 cānjiā participate in",
  "草 草 cǎo grass",
  "层 層 céng layer",
  "差 差 chà bad",
  "超市 超市 chāoshì Supermarket",
  "衬衫 襯衫 chènshān shirt",
  "成绩 成績 chéngjì achievement",
  "城市 城市 chéngshì City",
  "迟到 遲到 chídào Late",
  "出现 出現 chūxiàn Appear",
  "厨房 廚房 chúfáng Kitchen",
  "除了 除了 chúle except, besides",
  "春 春天 chūn spring",
  "词语 詞語 cíyǔ terms, words",
  "聪明 聰明 cōngming clever",
  "打扫 打掃 dǎsǎo Clean",
  "打算 打算 dǎsuàn Plan",
  "带 帶 dài belt",
  "担心 擔心 dānxīn Worry",
  "蛋糕 蛋糕 dàngāo Cake",
  "当然 當然 dāngrán Of course",
  "灯 燈 dēng lamp",
  "低 低 dī low",
  "地方 地方 dìfang local",
  "地铁 地鐵 dìtiě metro",
  "地图 地圖 dìtú Map",
  "电梯 電梯 diàntī Elevator.",
  "电子邮件 電子郵件 diànzǐyóujiàn E-mail",
  "东 東 dōng east",
  "冬 冬季 dōng winter",
  "动物 動物 dòngwù Animal",
  "短 短 duǎn short",
  "段 段 duàn paragraph",
  "锻炼 鍛煉 duànliàn Physical exercise",
  "多么 多麼 duōme such",
  "饿 餓 è hungry",
  "而且 而且 érqiě And",
  "耳朵 耳朵 ěrduo Ears",
  "发烧 發燒 fāshāo Have a fever",
  "发现 發現 fāxiàn find, discover",
  "方便 方便 fāngbiàn convenient",
  "放 放 fàng discharge",
  "放心 放心 fàngxīn Don't worry",
  "分 分 fēn minute",
  "附近 附近 fùjìn nearby",
  "复习 複習 fùxí Review",
  "干净 乾淨 gānjìng clean",
  "敢 敢 gǎn dare",
  "感冒 感冒 gǎnmào get a cold",
  "刚才 剛才 gāngcái just",
  "跟 跟 gēn with",
  "根据 根據 gēnjù according to",
  "更 更 gèng more",
  "公司 公司 gōngsī company",
  "公园 公園 gōngyuán Park",
  "故事 故事 gùshi Story",
  "刮风 刮風 guāfēng Windy",
  "关 關 guān shut",
  "关系 關係 guānxì relationship",
  "关心 關心 guānxīn Care for",
  "关于 關於 guānyú about",
  "国家 國家 guójiā Country",
  "果汁 果汁 guǒzhī fruit juice",
  "过去 過去 guòqù Past times",
  "过 過 guo too",
  "还是 還是 háishì still",
  "害怕 害怕 hàipà Fear",
  "河 河 hé river",
  "黑板 黑板 hēibǎn blackboard",
  "护照 護照 hùzhào passport",
  "花 花 (动) huā spend (verb)",
  "花园 花園 huāyuán Garden",
  "画 畫 huà painting",
  "坏 壞 huài bad",
  "环境 環境 huánjìng Environment",
  "换 換 huàn change",
  "黄 黃 huáng yellow",
  "会议 會議 huìyì Meeting",
  "或者 或者 huòzhě perhaps",
  "几乎 幾乎 jīhū almost",
  "机会 機會 jīhuì Opportunity",
  "极 極 jí extremely",
  "记得 記得 jìde remember",
  "季节 季節 jìjié Season",
  "检查 檢查 jiǎnchá inspect",
  "简单 簡單 jiǎndān simple",
  "健康 健康 jiànkāng Healthy",
  "见面 見面 jiànmiàn meet",
  "讲 講 jiǎng speak",
  "教 教 jiāo teach",
  "角 角 jiǎo horn",
  "脚 腳 jiǎo foot",
  "接 接 jiē pick,get",
  "街道 街道 jiēdào Street",
  "结婚 結婚 jiéhūn marry",
  "结束 結束 jiéshù End",
  "节目 節目 jiémù program",
  "节日 節日 jiérì festival",
  "解决 解決 jiějué Solve",
  "借 借 jiè borrow",
  "经常 經常 jīngcháng Often",
  "经过 經過 jīngguò After, through",
  "经理 經理 jīnglǐ manager",
  "久 久 jiǔ long",
  "旧 舊 jiù old,used",
  "举行 舉行 jǔxíng hold",
  "句子 句子 jùzi sentence",
  "决定 決定 juédìng Decision",
  "渴 渴 kě thirsty",
  "可爱 可愛 kě'ài Lovely",
  "刻 刻 kè moment",
  "客人 客人 kèrén Guest",
  "空调 空調 kōngtiáo Air conditioner",
  "口 口 kǒu mouth",
  "哭 哭 kū cry",
  "裤子 褲子 kùzi trousers",
  "筷子 筷子 kuàizi chopsticks",
  "蓝 藍 lán blue",
  "老 老 lǎo old",
  "离开 離開 líkāi leave",
  "礼物 禮物 lǐwù gift",
  "历史 歷史 lìshǐ History",
  "脸 臉 liǎn face",
  "练习 練習 liànxí Practice",
  "辆 輛 liàng Car",
  "了解 了解 liǎojiě understand",
  "邻居 鄰居 línjū neighbor",
  "楼 樓 lóu floor",
  "绿 綠 lǜ green",
  "马 馬 mǎ Horse",
  "马上 馬上 mǎshàng Right off",
  "卖 賣 mài sell",
  "满意 滿意 mǎnyì Satisfied",
  "帽子 帽子 màozi Hat",
  "米 米 mǐ rice",
  "面包 麵包 miànbāo Bread",
  "面条 麵條 miàntiáo noodle",
  "明白 明白 míngbai clear",
  "拿 拿 ná take",
  "奶奶 奶奶 nǎinai grandma",
  "南 南 nán south",
  "难 難 nán difficult",
  "难过 難過 nánguò sad",
  "年级 年級 niánjí grade",
  "年轻 年輕 niánqīng Young",
  "鸟 鳥 niǎo bird",
  "努力 努力 nǔlì Strive",
  "爬山 爬山 páshān Mountain climbing",
  "盘子 盤子 pánzi plate",
  "胖 胖 pàng fat",
  "啤酒 啤酒 píjiǔ Beer",
  "葡萄 葡萄 pútao Grape",
  "普通话 普通話 pǔtōnghuà Mandarin",
  "其实 其實 qíshí actually",
  "其他 其他 qítā Other",
  "骑 騎 qí ride",
  "奇怪 奇怪 qíguài strange",
  "铅笔 鉛筆 qiānbǐ pencil",
  "清楚 清楚 qīngchu clear",
  "秋 秋 qiū autumn",
  "裙子 裙子 qúnzi skirt",
  "然后 然後 ránhòu Then",
  "热情 熱情 rèqíng Enthusiasm",
  "认为 認為 rènwéi think",
  "认真 認真 rènzhēn earnest",
  "容易 容易 róngyì easily",
  "如果 如果 rúguǒ If",
  "伞 傘 sǎn umbrella",
  "上网 上網 shàngwǎng Surf the Internet",
  "生气 生氣 shēngqì get angry",
  "声音 聲音 shēngyīn voice",
  "使 使 shǐ make",
  "世界 世界 shìjiè world",
  "瘦 瘦 shòu thin",
  "舒服 舒服 shūfu comfortable",
  "叔叔 叔叔 shūshu uncle",
  "树 樹 shù tree",
  "数学 數學 shùxué Mathematics",
  "刷牙 刷牙 shuāyá Brush one's teeth",
  "双 雙 shuāng double, pair",
  "水平 水平 shuǐpíng level",
  "司机 司機 sījī Driver",
  "虽然 雖然 suīrán although",
  "太阳 太陽 tàiyáng sun",
  "糖 糖 táng sugar",
  "特别 特別 tèbié Especially",
  "疼 疼 téng hurt",
  "提高 提高 tígāo increase",
  "体育 體育 tǐyù Sports",
  "甜 甜 tián sweet",
  "条 條 tiáo strip",
  "同事 同事 tóngshì Colleague",
  "同意 同意 tóngyì Agree",
  "头发 頭髮 tóufa Hair",
  "突然 突然 tūrán suddenly",
  "图书馆 圖書館 túshūguǎn Library",
  "腿 腿 tuǐ leg",
  "完成 完成 wánchéng complete",
  "碗 碗 wǎn bowl",
  "万 萬 wàn ten thousand",
  "忘记 忘記 wàngjì forget",
  "为 為 wèi for",
  "为了 為了 wèile in order to",
  "位 地方 wèi position",
  "文化 文化 wénhuà Culture",
  "西 西 xī west",
  "习惯 習慣 xíguàn Habit",
  "洗手间 洗手間 xǐshǒujiān Restroom",
  "洗澡 洗澡 xǐzǎo Take a shower",
  "夏 夏天 xià summer",
  "先 先 xiān first",
  "香蕉 香蕉 xiāngjiāo Banana",
  "相同 相同 xiāngtóng identical",
  "相信 相信 xiāngxìn believe",
  "像 像 xiàng image",
  "小心 小心 xiǎoxīn watch out",
  "校长 校長 xiàozhǎng Principal",
  "鞋 鞋 xié shoes",
  "新闻 新聞 xīnwén news",
  "新鲜 新鮮 xīnxiān fresh",
  "信 信 xìn letter",
  "行李箱 行李箱 xínglixiāng Trunk",
  "兴趣 興趣 xìngqù Interest",
  "熊猫 熊貓 xióngmāo Panda",
  "需要 需要 xūyào Need",
  "选择 選擇 xuǎnzé Choice",
  "眼镜 眼鏡 yǎnjìng glasses",
  "要求 要求 yāoqiú Requirement",
  "爷爷 爺爺 yéye grandpa",
  "一定 一定 yídìng Certain",
  "一共 一共 yígòng Altogether",
  "一会儿 一會兒 yíhuìr a while",
  "一样 一樣 yíyàng equally",
  "以后 以後 yǐhòu In the future",
  "以前 以前 yǐqián before",
  "以为 以為 yǐwéi Think",
  "一般 一般 yìbān commonly",
  "一边 一邊 yìbiān One side",
  "一直 一直 yìzhí always",
  "音乐 音樂 yīnyuè Music",
  "银行 銀行 yínháng Bank",
  "应该 應該 yīnggāi Should",
  "影响 影響 yǐngxiǎng Influence",
  "用 用 yòng use",
  "游戏 遊戲 yóuxì Game",
  "有名 名譽 yǒumíng Famous",
  "又 又 yòu again",
  "遇到 遇到 yùdào encounter",
  "愿意 願意 yuànyì Be willing",
  "月亮 月亮 yuèliang Moon",
  "越 越 yuè the more",
  "云 雲 yún cloud",
  "站 站 zhàn station",
  "着急 著急 zháojí Worry",
  "照顾 照顧 zhàogù look after",
  "照片 照片 zhàopiàn Photo",
  "照相机 照相機 zhàoxiàngjī Camera",
  "只 只 zhǐ only",
  "中间 中間 zhōngjiān Middle",
  "终于 終於 zhōngyú finally",
  "种 種 zhǒng species",
  "重要 重要 zhòngyào important",
  "周末 週末 zhōumò Weekend",
  "主要 主要 zhǔyào main",
  "祝 祝 zhù wish",
  "注意 注意 zhùyì Be careful",
  "字典 字典 zìdiǎn Dictionaries",
  "自己 自己 zìjǐ Own, self",
  "总是 總是 zǒngshì always",
  "最近 最近 zuìjìn lately",
  "作业 作業 zuòyè task",
  "作用 作用 zuòyòng Effect",
];
