export default [
  "阿姨 āyí aunt",
  "啊 a ah",
  "矮 ǎi short",
  "爱 ài love",
  "爱好 àihào hobby",
  "爱情 àiqíng Love",
  "安静 ānjìng Be quiet",
  "安排 ānpái arrange",
  "安全 ānquán security",
  "暗 àn dark",
  "按时 ànshí on time",
  "按照 ànzhào according to",
  "八 bā Eight",
  "把 bǎ hold",
  "爸爸 bàba Dad",
  "白 bái white",
  "百 bǎi hundred",
  "班 bān class",
  "搬 bān move",
  "半 bàn half",
  "办法 bànfǎ Way",
  "办公室 bàngōngshì Office",
  "帮忙 bāngmáng Help",
  "帮助 bāngzhù Help",
  "包 bāo package",
  "包括 bāokuò Include",
  "饱 bǎo full",
  "保护 bǎohù protect",
  "保证 bǎozhèng ensure",
  "抱 bào Hold",
  "抱歉 bàoqiàn feel sorry",
  "报道 bàodào report",
  "报名 bàomíng sign up",
  "报纸 bàozhǐ Newspaper",
  "杯子 bēizi glass",
  "北方 běifāng north",
  "北京 Běijīng Beijing",
  "倍 bèi times",
  "被 bèi cover",
  "本 běn book",
  "本来 běnlái originally",
  "笨 bèn stupid",
  "鼻子 bízi nose",
  "比 bǐ compare",
  "比较 bǐjiào compare",
  "比赛 bǐsài Match",
  "笔记本 bǐjìběn Notebook",
  "必须 bìxū Must",
  "毕业 bìyè graduation",
  "遍 biàn Times",
  "变化 biànhuà change",
  "标准 biāozhǔn standard",
  "表达 biǎodá Expression",
  "表格 biǎogé form",
  "表示 biǎoshì Express",
  "表演 biǎoyǎn perform",
  "表扬 biǎoyáng Praise",
  "别 bié other",
  "别人 biéren Others",
  "宾馆 bīnguǎn hotel",
  "冰箱 bīngxiāng Refrigerator",
  "饼干 bǐnggān Biscuits",
  "并且 bìngqiě also",
  "博士 bóshì doctor",
  "不但 búdàn not only",
  "不过 búguò However",
  "不客气 búkèqi You are welcome",
  "不 bù No",
  "不得不 bùdébù have to",
  "不管 bùguǎn no matter",
  "不仅 bùjǐn not only",
  "部分 bùfen Part",
  "擦 cā wipe",
  "猜 cāi guess",
  "才 cái just",
  "材料 cáiliào Material Science",
  "菜 cài food, dish",
  "菜单 càidān menu",
  "参观 cānguān visit",
  "参加 cānjiā participate in",
  "草 cǎo grass",
  "层 céng layer",
  "茶 chá tea",
  "差 chà difference",
  "差不多 chàbuduō Almost",
  "尝 cháng taste",
  "长 cháng long",
  "长城 chángchéng The Great Wall",
  "长江 chángjiāng The Yangtze River",
  "场 chǎng site",
  "唱歌 chànggē Sing",
  "超过 chāoguò Exceed",
  "超市 chāoshì Supermarket",
  "吵 chǎo Noisy",
  "衬衫 chènshān shirt",
  "成功 chénggōng Success",
  "成绩 chéngjì achievement",
  "成熟 chéngshú mature",
  "成为 chéngwéi Become",
  "诚实 chéngshí honest",
  "城市 chéngshì City",
  "乘坐 chéngzuò ride",
  "吃 chī eat",
  "吃惊 chījīng Be amazed",
  "迟到 chídào Late",
  "重新 chóngxīn again",
  "抽烟 chōuyān smoking",
  "出 chū come out",
  "出差 chūchāi A business travel",
  "出发 chūfā Set out",
  "出生 chūshēng Birth",
  "出现 chūxiàn Appear",
  "出租车 chūzūchē Taxi",
  "厨房 chúfáng Kitchen",
  "除了 chúle except",
  "穿 chuān Wear",
  "船 chuán ship",
  "传真 chuánzhēn Fax",
  "窗户 chuānghu Window",
  "春 chūn spring",
  "词典 cídiǎn Dictionary",
  "词语 cíyǔ terms, words",
  "次 cì times",
  "聪明 cōngming clever",
  "从 cóng from",
  "从来 cónglái Always",
  "粗心 cūxīn careless",
  "错 cuò Wrong",
  "答案 dá'àn Answer",
  "打扮 dǎban dress up",
  "打电话 dǎdiànhuà Phone call",
  "打篮球 dǎlánqiú Play basketball",
  "打扰 dǎrǎo Disturb",
  "打扫 dǎsǎo Clean",
  "打算 dǎsuàn Plan",
  "打印 dǎyìn Print",
  "打折 dǎzhé Discount",
  "打针 dǎzhēn To make an injection",
  "大 dà large, big",
  "大概 dàgài Probably",
  "大家 dàjiā everybody",
  "大使馆 dàshǐguǎn Embassy",
  "大约 dàyuē about",
  "带 dài belt",
  "戴 dài wear",
  "代表 dàibiǎo representative",
  "代替 dàitì replace",
  "大夫 dàifu Doctor",
  "担心 dānxīn Worry",
  "蛋糕 dàngāo Cake",
  "但是 dànshì however",
  "当 dāng When",
  "当地 dāngdì Local",
  "当然 dāngrán Of course",
  "当时 dāngshí at that time",
  "刀 dāo knife",
  "导游 dǎoyóu Guide",
  "到 dào reach",
  "到处 dàochù everywhere",
  "到底 dàodǐ To the end",
  "道歉 dàoqiàn apologize",
  "得意 déyì Proud",
  "得 děi have to",
  "灯 dēng lamp",
  "等 (动) děng Wait (verb)",
  "等 (助) děng Etc",
  "低 dī low",
  "底 dǐ bottom",
  "弟弟 dìdi Younger brother",
  "地方 dìfang location, place",
  "地球 dìqiú earth",
  "地铁 dìtiě metro",
  "地图 dìtú Map",
  "地址 dìzhǐ address",
  "第一 dìyī first",
  "点 diǎn spot",
  "电脑 diànnǎo Computer",
  "电视 diànshì television",
  "电梯 diàntī Elevator.",
  "电影 diànyǐng Film",
  "电子邮件 diànzǐyóujiàn E-mail",
  "掉 diào fall",
  "调查 diàochá investigation",
  "丢 diū lose",
  "冬 dōng winter",
  "东 dōng east",
  "东西 dōngxi thing",
  "懂 dǒng understand",
  "动物 dòngwù Animal",
  "动作 dòngzuò action",
  "都 dōu all",
  "读 dú read",
  "堵车 dǔchē Traffic jam",
  "肚子 dùzi belly",
  "短 duǎn short",
  "段 duàn paragraph",
  "断 duàn break",
  "锻炼 duànliàn Physical exercise",
  "对 duì Pair, couple",
  "对 duì to, for",
  "对不起 duìbuqǐ I'm sorry.",
  "对话 duìhuà dialogue",
  "对面 duìmiàn Opposite side",
  "顿 dùn Meal",
  "多 duō many",
  "多么 duōme what, how",
  "多少 duōshao how much",
  "朵 duǒ classifier of flower",
  "饿 è hungry",
  "而 ér and",
  "而且 érqiě And",
  "儿童 értóng children",
  "儿子 érzi Son",
  "耳朵 ěrduo Ears",
  "二 èr Two",
  "发 fā send out",
  "发烧 fāshāo Have a fever",
  "发生 fāshēng Happen",
  "发现 fāxiàn find",
  "发展 fāzhǎn Development",
  "法律 fǎlǜ Law",
  "翻译 fānyì translate",
  "烦恼 fánnǎo annoyance",
  "反对 fǎnduì Opposition",
  "反映 fǎnyìng reflect",
  "饭馆 fànguǎn restaurant",
  "范围 fànwéi Range",
  "方便 fāngbiàn convenient",
  "方法 fāngfǎ Method",
  "方面 fāngmiàn Aspect",
  "方向 fāngxiàng direction",
  "房间 fángjiān Room",
  "访问 fǎngwèn Visit",
  "放 fàng discharge",
  "放弃 fàngqì give up",
  "放暑假 fàngshǔjià summer vacation",
  "放心 fàngxīn Don't worry",
  "非常 fēicháng very",
  "飞机 fēijī aircraft",
  "分 fēn minute",
  "分之 fēnzhī percent",
  "分钟 fēnzhōng Minute",
  "份 fèn share (measure word)",
  "丰富 fēngfù rich",
  "风景 fēngjǐng Scenery",
  "否则 fǒuzé otherwise",
  "符合 fúhé accord with",
  "服务员 fúwùyuán Waiter",
  "富 fù rich",
  "附近 fùjìn nearby",
  "父亲 fùqīn father",
  "复习 fùxí Review",
  "复印 fùyìn To copy",
  "复杂 fùzá complex",
  "负责 fùzé Be responsible for",
  "改变 gǎibiàn change",
  "干杯 gānbēi Cheers!",
  "干净 gānjìng clean",
  "干燥 gānzào Dry",
  "敢 gǎn dare",
  "感动 gǎndòng Be moved",
  "感觉 gǎnjué feel",
  "感冒 gǎnmào get cold",
  "感情 gǎnqíng feeling",
  "感谢 gǎnxiè Thank",
  "干 gān dry",
  "刚才 gāngcái just",
  "刚刚 gānggāng just",
  "高 gāo high",
  "高级 gāojí senior",
  "高兴 gāoxìng happy",
  "告诉 gàosu tell",
  "哥哥 gēge older brother",
  "各 gè various",
  "个 gè individual",
  "个子 gèzi Height",
  "给 gěi give",
  "跟 gēn with",
  "根据 gēnjù according to",
  "更 gèng more",
  "公共汽车 gōnggòngqìchē Bus",
  "公斤 gōngjīn Kilogram",
  "公里 gōnglǐ kilometre",
  "公司 gōngsī company",
  "公园 gōngyuán Park",
  "工具 gōngjù tool",
  "工资 gōngzī wages",
  "工作 gōngzuò work",
  "共同 gòngtóng common",
  "狗 gǒu Dog",
  "够 gòu enough",
  "购物 gòuwù Shopping",
  "孤单 gūdān alone",
  "估计 gūjì estimate",
  "鼓励 gǔlì encourage",
  "鼓掌 gǔzhǎng applause",
  "顾客 gùkè customer",
  "故事 gùshi Story",
  "故意 gùyì deliberately",
  "刮风 guāfēng Windy",
  "挂 guà hang",
  "关 guān shut down, close",
  "关键 guānjiàn key",
  "关系 guānxì relationship",
  "关心 guānxīn Care for",
  "关于 guānyú about",
  "观众 guānzhòng Audience",
  "管理 guǎnlǐ Administration",
  "光 guāng light",
  "广播 guǎngbō Radio broadcast",
  "广告 guǎnggào Advertisement",
  "逛 guàng Stroll",
  "规定 guīdìng Regulations",
  "贵 guì Expensive",
  "国际 guójì international",
  "国家 guójiā Country",
  "果然 guǒrán Sure enough",
  "果汁 guǒzhī fruit juice",
  "过 (动) guò pass",
  "过 (助) guo Over",
  "过程 guòchéng process",
  "过去 guòqù Past times",
  "还 hái still",
  "还是 háishì still",
  "孩子 háizi Children",
  "海洋 hǎiyáng ocean",
  "害怕 hàipà Fear",
  "害羞 hàixiū Shy",
  "寒假 hánjià The winter vacation",
  "汗 hàn sweat",
  "汉语 hànyǔ Chinese",
  "航班 hángbān flight",
  "好 hǎo good",
  "好吃 hǎochī Yummy",
  "好处 hǎochù benefit",
  "好像 hǎoxiàng Be like, seem",
  "号 hào Number",
  "号码 hàomǎ number",
  "喝 hē drink",
  "和 hé and",
  "河 hé river",
  "合格 hégé qualified",
  "合适 héshì appropriate",
  "盒子 hézi Box",
  "黑 hēi black",
  "黑板 hēibǎn blackboard",
  "很 hěn very",
  "红 hóng red",
  "猴子 hóuzi Monkey",
  "厚 hòu thick",
  "后悔 hòuhuǐ regret",
  "后来 hòulái later",
  "后面 hòumiàn behind",
  "忽然 hūrán suddenly",
  "护士 hùshi Nurse",
  "护照 hùzhào passport",
  "互相 hùxiāng each other",
  "花 (动) huā spend",
  "花园 huāyuán Garden",
  "画 huà painting",
  "怀疑 huáiyí doubt",
  "坏 huài bad",
  "欢迎 huānyíng Welcome",
  "还 huán return",
  "环境 huánjìng Environment",
  "换 huàn change",
  "黄 huáng yellow",
  "回 huí return",
  "回答 huídá Answer",
  "回忆 huíyì Memory",
  "会 huì can;be able to",
  "会议 huìyì Meeting",
  "活动 huódòng activity",
  "活泼 huópō lively",
  "火 huǒ fire",
  "火车站 huǒchēzhàn Train station",
  "获得 huòdé Get",
  "或者 huòzhě perhaps",
  "机场 jīchǎng Airport",
  "机会 jīhuì Opportunity",
  "基础 jīchǔ Basics",
  "鸡蛋 jīdàn Egg",
  "激动 jīdòng Excited",
  "几乎 jīhū almost",
  "积极 jījí positive",
  "积累 jīlěi accumulation",
  "极 jí extremely",
  "极其 jíqí extremely",
  "集合 jíhé aggregate",
  "及时 jíshí timely",
  "即使 jíshǐ even if",
  "几 jǐ several",
  "寄 jì send",
  "记得 jìde remember",
  "记者 jìzhě Reporter",
  "计划 jìhuà plan",
  "季节 jìjié Season",
  "既然 jìrán although",
  "技术 jìshù technology",
  "继续 jìxù Continue",
  "家 jiā home",
  "家具 jiājù furniture",
  "加班 jiābān overtime work",
  "加油站 jiāyóuzhàn Gas station",
  "假 jiǎ false",
  "价格 jiàgé Price",
  "坚持 jiānchí Insist",
  "检查 jiǎnchá inspect; check",
  "简单 jiǎndān simple",
  "减肥 jiǎnféi Reduce weight",
  "减少 jiǎnshǎo reduce",
  "件 jiàn piece",
  "健康 jiànkāng Healthy",
  "见面 jiànmiàn meet",
  "将来 jiānglái future",
  "讲 jiǎng speak",
  "奖金 jiǎngjīn bonus",
  "降低 jiàngdī reduce",
  "教 jiāo teach",
  "交 jiāo hand over",
  "交流 jiāoliú Communication",
  "交通 jiāotōng traffic",
  "骄傲 jiāo'ào Proud",
  "角 jiǎo horn",
  "脚 jiǎo foot",
  "饺子 jiǎozi Dumplings",
  "叫 jiào call",
  "教室 jiàoshì Classroom",
  "教授 jiàoshòu professor",
  "教育 jiàoyù education",
  "接 jiē meet, pick",
  "接受 jiēshòu accept",
  "街道 jiēdào Street",
  "结果 jiéguǒ Result",
  "结婚 jiéhūn get married",
  "结束 jiéshù End",
  "节目 jiémù program",
  "节日 jiérì festival",
  "节约 jiéyuē save",
  "姐姐 jiějie older sister",
  "解决 jiějué Solve",
  "解释 jiěshì explain",
  "借 jiè borrow",
  "介绍 jièshào introduce",
  "今天 jīntiān Today",
  "尽管 jǐnguǎn although",
  "紧张 jǐnzhāng Nervous",
  "近 jìn near",
  "进 jìn enter",
  "进行 jìnxíng in process of",
  "禁止 jìnzhǐ prohibit",
  "精彩 jīngcǎi Marvellous",
  "精神 jīngshén spirit",
  "经常 jīngcháng Often",
  "经过 jīngguò through",
  "经济 jīngjì Economics",
  "经理 jīnglǐ manager",
  "经历 jīnglì experience",
  "经验 jīngyàn experience",
  "京剧 jīngjù Beijing opera",
  "警察 jǐngchá Policeman",
  "竟然 jìngrán Unexpectedly",
  "竞争 jìngzhēng compete",
  "镜子 jìngzi Mirror",
  "究竟 jiūjìng exactly",
  "九 jiǔ Nine",
  "久 jiǔ long",
  "旧 jiù used, old",
  "举办 jǔbàn hold",
  "举行 jǔxíng hold",
  "拒绝 jùjué refuse",
  "距离 jùlí distance",
  "句子 jùzi sentence",
  "觉得 juéde Think",
  "决定 juédìng Decision",
  "咖啡 kāfēi Coffee",
  "开 kāi open",
  "开始 kāishǐ start",
  "开玩笑 kāiwánxiào Make fun of",
  "看 kàn see",
  "看法 kànfǎ view",
  "看见 kànjiàn seeing",
  "考虑 kǎolǜ Consider",
  "考试 kǎoshì Examination",
  "棵 kē Tree (measure word)",
  "科学 kēxué science",
  "咳嗽 késou cough",
  "渴 kě thirsty",
  "可爱 kě'ài Lovely",
  "可怜 kělián Poor",
  "可能 kěnéng Probably",
  "可是 kěshì however",
  "可惜 kěxī unfortunately",
  "可以 kěyǐ Sure",
  "刻 kè moment",
  "课 kè course",
  "客人 kèrén Guest",
  "肯定 kěndìng sure",
  "空气 kōngqì air",
  "空调 kōngtiáo Air conditioner",
  "恐怕 kǒngpà I'm afraid",
  "口 kǒu mouth",
  "哭 kū cry",
  "苦 kǔ bitter",
  "裤子 kùzi trousers",
  "块 kuài block",
  "快 kuài fast",
  "快乐 kuàilè happy",
  "筷子 kuàizi chopsticks",
  "宽 kuān wide",
  "困 kùn sleepy",
  "困难 kùnnan difficulty",
  "扩大 kuòdà Expand",
  "拉 lā pull",
  "垃圾桶 lājītǒng Trash",
  "辣 là spicy",
  "来 lái come",
  "来不及 láibují There's not enough time",
  "来得及 láidejí In time",
  "蓝 lán blue",
  "懒 lǎn lazy",
  "浪费 làngfèi Waste",
  "浪漫 làngmàn romantic",
  "老 lǎo old",
  "老虎 lǎohǔ Tiger",
  "老师 lǎoshī Teacher",
  "累 lèi tired",
  "冷 lěng cold",
  "冷静 lěngjìng calm down",
  "离 lí leave",
  "离开 líkāi leave",
  "里 lǐ in",
  "理发 lǐfà Haircut",
  "理解 lǐjiě Understand",
  "理想 lǐxiǎng ideal",
  "礼貌 lǐmào politeness",
  "礼物 lǐwù gift",
  "厉害 lìhai Fierce",
  "力气 lìqi Strength",
  "例如 lìrú for example",
  "历史 lìshǐ History",
  "俩 liǎ Two",
  "连 lián even",
  "联系 liánxì contact",
  "脸 liǎn face",
  "练习 liànxí Practice",
  "凉快 liángkuai Pleasantly cool",
  "两 liǎng Two",
  "亮 liàng bright",
  "辆 liàng Car (measure word)",
  "聊天 liáotiān chat",
  "了解 liǎojiě understand",
  "邻居 línjū neighbor",
  "零 líng Zero",
  "另外 lìngwài in addition",
  "留 liú stay",
  "留学 liúxué Overseas Study",
  "流泪 liúlèi Shed tears",
  "流利 liúlì fluent",
  "流行 liúxíng Popular",
  "六 liù Six",
  "楼 lóu floor",
  "路 lù road",
  "乱 luàn chaos",
  "旅游 lǚyóu Tourism",
  "绿 lǜ green",
  "律师 lǜshī Lawyer",
  "妈妈 māma Mom",
  "麻烦 máfan trouble",
  "马 mǎ Horse",
  "马虎 mǎhu Careless",
  "马上 mǎshàng Right off",
  "买 mǎi buy",
  "卖 mài sell",
  "满 mǎn full",
  "满意 mǎnyì Satisfied",
  "慢 màn slow",
  "忙 máng busy",
  "猫 māo cat",
  "毛巾 máojīn Towel",
  "帽子 màozi Hat",
  "没 méi no",
  "没关系 méiguānxi No problem",
  "每 měi each",
  "美丽 měilì beautiful",
  "妹妹 mèimei Younger sister",
  "门 mén door",
  "梦 mèng dream",
  "米 mǐ rice",
  "米饭 mǐfàn Steamed Rice",
  "密码 mìmǎ Password",
  "免费 miǎnfèi Free of charge",
  "面包 miànbāo Bread",
  "面条 miàntiáo noodle",
  "民族 mínzú Nation",
  "明白 míngbai clear",
  "明天 míngtiān Tomorrow",
  "名字 míngzi Name",
  "母亲 mǔqīn mother",
  "目的 mùdì objective",
  "拿 ná take",
  "哪 (哪儿) nǎ(nǎr) Which (where)",
  "那 (那儿) nà(nàr) That (there)",
  "奶奶 nǎinai grandma",
  "耐心 nàixīn patience",
  "南 nán south",
  "难 nán difficult",
  "难道 nándào could it be said that ...",
  "难过 nánguò Sorry",
  "难受 nánshòu Uncomfortable",
  "男人 nánrén Man",
  "内 nèi within",
  "内容 nèiróng content",
  "能 néng can",
  "能力 nénglì ability",
  "你 nǐ you",
  "年 nián year",
  "年级 niánjí grade",
  "年龄 niánlíng Age",
  "年轻 niánqīng Young",
  "鸟 niǎo bird",
  "您 nín you",
  "牛奶 niúnǎi milk",
  "农村 nóngcūn countryside",
  "弄 nòng get, make",
  "努力 nǔlì Strive",
  "暖和 nuǎnhuo warm",
  "女儿 nǚ'ér daughter",
  "女人 nǚrén woman",
  "偶尔 ǒu'ěr occasionally",
  "爬山 páshān Mountain climbing",
  "排列 páiliè array",
  "盘子 pánzi plate",
  "判断 pànduàn judge",
  "旁边 pángbiān Side",
  "胖 pàng fat",
  "跑步 pǎobù Run",
  "陪 péi accompany",
  "朋友 péngyou Friend",
  "批评 pīpíng criticism",
  "皮肤 pífū skin",
  "啤酒 píjiǔ Beer",
  "脾气 píqi Bad temper",
  "篇 piān piece",
  "便宜 piányi Cheap",
  "骗 piàn fool",
  "票 piào ticket",
  "漂亮 piàoliang beautiful",
  "乒乓球 pīngpāngqiú Table Tennis",
  "苹果 píngguǒ Apple",
  "平时 píngshí peacetime",
  "瓶子 píngzi Bottle",
  "破 pò broken",
  "葡萄 pútao Grape",
  "普遍 pǔbiàn universal",
  "普通话 pǔtōnghuà Mandarin",
  "七 qī Seven",
  "妻子 qīzi Wife",
  "骑 qí ride",
  "其次 qícì Secondly",
  "其实 qíshí actually",
  "其他 qítā Other",
  "其中 qízhōng among",
  "奇怪 qíguài strange",
  "起床 qǐchuáng Get up",
  "起飞 qǐfēi take off",
  "起来 qǐlái get up",
  "气候 qìhòu climate",
  "千 qiān thousand",
  "千万 qiānwàn Must",
  "铅笔 qiānbǐ pencil",
  "签证 qiānzhèng visa",
  "钱 qián money",
  "前面 qiánmiàn Front",
  "墙 qiáng wall",
  "敲 qiāo knock",
  "桥 qiáo Bridge",
  "巧克力 qiǎokèlì Chocolates",
  "亲戚 qīnqi Relative",
  "轻 qīng light",
  "轻松 qīngsōng Relaxed",
  "清楚 qīngchu clear",
  "晴 qíng Sunny",
  "情况 qíngkuàng Situation",
  "请 qǐng please",
  "请假 qǐngjià leave",
  "请客 qǐngkè Treat",
  "穷 qióng poor",
  "秋 qiū autumn",
  "区别 qūbié Difference",
  "取 qǔ take",
  "去 qù go",
  "去年 qùnián Last year",
  "全部 quánbù whole",
  "缺点 quēdiǎn shortcoming",
  "缺少 quēshǎo Lack",
  "却 què but",
  "确实 quèshí Exactly",
  "群 qún group",
  "裙子 qúnzi skirt",
  "然而 rán'ér however",
  "然后 ránhòu Then",
  "让 ràng Give Way",
  "热 rè heat",
  "热闹 rènao lively",
  "热情 rèqíng Enthusiasm",
  "人 rén people",
  "人民币 rénmínbì RMB",
  "任何 rènhé whatever, any",
  "任务 rènwu task",
  "认识 rènshi know",
  "认为 rènwéi think",
  "认真 rènzhēn earnest",
  "扔 rēng throw",
  "仍然 réngrán still",
  "日 rì day",
  "日记 rìjì diary",
  "容易 róngyì easily",
  "如果 rúguǒ If",
  "入口 rùkǒu Entrance",
  "软 ruǎn soft",
  "三 sān Three",
  "伞 sǎn umbrella",
  "散步 sànbù Take a walk",
  "森林 sēnlín Forest",
  "沙发 shāfā Sofa",
  "商店 shāngdiàn Shop",
  "商量 shāngliang discuss",
  "伤心 shāngxīn Sad",
  "上 shàng upper",
  "上班 shàngbān go to work",
  "上网 shàngwǎng Surf the Internet",
  "上午 shàngwǔ morning",
  "稍微 shāowēi slightly",
  "少 shǎo less",
  "社会 shèhuì Sociology",
  "谁 shéi who",
  "深 shēn deep",
  "申请 shēnqǐng Apply",
  "身体 shēntǐ body",
  "什么 shénme What",
  "甚至 shènzhì Even to the extent that",
  "生病 shēngbìng Fall ill, get sick",
  "生活 shēnghuó Life",
  "生命 shēngmìng life",
  "生气 shēngqì get angry",
  "生日 shēngrì Birthday",
  "声音 shēngyīn voice",
  "省 shěng province",
  "剩 shèng Left",
  "失败 shībài fail",
  "失望 shīwàng Disappointment",
  "师傅 shīfu Master worker",
  "湿润 shīrùn Moist",
  "狮子 shīzi Lion",
  "十 shí Ten",
  "十分 shífēn very",
  "时候 shíhou time",
  "时间 shíjiān time",
  "实际 shíjì Actual",
  "实在 shízài really",
  "食品 shípǐn food",
  "使 shǐ make",
  "使用 shǐyòng Use",
  "是 shì yes",
  "试 shì try",
  "市场 shìchǎng market",
  "适合 shìhé Fit",
  "适应 shìyìng Adapt",
  "世纪 shìjì century",
  "世界 shìjiè world",
  "事情 shìqing Thing",
  "收 shōu collect",
  "收入 shōurù income",
  "收拾 shōushi Tidy",
  "手表 shǒubiǎo Wrist Watch",
  "手机 shǒujī Mobile phone",
  "首都 shǒudū capital",
  "首先 shǒuxiān First",
  "瘦 shòu thin",
  "受不了 shòubuliǎo Cannot bear sth",
  "受到 shòudào Suffer",
  "售货员 shòuhuòyuán Salesperson",
  "书 shū book",
  "输 shū lose, fail",
  "舒服 shūfu comfortable",
  "叔叔 shūshu uncle",
  "熟悉 shúxī be familiar with",
  "树 shù tree",
  "数量 shùliàng Number",
  "数学 shùxué Mathematics",
  "数字 shùzì number",
  "刷牙 shuāyá Brush one's teeth",
  "帅 shuài Handsome",
  "双 shuāng double",
  "水 shuǐ water",
  "水果 shuǐguǒ Fruits",
  "水平 shuǐpíng level",
  "睡觉 shuìjiào sleep",
  "顺便 shùnbiàn Incidentally",
  "顺利 shùnlì smoothly",
  "顺序 shùnxù order",
  "说话 shuōhuà speak",
  "说明 shuōmíng Explain",
  "硕士 shuòshì master",
  "司机 sījī Driver",
  "死 sǐ die",
  "四 sì Four",
  "送 sòng give",
  "速度 sùdù speed",
  "塑料袋 sùliàodài Plastic bag",
  "酸 suān acid",
  "算 suàn count",
  "虽然 suīrán although",
  "随便 suíbiàn casual",
  "随着 suízhe along with",
  "岁 suì year",
  "孙子 sūnzi Grandson",
  "所以 suǒyǐ therefore",
  "所有 suǒyǒu All",
  "他 tā he",
  "她 tā she",
  "它 tā it",
  "台 tái platform",
  "抬 tái Lift",
  "太 tài too",
  "太阳 tàiyáng sunlight",
  "态度 tàidu attitude",
  "谈 tán talk",
  "弹钢琴 tángāngqín Play the piano",
  "汤 tāng soup",
  "糖 táng sugar",
  "躺 tǎng lie",
  "趟 tàng Trip",
  "讨论 tǎolùn discuss",
  "讨厌 tǎoyàn Hate",
  "特别 tèbié Especially",
  "特点 tèdiǎn Characteristic",
  "疼 téng hurt",
  "踢足球 tīzúqiú Play football",
  "题 tí topic",
  "提高 tígāo increase",
  "提供 tígōng provide",
  "提前 tíqián in advance",
  "提醒 tíxǐng remind",
  "体育 tǐyù Sports",
  "天气 tiānqì weather",
  "甜 tián sweet",
  "填空 tiánkòng Fill in the blanks",
  "条 tiáo strip",
  "条件 tiáojiàn condition",
  "跳舞 tiàowǔ dance",
  "听 tīng hear",
  "停止 tíngzhǐ Stop it",
  "挺 tǐng quite",
  "通过 tōngguò through",
  "通知 tōngzhī notice",
  "同情 tóngqíng Sympathy",
  "同事 tóngshì Colleague",
  "同学 tóngxué Classmate",
  "同意 tóngyì Agree",
  "头发 tóufa Hair",
  "突然 tūrán suddenly",
  "图书馆 túshūguǎn Library",
  "推 tuī push",
  "推迟 tuīchí delay",
  "腿 tuǐ leg",
  "脱 tuō take off",
  "袜子 wàzi Socks",
  "外 wài abroad, outside",
  "玩 wán play",
  "完 wán finish",
  "完成 wánchéng complete, finish",
  "完全 wánquán completely",
  "碗 wǎn bowl",
  "晚上 wǎnshang Night",
  "万 wàn ten thousand",
  "往 wǎng to, towards",
  "往往 wǎngwǎng Often",
  "网球 wǎngqiú Tennis",
  "网站 wǎngzhàn website",
  "忘记 wàngjì forget",
  "危险 wēixiǎn danger",
  "喂 wèi feed",
  "位 wèi position",
  "为 wèi by",
  "为了 wèile in order to",
  "为什么 wèishénme Why",
  "味道 wèidào taste",
  "温度 wēndù temperature",
  "文化 wénhuà Culture",
  "文章 wénzhāng Article",
  "问 wèn ask",
  "问题 wèntí problem",
  "我 wǒ I",
  "我们 wǒmen We",
  "握手 wòshǒu Handshake",
  "污染 wūrǎn contaminated",
  "无 wú nothing",
  "无聊 wúliáo Boring",
  "无论 wúlùn no matter what",
  "五 wǔ Five",
  "误会 wùhuì Misunderstanding",
  "西 xī west",
  "西瓜 xīguā watermelon",
  "西红柿 xīhóngshì Tomato",
  "希望 xīwàng hope",
  "吸引 xīyǐn Attract",
  "习惯 xíguàn Habit",
  "洗 xǐ wash",
  "洗手间 xǐshǒujiān Restroom",
  "洗衣机 xǐyījī Washing machine",
  "洗澡 xǐzǎo Take a shower",
  "喜欢 xǐhuan like",
  "夏 xià summer",
  "下 xià lower",
  "下午 xiàwǔ Afternoon",
  "下雨 xiàyǔ rain",
  "先 xiān before",
  "先生 xiānsheng Sir",
  "咸 xián salty",
  "现代 xiàndài modern",
  "现在 xiànzài Now",
  "羡慕 xiànmù Envy",
  "限制 xiànzhì limit",
  "香 xiāng fragrant",
  "香蕉 xiāngjiāo Banana",
  "相反 xiāngfǎn Contrary",
  "相同 xiāngtóng identical",
  "相信 xiāngxìn believe",
  "详细 xiángxì detailed",
  "响 xiǎng ring",
  "想 xiǎng think",
  "向 xiàng towards",
  "像 xiàng image",
  "消息 xiāoxi message",
  "小 xiǎo Small",
  "小姐 xiǎojiě Miss",
  "小时 xiǎoshí hour",
  "小说 xiǎoshuō Novel",
  "小心 xiǎoxīn Look out",
  "笑 xiào laugh",
  "笑话 xiàohua joke",
  "效果 xiàoguǒ Effect",
  "校长 xiàozhǎng Principal",
  "些 xiē some",
  "鞋 xié shoes",
  "写 xiě write",
  "谢谢 xièxie Thank you",
  "新 xīn new",
  "新闻 xīnwén news",
  "新鲜 xīnxiān fresh",
  "辛苦 xīnkǔ hard",
  "心情 xīnqíng mood",
  "信 xìn letter",
  "信任 xìnrèn trust",
  "信心 xìnxīn confidence",
  "信用卡 xìnyòngkǎ Credit card",
  "兴奋 xīngfèn Excitement",
  "星期 xīngqī week",
  "行 xíng That's ok",
  "行李箱 xínglixiāng Trunk",
  "醒 xǐng wake up",
  "姓 xìng surname",
  "性别 xìngbié Gender",
  "性格 xìnggé character",
  "幸福 xìngfú happiness",
  "兴趣 xìngqù Interest",
  "熊猫 xióngmāo Panda",
  "修 xiū repair",
  "休息 xiūxi Rest",
  "需要 xūyào Need",
  "许多 xǔduō many",
  "选择 xuǎnzé Choice",
  "学生 xuésheng Student",
  "学习 xuéxí Study",
  "学校 xuéxiào School",
  "雪 xuě Snow",
  "血 xuè blood",
  "压力 yālì pressure",
  "牙膏 yágāo toothpaste",
  "亚洲 yàzhōu Asia",
  "呀 ya ah",
  "盐 yán salt",
  "严格 yángé strict",
  "严重 yánzhòng serious",
  "研究生 yánjiūshēng Graduate student",
  "颜色 yánsè colour",
  "演出 yǎnchū show",
  "演员 yǎnyuán performer, actor",
  "眼镜 yǎnjìng glasses",
  "眼睛 yǎnjing Eye",
  "阳光 yángguāng Sunshine",
  "羊肉 yángròu mutton",
  "养成 yǎngchéng Cultivate",
  "样子 yàngzi A look",
  "邀请 yāoqǐng Invitation",
  "要求 yāoqiú Requirement",
  "要 yào want",
  "药 yào drug",
  "钥匙 yàoshi Key",
  "爷爷 yéye grandpa",
  "也 yě also",
  "也许 yěxǔ perhaps",
  "页 yè page",
  "叶子 yèzi Leaf",
  "一 yī One",
  "衣服 yīfu clothes",
  "医生 yīshēng Doctor",
  "医院 yīyuàn Hospital",
  "一定 yídìng Certain",
  "一共 yígòng Altogether",
  "一会儿 yíhuìr A little while",
  "一切 yíqiè everything",
  "一样 yíyàng equally",
  "以 yǐ with",
  "以后 yǐhòu In the future",
  "以前 yǐqián before",
  "以为 yǐwéi Think",
  "已经 yǐjīng Already",
  "椅子 yǐzi Chair",
  "亿 yì Billion",
  "一般 yìbān commonly",
  "一边 yìbiān One side",
  "一起 yìqǐ together",
  "一直 yìzhí always",
  "意见 yìjiàn Opinion",
  "意思 yìsi Meaning",
  "艺术 yìshù Art",
  "阴 yīn Yin",
  "因此 yīncǐ therefore",
  "因为 yīnwèi because",
  "音乐 yīnyuè Music",
  "银行 yínháng Bank",
  "饮料 yǐnliào Drinks",
  "引起 yǐnqǐ cause",
  "印象 yìnxiàng impression",
  "应该 yīnggāi Should",
  "赢 yíng win",
  "影响 yǐngxiǎng Influence",
  "硬 yìng hard",
  "勇敢 yǒnggǎn Brave",
  "永远 yǒngyuǎn forever",
  "用 yòng use",
  "优点 yōudiǎn Advantage",
  "优秀 yōuxiù excellent",
  "幽默 yōumò Humor",
  "由 yóu from",
  "由于 yóuyú Because",
  "尤其 yóuqí especially",
  "游戏 yóuxì Game",
  "游泳 yóuyǒng Swimming",
  "有 yǒu have",
  "有名 yǒumíng Famous",
  "有趣 yǒuqù interesting",
  "友好 yǒuhǎo friendly",
  "友谊 yǒuyì friendship",
  "又 yòu also",
  "右边 yòubian Right",
  "鱼 yú fish",
  "愉快 yúkuài Cheerful",
  "于是 yúshì Therefore",
  "与 yǔ and",
  "语法 yǔfǎ grammar",
  "语言 yǔyán language",
  "羽毛球 yǔmáoqiú Badminton",
  "遇到 yùdào encounter",
  "预习 yùxí Preview",
  "元 yuán element, Yuan",
  "圆 yuán circle",
  "原来 yuánlái Original",
  "原谅 yuánliàng Forgive",
  "原因 yuányīn Reason",
  "远 yuǎn far",
  "愿意 yuànyì Be willing",
  "约会 yuēhuì Date",
  "越 yuè The more",
  "月 yuè month",
  "月亮 yuèliang Moon",
  "阅读 yuèdú Read",
  "云 yún cloud",
  "允许 yǔnxǔ allow",
  "运动 yùndòng motion",
  "杂志 zázhì Magazine",
  "在 zài stay",
  "再 zài again",
  "再见 zàijiàn Bye",
  "咱们 zánmen We",
  "暂时 zànshí temporary",
  "脏 zāng dirty",
  "早上 zǎoshang Morning",
  "责任 zérèn responsibility",
  "怎么 zěnme How",
  "怎么样 zěnmeyàng How about",
  "增加 zēngjiā increase",
  "增长 zēngzhǎng increase",
  "窄 zhǎi narrow",
  "站 zhàn station",
  "张 zhāng Zhang",
  "长 zhǎng grow",
  "丈夫 zhàngfu husband",
  "招聘 zhāopìn recruit",
  "着急 zháojí Worry",
  "找 zhǎo look for",
  "照顾 zhàogù look after",
  "照片 zhàopiàn Photo",
  "照相机 zhàoxiàngjī Camera",
  "这 (这儿) zhè(zhèr) Here (here)",
  "着 zhe in process of",
  "真 zhēn really",
  "真正 zhēnzhèng real",
  "整理 zhěnglǐ Arrangement",
  "整齐 zhěngqí neat",
  "正常 zhèngcháng normal",
  "正好 zhènghǎo Just right",
  "正确 zhèngquè Correct",
  "正式 zhèngshì formal",
  "正在 zhèngzài in process of",
  "证明 zhèngmíng Prove",
  "之 zhī of",
  "只 zhī only",
  "支持 zhīchí Support",
  "知道 zhīdào know",
  "知识 zhīshi knowledge",
  "值得 zhídé Worth",
  "直接 zhíjiē direct",
  "植物 zhíwù Botany, plant",
  "职业 zhíyè Occupation",
  "指 zhǐ finger, to point",
  "只 zhǐ only",
  "只好 zhǐhǎo have to",
  "只要 zhǐyào as long as",
  "质量 zhìliàng quality",
  "至少 zhìshǎo at least",
  "制造 zhìzào Manufacture",
  "中国 zhōngguó China",
  "中间 zhōngjiān Middle",
  "中文 zhōngwén Chinese",
  "中午 zhōngwǔ Noon",
  "终于 zhōngyú finally",
  "种 zhǒng species",
  "重点 zhòngdiǎn A key",
  "重视 zhòngshì importance, attach importance to",
  "重要 zhòngyào important",
  "周末 zhōumò Weekend",
  "周围 zhōuwéi around",
  "猪 zhū pig",
  "逐渐 zhújiàn gradually",
  "主动 zhǔdòng active",
  "主要 zhǔyào main",
  "主意 zhǔyi idea",
  "住 zhù live",
  "祝 zhù wish",
  "祝贺 zhùhè Congratulate",
  "著名 zhùmíng famous",
  "注意 zhùyì Be careful",
  "专门 zhuānmén specialized",
  "专业 zhuānyè major",
  "赚 zhuàn earn",
  "撞 zhuàng Hit",
  "准备 zhǔnbèi Get ready",
  "准确 zhǔnquè accuracy",
  "准时 zhǔnshí on time",
  "桌子 zhuōzi Table",
  "仔细 zǐxì careful",
  "字 zì word, character",
  "字典 zìdiǎn Dictionaries",
  "自己 zìjǐ Own, self",
  "自然 zìrán natural",
  "自行车 zìxíngchē Bicycle",
  "总结 zǒngjié summary",
  "总是 zǒngshì always",
  "走 zǒu go",
  "租 zū rent",
  "组成 zǔchéng Form",
  "组织 zǔzhī organization",
  "嘴 zuǐ mouth",
  "最 zuì most",
  "最好 zuìhǎo Best",
  "最后 zuìhòu Last",
  "最近 zuìjìn Lately",
  "尊重 zūnzhòng respect",
  "昨天 zuótiān Yesterday",
  "左边 zuǒbian left",
  "坐 zuò sit",
  "做 zuò do",
  "做生意 zuòshēngyi Do business",
  "座 zuò Seat",
  "座位 zuòwèi seat",
  "作业 zuòyè task",
  "作用 zuòyòng Effect",
  "作者 zuòzhě author",
];
