export default [
  "阿姨 āyí aunt",
  "啊 a ah",
  "唉 āi alas",
  "矮 ǎi short",
  "爱 ài love",
  "爱好 àihào hobby",
  "爱护 àihù Care",
  "爱情 àiqíng Love",
  "爱惜 àixī Cherish",
  "爱心 àixīn love",
  "安静 ānjìng Be quiet",
  "安排 ānpái arrange",
  "安全 ānquán security",
  "安慰 ānwèi comfort",
  "安装 ānzhuāng install",
  "岸 àn bank",
  "暗 àn dark",
  "按时 ànshí on time",
  "按照 ànzhào according to",
  "八 bā Eight",
  "把握 bǎwò grasp",
  "爸爸 bàba Dad",
  "白 bái white",
  "百 bǎi hundred",
  "摆 bǎi pendulum",
  "搬 bān move",
  "班 bān class",
  "班主任 bānzhǔrèn Headmaster",
  "半 bàn half",
  "办法 bànfǎ Way",
  "办公室 bàngōngshì Office",
  "办理 bànlǐ handle",
  "帮忙 bāngmáng Help",
  "帮助 bāngzhù Help",
  "棒 bàng stick",
  "傍晚 bàngwǎn Evening",
  "包 bāo to pack; bag",
  "包裹 bāoguǒ package",
  "包含 bāohán Contain",
  "包括 bāokuò Include",
  "包子 bāozi Steamed stuffed bun",
  "薄 báo thin",
  "饱 bǎo full",
  "宝贝 bǎobèi baby",
  "宝贵 bǎoguì valuable",
  "保持 bǎochí keep",
  "保存 bǎocún Preservation",
  "保护 bǎohù protect",
  "保留 bǎoliú Retain",
  "保险 bǎoxiǎn Insurance",
  "保证 bǎozhèng ensure",
  "抱 bào Hold",
  "抱歉 bàoqiàn feel sorry",
  "报道 bàodào report",
  "报告 bàogào Presentation",
  "报名 bàomíng sign up",
  "报纸 bàozhǐ Newspaper",
  "悲观 bēiguān Pessimism",
  "杯子 bēizi glass",
  "北方 běifāng north",
  "北京 Běijīng Beijing",
  "倍 bèi times",
  "背 bèi Back",
  "背景 bèijǐng background",
  "被 bèi cover",
  "被子 bèizi quilt",
  "本 běn book",
  "本科 běnkē Undergraduate",
  "本来 běnlái originally",
  "本领 běnlǐng ability",
  "本质 běnzhì essence",
  "笨 bèn stupid",
  "鼻子 bízi nose",
  "比 bǐ than",
  "比较 bǐjiào compare",
  "比例 bǐlì Proportion",
  "比如 bǐrú such as",
  "比赛 bǐsài Match",
  "彼此 bǐcǐ each other",
  "笔记本 bǐjìběn Notebook",
  "毕竟 bìjìng after all",
  "毕业 bìyè graduation",
  "避免 bìmiǎn avoid",
  "必然 bìrán Inevitable",
  "必须 bìxū Must",
  "必需 bìxū essential",
  "必要 bìyào necessary",
  "编辑 biānjí edit",
  "鞭炮 biānpào firecracker",
  "便 biàn then, in that case",
  "遍 biàn Times",
  "变化 biànhuà change",
  "辩论 biànlùn Debate",
  "标点 biāodiǎn punctuation",
  "标志 biāozhì sign",
  "标准 biāozhǔn standard",
  "表达 biǎodá Expression",
  "表格 biǎogé form",
  "表面 biǎomiàn surface",
  "表明 biǎomíng Indicate",
  "表情 biǎoqíng Expression",
  "表示 biǎoshì Express",
  "表现 biǎoxiàn performance",
  "表演 biǎoyǎn perform",
  "表扬 biǎoyáng Praise",
  "别 bié other",
  "别人 biéren Others",
  "宾馆 bīnguǎn hotel",
  "冰箱 bīngxiāng Refrigerator",
  "饼干 bǐnggān Biscuits",
  "病毒 bìngdú virus",
  "并且 bìngqiě also",
  "玻璃 bōli Glass",
  "博士 bóshì doctor",
  "博物馆 bówùguǎn Museum",
  "脖子 bózi neck",
  "不必 búbì need not",
  "不但 búdàn not only",
  "不断 búduàn Constantly",
  "不过 búguò However",
  "不见得 bújiàndé Not necessarily",
  "不客气 búkèqi You are welcome",
  "不耐烦 búnàifán Impatient",
  "不要紧 búyàojǐn Never mind",
  "补充 bǔchōng supplement",
  "布 bù cloth, textile",
  "不 bù No",
  "不安 bù'ān Uneasy, unstable",
  "不得不 bùdébù Cannot but; have to",
  "不得了 bùdéliǎo Very",
  "不管 bùguǎn no matter",
  "不好意思 bùhǎoyìsi Sorry",
  "不仅 bùjǐn not only",
  "不免 bùmiǎn unavoidable",
  "不然 bùrán otherwise",
  "不如 bùrú not as good as",
  "不足 bùzú insufficient",
  "部分 bùfen Part",
  "部门 bùmén department",
  "步骤 bùzhòu step",
  "擦 cā wipe",
  "猜 cāi guess",
  "才 cái just",
  "财产 cáichǎn property",
  "材料 cáiliào Material Science",
  "踩 cǎi step on",
  "采访 cǎifǎng interview",
  "采取 cǎiqǔ take, adopt",
  "彩虹 cǎihóng Rainbow",
  "菜 cài food, dish",
  "菜单 càidān menu",
  "参观 cānguān visit",
  "参加 cānjiā participate in",
  "参考 cānkǎo Reference resources",
  "参与 cānyù participate in",
  "餐厅 cāntīng Restaurant",
  "残疾 cánjí disability",
  "惭愧 cánkuì Be ashamed",
  "操场 cāochǎng Playground",
  "操心 cāoxīn Worry",
  "草 cǎo grass",
  "册 cè volume, book",
  "厕所 cèsuǒ Toilet",
  "测验 cèyàn test",
  "层 céng layer",
  "曾经 céngjīng once",
  "插 chā insert",
  "差别 chābié difference",
  "叉子 chāzi Fork",
  "茶 chá tea",
  "差 chà differ from",
  "差不多 chàbuduō Almost",
  "拆 chāi Remove",
  "产品 chǎnpǐn product",
  "产生 chǎnshēng produce",
  "尝 cháng taste",
  "长 cháng long",
  "长城 chángchéng The Great Wall",
  "长江 chángjiāng The Yangtze River",
  "长途 chángtú Long-distance",
  "常识 chángshí common sense",
  "场 chǎng site",
  "唱歌 chànggē Sing",
  "抄 chāo copy",
  "超过 chāoguò Exceed",
  "超市 chāoshì Supermarket",
  "朝 cháo towards",
  "朝代 cháodài Dynasty",
  "炒 chǎo fry",
  "吵 chǎo Noisy",
  "吵架 chǎojià quarrel",
  "车库 chēkù Garage",
  "车厢 chēxiāng carriage",
  "彻底 chèdǐ thorough",
  "沉默 chénmò silent",
  "趁 chèn while",
  "衬衫 chènshān shirt",
  "称 chēng call",
  "称呼 chēnghu to address",
  "称赞 chēngzàn Praise",
  "乘 chéng ride, take",
  "乘坐 chéngzuò ride, take",
  "承担 chéngdān bear",
  "承认 chéngrèn Admit",
  "承受 chéngshòu bear",
  "程度 chéngdù degree",
  "程序 chéngxù program",
  "成分 chéngfèn component",
  "成功 chénggōng Success",
  "成果 chéngguǒ Achievements",
  "成绩 chéngjì achievement",
  "成就 chéngjiù achievement",
  "成立 chénglì establish",
  "成熟 chéngshú mature",
  "成为 chéngwéi Become",
  "成语 chéngyǔ idiom",
  "成长 chéngzhǎng Grow up",
  "诚恳 chéngkěn sincere",
  "诚实 chéngshí honest",
  "城市 chéngshì City",
  "吃 chī eat",
  "吃惊 chījīng Be amazed",
  "吃亏 chīkuī Suffer",
  "迟到 chídào Late",
  "持续 chíxù Continued",
  "池子 chízi Pond",
  "尺子 chǐzi Ruler",
  "翅膀 chìbǎng Wing",
  "冲 chōng punching",
  "充电器 chōngdiànqì Charger",
  "充分 chōngfèn To the full",
  "充满 chōngmǎn full of",
  "重复 chóngfù repeat",
  "重新 chóngxīn again",
  "宠物 chǒngwù Pet",
  "抽屉 chōuti drawer",
  "抽象 chōuxiàng abstract",
  "抽烟 chōuyān smoking",
  "丑 chǒu ugly",
  "臭 chòu smelly",
  "出 chū come out",
  "出版 chūbǎn publish",
  "出差 chūchāi be on a business trip",
  "出发 chūfā Set out",
  "出口 chūkǒu Exit",
  "出生 chūshēng Birth",
  "出席 chūxí Attend",
  "出现 chūxiàn Appear",
  "出租车 chūzūchē Taxi",
  "初级 chūjí primary",
  "除 chú except",
  "除非 chúfēi Unless",
  "除了 chúle except, besides",
  "除夕 chúxī the New Year's Eve",
  "厨房 chúfáng Kitchen",
  "处理 chǔlǐ Handle",
  "穿 chuān Wear",
  "船 chuán ship",
  "传播 chuánbō spread",
  "传递 chuándì pass; transfer",
  "传染 chuánrǎn contagion",
  "传说 chuánshuō Legend",
  "传统 chuántǒng tradition",
  "传真 chuánzhēn Fax",
  "窗户 chuānghu Window",
  "窗帘 chuānglián Window curtains",
  "闯 chuǎng rush; dash",
  "创造 chuàngzào create",
  "吹 chuī blow",
  "春 chūn spring",
  "磁带 cídài Magnetic tape",
  "词典 cídiǎn Dictionary",
  "词语 cíyǔ terms, words",
  "辞职 cízhí Resignation",
  "此外 cǐwài in addition",
  "次 cì second",
  "次要 cìyào secondary",
  "刺激 cìjī stimulate",
  "匆忙 cōngmáng hastily",
  "聪明 cōngming clever",
  "从 cóng from",
  "从此 cóngcǐ from then on",
  "从而 cóng'ér thus",
  "从来 cónglái Always",
  "从前 cóngqián before",
  "从事 cóngshì Be engaged in",
  "粗心 cūxīn careless",
  "醋 cù vinegar",
  "促进 cùjìn Promote",
  "促使 cùshǐ Urge",
  "催 cuī Reminder, urge",
  "存 cún Deposit",
  "存在 cúnzài existence",
  "错 cuò Wrong",
  "错误 cuòwù error",
  "措施 cuòshī Measures",
  "答应 dāying promise",
  "答案 dá'àn Answer",
  "达到 dádào Achieve",
  "打扮 dǎban dress up",
  "打电话 dǎdiànhuà Phone",
  "打工 dǎgōng Work",
  "打交道 dǎjiāodao Dealing with",
  "打篮球 dǎlánqiú Play basketball",
  "打喷嚏 dǎpēntì Sneeze",
  "打扰 dǎrǎo Disturb",
  "打扫 dǎsǎo Clean",
  "打算 dǎsuàn Plan",
  "打听 dǎting Inquire",
  "打印 dǎyìn Print",
  "打招呼 dǎzhāohu Say hello",
  "打折 dǎzhé Discount",
  "打针 dǎzhēn To make an injection",
  "大 dà large",
  "大方 dàfang generous",
  "大概 dàgài Probably",
  "大家 dàjiā everybody",
  "大使馆 dàshǐguǎn Embassy",
  "大象 dàxiàng Elephant",
  "大型 dàxíng large",
  "大约 dàyuē about",
  "呆 dāi stay",
  "带 dài belt; take",
  "戴 dài wear",
  "代表 dàibiǎo representative",
  "代替 dàitì replace",
  "大夫 dàifu Doctor",
  "贷款 dàikuǎn extend credit to; provide a loan",
  "待遇 dàiyù treatment",
  "单纯 dānchún Simple",
  "单调 dāndiào monotonous",
  "单独 dāndú Alone",
  "单位 dānwèi Company",
  "单元 dānyuán unit",
  "担任 dānrèn To serve as",
  "担心 dānxīn Worry",
  "耽误 dānwu delay",
  "胆小鬼 dǎnxiǎoguǐ Coward",
  "淡 dàn light",
  "蛋糕 dàngāo Cake",
  "但是 dànshì however",
  "当 dāng When",
  "当代 dāngdài Contemporary",
  "当地 dāngdì Local",
  "当然 dāngrán Of course",
  "当时 dāngshí at that time",
  "挡 dǎng block",
  "刀 dāo knife",
  "岛 dǎo island",
  "倒霉 dǎoméi fall on evil days",
  "导演 dǎoyǎn director",
  "导游 dǎoyóu Guide",
  "导致 dǎozhì cause",
  "倒 dào inverted",
  "到 dào reach",
  "到处 dàochù everywhere",
  "到达 dàodá Arrive",
  "到底 dàodǐ To the end",
  "道德 dàodé Morality",
  "道理 dàolǐ truth",
  "道歉 dàoqiàn apologize",
  "得意 déyì Proud",
  "得 děi have to",
  "灯 dēng lamp",
  "登机牌 dēngjīpái Boarding pass",
  "登记 dēngjì register",
  "等 (动) děng Wait (move)",
  "等 (助) děng Etc (help)",
  "等待 děngdài wait for",
  "等候 děnghòu Wait",
  "等于 děngyú Be equal to",
  "低 dī low",
  "滴 dī drop",
  "的确 díquè indeed; be certain to",
  "敌人 dírén Enemy",
  "底 dǐ bottom",
  "递 dì Delivery",
  "地道 dìdao tunnel",
  "地方 dìfang local",
  "地理 dìlǐ Geography",
  "地球 dìqiú earth",
  "地区 dìqū region",
  "地毯 dìtǎn Carpet",
  "地铁 dìtiě metro",
  "地图 dìtú Map",
  "地位 dìwèi status",
  "地震 dìzhèn earthquake",
  "地址 dìzhǐ address",
  "弟弟 dìdi Younger brother",
  "第一 dìyī first",
  "点 diǎn spot",
  "点头 diǎntóu Nod",
  "点心 diǎnxin snack",
  "电池 diànchí Battery",
  "电脑 diànnǎo Computer",
  "电视 diànshì television",
  "电台 diàntái radio station",
  "电梯 diàntī Elevator.",
  "电影 diànyǐng Film",
  "电子邮件 diànzǐyóujiàn E-mail",
  "钓 diào Fishing",
  "掉 diào fall",
  "调查 diàochá investigation",
  "顶 dǐng top",
  "丢 diū lose",
  "冬 dōng winter",
  "东 dōng east",
  "东西 dōngxi thing",
  "懂 dǒng understand",
  "冻 dòng freeze",
  "洞 dòng hole",
  "动画片 dònghuàpiàn Cartoon",
  "动物 dòngwù Animal",
  "动作 dòngzuò action",
  "都 dōu all",
  "逗 dòu Funny",
  "豆腐 dòufu Bean curd",
  "读 dú read",
  "独立 dúlì Independent",
  "独特 dútè unique",
  "堵车 dǔchē Traffic jam",
  "度过 dùguò Spend",
  "肚子 dùzi belly",
  "短 duǎn short",
  "短信 duǎnxìn Short message",
  "段 duàn paragraph",
  "断 duàn break",
  "锻炼 duànliàn Physical exercise",
  "堆 duī heap",
  "对 duì Pair, couple",
  "对 duì to",
  "对比 duìbǐ Contrast",
  "对不起 duìbuqǐ I'm sorry.",
  "对待 duìdài treat",
  "对方 duìfāng the other party",
  "对话 duìhuà dialogue",
  "对面 duìmiàn Opposite side",
  "对手 duìshǒu Opponent",
  "对象 duìxiàng object",
  "对于 duìyú about",
  "吨 dūn ton",
  "蹲 dūn squat",
  "顿 dùn Meal",
  "多 duō many",
  "多亏 duōkuī thanks to",
  "多么 duōme what",
  "多少 duōshao how much",
  "多余 duōyú surplus",
  "朵 duǒ classifier of flower",
  "躲藏 duǒcáng Hide oneself",
  "饿 è hungry",
  "恶劣 èliè Adverse",
  "而 ér and",
  "而且 érqiě And",
  "儿童 értóng children",
  "儿子 érzi Son",
  "耳朵 ěrduo Ears",
  "二 èr Two",
  "发 fā give out",
  "发表 fābiǎo Publish",
  "发愁 fāchóu To be worried",
  "发达 fādá To develop",
  "发抖 fādǒu Tremble",
  "发挥 fāhuī Develop",
  "发明 fāmíng Invention",
  "发票 fāpiào invoice",
  "发烧 fāshāo Have a fever",
  "发生 fāshēng Happen",
  "发现 fāxiàn find",
  "发言 fāyán give a speech",
  "发展 fāzhǎn Development",
  "罚款 fákuǎn forfeit; amerce; fine",
  "法律 fǎlǜ Law",
  "法院 fǎyuàn Court",
  "翻 fān Turn",
  "翻译 fānyì translate",
  "烦恼 fánnǎo annoyance",
  "繁荣 fánróng Boom",
  "凡是 fánshì All, everything",
  "反对 fǎnduì Opposition",
  "反而 fǎn'ér Instead",
  "反复 fǎnfù Repeatedly",
  "反应 fǎnyìng reaction",
  "反映 fǎnyìng reflect",
  "反正 fǎnzhèng anyway",
  "饭馆 fànguǎn restaurant",
  "范围 fànwéi Range",
  "方 fāng square",
  "方案 fāng'àn programme",
  "方便 fāngbiàn convenient",
  "方法 fāngfǎ Method",
  "方面 fāngmiàn Aspect",
  "方式 fāngshì mode",
  "方向 fāngxiàng direction",
  "妨碍 fáng'ài Hinder",
  "房东 fángdōng landlord",
  "房间 fángjiān Room",
  "仿佛 fǎngfú as if",
  "访问 fǎngwèn Visit",
  "放 fàng discharge",
  "放弃 fàngqì give up",
  "放暑假 fàngshǔjià summer vacation",
  "放松 fàngsōng Relax",
  "放心 fàngxīn Don't worry",
  "非 fēi wrong; non",
  "非常 fēicháng very",
  "飞机 fēijī aircraft",
  "肥皂 féizào soap",
  "肺 fèi lung",
  "废话 fèihuà Crap",
  "费用 fèiyong Cost",
  "分 fēn minute",
  "分别 fēnbié part",
  "分布 fēnbù distribution",
  "分配 fēnpèi distribution",
  "分析 fēnxī Analysis",
  "分之 fēnzhī %",
  "分钟 fēnzhōng Minute",
  "纷纷 fēnfēn one after another",
  "份 fèn share (measure word)",
  "奋斗 fèndòu Struggle",
  "愤怒 fènnù anger",
  "丰富 fēngfù rich",
  "风格 fēnggé style",
  "风景 fēngjǐng Scenery",
  "风俗 fēngsú Customs",
  "风险 fēngxiǎn risk",
  "疯狂 fēngkuáng Insane",
  "讽刺 fěngcì satire",
  "否定 fǒudìng negative",
  "否认 fǒurèn deny",
  "否则 fǒuzé otherwise",
  "扶 fú hold up",
  "幅 fú classifier of picture",
  "服从 fúcóng Obey",
  "服务员 fúwùyuán Waiter",
  "服装 fúzhuāng costume; dress",
  "符合 fúhé accord with",
  "辅导 fǔdǎo Coach",
  "富 fù rich",
  "附近 fùjìn nearby",
  "付款 fùkuǎn pay",
  "妇女 fùnǚ Woman",
  "父亲 fùqīn father",
  "复习 fùxí Review",
  "复印 fùyìn To copy",
  "复杂 fùzá complex",
  "复制 fùzhì copy",
  "负责 fùzé Be responsible for",
  "改变 gǎibiàn change",
  "改革 gǎigé reform",
  "改进 gǎijìn Improvement",
  "改善 gǎishàn Improve",
  "改正 gǎizhèng correction",
  "盖 gài cover",
  "概括 gàikuò Generalization",
  "概念 gàiniàn concept",
  "干杯 gānbēi Cheers!",
  "干脆 gāncuì simply",
  "干净 gānjìng clean",
  "干燥 gānzào Dry",
  "敢 gǎn dare",
  "感动 gǎndòng Be moved",
  "感激 gǎnjī Appreciate",
  "感觉 gǎnjué feel",
  "感冒 gǎnmào get a cold",
  "感情 gǎnqíng feeling",
  "感受 gǎnshòu feel",
  "感想 gǎnxiǎng Feel",
  "感谢 gǎnxiè Thank",
  "赶紧 gǎnjǐn Quickly",
  "赶快 gǎnkuài hurry up",
  "干 gàn dry",
  "干活儿 gànhuór work on a job",
  "刚才 gāngcái just",
  "刚刚 gānggāng just",
  "钢铁 gāngtiě steel",
  "高 gāo high",
  "高档 gāodàng High-grade",
  "高级 gāojí senior",
  "高速公路 gāosùgōnglù Expressway",
  "高兴 gāoxìng happy",
  "搞 gǎo get",
  "告别 gàobié farewell",
  "告诉 gàosu tell",
  "胳膊 gēbo Arm",
  "哥哥 gēge older brother",
  "鸽子 gēzi Dove",
  "隔壁 gébì next door",
  "革命 gémìng revolution",
  "格外 géwài especially",
  "个 gè individual",
  "个别 gèbié individual",
  "个人 gèrén personal",
  "个性 gèxìng personality",
  "个子 gèzi Height",
  "各 gè various",
  "各自 gèzì Each",
  "给 gěi give",
  "跟 gēn with",
  "根 gēn root",
  "根本 gēnběn at all",
  "根据 gēnjù according to",
  "更 gèng more",
  "更加 gèngjiā More",
  "公布 gōngbù Publish",
  "公共汽车 gōnggòngqìchē Bus",
  "公斤 gōngjīn Kg.",
  "公开 gōngkāi open",
  "公里 gōnglǐ kilometre",
  "公平 gōngpíng fair",
  "公司 gōngsī company",
  "公寓 gōngyù apartment",
  "公元 gōngyuán A.D.",
  "公园 gōngyuán Park",
  "公主 gōngzhǔ princess",
  "工厂 gōngchǎng factory",
  "工程师 gōngchéngshī Engineer",
  "工具 gōngjù tool",
  "工人 gōngrén Worker",
  "工业 gōngyè Industry",
  "工资 gōngzī wages",
  "工作 gōngzuò work",
  "功夫 gōngfu Kungfu",
  "功能 gōngnéng function",
  "共同 gòngtóng common",
  "贡献 gòngxiàn contribution",
  "沟通 gōutōng Communicate",
  "狗 gǒu Dog",
  "够 gòu enough",
  "构成 gòuchéng constitute",
  "购物 gòuwù Shopping",
  "孤单 gūdān alone",
  "姑姑 gūgu aunt",
  "姑娘 gūniang girl",
  "估计 gūjì estimate",
  "古代 gǔdài Ancient",
  "古典 gǔdiǎn classical",
  "古老 gǔlǎo ancient",
  "鼓励 gǔlì encourage",
  "鼓舞 gǔwǔ Inspire",
  "鼓掌 gǔzhǎng applause",
  "股票 gǔpiào shares; stock",
  "骨头 gǔtou Bone",
  "固定 gùdìng fixed",
  "固体 gùtǐ solid",
  "顾客 gùkè customer",
  "故事 gùshi Story",
  "故意 gùyì deliberately",
  "雇佣 gùyōng hire",
  "刮风 guāfēng Windy",
  "挂 guà hang",
  "挂号 guàhào Register",
  "乖 guāi Good behaved",
  "拐弯 guǎiwān Turn",
  "怪不得 guàibude No wonder",
  "官 guān officer",
  "关 guān shut",
  "关闭 guānbì close; shut",
  "关怀 guānhuái Care",
  "关键 guānjiàn key",
  "关系 guānxì relationship",
  "关心 guānxīn Care for",
  "关于 guānyú about",
  "观察 guānchá observation",
  "观点 guāndiǎn viewpoint",
  "观念 guānniàn concept",
  "观众 guānzhòng Audience",
  "管理 guǎnlǐ Administration",
  "管子 guǎnzi pipe",
  "冠军 guànjūn Champion",
  "罐头 guàntou Can, tin",
  "光 guāng light",
  "光滑 guānghuá smooth",
  "光临 guānglín presence",
  "光明 guāngmíng light",
  "光盘 guāngpán CD",
  "光荣 guāngróng glory",
  "广播 guǎngbō Radio broadcast",
  "广场 guǎngchǎng square",
  "广大 guǎngdà Vast",
  "广泛 guǎngfàn widely",
  "广告 guǎnggào Advertisement",
  "逛 guàng Stroll",
  "规定 guīdìng Regulations",
  "规矩 guīju Rules",
  "规律 guīlǜ Law",
  "规模 guīmó scale",
  "规则 guīzé rule",
  "贵 guì Expensive",
  "柜台 guìtái Counter",
  "滚 gǔn rolling",
  "锅 guō pot",
  "国籍 guójí nationality",
  "国际 guójì international",
  "国家 guójiā Country",
  "国庆节 guóqìngjié National Day",
  "果然 guǒrán Sure enough",
  "果实 guǒshí fruit",
  "果汁 guǒzhī fruit juice",
  "过 (动) guò pass",
  "过 (助) guo Over",
  "过程 guòchéng process",
  "过分 guòfèn excessive",
  "过敏 guòmǐn allergy",
  "过期 guòqī Be overdue",
  "过去 guòqù Past times",
  "哈 hā ah",
  "还 hái still",
  "还是 háishì still",
  "孩子 háizi Children",
  "海关 hǎiguān Customs",
  "海鲜 hǎixiān seafood",
  "海洋 hǎiyáng ocean",
  "害怕 hàipà Fear",
  "害羞 hàixiū Shy",
  "寒假 hánjià The winter vacation",
  "喊 hǎn shout",
  "汗 hàn sweat",
  "汉语 hànyǔ Chinese",
  "航班 hángbān flight",
  "行业 hángyè industry",
  "豪华 háohuá luxury",
  "好 hǎo good",
  "好吃 hǎochī Yummy",
  "好处 hǎochu benefit",
  "好像 hǎoxiàng Be like; seem",
  "号 hào Number",
  "号码 hàomǎ number",
  "好奇 hàoqí Be curious",
  "喝 hē drink",
  "河 hé river",
  "和 hé and",
  "和平 hépíng peace",
  "何必 hébì Why",
  "何况 hékuàng Not to mention",
  "合法 héfǎ legitimate",
  "合格 hégé qualified",
  "合理 hélǐ reasonable",
  "合适 héshì appropriate",
  "合同 hétong contract",
  "合影 héyǐng Group photo",
  "合作 hézuò cooperation",
  "核心 héxīn core",
  "盒子 hézi Box",
  "黑 hēi black",
  "黑板 hēibǎn blackboard",
  "很 hěn very",
  "恨 hèn hate",
  "横 héng harsh and unreasonable; perverse",
  "红 hóng red",
  "猴子 hóuzi Monkey",
  "厚 hòu thick",
  "后果 hòuguǒ Consequence",
  "后悔 hòuhuǐ regret",
  "后来 hòulái later",
  "后面 hòumiàn behind",
  "忽然 hūrán suddenly",
  "忽视 hūshì Ignore",
  "呼吸 hūxī breathing",
  "壶 hú pot",
  "蝴蝶 húdié Butterfly",
  "胡说 húshuō Nonsense",
  "胡同 hútòng Hutong",
  "胡须 húxū beard",
  "糊涂 hútu Confused",
  "护士 hùshi Nurse",
  "护照 hùzhào passport",
  "互相 hùxiāng each other",
  "花 (动) huā spend (verb)",
  "花生 huāshēng peanut",
  "花园 huāyuán Garden",
  "滑冰 huábīng skating",
  "划船 huáchuán Rowing",
  "华裔 huáyì Chinese born",
  "画 huà painting",
  "话题 huàtí Topic of conversation",
  "化学 huàxué Chemistry",
  "怀念 huáiniàn miss",
  "怀疑 huáiyí doubt",
  "坏 huài bad",
  "欢迎 huānyíng Welcome",
  "还 huán return",
  "环境 huánjìng Environmental Science",
  "缓解 huǎnjiě relieve",
  "换 huàn change",
  "幻想 huànxiǎng fantasy",
  "慌张 huāngzhāng flurried",
  "黄 huáng yellow",
  "黄瓜 huángguā cucumber",
  "黄金 huángjīn gold",
  "皇帝 huángdì Emperor",
  "皇后 huánghòu Queen",
  "挥 huī Essential",
  "灰 huī ash",
  "灰尘 huīchén dust",
  "灰心 huīxīn Lose heart; be discouraged",
  "恢复 huīfù recovery",
  "回 huí return",
  "回答 huídá Answer",
  "回忆 huíyì Memory",
  "会 huì can;be able to",
  "会议 huìyì Meeting",
  "汇率 huìlǜ exchange rate",
  "婚礼 hūnlǐ wedding",
  "婚姻 hūnyīn Marriage",
  "活动 huódòng activity",
  "活泼 huópō lively",
  "活跃 huóyuè active",
  "火 huǒ fire",
  "火柴 huǒchái Match",
  "火车站 huǒchēzhàn Train station",
  "伙伴 huǒbàn Partner",
  "获得 huòdé Get",
  "或者 huòzhě perhaps",
  "基本 jīběn basic",
  "基础 jīchǔ Basics",
  "机场 jīchǎng Airport",
  "机会 jīhuì Opportunity",
  "机器 jīqì machine",
  "鸡蛋 jīdàn Egg",
  "激动 jīdòng Excited",
  "激烈 jīliè fierce",
  "几乎 jīhū almost",
  "积极 jījí positive",
  "积累 jīlěi accumulation",
  "肌肉 jīròu muscle",
  "极 jí extremely",
  "极其 jíqí extremely",
  "及格 jígé pass",
  "及时 jíshí timely",
  "集合 jíhé aggregate",
  "集体 jítǐ collective",
  "集中 jízhōng focus",
  "急忙 jímáng Hastily",
  "即使 jíshǐ even if",
  "几 jǐ several",
  "寄 jì send",
  "记得 jìde remember",
  "记录 jìlù Record",
  "记忆 jìyì memory",
  "记者 jìzhě Reporter",
  "计划 jìhuà plan",
  "计算 jìsuàn Calculation",
  "季节 jìjié Season",
  "系领带 jìlǐngdài wear a tie",
  "纪录 jìlù Record",
  "纪律 jìlǜ discipline",
  "纪念 jìniàn memorialize",
  "寂寞 jìmò lonely",
  "既然 jìrán although",
  "技术 jìshù technology",
  "继续 jìxù Continue",
  "家 jiā home",
  "家具 jiājù furniture",
  "家庭 jiātíng Family",
  "家务 jiāwù Housework",
  "家乡 jiāxiāng Hometown",
  "加班 jiābān overtime work",
  "加油站 jiāyóuzhàn Gas station",
  "嘉宾 jiābīn Distinguished guest",
  "夹子 jiāzi Clip",
  "甲 jiǎ nail",
  "假 jiǎ false, fake",
  "假如 jiǎrú If",
  "假装 jiǎzhuāng pretend",
  "嫁 jià get married to",
  "价格 jiàgé Price",
  "价值 jiàzhí value",
  "驾驶 jiàshǐ Drive",
  "煎 jiān Fried",
  "肩膀 jiānbǎng shoulder",
  "坚持 jiānchí Insist",
  "坚决 jiānjué firm, determined",
  "坚强 jiānqiáng Firm",
  "艰巨 jiānjù arduous",
  "艰苦 jiānkǔ hard",
  "尖锐 jiānruì Sharp",
  "捡 jiǎn pick up",
  "检查 jiǎnchá inspect; check",
  "简单 jiǎndān simple",
  "简历 jiǎnlì resume",
  "简直 jiǎnzhí simply",
  "剪刀 jiǎndāo scissors",
  "减肥 jiǎnféi Reduce weight",
  "减少 jiǎnshǎo reduce",
  "件 jiàn piece",
  "健康 jiànkāng Healthy",
  "健身房 jiànshēnfáng Gym",
  "建立 jiànlì establish",
  "建设 jiànshè build",
  "建议 jiànyì proposal",
  "建筑 jiànzhù Architecture",
  "见面 jiànmiàn meet",
  "键盘 jiànpán keyboard",
  "将来 jiānglái future",
  "讲 jiǎng speak",
  "讲究 jiǎngjiu Pay attention to; daintily",
  "讲座 jiǎngzuò Lecture",
  "奖金 jiǎngjīn bonus",
  "降低 jiàngdī reduce",
  "降落 jiàngluò land",
  "酱油 jiàngyóu soy sauce",
  "教 jiāo teach",
  "浇 jiāo pour it over",
  "交 jiāo hand over",
  "交换 jiāohuàn exchange",
  "交际 jiāojì communication",
  "交流 jiāoliú Communication",
  "交通 jiāotōng traffic",
  "骄傲 jiāo'ào Proud",
  "郊区 jiāoqū Suburb",
  "胶水 jiāoshuǐ glue",
  "脚 jiǎo foot",
  "角 jiǎo horn",
  "角度 jiǎodù angle",
  "狡猾 jiǎohuá cunning",
  "饺子 jiǎozi Dumplings",
  "叫 jiào call",
  "教材 jiàocái teaching material",
  "教练 jiàoliàn coach",
  "教室 jiàoshì Classroom",
  "教授 jiàoshòu professor",
  "教训 jiàoxùn lesson",
  "教育 jiàoyù education",
  "接 jiē meet, pick",
  "接触 jiēchù Contact",
  "接待 jiēdài Reception",
  "接近 jiējìn near",
  "接受 jiēshòu accept",
  "接着 jiēzhe Next",
  "街道 jiēdào Street",
  "阶段 jiēduàn stage",
  "结实 jiēshi strong",
  "节 jié section, festival",
  "节目 jiémù program",
  "节日 jiérì festival",
  "节省 jiéshěng save",
  "节约 jiéyuē save",
  "结构 jiégòu structure",
  "结果 jiéguǒ Result",
  "结合 jiéhé Combination",
  "结婚 jiéhūn get married",
  "结论 jiélùn conclusion",
  "结束 jiéshù End",
  "结账 jiézhàng Checkout",
  "解放 jiěfàng liberate",
  "解决 jiějué Solve",
  "解释 jiěshì explain",
  "解说员 jiěshuōyuán Narrator",
  "姐姐 jiějie older sister",
  "届 jiè Session",
  "借 jiè borrow",
  "借口 jièkǒu Excuse",
  "介绍 jièshào introduce",
  "戒烟 jièyān Quit smoking",
  "戒指 jièzhi Ring",
  "今天 jīntiān Today",
  "金属 jīnshǔ Metal",
  "紧 jǐn tight",
  "紧急 jǐnjí urgent",
  "紧张 jǐnzhāng Nervous",
  "尽管 jǐnguǎn although",
  "谨慎 jǐnshèn cautious",
  "进 jìn enter",
  "进步 jìnbù progress",
  "进口 jìnkǒu Imported",
  "进行 jìnxíng Conduct",
  "近 jìn near",
  "近代 jìndài Modern",
  "尽力 jìnlì Try the best",
  "尽量 jìnliàng as far as possible",
  "禁止 jìnzhǐ prohibit",
  "精彩 jīngcǎi Marvellous",
  "精力 jīnglì energy",
  "精神 jīngshén spirit",
  "经常 jīngcháng Often",
  "经典 jīngdiǎn classics; scriptures",
  "经过 jīngguò through",
  "经济 jīngjì Economics",
  "经理 jīnglǐ manager",
  "经历 jīnglì experience",
  "经验 jīngyàn experience",
  "经营 jīngyíng Management",
  "京剧 jīngjù Beijing opera",
  "警察 jǐngchá Police",
  "景色 jǐngsè scenery",
  "敬爱 jìng'ài respect and love; esteem",
  "竟然 jìngrán Unexpectedly",
  "竞争 jìngzhēng compete",
  "镜子 jìngzi Mirror",
  "究竟 jiūjìng exactly",
  "九 jiǔ Nine",
  "久 jiǔ long",
  "酒吧 jiǔbā Bar",
  "旧 jiù used, old",
  "救 jiù save",
  "救护车 jiùhùchē Ambulance",
  "舅舅 jiùjiu uncle",
  "居然 jūrán actually",
  "桔子 júzi Orange",
  "举 jǔ lift",
  "举办 jǔbàn hold",
  "举行 jǔxíng hold",
  "具备 jùbèi Have, possess",
  "具体 jùtǐ specific",
  "巨大 jùdà huge",
  "聚会 jùhuì Party",
  "拒绝 jùjué refuse",
  "俱乐部 jùlèbù Club",
  "距离 jùlí distance",
  "据说 jùshuō allegedly; it`s said",
  "句子 jùzi sentence",
  "捐 juān Donate",
  "卷 juǎn volume",
  "觉得 juéde Think",
  "决定 juédìng Decision",
  "决赛 juésài Finals",
  "决心 juéxīn Determination",
  "绝对 juéduì Absolutely",
  "角色 juésè role",
  "军事 jūnshì Military",
  "均匀 jūnyún uniformity",
  "咖啡 kāfēi Coffee",
  "卡车 kǎchē Truck",
  "开 kāi open",
  "开发 kāifā Development",
  "开放 kāifàng To open up",
  "开幕式 kāimùshì The opening ceremony",
  "开始 kāishǐ start",
  "开玩笑 kāiwánxiào Make fun of",
  "开心 kāixīn Happy",
  "砍 kǎn cut",
  "看 kàn see",
  "看不起 kànbuqǐ Despise",
  "看法 kànfǎ view",
  "看见 kànjiàn seeing",
  "看来 kànlái it seems",
  "抗议 kàngyì Protest",
  "考虑 kǎolǜ Consider",
  "考试 kǎoshì Examination",
  "烤鸭 kǎoyā Roasted Duck",
  "棵 kē Tree (measure word)",
  "颗 kē pellet (measure word)",
  "科学 kēxué science",
  "咳嗽 késou cough",
  "渴 kě thirsty",
  "可爱 kě'ài Lovely",
  "可见 kějiàn so; it`s thus clear",
  "可靠 kěkào reliable",
  "可怜 kělián Poor",
  "可能 kěnéng Probably",
  "可怕 kěpà dreadful",
  "可是 kěshì however",
  "可惜 kěxī unfortunately",
  "可以 kěyǐ Sure",
  "课 kè course",
  "课程 kèchéng curriculum",
  "克 kè gram",
  "克服 kèfú Overcome",
  "刻 kè moment",
  "刻苦 kèkǔ Hardworking",
  "客观 kèguān objective",
  "客人 kèrén Guest",
  "客厅 kètīng A living room",
  "肯定 kěndìng sure",
  "空间 kōngjiān space",
  "空气 kōngqì atmosphere， air",
  "空调 kōngtiáo Air conditioner",
  "恐怖 kǒngbù terror， horrible",
  "恐怕 kǒngpà I'm afraid",
  "空闲 kòngxián free",
  "控制 kòngzhì control",
  "口 kǒu mouth",
  "口味 kǒuwèi Flavor",
  "哭 kū cry",
  "苦 kǔ bitter",
  "裤子 kùzi trousers",
  "夸 kuā boast, praise",
  "块 kuài block",
  "快 kuài fast",
  "快乐 kuàilè happy",
  "会计 kuàijì accountant",
  "筷子 kuàizi chopsticks",
  "宽 kuān wide",
  "矿泉水 kuàngquánshuǐ Mineral water",
  "困 kùn sleepy",
  "困难 kùnnan difficulty",
  "扩大 kuòdà Expand",
  "拉 lā pull",
  "垃圾桶 lājītǒng Trash",
  "辣 là hot, spicy",
  "辣椒 làjiāo Pepper, spice",
  "蜡烛 làzhú candle",
  "来 lái come",
  "来不及 láibují There's not enough time",
  "来得及 láidejí In time",
  "来自 láizì Come from",
  "拦 lán Stop",
  "蓝 lán blue",
  "懒 lǎn lazy",
  "烂 làn rotten",
  "狼 láng wolf",
  "浪费 làngfèi Waste",
  "浪漫 làngmàn romantic",
  "劳动 láodòng labour",
  "劳驾 láojià Excuse me",
  "老 lǎo old",
  "老百姓 lǎobǎixìng Ordinary people",
  "老板 lǎobǎn Boss",
  "老虎 lǎohǔ Tiger",
  "老师 lǎoshī Teacher",
  "老实 lǎoshi honest",
  "老鼠 lǎoshǔ Mouse",
  "姥姥 lǎolao Grandma",
  "乐观 lèguān optimistic",
  "雷 léi Thunder",
  "类 lèi class, category",
  "累 lèi tired",
  "冷 lěng cold",
  "冷静 lěngjìng calm down",
  "梨 lí pear",
  "离 lí leave",
  "离婚 líhūn divorce",
  "离开 líkāi leave",
  "厘米 límǐ centimeter",
  "里 lǐ in",
  "礼拜天 lǐbàitiān Sunday",
  "礼貌 lǐmào politeness",
  "礼物 lǐwù gift",
  "理发 lǐfà Haircut",
  "理解 lǐjiě Understand",
  "理论 lǐlùn theory",
  "理想 lǐxiǎng ideal",
  "理由 lǐyóu Reason",
  "粒 lì grain (measure word)",
  "立方 lìfāng cube",
  "立即 lìjí immediately",
  "立刻 lìkè immediately",
  "厉害 lìhai Fierce",
  "力量 lìliàng Power",
  "力气 lìqi Strength",
  "例如 lìrú for example",
  "利润 lìrùn profit",
  "利息 lìxī accrual; interest",
  "利益 lìyì interest",
  "利用 lìyòng utilize",
  "历史 lìshǐ History",
  "俩 liǎ Two",
  "连 lián even",
  "连忙 liánmáng Hurriedly",
  "连续剧 liánxùjù serial TV drama",
  "联合 liánhé union",
  "联系 liánxì contact",
  "脸 liǎn face",
  "恋爱 liàn'ài Love, in love",
  "练习 liànxí Practice",
  "良好 liánghǎo good",
  "凉快 liángkuai Pleasantly cool",
  "粮食 liángshi foodstuff",
  "两 liǎng Two",
  "亮 liàng bright",
  "辆 liàng Car (measure word)",
  "聊天 liáotiān chat",
  "了不起 liǎobuqǐ Amazing",
  "了解 liǎojiě understand",
  "邻居 línjū neighbor",
  "临时 línshí temporary",
  "铃 líng bell",
  "零 líng Zero",
  "零件 língjiàn Spare parts",
  "零钱 língqián Small change",
  "零食 língshí snacks",
  "灵活 línghuó flexible",
  "领导 lǐngdǎo Leader",
  "领域 lǐngyù field",
  "另外 lìngwài in addition",
  "留 liú stay",
  "留学 liúxué Overseas Study",
  "流传 liúchuán spread",
  "流泪 liúlèi Shed tears",
  "流利 liúlì fluent",
  "流行 liúxíng Popular",
  "浏览 liúlǎn browse",
  "六 liù Six",
  "龙 lóng dragon",
  "楼 lóu floor",
  "漏 lòu leak",
  "路 lù road",
  "露 lù dew",
  "陆地 lùdì land",
  "陆续 lùxù One after another",
  "录取 lùqǔ matriculate",
  "录音 lùyīn Sound recording",
  "乱 luàn chaos",
  "轮流 lúnliú take turns",
  "论文 lùnwén paper",
  "逻辑 luóji logic",
  "落后 luòhòu backward, fall behind",
  "旅游 lǚyóu Tourism",
  "绿 lǜ green",
  "律师 lǜshī Lawyer",
  "妈妈 māma Mom",
  "麻烦 máfan trouble",
  "马 mǎ Horse",
  "马虎 mǎhu Careless",
  "马上 mǎshàng Right off",
  "骂 mà scold",
  "买 mǎi buy",
  "卖 mài sell",
  "麦克风 màikèfēng Microphone",
  "馒头 mántou Steamed buns",
  "满 mǎn full",
  "满意 mǎnyì Satisfied",
  "满足 mǎnzú satisfy",
  "慢 màn slow",
  "忙 máng busy",
  "猫 māo cat",
  "毛 máo hair",
  "毛病 máobìng Trouble",
  "毛巾 máojīn Towel",
  "矛盾 máodùn contradiction",
  "冒险 màoxiǎn adventure",
  "贸易 màoyì Trade",
  "帽子 màozi Hat",
  "没 méi no",
  "没关系 méiguānxi No problem",
  "眉毛 méimao eyebrow",
  "煤炭 méitàn coal",
  "每 měi each",
  "美丽 měilì beautiful",
  "美术 měishù Fine Arts",
  "魅力 mèilì charm",
  "妹妹 mèimei Younger sister",
  "门 mén door",
  "梦 mèng dream",
  "迷路 mílù Get lost",
  "谜语 míyǔ Riddle",
  "米 mǐ rice",
  "米饭 mǐfàn Steamed Rice",
  "蜜蜂 mìfēng honeybee",
  "密码 mìmǎ Password",
  "密切 mìqiè close",
  "秘密 mìmì Secret",
  "秘书 mìshū secretary",
  "棉花 miánhua cotton",
  "免费 miǎnfèi Free of charge",
  "面包 miànbāo Bread",
  "面对 miànduì Face",
  "面积 miànjī The measure of area",
  "面临 miànlín face",
  "面条 miàntiáo noodle",
  "苗条 miáotiao slim",
  "描写 miáoxiě describe",
  "秒 miǎo second",
  "民主 mínzhǔ democratic",
  "民族 mínzú Nation",
  "明白 míngbai clear",
  "明确 míngquè To make clear",
  "明天 míngtiān Tomorrow",
  "明显 míngxiǎn obvious",
  "明信片 míngxìnpiàn Postcard",
  "明星 míngxīng Star",
  "名牌 míngpái famous brand",
  "名片 míngpiàn business card",
  "名胜古迹 míngshènggǔjì Places of historic interest and scenic beauty",
  "名字 míngzi Name",
  "命令 mìnglìng call; nominate",
  "命运 mìngyùn fate, destiny",
  "摸 mō feel, touch",
  "模仿 mófǎng imitate",
  "模糊 móhu vague",
  "摩托车 mótuōchē Motorcycle",
  "陌生 mòshēng strange",
  "某 mǒu some",
  "母亲 mǔqīn mother",
  "目标 mùbiāo target",
  "目的 mùdì objective",
  "目录 mùlù Catalog",
  "目前 mùqián at present",
  "木头 mùtou wood",
  "拿 ná take",
  "哪 (哪儿) nǎ(nǎr) Which (where)",
  "哪怕 nǎpà even if",
  "那 (那儿) nà(nàr) That (there)",
  "奶奶 nǎinai grandma",
  "耐心 nàixīn patience",
  "南 nán south",
  "难 nán difficult",
  "难道 nándào could it be said that ...",
  "难怪 nánguài no wonder",
  "难过 nánguò sad",
  "难看 nánkàn ugly",
  "难受 nánshòu Uncomfortable",
  "男人 nánrén Man",
  "脑袋 nǎodai head",
  "内 nèi within",
  "内科 nèikē Internal medicine",
  "内容 nèiróng content",
  "嫩 nèn tender, delicate",
  "能 néng can",
  "能干 nénggàn capable",
  "能力 nénglì ability",
  "能源 néngyuán energy",
  "你 nǐ you",
  "年 nián year",
  "年代 niándài years",
  "年级 niánjí grade",
  "年纪 niánjì Age",
  "年龄 niánlíng Age",
  "年轻 niánqīng Young",
  "念 niàn Read",
  "鸟 niǎo bird",
  "您 nín you",
  "宁可 nìngkě would rather",
  "牛奶 niúnǎi milk",
  "牛仔裤 niúzǎikù Jeans",
  "浓 nóng strong",
  "农村 nóngcūn countryside",
  "农民 nóngmín farmer",
  "农业 nóngyè Agriculture",
  "弄 nòng get",
  "努力 nǔlì Strive",
  "暖和 nuǎnhuo warm",
  "女儿 nǚ'ér daughter",
  "女人 nǚrén woman",
  "女士 nǚshì Madam",
  "偶尔 ǒu'ěr occasionally",
  "偶然 ǒurán accidental",
  "爬山 páshān Mountain climbing",
  "拍 pāi beat",
  "排队 páiduì queue; stand in a line",
  "排列 páiliè array",
  "排球 páiqiú Volleyball",
  "派 pài send",
  "盘子 pánzi plate",
  "判断 pànduàn judge",
  "盼望 pànwàng look forward to",
  "旁边 pángbiān Side",
  "胖 pàng fat",
  "跑步 pǎobù Run",
  "陪 péi accompany",
  "赔偿 péicháng compensate for",
  "培养 péiyǎng culture, foster",
  "佩服 pèifu Admire",
  "配合 pèihé Coordination",
  "盆 pén basin, pot",
  "朋友 péngyou Friend",
  "碰见 pèngjiàn Meet",
  "披 pī drape over one`s shoulders",
  "批 pī batch",
  "批评 pīpíng criticism",
  "批准 pīzhǔn Approval",
  "皮肤 pífū skin",
  "皮鞋 píxié leather shoes",
  "啤酒 píjiǔ Beer",
  "疲劳 píláo fatigue",
  "脾气 píqi temper",
  "匹 pǐ Horse (meaure word)",
  "篇 piān piece",
  "便宜 piányi Cheap",
  "骗 piàn fool",
  "片 piàn slice",
  "片面 piànmiàn one-sided",
  "飘 piāo Gone with the wind",
  "票 piào ticket",
  "漂亮 piàoliang Well done! Beautiful",
  "频道 píndào channel",
  "品种 pǐnzhǒng Varieties",
  "乒乓球 pīngpāngqiú Table Tennis",
  "凭 píng By",
  "平 píng flat",
  "平常 píngcháng Usual",
  "平等 píngděng equality",
  "平方 píngfāng square",
  "平衡 pínghéng balance",
  "平静 píngjìng calm",
  "平均 píngjūn Average",
  "平时 píngshí peacetime",
  "苹果 píngguǒ Apple",
  "评价 píngjià evaluate",
  "瓶子 píngzi Bottle",
  "破 pò broken",
  "破产 pòchǎn bankruptcy",
  "破坏 pòhuài Destruction",
  "迫切 pòqiè urgent",
  "葡萄 pútao Grape",
  "普遍 pǔbiàn universal",
  "普通话 pǔtōnghuà Mandarin",
  "朴素 pǔsù simple",
  "七 qī Seven",
  "期待 qīdài expect",
  "期间 qījiān Period",
  "妻子 qīzi Wife",
  "骑 qí ride",
  "其次 qícì Secondly",
  "其实 qíshí actually",
  "其他 qítā Other",
  "其余 qíyú Rest",
  "其中 qízhōng among",
  "奇怪 qíguài strange",
  "奇迹 qíjì Miracle",
  "起床 qǐchuáng Get up",
  "起飞 qǐfēi take off",
  "起来 qǐlái get up",
  "启发 qǐfā Inspire",
  "企图 qǐtú Attempt",
  "企业 qǐyè enterprise",
  "气氛 qìfēn atmosphere",
  "气候 qìhòu climate",
  "汽油 qìyóu gasoline",
  "牵 qiān Pull",
  "千 qiān thousand",
  "千万 qiānwàn Must",
  "铅笔 qiānbǐ pencil",
  "谦虚 qiānxū Modest",
  "签证 qiānzhèng visa",
  "签字 qiānzì Sign",
  "钱 qián money",
  "前面 qiánmiàn Front",
  "前途 qiántú future",
  "浅 qiǎn shallow",
  "欠 qiàn owe",
  "枪 qiāng gun",
  "墙 qiáng wall",
  "强调 qiángdiào Emphasize",
  "强烈 qiángliè strong",
  "抢 qiǎng rob",
  "敲 qiāo knock",
  "悄悄 qiāoqiāo quietly",
  "桥 qiáo Bridge",
  "瞧 qiáo look",
  "巧克力 qiǎokèlì Chocolates",
  "巧妙 qiǎomiào clever",
  "切 qiē cut",
  "亲爱 qīn'ài Dear",
  "亲戚 qīnqi Relative",
  "亲切 qīnqiè kind",
  "亲自 qīnzì personally",
  "侵略 qīnlüè aggression",
  "勤奋 qínfèn hardworking",
  "勤劳 qínláo industrious",
  "青 qīng young",
  "青春 qīngchūn Youth",
  "青少年 qīngshàonián Teenagers",
  "轻 qīng light",
  "轻视 qīngshì Despise",
  "轻松 qīngsōng Relaxed",
  "清楚 qīngchu clear",
  "清淡 qīngdàn light",
  "晴 qíng Sunny",
  "情景 qíngjǐng scene",
  "情况 qíngkuàng Situation",
  "情绪 qíngxù emotion",
  "请 qǐng please",
  "请假 qǐngjià ask for leave",
  "请客 qǐngkè Treat",
  "请求 qǐngqiú request",
  "庆祝 qìngzhù Celebrate",
  "穷 qióng poor",
  "秋 qiū autumn",
  "球迷 qiúmí fans",
  "区别 qūbié Difference",
  "趋势 qūshì trend",
  "娶 qǔ marry",
  "取 qǔ take",
  "取消 qǔxiāo cancel",
  "去 qù go",
  "去年 qùnián Last year",
  "去世 qùshì pass away",
  "圈 quān circle",
  "全部 quánbù whole",
  "全面 quánmiàn comprehensive",
  "权力 quánlì power",
  "权利 quánlì right, interest",
  "劝 quàn persuade",
  "缺点 quēdiǎn shortcoming",
  "缺乏 quēfá Lack",
  "缺少 quēshǎo Lack",
  "却 què but",
  "确定 quèdìng Determine",
  "确认 quèrèn confirm",
  "确实 quèshí Exactly",
  "群 qún group",
  "裙子 qúnzi skirt",
  "然而 rán'ér however",
  "然后 ránhòu Then",
  "燃烧 ránshāo burning",
  "嚷 rǎng Shout",
  "让 ràng Give Way",
  "绕 rào Around",
  "热 rè heat, hot",
  "热爱 rè'ài Ardently love",
  "热烈 rèliè warm",
  "热闹 rènao lively",
  "热情 rèqíng Enthusiasm",
  "热心 rèxīn enthusiastic",
  "人 rén people",
  "人才 réncái talented people",
  "人口 rénkǒu population",
  "人类 rénlèi Human beings",
  "人民币 rénmínbì RMB",
  "人生 rénshēng Life",
  "人事 rénshì Personnel matters",
  "人物 rénwù character",
  "人员 rényuán personnel",
  "忍不住 rěnbuzhù Unable to bear",
  "任何 rènhé whatever",
  "任务 rènwu task",
  "认识 rènshi know",
  "认为 rènwéi think",
  "认真 rènzhēn earnest",
  "扔 rēng throw",
  "仍然 réngrán still",
  "日 rì day",
  "日常 rìcháng daily",
  "日程 rìchéng schedule",
  "日记 rìjì diary",
  "日历 rìlì calendar",
  "日期 rìqī Date",
  "日用品 rìyòngpǐn Daily Necessities",
  "融化 rónghuà thaw",
  "荣幸 róngxìng To be honored",
  "荣誉 róngyù Honor",
  "容易 róngyì easily",
  "如果 rúguǒ If",
  "如何 rúhé How",
  "如今 rújīn nowadays",
  "入口 rùkǒu Entrance",
  "软 ruǎn soft",
  "软件 ruǎnjiàn Software",
  "弱 ruò weak",
  "洒 sǎ sprinkle",
  "三 sān Three",
  "伞 sǎn umbrella",
  "散步 sànbù Take a walk",
  "嗓子 sǎngzi throat",
  "森林 sēnlín Forest",
  "杀 shā kill",
  "沙发 shāfā Sofa",
  "沙漠 shāmò Desert",
  "沙滩 shātān beach",
  "傻 shǎ silly",
  "晒 shài The sun",
  "删除 shānchú delete",
  "闪电 shǎndiàn lightning",
  "善良 shànliáng kind; virtuous",
  "善于 shànyú be good at",
  "扇子 shànzi Fan",
  "商店 shāngdiàn Shop",
  "商量 shāngliang discuss",
  "商品 shāngpǐn commodity",
  "商业 shāngyè business",
  "伤心 shāngxīn Sad",
  "上 shàng upper",
  "上班 shàngbān go to work",
  "上当 shàngdàng When",
  "上网 shàngwǎng Surf the Internet",
  "上午 shàngwǔ morning",
  "稍微 shāowēi slightly",
  "勺子 sháozi Spoon",
  "少 shǎo less",
  "蛇 shé snake",
  "舌头 shétou Tongue",
  "舍不得 shěbude Hate to part with or use",
  "设备 shèbèi equipment",
  "设计 shèjì Design",
  "设施 shèshī facilities",
  "社会 shèhuì Socioty",
  "射击 shèjī Shooting",
  "摄影 shèyǐng Photography",
  "谁 shéi who",
  "伸 shēn stretch",
  "深 shēn deep",
  "深刻 shēnkè profound",
  "身材 shēncái figure",
  "身份 shēnfèn identity",
  "身体 shēntǐ body",
  "申请 shēnqǐng Apply",
  "神话 shénhuà Myth",
  "神经 shénjīng nerve",
  "神秘 shénmì mysterious",
  "什么 shénme What",
  "甚至 shènzhì Even to the extent that",
  "升 shēng rise",
  "生病 shēngbìng Fall ill",
  "生产 shēngchǎn production",
  "生动 shēngdòng vivid",
  "生活 shēnghuó Life",
  "生命 shēngmìng life",
  "生气 shēngqì get angry",
  "生日 shēngrì Birthday",
  "声调 shēngdiào Tone",
  "声音 shēngyīn voice",
  "绳子 shéngzi Rope",
  "省 shěng province",
  "省略 shěnglüè ellipsis",
  "剩 shèng Left",
  "胜利 shènglì victory",
  "诗 shī poetry",
  "失败 shībài fail",
  "失眠 shīmián insomnia",
  "失去 shīqù Lose",
  "失望 shīwàng Disappointment",
  "失业 shīyè Unemployment",
  "师傅 shīfu Master worker",
  "湿润 shīrùn Moist",
  "狮子 shīzi Lion",
  "十 shí Ten",
  "十分 shífēn very",
  "时代 shídài times, epoch",
  "时候 shíhou time",
  "时间 shíjiān time",
  "时刻 shíkè time",
  "时髦 shímáo Fashionable",
  "时期 shíqī period",
  "时尚 shíshàng fashion",
  "实话 shíhuà The truth",
  "实际 shíjì Actual",
  "实践 shíjiàn practice",
  "实习 shíxí Internship",
  "实现 shíxiàn Realization",
  "实行 shíxíng Implement",
  "实验 shíyàn Experiment",
  "实用 shíyòng Practical",
  "实在 shízài really",
  "食品 shípǐn food",
  "食物 shíwù food",
  "石头 shítou stone",
  "使 shǐ send",
  "使劲儿 shǐjìnr exert all one's strength",
  "使用 shǐyòng Use",
  "始终 shǐzhōng Throughout",
  "是 shì yes",
  "是否 shìfǒu Whether",
  "试 shì try",
  "试卷 shìjuàn test paper",
  "士兵 shìbīng soldiers",
  "市场 shìchǎng market",
  "似的 shìde Likely",
  "适合 shìhé Fit",
  "适应 shìyìng Adapt",
  "世纪 shìjì century",
  "世界 shìjiè world",
  "事情 shìqing Thing",
  "事实 shìshí Fact",
  "事物 shìwù Thing",
  "事先 shìxiān Prior",
  "收 shōu collect",
  "收获 shōuhuò Harvest",
  "收据 shōujù receipt",
  "收入 shōurù income",
  "收拾 shōushi Tidy",
  "手表 shǒubiǎo Wrist Watch",
  "手工 shǒugōng manual",
  "手机 shǒujī Mobile phone",
  "手术 shǒushù Operation",
  "手套 shǒutào glove",
  "手续 shǒuxù procedures",
  "手指 shǒuzhǐ finger",
  "首都 shǒudū capital",
  "首先 shǒuxiān First",
  "瘦 shòu thin",
  "受不了 shòubuliǎo Cannot bear sth",
  "受到 shòudào Suffer",
  "受伤 shòushāng Injured",
  "售货员 shòuhuòyuán Salesperson",
  "寿命 shòumìng Life",
  "书 shū book",
  "书架 shūjià bookshelf",
  "输 shū transport",
  "蔬菜 shūcài Vegetables",
  "舒服 shūfu comfortable",
  "舒适 shūshì Comfortable",
  "叔叔 shūshu uncle",
  "梳子 shūzi comb",
  "熟练 shúliàn skilled",
  "熟悉 shúxī be familiar with",
  "鼠标 shǔbiāo mouse",
  "属于 shǔyú belong to",
  "树 shù tree",
  "数据 shùjù data",
  "数量 shùliàng Number",
  "数码 shùmǎ Digital",
  "数学 shùxué Mathematics",
  "数字 shùzì number",
  "刷牙 shuāyá Brush one's teeth",
  "摔 shuāi fall",
  "甩 shuǎi Rejection",
  "帅 shuài Handsome",
  "双 shuāng double",
  "双方 shuāngfāng both sides",
  "水 shuǐ water",
  "水果 shuǐguǒ Fruits",
  "水平 shuǐpíng level",
  "税 shuì tax",
  "睡觉 shuìjiào sleep",
  "顺便 shùnbiàn by the way",
  "顺利 shùnlì smoothly",
  "顺序 shùnxù order",
  "说不定 shuōbudìng maybe",
  "说服 shuōfú Persuade",
  "说话 shuōhuà speak",
  "说明 shuōmíng Explain",
  "硕士 shuòshì master",
  "撕 sī tear",
  "丝绸 sīchóu silk",
  "丝毫 sīháo A bit",
  "司机 sījī Driver",
  "思考 sīkǎo Reflection",
  "思想 sīxiǎng thought",
  "私人 sīrén private",
  "死 sǐ die",
  "四 sì Four",
  "似乎 sìhū It seems that",
  "寺庙 sìmiào Temple",
  "送 sòng give",
  "速度 sùdù speed",
  "塑料袋 sùliàodài Plastic bag",
  "宿舍 sùshè dormitory",
  "酸 suān acid",
  "算 suàn count",
  "虽然 suīrán although",
  "随便 suíbiàn casual",
  "随时 suíshí at any time",
  "随着 suízhe along with",
  "岁 suì year",
  "碎 suì broken",
  "孙子 sūnzi Grandson",
  "损失 sǔnshī loss",
  "缩短 suōduǎn Shorten",
  "缩小 suōxiǎo narrow",
  "锁 suǒ lock",
  "所 suǒ place",
  "所谓 suǒwèi So-called",
  "所以 suǒyǐ therefore",
  "所有 suǒyǒu All",
  "他 tā he",
  "她 tā she",
  "它 tā it",
  "塔 tǎ tower",
  "抬 tái Lift",
  "台 tái platform",
  "台阶 táijiē Steps",
  "太 tài too",
  "太极拳 tàijíquán Taiji boxing",
  "太太 tàitai Ma'am",
  "太阳 tàiyáng sun",
  "态度 tàidu attitude",
  "谈 tán talk",
  "谈判 tánpàn negotiation",
  "弹钢琴 tángāngqín Play the piano",
  "坦率 tǎnshuài frank",
  "汤 tāng soup",
  "糖 táng sugar",
  "躺 tǎng lie",
  "烫 tàng Hot",
  "趟 tàng Trip",
  "桃 táo peach",
  "逃 táo flee",
  "逃避 táobì escape",
  "讨论 tǎolùn discuss",
  "讨厌 tǎoyàn Hate",
  "套 tào set",
  "特别 tèbié Especially",
  "特点 tèdiǎn Characteristic",
  "特殊 tèshū special",
  "特意 tèyì specially",
  "特征 tèzhēng Features",
  "疼 téng hurt",
  "疼爱 téng'ài Love dearly",
  "踢足球 tīzúqiú Play football",
  "提 tí carry",
  "提倡 tíchàng promote",
  "提纲 tígāng outline",
  "提高 tígāo increase",
  "提供 tígōng provide",
  "提前 tíqián in advance",
  "提问 tíwèn Put questions to",
  "提醒 tíxǐng remind",
  "题 tí topic",
  "题目 tímù subject",
  "体会 tǐhuì Experience",
  "体积 tǐjī volume",
  "体贴 tǐtiē Considerate",
  "体现 tǐxiàn Reflect",
  "体验 tǐyàn experience",
  "体育 tǐyù Sports",
  "天空 tiānkōng sky",
  "天气 tiānqì weather",
  "天真 tiānzhēn naive",
  "甜 tián sweet",
  "填空 tiánkòng Fill in the blanks",
  "田野 tiányě Field",
  "条 tiáo strip",
  "条件 tiáojiàn condition",
  "调皮 tiáopí naughty",
  "调整 tiáozhěng adjustment",
  "挑战 tiǎozhàn challenge",
  "跳舞 tiàowǔ dance",
  "听 tīng hear",
  "停止 tíngzhǐ Stop it",
  "挺 tǐng quite",
  "通常 tōngcháng usually",
  "通过 tōngguò Through",
  "通讯 tōngxùn communication",
  "通知 tōngzhī notice",
  "铜 tóng copper",
  "同情 tóngqíng Sympathy",
  "同时 tóngshí meanwhile",
  "同事 tóngshì Colleague",
  "同学 tóngxué Classmate",
  "同意 tóngyì Agree",
  "统一 tǒngyī Unified",
  "统治 tǒngzhì rule",
  "痛苦 tòngkǔ Pain",
  "痛快 tòngkuài Happy, to one`s great satisfaction",
  "头发 tóufa Hair",
  "投资 tóuzī Investment",
  "透明 tòumíng transparent",
  "突出 tūchū prominent",
  "突然 tūrán suddenly",
  "图书馆 túshūguǎn Library",
  "土地 tǔdì land",
  "土豆 tǔdòu Potato",
  "吐 tù spit",
  "兔子 tùzi Rabbit",
  "团 tuán group",
  "推 tuī push",
  "推迟 tuīchí delay",
  "推辞 tuīcí Refuse",
  "推广 tuīguǎng Extension",
  "推荐 tuījiàn Recommend",
  "腿 tuǐ leg",
  "退 tuì retreat",
  "退步 tuìbù Backward",
  "退休 tuìxiū retire",
  "脱 tuō take off",
  "袜子 wàzi Socks",
  "歪 wāi Crooked",
  "外 wài abroad, outside",
  "外交 wàijiāo International Relations",
  "弯 wān curved",
  "完 wán finish",
  "完成 wánchéng complete",
  "完美 wánměi perfect",
  "完全 wánquán completely",
  "完善 wánshàn perfect",
  "完整 wánzhěng complete",
  "玩 wán play",
  "玩具 wánjù Toys",
  "碗 wǎn bowl",
  "晚上 wǎnshang Night",
  "万 wàn ten thousand",
  "万一 wànyī In case",
  "王子 wángzǐ prince",
  "往 wǎng to",
  "往返 wǎngfǎn Return",
  "往往 wǎngwǎng Often",
  "网球 wǎngqiú Tennis",
  "网站 wǎngzhàn website",
  "忘记 wàngjì forget",
  "危害 wēihài Harm",
  "危险 wēixiǎn danger",
  "微笑 wēixiào Smile",
  "威胁 wēixié threaten",
  "违反 wéifǎn Violation",
  "维护 wéihù Maintain",
  "围巾 wéijīn scarf",
  "围绕 wéirào around",
  "唯一 wéiyī Only",
  "尾巴 wěiba tail",
  "伟大 wěidà great",
  "委屈 wěiqu suffer from injustice",
  "委托 wěituō Entrust",
  "喂 wèi feed",
  "胃 wèi stomach",
  "为 wèi by",
  "为了 wèile in order to",
  "为什么 wèishénme Why",
  "位 wèi measure word of person",
  "位置 wèizhì position",
  "未必 wèibì not necessarily",
  "未来 wèilái Future",
  "味道 wèidào taste",
  "卫生间 wèishēngjiān toilet",
  "温度 wēndù temperature",
  "温暖 wēnnuǎn warm",
  "温柔 wēnróu Tender",
  "闻 wén smell",
  "文化 wénhuà Culture",
  "文件 wénjiàn file",
  "文具 wénjù Stationery",
  "文明 wénmíng civilization",
  "文学 wénxué literature",
  "文章 wénzhāng Article",
  "吻 wěn kiss",
  "稳定 wěndìng Stable",
  "问 wèn ask",
  "问候 wènhòu To greet",
  "问题 wèntí problem",
  "我 wǒ I",
  "我们 wǒmen We",
  "卧室 wòshì Bedroom",
  "握手 wòshǒu Handshake",
  "污染 wūrǎn contaminated",
  "屋子 wūzi House",
  "无 wú nothing",
  "无聊 wúliáo Boring",
  "无论 wúlùn whether, no matter what",
  "无奈 wúnài have no choice",
  "无数 wúshù Countless",
  "五 wǔ Five",
  "武器 wǔqì arms",
  "武术 wǔshù A martial art",
  "雾 wù Fog",
  "误会 wùhuì Misunderstanding",
  "物理 wùlǐ Physics",
  "物质 wùzhì material",
  "西 xī west",
  "西瓜 xīguā watermelon",
  "西红柿 xīhóngshì Tomato",
  "吸收 xīshōu absorb",
  "吸引 xīyǐn Attract",
  "希望 xīwàng hope",
  "习惯 xíguàn Habit",
  "洗 xǐ wash",
  "洗手间 xǐshǒujiān Restroom",
  "洗衣机 xǐyījī Washing machine",
  "洗澡 xǐzǎo Take a shower",
  "喜欢 xǐhuan like",
  "系 xì department",
  "系统 xìtǒng system",
  "细节 xìjié details",
  "戏剧 xìjù drama",
  "瞎 xiā blind",
  "吓 xià scare",
  "夏 xià summer",
  "下 xià lower",
  "下午 xiàwǔ Afternoon",
  "下雨 xiàyǔ rain",
  "下载 xiàzài download",
  "先 xiān before",
  "先生 xiānsheng Sir",
  "鲜艳 xiānyàn Colorful",
  "咸 xián salty",
  "显得 xiǎnde Appear, seem",
  "显然 xiǎnrán Obviously",
  "显示 xiǎnshì display",
  "县 xiàn county",
  "现代 xiàndài modern",
  "现金 xiànjīn cash",
  "现实 xiànshí reality",
  "现象 xiànxiàng phenomenon",
  "现在 xiànzài Now",
  "羡慕 xiànmù Envy",
  "限制 xiànzhì limit",
  "香 xiāng fragrant",
  "香蕉 xiāngjiāo Banana",
  "相处 xiāngchǔ Get along with",
  "相当 xiāngdāng Quite",
  "相对 xiāngduì Relative",
  "相反 xiāngfǎn Contrary",
  "相关 xiāngguān correlate",
  "相似 xiāngsì Be similar",
  "相同 xiāngtóng identical",
  "相信 xiāngxìn believe",
  "详细 xiángxì detailed",
  "响 xiǎng ring",
  "想 xiǎng think",
  "想念 xiǎngniàn miss",
  "想象 xiǎngxiàng imagine",
  "享受 xiǎngshòu enjoy",
  "向 xiàng towards",
  "像 xiàng image",
  "项 xiàng term",
  "项链 xiàngliàn Necklace",
  "项目 xiàngmù project",
  "橡皮 xiàngpí rubber",
  "象棋 xiàngqí Xiangqi",
  "象征 xiàngzhēng Symbolize",
  "消费 xiāofèi consumption",
  "消化 xiāohuà Digestion",
  "消灭 xiāomiè eliminate",
  "消失 xiāoshī disappear",
  "销售 xiāoshòu Sale",
  "消息 xiāoxi news, message",
  "小 xiǎo Small",
  "小吃 xiǎochī snack",
  "小伙子 xiǎohuǒzi Young fellow",
  "小姐 xiǎojiě Miss",
  "小麦 xiǎomài Wheat",
  "小气 xiǎoqi Mean",
  "小时 xiǎoshí hour",
  "小说 xiǎoshuō Novel",
  "小偷 xiǎotōu Thief",
  "小心 xiǎoxīn Look out",
  "笑 xiào laugh",
  "笑话 xiàohua joke",
  "效果 xiàoguǒ Effect",
  "效率 xiàolǜ efficiency",
  "孝顺 xiàoshun Filial piety",
  "校长 xiàozhǎng Principal",
  "些 xiē some",
  "歇 xiē Rest",
  "斜 xié oblique",
  "鞋 xié shoes",
  "协调 xiétiáo coordinate",
  "写 xiě write",
  "谢谢 xièxie Thank you",
  "新 xīn new",
  "新闻 xīnwén news",
  "新鲜 xīnxiān fresh",
  "辛苦 xīnkǔ hard",
  "心理 xīnlǐ Psychology",
  "心情 xīnqíng mood",
  "心脏 xīnzàng heart",
  "欣赏 xīnshǎng Appreciate",
  "信 xìn letter",
  "信封 xìnfēng envelope",
  "信号 xìnhào signal",
  "信任 xìnrèn trust",
  "信息 xìnxī information",
  "信心 xìnxīn confidence",
  "信用卡 xìnyòngkǎ Credit card",
  "兴奋 xīngfèn Excitement",
  "星期 xīngqī week",
  "行 xíng That's ok",
  "行动 xíngdòng Get some action",
  "行李箱 xínglixiāng Trunk",
  "行人 xíngrén pedestrian",
  "行为 xíngwéi behavior",
  "形成 xíngchéng formation",
  "形容 xíngróng describe",
  "形式 xíngshì form",
  "形势 xíngshì situation",
  "形象 xíngxiàng image",
  "形状 xíngzhuàng shape",
  "醒 xǐng wake up",
  "姓 xìng surname",
  "性别 xìngbié Gender",
  "性格 xìnggé character",
  "性质 xìngzhì Nature",
  "幸福 xìngfú happiness",
  "幸亏 xìngkuī Thanks",
  "幸运 xìngyùn lucky",
  "兴趣 xìngqù Interest",
  "胸 xiōng chest",
  "兄弟 xiōngdì Brother",
  "熊猫 xióngmāo Panda",
  "雄伟 xióngwěi Magnificent",
  "修 xiū repair",
  "修改 xiūgǎi modify",
  "休息 xiūxi Rest",
  "休闲 xiūxián Leisure time",
  "虚心 xūxīn With an open mind, modest",
  "需要 xūyào Need",
  "许多 xǔduō many",
  "叙述 xùshù Narration",
  "宣布 xuānbù Announce",
  "宣传 xuānchuán Propaganda",
  "选举 xuǎnjǔ Election",
  "选择 xuǎnzé Choice",
  "学期 xuéqī Semester",
  "学生 xuésheng Student",
  "学术 xuéshù learning",
  "学问 xuéwen knowledge",
  "学习 xuéxí Study",
  "学校 xuéxiào School",
  "雪 xuě Snow",
  "血 xuè blood",
  "询问 xúnwèn inquiry",
  "寻找 xúnzhǎo Seek, look for",
  "训练 xùnliàn training",
  "迅速 xùnsù rapid",
  "压力 yālì pressure",
  "牙膏 yágāo toothpaste",
  "亚洲 yàzhōu Asia",
  "呀 ya ah",
  "盐 yán salt",
  "延长 yáncháng extend",
  "严格 yángé strict",
  "严肃 yánsù serious",
  "严重 yánzhòng serious",
  "研究生 yánjiūshēng Graduate student",
  "颜色 yánsè colour",
  "演出 yǎnchū show",
  "演员 yǎnyuán performer, actor",
  "眼镜 yǎnjìng glasses",
  "眼睛 yǎnjing Eye",
  "宴会 yànhuì banquet",
  "阳光 yángguāng Sunshine",
  "羊肉 yángròu mutton",
  "阳台 yángtái balcony",
  "痒 yǎng itch",
  "养成 yǎngchéng Cultivate",
  "样式 yàngshì style",
  "样子 yàngzi A look",
  "腰 yāo waist",
  "邀请 yāoqǐng Invitation",
  "要求 yāoqiú Requirement",
  "摇 yáo shake",
  "咬 yǎo bite",
  "药 yào drug",
  "要 yào want",
  "要不 yàobù Or",
  "要是 yàoshi If",
  "钥匙 yàoshi Key",
  "爷爷 yéye grandpa",
  "也 yě also",
  "也许 yěxǔ perhaps",
  "页 yè page",
  "夜 yè night",
  "液体 yètǐ liquid",
  "业务 yèwù business",
  "业余 yèyú amateur",
  "叶子 yèzi Leaf",
  "一 yī One",
  "衣服 yīfu clothes",
  "依然 yīrán still",
  "医生 yīshēng Doctor",
  "医院 yīyuàn Hospital",
  "一辈子 yíbèizi A lifetime",
  "一旦 yídàn once; in case",
  "一定 yídìng Certain",
  "一共 yígòng Altogether",
  "一会儿 yíhuìr A little while",
  "一路平安 yílùpíng'ān Bon Voyage",
  "一切 yíqiè everything",
  "一样 yíyàng equally, same",
  "一致 yízhì Agreement",
  "移动 yídòng move",
  "移民 yímín immigrant",
  "遗憾 yíhàn pity",
  "疑问 yíwèn Doubt",
  "以 yǐ with",
  "以后 yǐhòu In the future",
  "以及 yǐjí as well as",
  "以来 yǐlái Since",
  "以前 yǐqián before",
  "以为 yǐwéi Think",
  "已经 yǐjīng Already",
  "椅子 yǐzi Chair",
  "亿 yì Billion",
  "一般 yìbān commonly",
  "一边 yìbiān One side",
  "一起 yìqǐ together",
  "一直 yìzhí always",
  "意见 yìjiàn Opinion",
  "意思 yìsi Meaning",
  "意外 yìwài Accident",
  "意义 yìyì Significance",
  "议论 yìlùn Discussion",
  "艺术 yìshù Art",
  "义务 yìwù obligation",
  "阴 yīn Yin",
  "因此 yīncǐ therefore",
  "因而 yīn'ér thus",
  "因素 yīnsù Factor",
  "因为 yīnwèi because",
  "音乐 yīnyuè Music",
  "银 yín silver",
  "银行 yínháng Bank",
  "饮料 yǐnliào Drinks",
  "引起 yǐnqǐ cause",
  "印象 yìnxiàng impression",
  "应该 yīnggāi Should",
  "英俊 yīngjùn Handsome and spirited",
  "英雄 yīngxióng Hero",
  "赢 yíng win",
  "迎接 yíngjiē meet, welcome",
  "营养 yíngyǎng Nutrition",
  "营业 yíngyè Do business",
  "影响 yǐngxiǎng Influence",
  "影子 yǐngzi shadow",
  "硬 yìng hard",
  "硬币 yìngbì Coin",
  "硬件 yìngjiàn Hardware",
  "应付 yìngfu cope with",
  "应聘 yìngpìn Apply for",
  "应用 yìngyòng application",
  "拥抱 yōngbào embrace",
  "拥挤 yōngjǐ Crowded",
  "勇敢 yǒnggǎn Brave",
  "勇气 yǒngqì courage",
  "永远 yǒngyuǎn forever",
  "用 yòng use",
  "用途 yòngtú purpose",
  "优点 yōudiǎn Advantage",
  "优惠 yōuhuì preferential; favorable",
  "优美 yōuměi Graceful",
  "优势 yōushì advantage",
  "优秀 yōuxiù excellent",
  "悠久 yōujiǔ long",
  "幽默 yōumò Humor",
  "由 yóu from",
  "由于 yóuyú Because",
  "邮局 yóujú Post Office",
  "游览 yóulǎn visit",
  "游戏 yóuxì Game",
  "游泳 yóuyǒng Swimming",
  "尤其 yóuqí especially",
  "犹豫 yóuyù hesitate",
  "油炸 yóuzhá Fried",
  "有 yǒu have",
  "有利 yǒulì favourable, beneficial",
  "有名 yǒumíng Famous",
  "有趣 yǒuqù interesting",
  "友好 yǒuhǎo friendly",
  "友谊 yǒuyì friendship",
  "又 yòu also",
  "右边 yòubian Right",
  "幼儿园 yòu'éryuán Kindergarten",
  "鱼 yú fish",
  "愉快 yúkuài Cheerful",
  "娱乐 yúlè entertainment",
  "于是 yúshì Therefore",
  "与 yǔ and",
  "与其 yǔqí Rather than",
  "语法 yǔfǎ grammar",
  "语气 yǔqì tone",
  "语言 yǔyán language",
  "羽毛球 yǔmáoqiú Badminton",
  "宇宙 yǔzhòu universe",
  "预报 yùbào prediction",
  "预订 yùdìng book; subscribe for",
  "预防 yùfáng Prevention",
  "预习 yùxí Preview",
  "遇到 yùdào encounter",
  "玉米 yùmǐ Corn",
  "圆 yuán circular",
  "元 yuán element, Yuan",
  "元旦 uándàn New year's Day",
  "缘故 yuángù Reason",
  "原来 yuánlái Original",
  "原谅 yuánliàng Forgive",
  "原料 yuánliào raw material",
  "原因 yuányīn Reason",
  "原则 yuánzé Principle",
  "远 yuǎn far",
  "愿望 yuànwàng desire, wish",
  "愿意 yuànyì Be willing",
  "约会 yuēhuì Date",
  "越 yuè The more",
  "月 yuè month",
  "月亮 yuèliang Moon",
  "阅读 yuèdú Read",
  "晕 yūn faint",
  "云 yún cloud",
  "允许 yǔnxǔ allow",
  "运动 yùndòng motion",
  "运气 yùnqi luck",
  "运输 yùnshū transport",
  "运用 yùnyòng Application",
  "杂志 zázhì Magazine",
  "灾害 zāihài disaster",
  "在 zài stay",
  "再 zài again",
  "再见 zàijiàn Bye",
  "再三 zàisān repeatedly",
  "咱们 zánmen We",
  "赞成 zànchéng Agreement",
  "赞美 zànměi Praise",
  "暂时 zànshí temporary",
  "脏 zāng dirty",
  "糟糕 zāogāo Too bad",
  "早上 zǎoshang Morning",
  "造成 zàochéng cause",
  "则 zé be",
  "责备 zébèi Reproach",
  "责任 zérèn responsibility",
  "怎么 zěnme How",
  "怎么样 zěnmeyàng How about",
  "增加 zēngjiā increase",
  "增长 zēngzhǎng increase",
  "摘 zhāi pick",
  "窄 zhǎi narrow",
  "粘贴 zhāntiē paste",
  "展开 zhǎnkāi Open",
  "展览 zhǎnlǎn exhibition",
  "站 zhàn station",
  "占线 zhànxiàn (line) Busy",
  "战争 zhànzhēng War",
  "张 zhāng Zhang",
  "长 zhǎng grow",
  "涨 zhǎng rise",
  "掌握 zhǎngwò master",
  "丈夫 zhàngfu husband",
  "账户 zhànghù account",
  "招待 zhāodài Entertain",
  "招聘 zhāopìn recruit",
  "着急 zháojí Worry",
  "着凉 zháoliáng get cold",
  "找 zhǎo look for",
  "召开 zhàokāi convene",
  "照常 zhàocháng as usual",
  "照顾 zhàogù look after",
  "照片 zhàopiàn Photo",
  "照相机 zhàoxiàngjī Camera",
  "哲学 zhéxué Philosophy",
  "这 (这儿) zhè(zhèr) Here (here)",
  "着 zhe in process of",
  "真 zhēn really",
  "真理 zhēnlǐ Truth",
  "真实 zhēnshí real",
  "真正 zhēnzhèng real",
  "针对 zhēnduì aim at",
  "珍惜 zhēnxī cherish",
  "诊断 zhěnduàn Diagnosis",
  "枕头 zhěntou Pillow",
  "阵 zhèn front",
  "振动 zhèndòng Vibration",
  "睁 zhēng open (eyes)",
  "争论 zhēnglùn debate",
  "争取 zhēngqǔ strive for",
  "征求 zhēngqiú ask for",
  "整个 zhěnggè Whole",
  "整理 zhěnglǐ Arrangement",
  "整齐 zhěngqí neat",
  "整体 zhěngtǐ Whole",
  "正 zhèng just",
  "正常 zhèngcháng normal",
  "正好 zhènghǎo Just right",
  "正确 zhèngquè Correct",
  "正式 zhèngshì formal",
  "正在 zhèngzài in process of",
  "政策 zhèngcè policy",
  "政府 zhèngfǔ government",
  "政治 zhèngzhì Politics",
  "证件 zhèngjiàn Certificates",
  "证据 zhèngjù evidence",
  "证明 zhèngmíng Prove",
  "挣钱 zhèngqián Earn money",
  "只 zhī measure word of animal",
  "之 zhī of",
  "支 zhī branch (measure word)",
  "支持 zhīchí Support",
  "支票 zhīpiào Check",
  "知道 zhīdào know",
  "知识 zhīshi knowledge",
  "直 zhí straight",
  "直接 zhíjiē direct",
  "值得 zhíde Worth",
  "植物 zhíwù Botany",
  "执行 zhíxíng implement",
  "执照 zhízhào License",
  "职业 zhíyè Occupation",
  "指 zhǐ finger",
  "指导 zhǐdǎo guidance",
  "指挥 zhǐhuī command",
  "只 zhǐ only",
  "只好 zhǐhǎo have to",
  "只要 zhǐyào as long as",
  "制定 zhìdìng Formulate",
  "制度 zhìdù system",
  "制造 zhìzào Manufacture",
  "制作 zhìzuò Make",
  "智慧 zhìhuì wisdom",
  "至今 zhìjīn so far",
  "至少 zhìshǎo at least",
  "至于 zhìyú As for",
  "质量 zhìliàng quality",
  "治疗 zhìliáo Treatment",
  "秩序 zhìxù order",
  "志愿者 zhìyuànzhě Volunteer",
  "钟 zhōng clock",
  "中国 zhōngguó China",
  "中间 zhōngjiān Middle",
  "中介 zhōngjiè intermediary",
  "中文 hōngwén Chinese",
  "中午 zhōngwǔ Noon",
  "中心 zhōngxīn core",
  "中旬 zhōngxún Mid",
  "终于 zhōngyú finally",
  "种 zhǒng species",
  "重 zhòng heavy",
  "重点 zhòngdiǎn A key",
  "重量 zhòngliàng weight",
  "重视 zhòngshì take sth. seriously, importance",
  "重要 zhòngyào important",
  "周到 zhōudào thoughtful",
  "周末 zhōumò Weekend",
  "周围 zhōuwéi around",
  "猪 zhū pig",
  "逐步 zhúbù gradually",
  "逐渐 zhújiàn gradually",
  "竹子 zhúzi Bamboo",
  "煮 zhǔ cook",
  "主持 zhǔchí Host",
  "主动 zhǔdòng active",
  "主观 zhǔguān subjective",
  "主人 zhǔrén master",
  "主席 zhǔxí Chairman",
  "主要 zhǔyào main",
  "主意 zhǔyi idea",
  "主张 zhǔzhāng opinion",
  "嘱咐 zhǔfù Charge",
  "住 zhù live",
  "祝 zhù wish",
  "祝福 zhùfú blessing",
  "祝贺 zhùhè Congratulate",
  "注册 zhùcè register",
  "注意 zhùyì Be careful",
  "著名 zhùmíng famous",
  "抓紧 zhuājǐn Pay close attention to, grasp",
  "专家 zhuānjiā expert",
  "专门 zhuānmén specialized",
  "专心 zhuānxīn Attentively",
  "专业 zhuānyè major",
  "转变 zhuǎnbiàn change",
  "转告 zhuǎngào Tell, transmit",
  "赚 zhuàn earn",
  "装 zhuāng pretend",
  "装饰 zhuāngshì decorate",
  "撞 zhuàng Hit",
  "状况 zhuàngkuàng status",
  "状态 zhuàngtài state",
  "追求 zhuīqiú Pursuit",
  "准备 zhǔnbèi Get ready",
  "准确 zhǔnquè accuracy",
  "准时 zhǔnshí on time",
  "桌子 zhuōzi Table",
  "资格 zīgé Qualifications",
  "资金 zījīn capital",
  "资料 zīliào data",
  "资源 zīyuán Resources",
  "姿势 zīshì posture",
  "咨询 zīxún Consultation",
  "紫 zǐ purple",
  "仔细 zǐxì careful",
  "字 zì word, character",
  "字典 zìdiǎn Dictionaries",
  "字幕 zìmù Subtitle",
  "自从 zìcóng Since",
  "自动 zìdòng automatic",
  "自豪 zìháo Proud",
  "自己 zìjǐ Own, self",
  "自觉 zìjué Conscious",
  "自然 zìrán natural",
  "自私 zìsī selfish",
  "自信 zìxìn self-confidence",
  "自行车 zìxíngchē Bicycle",
  "自由 zìyóu free",
  "自愿 zìyuàn voluntarily",
  "综合 zōnghé comprehensive",
  "宗教 zōngjiào Religion",
  "总裁 zǒngcái CEO",
  "总共 zǒnggòng In total",
  "总结 zǒngjié summary",
  "总理 zǒnglǐ prime minister",
  "总是 zǒngshì always",
  "总算 zǒngsuàn finally",
  "总统 zǒngtǒng President",
  "总之 zǒngzhī in short, in brief",
  "走 zǒu go",
  "租 zū rent",
  "组成 zǔchéng Form",
  "组合 zǔhé combination",
  "组织 zǔzhī organization",
  "祖国 zǔguó Motherland",
  "祖先 zǔxiān Ancestors",
  "阻止 zǔzhǐ prevent",
  "嘴 zuǐ mouth",
  "醉 zuì drunk",
  "最 zuì most",
  "最初 zuìchū First, at the beginning",
  "最好 zuìhǎo Best",
  "最后 zuìhòu Last",
  "最近 zuìjìn Lately",
  "罪犯 zuìfàn Criminal",
  "尊敬 zūnjìng respect",
  "尊重 zūnzhòng respect",
  "遵守 zūnshǒu comply with",
  "昨天 zuótiān Yesterday",
  "左边 zuǒbian left",
  "坐 zuò sit",
  "做 zuò do",
  "做生意 zuòshēngyi Do business",
  "座 zuò Seat",
  "座位 zuòwèi seat",
  "作品 zuòpǐn works",
  "作为 zuòwéi As",
  "作文 zuòwén composition",
  "作业 zuòyè task, homework",
  "作用 zuòyòng Effect",
  "作者 zuòzhě author",
];
