export default [
  "我 我 wǒ I, me",
  "我们 我們 wǒmen we, us (pl.)",
  "你 你 nǐ you",
  "你们 你們 nǐmen you (pl.)",
  "他 他 tā he, him",
  "她 她 tā she, her",
  "他们 他們 tāmen they (male+female / male，pl.)",
  "她们 她們 tāmen they (females, pl.)",
  "这 這 zhè here, this",
  "那 那 nà there, that",
  "哪 哪 nǎ where",
  "谁 誰 shéi who",
  "什么 什麼 shénme what, why",
  "多少 多少 duōshǎo how many, how much",
  "几 幾 jǐ a few, how many",
  "怎么 怎麼 zěnme how",
  "怎么样 怎麼樣 zěnmeyàng how about",
  "您 您 nín you",
  "它 它 tā it",
  "大家 大家 dàjiā everyone",
  "每 每 měi every",
  "为什么 為什麼 wèishénme why",
  "一 一 yī one",
  "二 二 èr two",
  "三 三 sān three",
  "四 四 sì four",
  "五 五 wǔ five",
  "六 六 liù six",
  "七 七 qī seven",
  "八 八 bā eight",
  "九 九 jiǔ nine",
  "十 十 shí ten",
  "零 零 líng zero",
  "两 兩 liǎng two",
  "百 百 bǎi hundred",
  "千 千 qiān thousand",
  "第一 第一 dìyī first",
  "个 個 gè one, a, an",
  "岁 歲 suì year",
  "本 本 běn volume",
  "些 些 xiē some",
  "块 塊 kuài piece",
  "次 次 cì number",
  "公斤 公斤 gōngjīn kilogram",
  "元 元 yuán yuan",
  "件 事 jiàn piece",
  "张 張 zhāng sheet",
  "不 不 bù no",
  "没 沒 méi no",
  "很 很 hěn quite, very",
  "太 太 tài too",
  "都 都 dōu all",
  "别 別 bié other",
  "非常 非常 fēicháng very",
  "也 也 yě likewise",
  "还 還 hái still",
  "最 最 zuì most",
  "真 真 zhēn real",
  "正在 Seizai zhèngzài be being",
  "已经 已經 yǐjīng already",
  "一起 一起 yìqǐ together",
  "再 再 zài again",
  "就 就 jiǜ at once",
  "和 和 hé and",
  "因为 因為 yīnwèi because",
  "所以 所以 suǒyǐ so",
  "但是 但是 dànshì but",
  "在 在 zài in, at",
  "从 從 cóng from",
  "对 對 duì right",
  "此 此 cǐ this",
  "向 向 xiàng towards",
  "离 離 lí leave",
  "喂 餵 wèi hello",
  "家 家 jiā home",
  "学校 學校 xuéxiào school",
  "饭馆 飯館 fàndiàn restaunt",
  "商店 商店 shāngdiàn store",
  "医院 醫院 yīyuàn hospital",
  "火车站 火車站 huǒchēzhàn train station",
  "中国 中國 Zhōngguó China",
  "机场 機場 jīchǎng airport",
  "教室 教室 jiàoshì classroom",
  "房间 房間 fángjiān room",
  "路 路 lù road",
  "北京 北京 Běijīng Beijing",
  "上 上 shàng up",
  "下 下 xià below",
  "前面 前面 qiánmiàn front",
  "后面 後面 hòumiàn behind",
  "左边 左邊 zuǒbiān left",
  "右边 右邊 yòubiān right",
  "外 外 wài out",
  "旁边 旁邊 pángbiān side",
  "里 裡 lǐ inside",
  "今天 今天 jīntiān today",
  "明天 明天 míngtiān tomorrow",
  "昨天 昨天 zuótiān yesterday",
  "上午 上午 shàngwǔ morning",
  "中午 中午 zhōngwǔ noon",
  "下午 下午 xiàwǔ afternoon",
  "年 年 nián year",
  "月 月 yuè month",
  "日 日 rì day",
  "星期 星期 xīngqī week",
  "点 點 diǎn dot, spot",
  "分钟 分鐘 fēnzhōng minute",
  "现在 現在 xiànzài now",
  "时候 時候 shíhou time",
  "早上 早上 zǎoshàng morning",
  "晚上 晚上 wǎnshàng night",
  "小时 小時 xiǎoshí hour",
  "时间 時間 shíjiān time",
  "去年 去年 qùnián last year",
  "号 號 hào number",
  "生日 生日 shēngrì birthday",
  "爸爸 爸爸 bàba father",
  "妈妈 媽媽 māma mother",
  "儿子 兒子 érzi son",
  "女儿 女兒 nǚ'ér daughter",
  "老师 老師 lǎoshī teacher",
  "学生 學生 xuéshēng student",
  "同学 同學 tóngxué shoolmate",
  "朋友 朋友 péngyǒu friend",
  "医生 醫生 yīshēng doctor",
  "先生 先生 xiānsheng sir",
  "小姐 小姐 xiǎojiě Miss",
  "哥哥 哥哥 gēge older brother",
  "姐姐 姐姐 jiějie older sister",
  "弟弟 弟弟 dìdi younger brother",
  "妹妹 妹妹 mèimei younger sister",
  "丈夫 丈夫 zhàngfu husband",
  "妻子 妻子 qīzi wife",
  "孩子 孩子 háizi child",
  "男人 男人 nánrén man",
  "女人 女人 nǚrén woman",
  "服务员 服務員 fúwùyuán waiter",
  "衣服 衣服 yīfu cloth",
  "水 水 shuǐ water",
  "菜 菜 cài dish",
  "米饭 米飯 mǐfàn rice",
  "水果 水果 shuǐguǒ fruit",
  "苹果 蘋果 píngguǒ apple",
  "茶 茶 chá tea",
  "杯子 杯子 bēizi cup",
  "钱 錢 qián money",
  "飞机 飛機 fēijī airplane",
  "出租车 出租車 chūzūchē taxi",
  "电视 電視 diànshì television",
  "电脑 電腦 diànnǎo computer",
  "电影 電影 diànyǐng movie",
  "天气 天氣 tiānqì weather",
  "猫 貓 māo cat",
  "狗 狗 gǒu dog",
  "东西 東西 dōngxi thing",
  "鱼 魚 yú fish",
  "羊肉 羊肉 yángròu mutton",
  "牛奶 牛奶 niúnǎi milk",
  "鸡蛋 雞蛋 jīdàn egg",
  "西瓜 西瓜 xīguā watermelon",
  "咖啡 咖啡 kāfēi coffee",
  "自行车 自行車 zìxíngchē bike",
  "船 船 chuán boat",
  "雪 雪 xuě snow",
  "药 藥 yào medicine",
  "手机 手機 shǒujī cellphone",
  "手表 手錶 shǒubiǎo watch",
  "眼睛 眼睛 yǎnjīng eye",
  "身体 身體 shēntǐ body",
  "公共汽车 公共汽車 gōnggòngqìchē bus",
  "报纸 報紙 bàozhǐ newspaper",
  "人 人 rén person",
  "名字 名字 míngzì name",
  "书 書 shū book",
  "汉语 漢語 hànyǔ Chinese",
  "字 字 zì character",
  "桌子 桌子 zhuōzi desk",
  "椅子 椅子 yǐzi chair",
  "门 門 mén door",
  "题 題 tí topic",
  "课 課 kè lesson",
  "姓 姓 xìng surname",
  "问题 問題 wèntí question",
  "事情 事情 shìqing matter",
  "考试 考試 kǎoshì exam",
  "票 票 piào ticket",
  "意思 意思 yìsi meaning",
  "颜色 顏色 yánsè color",
  "谢谢 謝謝 xièxie thank",
  "不客气 不客氣 búkèqì you are welcome",
  "再见 再見 zàijiàn good-bye",
  "请 請 qǐng please",
  "对不起 對不起 duìbùqǐ sorry",
  "没关系 沒關係 méiguānxi It doesn't matter",
  "欢迎 歡迎 huānyíng welcome",
  "是 是 shì am, is, are",
  "有 有 yǒu have",
  "看 看 kàn look",
  "听 聽 tīng listen",
  "说话 說話 shuōhuà speak",
  "读 讀 dú read",
  "写 寫 xiě write",
  "看见 看見 kànjiàn see",
  "叫 叫 jiào call",
  "来 來 lái come",
  "回 時 huí return",
  "去 去 qù go",
  "吃 吃 chī eat",
  "喝 喝 hē drink",
  "睡觉 睡覺 shuìjiào sleep",
  "打电话 打電話 dǎdiànhuà call up",
  "做 做 zuò do",
  "买 買 mǎi buy",
  "开 開 kāi open",
  "坐 坐 zuò sit",
  "住 住 zhù live",
  "学习 學習 xuéxí study",
  "工作 工作 gōngzuò work",
  "下雨 下雨 xiàyǔ rain",
  "问 問 wèn ask",
  "走 走 zǒu walk",
  "进 進 jìn enter",
  "出 出 chū come",
  "跑步 跑步 pǎobù run",
  "到 到 dào arrive",
  "穿 穿 chuān wear",
  "洗 洗 xǐ wash",
  "给 給 gěi give",
  "找 找 zhǎo find",
  "懂 懂 dǒng understand",
  "笑 洛爾 xiào smile",
  "回答 回答 huídá answer",
  "告诉 告訴 gàosù tell",
  "准备 準備 zhǔnbèi prepare",
  "开始 開始 kāishǐ begin",
  "介绍 介紹 jièshào introduce",
  "帮助 幫助 bāngzhù help",
  "玩 玩 wán play",
  "送 送 sòng present",
  "等 等 děng wait",
  "让 讓 ràng let",
  "起床 起床 qǐchuáng get up",
  "唱歌 唱歌 chànggē sing",
  "跳舞 跳舞 tiàowǔ dance",
  "旅游 旅遊 lǚyóu travel",
  "上班 上班 shàngbān be on duty",
  "生病 生病 shēngbìng fall ill",
  "休息 休息 xiūxi rest",
  "运动 運動 yùndòng exercise",
  "游泳 游泳 yóuyǒng swim",
  "踢足球 踢足球 tīzúqiú play footbal",
  "打篮球 打籃球 dǎlánqiú play basketball",
  "完 完 wán finish",
  "爱 愛 ài love",
  "喜欢 喜歡 xǐhuān love, like",
  "想 想 xiǎng want",
  "认识 認識 rènshi know",
  "觉得 覺得 juédé think",
  "知道 知道 zhīdao know",
  "希望 希望 xīwàng hope",
  "会 會 huì can",
  "能 能 néng can, be able to",
  "可以 可以 kěyǐ can",
  "要 要 yào ask for",
  "可能 可能 kěnéng may",
  "好 好 hǎo good",
  "大 大 dà big",
  "小 小 xiǎo small",
  "多 多 duō many, much",
  "少 少 shǎo few, little",
  "冷 冷 lěng cold",
  "热 熱 rè hot",
  "高兴 高興 gāoxìng happy",
  "漂亮 漂亮 piàoliang beautiful",
  "高 高 gāo tall",
  "红 紅 hóng red",
  "白 白 bái white",
  "黑 黑 hēi black",
  "忙 忙 máng busy",
  "快 快 kuài fast",
  "慢 慢 màn slow",
  "远 遠 yuǎn far",
  "近 近 jìn close",
  "好吃 好吃 hǎochī delicioous",
  "累 累 lèi tired",
  "长 長 cháng long",
  "新 新 xīn new",
  "贵 貴 guì expensive",
  "便宜 便宜 piányi cheap",
  "晴 晴 qíng fine",
  "阴 陰 yīn cloudy",
  "错 錯 cuò wrong",
  "快乐 快樂 kuàilè happy",
];
