export default [
  "爱情 愛情 àiqíng Love",
  "安排 安排 ānpái arrange",
  "安全 安全 ānquán security",
  "暗 暗 àn dark",
  "按时 按時 ànshí on time",
  "按照 按照 ànzhào according to",
  "包括 包括 bāokuò Include",
  "保护 保護 bǎohù protect",
  "保证 保證 bǎozhèng ensure",
  "抱 抱 bào Hold",
  "抱歉 抱歉 bàoqiàn feel sorry",
  "报道 報導 bàodào report",
  "报名 報名 bàomíng sign up",
  "倍 倍 bèi times",
  "本来 本來 běnlái originally",
  "笨 笨 bèn stupid",
  "笔记本 筆記本 bǐjìběn Notebook",
  "毕业 畢業 bìyè graduation",
  "遍 遍 biàn Times",
  "标准 標準 biāozhǔn standard",
  "表达 表達 biǎodá Expression",
  "表格 表格 biǎogé form",
  "表扬 表揚 biǎoyáng Praise",
  "饼干 餅乾 bǐnggān Biscuits",
  "并且 並且 bìngqiě also",
  "博士 博士 bóshì doctor",
  "不但 不但 búdàn not only",
  "不过 不過 búguò However",
  "不得不 不得不 bùdébù have to",
  "不管 不管 bùguǎn no matter",
  "不仅 不僅 bùjǐn not only",
  "部分 部分 bùfen Part",
  "擦 擦 cā wipe",
  "猜 猜 cāi guess",
  "材料 材料 cáiliào Material Science",
  "参观 參觀 cānguān visit",
  "差不多 差不多 chàbuduō Almost",
  "尝 嘗 cháng taste",
  "长城 長城 chángchéng The Great Wall",
  "长江 長江 chángjiāng The Yangtze River",
  "场 場 chǎng site",
  "超过 超過 chāoguò Exceed",
  "吵 吵 chǎo Noisy",
  "成功 成功 chénggōng Success",
  "成熟 成熟 chéngshú mature",
  "成为 成為 chéngwéi Become",
  "诚实 誠實 chéngshí honest",
  "乘坐 乘坐 chéngzuò ride",
  "吃惊 吃驚 chījīng Be amazed",
  "重新 重新 chóngxīn again",
  "抽烟 抽煙 chōuyān smoking",
  "出差 出差 chūchāi A business travel",
  "出发 出發 chūfā Set out",
  "出生 出生 chūshēng Birth",
  "传真 傳真 chuánzhēn Fax",
  "窗户 窗戶 chuānghu Window",
  "词典 詞典 cídiǎn Dictionary",
  "从来 從來 cónglái Always",
  "粗心 粗心 cūxīn careless",
  "答案 答案 dá'àn Answer",
  "打扮 打扮 dǎban dress up",
  "打扰 打擾 dǎrǎo Disturb",
  "打印 打印 dǎyìn Print",
  "打折 打折 dǎzhé Discount",
  "打针 打針 dǎzhēn To make an injection",
  "大概 大概 dàgài Probably",
  "大使馆 大使館 dàshǐguǎn Embassy",
  "大约 大約 dàyuē about",
  "戴 戴 dài wear",
  "代表 代表 dàibiǎo representative",
  "代替 代替 dàitì replace",
  "大夫 大夫 dàifu Doctor",
  "当 當 dāng When",
  "当地 當地 dāngdì Local",
  "当时 當時 dāngshí at that time",
  "刀 刀 dāo knife",
  "导游 導遊 dǎoyóu Guide",
  "到处 到處 dàochù everywhere",
  "到底 到底 dàodǐ To the end",
  "道歉 道歉 dàoqiàn apologize",
  "得意 擅長 déyì Proud",
  "得 得 děi have to",
  "底 底 dǐ bottom",
  "地球 地球 dìqiú earth",
  "地址 地址 dìzhǐ address",
  "掉 掉 diào fall",
  "调查 調查 diàochá investigation",
  "丢 丟 diū lose",
  "动作 動作 dòngzuò action",
  "堵车 堵車 dǔchē Traffic jam",
  "肚子 肚子 dùzi belly",
  "断 斷 duàn break",
  "对话 對話 duìhuà dialogue",
  "对面 對面 duìmiàn Opposite side",
  "顿 頓 dùn Meal",
  "朵 朵 duǒ classifier of flower",
  "而 而 ér and",
  "儿童 兒童 értóng children",
  "发 發 fā send out",
  "发生 發生 fāshēng Happen",
  "发展 發展 fāzhǎn Development",
  "法律 法律 fǎlǜ Law",
  "翻译 翻譯 fānyì translate",
  "烦恼 煩惱 fánnǎo annoyance",
  "反对 反對 fǎnduì Opposition",
  "反映 反映 fǎnyìng reflect",
  "范围 範圍 fànwéi Range",
  "方法 方法 fāngfǎ Method",
  "方面 方面 fāngmiàn Aspect",
  "方向 方向 fāngxiàng direction",
  "访问 訪問 fǎngwèn Visit",
  "放弃 放棄 fàngqì give up",
  "放暑假 放暑假 fàngshǔjià summer vacation",
  "分之 分之 fēnzhī percent",
  "份 份 fèn share (measure word)",
  "丰富 豐富 fēngfù rich",
  "风景 風景 fēngjǐng Scenery",
  "否则 否則 fǒuzé otherwise",
  "符合 符合 fúhé accord with",
  "富 富 fù rich",
  "父亲 父親 fùqīn father",
  "复印 複印 fùyìn To copy",
  "复杂 複雜 fùzá complex",
  "负责 負責 fùzé Be responsible for",
  "改变 改變 gǎibiàn change",
  "干杯 乾杯 gānbēi Cheers!",
  "干燥 乾燥 gānzào Dry",
  "感动 感動 gǎndòng Be moved",
  "感觉 感覺 gǎnjué feel",
  "感情 感情 gǎnqíng feeling",
  "感谢 感謝 gǎnxiè Thank",
  "干 幹 gān dry",
  "刚刚 剛剛 gānggāng just",
  "高级 高級 gāojí senior",
  "各 各 gè various",
  "个子 個子 gèzi Height",
  "公里 公里 gōnglǐ kilometre",
  "工具 工具 gōngjù tool",
  "工资 工資 gōngzī wages",
  "共同 共同 gòngtóng common",
  "够 夠 gòu enough",
  "购物 購物 gòuwù Shopping",
  "孤单 孤單 gūdān alone",
  "估计 估計 gūjì estimate",
  "鼓励 鼓勵 gǔlì encourage",
  "鼓掌 鼓掌 gǔzhǎng applause",
  "顾客 顧客 gùkè customer",
  "故意 故意 gùyì deliberately",
  "挂 掛 guà hang",
  "关键 關鍵 guānjiàn key",
  "观众 觀眾 guānzhòng Audience",
  "管理 管理 guǎnlǐ Administration",
  "光 光 guāng light",
  "广播 廣播 guǎngbō Radio broadcast",
  "广告 廣告 guǎnggào Advertisement",
  "逛 逛 guàng Stroll",
  "规定 規定 guīdìng Regulations",
  "国际 國際 guójì international",
  "果然 果然 guǒrán Sure enough",
  "过程 過程 guòchéng process",
  "海洋 海洋 hǎiyáng ocean",
  "害羞 害羞 hàixiū Shy",
  "寒假 寒假 hánjià The winter vacation",
  "汗 汗 hàn sweat",
  "航班 航班 hángbān flight",
  "好处 好處 hǎochù benefit",
  "好像 好像 hǎoxiàng Be like, seem",
  "号码 號碼 hàomǎ number",
  "合格 合格 hégé qualified",
  "合适 合適 héshì appropriate",
  "盒子 盒子 hézi Box",
  "猴子 猴子 hóuzi Monkey",
  "厚 厚 hòu thick",
  "后悔 後悔 hòuhuǐ regret",
  "后来 後來 hòulái later",
  "忽然 忽然 hūrán suddenly",
  "护士 護士 hùshi Nurse",
  "互相 互相 hùxiāng each other",
  "怀疑 懷疑 huáiyí doubt",
  "回忆 回憶 huíyì Memory",
  "活动 活動 huódòng activity",
  "活泼 活潑 huópō lively",
  "火 火 huǒ fire",
  "获得 獲得 huòdé Get",
  "基础 基礎 jīchǔ Basics",
  "激动 激動 jīdòng Excited",
  "积极 積極 jījí positive",
  "积累 積累 jīlěi accumulation",
  "极其 極其 jíqí extremely",
  "集合 集合 jíhé aggregate",
  "及时 及時 jíshí timely",
  "即使 即使 jíshǐ even if",
  "寄 寄 jì send",
  "记者 記者 jìzhě Reporter",
  "计划 計劃 jìhuà plan",
  "既然 既然 jìrán although",
  "技术 技術 jìshù technology",
  "继续 繼續 jìxù Continue",
  "家具 家具 jiājù furniture",
  "加班 加班 jiābān overtime work",
  "加油站 加油站 jiāyóuzhàn Gas station",
  "假 假 jiǎ false",
  "价格 價格 jiàgé Price",
  "坚持 堅持 jiānchí Insist",
  "减肥 減肥 jiǎnféi Reduce weight",
  "减少 減少 jiǎnshǎo reduce",
  "将来 未來 jiānglái future",
  "奖金 獎金 jiǎngjīn bonus",
  "降低 降低 jiàngdī reduce",
  "交 交 jiāo hand over",
  "交流 交流 jiāoliú Communication",
  "交通 交通 jiāotōng traffic",
  "骄傲 驕傲 jiāo'ào Proud",
  "饺子 餃子 jiǎozi Dumplings",
  "教授 教授 jiàoshòu professor",
  "教育 教育 jiàoyù education",
  "接受 接受 jiēshòu accept",
  "结果 結果 jiéguǒ Result",
  "节约 節約 jiéyuē save",
  "解释 解釋 jiěshì explain",
  "尽管 儘管 jǐnguǎn although",
  "紧张 緊張 jǐnzhāng Nervous",
  "进行 進行 jìnxíng in process of",
  "禁止 禁止 jìnzhǐ prohibit",
  "精彩 精彩 jīngcǎi Marvellous",
  "精神 精神 jīngshén spirit",
  "经济 經濟 jīngjì Economics",
  "经历 經歷 jīnglì experience",
  "经验 經驗 jīngyàn experience",
  "京剧 京劇 jīngjù Beijing opera",
  "警察 警察 jǐngchá Policeman",
  "竟然 竟然 jìngrán Unexpectedly",
  "竞争 競爭 jìngzhēng compete",
  "镜子 鏡子 jìngzi Mirror",
  "究竟 究竟 jiūjìng exactly",
  "举办 舉辦 jǔbàn hold",
  "拒绝 拒絕 jùjué refuse",
  "距离 距離 jùlí distance",
  "开玩笑 開玩笑 kāiwánxiào Make fun of",
  "看法 看法 kànfǎ view",
  "考虑 考慮 kǎolǜ Consider",
  "棵 棵 kē Tree (measure word)",
  "科学 科學 kēxué science",
  "咳嗽 咳嗽 késou cough",
  "可怜 可憐 kělián Poor",
  "可是 可是 kěshì however",
  "可惜 可惜 kěxī unfortunately",
  "肯定 肯定 kěndìng sure",
  "空气 空氣 kōngqì air",
  "恐怕 恐怕 kǒngpà I'm afraid",
  "苦 苦 kǔ bitter",
  "宽 寬 kuān wide",
  "困 困 kùn sleepy",
  "困难 困難 kùnnan difficulty",
  "扩大 擴大 kuòdà Expand",
  "拉 拉 lā pull",
  "垃圾桶 垃圾桶 lājītǒng Trash",
  "辣 辣 là spicy",
  "来不及 來不及 láibují There's not enough time",
  "来得及 來得及 láidejí In time",
  "懒 懶 lǎn lazy",
  "浪费 浪費 làngfèi Waste",
  "浪漫 浪漫 làngmàn romantic",
  "老虎 老虎 lǎohǔ Tiger",
  "冷静 冷靜 lěngjìng calm down",
  "理发 理髮 lǐfà Haircut",
  "理解 理解 lǐjiě Understand",
  "理想 理想 lǐxiǎng ideal",
  "礼貌 禮貌 lǐmào politeness",
  "厉害 厲害 lìhai Fierce",
  "力气 力氣 lìqi Strength",
  "例如 例如 lìrú for example",
  "俩 倆 liǎ Two",
  "连 連 lián even",
  "联系 聯繫 liánxì contact",
  "凉快 涼快 liángkuai Pleasantly cool",
  "亮 亮 liàng bright",
  "聊天 聊天 liáotiān chat",
  "另外 另外 lìngwài in addition",
  "留 留 liú stay",
  "留学 留學 liúxué Overseas Study",
  "流泪 流淚 liúlèi Shed tears",
  "流利 流利 liúlì fluent",
  "流行 流行 liúxíng Popular",
  "乱 亂 luàn chaos",
  "律师 律師 lǜshī Lawyer",
  "麻烦 麻煩 máfan trouble",
  "马虎 馬虎 mǎhu Careless",
  "满 滿 mǎn full",
  "毛巾 毛巾 máojīn Towel",
  "美丽 美麗 měilì beautiful",
  "梦 夢 mèng dream",
  "密码 密碼 mìmǎ Password",
  "免费 免費 miǎnfèi Free of charge",
  "民族 民族 mínzú Nation",
  "母亲 母親 mǔqīn mother",
  "目的 目的 mùdì objective",
  "耐心 耐心 nàixīn patience",
  "难道 難道 nándào could it be said that ...",
  "难受 難受 nánshòu Uncomfortable",
  "内 內 nèi within",
  "内容 內容 nèiróng content",
  "能力 能力 nénglì ability",
  "年龄 年齡 niánlíng Age",
  "农村 農村 nóngcūn countryside",
  "弄 弄 nòng get, make",
  "暖和 暖和 nuǎnhuo warm",
  "偶尔 偶爾 ǒu'ěr occasionally",
  "排列 排列 páiliè array",
  "判断 判斷 pànduàn judge",
  "陪 陪 péi accompany",
  "批评 批評 pīpíng criticism",
  "皮肤 皮膚 pífū skin",
  "脾气 脾氣 píqi Bad temper",
  "篇 篇 piān piece",
  "骗 騙 piàn fool",
  "乒乓球 乒乓球 pīngpāngqiú Table Tennis",
  "平时 平時 píngshí peacetime",
  "瓶子 瓶子 píngzi Bottle",
  "破 破 pò broken",
  "普遍 普遍 pǔbiàn universal",
  "其次 其次 qícì Secondly",
  "其中 其中 qízhōng among",
  "起飞 起飛 qǐfēi take off",
  "起来 起來 qǐlái get up",
  "气候 氣候 qìhòu climate",
  "千万 千萬 qiānwàn Must",
  "签证 簽證 qiānzhèng visa",
  "墙 牆 qiáng wall",
  "敲 敲 qiāo knock",
  "桥 橋 qiáo Bridge",
  "巧克力 巧克力 qiǎokèlì Chocolates",
  "亲戚 親戚 qīnqi Relative",
  "轻 輕 qīng light",
  "轻松 輕鬆 qīngsōng Relaxed",
  "情况 情況 qíngkuàng Situation",
  "请假 請假 qǐngjià leave",
  "请客 請客 qǐngkè Treat",
  "穷 窮 qióng poor",
  "区别 區別 qūbié Difference",
  "取 取 qǔ take",
  "全部 全部 quánbù whole",
  "缺点 缺點 quēdiǎn shortcoming",
  "缺少 缺少 quēshǎo Lack",
  "却 卻 què but",
  "确实 確實 quèshí Exactly",
  "群 群 qún group",
  "然而 然而 rán'ér however",
  "热闹 熱鬧 rènao lively",
  "人民币 人民幣 rénmínbì RMB",
  "任何 任何 rènhé whatever, any",
  "任务 任務 rènwu task",
  "扔 扔 rēng throw",
  "仍然 仍然 réngrán still",
  "日记 日記 rìjì diary",
  "入口 入口 rùkǒu Entrance",
  "软 軟 ruǎn soft",
  "散步 散步 sànbù Take a walk",
  "森林 森林 sēnlín Forest",
  "沙发 沙發 shāfā Sofa",
  "商量 商量 shāngliang discuss",
  "伤心 傷心 shāngxīn Sad",
  "稍微 稍微 shāowēi slightly",
  "社会 社會 shèhuì Sociology",
  "深 深 shēn deep",
  "申请 申請 shēnqǐng Apply",
  "甚至 甚至 shènzhì Even to the extent that",
  "生活 生活 shēnghuó Life",
  "生命 生命 shēngmìng life",
  "省 省 shěng province",
  "剩 剩 shèng Left",
  "失败 失敗 shībài fail",
  "失望 失望 shīwàng Disappointment",
  "师傅 師傅 shīfu Master worker",
  "湿润 濕潤 shīrùn Moist",
  "狮子 獅子 shīzi Lion",
  "十分 十分 shífēn very",
  "实际 實際 shíjì Actual",
  "实在 實在 shízài really",
  "食品 食品 shípǐn food",
  "使用 使用 shǐyòng Use",
  "试 試 shì try",
  "市场 市場 shìchǎng market",
  "适合 適合 shìhé Fit",
  "适应 適應 shìyìng Adapt",
  "世纪 世紀 shìjì century",
  "收 收 shōu collect",
  "收入 收入 shōurù income",
  "收拾 收拾 shōushi Tidy",
  "首都 首都 shǒudū capital",
  "首先 首先 shǒuxiān First",
  "受不了 受不了 shòubuliǎo Cannot bear sth",
  "受到 受到 shòudào Suffer",
  "售货员 售貨員 shòuhuòyuán Salesperson",
  "输 輸 shū lose, fail",
  "熟悉 熟悉 shúxī be familiar with",
  "数量 數量 shùliàng Number",
  "数字 數字 shùzì number",
  "帅 帥 shuài Handsome",
  "顺便 順便 shùnbiàn Incidentally",
  "顺利 順利 shùnlì smoothly",
  "顺序 順序 shùnxù order",
  "说明 說明 shuōmíng Explain",
  "硕士 碩士 shuòshì master",
  "死 死 sǐ die",
  "速度 速度 sùdù speed",
  "塑料袋 塑料袋 sùliàodài Plastic bag",
  "酸 酸 suān acid",
  "算 算 suàn count",
  "随便 隨便 suíbiàn casual",
  "随着 隨著 suízhe along with",
  "孙子 孫子 sūnzi Grandson",
  "所有 所有 suǒyǒu All",
  "台 台 tái platform",
  "抬 抬 tái Lift",
  "态度 態度 tàidu attitude",
  "谈 談 tán talk",
  "弹钢琴 彈鋼琴 tángāngqín Play the piano",
  "汤 湯 tāng soup",
  "躺 躺 tǎng lie",
  "趟 趟 tàng Trip",
  "讨论 討論 tǎolùn discuss",
  "讨厌 討厭 tǎoyàn Hate",
  "特点 特點 tèdiǎn Characteristic",
  "提供 提供 tígōng provide",
  "提前 提前 tíqián in advance",
  "提醒 提醒 tíxǐng remind",
  "填空 填空 tiánkòng Fill in the blanks",
  "条件 條件 tiáojiàn condition",
  "停止 停止 tíngzhǐ Stop it",
  "挺 挺 tǐng quite",
  "通过 通過 tōngguò through",
  "通知 通知 tōngzhī notice",
  "同情 同情 tóngqíng Sympathy",
  "推 推 tuī push",
  "推迟 推遲 tuīchí delay",
  "脱 脫 tuō take off",
  "袜子 襪子 wàzi Socks",
  "完全 完全 wánquán completely",
  "往 往 wǎng to, towards",
  "往往 往往 wǎngwǎng Often",
  "网球 網球 wǎngqiú Tennis",
  "网站 網站 wǎngzhàn website",
  "危险 危險 wēixiǎn danger",
  "味道 味道 wèidào taste",
  "温度 溫度 wēndù temperature",
  "文章 文章 wénzhāng Article",
  "握手 握手 wòshǒu Handshake",
  "污染 污染 wūrǎn contaminated",
  "无 無 wú nothing",
  "无聊 無聊 wúliáo Boring",
  "无论 無論 wúlùn no matter what",
  "误会 誤會 wùhuì Misunderstanding",
  "西红柿 西紅柿 xīhóngshì Tomato",
  "吸引 吸引 xīyǐn Attract",
  "洗衣机 洗衣機 xǐyījī Washing machine",
  "咸 咸 xián salty",
  "现代 現代 xiàndài modern",
  "羡慕 羨慕 xiànmù Envy",
  "限制 限制 xiànzhì limit",
  "香 香 xiāng fragrant",
  "相反 相反 xiāngfǎn Contrary",
  "详细 詳細 xiángxì detailed",
  "响 響 xiǎng ring",
  "消息 消息 xiāoxi message",
  "小说 小說 xiǎoshuō Novel",
  "笑话 笑話 xiàohua joke",
  "效果 效果 xiàoguǒ Effect",
  "辛苦 辛苦 xīnkǔ hard",
  "心情 心情 xīnqíng mood",
  "信任 信任 xìnrèn trust",
  "信心 信心 xìnxīn confidence",
  "信用卡 信用卡 xìnyòngkǎ Credit card",
  "兴奋 興奮 xīngfèn Excitement",
  "行 行 xíng That's ok",
  "醒 醒 xǐng wake up",
  "性别 性別 xìngbié Gender",
  "性格 性格 xìnggé character",
  "幸福 幸福 xìngfú happiness",
  "修 修 xiū repair",
  "许多 許多 xǔduō many",
  "血 血 xuè blood",
  "压力 壓力 yālì pressure",
  "牙膏 牙膏 yágāo toothpaste",
  "亚洲 亞洲 yàzhōu Asia",
  "呀 呀 ya ah",
  "盐 鹽 yán salt",
  "严格 嚴格 yángé strict",
  "严重 嚴重 yánzhòng serious",
  "研究生 研究生 yánjiūshēng Graduate student",
  "演出 演出 yǎnchū show",
  "演员 演員 yǎnyuán performer, actor",
  "阳光 陽光 yángguāng Sunshine",
  "养成 養成 yǎngchéng Cultivate",
  "样子 樣子 yàngzi A look",
  "邀请 邀請 yāoqǐng Invitation",
  "钥匙 鑰匙 yàoshi Key",
  "也许 也許 yěxǔ perhaps",
  "页 頁 yè page",
  "叶子 葉子 yèzi Leaf",
  "一切 一切 yíqiè everything",
  "以 以 yǐ with",
  "亿 億 yì Billion",
  "意见 意見 yìjiàn Opinion",
  "艺术 藝術 yìshù Art",
  "因此 因此 yīncǐ therefore",
  "饮料 飲料 yǐnliào Drinks",
  "引起 引起 yǐnqǐ cause",
  "印象 印象 yìnxiàng impression",
  "赢 贏 yíng win",
  "硬 硬 yìng hard",
  "勇敢 勇敢 yǒnggǎn Brave",
  "永远 永遠 yǒngyuǎn forever",
  "优点 優點 yōudiǎn Advantage",
  "优秀 優秀 yōuxiù excellent",
  "幽默 幽默 yōumò Humor",
  "由 由 yóu from",
  "由于 由於 yóuyú Because",
  "尤其 尤其 yóuqí especially",
  "有趣 有趣 yǒuqù interesting",
  "友好 友好 yǒuhǎo friendly",
  "友谊 友誼 yǒuyì friendship",
  "愉快 愉快 yúkuài Cheerful",
  "于是 於是 yúshì Therefore",
  "与 與 yǔ and",
  "语法 語法 yǔfǎ grammar",
  "语言 語言 yǔyán language",
  "羽毛球 羽毛球 yǔmáoqiú Badminton",
  "预习 預習 yùxí Preview",
  "圆 圓 yuán circle",
  "原来 原來 yuánlái Original",
  "原谅 原諒 yuánliàng Forgive",
  "原因 原因 yuányīn Reason",
  "约会 約會 yuēhuì Date",
  "阅读 閱讀 yuèdú Read",
  "允许 允許 yǔnxǔ allow",
  "杂志 雜誌 zázhì Magazine",
  "咱们 咱們 zánmen We",
  "暂时 暫時 zànshí temporary",
  "脏 臟 zāng dirty",
  "责任 責任 zérèn responsibility",
  "增加 增加 zēngjiā increase",
  "增长 增長 zēngzhǎng increase",
  "窄 窄 zhǎi narrow",
  "招聘 招聘 zhāopìn recruit",
  "着 著 zhe in process of",
  "真正 真正 zhēnzhèng real",
  "整理 整理 zhěnglǐ Arrangement",
  "整齐 整齊 zhěngqí neat",
  "正常 正常 zhèngcháng normal",
  "正好 正好 zhènghǎo Just right",
  "正确 正確 zhèngquè Correct",
  "正式 正式 zhèngshì formal",
  "证明 證明 zhèngmíng Prove",
  "之 之 zhī of",
  "支持 支持 zhīchí Support",
  "知识 知識 zhīshi knowledge",
  "值得 值得 zhídé Worth",
  "直接 直接 zhíjiē direct",
  "植物 植物 zhíwù Botany, plant",
  "职业 職業 zhíyè Occupation",
  "指 指 zhǐ finger, to point",
  "只好 只好 zhǐhǎo have to",
  "只要 只要 zhǐyào as long as",
  "质量 質量 zhìliàng quality",
  "至少 至少 zhìshǎo at least",
  "制造 製造 zhìzào Manufacture",
  "中文 中國 zhōngwén Chinese",
  "重点 重點 zhòngdiǎn A key",
  "重视 重視 zhòngshì importance, attach importance to",
  "周围 周圍 zhōuwéi around",
  "猪 豬 zhū pig",
  "逐渐 逐漸 zhújiàn gradually",
  "主动 主動 zhǔdòng active",
  "主意 主意 zhǔyi idea",
  "祝贺 祝賀 zhùhè Congratulate",
  "著名 著名 zhùmíng famous",
  "专门 專門 zhuānmén specialized",
  "专业 專業 zhuānyè major",
  "赚 賺 zhuàn earn",
  "撞 撞 zhuàng Hit",
  "准确 準確 zhǔnquè accuracy",
  "准时 準時 zhǔnshí on time",
  "仔细 仔細 zǐxì careful",
  "自然 自然 zìrán natural",
  "总结 總結 zǒngjié summary",
  "租 租 zū rent",
  "组成 組成 zǔchéng Form",
  "组织 組織 zǔzhī organization",
  "嘴 嘴 zuǐ mouth",
  "最好 最好 zuìhǎo Best",
  "最后 最後 zuìhòu Last",
  "尊重 尊重 zūnzhòng respect",
  "做生意 做生意 zuòshēngyi Do business",
  "座 座 zuò Seat",
  "座位 座位 zuòwèi seat",
  "作者 作者 zuòzhě author",
];
