export default [
  "哎哟 哎喲 āiyō Oh",
  "挨 挨 ái Next to",
  "癌症 癌症 áizhèng cancer",
  "爱不释手 愛不釋手 àibúshìshǒu So much that one cannot bear to part with it",
  "爱戴 愛戴 àidài love and esteem",
  "暧昧 曖昧 àimèi ambiguous",
  "安居乐业 安居樂業 ānjūlèyè Live and work in peace",
  "安宁 安寧 ānníng peaceful; calm",
  "安详 安詳 ānxiáng serene; composed",
  "安置 安置 ānzhì put; arrange for",
  "暗示 暗示 ànshì suggest secretly",
  "案件 案件 ànjiàn law case; case",
  "案例 案例 ànlì case",
  "按摩 按摩 ànmó massage",
  "昂贵 昂貴 ángguì expensive",
  "凹凸 凹凸 āotū concave-convex",
  "熬 熬 áo Boil",
  "奥秘 奧秘 àomì secret",
  "扒 扒 bā hold on to; dig up; push aside;",
  "疤 疤 bā scar",
  "巴不得 巴不得 bābude eagerly look forward to",
  "巴结 巴結 bājié stutter",
  "拔苗助长 拔苗助長 bámiáozhùzhǎng Spoil things by excessive enthusiasm",
  "把关 把關 bǎguān hold the pass",
  "把手 把手 bǎshou knob",
  "把戏 把戲 bǎxì acrobatics; jugglery",
  "霸道 霸道 bàdào overbearing",
  "罢工 罷工 bàgōng Strike",
  "掰 掰 bāi break off with fingers and thumb",
  "百分点 百分點 bǎifēndiǎn percentage",
  "摆脱 擺脫 bǎituō cast off",
  "拜访 拜訪 bàifǎng visit",
  "拜年 拜年 bàinián congratulate the New Year",
  "拜托 拜託 bàituō request",
  "败坏 敗壞 bàihuài Corrupt",
  "颁布 頒布 bānbù promulgate; issue",
  "颁发 頒發 bānfā award; issue",
  "斑纹 斑紋 bānwén stripe",
  "版本 版本 bǎnběn Edition",
  "半途而废 半途而廢 bàntú'érfèi Give up halfway",
  "伴侣 伴侶 bànlǚ partner; mate",
  "伴随 伴隨 bànsuí go with",
  "扮演 扮演 bànyǎn Play the role",
  "绑架 綁架 bǎngjià Kidnap",
  "榜样 榜樣 bǎngyàng example",
  "磅 磅 bàng pound",
  "包庇 包庇 bāobì Shield",
  "包袱 包袱 bāofu Burden",
  "包围 包圍 bāowéi Surround",
  "包装 包裝 bāozhuāng pack; put up; make up",
  "饱和 飽和 bǎohé saturated",
  "饱经沧桑 飽經滄桑 bǎojīngcāngsāng Have seen much of the changes in human life",
  "保管 存儲 bǎoguǎn Safekeeping",
  "保密 保密 bǎomì secrecy",
  "保姆 保姆 bǎomǔ nurse; mammy",
  "保守 保守 bǎoshǒu Conservative",
  "保卫 保衛 bǎowèi Defend",
  "保养 保養 bǎoyǎng maintain",
  "保障 保障 bǎozhàng guarantee",
  "保重 保重 bǎozhòng take care of oneself",
  "抱负 抱負 bàofù ambition",
  "抱怨 抱怨 bàoyuàn Complain",
  "报仇 報仇 bàochóu revenge",
  "报酬 報酬 bàochou remuneration",
  "报答 報答 bàodá reciprocate; pay back; repay",
  "报到 報到 bàodào register,check in",
  "报复 報復 bàofù Payback",
  "报社 報社 bàoshè Newspaper office",
  "报销 報銷 bàoxiāo submit and expense account",
  "爆发 爆發 bàofā burst",
  "爆炸 爆炸 bàozhà blast",
  "曝光 曝光 bàoguāng exposure",
  "暴力 暴力 bàolì violence",
  "暴露 暴露 bàolù Expose",
  "悲哀 悲哀 bēi'āi Grief",
  "悲惨 悲慘 bēicǎn miserable",
  "卑鄙 卑鄙 bēibǐ despicable",
  "北极 北極 běijí arctic",
  "被动 被動 bèidòng passive",
  "被告 被告 bèigào Defendant",
  "背叛 背叛 bèipàn sellout; betray",
  "背诵 背誦 bèisòng recite",
  "备份 備份 bèifèn backups",
  "备忘录 備忘錄 bèiwànglù Memorandum",
  "贝壳 貝殼 bèikè shell; conch",
  "奔波 奔波 bēnbō rush about",
  "奔驰 奔馳 bēnchí run quickly",
  "本能 本能 běnnéng instinct",
  "本钱 本錢 běnqián Capital",
  "本人 本人 běnrén oneself",
  "本身 本身 běnshēn itself",
  "本事 本事 běnshi Skill",
  "本着 這件衣服 běnzhe In line with",
  "笨拙 笨拙 bènzhuō clumsy",
  "崩溃 崩潰 bēngkuì collapse breakdown",
  "甭 甭 béng Not",
  "蹦 蹦 bèng Jump",
  "迸发 迸發 bèngfā Burst",
  "逼迫 逼迫 bīpò force; compel",
  "鼻涕 鼻涕 bítì nasal mucus",
  "比方 比方 bǐfāng Example",
  "比喻 比喻 bǐyù comparison; trope",
  "比重 比重 bǐzhòng specific gravity; proportion",
  "臂 臂 bì arm",
  "弊病 弊病 bìbìng ills",
  "弊端 弊端 bìduān malpractice",
  "必定 必定 bìdìng Certainly",
  "闭塞 閉塞 bìsè Occlusion",
  "碧玉 碧玉 bìyù Jasper",
  "鞭策 鞭策 biāncè urge on",
  "编织 編織 biānzhī Weave",
  "边疆 邊疆 biānjiāng frontier",
  "边界 邊界 biānjiè boundary",
  "边境 邊境 biānjìng border; frontier",
  "边缘 邊緣 biānyuán edge",
  "扁 扁 biǎn flat",
  "贬低 貶低 biǎndī depreciate",
  "贬义 貶義 biǎnyì derogatory sense",
  "遍布 遍布 biànbù All over",
  "便利 方便 biànlì facilitate",
  "便条 便條 biàntiáo Note",
  "便于 便於 biànyú Easy to",
  "变故 變故 biàngù Misfortune",
  "变迁 變遷 biànqiān Changes",
  "变质 變質 biànzhì deteriorate",
  "辩护 辯護 biànhù Defend",
  "辩解 辯解 biànjiě Explain",
  "辩证 辯證 biànzhèng dialectical",
  "辨认 辨認 biànrèn distinguish",
  "辫子 辮子 biànzi queue; plait",
  "标本 標本 biāoběn specimen; demo",
  "标记 標記 biāojì sign",
  "标题 標題 biāotí title; heading",
  "飙升 飆升 biāoshēng Soar",
  "表决 表決 biǎojué Vote",
  "表态 表態 biǎotài clarify one's position",
  "表彰 表彰 biǎozhāng commend; cite",
  "憋 憋 biē hold back",
  "别墅 別墅 biéshù Villa",
  "别致 別緻 biézhì Unique",
  "别扭 彆扭 bièniu unnatural; awkward",
  "濒临 瀕臨 bīnlín On the verge of",
  "冰雹 冰雹 bīngbáo hail",
  "并存 並存 bìngcún Coexist",
  "并非 並非 bìngfēi not so",
  "并列 並列 bìngliè Parallel",
  "拨打 撥打 bōdǎ dial",
  "播放 播放 bōfàng play",
  "播种 播種 bōzhòng Sow",
  "波浪 波浪 bōlàng wave",
  "波涛汹涌 波濤洶湧 bōtāoxiōngyǒng Roaring waves",
  "剥削 剝削 bōxuē exploitation",
  "博大精深 博大精深 bódàjīngshēn Broad and profound",
  "博览会 博覽會 bólǎnhuì exposition",
  "搏斗 搏鬥 bódòu struggle; fight",
  "伯母 伯母 bómǔ Aunt",
  "薄弱 薄弱 bóruò weak",
  "不顾 不顧 búgù disregard",
  "不愧 不愧 búkuì Worthy",
  "不料 不料 búliào Unexpectedly",
  "不像话 不像話 búxiànghuà unreasonable",
  "不屑一顾 不屑一顧 búxièyígù A contemptuous disregard",
  "补偿 補償 bǔcháng compensate",
  "补救 補救 bǔjiù remedy",
  "补贴 補貼 bǔtiē subsidy",
  "哺乳 哺乳 bǔrǔ lactation",
  "捕捉 捕捉 bǔzhuō Catch",
  "不得已 不得已 bùdéyǐ have no alternative but to",
  "不妨 不妨 bùfáng might as well",
  "不敢当 不敢當 bùgǎndāng I really don't deserve this.",
  "不禁 不禁 bùjīn Can not help but",
  "不堪 不堪 bùkān can't bear",
  "不可思议 不可思議 bùkěsīyì It is beyond logic and above reason",
  "不时 不時 bùshí now and then",
  "不惜 不惜 bùxī not spare; not hesitate",
  "不相上下 不相上下 bùxiāngshàngxià about the same; equally matched",
  "不言而喻 不言而喻 bùyán'éryù Self-evident",
  "不由得 不由得 bùyóude Cannot help",
  "不择手段 不擇手段 bùzéshǒuduàn Use unscrupulous divisive tactics",
  "不止 不止 bùzhǐ more than",
  "布告 佈告 bùgào Notice",
  "布局 佈局 bùjú distribution; layout",
  "布置 佈置 bùzhì Arrangement",
  "步伐 步伐 bùfá pace",
  "部署 部署 bùshǔ deploy",
  "部位 部位 bùwèi part; section",
  "才干 才幹 cáigàn Talent",
  "财富 財富 cáifù wealth",
  "财务 財務 cáiwù financial affairs",
  "财政 財政 cáizhèng finance",
  "裁缝 裁縫 cáifeng Tailor",
  "裁判 裁判 cáipàn Referee",
  "裁员 裁員 cáiyuán Layoffs",
  "采购 採購 cǎigòu Purchase",
  "采集 採集 cǎijí gather; collect",
  "采纳 採納 cǎinà accept",
  "彩票 彩票 cǎipiào lottery",
  "参谋 參謀 cānmóu Staff officer",
  "参照 參考 cānzhào refer to",
  "残酷 殘酷 cánkù cruel",
  "残留 殘留 cánliú Residual",
  "残忍 殘忍 cánrěn brutal",
  "灿烂 燦爛 cànlàn splendid",
  "舱 艙 cāng cabin",
  "苍白 蒼白 cāngbái pale",
  "仓促 倉促 cāngcù Hasty",
  "仓库 倉庫 cāngkù Warehouse",
  "操劳 操勞 cāoláo work hard",
  "操练 操練 cāoliàn drill; practice",
  "操纵 操縱 cāozòng control",
  "操作 操作 cāozuò operation",
  "嘈杂 嘈雜 cáozá noisy",
  "草案 草案 cǎo'àn draft",
  "草率 草率 cǎoshuài cursory; jerry",
  "策划 策劃 cèhuà plan; hatch; plot",
  "策略 策略 cèlüè tactic; policy",
  "测量 測量 cèliáng measure",
  "侧面 側面 cèmiàn side; flank",
  "层出不穷 層出不窮 céngchūbùqióng emerge in endlessly",
  "层次 層次 céngcì gradation; arrangement",
  "差距 差距 chājù disparity; distance",
  "查获 查獲 cháhuò hunt down and seize; ferret out",
  "岔 岔 chà turn off; fork",
  "刹那 剎那 chànà Instant",
  "诧异 詫異 chàyì astonished",
  "柴油 柴油 cháiyóu diesel oil",
  "搀 攙 chān mix; mingle",
  "馋 饞 chán Greedy",
  "缠绕 纏繞 chánrào twine",
  "产业 產業 chǎnyè industry",
  "阐述 闡述 chǎnshù expatiate; expound",
  "颤抖 顫抖 chàndǒu Tremble",
  "猖狂 猖狂 chāngkuáng furious; savage",
  "昌盛 昌盛 chāngshèng Prosperity",
  "尝试 嘗試 chángshì attempt",
  "偿还 償還 chánghuán repay",
  "常年 常年 chángnián perennial",
  "常务 常務 chángwù day-to-day; standing",
  "场合 場合 chǎnghé occasion",
  "场面 場面 chǎngmiàn scene",
  "场所 場所 chǎngsuǒ place",
  "敞开 敞開 chǎngkāi Open wide",
  "倡导 倡導 chàngdǎo Advocate",
  "倡议 倡議 chàngyì Initiative",
  "畅通 暢通 chàngtōng unimpeded; unblocked",
  "畅销 暢銷 chàngxiāo sell well",
  "超级 超級 chāojí super",
  "超越 超越 chāoyuè Transcend",
  "钞票 鈔票 chāopiào Bank note",
  "潮流 潮流 cháoliú Trend",
  "潮湿 潮濕 cháoshī damp",
  "嘲笑 嘲笑 cháoxiào Ridicule",
  "撤退 提款 chètuì haul off",
  "撤销 撤銷 chèxiāo repeal; retract",
  "沉淀 沉澱 chéndiàn subside",
  "沉闷 沉悶 chénmèn oppressive; withdrawn",
  "沉思 沉思 chénsī Meditation",
  "沉重 沉重 chénzhòng heavy",
  "沉着 沉著 chénzhuó composed; cool headed",
  "陈旧 陳舊 chénjiù obsolete",
  "陈列 陳列 chénliè display",
  "陈述 陳述 chénshù present; state; mention",
  "称心如意 稱心如意 chènxīnrúyì As one wishes",
  "称号 稱號 chēnghào Title",
  "盛 盛 chéng fill",
  "橙 橙 chéng orange",
  "乘务员 乘務員 chéngwùyuán trainman; stewardess",
  "承办 承辦 chéngbàn Undertake",
  "承包 承包 chéngbāo Contract",
  "承诺 承諾 chéngnuò Promise",
  "城堡 城堡 chéngbǎo Castle",
  "成本 成本 chéngběn cost",
  "成交 成交 chéngjiāo Deal",
  "成天 成天 chéngtiān All day long",
  "成效 成效 chéngxiào Results, effects",
  "成心 成心 chéngxīn on purpose",
  "成员 成員 chéngyuán member",
  "惩罚 懲罰 chéngfá punish",
  "诚挚 誠摯 chéngzhì sincere; cordial; earnest",
  "澄清 澄清 chéngqīng clarify",
  "呈现 呈現 chéngxiàn Present",
  "秤 秤 chèng balance",
  "吃苦 吃苦 chīkǔ Hardship",
  "吃力 吃力 chīlì Sweaty",
  "迟缓 遲緩 chíhuǎn tardy; sluggish",
  "迟疑 遲疑 chíyí Hesitation",
  "持久 持久 chíjiǔ Lasting",
  "池塘 池塘 chítáng pool; pond",
  "赤道 赤道 chìdào equator",
  "赤字 赤字 chìzì deficit; red ink",
  "冲动 衝動 chōngdòng impulse",
  "冲击 衝擊 chōngjī To attack",
  "冲突 衝突 chōngtū conflict",
  "充当 充當 chōngdāng act as; serve as",
  "充沛 充沛 chōngpèi Abundant",
  "充实 充實 chōngshí Enrich",
  "充足 充足 chōngzú adequate",
  "崇拜 崇拜 chóngbài worship",
  "崇高 崇高 chónggāo lofty",
  "崇敬 崇敬 chóngjìng respect; revere",
  "重叠 重疊 chóngdié overlap",
  "重阳节 重陽節 Chóngyángjié Double Ninth Festival",
  "抽空 抽空 chōukòng make time",
  "筹备 籌備 chóubèi arrange; prepare",
  "踌躇 躊躇 chóuchú hesitate; boggle",
  "稠密 稠密 chóumì thick; dense",
  "丑恶 醜惡 chǒu'è ugly; filthy",
  "出路 出路 chūlù way out",
  "出卖 出賣 chūmài sell",
  "出色 出色 chūsè excellent; outstanding",
  "出身 畢業 chūshēn Birth",
  "出神 出神 chūshén Trance",
  "出息 出息 chūxi Good",
  "出洋相 出洋相 chūyángxiàng Make a fool",
  "初步 初步 chūbù preliminary",
  "储备 儲備 chǔbèi store",
  "储存 儲存 chǔcún Storage",
  "储蓄 儲蓄 chǔxù save up; bank",
  "处分 處分 chǔfèn prescription",
  "处境 處境 chǔjìng plight; situation",
  "处置 處置 chǔzhì treat; dispose",
  "触犯 觸犯 chùfàn offend; violate",
  "穿越 穿越 chuānyuè Pass through",
  "川流不息 川流不息 chuānliúbùxī flowing up in an endless stream",
  "船舶 船舶 chuánbó watercraft; ships",
  "传达 傳達 chuándá Convey",
  "传单 傳單 chuándān fly sheet; leaflet",
  "传授 傳授 chuánshòu initiate; teach",
  "喘气 喘氣 chuǎnqì Panting",
  "串 串 chuàn strand, cluster",
  "床单 床單 chuángdān Sheet",
  "创立 創立 chuànglì Found",
  "创新 創新 chuàngxīn innovate",
  "创业 創業 chuàngyè carve out",
  "创作 創作 chuàngzuò A literary creation",
  "吹牛 吹牛 chuīniú brag; boast",
  "吹捧 吹捧 chuīpěng flatter; puff",
  "锤 錘 chuí hammer",
  "垂直 垂直 chuízhí vertical",
  "纯粹 純粹 chúncuì pure",
  "纯洁 純潔 chúnjié pure",
  "词汇 詞彙 cíhuì vocabulary",
  "慈祥 慈祥 cíxiáng Kindly",
  "雌雄 雌雄 cíxióng male and female",
  "刺 刺 cì thorn",
  "次品 次品 cìpǐn defective goods",
  "次序 次序 cìxù order; sequence",
  "伺候 伺候 cìhou Wait",
  "丛 叢 cóng cluster",
  "从容不迫 從容不迫 cóngróngbúpò take one's time; calm and unhurried",
  "凑合 湊合 còuhuo gather together",
  "粗鲁 粗魯 cūlǔ rude",
  "窜 竄 cuàn Channeling",
  "摧残 摧殘 cuīcán devastate; wreck",
  "脆弱 脆弱 cuìruò fragile",
  "搓 搓 cuō Rub",
  "磋商 磋商 cuōshāng negotiate",
  "挫折 挫折 cuòzhé frustration",
  "搭 搭 dā to match, to take",
  "搭档 搭檔 dādàng partner",
  "搭配 搭配 dāpèi arrange; match",
  "答辩 答辯 dábiàn reply; answer",
  "答复 答复 dáfù Reply",
  "达成 達成 dáchéng Reach",
  "打包 打包 dǎbāo Pack",
  "打官司 打官司 dǎguānsi To engage in a lawsuit",
  "打击 打擊 dǎjī strike",
  "打架 打架 dǎjià Fight",
  "打量 打量 dǎliang look sb. up and down",
  "打猎 打獵 dǎliè Go hunting",
  "打仗 打仗 dǎzhàng To war",
  "大不了 大不了 dàbuliǎo Big deal",
  "大臣 該部 dàchén Minister",
  "大伙儿 大夥兒 dàhuǒr you all; everybody",
  "大厦 大廈 dàshà Large building",
  "大肆 大肆 dàsì Wantonly",
  "大体 通常 dàtǐ general",
  "大意 大意 dàyi Careless",
  "大致 大致 dàzhì roughly",
  "歹徒 歹徒 dǎitú gangster; mobster",
  "带领 帶領 dàilǐng lead",
  "代价 代價 dàijià cost",
  "代理 代理 dàilǐ agent",
  "逮捕 逮捕 dàibǔ Arrest",
  "怠慢 怠慢 dàimàn cold-shoulder",
  "担保 擔保 dānbǎo assure; hypothecate",
  "胆怯 膽怯 dǎnqiè coward, fear",
  "淡季 淡季 dànjì Low Season",
  "淡水 淡水 dànshuǐ fresh water",
  "蛋白质 蛋白質 dànbáizhì Protein",
  "诞辰 誕辰 dànchén Birthday",
  "诞生 誕生 dànshēng Be born",
  "当场 當場 dāngchǎng On the spot",
  "当初 當初 dāngchū Original",
  "当面 當面 dāngmiàn Face to face",
  "当前 當前 dāngqián current",
  "当事人 當事人 dāngshìrén client",
  "当务之急 當務之急 dāngwùzhījí A pressing matter of the moment",
  "当心 當心 dāngxīn Watch out",
  "当选 當選 dāngxuǎn be elected; come in",
  "党 黨 dǎng party",
  "档案 檔案 dàng'àn archives",
  "档次 檔次 dàngcì grade",
  "岛屿 島嶼 dǎoyǔ Islands",
  "倒闭 倒閉 dǎobì Collapse",
  "导弹 導彈 dǎodàn Missile",
  "导航 導航 dǎoháng navigate",
  "导向 導向 dǎoxiàng guide",
  "捣乱 搗亂 dǎoluàn Trouble",
  "稻谷 稻穀 dàogǔ Unhusked rice",
  "盗窃 盜竊 dàoqiè steal; pilfer",
  "be 是 not worth the candle; get more kicks than halfpence",
  "得力 得力 délì right-hand",
  "得天独厚 得天獨厚 détiāndúhòu Be richly endowed by nature",
  "得罪 得罪 dézuì Offend",
  "蹬 蹬 dēng thrust",
  "灯笼 燈籠 dēnglong lantern",
  "登陆 登陸 dēnglù disembark; land",
  "登录 登錄 dēnglù Sign in",
  "等级 等級 děngjí grade; rank",
  "瞪 瞪 dèng Stare",
  "堤坝 堤壩 dībà Dam",
  "敌视 敵視 díshì be hostile to; antagonize",
  "抵达 抵達 dǐdá Arrive",
  "抵抗 阻力 dǐkàng resistance",
  "抵制 抵制 dǐzhì resist; reject; repel",
  "递增 遞增 dìzēng Increasing",
  "地步 地步 dìbù condition; plight; situation; state; extent",
  "地势 地勢 dìshì Terrain",
  "地质 地質 dìzhì geology",
  "颠簸 顛簸 diānbǒ bump; welter",
  "颠倒 顛倒 diāndǎo Upside down",
  "点缀 點綴 diǎnzhuì Embellishment",
  "典礼 典禮 diǎnlǐ Ceremony",
  "典型 典型 diǎnxíng typical",
  "垫 墊 diàn pad",
  "电源 電源 diànyuán power supply",
  "奠定 奠定 diàndìng Establish",
  "惦记 惦記 diànjì Miss",
  "叼 叼 diāo hold in mouth",
  "雕刻 雕刻 diāokè carving",
  "雕塑 雕塑 diāosù Sculpture",
  "吊 吊 diào crane",
  "调动 調動 diàodòng transfer",
  "跌 跌 diē fall",
  "盯 盯 dīng stare at",
  "叮嘱 叮囑 dīngzhǔ urge again and again; exhort; warn",
  "定期 經常 dìngqī regular",
  "定义 定義 dìngyì Definition",
  "丢人 丟人 diūrén lose face",
  "丢三落四 丟三落四 diūsānlàsì Miss or lose this and that",
  "东道主 東道主 dōngdàozhǔ Host",
  "东张西望 東張西望 dōngzhāngxīwàng Look around",
  "董事长 董事長 dǒngshìzhǎng Chairman",
  "栋 棟 dòng Building (measure word)",
  "冻结 凍結 dòngjié Frozen",
  "洞穴 洞穴 dòngxué Cave",
  "动荡 動盪 dòngdàng turbulence",
  "动机 動機 dòngjī motivation",
  "动静 動靜 dòngjing Movement",
  "动力 動力 dònglì power, motivation",
  "动脉 動脈 dòngmài artery",
  "动身 動身 dòngshēn Leave",
  "动手 動手 dòngshǒu DIY",
  "动态 動態 dòngtài dynamic",
  "动员 動員 dòngyuán mobilization",
  "兜 兜 dōu Pocket",
  "陡峭 陡峭 dǒuqiào Steep",
  "斗争 鬥爭 dòuzhēng Struggle",
  "督促 督促 dūcù supervise and urge",
  "都市 城市 dūshì urban",
  "独裁 獨裁 dúcái autocracy",
  "毒品 毒品 dúpǐn narcotics",
  "赌博 賭博 dǔbó gambling",
  "堵塞 堵塞 dǔsè blocking",
  "杜绝 杜絕 dùjué Stop， ban",
  "端 端 duān end",
  "端午节 端午節 uānwǔjié The Dragon Boat Festival",
  "端正 端正 duānzhèng correct",
  "短促 短促 duǎncù very brief",
  "断定 斷定 duàndìng be sure; figure out",
  "断断续续 斷斷續續 duànduànxùxù off and on; intermittently",
  "断绝 斷絕 duànjué be sure; figure out",
  "堆积 堆積 duījī Accumulation",
  "对策 對策 duìcè countermeasure",
  "对称 對稱 duìchèn symmetrical",
  "对付 對付 duìfu deal with",
  "对抗 對抗 duìkàng Combat",
  "对立 對立 duìlì Opposition",
  "对联 對聯 duìlián Antithetical couplet",
  "对应 對應 duìyìng Corresponding",
  "对照 對照 duìzhào compare; collate",
  "兑换 兌換 duìhuàn exchange",
  "兑现 兌現 duìxiàn Cash",
  "队伍 隊伍 duìwu Ranks",
  "顿时 頓時 dùnshí Suddenly",
  "多元化 多樣化 duōyuánhuà Diversification",
  "哆嗦 哆嗦 duōsuo Shiver",
  "堕落 墮落 duòluò Degenerate",
  "额外 額外 éwài extra; additional",
  "恶心 噁心 ěxin disgusting",
  "恶化 惡化 èhuà deteriorate",
  "遏制 遏制 èzhì contain",
  "恩怨 恩怨 ēnyuàn Resentment",
  "而已 而已 éryǐ Nothing more",
  "耳环 耳環 ěrhuán Earrings",
  "二氧化碳 二氧化碳 èryǎnghuàtàn Carbon dioxide",
  "发布 發布 fābù Release",
  "发财 發財 fācái make a fortune; make a pile",
  "发呆 發呆 fādāi In a daze",
  "发动 發動 fādòng Launch",
  "发火 發火 fāhuǒ get angry",
  "发觉 發覺 fājué find",
  "发射 發射 fāshè launch",
  "发誓 發誓 fāshì swear",
  "发行 發行 fāxíng issue",
  "发炎 發炎 fāyán inflammation",
  "发扬 發揚 fāyáng carry forward",
  "发育 發育 fāyù Development, growth",
  "法人 公司 fǎrén juridical person",
  "番 禁令 fān Some",
  "繁华 繁華 fánhuá Bustling",
  "繁忙 繁忙 fánmáng busy",
  "繁体字 繁體字 fántǐzì the traditional Chinese character",
  "繁殖 繁殖 fánzhí Reproduction",
  "反驳 反駁 fǎnbó refute",
  "反常 反常 fǎncháng abnormal",
  "反倒 反倒 fǎndào Instead",
  "反动 反動 fǎndòng Reactionary",
  "反感 反感 fǎngǎn Disgusted",
  "反抗 反抗 fǎnkàng Resistance",
  "反馈 反饋 fǎnkuì feedback",
  "反面 反面 fǎnmiàn The other side",
  "反射 反射 fǎnshè echo; reflect",
  "反思 反思 fǎnsī Reflect",
  "反问 反問 fǎnwèn rhetorical question",
  "反之 反之 fǎnzhī on the contrary; whereas",
  "范畴 範疇 fànchóu category",
  "泛滥 氾濫 fànlàn Flood",
  "贩卖 販賣 fànmài Trafficking",
  "方位 方位 fāngwèi Position",
  "方言 方言 fāngyán dialect",
  "方针 方針 fāngzhēn policy",
  "防守 防守 fángshǒu Defense",
  "防疫 防疫 fángyì epidemic prevention",
  "防御 防禦 fángyù defense",
  "防止 防止 fángzhǐ Prevent",
  "防治 防治 fángzhì Prevention and cure",
  "纺织 紡織 fǎngzhī Spin",
  "放大 放大 fàngdà enlarge",
  "放射 輻射 fàngshè radiation",
  "放手 放手 fàngshǒu Let go",
  "非法 非法 fēifǎ illegal",
  "飞禽走兽 飛禽走獸 fēiqínzǒushòu Birds and animals",
  "飞翔 飛翔 fēixiáng flight",
  "飞跃 飛躍 fēiyuè leap",
  "肥沃 肥沃 féiwò fertile",
  "诽谤 誹謗 fěibàng slander; defame",
  "匪徒 匪徒 fěitú The bandits",
  "废除 廢除 fèichú Abolish",
  "废墟 廢墟 fèixū Ruins",
  "沸腾 沸騰 fèiténg boiling",
  "分辨 分辨 fēnbiàn Distinguish",
  "分寸 分寸 fēncùn Sense of propriety",
  "分红 分紅 fēnhóng bonus",
  "分解 分解 fēnjiě decompose",
  "分裂 分裂 fēnliè division",
  "分泌 分泌 fēnmì secretion",
  "分明 分明 fēnmíng clear",
  "分歧 分歧 fēnqí divergence",
  "分散 分散 fēnsàn Dispersed",
  "分手 分手 fēnshǒu Break up",
  "吩咐 吩咐 fēnfù Tell",
  "坟墓 墳墓 fénmù Grave",
  "粉末 粉 fěnmò powder",
  "粉色 粉色 fěnsè Pink",
  "粉碎 粉碎 fěnsuì smash",
  "分量 分量 fènliàng Weight",
  "风暴 風暴 fēngbào Storm",
  "风度 風度 fēngdù Manner",
  "风光 風光 fēngguāng Scenery",
  "风气 風氣 fēngqì atmosphere",
  "风趣 風趣 fēngqù Funny",
  "风土人情 風土人情 fēngtǔrénqíng Local customs and practices",
  "风味 風味 fēngwèi flavor",
  "封闭 封閉 fēngbì close",
  "封建 封建 fēngjiàn Feudal",
  "封锁 封鎖 fēngsuǒ blockade",
  "丰满 豐滿 fēngmǎn Plump",
  "丰盛 豐盛 fēngshèng rich; sumptuous",
  "丰收 豐收 fēngshōu Have bumper harvest",
  "锋利 鋒利 fēnglì sharp",
  "逢 逢 féng meet; come upon",
  "奉献 奉獻 fèngxiàn dedicate",
  "否决 否決 fǒujué veto; reject; overrule",
  "夫妇 夫婦 fūfù couple",
  "夫人 夫人 fūrén Madam",
  "敷衍 敷衍 fūyǎn play at",
  "幅度 幅度 fúdù range; extent",
  "服气 服氣 fúqì Be convinced",
  "符号 符號 fúhào Symbol",
  "福利 福利 fúlì welfare",
  "福气 福氣 fúqi good luck; felicity",
  "俘虏 俘虜 fúlǔ captive",
  "辐射 輻射 fúshè radiation",
  "腐败 腐敗 fǔbài corrupt",
  "腐烂 腐爛 fǔlàn Decay",
  "腐蚀 腐蝕 fǔshí corrosion",
  "腐朽 腐朽 fǔxiǔ Decadent",
  "辅助 輔助 fǔzhù auxiliary",
  "抚养 撫養 fǔyǎng Raise",
  "俯仰 俯仰 fǔyǎng pitch",
  "富裕 富裕 fùyù Affluent",
  "副 副 fù Vice-",
  "副作用 副作用 fùzuòyòng side effect",
  "负担 負擔 fùdān burden",
  "覆盖 覆蓋 fùgài overlay; cover with",
  "附和 附和 fùhè chime in with; come to heel",
  "附件 附件 fùjiàn Enclosure",
  "附属 附屬 fùshǔ attach appertain",
  "复活 復活 fùhuó Resurrection",
  "复兴 復興 fùxīng Revival",
  "腹泻 腹瀉 fùxiè diarrhea",
  "赋予 賦予 fùyǔ give",
  "改良 起色 gǎiliáng Improvement",
  "盖章 蓋章 gàizhāng Seal",
  "干旱 乾旱 gānhàn drought",
  "干扰 干擾 gānrǎo interfere",
  "干涉 干涉 gānshè interference",
  "干预 干預 gānyù intervene",
  "尴尬 尷尬 gāngà awkward",
  "甘心 甘心 gānxīn Willing",
  "感慨 感慨 gǎnkǎi Feeling",
  "感染 感染 gǎnrǎn Infected",
  "干劲 幹勁 gànjìn Drive",
  "纲领 綱領 gānglǐng Programme",
  "港口 港口 gǎngkǒu Port",
  "港湾 港灣 gǎngwān Harbour",
  "岗位 崗位 gǎngwèi post",
  "杠杆 槓桿 gànggǎn lever",
  "高超 高超 gāochāo outstanding; superb; excellent",
  "高潮 高潮 gāocháo climax",
  "高峰 高峰 gāofēng peak",
  "高考 高考 gāokǎo the exam for entering universities",
  "高明 高明 gāomíng brilliant; bright",
  "高尚 高尚 gāoshàng noble",
  "高涨 高漲 gāozhǎng Upsurge",
  "稿件 稿件 gǎojiàn manuscript",
  "告辞 告辭 gàocí Take leave",
  "告诫 告誡 gàojiè warn; caution",
  "割 百分比 gē cut",
  "搁 擱 gē Put aside",
  "疙瘩 疙瘩 gēda lump; pimple",
  "歌颂 歌頌 gēsòng Sing",
  "隔阂 隔閡 géhé Estrangement",
  "隔离 隔離 gélí quarantine",
  "格局 格局 géjú situation",
  "格式 格式 géshi format",
  "个体 個體 gètǐ individual",
  "各抒己见 各抒己見 gèshūjǐjiàn Each airs his own views",
  "根深蒂固 根深蒂固 gēnshēndìgù being deeply rooted; in grain",
  "根源 根源 gēnyuán root",
  "跟前 跟前 gēnqián In front of",
  "跟随 跟隨 gēnsuí follow",
  "跟踪 跟踪 gēnzōng run after; tail",
  "耕地 耕地 gēngdì Cultivated land",
  "更新 更新 gēngxīn renovate; renew",
  "更正 更正 gēngzhèng correct",
  "公安局 公安局 gōng'ānjú Bureau of public security",
  "公道 公道 gōngdao fair",
  "公告 公告 gōnggào Notice",
  "公关 公關 gōngguān public relations",
  "公民 公民 gōngmín citizen",
  "公婆 公婆 gōngpó Parents-in-law",
  "公然 公然 gōngrán to the teeth; under one's nose",
  "公认 公認 gōngrèn Accepted",
  "公式 官方 gōngshì formula",
  "公务 公務 gōngwù Official business",
  "公正 公正 gōngzhèng fair",
  "公证 公證 gōngzhèng Notarization",
  "供不应求 供不應求 gōngbúyìngqiú Demand exceeds supply",
  "供给 供給 gōngjǐ supply",
  "工夫 設備 gōngfu time",
  "工艺品 工藝品 gōngyìpǐn Arts and Crafts",
  "宫殿 宮殿 gōngdiàn Palace",
  "功课 功課 gōngkè lessons",
  "功劳 功勞 gōngláo credit",
  "功效 功效 gōngxiào Effect",
  "攻击 攻擊 gōngjī attack",
  "攻克 攻克 gōngkè Conquer",
  "恭敬 恭敬 gōngjìng dutiful; respectful",
  "巩固 鞏固 gǒnggù consolidate",
  "共和国 共和國 gònghéguó Republic",
  "共计 共計 gòngjì count up to; sum to",
  "共鸣 共鳴 gòngmíng resonance",
  "勾结 勾結 gōujié Collusion",
  "钩子 鉤子 gōuzi hook",
  "构思 構思 gòusī Design",
  "孤独 孤獨 gūdú lonely",
  "孤立 孤立 gūlì isolated",
  "辜负 辜負 gūfù Live up to",
  "姑且 姑且 gūqiě Tentatively",
  "古董 古董 gǔdǒng antique",
  "古怪 古怪 gǔguài cranky; wacky",
  "股东 股東 gǔdōng stockholder",
  "股份 股份 gǔfèn Shares",
  "鼓动 鼓動 gǔdòng Agitation",
  "骨干 骨幹 gǔgàn backbone",
  "固然 固然 gùrán Of course",
  "固有 特點 gùyǒu Inherent",
  "固执 固執 gùzhi stubborn",
  "顾虑 顧慮 gùlǜ misgive; misgiving",
  "顾问 顧問 gùwèn adviser",
  "故乡 故鄉 gùxiāng Hometown",
  "故障 故障 gùzhàng fault",
  "拐杖 拐杖 guǎizhàng cane",
  "关照 關照 guānzhào Take care of",
  "官方 官方 guānfāng by the government official",
  "观光 觀光 guānguāng Sightseeing",
  "管辖 管轄 guǎnxiá dominate; rule",
  "罐 罐 guàn pot",
  "贯彻 貫徹 guànchè implement",
  "灌溉 灌溉 guàngài irrigation",
  "惯例 慣例 guànlì convention",
  "光彩 光彩 guāngcǎi Brilliance",
  "光辉 光輝 guānghuī Glory",
  "光芒 光芒 guāngmáng Shine",
  "广阔 廣闊 guǎngkuò wide",
  "规范 規範 guīfàn criterion; rule",
  "规格 規格 guīgé standard; format",
  "规划 規劃 guīhuà Plan",
  "规章 規章 guīzhāng Rules",
  "归根到底 歸根到底 guīgēndàodǐ at all time and place",
  "归还 歸還 guīhuán return",
  "归纳 歸納 guīnà Induce",
  "轨道 軌道 guǐdào track",
  "跪 跪 guì kneel",
  "贵族 貴族 guìzú noble",
  "棍棒 棍棒 gùnbàng club; cudgel",
  "国防 國防 guófáng national defense",
  "国务院 國務院 guówùyuàn The State Council",
  "果断 果斷 guǒduàn decisive",
  "过度 過度 guòdù excessive",
  "过渡 過渡 guòdù transition",
  "过奖 過獎 guòjiǎng you flatter",
  "过滤 過濾 guòlǜ filter",
  "过失 過失 guòshī fault",
  "过问 過問 guòwèn Ask",
  "过瘾 過癮 guòyǐn Fun",
  "过于 過於 guòyú too; excessively",
  "嗨 嗨 hāi hi",
  "海拔 海拔 hǎibá altitude",
  "海滨 海濱 hǎibīn Seaside",
  "含糊 含糊 hánhu vague",
  "含义 含義 hányì signification; meanings",
  "寒暄 寒暄 hánxuān exchange of conventional greetings",
  "罕见 罕見 hǎnjiàn peculiar; rare",
  "捍卫 捍衛 hànwèi defend; guard",
  "航空 航空 hángkōng aviation",
  "航天 航天 hángtiān Space flight",
  "航行 航行 hángxíng Sail",
  "行列 行列 hángliè Ranks",
  "30 三十   豪华 háohuá luxury",
  "豪迈 豪邁 háomài Heroic",
  "毫米 毫米 háomǐ millimeter",
  "毫无 毫無 háowú nothing",
  "号召 號召 hàozhào call",
  "耗费 耗費 hàofèi cost",
  "好客 好客 hàokè Hospitable",
  "呵 呵 hē Oh",
  "和蔼 和藹 hé'ǎi Kindly",
  "和解 和解 héjiě compromise",
  "和睦 和睦 hémù harmony",
  "和气 和氣 héqi kind; polite",
  "和谐 和諧 héxié Harmonious",
  "合并 合併 hébìng merge",
  "合成 合成 héchéng Synthesis",
  "合乎 合乎 héhū accord with",
  "合伙 合夥 héhuǒ cooperate; join hands with",
  "合身 合身 héshēn Fit",
  "合算 加起來 hésuàn Cost-effective",
  "痕迹 痕跡 hénjì mark",
  "狠心 狠心 hěnxīn cruel hearted",
  "恨不得 恨不得 hènbude Hate not",
  "哼 哼 hēng Hum",
  "哄 哄 hōng fool",
  "烘 烘 hōng Bake",
  "轰动 轟動 hōngdòng make a sensation; make a stir",
  "红包 紅包 hóngbāo Red envelope",
  "宏观 宏觀 hóngguān Macroscopic",
  "宏伟 宏偉 hóngwěi grand",
  "洪水 洪水 hóngshuǐ Flood",
  "喉咙 喉嚨 hóulóng throat",
  "吼 吼 hǒu Roar",
  "后代 後代 hòudài Offspring",
  "后顾之忧 後顧之憂 hòugùzhīyōu Any menace from the rear",
  "后勤 後勤 hòuqín logistics",
  "候选 候選 hòuxuǎn candidate",
  "忽略 忽略 hūlüè ignore",
  "呼啸 呼嘯 hūxiào Whistling",
  "呼吁 呼籲 hūyù call on; appeal",
  "胡乱 胡亂 húluàn Casually",
  "湖泊 湖泊 húpō lake",
  "互联网 互聯網 hùliánwǎng Internet",
  "花瓣 花瓣 huābàn Petal",
  "华丽 華麗 huálì design",
  "华侨 華僑 huáqiáo overseas Chinese",
  "画蛇添足 畫蛇添足 huàshétiānzú Superfluous",
  "化肥 化肥 huàféi chemical fertilizer",
  "化石 化石 huàshí Fossil",
  "化验 化驗 huàyàn Test",
  "化妆 化妝 huàzhuāng prink; make up",
  "划分 劃分 huàfēn Divide",
  "话筒 話筒 huàtǒng Microphone",
  "怀孕 懷孕 huáiyùn become pregnant",
  "欢乐 歡樂 huānlè Happy",
  "还原 還原 huányuán reduction",
  "环节 環節 huánjié link",
  "缓和 緩和 huǎnhé To moderate",
  "患者 患者 huànzhě Patient",
  "荒凉 荒涼 huāngliáng Desolate",
  "荒谬 荒謬 huāngmiù ridiculous; nonsensical",
  "荒唐 荒唐 huāngtáng absurd",
  "慌忙 慌忙 huāngmáng Hurriedly",
  "黄昏 黃昏 huánghūn Dusk",
  "恍然大悟 恍然大悟 huǎngrándàwù See light suddenly",
  "挥霍 揮霍 huīhuò splurge; devour",
  "辉煌 輝煌 huīhuáng brilliant",
  "回报 回報 huíbào Return",
  "回避 躲避 huíbì obviate; slide over",
  "回顾 回顧 huígù review; look back",
  "回收 回收 huíshōu recovery",
  "悔恨 悔恨 huǐhèn Regret",
  "毁灭 毀滅 huǐmiè Ruin",
  "会晤 會晤 huìwù Meet",
  "汇报 匯報 huìbào report",
  "贿赂 賄賂 huìlù bribery",
  "昏迷 昏迷 hūnmí coma",
  "浑身 渾身 húnshēn All",
  "混合 混合 hùnhé blend",
  "混乱 混亂 hùnluàn confusion",
  "混淆 混淆 hùnxiáo confusion",
  "混浊 混濁 hùnzhuó Turbidity",
  "活该 活該 huógāi You deserves it",
  "活力 活力 huólì energy; vigor",
  "火箭 火箭 huǒjiàn rocket",
  "火焰 火焰 huǒyàn flame",
  "火药 火藥 huǒyào gunpowder",
  "货币 貨幣 huòbì currency",
  "或许 或許 huòxǔ maybe; probably",
  "基地 基地 jīdì base",
  "基金 基金 jījīn fund",
  "基因 基因 jīyīn gene",
  "机动 機動 jīdòng Maneuver",
  "机构 機構 jīgòu mechanism",
  "机关 機關 jīguān office",
  "机灵 機靈 jīling wise; clever",
  "机密 機密 jīmì Confidential",
  "机械 機械 jīxiè Mechanics",
  "机遇 機遇 jīyù Opportunity",
  "机智 機智 jīzhì tactful; resourceful",
  "激发 激發 jīfā inspire",
  "激励 激勵 jīlì inspirit",
  "激情 激情 jīqíng Passion",
  "饥饿 飢餓 jī'è hunger",
  "讥笑 譏笑 jīxiào fleer",
  "极端 極端 jíduān extreme",
  "极限 極限 jíxiàn limit",
  "即便 即便 jíbiàn even if",
  "即将 即將 jíjiāng soon",
  "级别 級別 jíbié level",
  "疾病 疾病 jíbìng disease",
  "嫉妒 嫉妒 jídù Envy",
  "及早 及早 jízǎo as soon as possible",
  "Be 是 anxious to achieve quick success and get instant benefits",
  "急剧 急劇 jíjù sharp",
  "急切 急切 jíqiè impatient eager; imperative",
  "急于求成 急於求成 jíyúqiúchéng Be anxious for success",
  "急躁 急躁 jízào Impatient",
  "籍贯 籍貫 jíguàn Place of origin",
  "集团 集團 jítuán group",
  "吉祥 吉祥 jíxiáng lucky; auspicious",
  "给予 給予 jǐyǔ give",
  "寄托 寄託 jìtuō place on; consign or commit",
  "继承 繼承 jìchéng inherit",
  "Carry 攜帶 forward the cause pioneered by one's predecessors and forge ahead into the future",
  "记性 記性 jìxing memory",
  "记载 記載 jìzǎi Record",
  "季度 季度 jìdù quarter (of a year)",
  "季军 季軍 jìjūn Third place",
  "计较 計較 jìjiào Regardless of",
  "忌讳 忌諱 jìhuì Taboo",
  "寂静 寂靜 jìjìng Silent",
  "纪要 紀要 jìyào summary",
  "技能 技能 jìnéng Skill",
  "技巧 技巧 jìqiǎo Skill",
  "迹象 跡象 jìxiàng Sign",
  "家常 家常 jiācháng the daily life of a family",
  "家伙 傢伙 jiāhuo Fellow",
  "家属 家屬 jiāshǔ family members",
  "家喻户晓 家喻戶曉 jiāyùhùxiǎo widely known",
  "加工 加工 jiāgōng machining",
  "加剧 加劇 jiājù exacerbate",
  "佳肴 佳餚 jiāyáo Delicacy",
  "夹杂 夾雜 jiāzá Inclusion",
  "假设 假設 jiǎshè in case of",
  "假使 假使 jiǎshǐ If",
  "坚定 堅定 jiāndìng Firm, steadfast",
  "坚固 堅固 jiāngù strong",
  "坚韧 堅韌 jiānrèn gritty; hard-bitten",
  "坚实 堅實 jiānshí solid",
  "坚硬 堅硬 jiānyìng hard",
  "监督 監督 jiāndū supervise",
  "监视 監視 jiānshì Monitor",
  "监狱 監獄 jiānyù Prison",
  "尖端 尖端 jiānduān top end",
  "艰难 艱難 jiānnán difficult",
  "兼职 兼職 jiānzhí Part-time job",
  "拣 揀 jiǎn Pick",
  "剪彩 剪彩 jiǎncǎi Ribbon-cutting",
  "检讨 檢討 jiǎntǎo A review",
  "检验 檢驗 jiǎnyàn test",
  "简化 簡化 jiǎnhuà predigest",
  "简陋 簡陋 jiǎnlòu simple and crude",
  "简体字 簡體字 jiǎntǐzì simplified character",
  "简要 簡要 jiǎnyào in brief",
  "溅 濺 jiàn splash",
  "鉴别 鑑別 jiànbié differentiate",
  "鉴定 鑑定 jiàndìng Appraisal",
  "鉴于 鑑於 jiànyú In view of the fact that",
  "间谍 間諜 jiàndié espionage",
  "间隔 間隔 jiàngé interval",
  "间接 間接 jiànjiē indirect",
  "见多识广 見多識廣 jiànduōshíguǎng Have great experience",
  "见解 見解 jiànjiě Opinion",
  "见闻 見聞 jiànwén Informative",
  "见义勇为 見義勇為 jiànyìyǒngwéi Do boldly what is righteous",
  "健全 健全 jiànquán sound",
  "践踏 踐踏 jiàntà override",
  "舰艇 艦艇 jiàntǐng Naval vessels",
  "将近 將近 jiāngjìn nearly",
  "将军 將軍 jiāngjūn General",
  "僵硬 僵硬 jiāngyìng stiff",
  "桨 槳 jiǎng propeller",
  "奖励 獎勵 jiǎnglì reward",
  "奖赏 獎賞 jiǎngshǎng reward",
  "降临 降臨 jiànglín become of; befall; arrive",
  "交叉 交叉 jiāochā intercross",
  "交代 交代 jiāodài hand over",
  "交涉 交涉 jiāoshè Negotiate",
  "交往 交往 jiāowǎng affiliate with",
  "交易 交易 jiāoyì transaction",
  "焦点 焦點 jiāodiǎn focus",
  "焦急 焦急 jiāojí anxious",
  "娇气 嬌氣 jiāoqì effeminate",
  "角落 角落 jiǎoluò corner",
  "搅拌 攪拌 jiǎobàn mix up",
  "缴纳 繳納 jiǎonà Pay",
  "教养 教養 jiàoyǎng train; upbringing; education",
  "较量 較量 jiàoliàng Contest",
  "皆 皆 jiē all",
  "接连 接連 jiēlián One after another",
  "阶层 階層 jiēcéng stratum",
  "揭发 揭發 jiēfā Expose",
  "揭露 揭露 jiēlù Expose",
  "节奏 節奏 jiézòu rhythm",
  "杰出 傑出 jiéchū outstanding",
  "结晶 結晶 jiéjīng result; finale",
  "结局 結局 jiéjú Ending",
  "结算 結算 jiésuàn Settlement",
  "竭尽全力 竭盡全力 jiéjìnquánlì Strain every nerve",
  "截至 截至 jiézhì By (time)",
  "解除 發布 jiěchú Relieve",
  "解雇 解僱 jiěgù fire",
  "解剖 解剖 jiěpōu anatomy",
  "解散 解散 jiěsàn dissolution",
  "解体 拆解 jiětǐ Disintegrate",
  "借鉴 借鑒 jièjiàn take example by",
  "借助 借助 jièzhù With the help of",
  "戒备 戒備 jièbèi Alert",
  "界限 界限 jièxiàn limit",
  "津津有味 津津有味 jīnjīnyǒuwèi Eat with appetite",
  "金融 金融 jīnróng Finance",
  "紧密 緊密 jǐnmì Close together",
  "紧迫 緊迫 jǐnpò urgent",
  "尽快 盡快 jǐnkuài as soon as possible",
  "锦绣前程 錦繡前程 jǐnxiùqiánchéng Bright future",
  "进而 進而 jìn'ér and then",
  "进攻 進攻 jìngōng attack",
  "进化 進化 jìnhuà evolution",
  "进展 進展 jìnzhǎn evolve; get along",
  "近来 近來 jìnlái recently",
  "近视 近視 jìnshì myopia",
  "浸泡 浸泡 jìnpào soak",
  "晋升 晉升 jìnshēng Promotion",
  "劲头 勁頭 jìntóu Momentum",
  "茎 莖 jīng stalk; stem",
  "精打细算 精打細算 jīngdǎxìsuàn pinch pennies",
  "精华 精華 jīnghuá elite; distillate",
  "精简 精簡 jīngjiǎn simplify; condense",
  "精密 精密 jīngmì exact; close",
  "精确 精確 jīngquè accurate; exact",
  "精通 精通 jīngtōng Master, be good at",
  "精心 精心 jīngxīn Elaborate",
  "精益求精 精益求精 jīngyìqiújīng keep improving",
  "精致 精緻 jīngzhì delicate",
  "经费 經費 jīngfèi funds",
  "经商 經商 jīngshāng be in business; trade",
  "经纬 經緯 jīngwěi longitude and latitude",
  "惊动 驚動 jīngdòng Disturb",
  "惊奇 驚奇 jīngqí Be surprised",
  "惊讶 驚訝 jīngyà surprised",
  "兢兢业业 兢兢業業 jīngjīngyèyè cautious and conscientious",
  "井 井 jǐng well",
  "警告 警告 jǐnggào warning",
  "警惕 警惕 jǐngtì Be vigilant",
  "颈椎 頸椎 jǐngzhuī cervical vertebra",
  "敬礼 敬禮 jìnglǐ Salute",
  "境界 境界 jìngjiè realm; extent reached",
  "竞赛 競賽 jìngsài competition",
  "竞选 競選 jìngxuǎn Campaign for",
  "镜头 鏡頭 jìngtóu Camera lens",
  "纠纷 糾紛 jiūfēn dissension; tangle",
  "纠正 糾正 jiūzhèng correct",
  "酒精 酒精 jiǔjīng alcohol",
  "救济 救濟 jiùjì redress; relief",
  "就近 就近 jiùjìn Nearby",
  "就业 就業 jiùyè take up an occupation",
  "就职 就職 jiùzhí Inauguration",
  "鞠躬 鞠躬 jūgōng Bow",
  "拘留 拘留 jūliú detain",
  "拘束 克制 jūshù constrained; ill at ease",
  "居住 居住 jūzhù live",
  "局部 局部 júbù local",
  "局面 局面 júmiàn situation",
  "局势 局勢 júshì Situation",
  "局限 局限 júxiàn limit; confine",
  "举动 舉動 jǔdòng Move",
  "举世闻名 舉世聞名 jǔshìwénmíng of world known; world-famous",
  "举世瞩目 舉世矚目 jǔshìzhǔmù attract worldwide attention",
  "举足轻重 舉足輕重 jǔzúqīngzhòng Play a decisive role",
  "咀嚼 咀嚼 jǔjué Chew",
  "沮丧 沮喪 jǔsàng depressed",
  "剧本 劇本 jùběn Script",
  "剧烈 劇烈 jùliè Severe",
  "聚精会神 聚精會神 jùjīnghuìshén Concentrate one's attention on",
  "据悉 據悉 jùxī it is reported",
  "决策 決策 juécè make policy",
  "觉悟 覺悟 juéwù consciousness",
  "觉醒 覺醒 juéxǐng rouse; awake",
  "绝望 絕望 juéwàng Despair",
  "军队 軍隊 jūnduì army",
  "卡通 卡通 kǎtōng Cartoon",
  "开采 開採 kāicǎi exploit (mine)",
  "开除 開除 kāichú Expel",
  "开阔 開闊 kāikuò open",
  "开朗 開朗 kāilǎng Optimistic",
  "开明 開明 kāimíng enlightened",
  "开辟 開闢 kāipì open up",
  "开水 開水 kāishuǐ Boiling water",
  "开拓 開拓 kāituò open up; exploit",
  "开展 開展 kāizhǎn Develop",
  "开支 開支 kāizhī expenditure",
  "刊登 刊登 kāndēng publish in a newspaper",
  "刊物 刊物 kānwù Publication",
  "勘探 勘探 kāntàn prospect for; prove up",
  "看待 看待 kàndài To view",
  "看望 看望 kànwàng visit",
  "慷慨 慷慨 kāngkǎi generous",
  "扛 扛 káng Carry",
  "考察 考察 kǎochá Investigate",
  "考古 考古 kǎogǔ Archaeology",
  "考核 考核 kǎohé examine; assess",
  "考验 考驗 kǎoyàn test",
  "靠拢 靠攏 kàolǒng Close to",
  "磕 磕 kē Knock",
  "颗粒 顆粒 kēlì Grain",
  "科目 科目 kēmù Subject",
  "渴望 渴望 kěwàng Yearn",
  "可观 可觀 kěguān considerable",
  "可口 可口 kěkǒu Delicious",
  "可恶 可惡 kěwù loathsome; hateful",
  "可笑 可笑 kěxiào ridiculous",
  "可行 可行 kěxíng feasible",
  "刻不容缓 刻不容緩 kèbùrónghuǎn Brook no delay",
  "课题 課題 kètí topic",
  "客户 客戶 kèhù Customer",
  "啃 啃 kěn Bite",
  "恳切 懇切 kěnqiè fair-spoken",
  "坑 坑 kēng pit",
  "空洞 空洞 kōngdòng empty",
  "空前绝后 空前絕後 kōngqiánjuéhòu Unprecedented",
  "空想 幻想 kōngxiǎng escapism; dream; phantasm",
  "空虚 空虛 kōngxū vain; empty",
  "孔 孔 kǒng hole",
  "恐吓 恐嚇 kǒnghè intimidate",
  "恐惧 恐懼 kǒngjù Fear",
  "空白 空白 kòngbái blank; vacancy",
  "空隙 空隙 kòngxì interspaced; lacuna",
  "口气 口氣 kǒuqì tone",
  "口腔 口腔 kǒuqiāng mouth; oral cavity",
  "口头 口頭 kǒutóu oral",
  "口音 口音 kǒuyīn accent",
  "枯竭 枯竭 kūjié Exhausted",
  "枯燥 枯燥 kūzào Boring",
  "苦尽甘来 苦盡甘來 kǔjìngānlái All sufferings have their reward",
  "挎 挎 kuà carry on the arm",
  "跨 跨 kuà Cross",
  "快活 快活 kuàihuo happy",
  "宽敞 寬敞 kuānchang spacious; commodious",
  "款待 款待 kuǎndài Entertain",
  "款式 款式 kuǎnshì style",
  "筐 住房 kuāng basket",
  "旷课 曠課 kuàngkè Absenteeism",
  "框架 框架 kuàngjià frame",
  "况且 況且 kuàngqiě moreover",
  "亏待 虧待 kuīdài Treat",
  "亏损 虧損 kuīsǔn loss",
  "昆虫 昆蟲 kūnchóng insect",
  "捆绑 捆綁 kǔnbǎng binding",
  "扩充 擴充 kuòchōng extend; enlarge",
  "扩散 擴散 kuòsàn spread",
  "扩张 擴張 kuòzhāng expand; outspread",
  "喇叭 喇叭 lǎba horn",
  "来历 來歷 láilì Origin",
  "来源 來源 láiyuán source",
  "栏目 欄目 lánmù column",
  "懒惰 懶惰 lǎnduò lazy",
  "狼狈 狼狽 lángbèi in sore straits; in a tight corner",
  "朗读 朗讀 lǎngdú Reading aloud",
  "捞 撈 lāo Fishing",
  "唠叨 嘮叨 láodao To nag",
  "牢固 牢固 láogù solid",
  "牢骚 牢騷 láosāo Complain",
  "乐趣 樂趣 lèqù pleasure",
  "乐意 樂意 lèyì Happy",
  "雷达 雷達 léidá radar",
  "类似 類似 lèisì Similar",
  "冷淡 冷淡 lěngdàn cool attitude",
  "冷酷 冷酷 lěngkù cool",
  "冷却 冷卻 lěngquè cooling",
  "愣 愣 lèng distracted",
  "黎明 黎明 límíng Dawn",
  "里程碑 里程碑 lǐchéngbēi Milepost",
  "礼节 禮節 lǐjié etiquette",
  "理睬 理睬 lǐcǎi Acknowledge",
  "理所当然 理所當然 lǐsuǒdāngrán go without saying; of course",
  "理直气壮 理直氣壯 lǐzhíqìzhuàng one is assured and bold with justice",
  "理智 理智 lǐzhì reasonable",
  "立场 立場 lìchǎng position",
  "立交桥 立交橋 lìjiāoqiáo Overpass",
  "立体 立體 lìtǐ Three-dimensional",
  "立足 立足 lìzú Based on the",
  "历代 歷代 lìdài past dynasties",
  "历来 歷來 lìlái always",
  "利害 利害 lìhài Interest",
  "利率 利率 lìlǜ interest rate",
  "力所能及 力所能及 lìsuǒnéngjí Do everything in one's power",
  "力图 力圖 lìtú Try to",
  "力争 力爭 lìzhēng Strive to",
  "例外 例外 lìwài exception",
  "连年 連年 liánnián in successive years",
  "连锁 連鎖 liánsuǒ chain",
  "连同 連同 liántóng together with",
  "联欢 聯歡 liánhuān Gala",
  "联络 聯絡 liánluò liaison",
  "联盟 聯盟 liánméng union",
  "联想 聯想 liánxiǎng association",
  "廉洁 廉潔 liánjié uncorrupted; clean-fingered",
  "良心 良心 liángxīn conscience",
  "晾 晾 liàng Dry",
  "谅解 諒解 liàngjiě understanding",
  "辽阔 遼闊 liáokuò Vast",
  "列举 列舉 lièjǔ list",
  "淋 淋 lín Shower",
  "临床 臨床 línchuáng clinical",
  "吝啬 吝嗇 lìnsè Stingy",
  "零星 零星 língxīng Sporadic",
  "凌晨 凌晨 língchén Before dawn",
  "灵感 靈感 línggǎn inspiration",
  "灵魂 靈魂 línghún soul",
  "灵敏 靈敏 língmǐn sensitive",
  "伶俐 伶俐 línglì Clever",
  "领会 領會 lǐnghuì Understand",
  "领事馆 領事館 lǐngshìguǎn Consulate",
  "领土 領土 lǐngtǔ territory",
  "领悟 領悟 lǐngwù Understand",
  "领先 領先 lǐngxiān keep ahead",
  "领袖 領袖 lǐngxiù leader",
  "溜 溜 liū Slip",
  "留恋 留戀 liúliàn be reluctant to leave",
  "留念 留念 liúniàn As a souvenir",
  "留神 留神 liúshén Watch",
  "流浪 流浪 liúlàng lead a vagrant life; rove; roam about",
  "流露 流露 liúlù reveal",
  "流氓 流氓 liúmáng rogue",
  "流通 流通 liútōng circulation",
  "聋哑 聾啞 lóngyǎ Deaf-mute",
  "隆重 隆重 lóngzhòng ceremonious",
  "垄断 壟斷 lǒngduàn monopoly",
  "笼罩 籠罩 lǒngzhào Shrouded",
  "搂 摟 lǒu Hug",
  "炉灶 爐灶 lúzào A kitchen stove",
  "轮船 輪船 lúnchuán Ship",
  "轮廓 輪廓 lúnkuò outline",
  "轮胎 輪胎 lúntāi tyre",
  "论坛 論壇 lùntán forum",
  "论证 論證 lùnzhèng Demonstration",
  "啰唆 囉唆 luōsuo troublesome, wordy",
  "螺丝钉 螺絲釘 luósīdīng Screw",
  "落成 落成 luòchéng Completion",
  "落实 落實 luòshí put into effect",
  "络绎不绝 絡繹不絕 luòyìbùjué Go and fro in constant streams",
  "屡次 屢次 lǚcì Repeatedly",
  "履行 履行 lǚxíng Perform",
  "掠夺 掠奪 lüèduó plunder",
  "略微 略微 lüèwēi slightly",
  "麻痹 麻痺 mábì lull; blunt; paralysis",
  "麻木 麻木 mámù numbness",
  "麻醉 麻醉 mázuì narcosis",
  "码头 碼頭 mǎtóu wharf",
  "埋伏 埋伏 máifú Ambush",
  "埋没 埋沒 máimò immerse oneself in",
  "埋葬 埋葬 máizàng bury",
  "迈 邁 mài Wallace",
  "脉搏 脈搏 màibó pulse",
  "埋怨 埋怨 mányuàn Complain",
  "慢性 慢性 mànxìng chronic",
  "漫长 漫長 màncháng Very long",
  "漫画 漫畫 mànhuà Cartoon",
  "蔓延 蔓延 mànyán spread; creep",
  "忙碌 忙碌 mánglù Be busy",
  "茫茫 茫茫 mángmáng vast; boundless",
  "茫然 茫然 mángrán Blank",
  "盲目 盲目 mángmù blind",
  "冒充 冒充 màochōng Posing",
  "茂盛 茂盛 màoshèng Lush",
  "枚 片 méi measure word for medal",
  "没辙 沒轍 méizhé have no idea",
  "媒介 媒介 méijiè agent; medium",
  "媒体 媒體 méitǐ media",
  "美观 美觀 měiguān Beautiful",
  "美满 美滿 měimǎn happy; perfect",
  "美妙 美妙 měimiào wonderful",
  "门诊 門診 ménzhěn Outpatient Department",
  "蒙 蒙 méng cover, encounter",
  "萌芽 萌芽 méngyá bud; sprout",
  "猛烈 猛烈 měngliè violent",
  "梦想 夢想 mèngxiǎng Dream",
  "眯 瞇 mī take a nap",
  "弥补 彌補 míbǔ remedy; offset",
  "弥漫 瀰漫 mímàn permeate; fill the air",
  "迷惑 麻煩 míhuò puzzle; delude",
  "迷人 迷人 mírén charming",
  "迷失 迷失 míshī maze; wilder",
  "迷信 迷信 míxìn superstition",
  "密度 密度 mìdù density",
  "密封 密封 mìfēng Seal up",
  "免得 免得 miǎndé lest",
  "免疫 免疫 miǎnyì immune",
  "勉励 勉勵 miǎnlì Encourage",
  "勉强 勉強 miǎnqiǎng reluctantly",
  "面貌 面貌 miànmào face",
  "面子 面子 miànzi prestige; face",
  "描绘 描繪 miáohuì describe; portray",
  "渺小 渺小 miǎoxiǎo Tiny",
  "蔑视 蔑視 mièshì disparage; scorn",
  "灭亡 滅亡 mièwáng perish",
  "民间 民間 mínjiān nongovernmental",
  "民用 民用 mínyòng civil",
  "敏感 敏感 mǐngǎn Sensitive",
  "敏捷 敏捷 mǐnjié agile",
  "敏锐 敏銳 mǐnruì keen",
  "明明 明明 míngmíng Obviously",
  "名次 名次 míngcì Ranking",
  "名额 名額 míng'é Places",
  "名副其实 名副其實 míngfùqíshí Be worthy of the name",
  "名誉 名譽 míngyù reputation",
  "命名 命名 mìngmíng call; nominate",
  "摸索 摸索 mōsuǒ fumble; grope",
  "膜 膜 mó membrane",
  "摩擦 摩擦 mócā rub; scrape",
  "磨合 磨合 móhé running-in",
  "模范 模範 mófàn model",
  "模式 模式 móshì mode; style",
  "模型 模型 móxíng Model",
  "魔鬼 魔鬼 móguǐ devil; demon",
  "魔术 魔術 móshù Magic",
  "抹杀 抹殺 mǒshā write off; obliterate",
  "莫名其妙 莫名其妙 mòmíng-qímiào without rhyme or reason",
  "默默 默默 mòmò silently",
  "墨水儿 墨水兒 mòshuǐr book learning",
  "谋求 謀求 móuqiú seek",
  "模样 模樣 múyàng Appearance",
  "母语 母語 mǔyǔ Mother tongue",
  "目睹 目睹 mùdǔ witness; see with one's eyes",
  "目光 目光 mùguāng Eye",
  "沐浴 沐浴 mùyù Bath",
  "拿手 拿手 náshǒu Good",
  "纳闷儿 納悶兒 nàmènr feel puzzle",
  "耐用 耐用 nàiyòng durable",
  "难得 難得 nándé rare",
  "难堪 難堪 nánkān Embarrassed",
  "难免 難免 nánmiǎn Unavoidable",
  "难能可贵 難能可貴 nánnéngkěguì Praiseworthy for one's excellent conduct",
  "恼火 惱火 nǎohuǒ angry; take fire",
  "内涵 內涵 nèihán connotation",
  "内幕 內幕 nèimù Insider",
  "内在 內在 nèizài inherent",
  "能量 能量 néngliàng energy",
  "嗯 嗯 en Well",
  "拟定 擬定 nǐdìng study out",
  "年度 年度 niándù year",
  "捏 捏 niē Pinch",
  "拧 擰 níng Screw",
  "凝固 凝固 nínggù freezing",
  "凝聚 凝聚 níngjù condensation",
  "凝视 凝視 níngshì gaze; stare",
  "宁肯 寧肯 nìngkěn would rather than",
  "宁愿 寧願 nìngyuàn would rather",
  "纽扣儿 鈕扣兒 niǔkòur button",
  "扭转 扭轉 niǔzhuǎn Reverse",
  "农历 農曆 nónglì Lunar calendar",
  "奴隶 奴隸 núlì slave",
  "挪 挪 nuó move; shift",
  "虐待 虐待 nüèdài To abuse",
  "哦 哦 o Oh",
  "殴打 毆打 ōudǎ beat up; hit; drub",
  "欧洲 歐洲 Ōuzhōu Europe",
  "呕吐 嘔吐 ǒutù vomit",
  "趴 趴 pā Lie",
  "排斥 排斥 páichì exclude",
  "排除 排除 páichú eliminate; remove; debar",
  "排放 排放 páifàng discharge",
  "徘徊 徘徊 páihuái wander",
  "派别 派別 pàibié faction; group",
  "派遣 調度 pàiqiǎn send; dispatch",
  "攀登 攀登 pāndēng Climb",
  "盘旋 盤旋 pánxuán convolute; hover",
  "畔 畔 pàn bank, side",
  "判决 判決 pànjué Sentence",
  "庞大 龐大 pángdà enormous",
  "抛弃 拋棄 pāoqì throw over; abandon; discard",
  "泡沫 泡沫 pàomò bubble; froth",
  "培训 培訓 péixùn Train",
  "培育 培育 péiyù Cultivation",
  "配备 配備 pèibèi Equipment",
  "配偶 配偶 pèi'ǒu consort; mate",
  "配套 配套 pèitào form a complete set",
  "盆地 盆地 péndì basin",
  "烹饪 烹飪 pēngrèn cooking",
  "捧 捧 pěng Holding",
  "劈 劈 pī split",
  "批发 批發 pīfā wholesale",
  "批判 批評 pīpàn critique",
  "疲惫 疲憊 píbèi tired out; exhausted",
  "疲倦 疲倦 píjuàn Tired",
  "皮革 皮革 pígé leather",
  "屁股 屁股 pìgu Butt",
  "譬如 譬如 pìrú for example",
  "偏差 偏差 piānchā error; deviation",
  "偏见 偏見 piānjiàn prejudice",
  "偏僻 偏僻 piānpì out of the way; devious; outlying",
  "偏偏 偏偏 piānpiān Just",
  "片断 片斷 piànduàn Fragment",
  "片刻 片刻 piànkè a while; a moment",
  "飘扬 飄揚 piāoyáng Flying",
  "漂浮 漂浮 piāofú Float",
  "拼搏 拼搏 pīnbó go all out in work",
  "拼命 拼命 pīnmìng Try my best",
  "频繁 頻繁 pínfán frequently",
  "频率 頻率 pínlǜ frequency",
  "贫乏 貧乏 pínfá poor; lacking indigent",
  "贫困 貧困 pínkùn Poor",
  "品尝 品嚐 pǐncháng Taste",
  "品德 品德 pǐndé Character",
  "品行 品行 pǐnxíng conduct",
  "品质 品質 pǐnzhì quality",
  "平凡 平凡 píngfán ordinary",
  "平面 平面 píngmiàn plane",
  "平坦 平坦 píngtǎn flat",
  "平行 平行 píngxíng Parallel",
  "平原 平原 píngyuán plain",
  "评估 評估 pínggū evaluate",
  "评论 評論 pínglùn comment",
  "屏障 屏障 píngzhàng wall; barrier",
  "坡 坡 pō slope",
  "泼 潑 pō Splash",
  "颇 頗 pō quite; pretty",
  "破例 破例 pòlì Make an exception",
  "迫不及待 迫不及待 pòbùjídài Unable to hold oneself back",
  "迫害 迫害 pòhài persecution",
  "魄力 魄力 pòlì Courage",
  "扑 撲 pū Flutter",
  "铺 鋪 pū spread",
  "普及 普及 pǔjí Universal",
  "朴实 樸實 pǔshí simple",
  "瀑布 瀑布 pùbù Waterfall",
  "期望 期望 qīwàng Expect",
  "期限 期限 qīxiàn term",
  "欺负 欺負 qīfu bully",
  "欺骗 欺騙 qīpiàn Deception",
  "凄凉 淒涼 qīliáng Desolate",
  "奇妙 奇妙 qímiào wonderful",
  "旗袍 旗袍 qípáo cheongsam",
  "旗帜 旗幟 qízhì flag",
  "齐全 齊全 qíquán complete; all ready",
  "齐心协力 齊心協力 qíxīn-xiélì Make concerted efforts",
  "歧视 歧視 qíshì discrimination",
  "起草 起草 qǐcǎo Draft",
  "起初 起初 qǐchū at first",
  "起伏 起伏 qǐfú undulate",
  "起哄 起哄 qǐhòng kick up a row",
  "起码 起碼 qǐmǎ Minimum, at least",
  "起义 起義 qǐyì Uprising",
  "起源 起源 qǐyuán origin",
  "启程 啟程 qǐchéng set out",
  "启示 啟示 qǐshì enlightenment",
  "启事 啟事 qǐshì Notice",
  "乞丐 乞丐 qǐgài Beggar",
  "岂有此理 豈有此理 qǐyǒu-cǐlǐ outrageous; preposterous",
  "器材 器材 qìcái equipment",
  "器官 器官 qìguān organ",
  "气概 氣概 qìgài Spirit",
  "气功 氣功 qìgōng Qigong (a system of breathing technique)",
  "气魄 氣魄 qìpò Verve",
  "气色 氣色 qìsè Look",
  "气势 氣勢 qìshì vigor",
  "气味 氣味 qìwèi smell",
  "气象 氣象 qìxiàng Meteorological",
  "气压 氣壓 qìyā pressure",
  "迄今为止 迄今為止 qìjīn-wéizhǐ So far",
  "掐 掐 qiā Pinch",
  "恰当 恰當 qiàdàng appropriate",
  "恰到好处 恰到好處 qiàdàohǎochù just right",
  "恰巧 恰巧 qiàqiǎo Just",
  "洽谈 洽談 qiàtán talk over with",
  "牵扯 牽扯 qiānchě Involved",
  "牵制 牽制 qiānzhì hold down",
  "千方百计 千方百計 qiānfāng-bǎijì Make every attempt",
  "签订 簽訂 qiāndìng conclude and sign",
  "签署 簽署 qiānshǔ sign; affix to; subscribe",
  "迁就 遷就 qiānjiù indulge",
  "迁徙 遷徙 qiānxǐ migrate",
  "谦逊 謙遜 qiānxùn Modest",
  "前景 前景 qiánjǐng prospect",
  "前提 前提 qiántí precondition",
  "潜力 潛力 qiánlì potential",
  "潜水 潛水 qiánshuǐ Diving",
  "潜移默化 潛移默化 qiányí-mòhuà Influence character by environment",
  "谴责 譴責 qiǎnzé condemn; accuse; censure",
  "强制 強制 qiángzhì force; oblige",
  "抢劫 搶劫 qiǎngjié Robbery",
  "抢救 搶救 qiǎngjiù rescue",
  "强迫 強迫 qiǎngpò Force",
  "桥梁 橋樑 qiáoliáng bridge",
  "翘 翹 qiào Alice",
  "锲而不舍 鍥而不捨 qiè'érbùshě Keep on carving",
  "切实 切實 qièshí practical",
  "亲热 親熱 qīnrè Affectionate",
  "亲身 親身 qīnshēn Personally",
  "侵犯 侵犯 qīnfàn Violation",
  "钦佩 欽佩 qīnpèi admire",
  "勤俭 勤儉 qínjiǎn hardworking and thrifty",
  "勤恳 勤懇 qínkěn earnest and assiduous",
  "氢 氫 qīng hydrogen",
  "轻而易举 輕而易舉 qīng'éryìjǔ It 's a piece of cake",
  "清澈 清澈 qīngchè clear",
  "清晨 清晨 qīngchén Early morning",
  "清除 清除 qīngchú Eliminate",
  "清洁 清潔 qīngjié clean",
  "清理 清理 qīnglǐ Clear",
  "清晰 清晰 qīngxī clear",
  "清醒 清醒 qīngxǐng Sober",
  "清真 清真 qīngzhēn Muslim",
  "倾听 傾聽 qīngtīng Listen for",
  "倾向 傾向 qīngxiàng inclination",
  "倾斜 傾斜 qīngxié tilt",
  "晴朗 晴朗 qínglǎng sunny",
  "情报 情報 qíngbào intelligence",
  "情节 情節 qíngjié plot",
  "情理 情理 qínglǐ Reason",
  "情形 情形 qíngxíng Situation",
  "请柬 請柬 qǐngjiǎn Invitation card",
  "请教 請教 qǐngjiào Consult",
  "请示 請示 qǐngshì For instructions",
  "请帖 請帖 qǐngtiě Invitation",
  "丘陵 丘陵 qiūlíng hill",
  "区分 區分 qūfēn Distinguish",
  "区域 區域 qūyù region",
  "屈服 屈服 qūfú submit; give in; bend",
  "曲折 曲折 qūzhé Tortuous",
  "驱逐 驅逐 qūzhú drive out; banish",
  "渠道 渠道 qúdào channel",
  "取缔 取締 qǔdì Ban",
  "曲子 曲子 qǔzi Tune",
  "趣味 愛好 qùwèi Interest",
  "圈套 圈套 quāntào trap",
  "全局 全局 quánjú Overall situation",
  "全力以赴 全力以赴 quánlìyǐfù do one's level best; go all out",
  "权衡 權衡 quánhéng Balance",
  "权威 權威 quánwēi authority",
  "权益 權益 quányì Rights and interests",
  "拳头 拳頭 quántou fist",
  "犬 狗 quǎn dog",
  "缺口 缺口 quēkǒu breach; gap",
  "缺席 缺席 quēxí Absent",
  "缺陷 缺陷 quēxiàn defect",
  "瘸 瘸 qué Lame",
  "确保 確保 quèbǎo ensure",
  "确立 確立 quèlì establish",
  "确切 確切 quèqiè exact; definite",
  "确信 確信 quèxìn Sure",
  "群众 群眾 qúnzhòng The masses",
  "染 染 rǎn dye",
  "让步 讓步 ràngbù give in; concede to",
  "饶恕 饒恕 ráoshù Forgive",
  "扰乱 擾亂 rǎoluàn Disturb",
  "惹祸 惹禍 rěhuò Trouble",
  "热泪盈眶 熱淚盈眶 rèlèi-yíngkuàng one's eyes brimming with tears",
  "热门 熱門 rèmén Hot",
  "人道 人道 réndào Humanity",
  "人格 人格 réngé personality",
  "人工 人工 réngōng artificial",
  "人家 人家 rénjiā family",
  "人间 人間 rénjiān Human world",
  "人士 人士 rénshì Personage",
  "61 61  人为 rénwéi artificial",
  "人性 人性 rénxìng human nature",
  "人质 人質 rénzhì Hostage",
  "仁慈 仁慈 réncí Kind",
  "忍耐 忍耐 rěnnài Exercise patience",
  "忍受 忍受 rěnshòu bear",
  "认定 認定 rèndìng cognizance",
  "认可 認可 rènkě certificate; ratify",
  "任命 任命 rènmìng Appointment",
  "任性 任性 rènxìng Wayward",
  "任意 任意 rènyì Arbitrarily",
  "任重道远 任重道遠 rènzhòng-dàoyuǎn Take a heavy burden and embark on a long road",
  "仍旧 仍舊 réngjiù still",
  "日新月异 日新月異 rìxīn-yuèyì Change rapidly",
  "日益 日益 rìyì increasingly",
  "融洽 融洽 róngqià harmonious",
  "溶解 解 róngjiě dissolve; melt",
  "容貌 容貌 róngmào appearance",
  "容纳 容納 róngnà accommodate; contain; hold",
  "容器 容器 róngqì container",
  "容忍 容忍 róngrěn tolerate",
  "揉 揉 róu Knead",
  "柔和 柔和 róuhé soft",
  "弱点 弱點 ruòdiǎn weakness",
  "若干 若干 ruògān a certain number or amount",
  "撒谎 撒謊 sāhuǎng Lie",
  "腮 腮 sāi Cheek",
  "三角 三角 sānjiǎo triangle",
  "散文 散文 sǎnwén Prose",
  "散布 散佈 sànbù spread",
  "散发 散發 sànfā Emission",
  "丧失 喪失 sàngshī lose",
  "嫂子 嫂子 sǎozi Sister-in-law",
  "色彩 色彩 sècǎi color",
  "刹车 剎車 shāchē brake",
  "啥 啥 shá what",
  "筛选 篩選 shāixuǎn screen",
  "山脉 山脈 shānmài Mountain range",
  "闪烁 閃爍 shǎnshuò Twinkle",
  "擅长 擅長 shàncháng Be good at",
  "擅自 擅自 shànzì do sth, without authorization",
  "商标 商標 shāngbiāo trademark",
  "伤脑筋 傷腦筋 shāngnǎojīn troublesome",
  "上级 上級 shàngjí Superior",
  "上进心 上進心 shàngjìnxīn Desire to advance",
  "上任 上任 shàngrèn take up an official post",
  "上瘾 上癮 shàngyǐn Addiction",
  "上游 上游 shàngyóu Upper reaches",
  "捎 捎 shāo take along sth. to sb",
  "梢 梢 shāo end; tip",
  "哨 哨 shào whistle",
  "奢侈 奢侈 shēchǐ luxurious",
  "设立 設立 shèlì Establish",
  "设想 設想 shèxiǎng imagine， conceive",
  "设置 設置 shèzhì Set up",
  "社区 社區 shèqū Community",
  "涉及 涉及 shèjí Involve",
  "摄取 攝取 shèqǔ absorb",
  "摄氏度 攝氏度 shèshìdù Centigrade",
  "深奥 深奧 shēn'ào profound",
  "深沉 深沉 shēnchén deep",
  "深情厚谊 深情厚誼 shēnqíng-hòuyì Profound sentiments of friendship",
  "申报 申報 shēnbào declare",
  "绅士 紳士 shēnshì gentleman",
  "呻吟 呻吟 shēnyín moan",
  "神奇 神奇 shénqí Magical",
  "神气 神氣 shénqì Air, expression",
  "神情 神情 shénqíng Look",
  "神色 神色 shénsè expression; look",
  "神圣 神聖 shénshèng sacred",
  "神态 神態 shéntài expression",
  "神仙 神仙 shénxiān supernatural being; immortal; fairy",
  "审查 審查 shěnchá Examination",
  "审理 審理 shěnlǐ hear; try (law)",
  "审美 審美 shěnměi taste",
  "审判 審判 shěnpàn Trial",
  "渗透 滲透 shèntòu Infiltration",
  "慎重 慎重 shènzhòng careful",
  "生存 生存 shēngcún Existence",
  "生机 生機 shēngjī vitality",
  "生理 生理 shēnglǐ Physiology",
  "生疏 生疏 shēngshū Strange",
  "生态 生態 shēngtài ecology",
  "生物 生物 shēngwù Biology",
  "生效 生效 shēngxiào Take effect",
  "生锈 生鏽 shēngxiù Rust",
  "生育 生育 shēngyù Birth",
  "牲畜 牲畜 shēngchù livestock",
  "声明 聲明 shēngmíng statement",
  "声势 聲勢 shēngshì impetus; momentum",
  "声誉 聲譽 shēngyù reputation",
  "省会 省會 shěnghuì provincial capital",
  "盛产 盛產 shèngchǎn abound in; teem with",
  "盛开 盛開 shèngkāi In full bloom",
  "盛情 盛情 shèngqíng boundless hospitality",
  "盛行 盛行 shèngxíng Prevalence",
  "胜负 勝負 shèngfù victory and defeat",
  "失误 失誤 shīwù An error",
  "失踪 失踪 shīzōng disappear",
  "师范 師範 shīfàn Normal school",
  "施加 施加 shījiā Exert",
  "施展 施展 shīzhǎn Display",
  "尸体 屍體 shītǐ body; cadaver",
  "拾 拾 shí pick up, collect",
  "十足 十足 shízú 100 percent",
  "识别 識別 shíbié Distinguish",
  "时差 時差 shíchā time difference",
  "时常 時常 shícháng often",
  "时而 時而 shí'ér from time to time; now ... now ...",
  "时光 時光 shíguāng time",
  "时机 時機 shíjī Opportunity",
  "时事 時事 shíshì current affairs",
  "时装 時裝 shízhuāng fashion dress",
  "实惠 實惠 shíhuì substantial",
  "实力 實力 shílì Strength",
  "实施 實施 shíshī Implementation",
  "实事求是 實事求是 shíshìqiúshì Seek truth from facts",
  "实质 實質 shízhì essence",
  "石油 石油 shíyóu petroleum",
  "使命 使命 shǐmìng Mission",
  "是非 無論如何 shìfēi right and wrong; quarrel; dispute",
  "试图 試圖 shìtú Try",
  "试验 試驗 shìyàn test",
  "势必 勢必 shìbì Certainly will",
  "势力 勢力 shìlì Power",
  "世代 代 shìdài generation",
  "世界观 世界觀 shìjièguān World outlook",
  "示范 示範 shìfàn lead the way; demonstrate",
  "示威 示威 shìwēi Demonstration",
  "示意 示意 shìyì hint，signal",
  "释放 釋放 shìfàng release",
  "事故 事故 shìgù Accident",
  "事迹 事蹟 shìjì Deed， story",
  "事件 事件 shìjiàn Event",
  "事态 事態 shìtài situation",
  "事务 事務 shìwù affair",
  "事项 事項 shìxiàng Matter",
  "事业 事業 shìyè career",
  "适宜 適宜 shìyí suitable",
  "视力 視力 shìlì Vision",
  "视线 視線 shìxiàn sight",
  "视野 視野 shìyě View",
  "逝世 逝世 shìshì Death",
  "收藏 收藏 shōucáng Collection",
  "收缩 收縮 shōusuō shrink",
  "收益 收益 shōuyì income; profit",
  "收音机 收音機 shōuyīnjī radio",
  "手法 手法 shǒufǎ technique",
  "手势 手勢 shǒushì gesture",
  "手艺 手藝 shǒuyì craft; handicraft",
  "首要 首要 shǒuyào chief; principal",
  "守护 守護 shǒuhù Guard",
  "受罪 受罪 shòuzuì Suffer",
  "授予 授予 shòuyǔ grant",
  "书法 書法 shūfǎ Calligraphy",
  "书籍 書籍 shūjí book",
  "书记 書記 shūjì secretary",
  "书面 書面 shūmiàn in written form",
  "输入 輸入 shūrù import; input",
  "舒畅 舒暢 shūchàng Happy, entirely free from worry",
  "疏忽 疏忽 shūhū neglect",
  "数 數 shǔ to count",
  "竖 豎 shù vertical",
  "束 束 shù beam",
  "束缚 束縛 shùfù Shackles",
  "树立 樹立 shùlì Establish",
  "数额 數額 shù'é Amount",
  "数目 數目 shùmù Number",
  "耍 耍 shuǎ Play",
  "衰老 衰老 shuāilǎo Be senile, grow old",
  "衰退 衰退 shuāituì decline",
  "率领 率領 shuàilǐng Lead",
  "涮火锅 涮火鍋 shuànhuǒguō have hotpot",
  "双胞胎 雙胞胎 shuāngbāotāi Horse hooves",
  "爽快 爽快 shuǎngkuài Frank",
  "水利 水利 shuǐlì Water conservancy",
  "水龙头 水龍頭 shuǐlóngtóu Water tap",
  "水泥 水泥 shuǐní cement",
  "司法 司法 sīfǎ judicial",
  "司令 司令 sīlìng commander",
  "思念 思念 sīniàn miss",
  "思索 思索 sīsuǒ Thinking",
  "思维 思維 sīwéi thinking",
  "思绪 思緒 sīxù Thoughts",
  "私自 私自 sīzì Secretly",
  "斯文 斯文 sīwen Gentle",
  "死亡 死亡 sǐwáng death",
  "四肢 四肢 sìzhī limb",
  "肆无忌惮 肆無忌憚 sìwújìdàn Act recklessly and care for nobody",
  "饲养 飼養 sìyǎng Raise",
  "耸 聳 sǒng Shrug",
  "艘 艘 sōu ship",
  "搜索 搜索 sōusuǒ search",
  "苏醒 甦醒 sūxǐng Wake up",
  "俗话 俗話 súhuà common saying",
  "塑造 塑造 sùzào Model",
  "素食主义 素食主義 sùshízhǔyì Vegetarian",
  "素质 素質 sùzhì quality",
  "诉讼 訴訟 sùsòng litigation",
  "算了 算了 suànle Forget it",
  "算数 算術 suànshù Count",
  "随即 隨即 suíjí immediately",
  "随身 隨身 suíshēn Carry on",
  "随手 隨手 suíshǒu Readily",
  "随意 隨意 suíyì random; casual",
  "岁月 歲月 suìyuè Years",
  "隧道 隧道 suìdào Tunnel",
  "损坏 損壞 sǔnhuài damage",
  "索赔 索賠 suǒpéi Claim demage",
  "索性 索性 suǒxìng Simply",
  "塌 塌 tā collapse",
  "踏实 踏實 tāshi earnest, steady and sure",
  "台风 颱風 táifēng Typhoon",
  "太空 太空 tàikōng Space",
  "泰斗 泰斗 tàidǒu leading authority",
  "瘫痪 癱瘓 tānhuàn paralysis",
  "贪婪 貪婪 tānlán Greedy",
  "贪污 貪污 tānwū corruption",
  "摊儿 攤兒 tānr stall",
  "弹性 彈性 tánxìng elastic",
  "坦白 坦白 tǎnbái Frank",
  "探测 探測 tàncè Probe",
  "探索 探索 tànsuǒ explore",
  "探讨 探討 tàntǎo discuss; probe into",
  "探望 探望 tànwàng Visit",
  "叹气 嘆氣 tànqì Sigh",
  "糖葫芦 糖葫蘆 tánghúlu Tomatoes on sticks",
  "倘若 倘若 tǎngruò If",
  "掏 掏 tāo Dig",
  "滔滔不绝 滔滔不絕 tāotāobùjué dash along; give it mouth",
  "陶瓷 陶瓷 táocí ceramics",
  "淘气 淘氣 táoqì naughty",
  "淘汰 淘汰 táotài eliminate",
  "讨价还价 討價還價 tǎojiàhuánjià bargain",
  "特长 特長 tècháng Specialty",
  "特定 具體 tèdìng given",
  "特色 特色 tèsè characteristic",
  "提拔 提拔 tíbá elevate",
  "提炼 提煉 tíliàn abstract; refine",
  "提示 提示 tíshì hint",
  "提议 提議 tíyì proposal",
  "题材 題材 tícái theme",
  "体谅 體諒 tǐliàng understand; allow for",
  "体面 體面 tǐmiàn Respectable",
  "体系 體系 tǐxì system",
  "天才 天才 tiāncái genius",
  "天伦之乐 天倫之樂 tiānlúnzhīlè The happiness of a family union",
  "天然气 天然氣 tiānránqì Natural gas",
  "天生 天生 tiānshēng Born",
  "天堂 天堂 tiāntáng heaven",
  "天文 天文 tiānwén Astronomy",
  "田径 田徑 tiánjìng Athletics",
  "舔 舔 tiǎn lick",
  "挑剔 挑剔 tiāoti Fastidious",
  "条款 條款 tiáokuǎn clause",
  "条理 條理 tiáolǐ Organized",
  "条约 條約 tiáoyuē Treaty",
  "调和 調和 tiáohé Reconcile",
  "调剂 調劑 tiáojì relief; temper",
  "调节 調節 tiáojié adjust",
  "调解 調解 tiáojiě mediate",
  "调料 調料 tiáoliào Seasoning",
  "挑拨 挑撥 tiǎobō Provoke",
  "挑衅 挑釁 tiǎoxìn provocation",
  "跳跃 跳躍 tiàoyuè jump",
  "停泊 停泊 tíngbó Anchor",
  "停顿 停頓 tíngdùn pause",
  "停滞 停滯 tíngzhì stagnation",
  "亭子 亭子 tíngzi Pavilion",
  "挺拔 挺拔 tǐngbá Tall and straight",
  "通货膨胀 通貨膨脹 tōnghuòpéngzhàng Inflation",
  "通俗 通俗 tōngsú popular, common",
  "通用 通用 tōngyòng currency",
  "铜矿 銅礦 tóngkuàng copper mine",
  "同胞 同胞 tóngbāo Compatriot",
  "同志 同志 tóngzhì comrade",
  "童话 童話 tónghuà fairy tale",
  "Take 採取 into consideration both needs of the state and the interests of the collectives",
  "统计 統計 tǒngjì Statistics",
  "统统 統統 tǒngtǒng All",
  "投机 投機 tóujī Speculation",
  "投票 表決 tóupiào vote",
  "投降 投降 tóuxiáng surrender",
  "投掷 投擲 tóuzhì Throw",
  "秃 禿 tū Bald",
  "突破 突破 tūpò Breach",
  "图案 圖案 tú'àn pattern",
  "徒弟 徒弟 túdì Apprentice",
  "途径 途徑 tújìng channel",
  "涂抹 塗抹 túmǒ Apply",
  "土壤 土壤 tǔrǎng soil",
  "团结 團結 tuánjié Unite",
  "团体 團體 tuántǐ group",
  "团圆 團圓 tuányuán reunion",
  "推测 推測 tuīcè Speculation",
  "推翻 推翻 tuīfān overthrow",
  "推理 推理 tuīlǐ reasoning",
  "推论 推論 tuīlùn inference",
  "推销 推銷 tuīxiāo promote sales",
  "吞咽 吞嚥 tūnyàn Swallow",
  "脱离 脫離 tuōlí Be divorced from",
  "拖延 拖延 tuōyán delay",
  "托运 托運 tuōyùn Consignment",
  "妥当 合理 tuǒdang appropriate",
  "妥善 妥善 tuǒshàn proper",
  "妥协 妥協 tuǒxié compromise",
  "椭圆 橢圓 tuǒyuán Ellipse",
  "唾沫 唾沫 tuòmo Spit",
  "挖掘 挖掘 wājué Excavate",
  "娃娃 娃娃 wáwa A doll",
  "瓦解 瓦解 wǎjiě collapse",
  "哇 哇 wa wow",
  "歪曲 歪曲 wāiqū distort",
  "外表 外表 wàibiǎo appearance",
  "外行 外行 wàiháng Layman",
  "外界 外界 wàijiè outside",
  "外向 外向 wàixiàng Extroversion",
  "丸 丸 wán pill",
  "完备 完備 wánbèi complete, maturity",
  "完毕 完畢 wánbì Complete",
  "玩弄 玩弄 wánnòng Play with; flirt with",
  "玩意儿 玩意兒 wányìr Thing",
  "顽固 頑固 wángù stubborn",
  "顽强 頑強 wánqiáng Tenacious",
  "挽回 挽回 wǎnhuí To save",
  "挽救 挽救 wǎnjiù save",
  "惋惜 惋惜 wǎnxī Sorry",
  "万分 萬分 wànfēn Extremely",
  "往常 往常 wǎngcháng The usual",
  "往事 往事 wǎngshì Past",
  "网络 網絡 wǎngluò network",
  "妄想 妄想 wàngxiǎng mirage; deliria",
  "微不足道 微不足道 wēibùzúdào Not worth mentioning",
  "微观 微觀 wēiguān Microcosmic",
  "威风 威風 wēifēng Prestige",
  "威力 威力 wēilì power",
  "威望 威望 wēiwàng prestige",
  "威信 威信 wēixìn Authority",
  "危机 危機 wēijī crisis",
  "违背 違背 wéibèi Violation",
  "维持 維持 wéichí maintain",
  "维生素 維生素 wéishēngsù Vitamin",
  "维修 維修 wéixiū Repair",
  "唯独 唯獨 wéidú Only",
  "为难 為難 wéinán Embarrassed",
  "为期 為期 wéiqī by a definite date",
  "为首 為首 wéishǒu To be led by",
  "委员 委員 wěiyuán Committee member",
  "伪造 偽造 wěizào Forge",
  "胃口 胃口 wèikǒu Appetite",
  "位于 位於 wèiyú Be located",
  "未免 未免 wèimiǎn Rather",
  "畏惧 畏懼 wèijù Fear",
  "卫星 衛星 wèixīng satellite",
  "慰问 慰問 wèiwèn Condolences",
  "温带 溫帶 wēndài The temperate zone",
  "温和 溫和 wēnhé mild",
  "文凭 文憑 wénpíng diploma",
  "文物 文物 wénwù Cultural relic",
  "文献 文獻 wénxiàn literature",
  "文雅 文雅 wényǎ Elegant",
  "文艺 文藝 wényì literature",
  "问世 問世 wènshì The advent of",
  "窝 窩 wō nest",
  "乌黑 烏黑 wūhēi Black",
  "污蔑 污衊 wūmiè Slander",
  "诬陷 誣陷 wūxiàn Framed",
  "无比 無比 wúbǐ extremely",
  "无偿 無償 wúcháng for free",
  "无耻 無恥 wúchǐ shameless",
  "无从 無從 wúcóng have no way",
  "无动于衷 無動於衷 wúdòngyúzhōng Completely indifferent",
  "无非 無非 wúfēi Nothing more than",
  "无精打采 無精打采 wújīngdǎcǎi Be in the blues",
  "无可奉告 無可奉告 wúkěfènggào No comment",
  "无可奈何 無可奈何 wúkěnàihé Feel helpless",
  "无赖 無賴 wúlài Rogue",
  "无理取闹 無理取鬧 wúlǐqǔnào Make trouble out of nothing",
  "无能为力 無能為力 wúnéngwéilì Incapable of action",
  "无穷无尽 無窮無盡 wúqióngwújìn Inexhaustible",
  "无微不至 無微不至 wúwēibúzhì Considerate right down to the most trivial detail",
  "无忧无虑 無憂無慮 wúyōuwúlǜ Be light of heart from care",
  "无知 無知 wúzhī ignorance",
  "舞蹈 舞蹈 wǔdǎo Dance",
  "武侠 武俠 wǔxiá Martial arts",
  "武装 武裝 wǔzhuāng Armed forces",
  "侮辱 侮辱 wǔrǔ insult",
  "勿 勿 wù Not",
  "务必 務必 wùbì must",
  "务实 務實 wùshí Pragmatic",
  "误差 誤差 wùchā error",
  "误解 誤解 wùjiě misunderstand",
  "物美价廉 物美價廉 wùměijiàlián High quality and inexpensive",
  "物资 物資 wùzī goods and materials",
  "溪 溪 xī brook",
  "膝盖 膝蓋 xīgài knee",
  "熄灭 熄滅 xīmiè crush out; go out",
  "吸取 吸取 xīqǔ Draw",
  "昔日 昔日 xīrì The past",
  "牺牲 犧牲 xīshēng sacrifice",
  "夕阳 夕陽 xīyáng Setting sun",
  "媳妇 媳婦 xífu daughter-in-law",
  "习俗 習俗 xísú custom",
  "袭击 襲擊 xíjī A surprise attack",
  "喜闻乐见 喜聞樂見 xǐwénlèjiàn Love to see and hear",
  "喜悦 喜悅 xǐyuè Joy",
  "系列 系列 xìliè series",
  "细胞 細胞 xìbāo Cells",
  "细菌 細菌 xìjūn Bacteria",
  "细致 細緻 xìzhì careful",
  "霞 霞 xiá rosy clouds",
  "狭隘 狹隘 xiá'ài narrow and limited",
  "狭窄 狹窄 xiázhǎi Narrow",
  "峡谷 峽谷 xiágǔ Canyon",
  "夏令营 夏令營 xiàlìngyíng Summer camp",
  "下属 下屬 xiàshǔ subordinate",
  "先进 先進 xiānjìn advanced",
  "先前 先前 xiānqián previously",
  "鲜明 鮮明 xiānmíng distinct",
  "掀起 掀起 xiānqǐ Set off",
  "纤维 纖維 xiānwéi fibre",
  "弦 弦 xián string",
  "嫌 不愉快 xián dislike and avoid",
  "嫌疑 嫌疑 xiányí suspicion",
  "闲话 閒話 xiánhuà gossip",
  "贤惠 賢惠 xiánhuì Virtuous",
  "衔接 銜接 xiánjiē joint",
  "显著 显著 xiǎnzhù remarkable",
  "现场 現場 xiànchǎng scene",
  "现成 現成 xiànchéng Ready-made",
  "现状 現狀 xiànzhuàng Present situation",
  "宪法 憲法 xiànfǎ Constitution",
  "陷害 陷害 xiànhài Framed",
  "陷入 陷入 xiànrù fall into",
  "馅儿 餡兒 xiànr Filling",
  "线索 線索 xiànsuǒ Clue",
  "相差 相差 xiāngchà Differ",
  "相等 相等 xiāngděng Equal",
  "相辅相成 相輔相成 xiāngfǔxiāngchéng Exist side by side and play a part together",
  "相应 相應 xiāngyìng Corresponding",
  "镶嵌 鑲嵌 xiāngqiàn Set, inlay",
  "乡镇 鄉鎮 xiāngzhèn Town",
  "想方设法 想方設法 xiǎngfāngshèfǎ Try various devices to",
  "响亮 響亮 xiǎngliàng loud and clear",
  "响应 響應 xiǎngyìng response",
  "巷 巷 xiàng Alley",
  "向导 嚮導 xiàngdǎo Guide",
  "向来 向來 xiànglái always",
  "向往 嚮往 xiàngwǎng Yearn for",
  "消除 消除 xiāochú eliminate",
  "消毒 消毒 xiāodú Disinfection",
  "消防 消防 xiāofáng Fire control",
  "消耗 消耗 xiāohào consume",
  "消极 消極 xiāojí negative",
  "销毁 銷毀 xiāohuǐ destroy by melting or burning",
  "小心翼翼 小心翼翼 xiǎoxīnyìyì With great care",
  "效益 效益 xiàoyì benefit",
  "肖像 肖像 xiàoxiàng portrait",
  "携带 攜帶 xiédài carry",
  "协会 協會 xiéhuì association",
  "协商 協商 xiéshāng consult",
  "协议 協議 xiéyì Agreement",
  "协助 協助 xiézhù assist",
  "写作 寫作 xiězuò writing",
  "屑 垃圾 xiè Chip",
  "谢绝 謝絕 xièjué decline with thanks",
  "泄露 洩露 xièlòu leakage",
  "泄气 洩氣 xièqì Feel discouraged",
  "新陈代谢 新陳代謝 xīnchéndàixiè The new supersedes the old",
  "新郎 新郎 xīnláng Groom",
  "新娘 新娘 xīnniáng Bride",
  "新颖 新穎 xīnyǐng novel",
  "心得 心得 xīndé Experience",
  "心灵 心靈 xīnlíng Heart",
  "心态 心態 xīntài mentality",
  "心疼 心疼 xīnténg Distressed",
  "心血 心血 xīnxuè Blood",
  "心眼儿 心眼兒 xīnyǎnr Heart, mind, intention",
  "辛勤 辛勤 xīnqín Hardworking",
  "欣慰 欣慰 xīnwèi Gratified",
  "欣欣向荣 欣欣向榮 xīnxīnxiàngróng Thriving",
  "薪水 薪水 xīnshui salary",
  "信赖 信賴 xìnlài trust; rely",
  "信念 信念 xìnniàn belief",
  "信仰 信仰 xìnyǎng Faith",
  "信誉 信譽 xìnyù reputation",
  "腥 腥 xīng Fishy",
  "兴隆 興隆 xīnglóng Prosperous",
  "兴旺 興旺 xīngwàng Prosperous",
  "行政 行政 xíngzhèng Administration",
  "形态 形態 xíngtài Form",
  "刑事 刑事 xíngshì criminal",
  "性感 性感 xìnggǎn sexy",
  "性命 性命 xìngmìng life",
  "性能 性能 xìngnéng performance",
  "性情 性情 xìngqíng Temperament",
  "幸好 幸好 xìnghǎo fortunately",
  "兴高采烈 興高采烈 xìnggāocǎiliè Be jubilant",
  "兴致勃勃 興致勃勃 xìngzhìbóbó Be in the best of spirits",
  "胸怀 胸懷 xiōnghuái mind",
  "胸膛 胸膛 xiōngtáng chest",
  "凶恶 兇惡 xiōng'è Ferocious",
  "凶手 兇手 xiōngshǒu Murderer",
  "雄厚 雄厚 xiónghòu Abundant",
  "修复 修復 xiūfù repair",
  "修建 修建 xiūjiàn build",
  "修理 修復 xiūlǐ repair",
  "羞耻 羞恥 xiūchǐ Shame",
  "休养 休養 xiūyǎng Rest",
  "绣 繡 xiù embroidery",
  "嗅觉 嗅覺 xiùjué smell",
  "虚假 虛假 xūjiǎ false sham",
  "虚荣 虛榮 xūróng vanity",
  "虚伪 虛偽 xūwěi hypocrisy",
  "需求 需求 xūqiú demand",
  "须知 須知 xūzhī Notice",
  "许可 許可 xǔkě Permit",
  "酗酒 酗酒 xùjiǔ Alcohol",
  "畜牧 畜牧 xùmù Animal husbandry",
  "序言 序言 xùyán Preface",
  "宣誓 宣誓 xuānshì Swear an oath",
  "宣扬 宣揚 xuānyáng Preach",
  "悬挂 懸掛 xuánguà suspension",
  "悬念 懸念 xuánniàn suspense",
  "悬崖峭壁 懸崖峭壁 xuányáqiàobì Steep cliff",
  "旋律 旋律 xuánlǜ Melody",
  "旋转 旋轉 xuánzhuǎn rotate",
  "选拔 選拔 xuǎnbá Selection",
  "选手 選手 xuǎnshǒu Player",
  "削弱 削弱 xuēruò weaken; cripple",
  "学历 學歷 xuélì education degree",
  "学说 學說 xuéshuō theory",
  "学位 學位 xuéwèi Academic degree",
  "雪上加霜 雪上加霜 xuěshàngjiāshuāng One disaster after another",
  "血压 血壓 xuèyā blood pressure",
  "熏陶 熏陶 xūntáo The influence of",
  "循环 循環 xúnhuán loop",
  "循序渐进 循序漸進 xúnxùjiànjìn follow in order and advance step by step",
  "巡逻 巡邏 xúnluó patrol",
  "寻觅 尋覓 xúnmì Looking for",
  "押金 押金 yājīn deposit",
  "压迫 壓迫 yāpò Oppression",
  "压岁钱 壓歲錢 yāsuìqián Lucky money in new year",
  "压缩 壓縮 yāsuō compress",
  "压抑 壓抑 yāyì oppress; overbear",
  "压榨 壓榨 yāzhà press",
  "压制 壓制 yāzhì Suppress",
  "亚军 亞軍 yàjūn Runner-up",
  "烟花爆竹 煙花爆竹 yānhuābàozhú Fireworks and firecrackers",
  "淹没 淹沒 yānmò Flood",
  "延期 延期 yánqī Delay",
  "延伸 延伸 yánshēn extend",
  "延续 延續 yánxù continue",
  "严寒 嚴寒 yánhán Severe cold",
  "严禁 嚴禁 yánjìn Strictly prohibit",
  "严峻 嚴峻 yánjùn stern; serious; harsh",
  "严厉 嚴厲 yánlì severe",
  "严密 嚴密 yánmì tight",
  "沿海 沿海 yánhǎi coastal",
  "言论 言論 yánlùn speech",
  "炎热 炎熱 yánrè Scorching hot",
  "岩石 岩石 yánshí rock",
  "演变 演變 yǎnbiàn evolution",
  "演讲 演講 yǎnjiǎng speech",
  "演习 演習 yǎnxí exercise",
  "演绎 演繹 yǎnyì deduction",
  "演奏 性能 yǎnzòu Play",
  "掩盖 掩蓋 yǎngài cover up",
  "掩护 掩護 yǎnhù cover",
  "掩饰 掩飾 yǎnshì Conceal",
  "眼光 眼光 yǎnguāng Eye",
  "眼色 眼色 yǎnsè meaningful glance",
  "眼神 眼神 yǎnshén expression in one's eyes",
  "眼下 眼下 yǎnxià Right now",
  "验收 驗收 yànshōu Check before acceptance",
  "验证 驗證 yànzhèng Verification",
  "厌恶 厭惡 yànwù Hate",
  "氧气 氧氣 yǎngqì oxygen",
  "样品 樣品 yàngpǐn sample",
  "摇摆 搖擺 yáobǎi swing",
  "摇滚 搖滾 yáogǔn Rock",
  "摇晃 搖晃 yáohuàng Shake",
  "遥控 遙控 yáokòng remote control",
  "遥远 遙遠 yáoyuǎn distant",
  "谣言 謠言 yáoyán Rumor",
  "咬牙切齿 咬牙切齒 yǎoyáqièchǐ Gnash the teeth in anger",
  "要不然 要不然 yàoburán Otherwise",
  "要点 要點 yàodiǎn Main points",
  "要命 要命 yàomìng kill, extremely",
  "要素 元素 yàosù Essential factor",
  "耀眼 耀眼 yàoyǎn dazzling",
  "野蛮 野蠻 yěmán barbarism",
  "野心 野心 yěxīn ambition",
  "一流 一流 yīliú First-class",
  "依次 依次 yīcì successively",
  "依旧 依舊 yījiù still",
  "依据 依據 yījù Basis",
  "依靠 依靠 yīkào rely on; depend on",
  "依赖 依賴 yīlài rely on",
  "依托 依托 yītuō rely on",
  "衣裳 衣裳 yīshang clothes",
  "一度 一度 yídù once",
  "一贯 一貫 yíguàn consistent",
  "一律 一律 yílǜ all and singular",
  "一目了然 一目了然 yímùliǎorán Stick out a mile",
  "一向 一向 yíxiàng Always",
  "一再 一再 yízài repeatedly",
  "遗产 遺產 yíchǎn heritage",
  "遗传 遺傳 yíchuán inheritance",
  "遗留 遺留 yíliú Left",
  "遗失 遺失 yíshī Loss",
  "疑惑 疑惑 yíhuò doubt; disbelieve",
  "仪器 儀器 yíqì instrument",
  "仪式 儀式 yíshì Ceremony",
  "以便 以便 yǐbiàn so that",
  "以免 以免 yǐmiǎn in case",
  "以往 以往 yǐwǎng Past",
  "以至 以至 yǐzhì So that; down to",
  "以致 以致 yǐzhì so that",
  "亦 亦 yì also",
  "翼 翼 yì Wing",
  "一帆风顺 一帆風順 yìfānfēngshùn Everything is going smoothly",
  "一举两得 一舉兩得 yìjǔliǎngdé Shoot two hawks with one arrow",
  "一如既往 一如既往 yìrújìwǎng As always",
  "一丝不苟 一絲不苟 yìsībùgǒu Be strict in one's demands",
  "异常 異常 yìcháng abnormal",
  "意料 意料 yìliào expect; anticipate",
  "意识 意識 yìshí consciousness",
  "意图 意圖 yìtú intention",
  "意味着 意思是衣服 yìwèizhe Signify",
  "意向 意向 yìxiàng intention",
  "意志 意志 yìzhì will",
  "毅力 毅力 yìlì Will",
  "毅然 毅然 yìrán Resolutely; firmly",
  "抑制 抑制 yìzhì Inhibition",
  "阴谋 陰謀 yīnmóu conspiracy",
  "音响 音響 yīnxiǎng sound",
  "隐蔽 隱蔽 yǐnbì Concealment",
  "隐患 隱患 yǐnhuàn hidden danger",
  "隐瞒 隱瞞 yǐnmán hide",
  "隐私 隱私 yǐnsī Privacy",
  "隐约 隱約 yǐnyuē Vaguely",
  "引导 引導 yǐndǎo guide",
  "引擎 引擎 yǐnqíng engine",
  "引用 引用 yǐnyòng Quote",
  "饮食 飲食 yǐnshí diet",
  "印刷 印花 yìnshuā printing",
  "婴儿 嬰兒 yīng'ér baby",
  "英明 英明 yīngmíng wise",
  "英勇 英勇 yīngyǒng heroic",
  "迎面 迎面 yíngmiàn Head-on; in one`s face",
  "盈利 盈利 yínglì profit",
  "荧屏 熒屏 yíngpíng screen",
  "应酬 應酬 yìngchou Entertainment",
  "应邀 應邀 yìngyāo Invited",
  "拥护 擁護 yōnghù support",
  "拥有 擁有 yōngyǒu Have",
  "庸俗 庸俗 yōngsú philistine; tacky",
  "勇于 勇於 yǒngyú The courage to",
  "永恒 永恆 yǒnghéng Eternal",
  "涌现 湧現 yǒngxiàn The emergence of",
  "踊跃 踴躍 yǒngyuè Enthusiastically",
  "用功 用功 yònggōng Diligent",
  "用户 用戶 yònghù user",
  "优胜劣汰 優勝劣汰 yōushèngliètài Survival of the fittest",
  "优先 優先 yōuxiān first",
  "优异 優異 yōuyì excellent",
  "优越 優越 yōuyuè superior",
  "忧郁 憂鬱 yōuyù heavy-hearted",
  "油腻 油膩 yóunì greasy",
  "油漆 油漆 yóuqī paint",
  "犹如 猶如 yóurú like; as if; just as",
  "有条不紊 有條不紊 yǒutiáobùwěn Everything in good order and well arranged",
  "幼稚 幼稚 yòuzhì Immature",
  "诱惑 誘惑 yòuhuò tempt; lure",
  "愚蠢 愚蠢 yúchǔn stupid",
  "愚昧 愚昧 yúmèi Foolish",
  "舆论 輿論 yúlùn public opinion",
  "渔民 漁民 yúmín Fisherman",
  "与日俱增 與日俱增 yǔrìjùzēng Grow with each passing day",
  "羽绒服 羽絨服 yǔróngfú Down Jackets",
  "予以 予以 yǔyǐ Give",
  "愈 愈 yù more",
  "预料 預料 yùliào Expect",
  "预期 預期 yùqī expect; anticipate",
  "预赛 預賽 yùsài preliminary match",
  "预算 預算 yùsuàn budget",
  "预先 預先 yùxiān beforehand",
  "预言 預言 yùyán Prophesy",
  "预兆 預兆 yùzhào Omen",
  "欲望 慾望 yùwàng desire",
  "寓言 寓言 yùyán fable",
  "冤枉 冤枉 yuānwang Wrong; treat unjustly",
  "元首 元首 yuánshǒu The heads of a state",
  "元素 元素 yuánsù element",
  "元宵节 元宵節 yuánxiāojié The Lantern Festival",
  "圆满 圓滿 yuánmǎn Satisfactorily",
  "原告 原告 yuángào accuser",
  "原理 原理 yuánlǐ principle",
  "原始 原始 yuánshǐ Original",
  "原先 原先 yuánxiān Original",
  "园林 園林 yuánlín Gardens",
  "源泉 源 yuánquán headspring",
  "约束 約束 yuēshù bind; restrain",
  "岳父 岳父 yuèfù father-in-law",
  "乐谱 樂譜 yuèpǔ Music score",
  "熨 熨 yùn Ironing",
  "蕴藏 蘊藏 yùncáng hold in store; contain",
  "运算 運算 yùnsuàn operation",
  "运行 運行 yùnxíng run; working",
  "酝酿 醞釀 yùnniàng Brewing",
  "孕育 孕育 yùnyù inoculation; breed",
  "砸 砸 zá Hit",
  "杂技 雜技 zájì acrobatics",
  "杂交 雜交 zájiāo Hybridization",
  "咋 咋 zǎ how; why",
  "灾难 災難 zāinàn disaster",
  "栽培 養殖 zāipéi cultivate",
  "宰 宰 zǎi Slaughter",
  "在乎 在乎 zàihu care about",
  "在意 在意 zàiyì care about",
  "再接再厉 再接再厲 zàijiēzàilì Make persistent efforts",
  "攒 攢 zǎn Save",
  "赞叹 讚歎 zàntàn Praise",
  "赞同 贊同 zàntóng agree with",
  "赞扬 讚揚 zànyáng Praise",
  "赞助 贊助 zànzhù Sponsor",
  "暂且 暫且 zànqiě For the time being",
  "糟蹋 糟蹋 zāotà waste; ruin",
  "遭受 遭受 zāoshòu Suffer",
  "遭殃 遭殃 zāoyāng Suffer",
  "遭遇 遭遇 zāoyù encounter",
  "造反 造反 zàofǎn Rebel",
  "造型 造型 zàoxíng style; modeling",
  "噪音 噪音 zàoyīn noise",
  "责怪 責怪 zéguài Blame",
  "贼 賊 zéi thief",
  "增添 增添 zēngtiān Add",
  "赠送 贈送 zèngsòng Give",
  "渣 渣 zhā residue",
  "扎 扎 zhā Tie",
  "扎实 紮實 zhāshi solid",
  "眨 眨 zhǎ Blink",
  "诈骗 詐騙 zhàpiàn Fraud",
  "摘要 摘要 zhāiyào abstract",
  "债券 債券 zhàiquàn bond",
  "沾光 沾光 zhānguāng gain some advantage from another",
  "瞻仰 瞻仰 zhānyǎng look at with reverence",
  "斩钉截铁 斬釘截鐵 zhǎndīngjiétiě Resolute and decisive",
  "展示 展示 zhǎnshì Exhibit",
  "展望 展望 zhǎnwàng expectation",
  "展现 展現 zhǎnxiàn To show",
  "崭新 嶄新 zhǎnxīn Completely new",
  "战斗 戰鬥 zhàndòu Battle",
  "战略 戰略 zhànlüè strategy",
  "战术 戰術 zhànshù tactics",
  "战役 戰役 zhànyì Battle",
  "占据 佔據 zhànjù Occupy",
  "占领 佔領 zhànlǐng occupy",
  "占有 佔有 zhànyǒu occupy",
  "长辈 長輩 zhǎngbèi Elder",
  "障碍 障礙 zhàng'ài obstacle",
  "帐篷 帳篷 zhàngpeng Tent",
  "招收 招收 zhāoshōu recruit",
  "招投标 招投標 zhāotóubiāo Bidding",
  "朝气蓬勃 朝氣蓬勃 zhāoqìpéngbó Full of youthful spirit",
  "get 得到 a cold",
  "着迷 著迷 zháomí Be fascinated",
  "沼泽 沼澤 zhǎozé Swamp",
  "照料 照料 zhàoliào Take care of",
  "all 所有 the same; as before",
  "照耀 照耀 zhàoyào Shine",
  "照应 照應 zhàoyìng Take care of",
  "遮挡 遮擋 zhēdǎng keep out",
  "折腾 折騰 zhēteng Toss",
  "折 折 zhé fracture",
  "折磨 折磨 zhémó torture",
  "真相 真相 zhēnxiàng fact; truth",
  "真挚 真摯 zhēnzhì sincere",
  "珍贵 珍貴 zhēnguì precious",
  "珍稀 珍稀 zhēnxī Rare",
  "珍珠 珍珠 zhēnzhū Pearl",
  "侦探 偵探 zhēntàn Detective",
  "斟酌 斟酌 zhēnzhuó Consider",
  "阵地 陣地 zhèndì position",
  "阵容 陣容 zhènróng Lineup",
  "镇定 鎮定 zhèndìng Calm",
  "镇静 鎮靜 zhènjìng Calm",
  "镇压 鎮壓 zhènyā Suppress",
  "振奋 振奮 zhènfèn Exciting",
  "振兴 振興 zhènxīng The revitalization of",
  "震惊 震驚 zhènjīng shock",
  "争端 爭端 zhēngduān Dispute",
  "争夺 爭奪 zhēngduó Fight for",
  "争气 爭氣 zhēngqì try to win credit for",
  "争先恐后 爭先恐後 zhēngxiānkǒnghòu strive to be the first; vie with each other",
  "争议 爭議 zhēngyì dispute",
  "蒸发 蒸發 zhēngfā evaporation",
  "征服 征服 zhēngfú Conquer",
  "征收 徵收 zhēngshōu collection",
  "正月 正月 zhēngyuè January (moon calendar)",
  "挣扎 掙扎 zhēngzhá Struggle",
  "整顿 整頓 zhěngdùn rectify",
  "正当 正當 zhèngdāng proper",
  "正负 正負 zhèngfù Positive and negative",
  "正规 正規 zhèngguī regular",
  "正经 正經 zhèngjing Serious",
  "正气 正氣 zhèngqì Righteousness",
  "正义 正義 zhèngyì justice",
  "政权 政權 zhèngquán regime",
  "证实 證實 zhèngshí Confirm",
  "证书 證書 zhèngshū certificate",
  "郑重 鄭重 zhèngzhòng Solemnly",
  "症状 症狀 zhèngzhuàng Symptom",
  "枝 枝 zhī branch",
  "支撑 支撐 zhīchēng brace",
  "支出 支出 zhīchū payout; expend",
  "支流 支流 zhīliú Tributary",
  "支配 統治 zhīpèi Control",
  "支援 支持 zhīyuán support",
  "支柱 支柱 zhīzhù mainstay; backbone",
  "知觉 知覺 zhījué perception",
  "知足常乐 知足常樂 zhīzúchánglè Happy is he who is content",
  "脂肪 脂肪 zhīfáng Fat",
  "直播 直播 zhíbō on live",
  "值班 值班 zhíbān Be on duty",
  "殖民地 殖民地 zhímíndì Colony",
  "职能 職能 zhínéng function",
  "职位 職位 zhíwèi position",
  "职务 職務 zhíwù post",
  "指标 指標 zhǐbiāo index",
  "指定 稱號 zhǐdìng Appoint",
  "指甲 指甲 zhǐjia nail",
  "指令 指令 zhǐlìng instructions",
  "指南针 指南針 zhǐnánzhēn Compass",
  "指示 指示 zhǐshì Instructions",
  "指望 指望 zhǐwàng expect; figure on",
  "指责 指責 zhǐzé Accuse",
  "治安 治安 zhì'ān public security",
  "治理 治理 zhìlǐ Government",
  "制裁 制裁 zhìcái Sanction",
  "制订 制訂 zhìdìng formulate",
  "制服 制服 zhìfú uniform",
  "制约 制約 zhìyuē restrict",
  "制止 制止 zhìzhǐ Stop it",
  "致辞 致辭 zhìcí Speech",
  "致力于 致力於 zhìlìyú devote oneself to",
  "致使 致使 zhìshǐ cause",
  "智力 智力 zhìlì intelligence",
  "智能 智能 zhìnéng Intelligence",
  "智商 智商 zhìshāng intelligence quotient",
  "滞留 滯留 zhìliú retention",
  "志气 志氣 zhìqì Ambition",
  "忠诚 忠誠 zhōngchéng loyal",
  "忠实 忠實 zhōngshí Faithful",
  "终点 終點 zhōngdiǎn End",
  "终究 終究 zhōngjiū after all",
  "终年 終年 zhōngnián All the year round",
  "终身 終身 zhōngshēn lifelong",
  "终止 終止 zhōngzhǐ termination",
  "中断 中斷 zhōngduàn interrupt",
  "中立 中立 zhōnglì neutral",
  "中央 中央 zhōngyāng center",
  "衷心 衷心 zhōngxīn Heartfelt",
  "种子 種子 zhǒngzi seed",
  "种族 種族 zhǒngzú race",
  "肿瘤 腫瘤 zhǒngliú tumour",
  "重心 重心 zhòngxīn Focus",
  "众所周知 眾所周知 zhòngsuǒzhōuzhī As everyone knows",
  "州 州 zhōu State",
  "舟 舟 zhōu boat",
  "粥 粥 zhōu Porridge",
  "周边 周邊 zhōubiān periphery",
  "周密 周密 zhōumì thorough; careful",
  "周年 週年 zhōunián anniversary",
  "周期 週期 zhōuqī period cycle",
  "周折 周折 zhōuzhé Twists and turns",
  "周转 周轉 zhōuzhuǎn turnover",
  "皱纹 皺紋 zhòuwén Wrinkle",
  "昼夜 晝夜 zhòuyè Day and night",
  "株 股票 zhū plant (measure word)",
  "诸位 諸位 zhūwèi every one",
  "逐年 逐年 zhúnián year by year",
  "拄 拄 zhǔ lean on a stick",
  "主办 主辦 zhǔbàn Host",
  "主导 主導 zhǔdǎo leading",
  "主管 主管 zhǔguǎn Executive director",
  "主流 主流 zhǔliú Main stream",
  "主权 主權 zhǔquán sovereignty",
  "主题 主題 zhǔtí theme",
  "住宅 住房 zhùzhái residence",
  "注射 注射 zhùshè injection",
  "注视 注視 zhùshì Gaze",
  "注释 註釋 zhùshì note; annotation",
  "注重 注重 zhùzhòng pay attention to",
  "助理 助理 zhùlǐ assistant",
  "助手 助手 zhùshǒu assistant",
  "著作 書 zhùzuò Work",
  "驻扎 駐紮 zhùzhā Be stationed",
  "铸造 鑄造 zhùzào casting, foundry",
  "拽 拽 zhuài drag; haul",
  "专长 專長 zhuāncháng Expertise",
  "专程 專程 zhuānchéng Special-purpose trip",
  "专科 專科 zhuānkē Specialty",
  "专利 專利 zhuānlì patent",
  "专题 專題 zhuāntí special collection",
  "砖瓦 磚瓦 zhuānwǎ Brick and tile",
  "转达 轉達 zhuǎndá Convey",
  "转让 轉讓 zhuǎnràng make over; transfer",
  "转移 轉移 zhuǎnyí transfer",
  "转折 轉折 zhuǎnzhé Transition",
  "传记 傳記 zhuànjì biography",
  "装备 裝備 zhuāngbèi equipment",
  "装卸 裝卸 zhuāngxiè Loading and unloading",
  "庄严 莊嚴 zhuāngyán solemn",
  "庄重 莊重 zhuāngzhòng grand; superb",
  "幢 幢 zhuàng Building (meaure word)",
  "壮观 壯觀 zhuàngguān grand; sublime",
  "壮丽 壯麗 zhuànglì Magnificent",
  "壮烈 壯烈 zhuàngliè brave; heroic",
  "追悼 紀念館 zhuīdào mour for",
  "追究 追究 zhuījiū Investigate",
  "准则 準則 zhǔnzé criterion",
  "琢磨 琢磨 zhuómó Pondering",
  "着手 著手 zhuóshǒu To start",
  "着想 著想 zhuóxiǎng consider",
  "着重 著重 zhuózhòng Emphasize",
  "卓越 卓越 zhuóyuè Excellent",
  "资本 資本 zīběn capital",
  "资产 資產 zīchǎn capital; asset",
  "资深 資深 zīshēn senior",
  "资助 資助 zīzhù give financial aid",
  "姿态 姿態 zītài attitude",
  "滋味 滋味 zīwèi Taste",
  "滋长 滋長 zīzhǎng Grow",
  "子弹 子彈 zǐdàn Bullet",
  "字母 字母 zìmǔ Letter",
  "自卑 自卑 zìbēi inferiority",
  "自发 自發 zìfā spontaneous; unprompted",
  "自力更生 自力更生 zìlìgēngshēng Rely through one's own efforts",
  "自满 自滿 zìmǎn Complacent",
  "自主 自主 zìzhǔ Autonomy",
  "踪迹 踪跡 zōngjì tail; trail; trace",
  "宗旨 宗旨 zōngzhǐ Purpose",
  "棕色 棕色 zōngsè brown",
  "总而言之 總而言之 zǒng'éryánzhī To make a long story short",
  "总和 總和 zǒnghé summation",
  "纵横 縱橫 zònghéng in length and breadth",
  "走廊 走廊 zǒuláng corridor",
  "走漏 走漏 zǒulòu leak out",
  "走私 走私 zǒusī smuggle",
  "揍 揍 zòu Beat",
  "租赁 租賃 zūlìn Lease",
  "足以 足以 zúyǐ Enough",
  "组 組 zǔ group",
  "阻碍 阻礙 zǔ'ài hinder",
  "阻拦 阻攔 zǔlán block off",
  "阻挠 阻撓 zǔnáo obstruct; stand in the way",
  "祖父 祖父 zǔfù grandfather",
  "钻研 鑽研 zuānyán Study intensively",
  "钻石 鑽石 zuànshí Diamonds",
  "嘴唇 嘴唇 zuǐchún Lips",
  "尊严 尊嚴 zūnyán dignity",
  "遵循 遵循 zūnxún follow",
  "左右 左右 zuǒyòu About",
  "座右铭 座右銘 zuòyòumíng Motto",
  "作弊 作弊 zuòbì Cheat",
  "作废 作廢 zuòfèi cancel, blank out",
  "作风 作風 zuòfēng style",
  "作息 作息 zuòxī work and rest",
];
