/** ========================================================================
 * Route names
 * =========================================================================
 */
export enum ROUTE_NAMES {
  APP = "APP",
  HOME = "HOME",
  LIST_SUMMARY = "LIST_SUMMARY",
  LESSON_SUMMARY = "LESSON_SUMMARY",
  QUIZ = "QUIZ",
  DAILY_CHALLENGE = "DAILY_CHALLENGE",
  HSK_TEST_OUT = "HSK_TEST_OUT",
  MULTIPLE_CHOICE_MANDARIN = "MULTIPLE_CHOICE_MANDARIN",
  MULTIPLE_CHOICE_ENGLISH = "MULTIPLE_CHOICE_ENGLISH",
  MULTIPLE_CHOICE_VOICE = "MULTIPLE_CHOICE_VOICE",
  FLASHCARDS = "FLASHCARDS",
  CHARACTER_WRITING = "CHARACTER_WRITING",
  WRITING_PAD = "WRITING_PAD",
  VIEW_ALL = "VIEW_ALL",
  AUDIO_REVIEW_QUIZ = "AUDIO_REVIEW_QUIZ",
  NOTE_PAD = "NOTE_PAD",
  TRANSLATION = "TRANSLATION",
  WELCOME = "WELCOME",
  INTRO = "INTRO",
  ABOUT = "ABOUT",
  ABOUT_DETAIL = "ABOUT_DETAIL",
  CONTACT = "CONTACT",
  SETTINGS = "SETTINGS",
  ACCOUNT = "ACCOUNT",
}
