export default [
  "唉 唉 āi alas",
  "爱护 愛護 àihù Care",
  "爱惜 愛惜 àixī Cherish",
  "爱心 愛心 àixīn love",
  "安慰 安慰 ānwèi comfort",
  "安装 安裝 ānzhuāng install",
  "岸 岸 àn bank",
  "把握 把握 bǎwò grasp",
  "摆 擺 bǎi pendulum",
  "班主任 班主任 bānzhǔrèn Headmaster",
  "办理 辦理 bànlǐ handle",
  "棒 棒 bàng stick",
  "傍晚 傍晚 bàngwǎn Evening",
  "包裹 包裹 bāoguǒ package",
  "包含 包含 bāohán Contain",
  "包子 包子 bāozi Steamed stuffed bun",
  "薄 薄 báo thin",
  "宝贝 寶貝 bǎobèi baby",
  "宝贵 寶貴 bǎoguì valuable",
  "保持 保持 bǎochí keep",
  "保存 存儲 bǎocún Preservation",
  "保留 保留 bǎoliú Retain",
  "保险 保險 bǎoxiǎn Insurance",
  "报告 報告 bàogào Presentation",
  "悲观 悲觀 bēiguān Pessimism",
  "背 背 bèi Back",
  "背景 背景 bèijǐng background",
  "被子 被子 bèizi quilt",
  "本科 本科 běnkē Undergraduate",
  "本领 本領 běnlǐng ability",
  "本质 本質 běnzhì essence",
  "比例 比例 bǐlì Proportion",
  "比如 比如 bǐrú such as",
  "彼此 彼此 bǐcǐ each other",
  "毕竟 畢竟 bìjìng after all",
  "避免 避免 bìmiǎn avoid",
  "必然 必然 bìrán Inevitable",
  "必需 必需 bìxū essential",
  "必要 需要 bìyào necessary",
  "编辑 編輯 biānjí edit",
  "鞭炮 鞭炮 biānpào firecracker",
  "便 便 biàn then, in that case",
  "辩论 辯論 biànlùn Debate",
  "标点 標點 biāodiǎn punctuation",
  "标志 標誌 biāozhì sign",
  "表面 表面 biǎomiàn surface",
  "表明 表明 biǎomíng Indicate",
  "表情 表情 biǎoqíng Expression",
  "表现 表現 biǎoxiàn performance",
  "病毒 病毒 bìngdú virus",
  "玻璃 玻璃 bōli Glass",
  "博物馆 博物館 bówùguǎn Museum",
  "脖子 脖子 bózi neck",
  "不必 不必 búbì need not",
  "不断 不斷 búduàn Constantly",
  "不见得 不見得 bújiàndé Not necessarily",
  "不耐烦 不耐煩 búnàifán Impatient",
  "不要紧 不要緊 búyàojǐn Never mind",
  "补充 補充 bǔchōng supplement",
  "布 布 bù cloth, textile",
  "不安 焦慮 bù'ān Uneasy, unstable",
  "不得了 不得了 bùdéliǎo Very",
  "不好意思 不好意思 bùhǎoyìsi Sorry",
  "不免 不免 bùmiǎn unavoidable",
  "不然 不然 bùrán otherwise",
  "不如 不如 bùrú not as good as",
  "不足 不足 bùzú insufficient",
  "部门 部門 bùmén department",
  "步骤 步驟 bùzhòu step",
  "财产 財產 cáichǎn property",
  "踩 踩 cǎi step on",
  "采访 採訪 cǎifǎng interview",
  "采取 採取 cǎiqǔ take, adopt",
  "彩虹 彩虹 cǎihóng Rainbow",
  "参考 參考 cānkǎo Reference resources",
  "参与 參與 cānyù participate in",
  "餐厅 餐廳 cāntīng Restaurant",
  "残疾 殘疾 cánjí disability",
  "惭愧 慚愧 cánkuì Be ashamed",
  "操场 操場 cāochǎng Playground",
  "操心 操心 cāoxīn Worry",
  "册 冊 cè volume, book",
  "厕所 廁所 cèsuǒ Toilet",
  "测验 測驗 cèyàn test",
  "曾经 曾經 céngjīng once",
  "插 插 chā insert",
  "差别 差別 chābié difference",
  "叉子 叉子 chāzi Fork",
  "拆 拆 chāi Remove",
  "产品 產品 chǎnpǐn product",
  "产生 產生 chǎnshēng produce",
  "长途 長途 chángtú Long-distance",
  "常识 常識 chángshí common sense",
  "抄 抄 chāo copy",
  "朝 上午 cháo towards",
  "朝代 朝代 cháodài Dynasty",
  "炒 炒 chǎo fry",
  "吵架 吵架 chǎojià quarrel",
  "车库 車庫 chēkù Garage",
  "车厢 車廂 chēxiāng carriage",
  "彻底 徹底 chèdǐ thorough",
  "沉默 沉默 chénmò silent",
  "趁 趁 chèn while",
  "称 稱 chēng call",
  "称呼 稱呼 chēnghu to address",
  "称赞 稱讚 chēngzàn Praise",
  "乘 乘 chéng ride, take",
  "承担 承擔 chéngdān bear",
  "承认 承認 chéngrèn Admit",
  "承受 承受 chéngshòu bear",
  "程度 程度 chéngdù degree",
  "程序 程序 chéngxù program",
  "成分 成分 chéngfèn component",
  "成果 成果 chéngguǒ Achievements",
  "成就 成就 chéngjiù achievement",
  "成立 成立 chénglì establish",
  "成语 成語 chéngyǔ idiom",
  "成长 成長 chéngzhǎng Grow up",
  "诚恳 誠懇 chéngkěn sincere",
  "吃亏 吃虧 chīkuī Suffer",
  "持续 持續 chíxù Continued",
  "池子 池子 chízi Pond",
  "尺子 尺子 chǐzi Ruler",
  "翅膀 翅膀 chìbǎng Wing",
  "冲 衝 chōng punching",
  "充电器 充電器 chōngdiànqì Charger",
  "充分 充分 chōngfèn To the full",
  "充满 充滿 chōngmǎn full of",
  "重复 重複 chóngfù repeat",
  "宠物 寵物 chǒngwù Pet",
  "抽屉 抽屜 chōuti drawer",
  "抽象 抽象 chōuxiàng abstract",
  "丑 醜 chǒu ugly",
  "臭 臭 chòu smelly",
  "出版 出版 chūbǎn publish",
  "出口 出口 chūkǒu Exit",
  "出席 出席 chūxí Attend",
  "初级 初級 chūjí primary",
  "除 除 chú except",
  "除非 除非 chúfēi Unless",
  "除夕 除夕 chúxī the New Year's Eve",
  "处理 處理 chǔlǐ Handle",
  "传播 傳播 chuánbō spread",
  "传递 傳遞 chuándì pass; transfer",
  "传染 傳染 chuánrǎn contagion",
  "传说 傳說 chuánshuō Legend",
  "传统 傳統 chuántǒng tradition",
  "窗帘 窗簾 chuānglián Window curtains",
  "闯 闖 chuǎng rush; dash",
  "创造 創造 chuàngzào create",
  "吹 吹 chuī blow",
  "磁带 磁帶 cídài Magnetic tape",
  "辞职 辭職 cízhí Resignation",
  "此外 此外 cǐwài in addition",
  "次要 次要 cìyào secondary",
  "刺激 刺激 cìjī stimulate",
  "匆忙 匆忙 cōngmáng hastily",
  "从此 從此 cóngcǐ from then on",
  "从而 從而 cóng'ér thus",
  "从前 從前 cóngqián before",
  "从事 從事 cóngshì Be engaged in",
  "醋 醋 cù vinegar",
  "促进 促進 cùjìn Promote",
  "促使 促使 cùshǐ Urge",
  "催 催 cuī Reminder, urge",
  "存 存 cún Deposit",
  "存在 存在 cúnzài existence",
  "错误 錯誤 cuòwù error",
  "措施 措施 cuòshī Measures",
  "答应 答應 dāying promise",
  "达到 達到 dádào Achieve",
  "打工 打工 dǎgōng Work",
  "打交道 打交道 dǎjiāodao Dealing with",
  "打喷嚏 打噴嚏 dǎpēntì Sneeze",
  "打听 打聽 dǎting Inquire",
  "打招呼 打招呼 dǎzhāohu Say hello",
  "大方 大方 dàfang generous",
  "大象 大象 dàxiàng Elephant",
  "大型 大型 dàxíng large",
  "呆 呆 dāi stay",
  "贷款 貸款 dàikuǎn extend credit to; provide a loan",
  "待遇 待遇 dàiyù treatment",
  "单纯 單純 dānchún Simple",
  "单调 單調 dāndiào monotonous",
  "单独 單獨 dāndú Alone",
  "单位 單位 dānwèi Company",
  "单元 單元 dānyuán unit",
  "担任 擔任 dānrèn To serve as",
  "耽误 耽誤 dānwu delay",
  "胆小鬼 膽小鬼 dǎnxiǎoguǐ Coward",
  "淡 淡 dàn light",
  "当代 當代 dāngdài Contemporary",
  "挡 擋 dǎng block",
  "岛 島 dǎo island",
  "倒霉 倒霉 dǎoméi fall on evil days",
  "导演 導演 dǎoyǎn director",
  "导致 導致 dǎozhì cause",
  "倒 倒 dào inverted",
  "到达 到達 dàodá Arrive",
  "道德 道德 dàodé Morality",
  "道理 道理 dàolǐ truth",
  "登机牌 登機牌 dēngjīpái Boarding pass",
  "登记 登記 dēngjì register",
  "等待 等待 děngdài wait for",
  "等候 等候 děnghòu Wait",
  "等于 等於 děngyú Be equal to",
  "滴 滴 dī drop",
  "的确 的確 díquè indeed; be certain to",
  "敌人 敵人 dírén Enemy",
  "递 遞 dì Delivery",
  "地道 地道 dìdao tunnel",
  "地理 地理 dìlǐ Geography",
  "地区 地區 dìqū region",
  "地毯 地毯 dìtǎn Carpet",
  "地位 地位 dìwèi status",
  "地震 地震 dìzhèn earthquake",
  "点头 點頭 diǎntóu Nod",
  "点心 點心 diǎnxin snack",
  "电池 電池 diànchí Battery",
  "电台 電台 diàntái radio station",
  "钓 釣 diào Fishing",
  "顶 頂 dǐng top",
  "冻 凍 dòng freeze",
  "洞 洞 dòng hole",
  "动画片 動畫片 dònghuàpiàn Cartoon",
  "逗 逗 dòu Funny",
  "豆腐 豆腐 dòufu Bean curd",
  "独立 獨立 dúlì Independent",
  "独特 獨特 dútè unique",
  "度过 度過 dùguò Spend",
  "短信 短信 duǎnxìn Short message",
  "堆 堆 duī heap",
  "对比 對比 duìbǐ Contrast",
  "对待 對待 duìdài treat",
  "对方 對方 duìfāng the other party",
  "对手 對手 duìshǒu Opponent",
  "对象 對象 duìxiàng object",
  "对于 對於 duìyú about",
  "吨 噸 dūn ton",
  "蹲 蹲 dūn squat",
  "多亏 多虧 duōkuī thanks to",
  "多余 多餘 duōyú surplus",
  "躲藏 躲藏 duǒcáng Hide oneself",
  "恶劣 惡劣 èliè Adverse",
  "发表 發表 fābiǎo Publish",
  "发愁 發愁 fāchóu To be worried",
  "发达 發達 fādá To develop",
  "发抖 發抖 fādǒu Tremble",
  "发挥 發揮 fāhuī Develop",
  "发明 發明 fāmíng Invention",
  "发票 發票 fāpiào invoice",
  "发言 發言 fāyán give a speech",
  "罚款 罰款 fákuǎn forfeit; amerce; fine",
  "法院 法院 fǎyuàn Court",
  "翻 翻 fān Turn",
  "繁荣 繁榮 fánróng Boom",
  "凡是 凡是 fánshì All, everything",
  "反而 反而 fǎn'ér Instead",
  "反复 反复 fǎnfù Repeatedly",
  "反应 反應 fǎnyìng reaction",
  "反正 反正 fǎnzhèng anyway",
  "方 如何 fāng square",
  "方案 方案 fāng'àn programme",
  "方式 方式 fāngshì mode",
  "妨碍 妨礙 fáng'ài Hinder",
  "房东 房東 fángdōng landlord",
  "仿佛 彷彿 fǎngfú as if",
  "放松 放鬆 fàngsōng Relax",
  "非 非 fēi wrong; non",
  "肥皂 肥皂 féizào soap",
  "肺 肺 fèi lung",
  "废话 廢話 fèihuà Crap",
  "费用 費用 fèiyong Cost",
  "分别 分別 fēnbié part",
  "分布 分佈 fēnbù distribution",
  "分配 分配 fēnpèi distribution",
  "分析 分析 fēnxī Analysis",
  "纷纷 紛紛 fēnfēn one after another",
  "奋斗 奮鬥 fèndòu Struggle",
  "愤怒 憤怒 fènnù anger",
  "风格 風格 fēnggé style",
  "风俗 風俗 fēngsú Customs",
  "风险 風險 fēngxiǎn risk",
  "疯狂 瘋狂 fēngkuáng Insane",
  "讽刺 諷刺 fěngcì satire",
  "否定 否定 fǒudìng negative",
  "否认 否認 fǒurèn deny",
  "扶 扶 fú hold up",
  "幅 寬度 fú classifier of picture",
  "服从 服從 fúcóng Obey",
  "服装 服裝 fúzhuāng costume; dress",
  "辅导 輔導 fǔdǎo Coach",
  "付款 付款 fùkuǎn pay",
  "妇女 婦女 fùnǚ Woman",
  "复制 複製 fùzhì copy",
  "改革 改革 gǎigé reform",
  "改进 改進 gǎijìn Improvement",
  "改善 改善 gǎishàn Improve",
  "改正 修訂 gǎizhèng correction",
  "盖 蓋 gài cover",
  "概括 概括 gàikuò Generalization",
  "概念 概念 gàiniàn concept",
  "干脆 乾脆 gāncuì simply",
  "感激 感激 gǎnjī Appreciate",
  "感受 感受 gǎnshòu feel",
  "感想 印象 gǎnxiǎng Feel",
  "赶紧 趕緊 gǎnjǐn Quickly",
  "赶快 趕快 gǎnkuài hurry up",
  "干活儿 幹活兒 gànhuór work on a job",
  "钢铁 鋼鐵 gāngtiě steel",
  "高档 高檔 gāodàng High-grade",
  "高速公路 高速公路 gāosùgōnglù Expressway",
  "搞 搞 gǎo get",
  "告别 告別 gàobié farewell",
  "胳膊 胳膊 gēbo Arm",
  "鸽子 鴿子 gēzi Dove",
  "隔壁 隔壁 gébì next door",
  "革命 革命 gémìng revolution",
  "格外 格外 géwài especially",
  "个别 個別 gèbié individual",
  "个人 個人 gèrén personal",
  "个性 個性 gèxìng personality",
  "各自 各自 gèzì Each",
  "根 根 gēn root",
  "根本 根本 gēnběn at all",
  "更加 更加 gèngjiā More",
  "公布 公佈 gōngbù Publish",
  "公开 公開 gōngkāi open",
  "公平 公平 gōngpíng fair",
  "公寓 公寓 gōngyù apartment",
  "公元 公元 gōngyuán A.D.",
  "公主 公主 gōngzhǔ princess",
  "工厂 工廠 gōngchǎng factory",
  "工程师 工程師 gōngchéngshī Engineer",
  "工人 工人 gōngrén Worker",
  "工业 工業 gōngyè Industry",
  "功夫 功夫 gōngfu Kungfu",
  "功能 功能 gōngnéng function",
  "贡献 貢獻 gòngxiàn contribution",
  "沟通 溝通 gōutōng Communicate",
  "构成 構成 gòuchéng constitute",
  "姑姑 姑姑 gūgu aunt",
  "姑娘 姑娘 gūniang girl",
  "古代 古代 gǔdài Ancient",
  "古典 古典 gǔdiǎn classical",
  "古老 古老 gǔlǎo ancient",
  "鼓舞 鼓舞 gǔwǔ Inspire",
  "股票 股票 gǔpiào shares; stock",
  "骨头 骨頭 gǔtou Bone",
  "固定 固定 gùdìng fixed",
  "固体 固體 gùtǐ solid",
  "雇佣 僱傭 gùyōng hire",
  "挂号 掛號 guàhào Register",
  "乖 乖 guāi Good behaved",
  "拐弯 拐彎 guǎiwān Turn",
  "怪不得 怪不得 guàibude No wonder",
  "官 官 guān officer",
  "关闭 關閉 guānbì close; shut",
  "关怀 關懷 guānhuái Care",
  "观察 觀察 guānchá observation",
  "观点 觀點 guāndiǎn viewpoint",
  "观念 觀念 guānniàn concept",
  "管子 管子 guǎnzi pipe",
  "冠军 冠軍 guànjūn Champion",
  "罐头 罐頭 guàntou Can, tin",
  "光滑 光滑 guānghuá smooth",
  "光临 光臨 guānglín presence",
  "光明 光明 guāngmíng light",
  "光盘 光盤 guāngpán CD",
  "光荣 光榮 guāngróng glory",
  "广场 廣場 guǎngchǎng square",
  "广大 廣大 guǎngdà Vast",
  "广泛 廣泛 guǎngfàn widely",
  "规矩 規矩 guīju Rules",
  "规律 規律 guīlǜ Law",
  "规模 規模 guīmó scale",
  "规则 規則 guīzé rule",
  "柜台 櫃檯 guìtái Counter",
  "滚 滾 gǔn rolling",
  "锅 鍋 guō pot",
  "国籍 國籍 guójí nationality",
  "国庆节 國慶節 guóqìngjié National Day",
  "果实 果實 guǒshí fruit",
  "过分 過分 guòfèn excessive",
  "过敏 過敏 guòmǐn allergy",
  "过期 過期 guòqī Be overdue",
  "哈 哈 hā ah",
  "海关 海關 hǎiguān Customs",
  "海鲜 海鮮 hǎixiān seafood",
  "喊 喊 hǎn shout",
  "行业 行業 hángyè industry",
  "豪华 豪華 háohuá luxury",
  "好奇 好奇 hàoqí Be curious",
  "和平 和平 hépíng peace",
  "何必 何必 hébì Why",
  "何况 何況 hékuàng Not to mention",
  "合法 合法 héfǎ legitimate",
  "合理 合理 hélǐ reasonable",
  "合同 合同 hétong contract",
  "合影 合影 héyǐng Group photo",
  "合作 合作 hézuò cooperation",
  "核心 核心 héxīn core",
  "恨 恨 hèn hate",
  "横 旁 héng harsh and unreasonable; perverse",
  "后果 後果 hòuguǒ Consequence",
  "忽视 忽視 hūshì Ignore",
  "呼吸 呼吸 hūxī breathing",
  "壶 壺 hú pot",
  "蝴蝶 蝴蝶 húdié Butterfly",
  "胡说 胡說 húshuō Nonsense",
  "胡同 胡同 hútòng Hutong",
  "胡须 鬍鬚 húxū beard",
  "糊涂 糊塗 hútu Confused",
  "花生 花生 huāshēng peanut",
  "滑冰 滑冰 huábīng skating",
  "划船 划船 huáchuán Rowing",
  "华裔 華裔 huáyì Chinese born",
  "话题 話題 huàtí Topic of conversation",
  "化学 化學 huàxué Chemistry",
  "怀念 懷念 huáiniàn miss",
  "缓解 緩解 huǎnjiě relieve",
  "幻想 幻想 huànxiǎng fantasy",
  "慌张 慌張 huāngzhāng flurried",
  "黄瓜 黃瓜 huángguā cucumber",
  "黄金 黃金 huángjīn gold",
  "皇帝 皇帝 huángdì Emperor",
  "皇后 皇后 huánghòu Queen",
  "挥 揮 huī Essential",
  "灰 灰 huī ash",
  "灰尘 灰塵 huīchén dust",
  "灰心 灰心 huīxīn Lose heart; be discouraged",
  "恢复 恢復 huīfù recovery",
  "汇率 匯率 huìlǜ exchange rate",
  "婚礼 婚禮 hūnlǐ wedding",
  "婚姻 婚姻 hūnyīn Marriage",
  "活跃 活躍 huóyuè active",
  "火柴 火柴 huǒchái Match",
  "伙伴 夥伴 huǒbàn Partner",
  "基本 基本 jīběn basic",
  "机器 機器 jīqì machine",
  "激烈 激烈 jīliè fierce",
  "肌肉 肌肉 jīròu muscle",
  "及格 及格 jígé pass",
  "集体 集體 jítǐ collective",
  "集中 濃度 jízhōng focus",
  "急忙 急忙 jímáng Hastily",
  "记录 記錄 jìlù Record",
  "记忆 記憶 jìyì memory",
  "计算 計算 jìsuàn Calculation",
  "系领带 系領帶 jìlǐngdài wear a tie",
  "纪录 紀錄 jìlù Record",
  "纪律 紀律 jìlǜ discipline",
  "纪念 紀念 jìniàn memorialize",
  "寂寞 寂寞 jìmò lonely",
  "家庭 家庭 jiātíng Family",
  "家务 家務 jiāwù Housework",
  "家乡 家鄉 jiāxiāng Hometown",
  "嘉宾 嘉賓 jiābīn Distinguished guest",
  "夹子 夾子 jiāzi Clip",
  "甲 甲 jiǎ nail",
  "假如 假如 jiǎrú If",
  "假装 假裝 jiǎzhuāng pretend",
  "嫁 媳婦 jià get married to",
  "价值 價值 jiàzhí value",
  "驾驶 駕駛 jiàshǐ Drive",
  "煎 煎 jiān Fried",
  "肩膀 肩膀 jiānbǎng shoulder",
  "坚决 堅決 jiānjué firm, determined",
  "坚强 堅強 jiānqiáng Firm",
  "艰巨 艱鉅 jiānjù arduous",
  "艰苦 艱苦 jiānkǔ hard",
  "尖锐 尖銳 jiānruì Sharp",
  "捡 撿 jiǎn pick up",
  "简历 簡歷 jiǎnlì resume",
  "简直 簡直 jiǎnzhí simply",
  "剪刀 剪刀 jiǎndāo scissors",
  "健身房 健身房 jiànshēnfáng Gym",
  "建立 建立 jiànlì establish",
  "建设 建設 jiànshè build",
  "建议 建議 jiànyì proposal",
  "建筑 建築 jiànzhù Architecture",
  "键盘 鍵盤 jiànpán keyboard",
  "讲究 講究 jiǎngjiu Pay attention to; daintily",
  "讲座 講座 jiǎngzuò Lecture",
  "降落 降落 jiàngluò land",
  "酱油 醬油 jiàngyóu soy sauce",
  "浇 澆 jiāo pour it over",
  "交换 交換 jiāohuàn exchange",
  "交际 交際 jiāojì communication",
  "郊区 郊區 jiāoqū Suburb",
  "胶水 膠水 jiāoshuǐ glue",
  "角度 角度 jiǎodù angle",
  "狡猾 狡猾 jiǎohuá cunning",
  "教材 教材 jiàocái teaching material",
  "教练 教練 jiàoliàn coach",
  "教训 教訓 jiàoxùn lesson",
  "接触 接觸 jiēchù Contact",
  "接待 接待 jiēdài Reception",
  "接近 接近 jiējìn near",
  "接着 膠粘劑 jiēzhe Next",
  "阶段 階段 jiēduàn stage",
  "结实 結實 jiēshi strong",
  "节 節 jié section, festival",
  "节省 節省 jiéshěng save",
  "结构 結構 jiégòu structure",
  "结合 結合 jiéhé Combination",
  "结论 結論 jiélùn conclusion",
  "结账 結賬 jiézhàng Checkout",
  "解放 解放 jiěfàng liberate",
  "解说员 解說員 jiěshuōyuán Narrator",
  "届 屆 jiè Session",
  "借口 藉口 jièkǒu Excuse",
  "戒烟 戒菸 jièyān Quit smoking",
  "戒指 戒指 jièzhi Ring",
  "金属 金屬 jīnshǔ Metal",
  "紧 緊 jǐn tight",
  "紧急 緊急 jǐnjí urgent",
  "谨慎 謹慎 jǐnshèn cautious",
  "进步 進步 jìnbù progress",
  "进口 進口 jìnkǒu Imported",
  "近代 現代 jìndài Modern",
  "尽力 盡力 jìnlì Try the best",
  "尽量 盡量 jìnliàng as far as possible",
  "精力 精力 jīnglì energy",
  "经典 經典 jīngdiǎn classics; scriptures",
  "经营 經營 jīngyíng Management",
  "景色 風景 jǐngsè scenery",
  "敬爱 敬愛 jìng'ài respect and love; esteem",
  "酒吧 酒吧 jiǔbā Bar",
  "救 救 jiù save",
  "救护车 救護車 jiùhùchē Ambulance",
  "舅舅 舅舅 jiùjiu uncle",
  "居然 居然 jūrán actually",
  "桔子 桔子 júzi Orange",
  "举 舉 jǔ lift",
  "具备 具備 jùbèi Have, possess",
  "具体 具體 jùtǐ specific",
  "巨大 巨大 jùdà huge",
  "聚会 聚會 jùhuì Party",
  "俱乐部 俱樂部 jùlèbù Club",
  "据说 據說 jùshuō allegedly; it`s said",
  "捐 捐 juān Donate",
  "卷 卷 juǎn volume",
  "决赛 決賽 juésài Finals",
  "决心 決心 juéxīn Determination",
  "绝对 絕對 juéduì Absolutely",
  "角色 角色 juésè role",
  "军事 軍事 jūnshì Military",
  "均匀 均勻 jūnyún uniformity",
  "卡车 卡車 kǎchē Truck",
  "开发 開發 kāifā Development",
  "开放 開放 kāifàng To open up",
  "开幕式 開幕式 kāimùshì The opening ceremony",
  "开心 開心 kāixīn Happy",
  "砍 砍 kǎn cut",
  "看不起 看不起 kànbuqǐ Despise",
  "看来 看來 kànlái it seems",
  "抗议 抗議 kàngyì Protest",
  "烤鸭 烤鴨 kǎoyā Roasted Duck",
  "颗 顆 kē pellet (measure word)",
  "可见 可見 kějiàn so; it`s thus clear",
  "可靠 可靠 kěkào reliable",
  "可怕 可怕 kěpà dreadful",
  "课程 課程 kèchéng curriculum",
  "克 克 kè gram",
  "克服 克服 kèfú Overcome",
  "刻苦 刻苦 kèkǔ Hardworking",
  "客观 客觀 kèguān objective",
  "客厅 客廳 kètīng A living room",
  "空间 空間 kōngjiān space",
  "恐怖 恐怖 kǒngbù terror， horrible",
  "空闲 空閒 kòngxián free",
  "控制 控制 kòngzhì control",
  "口味 口味 kǒuwèi Flavor",
  "夸 誇 kuā boast, praise",
  "会计 會計 kuàijì accountant",
  "矿泉水 礦泉水 kuàngquánshuǐ Mineral water",
  "辣椒 辣椒 làjiāo Pepper, spice",
  "蜡烛 蠟燭 làzhú candle",
  "来自 來自 láizì Come from",
  "拦 攔 lán Stop",
  "烂 爛 làn rotten",
  "狼 狼 láng wolf",
  "劳动 勞動 láodòng labour",
  "劳驾 勞駕 láojià Excuse me",
  "老百姓 老百姓 lǎobǎixìng Ordinary people",
  "老板 老闆 lǎobǎn Boss",
  "老实 老實 lǎoshi honest",
  "老鼠 老鼠 lǎoshǔ Mouse",
  "姥姥 姥姥 lǎolao Grandma",
  "乐观 樂觀 lèguān optimistic",
  "雷 雷 léi Thunder",
  "类 類 lèi class, category",
  "梨 梨 lí pear",
  "离婚 離婚 líhūn divorce",
  "厘米 厘米 límǐ centimeter",
  "礼拜天 禮拜天 lǐbàitiān Sunday",
  "理论 理論 lǐlùn theory",
  "理由 原因 lǐyóu Reason",
  "粒 粒 lì grain (measure word)",
  "立方 立方 lìfāng cube",
  "立即 立即 lìjí immediately",
  "立刻 立刻 lìkè immediately",
  "力量 力量 lìliàng Power",
  "利润 利潤 lìrùn profit",
  "利息 利息 lìxī accrual; interest",
  "利益 利益 lìyì interest",
  "利用 使用 lìyòng utilize",
  "连忙 連忙 liánmáng Hurriedly",
  "连续剧 連續劇 liánxùjù serial TV drama",
  "联合 聯合 liánhé union",
  "恋爱 戀愛 liàn'ài Love, in love",
  "良好 良好 liánghǎo good",
  "粮食 糧食 liángshi foodstuff",
  "了不起 了不起 liǎobuqǐ Amazing",
  "临时 臨時 línshí temporary",
  "铃 鈴 líng bell",
  "零件 零件 língjiàn Spare parts",
  "零钱 零錢 língqián Small change",
  "零食 零食 língshí snacks",
  "灵活 靈活 línghuó flexible",
  "领导 領導 lǐngdǎo Leader",
  "领域 領域 lǐngyù field",
  "流传 流傳 liúchuán spread",
  "浏览 瀏覽 liúlǎn browse",
  "龙 龍 lóng dragon",
  "漏 漏 lòu leak",
  "露 露 lù dew",
  "陆地 陸地 lùdì land",
  "陆续 陸續 lùxù One after another",
  "录取 錄取 lùqǔ matriculate",
  "录音 錄音 lùyīn Sound recording",
  "轮流 輪流 lúnliú take turns",
  "论文 論文 lùnwén paper",
  "逻辑 邏輯 luóji logic",
  "落后 落後 luòhòu backward, fall behind",
  "骂 罵 mà scold",
  "麦克风 麥克風 màikèfēng Microphone",
  "馒头 饅頭 mántou Steamed buns",
  "满足 滿足 mǎnzú satisfy",
  "毛 毛 máo hair",
  "毛病 毛病 máobìng Trouble",
  "矛盾 矛盾 máodùn contradiction",
  "冒险 冒險 màoxiǎn adventure",
  "贸易 貿易 màoyì Trade",
  "眉毛 眉毛 méimao eyebrow",
  "煤炭 煤炭 méitàn coal",
  "美术 美術 měishù Fine Arts",
  "魅力 魅力 mèilì charm",
  "迷路 迷路 mílù Get lost",
  "谜语 謎語 míyǔ Riddle",
  "蜜蜂 蜜蜂 mìfēng honeybee",
  "密切 密切 mìqiè close",
  "秘密 秘密 mìmì Secret",
  "秘书 秘書 mìshū secretary",
  "棉花 棉花 miánhua cotton",
  "面对 面對 miànduì Face",
  "面积 面積 miànjī The measure of area",
  "面临 面臨 miànlín face",
  "苗条 苗條 miáotiao slim",
  "描写 描寫 miáoxiě describe",
  "秒 秒 miǎo second",
  "民主 民主 mínzhǔ democratic",
  "明确 明確 míngquè To make clear",
  "明显 明顯 míngxiǎn obvious",
  "明信片 明信片 míngxìnpiàn Postcard",
  "明星 明星 míngxīng Star",
  "名牌 名牌 míngpái famous brand",
  "名片 名片 míngpiàn business card",
  "名胜古迹 名勝古蹟 míngshènggǔjì Places of historic interest and scenic beauty",
  "命令 命令 mìnglìng call; nominate",
  "命运 命運 mìngyùn fate, destiny",
  "摸 摸 mō feel, touch",
  "模仿 模仿 mófǎng imitate",
  "模糊 模糊 móhu vague",
  "摩托车 摩托車 mótuōchē Motorcycle",
  "陌生 陌生 mòshēng strange",
  "某 某 mǒu some",
  "目标 目標 mùbiāo target",
  "目录 目錄 mùlù Catalog",
  "目前 目前 mùqián at present",
  "木头 木頭 mùtou wood",
  "哪怕 哪怕 nǎpà even if",
  "难怪 難怪 nánguài no wonder",
  "难看 難看 nánkàn ugly",
  "脑袋 腦袋 nǎodai head",
  "内科 內科 nèikē Internal medicine",
  "嫩 嫩 nèn tender, delicate",
  "能干 能幹 nénggàn capable",
  "能源 能源 néngyuán energy",
  "年代 年代 niándài years",
  "年纪 年紀 niánjì Age",
  "念 念 niàn Read",
  "宁可 寧可 nìngkě would rather",
  "牛仔裤 牛仔褲 niúzǎikù Jeans",
  "浓 濃 nóng strong",
  "农民 農民 nóngmín farmer",
  "农业 農業 nóngyè Agriculture",
  "女士 女士 nǚshì Madam",
  "偶然 偶然 ǒurán accidental",
  "拍 拍 pāi beat",
  "排队 排隊 páiduì queue; stand in a line",
  "排球 排球 páiqiú Volleyball",
  "派 派 pài send",
  "盼望 盼望 pànwàng look forward to",
  "赔偿 賠償 péicháng compensate for",
  "培养 培養 péiyǎng culture, foster",
  "佩服 佩服 pèifu Admire",
  "配合 配合 pèihé Coordination",
  "盆 盆 pén basin, pot",
  "碰见 碰見 pèngjiàn Meet",
  "披 披 pī drape over one`s shoulders",
  "批 批 pī batch",
  "批准 批准 pīzhǔn Approval",
  "皮鞋 皮鞋 píxié leather shoes",
  "疲劳 疲勞 píláo fatigue",
  "匹 一隻狗 pǐ Horse (meaure word)",
  "片 片 piàn slice",
  "片面 片面 piànmiàn one-sided",
  "飘 飄 piāo Gone with the wind",
  "频道 頻道 píndào channel",
  "品种 品種 pǐnzhǒng Varieties",
  "凭 憑 píng By",
  "平 平 píng flat",
  "平常 平常 píngcháng Usual",
  "平等 平等 píngděng equality",
  "平方 平方 píngfāng square",
  "平衡 平衡 pínghéng balance",
  "平静 平靜 píngjìng calm",
  "平均 平均 píngjūn Average",
  "评价 評價 píngjià evaluate",
  "破产 破產 pòchǎn bankruptcy",
  "破坏 破壞 pòhuài Destruction",
  "迫切 迫切 pòqiè urgent",
  "朴素 樸素 pǔsù simple",
  "期待 期待 qīdài expect",
  "期间 期間 qījiān Period",
  "其余 其餘 qíyú Rest",
  "奇迹 奇蹟 qíjì Miracle",
  "启发 啟發 qǐfā Inspire",
  "企图 企圖 qǐtú Attempt",
  "企业 企業 qǐyè enterprise",
  "气氛 氣氛 qìfēn atmosphere",
  "汽油 汽油 qìyóu gasoline",
  "牵 牽 qiān Pull",
  "谦虚 謙虛 qiānxū Modest",
  "签字 簽字 qiānzì Sign",
  "前途 前途 qiántú future",
  "浅 淺 qiǎn shallow",
  "欠 欠 qiàn owe",
  "枪 槍 qiāng gun",
  "强调 強調 qiángdiào Emphasize",
  "强烈 強烈 qiángliè strong",
  "抢 搶 qiǎng rob",
  "悄悄 悄悄 qiāoqiāo quietly",
  "瞧 瞧 qiáo look",
  "巧妙 巧妙 qiǎomiào clever",
  "切 切 qiē cut",
  "亲爱 親愛 qīn'ài Dear",
  "亲切 親切 qīnqiè kind",
  "亲自 親自 qīnzì personally",
  "侵略 侵略 qīnlüè aggression",
  "勤奋 勤奮 qínfèn hardworking",
  "勤劳 勤勞 qínláo industrious",
  "青 青 qīng young",
  "青春 青春 qīngchūn Youth",
  "青少年 青少年 qīngshàonián Teenagers",
  "轻视 輕視 qīngshì Despise",
  "清淡 清淡 qīngdàn light",
  "情景 情景 qíngjǐng scene",
  "情绪 情緒 qíngxù emotion",
  "请求 請求 qǐngqiú request",
  "庆祝 慶祝 qìngzhù Celebrate",
  "球迷 球迷 qiúmí fans",
  "趋势 趨勢 qūshì trend",
  "娶 娶 qǔ marry",
  "取消 取消 qǔxiāo cancel",
  "去世 去世 qùshì pass away",
  "圈 圈 quān circle",
  "全面 全面 quánmiàn comprehensive",
  "权力 權力 quánlì power",
  "权利 權利 quánlì right, interest",
  "劝 勸 quàn persuade",
  "缺乏 缺乏 quēfá Lack",
  "确定 確定 quèdìng Determine",
  "确认 確認 quèrèn confirm",
  "燃烧 燃燒 ránshāo burning",
  "嚷 嚷 rǎng Shout",
  "绕 繞 rào Around",
  "热爱 熱愛 rè'ài Ardently love",
  "热烈 熱烈 rèliè warm",
  "热心 熱心 rèxīn enthusiastic",
  "人才 人才 réncái talented people",
  "人口 人口 rénkǒu population",
  "人类 人類 rénlèi Human beings",
  "人生 人生 rénshēng Life",
  "人事 人事 rénshì Personnel matters",
  "人物 人物 rénwù character",
  "人员 人員 rényuán personnel",
  "忍不住 忍不住 rěnbuzhù Unable to bear",
  "日常 日常 rìcháng daily",
  "日程 議程 rìchéng schedule",
  "日历 日曆 rìlì calendar",
  "日期 日期 rìqī Date",
  "日用品 日用品 rìyòngpǐn Daily Necessities",
  "融化 融化 rónghuà thaw",
  "荣幸 榮幸 róngxìng To be honored",
  "荣誉 榮譽 róngyù Honor",
  "如何 如何 rúhé How",
  "如今 如今 rújīn nowadays",
  "软件 軟件 ruǎnjiàn Software",
  "弱 弱 ruò weak",
  "洒 灑 sǎ sprinkle",
  "嗓子 嗓子 sǎngzi throat",
  "杀 殺 shā kill",
  "沙漠 沙漠 shāmò Desert",
  "沙滩 沙灘 shātān beach",
  "傻 傻 shǎ silly",
  "晒 曬 shài The sun",
  "删除 刪除 shānchú delete",
  "闪电 閃電 shǎndiàn lightning",
  "善良 善良 shànliáng kind; virtuous",
  "善于 善於 shànyú be good at",
  "扇子 折扇 shànzi Fan",
  "商品 產品 shāngpǐn commodity",
  "商业 商業 shāngyè business",
  "上当 上當 shàngdàng When",
  "勺子 勺子 sháozi Spoon",
  "蛇 蛇 shé snake",
  "舌头 舌頭 shétou Tongue",
  "舍不得 捨不得 shěbude Hate to part with or use",
  "设备 設備 shèbèi equipment",
  "设计 設計 shèjì Design",
  "设施 設施 shèshī facilities",
  "射击 射擊 shèjī Shooting",
  "摄影 攝影 shèyǐng Photography",
  "伸 伸 shēn stretch",
  "深刻 深刻 shēnkè profound",
  "身材 身材 shēncái figure",
  "身份 身份 shēnfèn identity",
  "神话 神話 shénhuà Myth",
  "神经 神經 shénjīng nerve",
  "神秘 神秘 shénmì mysterious",
  "升 升 shēng rise",
  "生产 生產 shēngchǎn production",
  "生动 生動 shēngdòng vivid",
  "声调 聲調 shēngdiào Tone",
  "绳子 繩子 shéngzi Rope",
  "省略 省略 shěnglüè ellipsis",
  "胜利 勝利 shènglì victory",
  "诗 詩 shī poetry",
  "失眠 失眠 shīmián insomnia",
  "失去 失去 shīqù Lose",
  "失业 失業 shīyè Unemployment",
  "时代 時代 shídài times, epoch",
  "时刻 時刻 shíkè time",
  "时髦 時髦 shímáo Fashionable",
  "时期 時期 shíqī period",
  "时尚 時尚 shíshàng fashion",
  "实话 實話 shíhuà The truth",
  "实践 實踐 shíjiàn practice",
  "实习 實習 shíxí Internship",
  "实现 實現 shíxiàn Realization",
  "实行 實行 shíxíng Implement",
  "实验 實驗 shíyàn Experiment",
  "实用 實用 shíyòng Practical",
  "食物 食物 shíwù food",
  "石头 石頭 shítou stone",
  "使劲儿 使勁兒 shǐjìnr exert all one's strength",
  "始终 始終 shǐzhōng Throughout",
  "是否 是否 shìfǒu Whether",
  "试卷 試卷 shìjuàn test paper",
  "士兵 士兵 shìbīng soldiers",
  "似的 似的 shìde Likely",
  "事实 事實 shìshí Fact",
  "事物 事物 shìwù Thing",
  "事先 事先 shìxiān Prior",
  "收获 收穫 shōuhuò Harvest",
  "收据 收據 shōujù receipt",
  "手工 手工 shǒugōng manual",
  "手术 手術 shǒushù Operation",
  "手套 手套 shǒutào glove",
  "手续 手續 shǒuxù procedures",
  "手指 手指 shǒuzhǐ finger",
  "受伤 受傷 shòushāng Injured",
  "寿命 壽命 shòumìng Life",
  "书架 書架 shūjià bookshelf",
  "蔬菜 蔬菜 shūcài Vegetables",
  "舒适 舒適 shūshì Comfortable",
  "梳子 梳子 shūzi comb",
  "熟练 熟練 shúliàn skilled",
  "鼠标 鼠標 shǔbiāo mouse",
  "属于 屬於 shǔyú belong to",
  "数据 數據 shùjù data",
  "数码 數碼 shùmǎ Digital",
  "摔 摔 shuāi fall",
  "甩 甩 shuǎi Rejection",
  "双方 雙方 shuāngfāng both sides",
  "税 稅 shuì tax",
  "说不定 說不定 shuōbudìng maybe",
  "说服 說服 shuōfú Persuade",
  "撕 撕 sī tear",
  "丝绸 絲綢 sīchóu silk",
  "丝毫 絲毫 sīháo A bit",
  "思考 思考 sīkǎo Reflection",
  "思想 思想 sīxiǎng thought",
  "私人 私人 sīrén private",
  "似乎 似乎 sìhū It seems that",
  "寺庙 寺廟 sìmiào Temple",
  "宿舍 宿舍 sùshè dormitory",
  "随时 隨時 suíshí at any time",
  "碎 碎 suì broken",
  "损失 損失 sǔnshī loss",
  "缩短 縮短 suōduǎn Shorten",
  "缩小 縮小 suōxiǎo narrow",
  "锁 鎖 suǒ lock",
  "所 所 suǒ place",
  "所谓 所謂 suǒwèi So-called",
  "塔 塔 tǎ tower",
  "台阶 台階 táijiē Steps",
  "太极拳 太極拳 tàijíquán Taiji boxing",
  "太太 太太 tàitai Ma'am",
  "谈判 談判 tánpàn negotiation",
  "坦率 坦率 tǎnshuài frank",
  "烫 燙 tàng Hot",
  "桃 桃 táo peach",
  "逃 逃 táo flee",
  "逃避 逃避 táobì escape",
  "套 套 tào set",
  "特殊 特殊 tèshū special",
  "特意 特意 tèyì specially",
  "特征 特徵 tèzhēng Features",
  "疼爱 疼愛 téng'ài Love dearly",
  "提 提 tí carry",
  "提倡 提倡 tíchàng promote",
  "提纲 提綱 tígāng outline",
  "提问 提問 tíwèn Put questions to",
  "题目 題目 tímù subject",
  "体会 體會 tǐhuì Experience",
  "体积 體積 tǐjī volume",
  "体贴 體貼 tǐtiē Considerate",
  "体现 體現 tǐxiàn Reflect",
  "体验 體驗 tǐyàn experience",
  "天空 天空 tiānkōng sky",
  "天真 天真 tiānzhēn naive",
  "田野 田野 tiányě Field",
  "调皮 調皮 tiáopí naughty",
  "调整 調整 tiáozhěng adjustment",
  "挑战 挑戰 tiǎozhàn challenge",
  "通常 平時 tōngcháng usually",
  "通讯 通訊 tōngxùn communication",
  "铜 銅 tóng copper",
  "同时 同時 tóngshí meanwhile",
  "统一 統一 tǒngyī Unified",
  "统治 統治 tǒngzhì rule",
  "痛苦 痛苦 tòngkǔ Pain",
  "痛快 痛快 tòngkuài Happy, to one`s great satisfaction",
  "投资 投資 tóuzī Investment",
  "透明 透明 tòumíng transparent",
  "突出 突出 tūchū prominent",
  "土地 土地 tǔdì land",
  "土豆 土豆 tǔdòu Potato",
  "吐 吐 tù spit",
  "兔子 兔子 tùzi Rabbit",
  "团 團 tuán group",
  "推辞 推辭 tuīcí Refuse",
  "推广 推廣 tuīguǎng Extension",
  "推荐 推薦 tuījiàn Recommend",
  "退 退 tuì retreat",
  "退步 退步 tuìbù Backward",
  "退休 退休 tuìxiū retire",
  "歪 歪 wāi Crooked",
  "外交 外交 wàijiāo International Relations",
  "弯 彎 wān curved",
  "完美 完美 wánměi perfect",
  "完善 完善 wánshàn perfect",
  "完整 完整 wánzhěng complete",
  "玩具 玩具 wánjù Toys",
  "万一 萬一 wànyī In case",
  "王子 王子 wángzǐ prince",
  "往返 往返 wǎngfǎn Return",
  "危害 危害 wēihài Harm",
  "微笑 微笑 wēixiào Smile",
  "威胁 威脅 wēixié threaten",
  "违反 違反 wéifǎn Violation",
  "维护 維護 wéihù Maintain",
  "围巾 圍巾 wéijīn scarf",
  "围绕 圍繞 wéirào around",
  "唯一 唯一 wéiyī Only",
  "尾巴 尾巴 wěiba tail",
  "伟大 偉大 wěidà great",
  "委屈 委屈 wěiqu suffer from injustice",
  "委托 委託 wěituō Entrust",
  "胃 胃 wèi stomach",
  "位置 位置 wèizhì position",
  "未必 未必 wèibì not necessarily",
  "未来 未來 wèilái Future",
  "卫生间 衛生間 wèishēngjiān toilet",
  "温暖 溫暖 wēnnuǎn warm",
  "温柔 溫柔 wēnróu Tender",
  "闻 聞 wén smell",
  "文件 文件 wénjiàn file",
  "文具 文具 wénjù Stationery",
  "文明 文明 wénmíng civilization",
  "文学 文學 wénxué literature",
  "吻 吻 wěn kiss",
  "稳定 穩定 wěndìng Stable",
  "问候 問候 wènhòu To greet",
  "卧室 臥室 wòshì Bedroom",
  "屋子 屋子 wūzi House",
  "无奈 無奈 wúnài have no choice",
  "无数 無數 wúshù Countless",
  "武器 武器 wǔqì arms",
  "武术 武術 wǔshù A martial art",
  "雾 霧 wù Fog",
  "物理 物理 wùlǐ Physics",
  "物质 物質 wùzhì material",
  "吸收 吸收 xīshōu absorb",
  "系 系 xì department",
  "系统 系統 xìtǒng system",
  "细节 細節 xìjié details",
  "戏剧 戲劇 xìjù drama",
  "瞎 瞎 xiā blind",
  "吓 嚇 xià scare",
  "下载 下載 xiàzài download",
  "鲜艳 鮮豔 xiānyàn Colorful",
  "显得 顯得 xiǎnde Appear, seem",
  "显然 顯然 xiǎnrán Obviously",
  "显示 顯示 xiǎnshì display",
  "县 縣 xiàn county",
  "现金 現金 xiànjīn cash",
  "现实 現實 xiànshí reality",
  "现象 現象 xiànxiàng phenomenon",
  "相处 相處 xiāngchǔ Get along with",
  "相当 相當 xiāngdāng Quite",
  "相对 相對 xiāngduì Relative",
  "相关 相關 xiāngguān correlate",
  "相似 相似 xiāngsì Be similar",
  "想念 想念 xiǎngniàn miss",
  "想象 想像 xiǎngxiàng imagine",
  "享受 享受 xiǎngshòu enjoy",
  "项 項 xiàng term",
  "项链 項鍊 xiàngliàn Necklace",
  "项目 項目 xiàngmù project",
  "橡皮 橡皮 xiàngpí rubber",
  "象棋 象棋 xiàngqí Xiangqi",
  "象征 象徵 xiàngzhēng Symbolize",
  "消费 消費 xiāofèi consumption",
  "消化 消化 xiāohuà Digestion",
  "消灭 消滅 xiāomiè eliminate",
  "消失 消失 xiāoshī disappear",
  "销售 銷售 xiāoshòu Sale",
  "小吃 小吃 xiǎochī snack",
  "小伙子 小伙子 xiǎohuǒzi Young fellow",
  "小麦 小麥 xiǎomài Wheat",
  "小气 小氣 xiǎoqi Mean",
  "小偷 小偷 xiǎotōu Thief",
  "效率 效率 xiàolǜ efficiency",
  "孝顺 孝順 xiàoshun Filial piety",
  "歇 歇 xiē Rest",
  "斜 斜 xié oblique",
  "协调 協調 xiétiáo coordinate",
  "心理 心理 xīnlǐ Psychology",
  "心脏 心臟 xīnzàng heart",
  "欣赏 欣賞 xīnshǎng Appreciate",
  "信封 信封 xìnfēng envelope",
  "信号 信號 xìnhào signal",
  "信息 信息 xìnxī information",
  "行动 行動 xíngdòng Get some action",
  "行人 行人 xíngrén pedestrian",
  "行为 行為 xíngwéi behavior",
  "形成 形成 xíngchéng formation",
  "形容 形容 xíngróng describe",
  "形式 形式 xíngshì form",
  "形势 形勢 xíngshì situation",
  "形象 形象 xíngxiàng image",
  "形状 形狀 xíngzhuàng shape",
  "性质 性質 xìngzhì Nature",
  "幸亏 幸虧 xìngkuī Thanks",
  "幸运 幸運 xìngyùn lucky",
  "胸 乳房 xiōng chest",
  "兄弟 兄弟 xiōngdì Brother",
  "雄伟 雄偉 xióngwěi Magnificent",
  "修改 修改 xiūgǎi modify",
  "休闲 休閒 xiūxián Leisure time",
  "虚心 虛心 xūxīn With an open mind, modest",
  "叙述 敘述 xùshù Narration",
  "宣布 宣布 xuānbù Announce",
  "宣传 宣傳 xuānchuán Propaganda",
  "选举 選舉 xuǎnjǔ Election",
  "学期 學期 xuéqī Semester",
  "学术 學術 xuéshù learning",
  "学问 學問 xuéwen knowledge",
  "询问 詢問 xúnwèn inquiry",
  "寻找 尋找 xúnzhǎo Seek, look for",
  "训练 訓練 xùnliàn training",
  "迅速 迅速 xùnsù rapid",
  "延长 延長 yáncháng extend",
  "严肃 嚴肅 yánsù serious",
  "宴会 宴會 yànhuì banquet",
  "阳台 陽台 yángtái balcony",
  "痒 癢 yǎng itch",
  "样式 樣式 yàngshì style",
  "腰 腰 yāo waist",
  "摇 搖 yáo shake",
  "咬 咬 yǎo bite",
  "要不 要不 yàobù Or",
  "要是 要是 yàoshi If",
  "夜 夜 yè night",
  "液体 液體 yètǐ liquid",
  "业务 業務 yèwù business",
  "业余 業餘 yèyú amateur",
  "依然 依然 yīrán still",
  "一辈子 一輩子 yíbèizi A lifetime",
  "一旦 一旦 yídàn once; in case",
  "一路平安 一路平安 yílùpíng'ān Bon Voyage",
  "一致 一致 yízhì Agreement",
  "移动 移動 yídòng move",
  "移民 移民 yímín immigrant",
  "遗憾 遺憾 yíhàn pity",
  "疑问 疑問 yíwèn Doubt",
  "以及 以及 yǐjí as well as",
  "以来 以來 yǐlái Since",
  "意外 意外 yìwài Accident",
  "意义 意義 yìyì Significance",
  "议论 議論 yìlùn Discussion",
  "义务 義務 yìwù obligation",
  "因而 因而 yīn'ér thus",
  "因素 因素 yīnsù Factor",
  "银 銀 yín silver",
  "英俊 英俊 yīngjùn Handsome and spirited",
  "英雄 英雄 yīngxióng Hero",
  "迎接 迎接 yíngjiē meet, welcome",
  "营养 營養 yíngyǎng Nutrition",
  "营业 營業 yíngyè Do business",
  "影子 影子 yǐngzi shadow",
  "硬币 硬幣 yìngbì Coin",
  "硬件 硬件 yìngjiàn Hardware",
  "应付 應付 yìngfu cope with",
  "应聘 應聘 yìngpìn Apply for",
  "应用 應用 yìngyòng application",
  "拥抱 擁抱 yōngbào embrace",
  "拥挤 擁擠 yōngjǐ Crowded",
  "勇气 勇氣 yǒngqì courage",
  "用途 用途 yòngtú purpose",
  "优惠 優惠 yōuhuì preferential; favorable",
  "优美 優美 yōuměi Graceful",
  "优势 優勢 yōushì advantage",
  "悠久 悠久 yōujiǔ long",
  "邮局 郵局 yóujú Post Office",
  "游览 遊覽 yóulǎn visit",
  "犹豫 猶豫 yóuyù hesitate",
  "油炸 油炸 yóuzhá Fried",
  "有利 有利 yǒulì favourable, beneficial",
  "幼儿园 幼兒園 yòu'éryuán Kindergarten",
  "娱乐 娛樂 yúlè entertainment",
  "与其 與其 yǔqí Rather than",
  "语气 語氣 yǔqì tone",
  "宇宙 宇宙 yǔzhòu universe",
  "预报 預報 yùbào prediction",
  "预订 預訂 yùdìng book; subscribe for",
  "预防 預防 yùfáng Prevention",
  "玉米 玉米 yùmǐ Corn",
  "元旦 元旦 uándàn New year's Day",
  "缘故 緣故 yuángù Reason",
  "原料 原料 yuánliào raw material",
  "原则 原則 yuánzé Principle",
  "愿望 願望 yuànwàng desire, wish",
  "晕 暈 yūn faint",
  "运气 運氣 yùnqi luck",
  "运输 運輸 yùnshū transport",
  "运用 運用 yùnyòng Application",
  "灾害 災害 zāihài disaster",
  "再三 再三 zàisān repeatedly",
  "赞成 贊成 zànchéng Agreement",
  "赞美 讚美 zànměi Praise",
  "糟糕 糟糕 zāogāo Too bad",
  "造成 造成 zàochéng cause",
  "则 則 zé be",
  "责备 責備 zébèi Reproach",
  "摘 摘 zhāi pick",
  "粘贴 粘貼 zhāntiē paste",
  "展开 展開 zhǎnkāi Open",
  "展览 展覽 zhǎnlǎn exhibition",
  "占线 佔線 zhànxiàn (line) Busy",
  "战争 戰爭 zhànzhēng War",
  "涨 漲 zhǎng rise",
  "掌握 掌握 zhǎngwò master",
  "账户 賬戶 zhànghù account",
  "招待 請帖 zhāodài Entertain",
  "着凉 著涼 zháoliáng get cold",
  "召开 召開 zhàokāi convene",
  "照常 照常 zhàocháng as usual",
  "哲学 哲學 zhéxué Philosophy",
  "真理 真理 zhēnlǐ Truth",
  "真实 真實 zhēnshí real",
  "针对 針對 zhēnduì aim at",
  "珍惜 珍惜 zhēnxī cherish",
  "诊断 診斷 zhěnduàn Diagnosis",
  "枕头 枕頭 zhěntou Pillow",
  "阵 陣 zhèn front",
  "振动 振動 zhèndòng Vibration",
  "睁 睜 zhēng open (eyes)",
  "争论 爭論 zhēnglùn debate",
  "争取 爭取 zhēngqǔ strive for",
  "征求 徵求 zhēngqiú ask for",
  "整个 整個 zhěnggè Whole",
  "整体 整體 zhěngtǐ Whole",
  "正 正 zhèng just",
  "政策 政策 zhèngcè policy",
  "政府 政府 zhèngfǔ government",
  "政治 政治 zhèngzhì Politics",
  "证件 證件 zhèngjiàn Certificates",
  "证据 證據 zhèngjù evidence",
  "挣钱 掙錢 zhèngqián Earn money",
  "支 支 zhī branch (measure word)",
  "支票 支票 zhīpiào Check",
  "直 直 zhí straight",
  "执行 執行 zhíxíng implement",
  "执照 執照 zhízhào License",
  "指导 指導 zhǐdǎo guidance",
  "指挥 指揮 zhǐhuī command",
  "制定 制定 zhìdìng Formulate",
  "制度 制度 zhìdù system",
  "制作 製作 zhìzuò Make",
  "智慧 智慧 zhìhuì wisdom",
  "至今 到現在為止 zhìjīn so far",
  "至于 至於 zhìyú As for",
  "治疗 治療 zhìliáo Treatment",
  "秩序 秩序 zhìxù order",
  "志愿者 志願者 zhìyuànzhě Volunteer",
  "钟 鐘 zhōng clock",
  "中介 中介 zhōngjiè intermediary",
  "中心 中心 zhōngxīn core",
  "中旬 中旬 zhōngxún Mid",
  "重 重 zhòng heavy",
  "重量 重量 zhòngliàng weight",
  "周到 周到 zhōudào thoughtful",
  "逐步 逐步 zhúbù gradually",
  "竹子 竹子 zhúzi Bamboo",
  "煮 煮 zhǔ cook",
  "主持 主持 zhǔchí Host",
  "主观 主觀 zhǔguān subjective",
  "主人 主人 zhǔrén master",
  "主席 主席 zhǔxí Chairman",
  "主张 主張 zhǔzhāng opinion",
  "嘱咐 囑咐 zhǔfù Charge",
  "祝福 祝福 zhùfú blessing",
  "注册 註冊 zhùcè register",
  "抓紧 抓緊 zhuājǐn Pay close attention to, grasp",
  "专家 專家 zhuānjiā expert",
  "专心 專心 zhuānxīn Attentively",
  "转变 轉變 zhuǎnbiàn change",
  "转告 轉告 zhuǎngào Tell, transmit",
  "装 裝 zhuāng pretend",
  "装饰 裝飾 zhuāngshì decorate",
  "状况 狀況 zhuàngkuàng status",
  "状态 狀態 zhuàngtài state",
  "追求 追求 zhuīqiú Pursuit",
  "资格 資格 zīgé Qualifications",
  "资金 資金 zījīn capital",
  "资料 資料 zīliào data",
  "资源 資源 zīyuán Resources",
  "姿势 姿勢 zīshì posture",
  "咨询 諮詢 zīxún Consultation",
  "紫 紫 zǐ purple",
  "字幕 字幕 zìmù Subtitle",
  "自从 自從 zìcóng Since",
  "自动 自動 zìdòng automatic",
  "自豪 自豪 zìháo Proud",
  "自觉 自覺 zìjué Conscious",
  "自私 自私 zìsī selfish",
  "自信 自信 zìxìn self-confidence",
  "自由 自由 zìyóu free",
  "自愿 自願 zìyuàn voluntarily",
  "综合 綜合 zōnghé comprehensive",
  "宗教 宗教 zōngjiào Religion",
  "总裁 總裁 zǒngcái CEO",
  "总共 總共 zǒnggòng In total",
  "总理 總理 zǒnglǐ prime minister",
  "总算 總算 zǒngsuàn finally",
  "总统 總統 zǒngtǒng President",
  "总之 總之 zǒngzhī in short, in brief",
  "组合 組合 zǔhé combination",
  "祖国 祖國 zǔguó Motherland",
  "祖先 祖先 zǔxiān Ancestors",
  "阻止 阻止 zǔzhǐ prevent",
  "醉 醉 zuì drunk",
  "最初 第一 zuìchū First, at the beginning",
  "罪犯 罪犯 zuìfàn Criminal",
  "尊敬 尊敬 zūnjìng respect",
  "遵守 遵守 zūnshǒu comply with",
  "作品 作品 zuòpǐn works",
  "作为 作為 zuòwéi As",
  "作文 作文 zuòwén composition",
];
