import fs from "fs";

const list: ReadonlyArray<string> = [
  "一 yī one",
  "二 èr two",
  "三 sān three",
  "四 sì four",
  "五 wǔ five",
  "六 liù six",
  "七 qī seven",
  "八 bā eight",
  "九 jiǔ nine",
  "十 shí ten",
  "零 líng zero",
  "两 liǎng two",
  "百 bǎi hundred",
  "千 qiān thousand",
  "第一 dìyī first",
  "Quantifier",
  "个 gè one, a, an",
  "岁 suì year",
  "本 běn volume",
  "些 xiē some",
  "块 kuài piece",
  "次 cì number",
  "公斤 gōngjīn kilogram",
  "元 yuán yuan",
  "件 jiàn piece",
  "张 zhāng sheet",
  "Adverb",
  "不 bù no",
  "没 méi no",
  "很 hěn quite, very",
  "太 tài too",
  "都 dōu all",
  "别 bié other",
  "非常 fēicháng very",
  "也 yě likewise",
  "还 hái still",
  "最 zuì most",
  "真 zhēn real",
  "正在 zhèngzài be being",
  "2",
  "已经 yǐjīng already",
  "一起 yìqǐ together",
  "再 zài again",
  "就 jiǜ at once",
  "Conjunction",
  "和 hé and",
  "因为 yīnwèi because",
  "所以 suǒyǐ so",
  "但是 dànshì but",
  "Preposition",
  "在 zài in, at",
  "从 cóng from",
  "对 duì right",
  "此 cǐ this",
  "向 xiàng towards",
  "离 lí leave",
  "Auxiliary",
  "的 de",
  "了 le",
  "吗 ma",
  "呢 ne",
  "得 dé",
  "着 zhe",
  "过 guò",
  "吧 ba",
  "Interjection",
  "喂 wèi hello",
  "Noun",
  "家 jiā home",
  "学校 xuéxiào school",
  "饭馆 fàndiàn restaunt",
  "商店 shāngdiàn store",
  "医院 yīyuàn hospital",
  "火车站 huǒchēzhàn train station",
  "中国 Zhōngguó China",
  "机场 jīchǎng airport",
  "3",
  "教室 jiàoshì classroom",
  "房间 fángjiān room",
  "路 lù road",
  "北京 Běijīng Beijing",
  "上 shàng up",
  "下 xià below",
  "前面 qiánmiàn front",
  "后面 hòumiàn behind",
  "左边 zuǒbiān left",
  "右边 yòubiān right",
  "外 wài out",
  "旁边 pángbiān side",
  "里 lǐ inside",
  "今天 jīntiān today",
  "明天 míngtiān tomorrow",
  "昨天 zuótiān yesterday",
  "上午 shàngwǔ morning",
  "中午 zhōngwǔ noon",
  "下午 xiàwǔ afternoon",
  "年 nián year",
  "月 yuè month",
  "日 rì day",
  "星期 xīngqī week",
  "点 diǎn dot, spot",
  "分钟 fēnzhōng minute",
  "现在 xiànzài now",
  "时候 shíhou time",
  "早上 zǎoshàng morning",
  "晚上 wǎnshàng night",
  "小时 xiǎoshí hour",
  "时间 shíjiān time",
  "去年 qùnián last year",
  "号 hào number",
  "生日 shēngrì birthday",
  "爸爸 bàba father",
  "妈妈 māma mother",
  "4",
  "儿子 érzi son",
  "女儿 nǚ'ér daughter",
  "老师 lǎoshī teacher",
  "学生 xuéshēng student",
  "同学 tóngxué shoolmate",
  "朋友 péngyǒu friend",
  "医生 yīshēng doctor",
  "先生 xiānsheng sir",
  "小姐 xiǎojiě Miss",
  "哥哥 gēge older brother",
  "姐姐 jiějie older sister",
  "弟弟 dìdi younger brother",
  "妹妹 mèimei younger sister",
  "丈夫 zhàngfu husband",
  "妻子 qīzi wife",
  "孩子 háizi child",
  "男人 nánrén man",
  "女人 nǚrén woman",
  "服务员 fúwùyuán waiter",
  "衣服 yīfu cloth",
  "水 shuǐ water",
  "菜 cài dish",
  "米饭 mǐfàn rice",
  "水果 shuǐguǒ fruit",
  "苹果 píngguǒ apple",
  "茶 chá tea",
  "杯子 bēizi cup",
  "钱 qián money",
  "飞机 fēijī airplane",
  "出租车 chūzūchē taxi",
  "电视 diànshì television",
  "电脑 diànnǎo computer",
  "电影 diànyǐng movie",
  "天气 tiānqì weather",
  "猫 māo cat",
  "狗 gǒu dog",
  "5",
  "东西 dōngxi thing",
  "鱼 yú fish",
  "羊肉 yángròu mutton",
  "牛奶 niúnǎi milk",
  "鸡蛋 jīdàn egg",
  "西瓜 xīguā watermelon",
  "咖啡 kāfēi coffee",
  "自行车 zìxíngchē bike",
  "船 chuán boat",
  "雪 xuě snow",
  "药 yào medicine",
  "手机 shǒujī cellphone",
  "手表 shǒubiǎo watch",
  "眼睛 yǎnjīng eye",
  "身体 shēntǐ body",
  "公共汽车 gōnggòngqìchē bus",
  "报纸 bàozhǐ newspaper",
  "人 rén person",
  "名字 míngzì name",
  "书 shū book",
  "汉语 hànyǔ Chinese",
  "字 zì character",
  "桌子 zhuōzi desk",
  "椅子 yǐzi chair",
  "门 mén door",
  "题 tí topic",
  "课 kè lesson",
  "姓 xìng surname",
  "问题 wèntí question",
  "事情 shìqing matter",
  "考试 kǎoshì exam",
  "票 piào ticket",
  "意思 yìsi meaning",
  "颜色 yánsè color",
  "Verb",
  "谢谢 xièxie thank",
  "6",
  "不客气 búkèqì you are welcome",
  "再见 zàijiàn good-bye",
  "请 qǐng please",
  "对不起 duìbùqǐ sorry",
  "没关系 méiguānxi It doesn't matter",
  "欢迎 huānyíng welcome",
  "是 shì am, is, are",
  "有 yǒu have",
  "看 kàn look",
  "听 tīng listen",
  "说话 shuōhuà speak",
  "读 dú read",
  "写 xiě write",
  "看见 kànjiàn see",
  "叫 jiào call",
  "来 lái come",
  "回 huí return",
  "去 qù go",
  "吃 chī eat",
  "喝 hē drink",
  "睡觉 shuìjiào sleep",
  "打电话 dǎdiànhuà call up",
  "做 zuò do",
  "买 mǎi buy",
  "开 kāi open",
  "坐 zuò sit",
  "住 zhù live",
  "学习 xuéxí study",
  "工作 gōngzuò work",
  "下雨 xiàyǔ rain",
  "问 wèn ask",
  "走 zǒu walk",
  "进 jìn enter",
  "出 chū come",
  "跑步 pǎobù run",
  "到 dào arrive",
  "7",
  "穿 chuān wear",
  "洗 xǐ wash",
  "给 gěi give",
  "找 zhǎo find",
  "懂 dǒng understand",
  "笑 xiào smile",
  "回答 huídá answer",
  "告诉 gàosù tell",
  "准备 zhǔnbèi prepare",
  "开始 kāishǐ begin",
  "介绍 jièshào introduce",
  "帮助 bāngzhù help",
  "玩 wán play",
  "送 sòng present",
  "等 děng wait",
  "让 ràng let",
  "起床 qǐchuáng get up",
  "唱歌 chànggē sing",
  "跳舞 tiàowǔ dance",
  "旅游 lǚyóu travel",
  "上班 shàngbān be on duty",
  "生病 shēngbìng fall ill",
  "休息 xiūxi rest",
  "运动 yùndòng exercise",
  "游泳 yóuyǒng swim",
  "踢足球 tīzúqiú play footbal",
  "打篮球 dǎlánqiú play basketball",
  "完 wán finish",
  "爱 ài love",
  "喜欢 xǐhuān love, like",
  "想 xiǎng want",
  "认识 rènshi know",
  "觉得 juédé think",
  "知道 zhīdao know",
  "希望 xīwàng hope",
  "会 huì can",
  "8",
  "能 néng can, be able to",
  "可以 kěyǐ can",
  "要 yào ask for",
  "可能 kěnéng may",
  "Adjective",
  "好 hǎo good",
  "大 dà big",
  "小 xiǎo small",
  "多 duō many, much",
  "少 shǎo few, little",
  "冷 lěng cold",
  "热 rè hot",
  "高兴 gāoxìng happy",
  "漂亮 piàoliang beautiful",
  "高 gāo tall",
  "红 hóng red",
  "白 bái white",
  "黑 hēi black",
  "忙 máng busy",
  "快 kuài fast",
  "慢 màn slow",
  "远 yuǎn far",
  "近 jìn close",
  "好吃 hǎochī delicioous",
  "累 lèi tired",
  "长 cháng long",
  "新 xīn new",
  "贵 guì expensive",
  "便宜 piányi cheap",
  "晴 qíng fine",
  "阴 yīn cloudy",
  "错 cuò wrong",
  "快乐 kuàilè happy",
];

const createItemLiteral = (
  simplified: string,
  traditional: string,
  pinyin: string,
  english: string,
) => {
  return `Item { simplified: "${simplified}", traditional: "${traditional}", pinyin: "${pinyin}", english: "${english}", english_alternate_choices: vec![""], }`;
};

const translateSimplifiedCharactersToTraditional = async (
  simplified: string,
) => {
  return simplified;
};

const parseList = (vocabulary: ReadonlyArray<string>) => {
  const parsedList = vocabulary
    .filter(line => line.split(" ").length > 2)
    .map(async line => {
      const [simplified, pinyin = "", english = ""] = line.split(" ");
      const traditional = await translateSimplifiedCharactersToTraditional(
        simplified,
      );
      return createItemLiteral(simplified, traditional, pinyin, english);
    });

  const lessonSize = 25;
  let result: ReadonlyArray<ReadonlyArray<string>> = [];

  for (let i = 0; i < parsedList.length; i += lessonSize) {
    // @ts-ignore
    result = result.concat([parsedList.slice(i, i + lessonSize)]);
  }

  return result;
};

const writeListToJson = (result: ReadonlyArray<ReadonlyArray<string>>) => {
  console.log("\nWriting JSON result...");
  const data = JSON.stringify({ lists: result });
  fs.writeFileSync("vocabulary.json", data, "utf8");
  console.log("\nFinished!\n");
};

const processWords = () => {
  console.log("\nProcessing words...");
  const parsedResult = parseList(list);
  writeListToJson(parsedResult);
};

processWords();
